import type { EventRealityEvaluation, SourceProvenance } from '../expectation-reality/contracts';
import type { HistoricalAnalogRetrievalResult } from '../historical-analog-memory/contracts';
import type { CleanlinessEvidenceReference, MarketCleanlinessComponent, MarketCleanlinessEvaluation, MarketSessionLiquidityContextRecord, CleanlinessComponentName, HardConflictFlag } from './contracts';
import { cleanlinessHash, cleanlinessId, immutableCleanliness } from './identity';
import { MANDATORY_DIRECT_COMPONENTS, MARKET_CLEANLINESS_POLICY_VERSION, MARKET_CLEANLINESS_WEIGHTS, roundScore, stageOrder } from './policy';

export type MarketCleanlinessEvidence = { event:EventRealityEvaluation; analog:HistoricalAnalogRetrievalResult|null; session:MarketSessionLiquidityContextRecord|null; evidenceCutoffAt:string };
const validTime=(at:string,cutoff:string)=>Number.isFinite(Date.parse(at))&&Date.parse(at)<=Date.parse(cutoff);
const eligible=(p:SourceProvenance)=>p.reliability==='verified'||(p.reliability==='replay'&&Boolean(p.verificationRef&&p.trustBasis&&p.verifiedAt));
const ref=(sourceType:string,sourceId:string,contentHash:string,observedAt:string,availableAt:string,reliability:CleanlinessEvidenceReference['reliability']):CleanlinessEvidenceReference=>({sourceType,sourceId,contentHash,observedAt,availableAt,reliability});
const component=(name:CleanlinessComponentName, availability:MarketCleanlinessComponent['availability'], score:number|null, reasonCodes:string[], rationale:string, refs:CleanlinessEvidenceReference[]=[], warnings:string[]=[], limitations:string[]=[]):MarketCleanlinessComponent=>({component:name,availability,status:score===null?'insufficient':score>=80?'supportive':score>=55?'neutral':score>=30?'conflicting':'severely_conflicting',score,weight:MARKET_CLEANLINESS_WEIGHTS[name],effectiveWeight:availability==='available'&&score!==null?MARKET_CLEANLINESS_WEIGHTS[name]:0,sourceReferences:refs,reasonCodes,warnings,limitations,rationale});
const phaseFor=(event:EventRealityEvaluation)=>event.assessmentStage==='immediate'?event.reality.priceReactionTimeline.immediate:event.assessmentStage==='confirmation'?event.reality.priceReactionTimeline.confirmation:event.reality.priceReactionTimeline.followThrough;
const resolved=(event:EventRealityEvaluation)=>event.reality.releaseAlignment.actualDirection;
const directional=(d:unknown):d is 'bullish'|'bearish'=>d==='bullish'||d==='bearish';

export function evaluateMarketCleanliness(input:MarketCleanlinessEvidence):MarketCleanlinessEvaluation {
 const {event,analog,session,evidenceCutoffAt}=input; if(!validTime(event.interpretedAt,evidenceCutoffAt)||!validTime(event.createdAt,evidenceCutoffAt)) throw new Error('event_evidence_after_cleanliness_cutoff');
 if(analog&&(analog.queryEventEvaluationId!==event.eventEvaluationId||!validTime(analog.queryCutoffAt,evidenceCutoffAt)||!validTime(analog.createdAt,evidenceCutoffAt))) throw new Error('analog_cutoff_or_lineage_mismatch');
 if(session&&(session.eventEvaluationId!==event.eventEvaluationId||session.asset!==event.asset||session.evidenceCutoffAt!==evidenceCutoffAt)) throw new Error('session_context_lineage_mismatch');
 if(session&&(!validTime(session.observedAt,evidenceCutoffAt)||!validTime(session.availableAt,evidenceCutoffAt)||!validTime(session.createdAt,evidenceCutoffAt))) throw new Error('session_context_after_cleanliness_cutoff');
 const references:CleanlinessEvidenceReference[]=[]; const releaseReliability=event.reality.provenance.map(p=>p.effectiveReliability??p.reliability); event.reality.provenance.forEach(p=>references.push(ref('release',p.sourceId,p.contentHash??event.assessmentEvidenceHash,event.reality.observedAt,p.verifiedAt??event.reality.observedAt,p.reliability)));
 event.reactionProvenance.forEach(p=>references.push(ref('price_reaction',p.sourceId,p.calculatedContentHash??p.suppliedContentHash??event.observationContentHash,event.interpretedAt,p.verifiedAt??event.interpretedAt,p.reliability)));
 const directProvenance=[...event.reality.provenance,...event.reactionProvenance]; const provenanceOkay=directProvenance.length>0&&directProvenance.every(eligible);
 const releaseStatus=event.reality.releaseAlignment.status; const releaseClear=releaseStatus==='aligned'||releaseStatus==='contradicted'||releaseStatus==='inline';
 const release=component('release_clarity',releaseClear?'available':'unavailable',releaseClear?(releaseStatus==='inline'?82:94):null,[`release_${releaseStatus}`],'Clarity measures the resolved release interpretation, not agreement with the frozen expectation.',references.filter(r=>r.sourceType==='release'),[],releaseClear?[]:['release_interpretation_unresolved']);
 const primary=event.reality.primaryPriceReaction; const releaseDirection=resolved(event); const primaryConflict=directional(releaseDirection)&&directional(primary.observedDirection)&&releaseDirection!==primary.observedDirection; const primaryAmbiguous=['ambiguous','reversed','insufficient_data','unknown'].includes(primary.status)||!directional(primary.observedDirection);
 const primaryScore=primaryAmbiguous?(primary.status==='reversed'?20:null):primaryConflict?15:Math.max(55,Math.min(96,90-primary.absorptionScore*.25-primary.wickRejectionScore*.15));
 const primaryComponent=component('primary_reaction_coherence',primaryScore===null?'unavailable':'available',primaryScore,[`primary_${primary.status}`],primaryConflict?'The decisive primary response opposes the resolved release direction.':'The primary response is assessed against resolved release direction, independently of the frozen expectation.',references.filter(r=>r.sourceType==='price_reaction'),primary.warnings,primaryScore===null?['primary_direction_unresolved']:[]);
 const phase=phaseFor(event); const pathStructural=event.assessmentStage==='immediate'; const twoSided=event.reasonCodes.includes('two_sided_expansion')||event.reasonCodes.includes('two_sided_whipsaw'); const pathBad=event.reality.priceReactionTimeline.initialConfirmationThenReversal||event.reality.priceReactionTimeline.acceptanceLostTimestamp!==null||event.reality.priceReactionTimeline.reversalTimestamp!==null||twoSided; const pathScore=pathStructural?null:phase.state==='insufficient_data'||phase.state==='unknown'?null:pathBad?15:['confirmed','rejected'].includes(phase.state)?92:['absorbed','delayed'].includes(phase.state)?55:30;
 const path=component('path_continuity',pathStructural?'structurally_unavailable':pathScore===null?'unavailable':'available',pathScore,[`path_${phase.state}`],pathStructural?'Later path evidence is not mature at the immediate stage.':'Only the current assessment-stage timeline is used.',[],phase.warnings,pathScore===null&&!pathStructural?['current_stage_path_unavailable']:[]);
 const relatedDecision=event.reality.relatedEvidenceDecision.status; const relatedStructural=event.assessmentStage==='immediate'||relatedDecision==='not_required'; const relatedScore=relatedStructural?null:relatedDecision==='confirmed'?94:relatedDecision==='conflicting_final'?5:null;
 const related=component('related_market_coherence',relatedStructural?'structurally_unavailable':relatedScore===null?'unavailable':'available',relatedScore,[`related_${relatedDecision}`],relatedDecision==='not_required'?'Canonical policy excludes related markets from expected weight.':'Canonical related-market closure is retained; missing evidence never confirms cleanliness.',[],[],relatedScore===null&&!relatedStructural?['related_market_evidence_unavailable']:[]);
 const envelope=event.reality.priceReactionTimeline.primaryObservation; const volatilityValid=typeof envelope.reactionInput.volatilityBasisPct==='number'&&envelope.reactionInput.volatilityBasisPct>0&&Number.isFinite(primary.volatilityAdjustedMove)&&!primary.warnings.includes('volatility_basis_missing'); const volatileConflict=twoSided||primary.warnings.includes('outlier_move')&&primary.reversalScore>=50;
 const volatility=component('volatility_interpretability',volatilityValid?'available':'unavailable',volatilityValid?(volatileConflict?25:primary.warnings.includes('outlier_move')?72:90):null,[volatilityValid?'pre_event_volatility_valid':'pre_event_volatility_missing'],volatilityValid?'The persisted pre-event basis makes reaction magnitude interpretable.':'No valid pre-event volatility basis is persisted.',references.filter(r=>r.sourceType==='price_reaction'),primary.warnings,volatilityValid?[]:['volatility_context_required']);
 let sessionScore:number|null=null; if(session&&session.marketState!=='unknown'&&session.marketState!=='closed'&&session.liquidityState!=='unknown'&&session.spreadState!=='unknown'){sessionScore=95; if(session.sessionState==='off_hours')sessionScore-=25;if(session.liquidityState==='thin')sessionScore-=25;if(session.liquidityState==='stressed')sessionScore-=45;if(session.spreadState==='wide')sessionScore-=25;if(session.activityState==='depressed')sessionScore-=10; sessionScore=Math.max(10,sessionScore);}
 const sessionEligible=Boolean(session&&session.provenance.length&&session.provenance.every(eligible)); if(session)session.provenance.forEach(p=>references.push(ref('session_liquidity',p.sourceId,p.contentHash??session.canonicalPayloadHash,session.observedAt,session.availableAt,p.reliability)));
 const sessionComponent=component('session_liquidity_quality',!session||sessionScore===null?'unavailable':sessionEligible?'available':'provenance_limited',sessionEligible?sessionScore:null,[session?'persisted_session_context':'session_context_missing'],session?'Only the persisted session/liquidity record is assessed.':'Session and liquidity conditions remain explicitly unavailable.',references.filter(r=>r.sourceType==='session_liquidity'),session?.warnings?[...session.warnings]:[],session?[...session.limitations,...(!sessionEligible?['session_provenance_limited']:[])]:['session_context_unavailable']);
 let analogScore:number|null=null; let analogAvailability:MarketCleanlinessComponent['availability']='unavailable'; if(analog){ const stageSafe=analog.queryElapsedMs>=0&&analog.memorySnapshot.every(m=>m.selectedStageAssessmentStageOrder<=stageOrder(event.assessmentStage)); if(!stageSafe)throw new Error('future_stage_analog_evidence'); if(analog.evidenceSufficiency==='sufficient'&&analog.eligibleUniqueEventCount>=3&&analog.matches.length>=3){ const states=analog.matches.map(m=>m.historicalOutcomeContext.finalPricePathState); const concentration=Math.max(...[...new Set(states)].map(s=>states.filter(x=>x===s).length))/states.length; analogScore=roundScore(45+50*concentration); analogAvailability=analog.matches.some(m=>m.sourceProvenanceSummary.datasetClass==='fixture'||m.sourceProvenanceSummary.datasetClass==='unverified')?'provenance_limited':'available'; if(analogAvailability==='provenance_limited')analogScore=null; } }
 const analogComponent=component('analog_consistency',analogAvailability,analogScore,[analog?`analog_${analog.evidenceSufficiency}`:'analog_not_supplied'],'Historical path-state concentration is context only; outcomes are never used to override direct evidence.',[],analog?.warnings??[],analog?.limitations??['no_comparable_history']);
 const provenance=component('provenance_quality',provenanceOkay?'available':'provenance_limited',provenanceOkay?95:null,[provenanceOkay?'required_provenance_eligible':'required_provenance_limited'],'Verified or certified replay evidence may support cleanliness; fixture and unverified evidence cannot.',references,[],provenanceOkay?[]:[`required_classes:${releaseReliability.join(',')}`]);
 const components=[release,primaryComponent,path,related,volatility,sessionComponent,analogComponent,provenance];
 const expected=components.filter(c=>c.availability!=='structurally_unavailable'); const expectedWeight=expected.reduce((n,c)=>n+c.weight,0); const available=expected.filter(c=>c.availability==='available'&&c.score!==null); const availableWeight=available.reduce((n,c)=>n+c.weight,0); const coverage=roundScore(availableWeight/expectedWeight); const raw=availableWeight?roundScore(available.reduce((n,c)=>n+c.score!*c.weight,0)/availableWeight):0; const qualified=roundScore(raw*coverage);
 const hard:HardConflictFlag[]=[]; if(primaryConflict)hard.push('release_primary_direction_conflict');if(event.reality.priceReactionTimeline.initialConfirmationThenReversal)hard.push('confirmation_follow_through_reversal');if(event.reality.priceReactionTimeline.acceptanceLostTimestamp)hard.push('initial_confirmation_lost');if(twoSided)hard.push('two_sided_expansion');if(relatedDecision==='conflicting_final')hard.push('related_market_final_conflict');if(releaseClear&&primaryAmbiguous)hard.push('resolved_release_with_ambiguous_primary');if(!provenanceOkay)hard.push('provenance_conflict');
 const ambiguity:string[]=[]; if(!relatedStructural&&relatedScore===null)ambiguity.push('related_market_unresolved');if(primaryAmbiguous)ambiguity.push('primary_reaction_ambiguous');
 const mandatory=[...MANDATORY_DIRECT_COMPONENTS,...(event.assessmentStage==='follow_through'?['path_continuity' as const]:[])]; const missingMandatory=mandatory.some(name=>components.find(c=>c.component===name)?.availability!=='available'); const insufficient=missingMandatory||coverage<.65||event.outcome==='insufficient_data'||!volatilityValid||!provenanceOkay;
 const state:MarketCleanlinessEvaluation['cleanlinessState']=insufficient?'insufficient_data':hard.length||qualified<45?'conflicted':qualified>=75&&raw>=80&&coverage>=.8&&!ambiguity.length?'clean':'mixed';
 const core={policyVersion:MARKET_CLEANLINESS_POLICY_VERSION,sourceEventEvaluationId:event.eventEvaluationId,sourceExpectationId:event.expectationId,sourceAnalogRetrievalId:analog?.retrievalId??null,sourceSessionLiquidityContextId:session?.contextId??null,eventInstanceKey:`${event.expectation.eventReleaseId}|${event.releaseVersion}|${event.asset}`,asset:event.asset,eventKind:event.expectation.eventKind,assessmentStage:event.assessmentStage,evidenceCutoffAt,rawAgreementScore:raw,evidenceCoverageRatio:coverage,evidenceQualifiedScore:qualified,cleanlinessState:state,components,hardConflictFlags:hard,ambiguityFlags:ambiguity,warnings:[...event.warnings],limitations:components.flatMap(c=>c.limitations),deterministicRationale:`Market-context coherence is ${state}; raw ${raw}, coverage ${coverage}, qualified ${qualified}. This is not a tradability assessment or trading instruction.`,sourceEvidenceReferences:references};
 const createdAt=evidenceCutoffAt; const canonicalPayloadHash=cleanlinessHash(core); return immutableCleanliness({...core,cleanlinessEvaluationId:cleanlinessId('mce',core),canonicalPayloadHash,createdAt});
}
