import type { EventRealityEvaluation } from '../expectation-reality/contracts';
import type { HistoricalAnalogRetrievalResult } from '../historical-analog-memory/contracts';
import type { CleanlinessEvidenceReference, MarketCleanlinessComponent, MarketCleanlinessEvaluation, MarketSessionLiquidityContextRecord, CleanlinessComponentName, HardConflictFlag } from './contracts';
import { canonicalJson } from '../expectation-reality/identity';
import { validateNoAdviceRecord } from '../contradiction-action-protocol/policy';
import { cleanlinessHash, cleanlinessId, immutableCleanliness } from './identity';
import { resolveCleanlinessTrust } from './trust';
import { stageSlicedPathView } from './path-view';
import { MANDATORY_DIRECT_COMPONENTS, MARKET_CLEANLINESS_POLICY_VERSION, MARKET_CLEANLINESS_WEIGHTS, roundScore, stageOrder } from './policy';

export type MarketCleanlinessEvidence = { event:EventRealityEvaluation; analog:HistoricalAnalogRetrievalResult|null; session:MarketSessionLiquidityContextRecord|null; evidenceCutoffAt:string };
const validTime=(at:string,cutoff:string)=>Number.isFinite(Date.parse(at))&&Date.parse(at)<=Date.parse(cutoff);
const ref=(sourceType:string,sourceId:string,contentHash:string,observedAt:string,availableAt:string,reliability:CleanlinessEvidenceReference['reliability']):CleanlinessEvidenceReference=>({sourceType,sourceId,contentHash,observedAt,availableAt,reliability});
const component=(name:CleanlinessComponentName, availability:MarketCleanlinessComponent['availability'], score:number|null, reasonCodes:string[], rationale:string, refs:CleanlinessEvidenceReference[]=[], warnings:string[]=[], limitations:string[]=[]):MarketCleanlinessComponent=>({component:name,availability,status:score===null?'insufficient':score>=80?'supportive':score>=55?'neutral':score>=30?'conflicting':'severely_conflicting',score,weight:MARKET_CLEANLINESS_WEIGHTS[name],effectiveWeight:availability==='available'&&score!==null?MARKET_CLEANLINESS_WEIGHTS[name]:0,sourceReferences:refs,reasonCodes,warnings,limitations,rationale});
const phaseFor=(event:EventRealityEvaluation)=>event.assessmentStage==='immediate'?event.reality.priceReactionTimeline.immediate:event.assessmentStage==='confirmation'?event.reality.priceReactionTimeline.confirmation:event.reality.priceReactionTimeline.followThrough;
const resolved=(event:EventRealityEvaluation)=>event.reality.releaseAlignment.actualDirection;
const directional=(d:unknown):d is 'bullish'|'bearish'=>d==='bullish'||d==='bearish';

export function evaluateMarketCleanliness(input:MarketCleanlinessEvidence):MarketCleanlinessEvaluation {
 const {event,analog,session,evidenceCutoffAt}=input; if(!validTime(event.interpretedAt,evidenceCutoffAt)||!validTime(event.createdAt,evidenceCutoffAt)) throw new Error('event_evidence_after_cleanliness_cutoff');
 if(analog&&(analog.queryEventEvaluationId!==event.eventEvaluationId||!validTime(analog.queryCutoffAt,evidenceCutoffAt)||!validTime(analog.createdAt,evidenceCutoffAt))) throw new Error('analog_cutoff_or_lineage_mismatch');
 if(session&&(session.eventEvaluationId!==event.eventEvaluationId||session.asset!==event.asset||session.evidenceCutoffAt!==evidenceCutoffAt)) throw new Error('session_context_lineage_mismatch');
 if(session&&(!validTime(session.observedAt,evidenceCutoffAt)||!validTime(session.availableAt,evidenceCutoffAt)||!validTime(session.createdAt,evidenceCutoffAt))) throw new Error('session_context_after_cleanliness_cutoff');
 const references:CleanlinessEvidenceReference[]=[]; const releaseReliability=event.reality.provenance.map(p=>resolveCleanlinessTrust(p,evidenceCutoffAt).effectiveReliability); event.reality.provenance.forEach(p=>{const trust=resolveCleanlinessTrust(p,evidenceCutoffAt);references.push(ref('release',p.sourceId,p.contentHash??event.assessmentEvidenceHash,event.reality.observedAt,p.verifiedAt??event.reality.observedAt,trust.effectiveReliability));});
 event.reactionProvenance.forEach(p=>{const trust=resolveCleanlinessTrust(p,evidenceCutoffAt);references.push(ref(p.reactionInput.asset===event.asset?'price_reaction':'related_reaction',p.sourceId,p.calculatedContentHash??p.suppliedContentHash??event.observationContentHash,event.interpretedAt,p.verifiedAt??event.interpretedAt,trust.effectiveReliability));});
 const directProvenance=[...event.reality.provenance,...event.reactionProvenance]; const relatedProvenancePresent=event.reality.relatedEvidenceDecision.status!=='confirmed'||event.reactionProvenance.some(p=>p.reactionInput.asset!==event.asset); const provenanceOkay=directProvenance.length>0&&relatedProvenancePresent&&directProvenance.every(p=>resolveCleanlinessTrust(p,evidenceCutoffAt).eligible);
 const alignment=event.reality.releaseAlignment; const releaseStatus=alignment.status; const revision=event.reality.revisionAdjustedMeasures; const resolvedDirection=alignment.actualDirection; const neutralRelease=releaseStatus==='inline'; const directionResolved=neutralRelease?resolvedDirection==='neutral':directional(resolvedDirection); const revisionResolved=revision.revisionEffect!=='reverses_interpretation'||revision.revisionAdjustedDirection!=='unknown'; const subfieldsClear=!['mixed','insufficient_data'].includes(alignment.economicMeaningAlignment)&&!['mixed','insufficient_data'].includes(alignment.policyPressureAlignment)&&!['mixed','insufficient_data'].includes(alignment.actualVsForecastAlignment); const releaseClear=(releaseStatus==='aligned'||releaseStatus==='contradicted'||neutralRelease)&&directionResolved&&revisionResolved&&subfieldsClear;
 const release=component('release_clarity',releaseClear?'available':'unavailable',releaseClear?(neutralRelease?80:94):null,[`release_${releaseStatus}`,`revision_${revision.revisionEffect}`,`economic_${alignment.economicMeaningAlignment}`,`policy_${alignment.policyPressureAlignment}`,`actual_forecast_${alignment.actualVsForecastAlignment}`],`Clarity uses status=${releaseStatus}, revisionDirection=${revision.revisionAdjustedDirection}, revisionEffect=${revision.revisionEffect}, economic=${alignment.economicMeaningAlignment}, policy=${alignment.policyPressureAlignment}, actualForecast=${alignment.actualVsForecastAlignment}, resolvedDirection=${resolvedDirection}.`,references.filter(r=>r.sourceType==='release'),event.reality.warnings,releaseClear?[]:[...event.reality.limitations,'release_interpretation_unresolved']);
 const primary=event.reality.primaryPriceReaction; const releaseDirection=resolved(event); const readinessValid=primary.readiness.contractShapeStatus==='valid'&&primary.readiness.deterministicFoundationStatus==='implemented'; const primaryDirectional=directional(primary.observedDirection); const neutralCoherent=(releaseDirection==='neutral'||neutralRelease)&&primary.observedDirection==='neutral'&&!['strong','extreme','outlier'].includes(primary.impulseClass); const neutralConflict=(releaseDirection==='neutral'||neutralRelease)&&primaryDirectional&&['strong','extreme','outlier'].includes(primary.impulseClass); const primaryConflict=neutralConflict||(directional(releaseDirection)&&primaryDirectional&&releaseDirection!==primary.observedDirection); const primaryAmbiguous=['ambiguous','reversed','insufficient_data','unknown'].includes(primary.status)||(!primaryDirectional&&!neutralCoherent)||!readinessValid||primary.confidence<40;
 const primaryScore=primaryAmbiguous?(primary.status==='reversed'?20:null):primaryConflict?15:Math.max(55,Math.min(96,90-primary.absorptionScore*.25-primary.wickRejectionScore*.15-primary.reversalScore*.25));
 const primaryComponent=component('primary_reaction_coherence',primaryScore===null?'unavailable':'available',primaryScore,[`primary_${primary.status}`],primaryConflict?'The decisive primary response opposes the resolved release direction.':'The primary response is assessed against resolved release direction, independently of the frozen expectation.',references.filter(r=>r.sourceType==='price_reaction'),primary.warnings,primaryScore===null?['primary_direction_unresolved']:[]);
 const phase=phaseFor(event); const pathStructural=event.assessmentStage==='immediate'; const pathView=stageSlicedPathView(event,evidenceCutoffAt); const twoSided=pathView.twoSided; const pathBad=pathView.reversal||pathView.acceptanceLost||twoSided;
 let pathScore:number|null=null; let pathReason=`path_${phase.state}`; let pathRationale='Only evidence in the stage-sliced persisted timeline is used.'; let pathAmbiguous=false;
 if(!pathStructural&&event.assessmentStage==='confirmation'){
  const [immediate,confirmation]=pathView.phases; const immediateDirectional=directional(immediate?.observedDirection); const confirmationDirectional=directional(confirmation?.observedDirection); const sameDirection=immediateDirectional&&confirmationDirectional&&immediate.observedDirection===confirmation.observedDirection;
  if(!immediate||!confirmation||['unknown','insufficient_data'].includes(confirmation.state)||(immediateDirectional&&!confirmationDirectional)){pathReason='confirmation_transition_ambiguous';pathRationale='The confirmation phase does not resolve the directional immediate response.';pathAmbiguous=true;}
  else if(!immediateDirectional&&confirmationDirectional&&!['absorbed','delayed'].includes(immediate.state)){pathScore=20;pathReason='confirmation_transition_neutral_directional_expansion';pathRationale='A neutral immediate phase became a decisive directional confirmation.';}
  else if(['absorbed','delayed'].includes(immediate.state)&&['confirmed','rejected'].includes(confirmation.state)){pathScore=60;pathReason='confirmation_transition_delayed_resolution';pathRationale='An absorbed or delayed immediate phase reached a coherent but only moderate confirmation-stage resolution.';}
  else if(sameDirection&&immediate.state===confirmation.state&&confirmation.state==='confirmed'){pathScore=92;pathReason='confirmation_transition_persistent_confirmed';pathRationale='Immediate and confirmation phases are both confirmed in the same observed direction.';}
  else if(sameDirection&&immediate.state===confirmation.state&&confirmation.state==='rejected'){pathScore=92;pathReason='confirmation_transition_persistent_rejected';pathRationale='Immediate and confirmation phases are both rejected in the same observed direction.';}
  else if(!sameDirection||immediate.state!==confirmation.state){pathScore=20;pathReason=!sameDirection?'confirmation_transition_direction_flip':'confirmation_transition_state_flip';pathRationale='The immediate-to-confirmation direction or state changed and is not strong continuity.';}
  else {pathScore=45;pathReason='confirmation_transition_mixed';pathRationale='The immediate-to-confirmation transition is mixed under the deterministic policy.';}
 } else if(!pathStructural) pathScore=phase.state==='insufficient_data'||phase.state==='unknown'?null:pathBad?15:['confirmed','rejected'].includes(phase.state)?92:['absorbed','delayed'].includes(phase.state)?55:30;
 const pathReferences=references.filter(r=>r.sourceType==='price_reaction'&&validTime(r.availableAt,event.interpretedAt)&&validTime(r.availableAt,evidenceCutoffAt));
 const path=component('path_continuity',pathStructural?'structurally_unavailable':pathScore===null?'unavailable':'available',pathScore,[pathReason],pathStructural?'Later path evidence is not mature at the immediate stage.':pathRationale,pathStructural||pathScore===null?[]:pathReferences,phase.warnings,pathScore===null&&!pathStructural?['current_stage_path_unavailable']:[]);
 const relatedDecision=event.reality.relatedEvidenceDecision.status; const relatedStructural=event.assessmentStage==='immediate'||relatedDecision==='not_required'; const relatedScore=relatedStructural?null:relatedDecision==='confirmed'?94:relatedDecision==='conflicting_final'?5:null;
 const relatedSourceIds=new Set(event.reactionProvenance.filter(p=>p.reactionInput.asset!==event.asset&&event.expectation.requiredRelatedAssets.includes(p.reactionInput.asset)).map(p=>p.sourceId));
 const relatedReferences=relatedScore===null?[]:references.filter(r=>r.sourceType==='related_reaction'&&relatedSourceIds.has(r.sourceId)&&validTime(r.availableAt,event.interpretedAt)&&validTime(r.availableAt,evidenceCutoffAt));
 const related=component('related_market_coherence',relatedStructural?'structurally_unavailable':relatedScore===null?'unavailable':'available',relatedScore,[`related_${relatedDecision}`],relatedDecision==='not_required'?'Canonical policy excludes related markets from expected weight.':'Canonical related-market closure is retained; missing evidence never confirms cleanliness.',relatedReferences,[],relatedScore===null&&!relatedStructural?['related_market_evidence_unavailable']:[]);
 const envelope=event.reality.priceReactionTimeline.primaryObservation; const volatilityValid=typeof envelope.reactionInput.volatilityBasisPct==='number'&&envelope.reactionInput.volatilityBasisPct>0&&Number.isFinite(primary.volatilityAdjustedMove)&&!primary.warnings.includes('volatility_basis_missing'); const volatileConflict=twoSided||primary.warnings.includes('outlier_move')&&primary.reversalScore>=50;
 const volatility=component('volatility_interpretability',volatilityValid?'available':'unavailable',volatilityValid?(volatileConflict?25:primary.warnings.includes('outlier_move')?72:90):null,[volatilityValid?'pre_event_volatility_valid':'pre_event_volatility_missing'],volatilityValid?'The persisted pre-event basis makes reaction magnitude interpretable.':'No valid pre-event volatility basis is persisted.',references.filter(r=>r.sourceType==='price_reaction'),primary.warnings,volatilityValid?[]:['volatility_context_required']);
 let sessionScore:number|null=null; if(session&&session.marketState!=='unknown'&&session.marketState!=='closed'&&session.sessionState!=='unknown'&&session.sessionState!=='closed'&&session.liquidityState!=='unknown'&&session.spreadState!=='unknown'&&session.activityState!=='unknown'&&((session.marketState==='continuous')===(session.sessionState==='continuous'))){sessionScore=95; if(session.sessionState==='off_hours')sessionScore-=25;if(session.liquidityState==='thin')sessionScore-=25;if(session.liquidityState==='stressed')sessionScore-=45;if(session.spreadState==='wide')sessionScore-=25;if(session.activityState==='depressed')sessionScore-=10; sessionScore=Math.max(10,sessionScore);}
 const sessionEligible=Boolean(session&&session.provenance.length&&session.provenance.every(p=>resolveCleanlinessTrust(p,evidenceCutoffAt).eligible)); if(session)session.provenance.forEach(p=>{const trust=resolveCleanlinessTrust(p,evidenceCutoffAt);references.push(ref('session_liquidity',p.sourceId,p.contentHash??session.canonicalPayloadHash,session.observedAt,session.availableAt,trust.effectiveReliability));});
 const sessionComponent=component('session_liquidity_quality',!session||sessionScore===null?'unavailable':sessionEligible?'available':'provenance_limited',sessionEligible?sessionScore:null,[session?'persisted_session_context':'session_context_missing'],session?'Only the persisted session/liquidity record is assessed.':'Session and liquidity conditions remain explicitly unavailable.',references.filter(r=>r.sourceType==='session_liquidity'),session?.warnings?[...session.warnings]:[],session?[...session.limitations,...(!sessionEligible?['session_provenance_limited']:[])]:['session_context_unavailable']);
 let analogScore:number|null=null; let analogAvailability:MarketCleanlinessComponent['availability']=analog?.evidenceSufficiency==='provenance_limited'?'provenance_limited':'unavailable'; const analogRefs:CleanlinessEvidenceReference[]=[]; if(analog){
  const snapshotsSafe=analog.memorySnapshot.every(m=>m.selectedStageAssessmentStageOrder<=stageOrder(event.assessmentStage)&&m.selectedStageProvenanceEligibility==='eligible'&&validTime(m.availableAt,evidenceCutoffAt)&&validTime(m.selectedStageCreatedAt,evidenceCutoffAt)&&validTime(m.selectedStageInterpretedAt,evidenceCutoffAt)); if(!snapshotsSafe)throw new Error('future_stage_analog_evidence');
  for(const m of analog.matches){if(m.similarityScore<0||m.similarityScore>100||m.featureCoverageRatio<0||m.featureCoverageRatio>1)throw new Error('invalid_cleanliness_analog_range');const required=m.sourceProvenanceSummary.requiredEvidenceReliability;const replayCertified=!required.includes('replay')||m.sourceProvenanceSummary.releaseVerificationArtifacts.some(artifact=>artifact.effectiveReliability==='replay'&&Boolean(artifact.verificationRef&&artifact.trustBasis&&validTime(artifact.verifiedAt,evidenceCutoffAt)));const allowed=required.every(r=>r==='verified'||r==='replay')&&replayCertified;if(!allowed)analogAvailability='provenance_limited';}
  for(const m of analog.memorySnapshot){const match=analog.matches.find(x=>x.analogMemoryId===m.analogMemoryId);const reliability=(match?.sourceProvenanceSummary.datasetClass??'unverified') as CleanlinessEvidenceReference['reliability'];analogRefs.push(ref('historical_analog_stage',`${analog.retrievalId}:${m.analogMemoryId}:${m.selectedStageSourceEventEvaluationId}`,m.selectedStageMatchFeatureHash,m.selectedStageInterpretedAt,m.availableAt,reliability));}
  if(analog.evidenceSufficiency==='sufficient'&&analog.eligibleUniqueEventCount>=3&&analog.matches.length>=3&&analogAvailability!=='provenance_limited'){ const states=analog.matches.map(m=>m.historicalOutcomeContext.finalPricePathState); const concentration=Math.max(...[...new Set(states)].map(state=>states.filter(x=>x===state).length))/states.length; analogScore=roundScore(45+50*concentration); analogAvailability=analog.matches.some(m=>m.sourceProvenanceSummary.datasetClass==='fixture'||m.sourceProvenanceSummary.datasetClass==='unverified')?'provenance_limited':'available'; if(analogAvailability==='provenance_limited')analogScore=null; }
 }
 const analogComponent=component('analog_consistency',analogAvailability,analogScore,[analog?`analog_${analog.evidenceSufficiency}`:'analog_not_supplied'],'Historical path-state concentration is context only; outcomes are never used to override direct evidence.',analogRefs,analog?.warnings??[],analog?.limitations??['no_comparable_history']);
 const directReferences=[...references]; references.push(...analogRefs);
 const identities=new Map<string,CleanlinessEvidenceReference>(); for(const reference of references){const key=`${reference.sourceType}|${reference.sourceId}`;const prior=identities.get(key);if(prior&&canonicalJson(prior)!==canonicalJson(reference))throw new Error('cleanliness_evidence_identity_conflict');identities.set(key,reference);}
 const provenance=component('provenance_quality',provenanceOkay?'available':'provenance_limited',provenanceOkay?95:null,[provenanceOkay?'required_provenance_eligible':'required_provenance_limited'],'Verified or certified replay evidence may support cleanliness; fixture and unverified evidence cannot.',directReferences,[],provenanceOkay?[]:[`required_classes:${releaseReliability.join(',')}`]);
 const components=[release,primaryComponent,path,related,volatility,sessionComponent,analogComponent,provenance];
 const expected=components.filter(c=>c.availability!=='structurally_unavailable'); const expectedWeight=expected.reduce((n,c)=>n+c.weight,0); const available=expected.filter(c=>c.availability==='available'&&c.score!==null); const availableWeight=available.reduce((n,c)=>n+c.weight,0); const coverage=roundScore(availableWeight/expectedWeight); const raw=availableWeight?roundScore(available.reduce((n,c)=>n+c.score!*c.weight,0)/availableWeight):0; const qualified=roundScore(raw*coverage);
 const hard:HardConflictFlag[]=[]; if(primaryConflict)hard.push('release_primary_direction_conflict');if(pathView.reversal)hard.push('confirmation_follow_through_reversal');if(pathView.acceptanceLost)hard.push('initial_confirmation_lost');if(twoSided)hard.push('two_sided_expansion');if(relatedDecision==='conflicting_final')hard.push('related_market_final_conflict');if(releaseClear&&primaryAmbiguous)hard.push('resolved_release_with_ambiguous_primary');if(!provenanceOkay)hard.push('provenance_conflict');
 const ambiguity:string[]=[]; if(!relatedStructural&&relatedScore===null)ambiguity.push('related_market_unresolved');if(primaryAmbiguous)ambiguity.push('primary_reaction_ambiguous');if(pathAmbiguous)ambiguity.push('confirmation_path_ambiguous');
 const mandatory=[...MANDATORY_DIRECT_COMPONENTS,...(event.assessmentStage==='follow_through'?['path_continuity' as const]:[])]; const missingMandatory=mandatory.some(name=>components.find(c=>c.component===name)?.availability!=='available'); const insufficient=missingMandatory||coverage<.65||event.outcome==='insufficient_data'||!volatilityValid||!provenanceOkay;
 const hasKnownProvenanceLimitation=components.some(c=>c.availability==='provenance_limited');
 const state:MarketCleanlinessEvaluation['cleanlinessState']=insufficient?'insufficient_data':hard.length||qualified<45?'conflicted':qualified>=75&&raw>=80&&coverage>=.8&&!ambiguity.length&&!hasKnownProvenanceLimitation?'clean':'mixed';
 const core={policyVersion:MARKET_CLEANLINESS_POLICY_VERSION,sourceEventEvaluationId:event.eventEvaluationId,sourceExpectationId:event.expectationId,sourceAnalogRetrievalId:analog?.retrievalId??null,sourceSessionLiquidityContextId:session?.contextId??null,eventInstanceKey:`${event.expectation.eventReleaseId}|${event.releaseVersion}|${event.asset}`,asset:event.asset,eventKind:event.expectation.eventKind,assessmentStage:event.assessmentStage,evidenceCutoffAt,rawAgreementScore:raw,evidenceCoverageRatio:coverage,evidenceQualifiedScore:qualified,cleanlinessState:state,components,hardConflictFlags:hard,ambiguityFlags:ambiguity,warnings:[...event.warnings],limitations:components.flatMap(c=>c.limitations),deterministicRationale:`Market-context coherence is ${state}; raw ${raw}, coverage ${coverage}, qualified ${qualified}. This is not a tradability assessment or trading instruction.`,sourceEvidenceReferences:references};
 const createdAt=evidenceCutoffAt; const canonicalPayloadHash=cleanlinessHash(core); const evaluation=immutableCleanliness({...core,cleanlinessEvaluationId:cleanlinessId('mce',core),canonicalPayloadHash,createdAt}); validateNoAdviceRecord(evaluation); return evaluation;
}
