import { canonicalJson } from '../expectation-reality/identity';
import type { MarketSessionLiquidityContextRecord } from './contracts';
import type { MarketSessionLiquidityContextRepository } from './context-repository';
export type SqlPool={query(sql:string,params?:unknown[]):Promise<{rows:any[];rowCount?:number}>;connect():Promise<{query(sql:string,params?:unknown[]):Promise<{rows:any[];rowCount?:number}>;release():void}>};
type PgError=Error&{code?:string;constraint?:string};
const value=(r:any)=>(typeof r.canonical_payload==='string'?JSON.parse(r.canonical_payload):r.canonical_payload) as MarketSessionLiquidityContextRecord;
const normalize=(e:unknown):Error=>{const p=e as PgError;switch(p.constraint){case'market_session_liquidity_contexts_event_fkey':return new Error('session_context_event_missing');case'market_session_liquidity_contexts_cutoff_check':return new Error('session_context_after_cutoff');case'market_session_liquidity_contexts_payload_hash_key':return new Error('session_context_payload_conflict');case'market_session_liquidity_contexts_pkey':return new Error('session_context_immutable_conflict');default:return e instanceof Error?e:new Error(String(e));}};
export class SqlMarketSessionLiquidityContextRepository implements MarketSessionLiquidityContextRepository{
 constructor(private pool:SqlPool){}
 async saveContext(r:MarketSessionLiquidityContextRecord){try{await this.pool.query('INSERT INTO market_session_liquidity_contexts(context_id,policy_version,event_evaluation_id,asset,observed_at,available_at,evidence_cutoff_at,market_state,session_state,liquidity_state,spread_state,activity_state,source_evidence_ids,provenance,warnings,limitations,canonical_payload,canonical_payload_hash,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19)',[r.contextId,r.policyVersion,r.eventEvaluationId,r.asset,r.observedAt,r.availableAt,r.evidenceCutoffAt,r.marketState,r.sessionState,r.liquidityState,r.spreadState,r.activityState,r.sourceEvidenceIds,JSON.stringify(r.provenance),r.warnings,r.limitations,JSON.stringify(r),r.canonicalPayloadHash,r.createdAt]);return r;}catch(e){const prior=await this.getContextById(r.contextId);if(prior&&canonicalJson(prior)===canonicalJson(r))return prior;if(prior)throw new Error('session_context_immutable_conflict');throw normalize(e);}}
 async getContextById(id:string){const q=await this.pool.query('SELECT canonical_payload FROM market_session_liquidity_contexts WHERE context_id=$1',[id]);return q.rows[0]?value(q.rows[0]):null;}
}
