import type { LaunchAsset, LaunchAssetFixtureAssetPack, LaunchAssetFixtureCoverageReport, LaunchAssetFixtureEvidenceItem, LaunchAssetFixtureExpectedOutput, LaunchAssetFixtureLibrary, LaunchAssetFixtureScenario, LaunchAssetFixtureScenarioId, LaunchAssetFixtureScenarioKind, ProviderSourceFamily, ProviderSourceId } from '@elceo/types';
import { getProviderSourceRegistrySnapshot } from '../provider-source-registry/index';

const T='2026-01-15T12:00:00.000Z';
const S=(asset:LaunchAsset,id:string,title:string,kind:LaunchAssetFixtureScenarioKind,tags:string[],pressure:LaunchAssetFixtureExpectedOutput['expectedPressure'],contr=false,stale=false):LaunchAssetFixtureScenario=>({scenarioId:`${asset}:${id}` as LaunchAssetFixtureScenarioId,asset,title,kind,severity:contr?'high':'medium',regime:stale?'stressed':'event_risk',tags,evidence:[E(asset,'federal_reserve_official','macro_official','policy_event','fed_policy',pressure,tags),E(asset,'marketaux_news','news_extraction','news_headlines','macro_risk',pressure,tags),E(asset,asset==='btc_usd'?'crypto_derivatives_shell':'tiingo_market_data',asset==='btc_usd'?'crypto':'market_data',asset==='btc_usd'?'derivatives_proxy':'market_price','price_action',pressure,tags,stale?'stale':'fresh')],expectedOutput:{scenarioId:`${asset}:${id}` as LaunchAssetFixtureScenarioId,expectedPressure:pressure,expectedConfidenceBand:contr?'medium':'high',expectedContradiction:contr,expectedFreshnessWarnings:stale,expectedTopEvidenceClasses:['price_action','macro_risk','fed_policy'],expectedCognitionThemes:tags}});
const E=(asset:LaunchAsset,sourceId:ProviderSourceId,fam:ProviderSourceFamily,cap:any,cls:string,p:any,tags:string[],fresh:'fresh'|'aging'|'stale'='fresh'):LaunchAssetFixtureEvidenceItem=>({evidenceId:`${asset}:${sourceId}:${cls}`,asset,sourceId,providerFamily:fam,sourceFamily:fam,capabilityKind:cap,evidenceClass:cls,observedAt:T,freshnessState:fresh,qualityHints:['fixture','deterministic'],directionalPressure:p,narrative:`Fixture evidence for ${asset} ${cls} context`,expectedRole:'primary',expectedImportance:0.8,scenarioTags:tags});
const packs = [
{asset:'xau_usd',scenarios:[S('xau_usd','conflicting_yields_safe_haven','Rising yields but safe-haven demand','conflicting_evidence',['conflicting','geopolitical'],'mixed',true),S('xau_usd','fed_dovish_weak_dxy','Fed dovish surprise and weaker DXY','central_bank_surprise',['dovish','fx'],'bullish'),S('xau_usd','hot_inflation_real_yields','Hot inflation and rising real yields','macro_event',['inflation','real_yield'],'bearish'),S('xau_usd','risk_off_geopolitical','Risk-off geopolitical shock','risk_off_shock',['risk_off','geopolitical'],'bullish'),S('xau_usd','stale_etf_flow_warning','Stale ETF and flow evidence warning','stale_evidence',['stale','flow'],'unknown',false,true)]},
{asset:'eur_usd',scenarios:[S('eur_usd','ecb_hawkish_vs_fed_neutral','ECB hawkish surprise vs Fed neutral','central_bank_surprise',['ecb','rates'],'bullish'),S('eur_usd','stale_pmi_warning','Stale PMI/euro macro evidence','stale_evidence',['stale','pmi'],'unknown',false,true),S('eur_usd','strong_euro_vs_us_yields','Strong euro data vs stronger US yields','conflicting_evidence',['conflicting','yields'],'mixed',true),S('eur_usd','us_cpi_upside','US CPI upside surprise','macro_event',['inflation'],'bearish'),S('eur_usd','euro_growth_deterioration','Euro-area growth deterioration','liquidity_pressure',['growth'],'bearish')]},
{asset:'gbp_usd',scenarios:[S('gbp_usd','boe_dovish_repricing','BoE dovish repricing','central_bank_surprise',['boe'],'bearish'),S('gbp_usd','conflicting_wages_growth','Strong UK wages vs weak retail growth','conflicting_evidence',['conflicting','uk_data'],'mixed',true),S('gbp_usd','uk_cpi_wage_upside','UK CPI and wage upside surprise','macro_event',['inflation'],'bullish'),S('gbp_usd','uk_fiscal_political_risk','UK fiscal and political risk','news_geopolitical_shock',['political_risk'],'bearish'),S('gbp_usd','usd_broad_strength','US dollar broad strength','normal_market',['usd_strength'],'bearish')]},
{asset:'usd_jpy',scenarios:[S('usd_jpy','boj_hawkish_surprise','BoJ hawkish surprise','central_bank_surprise',['boj'],'bearish'),S('usd_jpy','conflicting_yields_vs_intervention','High US yields vs intervention risk','conflicting_evidence',['conflicting','intervention'],'mixed',true),S('usd_jpy','intervention_risk_regime','Intervention-risk regime','high_volatility',['intervention'],'unknown'),S('usd_jpy','risk_off_yen_demand','Risk-off yen demand','risk_off_shock',['risk_off'],'bearish'),S('usd_jpy','us_yields_rise_boj_dovish','US yields rising and BoJ dovish','macro_event',['yields'],'bullish')]},
{asset:'btc_usd',scenarios:[S('btc_usd','conflicting_etf_vs_macro_tightening','ETF inflow vs macro tightening','conflicting_evidence',['conflicting','etf'],'mixed',true),S('btc_usd','etf_regulatory_positive','ETF and regulatory positive shock','news_geopolitical_shock',['etf','regulatory'],'bullish'),S('btc_usd','funding_oi_overheating','Funding and open interest overheating','high_volatility',['derivatives'],'mixed',true),S('btc_usd','macro_liquidity_improving','Macro liquidity improving','liquidity_pressure',['liquidity'],'bullish'),S('btc_usd','risk_off_liquidation','Risk-off liquidation shock','risk_off_shock',['liquidation'],'bearish')]},
{asset:'nasdaq_100',scenarios:[S('nasdaq_100','conflicting_earnings_vs_fci','Strong earnings vs tighter financial conditions','conflicting_evidence',['conflicting','fci'],'mixed',true),S('nasdaq_100','megacap_earnings_strength','Megacap earnings strength','normal_market',['earnings'],'bullish'),S('nasdaq_100','rates_shock_real_yields','Rates shock and higher real yields','macro_event',['rates'],'bearish'),S('nasdaq_100','semiconductor_risk_off','Semiconductor risk-off shock','risk_off_shock',['semis'],'bearish'),S('nasdaq_100','volatility_expansion','Volatility expansion','high_volatility',['volatility'],'bearish')]},
{asset:'sp500',scenarios:[S('sp500','broad_risk_on','Broad risk-on','normal_market',['risk_on'],'bullish'),S('sp500','conflicting_price_vs_breadth','Strong index price vs weakening breadth','conflicting_evidence',['conflicting','breadth'],'mixed',true),S('sp500','credit_stress_widening','Credit stress widening','risk_off_shock',['credit'],'bearish'),S('sp500','earnings_breadth_deterioration','Earnings breadth deterioration','liquidity_pressure',['earnings_breadth'],'bearish'),S('sp500','inflation_yields_shock','Inflation and yields shock','macro_event',['inflation','yields'],'bearish')]},
{asset:'de30',scenarios:[S('de30','conflicting_weak_macro_global_risk_on','Weak German macro vs global risk-on','conflicting_evidence',['conflicting','germany'],'mixed',true),S('de30','ecb_hawkish_surprise','ECB hawkish surprise','central_bank_surprise',['ecb'],'bearish'),S('de30','energy_supply_shock','Energy supply shock','news_geopolitical_shock',['energy'],'bearish'),S('de30','german_industrial_weakness','German industrial weakness','macro_event',['industrial'],'bearish'),S('de30','pmi_deterioration','Euro-area PMI deterioration','liquidity_pressure',['pmi'],'bearish')]},
{asset:'dxy',scenarios:[S('dxy','conflicting_weaker_us_vs_risk_aversion','Weaker US data vs global risk aversion','conflicting_evidence',['conflicting','risk_off'],'mixed',true),S('dxy','fed_hawkish_repricing','Fed hawkish repricing','central_bank_surprise',['fed'],'bullish'),S('dxy','global_risk_off_dollar_demand','Global risk-off dollar demand','risk_off_shock',['risk_off'],'bullish'),S('dxy','us_macro_downside','US macro downside surprise','macro_event',['us_macro'],'bearish'),S('dxy','yield_differential_narrowing','Yield differential narrowing','normal_market',['yield_diff'],'bearish')]},
{asset:'vix',scenarios:[S('vix','calm_regime_compression','Volatility compression calm regime','normal_market',['calm'],'bearish'),S('vix','conflicting_rising_equities_elevated_vol_risk','Rising equities but elevated vol risk','conflicting_evidence',['conflicting','vol'],'mixed',true),S('vix','credit_stress_spillover','Credit stress spillover','risk_off_shock',['credit'],'bullish'),S('vix','equity_selloff_shock','Equity selloff shock','high_volatility',['selloff'],'bullish'),S('vix','macro_event_uncertainty_spike','Macro-event uncertainty spike','macro_event',['event_risk'],'bullish')]},
].map((p)=>({ ...p, scenarios:[...p.scenarios].sort((a,b)=>a.scenarioId.localeCompare(b.scenarioId)) })) as LaunchAssetFixtureAssetPack[];
const scenarios=packs.flatMap((x)=>x.scenarios).sort((a,b)=>a.scenarioId.localeCompare(b.scenarioId));
const byId=new Map(scenarios.map((x)=>[x.scenarioId,x]));
export const getLaunchAssetFixtureLibrary=():LaunchAssetFixtureLibrary=>({generatedAt:T,assets:packs,scenarios});
export const getLaunchAssetFixtureAssetPack=(asset:LaunchAsset)=>packs.find((x)=>x.asset===asset)??null;
export const listLaunchAssetFixtureScenarios=(asset?:LaunchAsset)=>asset?(getLaunchAssetFixtureAssetPack(asset)?.scenarios??[]):scenarios;
export const getLaunchAssetFixtureScenario=(scenarioId:LaunchAssetFixtureScenarioId)=>byId.get(scenarioId)??null;
export const listFixtureScenariosByKind=(kind:LaunchAssetFixtureScenarioKind)=>scenarios.filter((x)=>x.kind===kind);
export const buildFixtureExpectedOutput=(scenarioId:LaunchAssetFixtureScenarioId)=>getLaunchAssetFixtureScenario(scenarioId)?.expectedOutput??null;
export const buildFixtureEvidenceForScenario=(scenarioId:LaunchAssetFixtureScenarioId)=>getLaunchAssetFixtureScenario(scenarioId)?.evidence??[];
export const getLaunchAssetFixtureCoverageReport=():LaunchAssetFixtureCoverageReport=>{const assetScenarioCounts=Object.fromEntries(packs.map((x)=>[x.asset,x.scenarios.length])) as LaunchAssetFixtureCoverageReport['assetScenarioCounts']; return {generatedAt:T,assetScenarioCounts,totalScenarioCount:scenarios.length,totalEvidenceCount:scenarios.reduce((n,s)=>n+s.evidence.length,0),staleScenarioCount:scenarios.filter((s)=>s.expectedOutput.expectedFreshnessWarnings).length,conflictingScenarioCount:scenarios.filter((s)=>s.expectedOutput.expectedContradiction).length,dxyComplete:(assetScenarioCounts.dxy??0)>=5,vixComplete:(assetScenarioCounts.vix??0)>=5};};
export const allFixtureSourceIds=()=>new Set(scenarios.flatMap((s)=>s.evidence.map((e)=>e.sourceId)));
export const assertFixtureSourceIdsInRegistry=()=>{const ids=new Set(getProviderSourceRegistrySnapshot(T).sources.map((s)=>s.sourceId)); return [...allFixtureSourceIds()].every((id)=>ids.has(id));};
