import type { OfficialMacroAdapterReadiness, OfficialMacroCoverageReport, OfficialMacroFixturePayload, OfficialMacroNormalizedEvidence, OfficialMacroRegion, OfficialMacroReleaseDescriptor, OfficialMacroSourceDescriptor, OfficialMacroSourceId } from '@elceo/types';
import { getProviderSourceDescriptor, getProviderSourceRegistrySnapshot } from '../provider-source-registry/index';

const sortStrings = <T extends string>(values: readonly T[]): T[] => [...values].sort((a, b) => a.localeCompare(b));

const OFFICIAL_MACRO_SOURCE_REGISTRY = [
  { sourceId: 'federal_reserve_official', providerSourceId: 'federal_reserve_official', displayName: 'Federal Reserve', region: 'us', releaseKinds: sortStrings(['pce']), policyKinds: sortStrings(['minutes', 'policy_decision', 'policy_statement', 'speech']), evidenceClasses: sortStrings(['inflation', 'policy', 'yields_real_rates']), assetRelevance: sortStrings(['btc_usd', 'dxy', 'eur_usd', 'gbp_usd', 'nasdaq_100', 'sp500', 'usd_jpy', 'vix', 'xau_usd']), fixtureMode: 'fixture_only', activationStatus: 'shell_ready', liveBlockedByDefault: true },
  { sourceId: 'fred_macro', providerSourceId: 'fred_macro', displayName: 'FRED', region: 'us', releaseKinds: sortStrings(['gdp', 'labor', 'pce', 'retail_sales']), policyKinds: [], evidenceClasses: sortStrings(['growth', 'inflation', 'labor']), assetRelevance: sortStrings(['dxy', 'eur_usd', 'gbp_usd', 'nasdaq_100', 'sp500', 'xau_usd']), fixtureMode: 'fixture_only', activationStatus: 'shell_ready', liveBlockedByDefault: true },
  { sourceId: 'us_treasury_official', providerSourceId: 'us_treasury_official', displayName: 'US Treasury', region: 'us', releaseKinds: sortStrings(['liquidity_credit']), policyKinds: sortStrings(['debt_supply_context']), evidenceClasses: sortStrings(['yields_real_rates']), assetRelevance: sortStrings(['btc_usd', 'dxy', 'nasdaq_100', 'sp500', 'usd_jpy', 'vix', 'xau_usd']), fixtureMode: 'fixture_only', activationStatus: 'shell_ready', liveBlockedByDefault: true },
  { sourceId: 'bls_official', providerSourceId: 'bls_official', displayName: 'BLS', region: 'us', releaseKinds: sortStrings(['cpi', 'labor', 'nfp']), policyKinds: [], evidenceClasses: sortStrings(['inflation', 'labor']), assetRelevance: sortStrings(['dxy', 'eur_usd', 'gbp_usd', 'nasdaq_100', 'sp500', 'xau_usd']), fixtureMode: 'fixture_only', activationStatus: 'shell_ready', liveBlockedByDefault: true },
  { sourceId: 'bea_official', providerSourceId: 'bea_official', displayName: 'BEA', region: 'us', releaseKinds: sortStrings(['gdp']), policyKinds: [], evidenceClasses: sortStrings(['growth']), assetRelevance: sortStrings(['dxy', 'nasdaq_100', 'sp500']), fixtureMode: 'fixture_only', activationStatus: 'shell_ready', liveBlockedByDefault: true },
  { sourceId: 'census_official', providerSourceId: 'census_official', displayName: 'Census', region: 'us', releaseKinds: sortStrings(['retail_sales']), policyKinds: [], evidenceClasses: sortStrings(['growth']), assetRelevance: sortStrings(['dxy', 'nasdaq_100', 'sp500']), fixtureMode: 'fixture_only', activationStatus: 'shell_ready', liveBlockedByDefault: true },
  { sourceId: 'ism_shell', providerSourceId: 'ism_shell', displayName: 'ISM', region: 'us', releaseKinds: sortStrings(['pmi']), policyKinds: [], evidenceClasses: sortStrings(['growth']), assetRelevance: sortStrings(['dxy', 'nasdaq_100', 'sp500', 'xau_usd']), fixtureMode: 'fixture_only', activationStatus: 'shell_ready', liveBlockedByDefault: true },
  { sourceId: 'ecb_official', providerSourceId: 'ecb_official', displayName: 'ECB', region: 'eurozone', releaseKinds: sortStrings(['hicp']), policyKinds: sortStrings(['policy_decision', 'speech']), evidenceClasses: sortStrings(['inflation', 'policy']), assetRelevance: sortStrings(['de30', 'dxy', 'eur_usd', 'xau_usd']), fixtureMode: 'fixture_only', activationStatus: 'shell_ready', liveBlockedByDefault: true },
  { sourceId: 'boe_official', providerSourceId: 'boe_official', displayName: 'BoE', region: 'uk', releaseKinds: sortStrings(['cpi', 'gdp', 'labor', 'pmi', 'retail_sales']), policyKinds: sortStrings(['policy_decision', 'vote_split']), evidenceClasses: sortStrings(['growth', 'inflation', 'labor', 'policy']), assetRelevance: sortStrings(['dxy', 'gbp_usd', 'nasdaq_100', 'sp500', 'vix']), fixtureMode: 'fixture_only', activationStatus: 'shell_ready', liveBlockedByDefault: true },
  { sourceId: 'boj_official', providerSourceId: 'boj_official', displayName: 'BoJ', region: 'japan', releaseKinds: sortStrings(['cpi', 'industrial_production', 'trade_balance']), policyKinds: sortStrings(['policy_decision']), evidenceClasses: sortStrings(['inflation', 'policy']), assetRelevance: sortStrings(['dxy', 'usd_jpy', 'vix']), fixtureMode: 'fixture_only', activationStatus: 'shell_ready', liveBlockedByDefault: true },
  { sourceId: 'imf_official', providerSourceId: 'imf_official', displayName: 'IMF', region: 'global', releaseKinds: sortStrings(['gdp']), policyKinds: [], evidenceClasses: sortStrings(['macro_context']), assetRelevance: sortStrings(['btc_usd', 'de30', 'nasdaq_100', 'sp500', 'vix']), fixtureMode: 'fixture_only', activationStatus: 'shell_ready', liveBlockedByDefault: true },
  { sourceId: 'world_bank_official', providerSourceId: 'world_bank_official', displayName: 'World Bank', region: 'global', releaseKinds: sortStrings(['gdp']), policyKinds: [], evidenceClasses: sortStrings(['macro_context']), assetRelevance: sortStrings(['btc_usd', 'de30', 'nasdaq_100', 'sp500']), fixtureMode: 'fixture_only', activationStatus: 'shell_ready', liveBlockedByDefault: true },
  { sourceId: 'oecd_official', providerSourceId: 'oecd_official', displayName: 'OECD', region: 'global', releaseKinds: sortStrings(['leading_indicator']), policyKinds: [], evidenceClasses: sortStrings(['growth']), assetRelevance: sortStrings(['de30', 'nasdaq_100', 'sp500', 'vix']), fixtureMode: 'fixture_only', activationStatus: 'shell_ready', liveBlockedByDefault: true },
  { sourceId: 'bis_official', providerSourceId: 'bis_official', displayName: 'BIS', region: 'global', releaseKinds: sortStrings(['liquidity_credit']), policyKinds: [], evidenceClasses: sortStrings(['liquidity_credit']), assetRelevance: sortStrings(['btc_usd', 'dxy', 'nasdaq_100', 'sp500', 'vix']), fixtureMode: 'fixture_only', activationStatus: 'shell_ready', liveBlockedByDefault: true }
] satisfies OfficialMacroSourceDescriptor[];

const SORTED_OFFICIAL_MACRO_SOURCE_REGISTRY: OfficialMacroSourceDescriptor[] = [...OFFICIAL_MACRO_SOURCE_REGISTRY].sort((a, b) => a.sourceId.localeCompare(b.sourceId));

const OFFICIAL_MACRO_RELEASES: OfficialMacroReleaseDescriptor[] = SORTED_OFFICIAL_MACRO_SOURCE_REGISTRY.flatMap((source) => source.releaseKinds.map((releaseKind) => ({ sourceId: source.sourceId, releaseKind, title: `${source.displayName} ${releaseKind}`, frequency: (releaseKind === 'gdp' ? 'quarterly' : 'monthly') as OfficialMacroReleaseDescriptor['frequency'], region: source.region, seriesId: `${source.sourceId}.${releaseKind}` }))).sort((a, b) => `${a.sourceId}.${a.releaseKind}`.localeCompare(`${b.sourceId}.${b.releaseKind}`));

const sourceById = (sourceId: OfficialMacroSourceId): OfficialMacroSourceDescriptor => SORTED_OFFICIAL_MACRO_SOURCE_REGISTRY.find((source) => source.sourceId === sourceId) ?? SORTED_OFFICIAL_MACRO_SOURCE_REGISTRY[0]!;

const OFFICIAL_MACRO_FIXTURES: OfficialMacroFixturePayload[] = OFFICIAL_MACRO_RELEASES.map((release, i) => ({ fixtureId: `fx-${String(i + 1).padStart(3, '0')}`, sourceId: release.sourceId, region: release.region, observedAt: `2026-0${(i % 4) + 1}-15T12:00:00.000Z`, period: '2026-Q1', title: release.title, releaseKind: release.releaseKind, headlineValue: 'placeholder', prior: '1.0', forecast: '1.1', actual: '1.2', surpriseDirection: 'upside', evidenceClass: sourceById(release.sourceId).evidenceClasses[0]!, assetRelevance: sourceById(release.sourceId).assetRelevance, narrativeSummary: `Fixture evidence for ${release.title}.`, freshnessState: 'fresh' }));

export const getOfficialMacroSourceRegistry = (): OfficialMacroSourceDescriptor[] => SORTED_OFFICIAL_MACRO_SOURCE_REGISTRY.map((source) => ({ ...source, releaseKinds: [...source.releaseKinds], policyKinds: [...source.policyKinds], evidenceClasses: [...source.evidenceClasses], assetRelevance: [...source.assetRelevance] }));
export const getOfficialMacroSourceDescriptor = (sourceId: OfficialMacroSourceId): OfficialMacroSourceDescriptor | null => getOfficialMacroSourceRegistry().find((source) => source.sourceId === sourceId) ?? null;
export const listOfficialMacroSourcesByRegion = (region: OfficialMacroRegion): OfficialMacroSourceDescriptor[] => getOfficialMacroSourceRegistry().filter((source) => source.region === region);
export const listOfficialMacroReleaseDescriptors = (sourceId?: OfficialMacroSourceId): OfficialMacroReleaseDescriptor[] => OFFICIAL_MACRO_RELEASES.filter((release) => !sourceId || release.sourceId === sourceId);
export const listOfficialMacroFixturePayloads = (sourceId?: OfficialMacroSourceId): OfficialMacroFixturePayload[] => OFFICIAL_MACRO_FIXTURES.filter((fixture) => !sourceId || fixture.sourceId === sourceId);
export const getOfficialMacroFixturePayload = (sourceId: OfficialMacroSourceId, fixtureId: string): OfficialMacroFixturePayload | null => listOfficialMacroFixturePayloads(sourceId).find((fixture) => fixture.fixtureId === fixtureId) ?? null;

export const normalizeOfficialMacroFixturePayload = (payload: OfficialMacroFixturePayload): OfficialMacroNormalizedEvidence => {
  const base: OfficialMacroNormalizedEvidence = { evidenceId: `official-macro:${payload.sourceId}:${payload.fixtureId}`, sourceId: payload.sourceId, region: payload.region, evidenceClass: payload.evidenceClass, observedAt: payload.observedAt, freshnessState: payload.freshnessState, assetRelevance: sortStrings(payload.assetRelevance), directionalPressure: payload.surpriseDirection === 'upside' ? 'inflationary' : payload.surpriseDirection === 'downside' ? 'disinflationary' : 'neutral', qualityHints: sortStrings(['fixture_only', 'live_blocked', 'official_macro_shell']), narrative: payload.narrativeSummary, rawFixtureId: payload.fixtureId };
  return { ...base, ...(payload.releaseKind ? { releaseKind: payload.releaseKind } : {}), ...(payload.policyKind ? { policyKind: payload.policyKind } : {}) };
};

export const getOfficialMacroAdapterReadiness = (sourceId: OfficialMacroSourceId): OfficialMacroAdapterReadiness => ({ sourceId, providerSourceId: getOfficialMacroSourceDescriptor(sourceId)?.providerSourceId ?? sourceId, status: 'shell_ready', fixtureMode: 'fixture_only', liveBlockedByDefault: true, notes: sortStrings(['fixture_dry_run_only', 'no_api_keys', 'no_live_calls']) });
export const getOfficialMacroCoverageReport = (): OfficialMacroCoverageReport => ({ generatedAt: '2026-05-14T00:00:00.000Z', sources: getOfficialMacroSourceRegistry(), releases: listOfficialMacroReleaseDescriptors(), fixtures: getOfficialMacroSourceRegistry().map((source) => ({ sourceId: source.sourceId, fixtureCount: listOfficialMacroFixturePayloads(source.sourceId).length })).sort((a, b) => a.sourceId.localeCompare(b.sourceId)), allLiveBlockedByDefault: getOfficialMacroSourceRegistry().every((source) => source.liveBlockedByDefault) });
export const assertOfficialMacroSourcesMapToProviderRegistry = (): boolean => getOfficialMacroSourceRegistry().every((source) => !!getProviderSourceDescriptor(source.providerSourceId));
export const assertOfficialMacroSourceIdsInProviderSnapshot = (): boolean => { const ids = new Set(getProviderSourceRegistrySnapshot('2026-01-01T00:00:00.000Z').sources.map((source) => source.sourceId)); return getOfficialMacroSourceRegistry().every((source) => ids.has(source.providerSourceId)); };
