export type InternalPaymentState='created'|'pending_provider'|'processing'|'succeeded'|'failed'|'expired'|'cancelled'|'unknown'|'reconciliation_required'|'refunded'|'partially_refunded'|'reversed'|'chargeback';
export type PaymentProviderMode='disabled'|'local_fake_provider'|'sandbox_stub_for_tests'|'replay_provider_event';
export type FakeProviderOutcome='accepted'|'accepted_response_lost'|'timeout_before_response'|'provider_500_before_accepting'|'provider_500_after_accepting'|'disconnect_during_redirect'|'unknown_result'|'duplicate_provider_reference'|'duplicate_event_id'|'refund'|'partial_refund'|'reversal'|'chargeback';
export type InternalPaymentOperation={internalPaymentOperationId:string;businessIdempotencyKey:string;providerIdempotencyKey:string;subjectUserId:string;targetPlan:string;amount:number;currency:string;provider:string;state:InternalPaymentState;providerPaymentReference:string|null;providerCheckoutSessionReference:string|null;providerEventReferences:string[];version:number;createdAt:string;updatedAt:string;expiresAt:string|null;reconciliationState:'not_required'|'required'|'matched'|'mismatch'|'duplicate_charge_risk';lastProviderComparisonSnapshot:Record<string,unknown>|null;safeErrorCategory:string|null};
type Ledger={effectKey:string;operationId:string;kind:'payment_success'|'refund'|'partial_refund'|'reversal'|'chargeback';amount:number;currency:string;createdAt:string};
type Entitlement={effectKey:string;operationId:string;subjectUserId:string;targetPlan:string;kind:'grant'|'refund'|'partial_refund'|'reversal'|'chargeback';createdAt:string};
type Inbox={eventId:string;provider:string;kind:string;providerPaymentReference:string|null;operationId:string|null;duplicate:boolean;createdAt:string;payload:Record<string,unknown>};
const terminal=new Set<InternalPaymentState>(['succeeded','failed','expired','cancelled','refunded','partially_refunded','reversed','chargeback']);
const allowed:Record<InternalPaymentState,InternalPaymentState[]>= {created:['pending_provider','processing','failed','unknown','reconciliation_required','cancelled','expired'],pending_provider:['processing','succeeded','failed','unknown','reconciliation_required','cancelled','expired'],processing:['succeeded','failed','unknown','reconciliation_required','cancelled','expired'],succeeded:['refunded','partially_refunded','reversed','chargeback'],failed:[],expired:[],cancelled:[],unknown:['reconciliation_required','succeeded','failed','expired','cancelled'],reconciliation_required:['succeeded','failed','expired','cancelled','refunded','partially_refunded','reversed','chargeback'],refunded:[],partially_refunded:['refunded','reversed','chargeback'],reversed:[],chargeback:[]};
export class InternalPaymentRuntime{private operations=new Map<string,InternalPaymentOperation>();private byBusiness=new Map<string,string>();private byProviderKey=new Map<string,string>();private byPaymentRef=new Map<string,string>();private bySessionRef=new Map<string,string>();private inbox=new Map<string,Inbox>();private ledger=new Map<string,Ledger>();private entitlements=new Map<string,Entitlement>();private audit:{key:string;message:string;createdAt:string;data:Record<string,unknown>}[]=[];private locks=new Map<string,Promise<unknown>>();public providerChargeAttempts=0;public providerCharges=new Map<string,string>();constructor(public mode:PaymentProviderMode='local_fake_provider'){}
 resetVolatileProcessState(){this.locks=new Map();}
 private async lock<T>(key:string,fn:()=>Promise<T>):Promise<T>{const prev=this.locks.get(key)??Promise.resolve();let release!:()=>void;const next=new Promise<void>(r=>{release=r});this.locks.set(key,prev.then(()=>next));await prev;try{return await fn();}finally{release();if(this.locks.get(key)===next)this.locks.delete(key);}}
 private id(prefix:string,key:string){let h=0;for(const c of key)h=(h*31+c.charCodeAt(0))>>>0;return `${prefix}_${h.toString(16)}`;}
 private transition(op:InternalPaymentOperation,next:InternalPaymentState,why:string){if(op.state===next)return; if(!allowed[op.state].includes(next)) throw new Error(`illegal_payment_transition:${op.state}->${next}`); op.state=next;op.version++;op.updatedAt=new Date().toISOString();this.audit.push({key:`audit:${op.internalPaymentOperationId}:${op.version}`,message:why,createdAt:op.updatedAt,data:{state:next}})}
 async checkout(input:{subjectUserId:string;targetPlan:string;amount:number;currency:string;businessIdempotencyKey:string;outcome?:FakeProviderOutcome}){const lockKey=`business:${input.subjectUserId}:${input.businessIdempotencyKey}`;return this.lock(lockKey,async()=>{const existingId=this.byBusiness.get(lockKey);if(existingId){const existing=this.operations.get(existingId)!;return {operation:existing,reused:true,providerMode:this.mode};}const now=new Date().toISOString();const op:InternalPaymentOperation={internalPaymentOperationId:this.id('ipo',lockKey),businessIdempotencyKey:lockKey,providerIdempotencyKey:this.id('pik',lockKey),subjectUserId:input.subjectUserId,targetPlan:input.targetPlan,amount:input.amount,currency:input.currency,provider:'local_fake_provider',state:'created',providerPaymentReference:null,providerCheckoutSessionReference:null,providerEventReferences:[],version:1,createdAt:now,updatedAt:now,expiresAt:new Date(Date.now()+30*60_000).toISOString(),reconciliationState:'not_required',lastProviderComparisonSnapshot:null,safeErrorCategory:null};this.operations.set(op.internalPaymentOperationId,op);this.byBusiness.set(lockKey,op.internalPaymentOperationId);this.byProviderKey.set(op.providerIdempotencyKey,op.internalPaymentOperationId);if(this.mode==='disabled'){this.transition(op,'reconciliation_required','provider disabled');op.safeErrorCategory='provider_disabled';op.reconciliationState='required';return {operation:op,reused:false,providerMode:this.mode};}return this.invokeProvider(op,input.outcome??'accepted').then(operation=>({operation,reused:false,providerMode:this.mode}));});}
 private async invokeProvider(op:InternalPaymentOperation,outcome:FakeProviderOutcome){if(terminal.has(op.state)||op.state==='unknown'||op.state==='reconciliation_required')return op;this.transition(op,'pending_provider','provider call prepared');this.providerChargeAttempts++;const ref=this.providerCharges.get(op.providerIdempotencyKey)??this.id('pay',op.providerIdempotencyKey);if(outcome!=='provider_500_before_accepting'&&outcome!=='timeout_before_response')this.providerCharges.set(op.providerIdempotencyKey,ref);if(outcome==='accepted'||outcome==='duplicate_provider_reference'){op.providerPaymentReference=ref;op.providerCheckoutSessionReference=this.id('chk',op.providerIdempotencyKey);this.byPaymentRef.set(ref,op.internalPaymentOperationId);this.bySessionRef.set(op.providerCheckoutSessionReference,op.internalPaymentOperationId);this.transition(op,'processing','provider accepted');return op;}op.safeErrorCategory=outcome;op.reconciliationState='required';op.lastProviderComparisonSnapshot={outcome,providerIdempotencyKey:op.providerIdempotencyKey,providerPaymentReference:this.providerCharges.get(op.providerIdempotencyKey)??null};this.transition(op,outcome==='provider_500_before_accepting'?'failed':outcome==='timeout_before_response'?'unknown':'reconciliation_required',`provider ambiguous:${outcome}`);return op;}
 async webhook(input:{eventId:string;kind:'success'|FakeProviderOutcome;providerPaymentReference?:string|null;providerCheckoutSessionReference?:string|null;operationId?:string|null;payload?:Record<string,unknown>}){return this.lock(`event:${input.eventId}`,async()=>{const existing=this.inbox.get(input.eventId);if(existing)return {duplicate:true,operation:existing.operationId?this.operations.get(existing.operationId)??null:null};let op=input.operationId?this.operations.get(input.operationId)??null:null;if(!op&&input.providerPaymentReference)op=this.operations.get(this.byPaymentRef.get(input.providerPaymentReference)??'')??null;if(!op&&input.providerCheckoutSessionReference)op=this.operations.get(this.bySessionRef.get(input.providerCheckoutSessionReference)??'')??null;this.inbox.set(input.eventId,{eventId:input.eventId,provider:'local_fake_provider',kind:input.kind,providerPaymentReference:input.providerPaymentReference??null,operationId:op?.internalPaymentOperationId??null,duplicate:false,createdAt:new Date().toISOString(),payload:input.payload??{}});if(!op)return {duplicate:false,operation:null};return this.lock(`op:${op.internalPaymentOperationId}`,async()=>{if(input.providerPaymentReference&&!op.providerPaymentReference){op.providerPaymentReference=input.providerPaymentReference;this.byPaymentRef.set(input.providerPaymentReference,op.internalPaymentOperationId);}op.providerEventReferences=[...new Set([...op.providerEventReferences,input.eventId])];if(input.kind==='success'||input.kind==='accepted'){this.transition(op,'succeeded','provider success event');this.effects(op,'payment_success');}else if(input.kind==='refund')this.reversal(op,'refunded','refund');else if(input.kind==='partial_refund')this.reversal(op,'partially_refunded','partial_refund');else if(input.kind==='reversal')this.reversal(op,'reversed','reversal');else if(input.kind==='chargeback')this.reversal(op,'chargeback','chargeback');else if(input.kind==='provider_500_before_accepting'&&op.state!=='succeeded')this.transition(op,'failed','provider failure event');return {duplicate:false,operation:op};});});}
 private effects(op:InternalPaymentOperation,kind:Ledger['kind']){const k=`${op.internalPaymentOperationId}:${kind}`;if(!this.ledger.has(k))this.ledger.set(k,{effectKey:k,operationId:op.internalPaymentOperationId,kind,amount:op.amount,currency:op.currency,createdAt:new Date().toISOString()});const ek=`${op.internalPaymentOperationId}:${kind==='payment_success'?'grant':kind}`;if(!this.entitlements.has(ek))this.entitlements.set(ek,{effectKey:ek,operationId:op.internalPaymentOperationId,subjectUserId:op.subjectUserId,targetPlan:op.targetPlan,kind:kind==='payment_success'?'grant':kind,createdAt:new Date().toISOString()});}
 private reversal(op:InternalPaymentOperation,state:InternalPaymentState,kind:Ledger['kind']){this.transition(op,state,kind);this.effects(op,kind)}
 async reconcile(input:{operationId?:string;businessIdempotencyKey?:string;subjectUserId?:string}){const id=input.operationId??(input.businessIdempotencyKey&&input.subjectUserId?this.byBusiness.get(`business:${input.subjectUserId}:${input.businessIdempotencyKey}`):undefined);const op=id?this.operations.get(id):undefined;if(!op)return {status:'not_found' as const};return this.lock(`op:${op.internalPaymentOperationId}`,async()=>{const ref=this.providerCharges.get(op.providerIdempotencyKey)??null;op.lastProviderComparisonSnapshot={providerPaymentReference:ref,providerIdempotencyKey:op.providerIdempotencyKey,providerChargeCount:[...this.providerCharges.keys()].filter(k=>k===op.providerIdempotencyKey).length};if(ref&&!op.providerPaymentReference){op.providerPaymentReference=ref;this.byPaymentRef.set(ref,op.internalPaymentOperationId);}if(ref&&(op.state==='unknown'||op.state==='reconciliation_required')){this.transition(op,'succeeded','reconciliation matched provider success');this.effects(op,'payment_success');op.reconciliationState='matched';}else if(!ref&&(op.state==='unknown'||op.state==='reconciliation_required'))op.reconciliationState='mismatch';this.audit.push({key:`reconcile:${op.internalPaymentOperationId}:${op.version}:${Date.now()}`,message:'operator reconciliation inspected',createdAt:new Date().toISOString(),data:op.lastProviderComparisonSnapshot});return {status:'ok' as const,operation:op,duplicateChargeRisk:false,localProviderMismatch:op.reconciliationState==='mismatch'};});}
 counts(){return {operations:this.operations.size,providerCharges:this.providerCharges.size,ledger:this.ledger.size,entitlements:this.entitlements.size,inbox:this.inbox.size,audit:this.audit.length};}
 listUnknown(){return [...this.operations.values()].filter(o=>o.state==='unknown'||o.state==='reconciliation_required');}
}
export const internalPaymentRuntime=new InternalPaymentRuntime((process.env.ELCEO_PAYMENT_PROVIDER_MODE as PaymentProviderMode)||'local_fake_provider');
