import type { EvidenceConflictInput, EvidenceQualityReport, EvidenceQualityScore, NormalizedMarketEvidencePayload } from '@elceo/types';
import { getFreshnessPolicyForEvidenceClass } from './quality-policies';
import { deriveConflictStatus, scoreConflict } from './conflict-scoring';
import { deriveFreshnessStatus, scoreFreshness } from './freshness-scoring';
import { combineEvidenceQualityScore, deriveProvenanceKind, deriveUsabilityStatus, scoreCompleteness, scoreSourceQuality } from './quality-scoring';
const parseMeta=(m:string):Record<string,unknown>|null=>{try{const v=JSON.parse(m); return typeof v==='object'&&v!==null?v as Record<string,unknown>:null;}catch{return null;}};
export const evaluateEvidencePayloadQuality=(payload:NormalizedMarketEvidencePayload,evaluatedAt=new Date().toISOString()):EvidenceQualityScore=>{const reasons:string[]=[]; const meta=parseMeta(payload.metadataJson); if(meta===null) reasons.push('malformed_or_missing_metadata'); const provenanceKind=deriveProvenanceKind(payload,meta??undefined); if(provenanceKind==='fixture') reasons.push('fixture_provenance_not_live_ready'); const policy=getFreshnessPolicyForEvidenceClass(payload.evidenceClass as never); const freshnessScore=scoreFreshness(payload.observedAt,evaluatedAt,policy); const freshnessStatus=deriveFreshnessStatus(freshnessScore); if(freshnessStatus==='stale'||freshnessStatus==='expired') reasons.push(`freshness_${freshnessStatus}`); const completenessScore=scoreCompleteness(payload); if(payload.dataQuality==='partial'||payload.dataQuality==='stale'||payload.dataQuality==='failed') reasons.push(`data_quality_${payload.dataQuality}`); const sourceQualityScore=scoreSourceQuality(payload.providerId,provenanceKind,payload.dataQuality); const conflictScore=0; const conflictStatus=deriveConflictStatus(conflictScore); const finalQualityScore=combineEvidenceQualityScore({sourceQualityScore,freshnessScore,completenessScore,conflictScore}); const usabilityStatus=deriveUsabilityStatus(finalQualityScore,freshnessStatus,conflictStatus); return {payloadId:payload.payloadId,evidenceTypeId:payload.evidenceTypeId,evidenceClass:payload.evidenceClass as never,providerId:payload.providerId,asset:payload.asset,region:payload.region,observedAt:payload.observedAt,evaluatedAt,provenanceKind,sourceQualityScore,freshnessScore,completenessScore,conflictScore,finalQualityScore,freshnessStatus,conflictStatus,usabilityStatus,reasons};};
export const evaluateEvidencePayloadsQuality=(payloads:NormalizedMarketEvidencePayload[],evaluatedAt=new Date().toISOString()):EvidenceQualityScore[]=>{const keys=new Map<string,EvidenceConflictInput[]>(); for(const p of payloads){try{const v=JSON.parse(p.valuesJson) as Record<string,unknown>; for(const [k,val] of Object.entries(v)){ if(typeof val==='number'&&Number.isFinite(val)){const key=`${p.evidenceTypeId}|${p.asset??'null'}|${p.region}|${k}`; const list=keys.get(key)??[]; list.push({evidenceTypeId:p.evidenceTypeId,evidenceClass:p.evidenceClass as never,asset:p.asset,region:p.region,observedAt:p.observedAt,providerId:p.providerId,valueKey:k,numericValue:val,tolerance:1,payloadId:p.payloadId}); keys.set(key,list); } }}catch{/* ignore malformed valuesJson for conflict sampling */}} const conflictByPayload=new Map<string,number>(); for(const list of keys.values()){const s=scoreConflict(list); for(const item of list) conflictByPayload.set(item.payloadId,Math.max(conflictByPayload.get(item.payloadId)??0,s));}
return payloads.map((p)=>{const base=evaluateEvidencePayloadQuality(p,evaluatedAt); const conflictScore=conflictByPayload.get(p.payloadId)??0; const conflictStatus=deriveConflictStatus(conflictScore); const finalQualityScore=combineEvidenceQualityScore({...base,conflictScore}); const usabilityStatus=deriveUsabilityStatus(finalQualityScore,base.freshnessStatus,conflictStatus); const reasons=[...base.reasons]; if(conflictScore>0) reasons.push(`conflict_${conflictStatus}`); return {...base,conflictScore,conflictStatus,finalQualityScore,usabilityStatus,reasons};});};
export const buildEvidenceQualityReport=(payloads:NormalizedMarketEvidencePayload[],evaluatedAt=new Date().toISOString()):EvidenceQualityReport=>{const scores=evaluateEvidencePayloadsQuality(payloads,evaluatedAt); const failures=scores.filter(s=>s.usabilityStatus==='blocked').map(s=>s.payloadId); return {generatedAt:evaluatedAt,scores,pass:failures.length===0,failures};};
