import type { EvidenceQualityScore, NormalizedMarketEvidencePayload, ReasoningEvidenceFilterPolicy, ReasoningEvidenceInputAssemblyReport, ReasoningEvidenceInputExclusion, ReasoningEvidenceInputItem, ReasoningEvidenceInputSnapshot } from '@elceo/types';
import { evaluateEvidencePayloadQuality } from '../evidence-quality/index';
import { getDefaultReasoningEvidenceFilterPolicy } from './market-evidence-input-policy';

export const buildReasoningEvidenceInputItem=(payload:NormalizedMarketEvidencePayload,qualityScore:EvidenceQualityScore):ReasoningEvidenceInputItem=>({payloadId:payload.payloadId,evidenceTypeId:payload.evidenceTypeId,evidenceClass:payload.evidenceClass as ReasoningEvidenceInputItem['evidenceClass'],providerId:payload.providerId,asset:payload.asset as ReasoningEvidenceInputItem['asset'],region:payload.region,observedAt:payload.observedAt,normalizedAt:payload.normalizedAt,qualityScore,usabilityStatus:qualityScore.usabilityStatus,freshnessStatus:qualityScore.freshnessStatus,conflictStatus:qualityScore.conflictStatus,dataQuality:payload.dataQuality,valuesJson:payload.valuesJson,metadataJson:payload.metadataJson,reasons:[...qualityScore.reasons]});

type AssembleParams={payloads:NormalizedMarketEvidencePayload[];qualityScores?:EvidenceQualityScore[]|null|undefined;generatedAt:string;asset?:ReasoningEvidenceInputSnapshot['asset'];evidenceClass?:ReasoningEvidenceInputSnapshot['evidenceClass'];filterPolicy?:ReasoningEvidenceFilterPolicy;};
export const assembleReasoningEvidenceInputSnapshot=(params:AssembleParams):ReasoningEvidenceInputSnapshot=>{const policy=params.filterPolicy??getDefaultReasoningEvidenceFilterPolicy(); const map=new Map((params.qualityScores??[]).map((s)=>[s.payloadId,s])); const items:ReasoningEvidenceInputItem[]=[]; const excludedItems:ReasoningEvidenceInputExclusion[]=[]; for(const p of params.payloads){const q=map.get(p.payloadId)??evaluateEvidencePayloadQuality(p,params.generatedAt); const meta=JSON.parse(p.metadataJson||'{}') as Record<string,unknown>; const fixture=q.provenanceKind==='fixture'||meta.sourceMode==='fixture'; if(!policy.includeBlockedEvidence&&q.usabilityStatus==='blocked'){excludedItems.push({payloadId:p.payloadId,reasonCode:'blocked',reason:'blocked evidence excluded by policy'}); continue;} if(!policy.includeExpiredEvidence&&q.freshnessStatus==='expired'){excludedItems.push({payloadId:p.payloadId,reasonCode:'expired',reason:'expired evidence excluded by policy'}); continue;} if(!policy.includeFixtureEvidence&&fixture){excludedItems.push({payloadId:p.payloadId,reasonCode:'fixture',reason:'fixture evidence excluded by policy'}); continue;} if(q.finalQualityScore<policy.minFinalQualityScore){excludedItems.push({payloadId:p.payloadId,reasonCode:'low_quality',reason:'below minFinalQualityScore'}); continue;} items.push(buildReasoningEvidenceInputItem(p,q)); }
items.sort((a,b)=>b.qualityScore.finalQualityScore-a.qualityScore.finalQualityScore||Date.parse(b.observedAt)-Date.parse(a.observedAt)||a.payloadId.localeCompare(b.payloadId));
const capped=items.slice(0,policy.maxEvidenceItems); for(const x of items.slice(policy.maxEvidenceItems)){excludedItems.push({payloadId:x.payloadId,reasonCode:'cap_exceeded',reason:'excluded by maxEvidenceItems cap'});} const warnings:string[]=[]; if(capped.length===0) warnings.push('no_usable_reasoning_evidence_items'); if(capped.length>0&&capped.every((x)=>x.qualityScore.provenanceKind==='fixture')) warnings.push('only_fixture_evidence_included'); return {snapshotId:`reasoning-input|${params.generatedAt}|${params.asset??'all'}|${params.evidenceClass??'all'}`,generatedAt:params.generatedAt,asset:params.asset??null,evidenceClass:params.evidenceClass??null,filterPolicy:policy,items:capped,excludedItems,warnings};};
export const buildReasoningEvidenceInputAssemblyReport=(snapshot:ReasoningEvidenceInputSnapshot):ReasoningEvidenceInputAssemblyReport=>({generatedAt:snapshot.generatedAt,asset:snapshot.asset,evidenceClass:snapshot.evidenceClass,inputItemCount:snapshot.items.length,excludedItemCount:snapshot.excludedItems.length,warnings:[...snapshot.warnings],pass:snapshot.items.length>0});
