import { createHash,createHmac,timingSafeEqual } from 'node:crypto';
import {decodeKoraProviderAmount,encodeKoraProviderAmount,serializeKoraJson,type KoraMoneyCapability} from './kora-money';
const BASE='https://api.korapay.com/merchant';
const obj=(x:unknown)=>x&&typeof x==='object'&&!Array.isArray(x)?x as Record<string,unknown>:{};
const str=(x:unknown)=>typeof x==='string'&&x?x:null;
export function verifyKoraWebhook(data:unknown,signature:string|null,secret:string){if(!signature||!/^[a-f0-9]{64}$/i.test(signature)||!secret)throw new Error('invalid_korapay_signature');const expected=createHmac('sha256',secret).update(JSON.stringify(data)).digest('hex');const a=Buffer.from(expected,'hex'),b=Buffer.from(signature,'hex');if(a.length!==b.length||!timingSafeEqual(a,b))throw new Error('invalid_korapay_signature');return true;}
export function koraEventIdentity(event:string,data:unknown){return `kora_${createHash('sha256').update(`${event}:${JSON.stringify(data)}`).digest('hex')}`;}
export type KoraTruth={reference:string|null;status:string|null;amountExpected:string|null;amountPaid:string|null;currency:string|null;paymentMethod:string|null;paidAt?:string|null;metadata:Record<string,unknown>};
export class KoraPayAdapter{constructor(private secret:string,private fetcher:typeof fetch=fetch){}
 private async call(path:string,init?:RequestInit){const r=await this.fetcher(`${BASE}${path}`,{...init,headers:{Authorization:`Bearer ${this.secret}`,'Content-Type':'application/json',...(init?.headers??{})}});const raw=await r.text();const exact=raw.replace(/("(?:amount|amount_paid)"\s*:\s*)([0-9]+(?:\.[0-9]+)?)/g,'$1"$2"');const body=JSON.parse(exact) as Record<string,unknown>;if(!r.ok)throw Object.assign(new Error('korapay_provider_request_failed'),{status:r.status});return obj(body.data);}
 async initialize(input:{amountMinor:string;moneyCapability:KoraMoneyCapability;currency:string;reference:string;notificationUrl:string;redirectUrl:string;customer:{name:string;email:string};plan:string;interval:string;operationId:string;channels?:string[]}){const amount=encodeKoraProviderAmount(input.amountMinor,input.moneyCapability);const data=await this.call('/api/v1/charges/initialize',{method:'POST',body:serializeKoraJson({currency:input.currency,reference:input.reference,notification_url:input.notificationUrl,redirect_url:input.redirectUrl,customer:input.customer,channels:input.channels,metadata:{operationId:input.operationId,plan:input.plan,billingInterval:input.interval}},amount)});return {checkoutUrl:str(data.checkout_url),reference:str(data.reference)??input.reference};}
 async retrieve(reference:string,moneyCapability:KoraMoneyCapability):Promise<KoraTruth>{const d=await this.call(`/api/v1/charges/${encodeURIComponent(reference)}`);const currency=str(d.currency)?.toUpperCase()??null;return {reference:str(d.reference),status:str(d.status),amountExpected:currency&&d.amount!=null?decodeKoraProviderAmount(String(d.amount),moneyCapability):null,amountPaid:currency&&d.amount_paid!=null?decodeKoraProviderAmount(String(d.amount_paid),moneyCapability):null,currency,paymentMethod:str(d.payment_method),paidAt:str(d.paid_at)??str(d.created_at),metadata:obj(d.metadata)};}
}
export function validateKoraTruth(q:{reference:string;amountMinor:string;currency:string;plan:string;interval:string;operationId:string},t:KoraTruth){const okay=t.reference===q.reference&&t.status==='success'&&t.amountExpected===q.amountMinor&&(t.amountPaid===null||t.amountPaid===q.amountMinor)&&t.currency===q.currency&&t.metadata.operationId===q.operationId&&t.metadata.plan===q.plan&&t.metadata.billingInterval===q.interval;if(!okay)throw new Error('provider_commercial_mismatch');return true;}
