import type { NormalizedMarketEvidencePayload } from '@elceo/types';import { buildMetadataJson,buildNormalizedPayloadId,buildValuesJson,clampConfidenceScore } from '../normalization-helpers';import type { CotFixtureRequest,CotReportKind,CotReportRow } from './cot-contracts';
export const COT_PROVIDER_ID='cftc_cot';
export function mapAssetToCotMarket(asset:string|null):string{const m:Record<string,string>={xau_usd:'Gold',eur_usd:'Euro FX',gbp_usd:'British Pound',usd_jpy:'Japanese Yen',btc_usd:'Bitcoin',nasdaq_100:'Nasdaq 100'};return asset?(m[asset]??asset):'Unknown';}
export function deriveNetNonCommercial(row:CotReportRow):number|null{return row.nonCommercialLong!==null&&row.nonCommercialShort!==null?row.nonCommercialLong-row.nonCommercialShort:null;}
const direction=(long:number|null|undefined,short:number|null|undefined):'bullish'|'bearish'|'neutral'|'mixed'=>long==null||short==null?'mixed':long>short?'bullish':long<short?'bearish':'neutral';
export function derivePositioningSentiment(row:CotReportRow,kind?:CotReportKind):'bullish'|'bearish'|'neutral'|'mixed'{const resolved=kind??(row.nonCommercialLong!==null||row.nonCommercialShort!==null?'legacy_futures_only':row.managedMoneyLong!=null||row.managedMoneyShort!=null?'disaggregated':'traders_in_financial_futures');if(resolved==='legacy_futures_only')return direction(row.nonCommercialLong,row.nonCommercialShort);if(resolved==='disaggregated')return direction(row.managedMoneyLong,row.managedMoneyShort);return direction(row.leveragedFundsLong,row.leveragedFundsShort);}
function complete(row:CotReportRow,kind:CotReportKind):boolean{if(kind==='legacy_futures_only')return[row.commercialLong,row.commercialShort,row.nonCommercialLong,row.nonCommercialShort,row.nonCommercialSpreading].every(v=>v!==null);if(kind==='disaggregated')return[row.producerMerchantLong,row.producerMerchantShort,row.swapDealerLong,row.swapDealerShort,row.swapDealerSpreading,row.managedMoneyLong,row.managedMoneyShort,row.managedMoneySpreading,row.otherReportablesLong,row.otherReportablesShort,row.otherReportablesSpreading].every(v=>v!=null);return[row.dealerLong,row.dealerShort,row.assetManagerLong,row.assetManagerShort,row.leveragedFundsLong,row.leveragedFundsShort,row.otherReportablesLong,row.otherReportablesShort].every(v=>v!==null);}
export function buildCotPositioningPayload(request:CotFixtureRequest,row:CotReportRow,providerId=COT_PROVIDER_ID):NormalizedMarketEvidencePayload{if(!Number.isFinite(row.openInterest)||row.openInterest<0)throw new Error('cot_invalid_open_interest');const values={oi:row.openInterest,cl:row.commercialLong,cs:row.commercialShort,ncl:row.nonCommercialLong,ncs:row.nonCommercialShort,nsp:row.nonCommercialSpreading,pml:row.producerMerchantLong??null,pms:row.producerMerchantShort??null,sdl:row.swapDealerLong??null,sds:row.swapDealerShort??null,sdsp:row.swapDealerSpreading??null,mml:row.managedMoneyLong??null,mms:row.managedMoneyShort??null,mmsp:row.managedMoneySpreading??null,dl:row.dealerLong,ds:row.dealerShort,aml:row.assetManagerLong,ams:row.assetManagerShort,lfl:row.leveragedFundsLong,lfs:row.leveragedFundsShort,orl:row.otherReportablesLong,ors:row.otherReportablesShort,orsp:row.otherReportablesSpreading??null,nnc:request.reportKind==='legacy_futures_only'?deriveNetNonCommercial(row):null};if(Object.values(values).some(x=>x!==null&&!Number.isFinite(x)))throw new Error('cot_invalid_numeric_field');const isComplete=complete(row,request.reportKind),evidenceClass=request.reportKind==='legacy_futures_only'?'cot_positioning':'futures_positioning';return{payloadId:buildNormalizedPayloadId(providerId,'cot_positioning',new Date(row.reportDate).toISOString(),row.asset),evidenceTypeId:'cot_positioning',evidenceClass,providerId,sourceId:row.cftcMarketCode??row.marketName,region:request.region??'united_states',asset:row.asset,observedAt:new Date(row.reportDate).toISOString(),publishedAt:null,normalizedAt:request.requestedAt,confidenceScore:clampConfidenceScore(isComplete?92:68),dataQuality:isComplete?'high':'partial',valuesJson:buildValuesJson(values),metadataJson:buildMetadataJson({reportKind:request.reportKind,cftcMarketCode:row.cftcMarketCode,exchangeName:row.exchangeName,derivedSentiment:derivePositioningSentiment(row,request.reportKind),sourceMapping:mapAssetToCotMarket(row.asset),reportKindComplete:isComplete})};}
export function normalizeCotRows(request:CotFixtureRequest,rows:CotReportRow[],providerId=COT_PROVIDER_ID):NormalizedMarketEvidencePayload[]{return rows.map(r=>buildCotPositioningPayload(request,r,providerId));}
