import type { CotFixtureResponse } from './cot-contracts';

const R='2026-03-31T00:00:00.000Z';
export const COT_FIXTURES: Record<string, CotFixtureResponse> = {
  xau_usd:{request:{asset:'xau_usd',reportKind:'legacy_futures_only',requestedAt:R,region:'united_states'},rows:[{reportDate:R,marketName:'Gold',cftcMarketCode:'088691',exchangeName:'COMEX',asset:'xau_usd',openInterest:450000,commercialLong:210000,commercialShort:250000,nonCommercialLong:165000,nonCommercialShort:120000,nonCommercialSpreading:22000,dealerLong:null,dealerShort:null,assetManagerLong:null,assetManagerShort:null,leveragedFundsLong:null,leveragedFundsShort:null,otherReportablesLong:18000,otherReportablesShort:14000}]},
  eur_usd:{request:{asset:'eur_usd',reportKind:'legacy_futures_only',requestedAt:R,region:'united_states'},rows:[{reportDate:R,marketName:'Euro FX',cftcMarketCode:'099741',exchangeName:'CME',asset:'eur_usd',openInterest:600000,commercialLong:190000,commercialShort:280000,nonCommercialLong:260000,nonCommercialShort:180000,nonCommercialSpreading:30000,dealerLong:null,dealerShort:null,assetManagerLong:null,assetManagerShort:null,leveragedFundsLong:null,leveragedFundsShort:null,otherReportablesLong:25000,otherReportablesShort:22000}]},
  gbp_usd:{request:{asset:'gbp_usd',reportKind:'legacy_futures_only',requestedAt:R,region:'united_states'},rows:[{reportDate:R,marketName:'British Pound',cftcMarketCode:'096742',exchangeName:'CME',asset:'gbp_usd',openInterest:240000,commercialLong:70000,commercialShort:110000,nonCommercialLong:105000,nonCommercialShort:65000,nonCommercialSpreading:12000,dealerLong:null,dealerShort:null,assetManagerLong:null,assetManagerShort:null,leveragedFundsLong:null,leveragedFundsShort:null,otherReportablesLong:8000,otherReportablesShort:9000}]},
  usd_jpy:{request:{asset:'usd_jpy',reportKind:'legacy_futures_only',requestedAt:R,region:'united_states'},rows:[{reportDate:R,marketName:'Japanese Yen',cftcMarketCode:'097741',exchangeName:'CME',asset:'usd_jpy',openInterest:310000,commercialLong:130000,commercialShort:90000,nonCommercialLong:90000,nonCommercialShort:140000,nonCommercialSpreading:10000,dealerLong:null,dealerShort:null,assetManagerLong:null,assetManagerShort:null,leveragedFundsLong:null,leveragedFundsShort:null,otherReportablesLong:7000,otherReportablesShort:9000}]},
  btc_usd:{request:{asset:'btc_usd',reportKind:'traders_in_financial_futures',requestedAt:R,region:'united_states'},rows:[{reportDate:R,marketName:'Bitcoin',cftcMarketCode:'133741',exchangeName:'CME',asset:'btc_usd',openInterest:22000,commercialLong:null,commercialShort:null,nonCommercialLong:null,nonCommercialShort:null,nonCommercialSpreading:null,dealerLong:4500,dealerShort:3900,assetManagerLong:2500,assetManagerShort:1700,leveragedFundsLong:6500,leveragedFundsShort:7200,otherReportablesLong:1100,otherReportablesShort:900}]},
  nasdaq_100:{request:{asset:'nasdaq_100',reportKind:'disaggregated',requestedAt:R,region:'united_states'},rows:[{reportDate:R,marketName:'Nasdaq 100',cftcMarketCode:'209742',exchangeName:'CME',asset:'nasdaq_100',openInterest:340000,commercialLong:null,commercialShort:null,nonCommercialLong:150000,nonCommercialShort:170000,nonCommercialSpreading:18000,dealerLong:44000,dealerShort:41000,assetManagerLong:80000,assetManagerShort:70000,leveragedFundsLong:50000,leveragedFundsShort:62000,otherReportablesLong:10000,otherReportablesShort:9000}]}
};
