import type { AdminAuditEvent, AdminAuditTimeline, AdminFreshnessSummary, AdminOpsSummary, AdminProviderCapabilitySummary, AdminRuntimeSnapshot, AdminSystemSummary } from '@elceo/types';
import { SNAPSHOT_DOMAIN_KINDS, SNAPSHOT_REFRESH_RUN_STATUSES, OPS_JOB_KINDS, OPS_JOB_RUN_STATUSES } from '@elceo/types';
import { isEnumValue, isIsoDateString, isNonEmptyString, isObjectRecord, isStringArray, type SchemaValidationResult } from './validation-utils';
const HS=['healthy','attention_needed','degraded','critical'] as const; const CS=['healthy','stale','degraded','failed','unknown'] as const; const AK=['ingestion_run','refresh_run','ops_run','reasoning_run','notification_decision','notification_outbox','notification_receipt','notification_feedback','journal_case','journal_influence','analytics_snapshot','coaching_snapshot','portfolio_snapshot','workspace_snapshot'] as const; const SV=['info','warning','error','critical'] as const;
const int=(v:unknown)=>Number.isInteger(v)&&Number(v)>=0;
export function validateAdminSystemSummary(i:unknown,p=''):SchemaValidationResult<AdminSystemSummary>{const e:string[]=[]; if(!isObjectRecord(i)) return {ok:false,errors:[`${p}AdminSystemSummary must be object`]}; if(!isIsoDateString(i.generatedAt)) e.push(`${p}generatedAt must be ISO date string`); if(!isEnumValue(i.overallHealth,HS)) e.push(`${p}overallHealth is invalid`); for(const k of ['ingestionStatus','reasoningStatus','notificationsStatus','refreshStatus','opsStatus','workspaceStatus'] as const){ if(!isEnumValue(i[k],CS)) e.push(`${p}${k} is invalid`);} for(const k of ['blockedOpsRunCount','failedOpsRunCount','staleFreshnessCount','failedFreshnessCount','degradedNotificationTargetCount','criticalReceiptCount'] as const){if(!int(i[k])) e.push(`${p}${k} must be integer >= 0`);} if(!(i.latestRefreshRunStatus===null||isEnumValue(i.latestRefreshRunStatus,SNAPSHOT_REFRESH_RUN_STATUSES))) e.push(`${p}latestRefreshRunStatus is invalid`); if(!(i.latestOpsRunStatus===null||isEnumValue(i.latestOpsRunStatus,OPS_JOB_RUN_STATUSES))) e.push(`${p}latestOpsRunStatus is invalid`); if(!(i.latestIngestionRunStatus===null||isNonEmptyString(i.latestIngestionRunStatus))) e.push(`${p}latestIngestionRunStatus must be string or null`); return e.length?{ok:false,errors:e}:{ok:true,value:i as AdminSystemSummary};}
export function validateAdminRuntimeSnapshot(i:unknown,p=''):SchemaValidationResult<AdminRuntimeSnapshot>{if(!isObjectRecord(i)) return {ok:false,errors:[`${p}AdminRuntimeSnapshot must be object`]}; const e:string[]=[]; if(!isNonEmptyString(i.snapshotId)) e.push(`${p}snapshotId must be non-empty string`); if(!isIsoDateString(i.createdAt)) e.push(`${p}createdAt must be ISO date string`); const s=validateAdminSystemSummary(i.summary,`${p}summary.`); if(!s.ok) e.push(...(s as {ok:false;errors:string[]}).errors); return e.length?{ok:false,errors:e}:{ok:true,value:i as AdminRuntimeSnapshot};}
export function validateAdminAuditEvent(i:unknown,p=''):SchemaValidationResult<AdminAuditEvent>{const e:string[]=[]; if(!isObjectRecord(i)) return {ok:false,errors:[`${p}AdminAuditEvent must be object`]}; for(const k of ['eventId','title','summary','subjectId','metadataJson'] as const){ if(!isNonEmptyString(i[k])) e.push(`${p}${k} must be non-empty string`);} if(!isEnumValue(i.kind,AK)) e.push(`${p}kind is invalid`); if(!isEnumValue(i.severity,SV)) e.push(`${p}severity is invalid`); if(!isIsoDateString(i.occurredAt)) e.push(`${p}occurredAt must be ISO date string`); if(!isEnumValue(i.subjectKind,['user','workspace','ops','global'] as const)) e.push(`${p}subjectKind is invalid`); for (const k of ['linkedRunId','linkedEntityId','linkedSnapshotId'] as const){ if(!(i[k]===null||isNonEmptyString(i[k]))) e.push(`${p}${k} must be non-empty string or null`);} return e.length?{ok:false,errors:e}:{ok:true,value:i as AdminAuditEvent};}
export function validateAdminAuditTimeline(i:unknown,p=''):SchemaValidationResult<AdminAuditTimeline>{if(!isObjectRecord(i)) return {ok:false,errors:[`${p}AdminAuditTimeline must be object`]}; const e:string[]=[]; if(!isIsoDateString(i.generatedAt)) e.push(`${p}generatedAt must be ISO date string`); if(!Array.isArray(i.events)) e.push(`${p}events must be array`); else i.events.forEach((ev,idx)=>{const v=validateAdminAuditEvent(ev,`${p}events[${idx}].`); if(!v.ok) e.push(...(v as {ok:false;errors:string[]}).errors);}); return e.length?{ok:false,errors:e}:{ok:true,value:i as AdminAuditTimeline};}
export function validateAdminProviderCapabilitySummary(i:unknown,p=''):SchemaValidationResult<AdminProviderCapabilitySummary>{if(!isObjectRecord(i)) return {ok:false,errors:[`${p}AdminProviderCapabilitySummary must be object`]}; const e:string[]=[]; if(!isIsoDateString(i.generatedAt)) e.push(`${p}generatedAt must be ISO date string`); for (const k of ['notificationProviders','ingestionProviders'] as const){ if(!Array.isArray(i[k])) e.push(`${p}${k} must be array`);} return e.length?{ok:false,errors:e}:{ok:true,value:i as AdminProviderCapabilitySummary};}
export function validateAdminFreshnessSummary(i:unknown,p=''):SchemaValidationResult<AdminFreshnessSummary>{if(!isObjectRecord(i)) return {ok:false,errors:[`${p}AdminFreshnessSummary must be object`]}; const e:string[]=[]; if(!isIsoDateString(i.generatedAt)) e.push(`${p}generatedAt must be ISO date string`); for(const k of ['totalDomains','freshCount','staleCount','missingCount','failedCount'] as const){if(!int(i[k])) e.push(`${p}${k} must be integer >= 0`);} if(!Array.isArray(i.domainsNeedingRefresh)) e.push(`${p}domainsNeedingRefresh must be array`); else i.domainsNeedingRefresh.forEach((d,idx)=>{if(!isEnumValue(d,SNAPSHOT_DOMAIN_KINDS)) e.push(`${p}domainsNeedingRefresh[${idx}] is invalid`);}); return e.length?{ok:false,errors:e}:{ok:true,value:i as AdminFreshnessSummary};}
export function validateAdminOpsSummary(i:unknown,p=''):SchemaValidationResult<AdminOpsSummary>{if(!isObjectRecord(i)) return {ok:false,errors:[`${p}AdminOpsSummary must be object`]}; const e:string[]=[]; if(!isIsoDateString(i.generatedAt)) e.push(`${p}generatedAt must be ISO date string`); for(const k of ['totalRecentRuns','failedRecentRuns','partialRecentRuns','blockedRecentRuns','staleLeaseCount'] as const){if(!int(i[k])) e.push(`${p}${k} must be integer >= 0`);} if(!(i.mostRecentFailureJobKind===null||isEnumValue(i.mostRecentFailureJobKind,OPS_JOB_KINDS))) e.push(`${p}mostRecentFailureJobKind is invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:i as AdminOpsSummary};}
