import type { BillingAdminOperationalSummary, BillingAdminSubjectSnapshot, BillingOperationalSummaryLite, BillingReconciliationFailureRecord, BillingRetryCandidate } from '@elceo/types';
import { validateBillingLifecycleSnapshot, validateBillingReconciliationRun } from './billing-lifecycle.schema';
import { validateBillingPolicySnapshot, validateBillingPolicyTransition } from './billing-policy.schema';
import { isBoolean, isEnumValue, isIsoDateString, isObjectRecord, type SchemaValidationResult } from './validation-utils';

const health=['healthy','attention_needed','degraded','critical'] as const; const provider=['stripe','manual_test','internal_import'] as const; const severity=['info','warning','restriction','suspension_candidate'] as const;
const failure=['subject_resolution_failed','provider_mapping_missing','provider_mapping_fallback_free','entitlement_sync_failed','persistence_failed','policy_restricted','policy_free_fallback','replay_deserialize_failed','unknown_failure'] as const;
const reason=['latest_reconciliation_failed','provider_mapping_fallback_free','restricted_due_to_past_due','restricted_due_to_paused','restricted_due_to_incomplete','pending_re_evaluation_after_recovery','missing_subscription_after_provider_event'] as const;
const op=['healthy','restricted','degraded','free_fallback'] as const; const sub=['trialing','active','past_due','paused','canceled','incomplete','incomplete_expired'] as const;
const rec=['success','partial_success','failed','skipped'] as const; const decision=['premium_active_ok','premium_trial_ok','premium_paused_restricted','premium_past_due_restricted','premium_incomplete_restricted','premium_incomplete_expired_free_fallback','premium_canceled_free_fallback','premium_recovered_to_active','free_default_ok','admin_internal_override_preserved'] as const;
const plan=['free','premium','admin_internal'] as const; const account=['active','suspended','restricted','canceled'] as const;
const nonEmpty=(v:unknown)=>typeof v==='string'&&v.trim().length>0;

export const validateBillingOperationalSummaryLite=(i:unknown):SchemaValidationResult<BillingOperationalSummaryLite>=>!isObjectRecord(i)?{ok:false,errors:['operationalState must be object']}:!isEnumValue(i.operationalState,op)||!nonEmpty(i.summary)?{ok:false,errors:['operationalState.summary invalid']}:{ok:true,value:i as BillingOperationalSummaryLite};
export const validateBillingAdminOperationalSummary=(i:unknown):SchemaValidationResult<BillingAdminOperationalSummary>=>!isObjectRecord(i)?{ok:false,errors:['summary must be object']}:!isIsoDateString(i.generatedAt)||!isEnumValue(i.healthState,health)?{ok:false,errors:['generatedAt/healthState invalid']}:['totalSubjectsWithBillingState','activePremiumCount','trialingPremiumCount','restrictedPremiumCount','freeFallbackCount','failedRecentReconciliations','degradedRecentReconciliations','providerMappingFallbackCount','recentPolicyRestrictionCount','recentRecoveredCount'].some((k)=>typeof i[k] !=='number')?{ok:false,errors:['count fields must be number']}:!(i.latestReconciliationStatus===null||isEnumValue(i.latestReconciliationStatus,rec))||!(i.latestPolicyDecisionCode===null||isEnumValue(i.latestPolicyDecisionCode,decision))?{ok:false,errors:['latest status fields invalid']}:{ok:true,value:i as BillingAdminOperationalSummary};
export const validateBillingReconciliationFailureRecord=(i:unknown):SchemaValidationResult<BillingReconciliationFailureRecord>=>!isObjectRecord(i)?{ok:false,errors:['failure must be object']}:!nonEmpty(i.failureId)||i.subjectKind!=='user'||!nonEmpty(i.subjectId)||!isEnumValue(i.providerKind,provider)?{ok:false,errors:['identity invalid']}:!(i.reconciliationRunId===null||nonEmpty(i.reconciliationRunId))||!(i.sourceEventId===null||nonEmpty(i.sourceEventId))||!isEnumValue(i.failureKind,failure)||!isEnumValue(i.severity,severity)||!nonEmpty(i.summary)||!isBoolean(i.retryCandidate)||!isIsoDateString(i.occurredAt)||typeof i.metadataJson!=='string'?{ok:false,errors:['failure fields invalid']}:{ok:true,value:i as BillingReconciliationFailureRecord};
export const validateBillingRetryCandidate=(i:unknown):SchemaValidationResult<BillingRetryCandidate>=>!isObjectRecord(i)?{ok:false,errors:['candidate must be object']}:!nonEmpty(i.candidateId)||i.subjectKind!=='user'||!nonEmpty(i.subjectId)||!isEnumValue(i.providerKind,provider)||!isEnumValue(i.reason,reason)?{ok:false,errors:['candidate identity/reason invalid']}:!(i.latestReconciliationRunId===null||nonEmpty(i.latestReconciliationRunId))||!(i.latestPolicyTransitionId===null||nonEmpty(i.latestPolicyTransitionId))||!(i.latestSubscriptionState===null||isEnumValue(i.latestSubscriptionState,sub))||!isEnumValue(i.currentPlanKind,plan)||!isEnumValue(i.currentAccountState,account)||!isIsoDateString(i.createdAt)?{ok:false,errors:['candidate fields invalid']}:{ok:true,value:i as BillingRetryCandidate};
export const validateBillingAdminSubjectSnapshot=(i:unknown):SchemaValidationResult<BillingAdminSubjectSnapshot>=>!isObjectRecord(i)?{ok:false,errors:['snapshot must be object']}:!isIsoDateString(i.generatedAt)||i.subjectKind!=='user'||!nonEmpty(i.subjectId)?{ok:false,errors:['snapshot identity invalid']}:!validateBillingLifecycleSnapshot(i.lifecycleSnapshot).ok||!validateBillingPolicySnapshot(i.policySnapshot).ok?{ok:false,errors:['snapshot child invalid']}:!(i.latestReconciliationRun===null||validateBillingReconciliationRun(i.latestReconciliationRun).ok)||!(i.latestPolicyTransition===null||validateBillingPolicyTransition(i.latestPolicyTransition).ok)||!(i.operationalState===null||validateBillingOperationalSummaryLite(i.operationalState).ok)?{ok:false,errors:['snapshot relation invalid']}:{ok:true,value:i as BillingAdminSubjectSnapshot};
