import type { CommercialEntitlementCoverageReport, CommercialFeatureAccessRequest, CommercialFeatureAccessResult, CommercialPaymentReadinessCheck, CommercialPlanCatalog, CommercialPlanDescriptor, CommercialProfileSocialIdentifier, CommercialSubscriptionWallResult, FocusPlanDescriptor, KickOffTrialDescriptor, UserCommercialEntitlementSnapshot } from '@elceo/types';
import { isEnumValue, isIsoDateString, isObjectRecord, type SchemaValidationResult } from './validation-utils';

const planCodes=['kick_off','focus_plan'] as const; const intervals=['monthly','quarterly','yearly'] as const; const featureKeys=['dashboard.chart','dashboard.evidence_score','dashboard.macro_headlines','journal.page','premium.full_access'] as const; const socialKinds=['linkedin_address','telegram_id','x_username'] as const;
const secrets=/(api[_-]?key|secret|token|password)/i; const banned=/(buy|sell|hold|profit promise)/i;
const hasBad=(s:string)=>secrets.test(s)||banned.test(s)||/[<>]/.test(s)||/javascript:/i.test(s);

export const validateCommercialPlanDescriptor=(i:unknown):SchemaValidationResult<CommercialPlanDescriptor>=>!isObjectRecord(i)?{ok:false,errors:['plan descriptor must be object']}:!isEnumValue(i.planCode,planCodes)||!['Kick off','Focus Plan'].includes(String(i.displayName))||!Array.isArray(i.billingIntervals)||i.billingIntervals.some((x)=>!isEnumValue(x,intervals))?{ok:false,errors:['plan descriptor invalid']}:{ok:true,value:i as CommercialPlanDescriptor};
export const validateKickOffTrialDescriptor=(i:unknown):SchemaValidationResult<KickOffTrialDescriptor>=>!isObjectRecord(i)?{ok:false,errors:['kick off descriptor must be object']}:validateCommercialPlanDescriptor(i).ok!==true||i.planCode!=='kick_off'||i.trialDurationDays!==3||!Array.isArray(i.featureAllowlist)||[...i.featureAllowlist].sort().join(',')!=='dashboard.chart,dashboard.evidence_score,dashboard.macro_headlines,journal.page'?{ok:false,errors:['kick off descriptor invalid']}:{ok:true,value:i as KickOffTrialDescriptor};
export const validateFocusPlanDescriptor=(i:unknown):SchemaValidationResult<FocusPlanDescriptor>=>!isObjectRecord(i)||validateCommercialPlanDescriptor(i).ok!==true||i.planCode!=='focus_plan'||i.pricingAuthority!=='commercial_price_versions'||i.priceConfiguredAtCheckout!==true?{ok:false,errors:['focus descriptor invalid']}:{ok:true,value:i as FocusPlanDescriptor};
export const validateCommercialPlanCatalog=(i:unknown):SchemaValidationResult<CommercialPlanCatalog>=>!isObjectRecord(i)||!Array.isArray(i.plans)||i.plans.length!==2||!validateKickOffTrialDescriptor(i.plans[0]).ok||!validateFocusPlanDescriptor(i.plans[1]).ok?{ok:false,errors:['catalog invalid']}:{ok:true,value:i as CommercialPlanCatalog};

export const validateCommercialProfileSocialIdentifier=(i:unknown):SchemaValidationResult<CommercialProfileSocialIdentifier>=>!isObjectRecord(i)||!isEnumValue(i.kind,socialKinds)||typeof i.value!=='string'||i.value.trim().length<2||hasBad(i.value)?{ok:false,errors:['social identifier invalid']}:{ok:true,value:{kind:i.kind,value:i.value.trim().replace(/^@/,'')}};
export const validateUserCommercialEntitlementSnapshot=(i:unknown):SchemaValidationResult<UserCommercialEntitlementSnapshot>=>!isObjectRecord(i)||typeof i.userId!=='string'||!isIsoDateString(i.nowIso)||!(i.trialStartedAt===null||isIsoDateString(i.trialStartedAt))||!(i.activePlanCode===null||isEnumValue(i.activePlanCode,planCodes))||typeof i.subscriptionActive!=='boolean'||!Array.isArray(i.socialIdentifiers)?{ok:false,errors:['snapshot invalid']}:{ok:true,value:i as UserCommercialEntitlementSnapshot};
export const validateCommercialFeatureAccessRequest=(i:unknown):SchemaValidationResult<CommercialFeatureAccessRequest>=>!isObjectRecord(i)||!validateUserCommercialEntitlementSnapshot(i.snapshot).ok||!isEnumValue(i.featureKey,featureKeys)?{ok:false,errors:['feature access request invalid']}:{ok:true,value:i as CommercialFeatureAccessRequest};
export const validateCommercialSubscriptionWallResult=(i:unknown):SchemaValidationResult<CommercialSubscriptionWallResult>=>!isObjectRecord(i)||typeof i.required!=='boolean'||!isEnumValue(i.reason,['subscription_required','feature_not_in_trial_allowlist','focus_plan_inactive'] as const)||i.targetPlanCode!=='focus_plan'?{ok:false,errors:['subscription wall invalid']}:{ok:true,value:i as CommercialSubscriptionWallResult};
export const validateCommercialFeatureAccessResult=(i:unknown):SchemaValidationResult<CommercialFeatureAccessResult>=>!isObjectRecord(i)||!isEnumValue(i.decision,['allow','deny'] as const)||!isEnumValue(i.status,['active','trial_active','inactive','subscription_required'] as const)||!isEnumValue(i.reason,['feature_allowed','subscription_required','feature_not_in_trial_allowlist','focus_plan_inactive'] as const)||!(i.subscriptionWall===null||validateCommercialSubscriptionWallResult(i.subscriptionWall).ok)?{ok:false,errors:['feature access result invalid']}:{ok:true,value:i as CommercialFeatureAccessResult};
export const validateCommercialPaymentReadinessCheck=(i:unknown):SchemaValidationResult<CommercialPaymentReadinessCheck>=>!isObjectRecord(i)||!isEnumValue(i.status,['eligible','blocked'] as const)||!isEnumValue(i.reason,['ready','missing_social_identifier'] as const)||!Array.isArray(i.normalizedIdentifiers)||i.normalizedIdentifiers.some((x)=>!validateCommercialProfileSocialIdentifier(x).ok)||(i.status==='eligible'&&i.normalizedIdentifiers.length<1)?{ok:false,errors:['payment readiness invalid']}:{ok:true,value:i as CommercialPaymentReadinessCheck};
export const validateCommercialEntitlementCoverageReport=(i:unknown):SchemaValidationResult<CommercialEntitlementCoverageReport>=>!isObjectRecord(i)||!isIsoDateString(i.generatedAt)||!Array.isArray(i.kickOffAllowlist)||i.kickOffAllowlist.some((x)=>!isEnumValue(x,featureKeys))||typeof i.focusPlanPremiumEnabled!=='boolean'||i.providerCallsPerformed!==false?{ok:false,errors:['coverage report invalid']}:{ok:true,value:i as CommercialEntitlementCoverageReport};
