import { createHash } from 'node:crypto';
import { EVIDENCE_WEIGHT_HORIZONS, LAUNCH_ASSET_SYMBOLS, type KickOffDashboardContextArtifact, type KickOffDashboardContextPayloadV1, type KickOffDashboardViewModelV1, type KickOffMacroHeadline } from '@elceo/types';
import { isFiniteNumber, isIsoDateString, isObjectRecord, isNonEmptyString, type SchemaValidationResult } from './validation-utils';

const exact=(value:Record<string,unknown>,keys:readonly string[])=>Object.keys(value).length===keys.length&&Object.keys(value).every(key=>keys.includes(key));
const canonicalize=(value:unknown):unknown=>Array.isArray(value)?value.map(canonicalize):value&&typeof value==='object'?Object.fromEntries(Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([key,child])=>[key,canonicalize(child)])):value;
const integrity=(value:unknown)=>`sha256:${createHash('sha256').update(JSON.stringify(canonicalize(value))).digest('hex')}`;
const supportedAsset=(value:unknown)=>typeof value==='string'&&(LAUNCH_ASSET_SYMBOLS as readonly string[]).includes(value);
const supportedHorizon=(value:unknown)=>typeof value==='string'&&(EVIDENCE_WEIGHT_HORIZONS as readonly string[]).includes(value);
const nonEmpty=(value:unknown)=>isNonEmptyString(value);
const score=(value:unknown)=>isFiniteNumber(value)&&value>=0&&value<=100;

export function validateKickOffMacroHeadline(input:unknown,evaluatedAt?:string):SchemaValidationResult<KickOffMacroHeadline>{
  if(!isObjectRecord(input)||!exact(input,['headline_id','title','source_name','source_url','published_at','freshness'])||!nonEmpty(input.headline_id)||!nonEmpty(input.title)||!(input.source_name===null||nonEmpty(input.source_name))||!(input.source_url===null||nonEmpty(input.source_url))||!isIsoDateString(input.published_at)||!['fresh','aging'].includes(String(input.freshness))||(evaluatedAt!==undefined&&Date.parse(input.published_at as string)>Date.parse(evaluatedAt)))return{ok:false,errors:['kick off headline invalid']};
  return{ok:true,value:input as KickOffMacroHeadline};
}

export function validateKickOffDashboardContextPayload(input:unknown,evaluatedAt?:string):SchemaValidationResult<KickOffDashboardContextPayloadV1>{
  if(!isObjectRecord(input)||!exact(input,['evidence_score','macro_headlines'])||!isObjectRecord(input.evidence_score)||!exact(input.evidence_score,['value','basis'])||!score(input.evidence_score.value)||input.evidence_score.basis!=='weighted_evidence_usable_weight'||!isObjectRecord(input.macro_headlines)||!exact(input.macro_headlines,['items'])||!Array.isArray(input.macro_headlines.items)||input.macro_headlines.items.length>3)return{ok:false,errors:['kick off context payload invalid']};
  const ids=new Set<string>(),semanticDuplicates=new Set<string>();
  for(const item of input.macro_headlines.items){if(!isObjectRecord(item)||!exact(item,['payload_id','evidence_class','title','source_name','source_url','published_at','freshness','source_evidence_artifact_identity'])||!nonEmpty(item.payload_id)||!['market_news','geopolitical_risk'].includes(String(item.evidence_class))||!nonEmpty(item.title)||!(item.source_name===null||nonEmpty(item.source_name))||!(item.source_url===null||nonEmpty(item.source_url))||!isIsoDateString(item.published_at)||!['fresh','aging'].includes(String(item.freshness))||!nonEmpty(item.source_evidence_artifact_identity)||(evaluatedAt!==undefined&&Date.parse(item.published_at as string)>Date.parse(evaluatedAt))||ids.has(item.payload_id as string))return{ok:false,errors:['kick off internal headline invalid']};const duplicateKey=`${String(item.source_url??item.source_name??'')}\0${String(item.title).trim()}\0${String(item.published_at)}`;if(semanticDuplicates.has(duplicateKey))return{ok:false,errors:['kick off internal headline semantic duplicate']};ids.add(item.payload_id as string);semanticDuplicates.add(duplicateKey)}
  return{ok:true,value:input as KickOffDashboardContextPayloadV1};
}

export function validateKickOffDashboardContextArtifact(input:unknown):SchemaValidationResult<KickOffDashboardContextArtifact>{
  const keys=['schemaVersion','kind','identity','scopeHash','integrityHash','asset','horizon','timeframe','evaluatedAt','generatedAt','freshUntil','parentDashboardProjectionIdentity','parentDashboardProjectionIntegrityHash','parentCognitionArtifactIdentity','parentCognitionIntegrityHash','parentReasoningInputIdentity','weightedEvidenceSnapshotId','weightedEvidenceContentHash','parentEvidenceArtifactIdentities','contextVersion','evidenceScorePolicyVersion','macroHeadlinePolicyVersion','evidenceFreshnessPolicyHash','payload'] as const;
  if(!isObjectRecord(input)||!exact(input,keys)||input.schemaVersion!=='canonical_materialization_v1'||input.kind!=='kick_off_dashboard_context'||input.timeframe!=='H4'||input.contextVersion!=='kick-off-dashboard-context-v1'||input.evidenceScorePolicyVersion!=='kick-off-evidence-score-v1'||input.macroHeadlinePolicyVersion!=='kick-off-macro-headlines-v1'||!supportedAsset(input.asset)||!supportedHorizon(input.horizon)||!isIsoDateString(input.evaluatedAt)||!isIsoDateString(input.generatedAt)||!isIsoDateString(input.freshUntil)||Date.parse(input.generatedAt)>Date.parse(input.evaluatedAt)||Date.parse(input.freshUntil)<=Date.parse(input.evaluatedAt))return{ok:false,errors:['kick off context artifact invalid']};
  for(const key of ['identity','scopeHash','integrityHash','parentDashboardProjectionIdentity','parentDashboardProjectionIntegrityHash','parentCognitionArtifactIdentity','parentCognitionIntegrityHash','parentReasoningInputIdentity','weightedEvidenceSnapshotId','weightedEvidenceContentHash','evidenceFreshnessPolicyHash'] as const)if(!nonEmpty(input[key]))return{ok:false,errors:[`${key} required`]};
  if(!Array.isArray(input.parentEvidenceArtifactIdentities)||input.parentEvidenceArtifactIdentities.some(x=>!nonEmpty(x))||input.parentEvidenceArtifactIdentities.join('\0')!==[...new Set(input.parentEvidenceArtifactIdentities as string[])].sort().join('\0')||!validateKickOffDashboardContextPayload(input.payload,input.evaluatedAt as string).ok||((input.payload as KickOffDashboardContextPayloadV1).macro_headlines.items.some(item=>!(input.parentEvidenceArtifactIdentities as string[]).includes(item.source_evidence_artifact_identity))))return{ok:false,errors:['kick off context lineage/payload invalid']};
  const{integrityHash,...body}=input;if(integrityHash!==integrity(body))return{ok:false,errors:['kick off context integrity invalid']};
  return{ok:true,value:input as unknown as KickOffDashboardContextArtifact};
}

export function validateKickOffDashboardViewModel(input:unknown):SchemaValidationResult<KickOffDashboardViewModelV1>{
  if(!isObjectRecord(input)||!exact(input,['contract_version','access','asset_code','timeframe','horizon','evaluated_at','chart','evidence_score','macro_headlines'])||input.contract_version!=='kick-off-dashboard-v1'||input.access!=='kick_off'||input.timeframe!=='H4'||!supportedAsset(input.asset_code)||!supportedHorizon(input.horizon)||!isIsoDateString(input.evaluated_at)||!isObjectRecord(input.chart)||!exact(input.chart,['candles','zones'])||!Array.isArray(input.chart.candles)||!Array.isArray(input.chart.zones))return{ok:false,errors:['kick off dashboard invalid or unknown fields']};
  for(const candle of input.chart.candles){if(!isObjectRecord(candle)||!exact(candle,candle.volume===undefined?['timestamp_utc','open','high','low','close']:['timestamp_utc','open','high','low','close','volume'])||!isIsoDateString(candle.timestamp_utc)||!['open','high','low','close'].every(k=>isFiniteNumber(candle[k]))||!(candle.volume===undefined||isFiniteNumber(candle.volume)))return{ok:false,errors:['kick off candle invalid']}}
  for(const zone of input.chart.zones){if(!isObjectRecord(zone)||!exact(zone,['zone_id','lower','upper','center'])||!nonEmpty(zone.zone_id)||!isFiniteNumber(zone.lower)||!isFiniteNumber(zone.upper)||!isFiniteNumber(zone.center))return{ok:false,errors:['kick off zone invalid']}}
  if(!isObjectRecord(input.evidence_score)||!exact(input.evidence_score,['availability','value','scale'])||input.evidence_score.scale!=='0_100'||!((input.evidence_score.availability==='available'&&score(input.evidence_score.value))||(input.evidence_score.availability==='unavailable'&&input.evidence_score.value===null)))return{ok:false,errors:['kick off evidence score invalid']};
  if(!isObjectRecord(input.macro_headlines)||!exact(input.macro_headlines,['availability','items'])||!Array.isArray(input.macro_headlines.items)||input.macro_headlines.items.length>3)return{ok:false,errors:['kick off headlines invalid']};
  const availability=input.macro_headlines.availability,items=input.macro_headlines.items;if(!((availability==='available'&&items.length>0)||(availability==='empty'&&items.length===0)||(availability==='unavailable'&&items.length===0)))return{ok:false,errors:['kick off headline availability invalid']};const ids=new Set<string>();for(const item of items){const checked=validateKickOffMacroHeadline(item,input.evaluated_at as string);if(!checked.ok||ids.has(checked.value.headline_id))return{ok:false,errors:['kick off headline invalid/duplicate']};ids.add(checked.value.headline_id)}
  return{ok:true,value:input as unknown as KickOffDashboardViewModelV1};
}
