import type { KoraPayCheckoutReadinessRequest, KoraPayCheckoutReadinessResult, KoraPayCheckoutSessionDraft, KoraPayEntitlementGrantDecision, KoraPayEnvironmentTemplate, KoraPayNormalizedPaymentEvent, KoraPayPaymentCoverageReport, KoraPayProviderDescriptor, KoraPayProviderReadinessReport, KoraPayRawWebhookEventFixture, KoraPayWebhookProcessingResult, KoraPayWebhookVerificationConfig, KoraPayWebhookVerificationInput, KoraPayWebhookVerificationResult } from '@elceo/types';
import { isIsoDateString, isObjectRecord, isNonEmptyString, type SchemaValidationResult } from './validation-utils';

const hasSecretLike = (v: unknown) => typeof v === 'string' && /(secret|private|authorization|bearer|api[_-]?key)/i.test(v);
const arrEq = (a: string[]) => [...a].sort().every((v, i) => v === a[i]);
const obj = (i: unknown) => isObjectRecord(i) ? i : null;

export function validateKoraPayProviderDescriptor(input: unknown): SchemaValidationResult<KoraPayProviderDescriptor> { const x=obj(input); if(!x) return {ok:false,errors:['descriptor must be object']}; const e:string[]=[]; if(x.provider!=='korapay') e.push('provider invalid'); if(!['not_activated','blocked_until_keys_configured','live_activation_required'].includes(String(x.activationStatus))) e.push('activationStatus invalid'); if(!Array.isArray(x.capabilities) || !arrEq((x.capabilities as string[]))) e.push('capabilities ordering invalid'); if(x.liveActivationRequired!==true) e.push('liveActivationRequired invalid'); return e.length?{ok:false,errors:e}:{ok:true,value:x as KoraPayProviderDescriptor}; }
export function validateKoraPayEnvironmentTemplate(input: unknown): SchemaValidationResult<KoraPayEnvironmentTemplate> { const x=obj(input); if(!x) return {ok:false,errors:['environment template must be object']}; const e:string[]=[]; for(const k of ['publicKeyTemplate','secretKeyTemplate','webhookSecretTemplate','checkoutBaseUrlTemplate']){ const v=(x as Record<string,unknown>)[k]; if(!isNonEmptyString(v) || hasSecretLike(v) && !String(v).includes('template')) e.push(`${k} invalid`);} if(x.provider!=='korapay') e.push('provider invalid'); return e.length?{ok:false,errors:e}:{ok:true,value:x as KoraPayEnvironmentTemplate}; }
export function validateKoraPayCheckoutReadinessRequest(input: unknown): SchemaValidationResult<KoraPayCheckoutReadinessRequest> { const x=obj(input); if(!x) return {ok:false,errors:['request must be object']}; const e:string[]=[]; if(!isNonEmptyString(x.userId)) e.push('userId invalid'); if(x.planCode!=='focus_plan') e.push('planCode invalid'); if(!['monthly','quarterly','yearly'].includes(String(x.billingInterval))) e.push('billingInterval invalid'); if(typeof x.socialIdentifierReady!=='boolean') e.push('socialIdentifierReady invalid'); if(!Array.isArray(x.socialIdentifiers)) e.push('socialIdentifiers invalid'); if(!isIsoDateString(x.nowIso)) e.push('nowIso invalid'); return e.length?{ok:false,errors:e}:{ok:true,value:x as KoraPayCheckoutReadinessRequest}; }
export function validateKoraPayCheckoutSessionDraft(input: unknown): SchemaValidationResult<KoraPayCheckoutSessionDraft> { const x=obj(input); if(!x) return {ok:false,errors:['draft must be object']}; const e:string[]=[]; if(x.provider!=='korapay'||x.liveCreated!==false||x.activationStatus!=='blocked_until_keys_configured') e.push('provider/live status invalid'); return e.length?{ok:false,errors:e}:{ok:true,value:x as KoraPayCheckoutSessionDraft}; }
export function validateKoraPayCheckoutReadinessResult(input: unknown): SchemaValidationResult<KoraPayCheckoutReadinessResult> { const x=obj(input); if(!x) return {ok:false,errors:['result must be object']}; const e:string[]=[]; if(!['ready_for_draft','blocked'].includes(String(x.status))) e.push('status invalid'); if(!Array.isArray(x.reasons)) e.push('reasons invalid'); if(x.checkoutSessionDraft!==null){ const d=validateKoraPayCheckoutSessionDraft(x.checkoutSessionDraft); if(!d.ok) e.push(...(d as {ok:false;errors:string[]}).errors);} return e.length?{ok:false,errors:e}:{ok:true,value:x as KoraPayCheckoutReadinessResult}; }
export const validateKoraPayWebhookVerificationConfig = (i: unknown): SchemaValidationResult<KoraPayWebhookVerificationConfig> => ({ ok: !!obj(i), value: i as KoraPayWebhookVerificationConfig, ...(obj(i)?{}:{errors:['config must be object']}) } as any);
export function validateKoraPayWebhookVerificationInput(input: unknown): SchemaValidationResult<KoraPayWebhookVerificationInput> { const x=obj(input); if(!x) return {ok:false,errors:['input must be object']}; const e:string[]=[]; if(!isNonEmptyString(x.rawBody) || hasSecretLike(x.rawBody)) e.push('rawBody invalid'); if(!isObjectRecord(x.headers)) e.push('headers invalid'); if(!isIsoDateString(x.receivedAt)) e.push('receivedAt invalid'); return e.length?{ok:false,errors:e}:{ok:true,value:x as KoraPayWebhookVerificationInput}; }
export const validateKoraPayWebhookVerificationResult = (i: unknown): SchemaValidationResult<KoraPayWebhookVerificationResult> => ({ ok: !!obj(i), value: i as KoraPayWebhookVerificationResult, ...(obj(i)?{}:{errors:['result must be object']}) } as any);
export const validateKoraPayRawWebhookEventFixture = (i: unknown): SchemaValidationResult<KoraPayRawWebhookEventFixture> => ({ ok: !!obj(i), value: i as KoraPayRawWebhookEventFixture, ...(obj(i)?{}:{errors:['fixture must be object']}) } as any);
export const validateKoraPayNormalizedPaymentEvent = (i: unknown): SchemaValidationResult<KoraPayNormalizedPaymentEvent> => ({ ok: !!obj(i), value: i as KoraPayNormalizedPaymentEvent, ...(obj(i)?{}:{errors:['event must be object']}) } as any);
export const validateKoraPayEntitlementGrantDecision = (i: unknown): SchemaValidationResult<KoraPayEntitlementGrantDecision> => ({ ok: !!obj(i), value: i as KoraPayEntitlementGrantDecision, ...(obj(i)?{}:{errors:['decision must be object']}) } as any);
export const validateKoraPayWebhookProcessingResult = (i: unknown): SchemaValidationResult<KoraPayWebhookProcessingResult> => ({ ok: !!obj(i), value: i as KoraPayWebhookProcessingResult, ...(obj(i)?{}:{errors:['processing result must be object']}) } as any);
export const validateKoraPayProviderReadinessReport = (i: unknown): SchemaValidationResult<KoraPayProviderReadinessReport> => ({ ok: !!obj(i), value: i as KoraPayProviderReadinessReport, ...(obj(i)?{}:{errors:['readiness report must be object']}) } as any);
export const validateKoraPayPaymentCoverageReport = (i: unknown): SchemaValidationResult<KoraPayPaymentCoverageReport> => ({ ok: !!obj(i), value: i as KoraPayPaymentCoverageReport, ...(obj(i)?{}:{errors:['coverage report must be object']}) } as any);
