import type { LaunchAssetFixtureAssetPack, LaunchAssetFixtureCoverageReport, LaunchAssetFixtureEvidenceItem, LaunchAssetFixtureExpectedOutput, LaunchAssetFixtureLibrary, LaunchAssetFixtureScenario } from '@elceo/types';
import { LAUNCH_ASSET_FIXTURE_EXPECTED_CONFIDENCE_BANDS, LAUNCH_ASSET_FIXTURE_EXPECTED_PRESSURES, LAUNCH_ASSET_FIXTURE_REGIMES, LAUNCH_ASSET_FIXTURE_SCENARIO_KINDS, LAUNCH_ASSET_FIXTURE_SEVERITIES, PROVIDER_SOURCE_CAPABILITY_KINDS, PROVIDER_SOURCE_FAMILIES, PROVIDER_SOURCE_IDS } from '@elceo/types';
import { isEnumValue, isIsoDateString, isNonEmptyString, isObjectRecord, isStringArray, type SchemaValidationResult } from './validation-utils';
const ASSETS=['xau_usd','eur_usd','gbp_usd','usd_jpy','aud_usd','usd_chf','nzd_usd','usd_cad','btc_usd','nasdaq_100','sp500','de30','dxy','vix'] as const;
const BAD=/(buy|sell|hold)/i; const SECRET=/(api[_-]?key|token|secret|password)/i;
const sorted=(x:string[])=>x.every((v,i)=>i===0||(x[i-1]??'')<=v);
export function validateLaunchAssetFixtureEvidenceItem(input:unknown,p=''):SchemaValidationResult<LaunchAssetFixtureEvidenceItem>{const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${p}evidence item object required`]}; for(const k of Object.keys(input)) if(SECRET.test(k)) e.push(`${p}${k} forbidden`);
if(!isEnumValue(input.asset,ASSETS)) e.push(`${p}asset invalid`); if(!isEnumValue(input.sourceId,PROVIDER_SOURCE_IDS)) e.push(`${p}sourceId invalid`); if(!isEnumValue(input.providerFamily,PROVIDER_SOURCE_FAMILIES)||!isEnumValue(input.sourceFamily,PROVIDER_SOURCE_FAMILIES)) e.push(`${p}family invalid`); if(!isEnumValue(input.capabilityKind,PROVIDER_SOURCE_CAPABILITY_KINDS)) e.push(`${p}capability invalid`); if(!isNonEmptyString(input.evidenceClass)) e.push(`${p}evidenceClass invalid`); if(!isIsoDateString(input.observedAt)) e.push(`${p}observedAt invalid`); if(!isEnumValue(input.freshnessState,['fresh','aging','stale'] as const)) e.push(`${p}freshness invalid`); if(!isStringArray(input.qualityHints)||input.qualityHints.length===0) e.push(`${p}qualityHints invalid`); if(!isEnumValue(input.directionalPressure,LAUNCH_ASSET_FIXTURE_EXPECTED_PRESSURES)) e.push(`${p}directionalPressure invalid`); if(!isNonEmptyString(input.narrative)||BAD.test(input.narrative)) e.push(`${p}narrative invalid`); if(!isEnumValue(input.expectedRole,['primary','secondary','context'] as const)) e.push(`${p}expectedRole invalid`); if(!(typeof input.expectedImportance==='number'&&input.expectedImportance>=0&&input.expectedImportance<=1)) e.push(`${p}expectedImportance invalid`); if(!isStringArray(input.scenarioTags)||input.scenarioTags.length===0) e.push(`${p}scenarioTags invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:input as LaunchAssetFixtureEvidenceItem};}
export function validateLaunchAssetFixtureExpectedOutput(input:unknown,p=''):SchemaValidationResult<LaunchAssetFixtureExpectedOutput>{const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${p}expected output object required`]}; if(!isNonEmptyString(input.scenarioId)) e.push(`${p}scenarioId invalid`); if(!isEnumValue(input.expectedPressure,LAUNCH_ASSET_FIXTURE_EXPECTED_PRESSURES)) e.push(`${p}pressure invalid`); if(!isEnumValue(input.expectedConfidenceBand,LAUNCH_ASSET_FIXTURE_EXPECTED_CONFIDENCE_BANDS)) e.push(`${p}confidence invalid`); if(typeof input.expectedContradiction!=='boolean'||typeof input.expectedFreshnessWarnings!=='boolean') e.push(`${p}flags invalid`); if(!isStringArray(input.expectedTopEvidenceClasses)||input.expectedTopEvidenceClasses.length===0) e.push(`${p}top classes invalid`); if(!isStringArray(input.expectedCognitionThemes)||input.expectedCognitionThemes.length===0) e.push(`${p}themes invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:input as LaunchAssetFixtureExpectedOutput};}
export function validateLaunchAssetFixtureScenario(input:unknown,p=''):SchemaValidationResult<LaunchAssetFixtureScenario>{const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${p}scenario object required`]}; if(!isNonEmptyString(input.scenarioId)||!String(input.scenarioId).startsWith(`${input.asset}:`)) e.push(`${p}scenarioId deterministic format invalid`); if(!isEnumValue(input.asset,ASSETS)) e.push(`${p}asset invalid`); if(!isNonEmptyString(input.title)||BAD.test(input.title)) e.push(`${p}title invalid`); if(!isEnumValue(input.kind,LAUNCH_ASSET_FIXTURE_SCENARIO_KINDS)||!isEnumValue(input.severity,LAUNCH_ASSET_FIXTURE_SEVERITIES)||!isEnumValue(input.regime,LAUNCH_ASSET_FIXTURE_REGIMES)) e.push(`${p}enum invalid`); if(!isStringArray(input.tags)||input.tags.length===0) e.push(`${p}tags invalid`); if(!Array.isArray(input.evidence)||input.evidence.length===0) e.push(`${p}evidence missing`); else input.evidence.forEach((x,i)=>{const r=validateLaunchAssetFixtureEvidenceItem(x,`${p}evidence[${i}].`); if(r.ok===false) e.push(...r.errors);}); const eo=validateLaunchAssetFixtureExpectedOutput(input.expectedOutput,`${p}expectedOutput.`); if(eo.ok===false) e.push(...eo.errors); return e.length?{ok:false,errors:e}:{ok:true,value:input as LaunchAssetFixtureScenario};}
export function validateLaunchAssetFixtureAssetPack(input:unknown,p=''):SchemaValidationResult<LaunchAssetFixtureAssetPack>{const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${p}asset pack object required`]}; if(!isEnumValue(input.asset,ASSETS)) e.push(`${p}asset invalid`); if(!Array.isArray(input.scenarios)||input.scenarios.length===0) e.push(`${p}scenarios invalid`); else {const ids=input.scenarios.map((x:any)=>x.scenarioId); if(!sorted(ids)) e.push(`${p}scenario ordering invalid`); input.scenarios.forEach((x,i)=>{const r=validateLaunchAssetFixtureScenario(x,`${p}scenarios[${i}].`); if(r.ok===false) e.push(...r.errors);});} return e.length?{ok:false,errors:e}:{ok:true,value:input as LaunchAssetFixtureAssetPack};}
export function validateLaunchAssetFixtureLibrary(input:unknown,p=''):SchemaValidationResult<LaunchAssetFixtureLibrary>{const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${p}library object required`]}; if(!isIsoDateString(input.generatedAt)) e.push(`${p}generatedAt invalid`); if(!Array.isArray(input.assets)||input.assets.length!==ASSETS.length) e.push(`${p}assets invalid`); else input.assets.forEach((x,i)=>{const r=validateLaunchAssetFixtureAssetPack(x,`${p}assets[${i}].`); if(r.ok===false) e.push(...r.errors);}); return e.length?{ok:false,errors:e}:{ok:true,value:input as LaunchAssetFixtureLibrary};}
export function validateLaunchAssetFixtureCoverageReport(input:unknown,p=''):SchemaValidationResult<LaunchAssetFixtureCoverageReport>{ if(!isObjectRecord(input)) return {ok:false,errors:[`${p}coverage object required`]}; return {ok:true,value:input as LaunchAssetFixtureCoverageReport}; }
