import type { MarketConfidenceCalibrationComponent, MarketConfidenceCalibrationCoverageReport, MarketConfidenceCalibrationInput, MarketConfidenceCalibrationPenalty, MarketConfidenceCalibrationResult, MarketConfidenceCalibrationRule, MarketConfidenceCalibrationRuleSetSnapshot } from '@elceo/types';
import { EVIDENCE_WEIGHT_HORIZONS, MARKET_CONFIDENCE_CALIBRATION_BOOST_KINDS, MARKET_CONFIDENCE_CALIBRATION_COMPONENT_KINDS, MARKET_CONFIDENCE_CALIBRATION_PENALTY_KINDS, MARKET_CONFIDENCE_CALIBRATION_REASON_CODES, MARKET_CONFIDENCE_CALIBRATION_TIERS, MARKET_CONFIDENCE_CALIBRATION_WARNINGS, TRADING_ASSET_COVERAGE } from '@elceo/types';
import { isEnumValue, isIsoDateString, isNonEmptyString, isObjectRecord, isScore0to100, isStringArray, type SchemaValidationResult } from './validation-utils';

const FORBIDDEN_ADVICE = /\b(buy|sell|hold|guaranteed profit|risk-free)\b/i;
const PENDING_KEYS = ['priceReactionR7','providerReliabilityExpansion','goldenScenarioExpansion','empiricalBacktesting'] as const;
function tierFor(score: number) { return score < 25 ? 'very_low' : score < 45 ? 'low' : score < 65 ? 'medium' : score < 80 ? 'high' : 'very_high'; }
function advice(text: unknown, errors: string[], path: string): void { if (typeof text === 'string' && FORBIDDEN_ADVICE.test(text)) errors.push(`${path} contains forbidden advice language`); }
function pending(input: Record<string, unknown>, errors: string[], path: string): void { if (input.complete !== false) errors.push(`${path}complete must remain false while R7/provider/golden/empirical validation remain pending`); if (!isObjectRecord(input.pending)) { errors.push(`${path}pending must be object`); return; } for (const k of PENDING_KEYS) if (input.pending[k] !== true) errors.push(`${path}pending.${k} must remain true`); }
function hasPenalty(input: Record<string, unknown>, kind: string, severe?: boolean): boolean { return Array.isArray(input.penalties) && input.penalties.some((p) => isObjectRecord(p) && p.kind === kind && (severe === undefined || p.severe === severe)); }

export function validateMarketConfidenceCalibrationInput(input: unknown, p = ''): SchemaValidationResult<MarketConfidenceCalibrationInput> { const e: string[] = []; if (!isObjectRecord(input)) return { ok:false, errors:[`${p}MarketConfidenceCalibrationInput must be object`] };
  if (!(isEnumValue(input.asset, TRADING_ASSET_COVERAGE) || input.asset === 'dxy')) e.push(`${p}asset is invalid`); if (!isEnumValue(input.horizon, EVIDENCE_WEIGHT_HORIZONS)) e.push(`${p}horizon is invalid`); if (!isIsoDateString(input.generatedAt)) e.push(`${p}generatedAt invalid`);
  for (const k of ['baseConfidence','evidenceQuality','usableWeight','freshness','coverage']) if (!isScore0to100(input[k])) e.push(`${p}${k} must be 0..100`);
  if (!isStringArray(input.warnings)) e.push(`${p}warnings must be string[]`); if (!isStringArray(input.reasonCodes)) e.push(`${p}reasonCodes must be string[]`);
  return e.length ? { ok:false, errors:e } : { ok:true, value:input as MarketConfidenceCalibrationInput }; }
export function validateMarketConfidenceCalibrationComponent(input: unknown, p = ''): SchemaValidationResult<MarketConfidenceCalibrationComponent> { const e: string[] = []; if (!isObjectRecord(input)) return { ok:false, errors:[`${p}component must be object`] };
  if (!isEnumValue(input.kind, MARKET_CONFIDENCE_CALIBRATION_COMPONENT_KINDS)) e.push(`${p}kind invalid`); if (!isScore0to100(input.score)) e.push(`${p}score must be 0..100`); if (typeof input.contribution !== 'number' || input.contribution < -100 || input.contribution > 100) e.push(`${p}contribution bounded -100..100`); if (!isNonEmptyString(input.rationale)) e.push(`${p}rationale required`); advice(input.rationale, e, `${p}rationale`);
  return e.length ? { ok:false, errors:e } : { ok:true, value:input as MarketConfidenceCalibrationComponent }; }
export function validateMarketConfidenceCalibrationPenalty(input: unknown, p = ''): SchemaValidationResult<MarketConfidenceCalibrationPenalty> { const e: string[] = []; if (!isObjectRecord(input)) return { ok:false, errors:[`${p}penalty must be object`] };
  if (!isEnumValue(input.kind, MARKET_CONFIDENCE_CALIBRATION_PENALTY_KINDS)) e.push(`${p}kind invalid`); if (typeof input.magnitude !== 'number' || input.magnitude < 0 || input.magnitude > 100) e.push(`${p}magnitude bounded 0..100`); if (typeof input.severe !== 'boolean') e.push(`${p}severe must be boolean`); if (!isNonEmptyString(input.rationale)) e.push(`${p}rationale required`); advice(input.rationale, e, `${p}rationale`);
  return e.length ? { ok:false, errors:e } : { ok:true, value:input as MarketConfidenceCalibrationPenalty }; }
export function validateMarketConfidenceCalibrationResult(input: unknown, p = ''): SchemaValidationResult<MarketConfidenceCalibrationResult> { const e: string[] = []; if (!isObjectRecord(input)) return { ok:false, errors:[`${p}MarketConfidenceCalibrationResult must be object`] };
  if (!(isEnumValue(input.asset, TRADING_ASSET_COVERAGE) || input.asset === 'dxy')) e.push(`${p}asset invalid`); if (!isEnumValue(input.horizon, EVIDENCE_WEIGHT_HORIZONS)) e.push(`${p}horizon invalid`); if (!isIsoDateString(input.generatedAt)) e.push(`${p}generatedAt invalid`); if (!isScore0to100(input.baseConfidence)) e.push(`${p}baseConfidence must be 0..100`); if (!isScore0to100(input.finalConfidence)) e.push(`${p}finalConfidence must be 0..100`);
  if (isScore0to100(input.finalConfidence) && input.confidenceTier !== tierFor(input.finalConfidence)) e.push(`${p}confidenceTier must match finalConfidence range`); if (!isEnumValue(input.confidenceTier, MARKET_CONFIDENCE_CALIBRATION_TIERS)) e.push(`${p}confidenceTier invalid`);
  if (!Array.isArray(input.components)) e.push(`${p}components must be array`); else input.components.forEach((x,i)=>{ const r=validateMarketConfidenceCalibrationComponent(x,`${p}components[${i}].`); if(r.ok===false)e.push(...r.errors); });
  if (!Array.isArray(input.penalties)) e.push(`${p}penalties must be array`); else input.penalties.forEach((x,i)=>{ const r=validateMarketConfidenceCalibrationPenalty(x,`${p}penalties[${i}].`); if(r.ok===false)e.push(...r.errors); });
  if (!Array.isArray(input.boosts) || input.boosts.some((b)=>!isObjectRecord(b) || !isEnumValue(b.kind, MARKET_CONFIDENCE_CALIBRATION_BOOST_KINDS) || typeof b.magnitude !== 'number' || b.magnitude < 0 || b.magnitude > 10 || !isNonEmptyString(b.rationale))) e.push(`${p}boosts invalid`);
  if (!Array.isArray(input.warnings) || input.warnings.some((w)=>!isEnumValue(w, MARKET_CONFIDENCE_CALIBRATION_WARNINGS))) e.push(`${p}warnings invalid`); if (!Array.isArray(input.reasonCodes) || input.reasonCodes.some((r)=>!isEnumValue(r, MARKET_CONFIDENCE_CALIBRATION_REASON_CODES))) e.push(`${p}reasonCodes invalid`);
  if (!isNonEmptyString(input.rationale)) e.push(`${p}rationale must be non-empty`); advice(input.rationale, e, `${p}rationale`); pending(input, e, p);
  if ((input.confidenceTier === 'high' || input.confidenceTier === 'very_high') && (hasPenalty(input,'missing_price_confirmation') || hasPenalty(input,'high_contradiction_severity') || hasPenalty(input,'one_sided_fx_evidence') || hasPenalty(input,'missing_macro_forecast') || hasPenalty(input,'provider_activation_gap', true))) e.push(`${p}high/very_high confidence blocked by severe pending context`);
  return e.length ? { ok:false, errors:e } : { ok:true, value:input as MarketConfidenceCalibrationResult }; }
export function validateMarketConfidenceCalibrationRule(input: unknown, p = ''): SchemaValidationResult<MarketConfidenceCalibrationRule> { const e: string[] = []; if (!isObjectRecord(input)) return { ok:false, errors:[`${p}rule must be object`] }; if (!isNonEmptyString(input.ruleId)) e.push(`${p}ruleId required`); if (input.componentKind !== undefined && !isEnumValue(input.componentKind, MARKET_CONFIDENCE_CALIBRATION_COMPONENT_KINDS)) e.push(`${p}componentKind invalid`); if (input.penaltyKind !== undefined && !isEnumValue(input.penaltyKind, MARKET_CONFIDENCE_CALIBRATION_PENALTY_KINDS)) e.push(`${p}penaltyKind invalid`); if (input.boostKind !== undefined && !isEnumValue(input.boostKind, MARKET_CONFIDENCE_CALIBRATION_BOOST_KINDS)) e.push(`${p}boostKind invalid`); if (!isNonEmptyString(input.rationale)) e.push(`${p}rationale required`); advice(input.rationale,e,`${p}rationale`); return e.length ? {ok:false,errors:e}:{ok:true,value:input as MarketConfidenceCalibrationRule}; }
export function validateMarketConfidenceCalibrationRuleSetSnapshot(input: unknown, p = ''): SchemaValidationResult<MarketConfidenceCalibrationRuleSetSnapshot> { const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${p}snapshot must be object`]}; if(!isIsoDateString(input.generatedAt)) e.push(`${p}generatedAt invalid`); if(!Array.isArray(input.rules)) e.push(`${p}rules must be array`); else input.rules.forEach((x,i)=>{const r=validateMarketConfidenceCalibrationRule(x,`${p}rules[${i}].`); if(r.ok===false)e.push(...r.errors);}); if(!Array.isArray(input.warnings) || input.warnings.some((w)=>!isEnumValue(w, MARKET_CONFIDENCE_CALIBRATION_WARNINGS))) e.push(`${p}warnings invalid`); pending(input,e,p); return e.length?{ok:false,errors:e}:{ok:true,value:input as MarketConfidenceCalibrationRuleSetSnapshot}; }
export function validateMarketConfidenceCalibrationCoverageReport(input: unknown, p = ''): SchemaValidationResult<MarketConfidenceCalibrationCoverageReport> { const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${p}coverage must be object`]}; if(!isIsoDateString(input.generatedAt)) e.push(`${p}generatedAt invalid`); if(!Array.isArray(input.componentKinds) || input.componentKinds.some((x)=>!isEnumValue(x, MARKET_CONFIDENCE_CALIBRATION_COMPONENT_KINDS))) e.push(`${p}componentKinds invalid`); if(!Array.isArray(input.penaltyKinds) || input.penaltyKinds.some((x)=>!isEnumValue(x, MARKET_CONFIDENCE_CALIBRATION_PENALTY_KINDS))) e.push(`${p}penaltyKinds invalid`); if(!Array.isArray(input.boostKinds) || input.boostKinds.some((x)=>!isEnumValue(x, MARKET_CONFIDENCE_CALIBRATION_BOOST_KINDS))) e.push(`${p}boostKinds invalid`); if(!Array.isArray(input.notes) || input.notes.some((n)=>!isNonEmptyString(n))) e.push(`${p}notes invalid`); else input.notes.forEach((n,i)=>advice(n,e,`${p}notes[${i}]`)); if(!Array.isArray(input.warnings) || input.warnings.some((w)=>!isEnumValue(w, MARKET_CONFIDENCE_CALIBRATION_WARNINGS))) e.push(`${p}warnings invalid`); pending(input,e,p); return e.length?{ok:false,errors:e}:{ok:true,value:input as MarketConfidenceCalibrationCoverageReport}; }
