import type { AssetEvidenceWeightPolicy, WeightedEvidenceAssemblyReport, WeightedEvidenceItem, WeightedEvidencePolicySnapshot, WeightedEvidenceSnapshot } from '@elceo/types';
import { EVIDENCE_WEIGHT_HORIZONS, EVIDENCE_WEIGHT_ROLES, MARKET_EVIDENCE_CLASSES, TRADING_ASSET_COVERAGE, WEIGHTED_EVIDENCE_DIRECTIONS } from '@elceo/types';
import { isEnumValue, isIsoDateString, isNonEmptyString, isObjectRecord, isScore0to100, isStringArray, type SchemaValidationResult } from './validation-utils';

const s100=(v:unknown)=>typeof v==='number'&&Number.isFinite(v)&&v>=-100&&v<=100;
const nn=(v:unknown)=>Number.isFinite(v as number)&&Number(v)>=0&&Number(v)<=100;
export function validateAssetEvidenceWeightPolicy(input:unknown,p=''):SchemaValidationResult<AssetEvidenceWeightPolicy>{const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${p}AssetEvidenceWeightPolicy must be object`]}; if(!isEnumValue(input.asset,TRADING_ASSET_COVERAGE)) e.push(`${p}asset is invalid`); if(!isEnumValue(input.horizon,EVIDENCE_WEIGHT_HORIZONS)) e.push(`${p}horizon is invalid`); if(!isEnumValue(input.evidenceClass,MARKET_EVIDENCE_CLASSES)) e.push(`${p}evidenceClass is invalid`); if(!isScore0to100(input.baseWeight)) e.push(`${p}baseWeight must be 0..100`); if(!isEnumValue(input.role,EVIDENCE_WEIGHT_ROLES)) e.push(`${p}role is invalid`); if(!isNonEmptyString(input.rationale)) e.push(`${p}rationale must be non-empty string`); return e.length?{ok:false,errors:e}:{ok:true,value:input as AssetEvidenceWeightPolicy};}
export function validateWeightedEvidenceItem(input:unknown,p=''):SchemaValidationResult<WeightedEvidenceItem>{const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${p}WeightedEvidenceItem must be object`]}; for(const k of ['payloadId','evidenceTypeId','providerId'] as const){if(!isNonEmptyString(input[k])) e.push(`${p}${k} must be non-empty string`);} if(!isEnumValue(input.asset,TRADING_ASSET_COVERAGE)) e.push(`${p}asset is invalid`); if(!isEnumValue(input.horizon,EVIDENCE_WEIGHT_HORIZONS)) e.push(`${p}horizon is invalid`); if(!isEnumValue(input.evidenceClass,MARKET_EVIDENCE_CLASSES)) e.push(`${p}evidenceClass is invalid`); if(!isIsoDateString(input.observedAt)) e.push(`${p}observedAt invalid`); if(!nn(input.finalQualityScore)) e.push(`${p}finalQualityScore must be 0..100`); if(!nn(input.baseWeight)) e.push(`${p}baseWeight must be 0..100`); if(!nn(input.qualityAdjustedWeight)) e.push(`${p}qualityAdjustedWeight must be 0..100`); if(!isEnumValue(input.role,EVIDENCE_WEIGHT_ROLES)) e.push(`${p}role is invalid`); if(!isEnumValue(input.direction,WEIGHTED_EVIDENCE_DIRECTIONS)) e.push(`${p}direction is invalid`); if(!s100(input.contributionScore)) e.push(`${p}contributionScore must be -100..100`); if(!isStringArray(input.reasons)) e.push(`${p}reasons must be string[]`); return e.length?{ok:false,errors:e}:{ok:true,value:input as WeightedEvidenceItem};}
export function validateWeightedEvidenceSnapshot(input:unknown,p=''):SchemaValidationResult<WeightedEvidenceSnapshot>{const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${p}WeightedEvidenceSnapshot must be object`]}; if(!isNonEmptyString(input.snapshotId)) e.push(`${p}snapshotId must be non-empty string`); if(!isIsoDateString(input.generatedAt)) e.push(`${p}generatedAt invalid`); if(!isEnumValue(input.asset,TRADING_ASSET_COVERAGE)) e.push(`${p}asset is invalid`); if(!isEnumValue(input.horizon,EVIDENCE_WEIGHT_HORIZONS)) e.push(`${p}horizon is invalid`); for(const k of ['totalWeight','usableWeight','excludedWeight'] as const){if(!nn(input[k])) e.push(`${p}${k} must be 0..100`);} if(!Array.isArray(input.items)) e.push(`${p}items must be array`); else input.items.forEach((x,i)=>{const r=validateWeightedEvidenceItem(x,`${p}items[${i}].`); if(r.ok===false)e.push(...r.errors);}); if(!isStringArray(input.warnings)) e.push(`${p}warnings must be string[]`); return e.length?{ok:false,errors:e}:{ok:true,value:input as WeightedEvidenceSnapshot};}
export function validateWeightedEvidencePolicySnapshot(input:unknown,p=''):SchemaValidationResult<WeightedEvidencePolicySnapshot>{const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${p}WeightedEvidencePolicySnapshot must be object`]}; if(!isIsoDateString(input.generatedAt)) e.push(`${p}generatedAt invalid`); if(!Array.isArray(input.policies)) e.push(`${p}policies must be array`); else input.policies.forEach((x,i)=>{const r=validateAssetEvidenceWeightPolicy(x,`${p}policies[${i}].`); if(r.ok===false)e.push(...r.errors);}); return e.length?{ok:false,errors:e}:{ok:true,value:input as WeightedEvidencePolicySnapshot};}
export function validateWeightedEvidenceAssemblyReport(input:unknown,p=''):SchemaValidationResult<WeightedEvidenceAssemblyReport>{const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${p}WeightedEvidenceAssemblyReport must be object`]}; if(!isIsoDateString(input.generatedAt)) e.push(`${p}generatedAt invalid`); if(!isEnumValue(input.asset,TRADING_ASSET_COVERAGE)) e.push(`${p}asset is invalid`); if(!isEnumValue(input.horizon,EVIDENCE_WEIGHT_HORIZONS)) e.push(`${p}horizon is invalid`); if(!Number.isInteger(input.itemCount)||Number(input.itemCount)<0) e.push(`${p}itemCount must be integer >= 0`); if(!nn(input.totalWeight)||!nn(input.usableWeight)) e.push(`${p}totalWeight/usableWeight must be 0..100`); if(!isStringArray(input.warnings)) e.push(`${p}warnings must be string[]`); if(typeof input.pass!=='boolean') e.push(`${p}pass must be boolean`); return e.length?{ok:false,errors:e}:{ok:true,value:input as WeightedEvidenceAssemblyReport};}
