import type { MarketGoldenScenarioAcceptanceReport, MarketGoldenScenarioAcceptanceResult, MarketGoldenScenarioCandleFixture, MarketGoldenScenarioCoverageReport, MarketGoldenScenarioEvidenceFixture, MarketGoldenScenarioFixture, MarketGoldenScenarioRule, MarketGoldenScenarioRuleSetSnapshot } from '@elceo/types';
import { MARKET_GOLDEN_SCENARIO_ASSETS, MARKET_GOLDEN_SCENARIO_CATEGORIES, MARKET_GOLDEN_SCENARIO_REGIMES, MARKET_EVIDENCE_CLASSES, MARKET_PRICE_REACTION_STATUSES, MARKET_PROVIDER_RELIABILITY_WARNINGS, MARKET_CONFIDENCE_CALIBRATION_TIERS } from '@elceo/types';
import { isBoolean, isEnumValue, isFiniteNumber, isIsoDateString, isNonEmptyString, isObjectRecord, isScore0to100, type SchemaValidationResult } from './validation-utils';

const forbidden = /\b(buy|sell|hold|guaranteed profit|risk-free)\b/i;
const engines = ['asset direction','FX relative strength','macro surprise','contradiction matrix','confidence calibration','price reaction','provider reliability'];
function fail<T>(errors: string[]): SchemaValidationResult<T> { return { ok: false, errors }; }
function pass<T>(value: T): SchemaValidationResult<T> { return { ok: true, value }; }
function strings(value: unknown): value is string[] { return Array.isArray(value) && value.every((x) => typeof x === 'string'); }
function noAdvice(value: unknown): boolean { return typeof value !== 'string' || !forbidden.test(value); }
function pendingFalse(input: Record<string, unknown>, errors: string[]): void { if (input.complete !== false) errors.push('complete must remain false'); const p = input.pending; if (!isObjectRecord(p) || p.liveProviderActivation !== true || p.empiricalBacktesting !== true || p.productionDataCalibration !== true) errors.push('pending flags must remain true'); }

export function validateMarketGoldenScenarioCandleFixture(input: unknown, path = ''): SchemaValidationResult<MarketGoldenScenarioCandleFixture> { if (!isObjectRecord(input)) return fail([`${path}must be object`]); const e: string[] = []; if (!isIsoDateString(input.timestamp)) e.push(`${path}timestamp`); for (const key of ['open','high','low','close']) if (!isFiniteNumber(input[key])) e.push(`${path}${key}`); if (isFiniteNumber(input.high) && isFiniteNumber(input.low) && input.high < input.low) e.push(`${path}high_low_coherence`); if (isFiniteNumber(input.open) && isFiniteNumber(input.high) && isFiniteNumber(input.low) && (input.open > input.high || input.open < input.low)) e.push(`${path}open_ohlc_coherence`); if (isFiniteNumber(input.close) && isFiniteNumber(input.high) && isFiniteNumber(input.low) && (input.close > input.high || input.close < input.low)) e.push(`${path}close_ohlc_coherence`); return e.length ? fail(e) : pass(input as MarketGoldenScenarioCandleFixture); }
export function validateMarketGoldenScenarioEvidenceFixture(input: unknown, path = ''): SchemaValidationResult<MarketGoldenScenarioEvidenceFixture> { if (!isObjectRecord(input)) return fail([`${path}must be object`]); const e: string[] = []; if (!isNonEmptyString(input.evidenceId)) e.push(`${path}evidenceId`); if (!isNonEmptyString(input.providerId)) e.push(`${path}providerId`); if (!isEnumValue(input.evidenceClass, MARKET_EVIDENCE_CLASSES)) e.push(`${path}evidenceClass`); if (!isIsoDateString(input.observedAt)) e.push(`${path}observedAt`); if (!isScore0to100(input.weight)) e.push(`${path}weight`); if (!isScore0to100(input.reliabilityScore)) e.push(`${path}reliabilityScore`); if (!isBoolean(input.independent)) e.push(`${path}independent`); if (!isNonEmptyString(input.rationale) || !noAdvice(input.rationale)) e.push(`${path}rationale`); return e.length ? fail(e) : pass(input as MarketGoldenScenarioEvidenceFixture); }
export function validateMarketGoldenScenarioFixture(input: unknown): SchemaValidationResult<MarketGoldenScenarioFixture> { if (!isObjectRecord(input)) return fail(['must be object']); const e: string[] = []; if (!isNonEmptyString(input.scenarioId)) e.push('scenarioId'); if (!isEnumValue(input.asset, MARKET_GOLDEN_SCENARIO_ASSETS)) e.push('asset'); if (!isEnumValue(input.category, MARKET_GOLDEN_SCENARIO_CATEGORIES)) e.push('category'); if (!isEnumValue(input.regime, MARKET_GOLDEN_SCENARIO_REGIMES)) e.push('regime'); if (!isNonEmptyString(input.rationale) || !noAdvice(input.rationale)) e.push('rationale'); if (!isObjectRecord(input.expectedOutcome) || !isNonEmptyString(input.expectedOutcome.rationale) || !noAdvice(input.expectedOutcome.rationale)) e.push('expectedOutcome'); if (!Array.isArray(input.evidence) || input.evidence.length === 0) e.push('evidence'); else input.evidence.forEach((x, i) => { const r = validateMarketGoldenScenarioEvidenceFixture(x, `evidence[${i}].`); if (r.ok === false) e.push(...r.errors); }); if (!Array.isArray(input.candles)) e.push('candles'); else input.candles.forEach((x, i) => { const r = validateMarketGoldenScenarioCandleFixture(x, `candles[${i}].`); if (r.ok === false) e.push(...r.errors); }); return e.length ? fail(e) : pass(input as MarketGoldenScenarioFixture); }
export function validateMarketGoldenScenarioAcceptanceResult(input: unknown): SchemaValidationResult<MarketGoldenScenarioAcceptanceResult> { if (!isObjectRecord(input)) return fail(['must be object']); const e: string[] = []; if (!isNonEmptyString(input.scenarioId)) e.push('scenarioId'); if (!isEnumValue(input.asset, MARKET_GOLDEN_SCENARIO_ASSETS)) e.push('asset'); if (!isEnumValue(input.category, MARKET_GOLDEN_SCENARIO_CATEGORIES)) e.push('category'); if (!isBoolean(input.pass)) e.push('pass'); if (!isScore0to100(input.confidence)) e.push('confidence'); if (!isEnumValue(input.confidenceTier, MARKET_CONFIDENCE_CALIBRATION_TIERS)) e.push('confidenceTier'); if (!isEnumValue(input.priceReactionStatus, MARKET_PRICE_REACTION_STATUSES)) e.push('priceReactionStatus'); if (!Array.isArray(input.providerReliabilityWarnings) || input.providerReliabilityWarnings.some((x) => !isEnumValue(x, MARKET_PROVIDER_RELIABILITY_WARNINGS))) e.push('providerReliabilityWarnings'); if (!isNonEmptyString(input.rationale) || !noAdvice(input.rationale)) e.push('rationale'); pendingFalse(input, e); return e.length ? fail(e) : pass(input as MarketGoldenScenarioAcceptanceResult); }
export function validateMarketGoldenScenarioAcceptanceReport(input: unknown): SchemaValidationResult<MarketGoldenScenarioAcceptanceReport> { if (!isObjectRecord(input)) return fail(['must be object']); const e: string[] = []; if (!isIsoDateString(input.generatedAt)) e.push('generatedAt'); if (!isFiniteNumber(input.totalScenarios) || input.totalScenarios < 28) e.push('totalScenarios'); if (!Array.isArray(input.results) || input.results.length !== input.totalScenarios) e.push('results'); pendingFalse(input, e); return e.length ? fail(e) : pass(input as MarketGoldenScenarioAcceptanceReport); }
export function validateMarketGoldenScenarioRule(input: unknown): SchemaValidationResult<MarketGoldenScenarioRule> { if (!isObjectRecord(input)) return fail(['must be object']); const e: string[] = []; if (!isNonEmptyString(input.ruleId)) e.push('ruleId'); if (!isNonEmptyString(input.engine)) e.push('engine'); if (!isNonEmptyString(input.rationale) || !noAdvice(input.rationale)) e.push('rationale'); if (!Array.isArray(input.requiredScenarioIds) || input.requiredScenarioIds.length === 0) e.push('requiredScenarioIds'); return e.length ? fail(e) : pass(input as MarketGoldenScenarioRule); }
export function validateMarketGoldenScenarioRuleSetSnapshot(input: unknown): SchemaValidationResult<MarketGoldenScenarioRuleSetSnapshot> { if (!isObjectRecord(input)) return fail(['must be object']); const e: string[] = []; if (!Array.isArray(input.rules) || input.rules.length === 0) e.push('rules'); else input.rules.forEach((x) => { const r = validateMarketGoldenScenarioRule(x); if (r.ok === false) e.push(...r.errors); }); pendingFalse(input, e); return e.length ? fail(e) : pass(input as MarketGoldenScenarioRuleSetSnapshot); }
export function validateMarketGoldenScenarioCoverageReport(input: unknown): SchemaValidationResult<MarketGoldenScenarioCoverageReport> { if (!isObjectRecord(input)) return fail(['must be object']); const e: string[] = []; const assetsCovered = Array.isArray(input.assetsCovered) ? input.assetsCovered : []; if (MARKET_GOLDEN_SCENARIO_ASSETS.some((x) => !assetsCovered.includes(x))) e.push('all 14 launch assets must be covered'); const enginesCovered = strings(input.enginesCovered) ? input.enginesCovered : []; if (engines.some((x) => !enginesCovered.includes(x))) e.push('major engine coverage missing'); if (strings(input.notes) && input.notes.some((x) => /exhaustive production coverage/i.test(x))) e.push('must not claim exhaustive production coverage'); pendingFalse(input, e); return e.length ? fail(e) : pass(input as MarketGoldenScenarioCoverageReport); }
