import type { MarketEvidenceDataQuality, NormalizedBankEarningsMetric, NormalizedBankHealthMetric, NormalizedInstitutionalLiquidityMetric, NormalizedRegulatoryFilingReference, NormalizedStressTestResult, NormalizedBondAuctionResult, NormalizedCentralBankBalanceSheetPoint, NormalizedCentralBankLiquidity, NormalizedCotPositioning, NormalizedCreditStressIndicator, NormalizedCrossMarketRatePoint, NormalizedCryptoMarketStructurePoint, NormalizedDebtSupplyCalendarItem, NormalizedDollarLiquidityPoint, NormalizedEarningsMacroPoint, NormalizedEnergyCommodityPoint, NormalizedEquityBreadthPoint, NormalizedFinancialConditionsPoint, NormalizedFuturesPositioning, NormalizedGeopoliticalRiskEvent, NormalizedLiquidityConditionPoint, NormalizedMacroCalendarEvent, NormalizedMacroIndicatorPoint, NormalizedMacroSurprisePoint, NormalizedPolicyRatePoint, NormalizedMarketEvidencePayload, NormalizedMarketNewsItem, NormalizedPositioningSentimentPoint, NormalizedPreciousMetalsFlowPoint, NormalizedPriceBar, NormalizedRealYieldPoint, NormalizedRiskSentimentPoint, NormalizedVolatilitySurfacePoint } from '@elceo/types';
import { MARKET_EVIDENCE_DATA_QUALITIES } from '@elceo/types';
import { isEnumValue, isFiniteNumber, isIsoDateString, isNonEmptyString, isObjectRecord, isScore0to100, isStringArray, type SchemaValidationResult } from './validation-utils';
const ns=(v:unknown)=>v===null||typeof v==='string'; const nn=(v:unknown)=>v===null||isFiniteNumber(v); const o=(i:unknown,n:string,p:string)=>isObjectRecord(i)?[]:[`${p}${n} must be object`];
export function validateNormalizedMarketEvidencePayload(input: unknown,p=''):SchemaValidationResult<NormalizedMarketEvidencePayload>{const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${p}NormalizedMarketEvidencePayload must be object`]}; if(!isNonEmptyString(input.payloadId)) e.push(`${p}payloadId must be non-empty string`); if(!isNonEmptyString(input.evidenceTypeId)) e.push(`${p}evidenceTypeId must be non-empty string`); if(!isNonEmptyString(input.evidenceClass)) e.push(`${p}evidenceClass must be non-empty string`); if(!isNonEmptyString(input.providerId)) e.push(`${p}providerId must be non-empty string`); if(!ns(input.sourceId)||!isNonEmptyString(input.region)||!ns(input.asset)) e.push(`${p}sourceId/region/asset invalid`); if(!isIsoDateString(input.observedAt)||!(input.publishedAt===null||isIsoDateString(input.publishedAt))||!isIsoDateString(input.normalizedAt)) e.push(`${p}observedAt/publishedAt/normalizedAt invalid`); if(!isScore0to100(input.confidenceScore)) e.push(`${p}confidenceScore must be 0..100`); if(!isEnumValue(input.dataQuality,MARKET_EVIDENCE_DATA_QUALITIES as readonly MarketEvidenceDataQuality[])) e.push(`${p}dataQuality is invalid`); if(typeof input.valuesJson!=='string'||typeof input.metadataJson!=='string') e.push(`${p}valuesJson/metadataJson must be string`); return e.length?{ok:false,errors:e}:{ok:true,value:input as NormalizedMarketEvidencePayload}; }
export const validateNormalizedPriceBar=(i:unknown,p=''):SchemaValidationResult<NormalizedPriceBar>=>{const e=o(i,'NormalizedPriceBar',p); if(e.length)return{ok:false,errors:e}; const x=i as Record<string,unknown>; if(!isNonEmptyString(x.asset)||!isNonEmptyString(x.timeframe)||!isIsoDateString(x.timestamp)||!isFiniteNumber(x.open)||!isFiniteNumber(x.high)||!isFiniteNumber(x.low)||!isFiniteNumber(x.close)||!(x.volume===null||isFiniteNumber(x.volume))||!isNonEmptyString(x.providerId)) e.push(`${p}NormalizedPriceBar fields invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:i as NormalizedPriceBar};};
export const validateNormalizedCotPositioning=(i:unknown,p=''):SchemaValidationResult<NormalizedCotPositioning>=>{const e=o(i,'NormalizedCotPositioning',p); if(e.length)return{ok:false,errors:e}; const x=i as Record<string,unknown>; if(!isIsoDateString(x.reportDate)||!isNonEmptyString(x.marketName)||!ns(x.asset)||!isFiniteNumber(x.commercialLong)||!isFiniteNumber(x.commercialShort)||!isFiniteNumber(x.nonCommercialLong)||!isFiniteNumber(x.nonCommercialShort)||!isFiniteNumber(x.netNonCommercial)||!isFiniteNumber(x.openInterest)||!isNonEmptyString(x.providerId)) e.push(`${p}NormalizedCotPositioning fields invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:i as NormalizedCotPositioning};};
export const validateNormalizedFuturesPositioning=(i:unknown,p=''):SchemaValidationResult<NormalizedFuturesPositioning>=>{const e=o(i,'NormalizedFuturesPositioning',p); if(e.length)return{ok:false,errors:e}; const x=i as Record<string,unknown>; if(!isIsoDateString(x.reportDate)||!isNonEmptyString(x.marketName)||!ns(x.asset)||!isFiniteNumber(x.leveragedFundsLong)||!isFiniteNumber(x.leveragedFundsShort)||!isFiniteNumber(x.assetManagerLong)||!isFiniteNumber(x.assetManagerShort)||!isFiniteNumber(x.openInterest)||!isNonEmptyString(x.providerId)) e.push(`${p}NormalizedFuturesPositioning fields invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:i as NormalizedFuturesPositioning};};

export const validateNormalizedCentralBankBalanceSheetPoint=(i:unknown,p=''):SchemaValidationResult<NormalizedCentralBankBalanceSheetPoint>=>{const e=o(i,'NormalizedCentralBankBalanceSheetPoint',p); if(e.length)return{ok:false,errors:e}; const x=i as Record<string,unknown>; if(!isNonEmptyString(x.institution)||!isNonEmptyString(x.region)||!isIsoDateString(x.observedAt)||!isNonEmptyString(x.metricName)||!isFiniteNumber(x.value)||!ns(x.currency)||!isNonEmptyString(x.unit)||!isNonEmptyString(x.providerId)) e.push(`${p}NormalizedCentralBankBalanceSheetPoint fields invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:i as NormalizedCentralBankBalanceSheetPoint};};

export const validateNormalizedCentralBankLiquidity=(i:unknown,p=''):SchemaValidationResult<NormalizedCentralBankLiquidity>=>{const e=o(i,'NormalizedCentralBankLiquidity',p); if(e.length)return{ok:false,errors:e}; const x=i as Record<string,unknown>; if(!isNonEmptyString(x.institution)||!isNonEmptyString(x.region)||!isIsoDateString(x.operationDate)||!isNonEmptyString(x.operationType)||!isFiniteNumber(x.amount)||!isNonEmptyString(x.currency)||!(x.maturityDays===null||Number.isInteger(x.maturityDays as number))||!isNonEmptyString(x.providerId)) e.push(`${p}NormalizedCentralBankLiquidity fields invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:i as NormalizedCentralBankLiquidity};};

export const validateNormalizedPolicyRatePoint=(i:unknown,p=''):SchemaValidationResult<NormalizedPolicyRatePoint>=>{const e=o(i,'NormalizedPolicyRatePoint',p); if(e.length)return{ok:false,errors:e}; const x=i as Record<string,unknown>; if(!isNonEmptyString(x.institution)||!isNonEmptyString(x.region)||!isIsoDateString(x.observedAt)||!isNonEmptyString(x.rateName)||!isFiniteNumber(x.value)||!isNonEmptyString(x.providerId)) e.push(`${p}NormalizedPolicyRatePoint fields invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:i as NormalizedPolicyRatePoint};};

export const validateNormalizedRealYieldPoint=(i:unknown,p=''):SchemaValidationResult<NormalizedRealYieldPoint>=>{const e=o(i,'NormalizedRealYieldPoint',p); if(e.length)return{ok:false,errors:e}; const x=i as Record<string,unknown>; if(!isNonEmptyString(x.region)||!isNonEmptyString(x.maturity)||!isIsoDateString(x.observedAt)||!isFiniteNumber(x.value)||!isNonEmptyString(x.providerId)) e.push(`${p}NormalizedRealYieldPoint fields invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:i as NormalizedRealYieldPoint};};
export const validateNormalizedBondAuctionResult=(i:unknown,p=''):SchemaValidationResult<NormalizedBondAuctionResult>=>{const e=o(i,'NormalizedBondAuctionResult',p); if(e.length)return{ok:false,errors:e}; const x=i as Record<string,unknown>; if(!isNonEmptyString(x.issuer)||!isNonEmptyString(x.region)||!isIsoDateString(x.auctionDate)||!isNonEmptyString(x.maturity)||!isFiniteNumber(x.yieldAwarded)||!nn(x.bidToCover)||!nn(x.amountOffered)||!nn(x.amountAccepted)||!isNonEmptyString(x.providerId)) e.push(`${p}NormalizedBondAuctionResult fields invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:i as NormalizedBondAuctionResult};};

export const validateNormalizedDebtSupplyCalendarItem=(i:unknown,p=''):SchemaValidationResult<NormalizedDebtSupplyCalendarItem>=>{const e=o(i,'NormalizedDebtSupplyCalendarItem',p); if(e.length)return{ok:false,errors:e}; const x=i as Record<string,unknown>; if(!isNonEmptyString(x.issuer)||!isNonEmptyString(x.region)||!isIsoDateString(x.announcementDate)||!(x.auctionDate===null||isIsoDateString(x.auctionDate))||!isNonEmptyString(x.maturity)||!nn(x.amountExpected)||!isNonEmptyString(x.currency)||!isNonEmptyString(x.providerId)) e.push(`${p}NormalizedDebtSupplyCalendarItem fields invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:i as NormalizedDebtSupplyCalendarItem};};

export const validateNormalizedCreditStressIndicator=(i:unknown,p=''):SchemaValidationResult<NormalizedCreditStressIndicator>=>{const e=o(i,'NormalizedCreditStressIndicator',p); if(e.length)return{ok:false,errors:e}; const x=i as Record<string,unknown>; if(!isNonEmptyString(x.region)||!isNonEmptyString(x.indicatorName)||!isIsoDateString(x.observedAt)||!isFiniteNumber(x.value)||!isNonEmptyString(x.unit)||!isNonEmptyString(x.providerId)) e.push(`${p}NormalizedCreditStressIndicator fields invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:i as NormalizedCreditStressIndicator};};
export const validateNormalizedVolatilitySurfacePoint=(i:unknown,p=''):SchemaValidationResult<NormalizedVolatilitySurfacePoint>=>{const e=o(i,'NormalizedVolatilitySurfacePoint',p); if(e.length)return{ok:false,errors:e}; const x=i as Record<string,unknown>; if(!isNonEmptyString(x.asset)||!isIsoDateString(x.observedAt)||!isIsoDateString(x.expiry)||!isNonEmptyString(x.tenor)||!isFiniteNumber(x.strikeDelta)||!isFiniteNumber(x.impliedVolatility)||!isNonEmptyString(x.providerId)) e.push(`${p}NormalizedVolatilitySurfacePoint fields invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:i as NormalizedVolatilitySurfacePoint};};

export const validateNormalizedMacroCalendarEvent=(i:unknown,p=''):SchemaValidationResult<NormalizedMacroCalendarEvent>=>{const e=o(i,'NormalizedMacroCalendarEvent',p); if(e.length)return{ok:false,errors:e}; const x=i as Record<string,unknown>; if(!isNonEmptyString(x.eventId)||!isNonEmptyString(x.region)||!isNonEmptyString(x.countryOrBloc)||!isNonEmptyString(x.eventName)||!isEnumValue(x.eventCategory,['inflation','labor_market','growth_activity','policy','other'] as const)||!isIsoDateString(x.scheduledFor)||!nn(x.actual)||!nn(x.consensus)||!nn(x.previous)||!ns(x.unit)||!isScore0to100(x.importanceScore)||!isNonEmptyString(x.providerId)) e.push(`${p}NormalizedMacroCalendarEvent fields invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:i as NormalizedMacroCalendarEvent};};
export const validateNormalizedMacroIndicatorPoint=(i:unknown,p=''):SchemaValidationResult<NormalizedMacroIndicatorPoint>=>{const e=o(i,'NormalizedMacroIndicatorPoint',p); if(e.length)return{ok:false,errors:e}; const x=i as Record<string,unknown>; if(!isNonEmptyString(x.region)||!isNonEmptyString(x.countryOrBloc)||!isNonEmptyString(x.indicatorName)||!isEnumValue(x.indicatorCategory,['inflation','labor_market','growth_activity','economic_indicator'] as const)||!isIsoDateString(x.observedAt)||!isNonEmptyString(x.period)||!isFiniteNumber(x.actual)||!nn(x.consensus)||!nn(x.previous)||!ns(x.unit)||!isNonEmptyString(x.providerId)) e.push(`${p}NormalizedMacroIndicatorPoint fields invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:i as NormalizedMacroIndicatorPoint};};

export const validateNormalizedMacroSurprisePoint=(i:unknown,p=''):SchemaValidationResult<NormalizedMacroSurprisePoint>=>{const e=o(i,'NormalizedMacroSurprisePoint',p); if(e.length)return{ok:false,errors:e}; const x=i as Record<string,unknown>; if(!isNonEmptyString(x.region)||!isNonEmptyString(x.indicatorName)||!isIsoDateString(x.observedAt)||!isFiniteNumber(x.actual)||!nn(x.consensus)||!nn(x.previous)||!isFiniteNumber(x.surprise)||!isNonEmptyString(x.providerId)) e.push(`${p}NormalizedMacroSurprisePoint fields invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:i as NormalizedMacroSurprisePoint};};
export const validateNormalizedBankHealthMetric=(i:unknown,p=''):SchemaValidationResult<NormalizedBankHealthMetric>=>{const e=o(i,'NormalizedBankHealthMetric',p); if(e.length)return{ok:false,errors:e}; const x=i as Record<string,unknown>; if(!isNonEmptyString(x.institution)||!isNonEmptyString(x.region)||!isIsoDateString(x.reportDate)||!isNonEmptyString(x.metricName)||!isFiniteNumber(x.value)||!isNonEmptyString(x.unit)||!isNonEmptyString(x.providerId)) e.push(`${p}NormalizedBankHealthMetric fields invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:i as NormalizedBankHealthMetric};};
const vp=(i:unknown,p=''):string[]=>{const e=o(i,'point',p); if(e.length)return e; return [];};
export const validateNormalizedFinancialConditionsPoint=(i:unknown,p=''):SchemaValidationResult<NormalizedFinancialConditionsPoint>=>{const e=vp(i,''); const x=i as Record<string,unknown>; if(!isNonEmptyString(x.region)||!isIsoDateString(x.observedAt)||!isNonEmptyString(x.indexName)||!isFiniteNumber(x.value)||!isNonEmptyString(x.unit)||!isNonEmptyString(x.providerId)) e.push(`${p}NormalizedFinancialConditionsPoint fields invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:i as NormalizedFinancialConditionsPoint};};
export const validateNormalizedLiquidityConditionPoint=(i:unknown,p=''):SchemaValidationResult<NormalizedLiquidityConditionPoint>=>{const e=vp(i,''); const x=i as Record<string,unknown>; if(!isNonEmptyString(x.region)||!isIsoDateString(x.observedAt)||!isNonEmptyString(x.indicatorName)||!isFiniteNumber(x.value)||!isNonEmptyString(x.unit)||!isNonEmptyString(x.providerId)) e.push(`${p}NormalizedLiquidityConditionPoint fields invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:i as NormalizedLiquidityConditionPoint};};
export const validateNormalizedDollarLiquidityPoint=(i:unknown,p=''):SchemaValidationResult<NormalizedDollarLiquidityPoint>=>{const e=vp(i,''); const x=i as Record<string,unknown>; if(!isNonEmptyString(x.region)||!isIsoDateString(x.observedAt)||!isNonEmptyString(x.indicatorName)||!isFiniteNumber(x.value)||!isNonEmptyString(x.unit)||!isNonEmptyString(x.providerId)) e.push(`${p}NormalizedDollarLiquidityPoint fields invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:i as NormalizedDollarLiquidityPoint};};
export const validateNormalizedCrossMarketRatePoint=(i:unknown,p=''):SchemaValidationResult<NormalizedCrossMarketRatePoint>=>{const e=vp(i,''); const x=i as Record<string,unknown>; if(!isNonEmptyString(x.baseAsset)||!isNonEmptyString(x.quoteAsset)||!isIsoDateString(x.observedAt)||!isFiniteNumber(x.value)||!isNonEmptyString(x.providerId)) e.push(`${p}NormalizedCrossMarketRatePoint fields invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:i as NormalizedCrossMarketRatePoint};};
export const validateNormalizedEquityBreadthPoint=(i:unknown,p=''):SchemaValidationResult<NormalizedEquityBreadthPoint>=>{const e=vp(i,''); const x=i as Record<string,unknown>; if(!isNonEmptyString(x.region)||!isIsoDateString(x.observedAt)||!isNonEmptyString(x.indexName)||!isFiniteNumber(x.advancing)||!isFiniteNumber(x.declining)||!isFiniteNumber(x.breadthRatio)||!isNonEmptyString(x.providerId)) e.push(`${p}NormalizedEquityBreadthPoint fields invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:i as NormalizedEquityBreadthPoint};};
export const validateNormalizedCryptoMarketStructurePoint=(i:unknown,p=''):SchemaValidationResult<NormalizedCryptoMarketStructurePoint>=>{const e=vp(i,''); const x=i as Record<string,unknown>; if(!isNonEmptyString(x.asset)||!isIsoDateString(x.observedAt)||!isNonEmptyString(x.metricName)||!isFiniteNumber(x.value)||!isNonEmptyString(x.unit)||!isNonEmptyString(x.providerId)) e.push(`${p}NormalizedCryptoMarketStructurePoint fields invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:i as NormalizedCryptoMarketStructurePoint};};
export const validateNormalizedEnergyCommodityPoint=(i:unknown,p=''):SchemaValidationResult<NormalizedEnergyCommodityPoint>=>{const e=vp(i,''); const x=i as Record<string,unknown>; if(!isNonEmptyString(x.commodity)||!isIsoDateString(x.observedAt)||!isFiniteNumber(x.price)||!isNonEmptyString(x.currency)||!isNonEmptyString(x.providerId)) e.push(`${p}NormalizedEnergyCommodityPoint fields invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:i as NormalizedEnergyCommodityPoint};};
export const validateNormalizedPreciousMetalsFlowPoint=(i:unknown,p=''):SchemaValidationResult<NormalizedPreciousMetalsFlowPoint>=>{const e=vp(i,''); const x=i as Record<string,unknown>; if(!isNonEmptyString(x.asset)||!isIsoDateString(x.observedAt)||!isFiniteNumber(x.flowAmount)||!isNonEmptyString(x.unit)||!isNonEmptyString(x.providerId)) e.push(`${p}NormalizedPreciousMetalsFlowPoint fields invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:i as NormalizedPreciousMetalsFlowPoint};};
export const validateNormalizedRiskSentimentPoint=(i:unknown,p=''):SchemaValidationResult<NormalizedRiskSentimentPoint>=>{const e=vp(i,''); const x=i as Record<string,unknown>; if(!isNonEmptyString(x.region)||!isIsoDateString(x.observedAt)||!isNonEmptyString(x.indicatorName)||!isScore0to100(x.score)||!isNonEmptyString(x.providerId)) e.push(`${p}NormalizedRiskSentimentPoint fields invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:i as NormalizedRiskSentimentPoint};};
export const validateNormalizedGeopoliticalRiskEvent=(i:unknown,p=''):SchemaValidationResult<NormalizedGeopoliticalRiskEvent>=>{const e=vp(i,''); const x=i as Record<string,unknown>; if(!isNonEmptyString(x.eventId)||!isNonEmptyString(x.region)||!isIsoDateString(x.publishedAt)||!isEnumValue(x.severity,['low','medium','high','critical'] as const)||!isNonEmptyString(x.title)||!isNonEmptyString(x.providerId)) e.push(`${p}NormalizedGeopoliticalRiskEvent fields invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:i as NormalizedGeopoliticalRiskEvent};};
export const validateNormalizedEarningsMacroPoint=(i:unknown,p=''):SchemaValidationResult<NormalizedEarningsMacroPoint>=>{const e=vp(i,''); const x=i as Record<string,unknown>; if(!isNonEmptyString(x.region)||!isIsoDateString(x.observedAt)||!isNonEmptyString(x.metricName)||!isFiniteNumber(x.value)||!isNonEmptyString(x.unit)||!isNonEmptyString(x.providerId)) e.push(`${p}NormalizedEarningsMacroPoint fields invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:i as NormalizedEarningsMacroPoint};};
export const validateNormalizedPositioningSentimentPoint=(i:unknown,p=''):SchemaValidationResult<NormalizedPositioningSentimentPoint>=>{const e=vp(i,''); const x=i as Record<string,unknown>; if(!isNonEmptyString(x.asset)||!isIsoDateString(x.observedAt)||!isScore0to100(x.longPercent)||!isScore0to100(x.shortPercent)||!isFiniteNumber(x.netSkew)||!isNonEmptyString(x.providerId)) e.push(`${p}NormalizedPositioningSentimentPoint fields invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:i as NormalizedPositioningSentimentPoint};};
export const validateNormalizedMarketNewsItem=(i:unknown,p=''):SchemaValidationResult<NormalizedMarketNewsItem>=>{const e=vp(i,''); const x=i as Record<string,unknown>; if(!isNonEmptyString(x.newsId)||!isNonEmptyString(x.providerId)||!isNonEmptyString(x.title)||!ns(x.url)||!isIsoDateString(x.publishedAt)||!isNonEmptyString(x.sourceName)||!isStringArray(x.relatedAssets)||!isStringArray(x.relatedEvidenceClasses)||!nn(x.sentiment)||!isScore0to100(x.importanceScore)) e.push(`${p}NormalizedMarketNewsItem fields invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:i as NormalizedMarketNewsItem};};

export const validateNormalizedBankEarningsMetric=(i:unknown,p=''):SchemaValidationResult<NormalizedBankEarningsMetric>=>{const e=o(i,'NormalizedBankEarningsMetric',p); if(e.length)return{ok:false,errors:e}; const x=i as Record<string,unknown>; if(!isNonEmptyString(x.institution)||!isNonEmptyString(x.region)||!isIsoDateString(x.reportDate)||!isNonEmptyString(x.fiscalPeriod)||!isNonEmptyString(x.metricName)||!isFiniteNumber(x.value)||!isNonEmptyString(x.unit)||!isNonEmptyString(x.providerId)) e.push(`${p}NormalizedBankEarningsMetric fields invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:i as NormalizedBankEarningsMetric};};
export const validateNormalizedStressTestResult=(i:unknown,p=''):SchemaValidationResult<NormalizedStressTestResult>=>{const e=o(i,'NormalizedStressTestResult',p); if(e.length)return{ok:false,errors:e}; const x=i as Record<string,unknown>; if(!isNonEmptyString(x.institution)||!isNonEmptyString(x.region)||!isIsoDateString(x.reportDate)||!isNonEmptyString(x.scenarioName)||!isNonEmptyString(x.metricName)||!isFiniteNumber(x.value)||!isNonEmptyString(x.unit)||!isNonEmptyString(x.providerId)) e.push(`${p}NormalizedStressTestResult fields invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:i as NormalizedStressTestResult};};
export const validateNormalizedRegulatoryFilingReference=(i:unknown,p=''):SchemaValidationResult<NormalizedRegulatoryFilingReference>=>{const e=o(i,'NormalizedRegulatoryFilingReference',p); if(e.length)return{ok:false,errors:e}; const x=i as Record<string,unknown>; const urlOk=x.url===null||(typeof x.url==='string'&&/^https?:\/\//.test(x.url)); if(!isNonEmptyString(x.filingId)||!isNonEmptyString(x.institution)||!isNonEmptyString(x.region)||!isIsoDateString(x.filingDate)||!isNonEmptyString(x.filingType)||!isNonEmptyString(x.title)||!urlOk||!isNonEmptyString(x.providerId)) e.push(`${p}NormalizedRegulatoryFilingReference fields invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:i as NormalizedRegulatoryFilingReference};};
export const validateNormalizedInstitutionalLiquidityMetric=(i:unknown,p=''):SchemaValidationResult<NormalizedInstitutionalLiquidityMetric>=>{const e=o(i,'NormalizedInstitutionalLiquidityMetric',p); if(e.length)return{ok:false,errors:e}; const x=i as Record<string,unknown>; if(!isNonEmptyString(x.institution)||!isNonEmptyString(x.region)||!isIsoDateString(x.observedAt)||!isNonEmptyString(x.metricName)||!isFiniteNumber(x.value)||!isNonEmptyString(x.unit)||!isNonEmptyString(x.providerId)) e.push(`${p}NormalizedInstitutionalLiquidityMetric fields invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:i as NormalizedInstitutionalLiquidityMetric};};
