import type { MarketReasoningModuleId, MarketReasoningModuleReadiness, MarketReasoningReadinessReport } from '@elceo/types';
import { MARKET_REASONING_CONTRACT_SHAPE_STATUSES, MARKET_REASONING_DETERMINISTIC_FOUNDATION_STATUSES, MARKET_REASONING_EMPIRICAL_VALIDATION_STATUSES, MARKET_REASONING_LIVE_PROVIDER_INTEGRATION_STATUSES, MARKET_REASONING_MODULE_IDS, MARKET_REASONING_PRODUCTION_CALIBRATION_STATUSES } from '@elceo/types';
import { isEnumValue, isIsoDateString, isNonEmptyString, isObjectRecord, isStringArray, type SchemaValidationResult } from './validation-utils';
const ADVICE=/\b(buy|sell|long|short|entry|stop loss|take profit|guaranteed|should trade)\b/i;
const PHASE=/pendingPhases|confidenceCalibrationR6|priceReactionR7|providerReliabilityExpansion|goldenScenarioExpansion|empiricalBacktesting|liveProviderActivation|productionDataCalibration|pending_r2_r9/i;
const READINESS_KEYS=['moduleId','contractShapeStatus','deterministicFoundationStatus','liveProviderIntegrationStatus','empiricalValidationStatus','productionCalibrationStatus','notes'];
const REPORT_KEYS=['generatedAt','modules','moduleCount','notes'];
function validNotes(v:unknown,p:string,e:string[]){ if(!isStringArray(v)||v.length===0) e.push(`${p}notes invalid`); else for(const n of v){ if(!n.trim()||ADVICE.test(n)||PHASE.test(n)) e.push(`${p}notes invalid`); }}
function extraKeys(input:Record<string,unknown>, allowed:readonly string[], p:string, e:string[]){ for(const k of Object.keys(input)){ if(!allowed.includes(k)) e.push(`${p}${k} unknown`); if(PHASE.test(k)) e.push(`${p}${k} is stale phase metadata`); }}
export function validateMarketReasoningModuleReadiness(input:unknown,p=''):SchemaValidationResult<MarketReasoningModuleReadiness>{const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${p}readiness object required`]}; extraKeys(input,READINESS_KEYS,p,e); if(!isEnumValue(input.moduleId,MARKET_REASONING_MODULE_IDS)) e.push(`${p}moduleId invalid`); if(!isEnumValue(input.contractShapeStatus,MARKET_REASONING_CONTRACT_SHAPE_STATUSES)) e.push(`${p}contractShapeStatus invalid`); if(!isEnumValue(input.deterministicFoundationStatus,MARKET_REASONING_DETERMINISTIC_FOUNDATION_STATUSES)) e.push(`${p}deterministicFoundationStatus invalid`); if(!isEnumValue(input.liveProviderIntegrationStatus,MARKET_REASONING_LIVE_PROVIDER_INTEGRATION_STATUSES)) e.push(`${p}liveProviderIntegrationStatus invalid`); if(!isEnumValue(input.empiricalValidationStatus,MARKET_REASONING_EMPIRICAL_VALIDATION_STATUSES)) e.push(`${p}empiricalValidationStatus invalid`); if(!isEnumValue(input.productionCalibrationStatus,MARKET_REASONING_PRODUCTION_CALIBRATION_STATUSES)) e.push(`${p}productionCalibrationStatus invalid`); if(input.contractShapeStatus==='invalid') e.push(`${p}contractShapeStatus invalid for emitted report`); validNotes(input.notes,p,e); return e.length?{ok:false,errors:e}:{ok:true,value:input as MarketReasoningModuleReadiness};}
export function validateMarketReasoningReadinessReport(input:unknown,p=''):SchemaValidationResult<MarketReasoningReadinessReport>{const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${p}readiness report required`]}; extraKeys(input,REPORT_KEYS,p,e); if(!isIsoDateString(input.generatedAt)) e.push(`${p}generatedAt invalid`); if(input.moduleCount!==MARKET_REASONING_MODULE_IDS.length) e.push(`${p}moduleCount invalid`); if(!Array.isArray(input.modules)) e.push(`${p}modules invalid`); else {const ids=input.modules.map((m:any)=>m?.moduleId); if(new Set(ids).size!==ids.length) e.push(`${p}duplicate moduleId`); for(const id of MARKET_REASONING_MODULE_IDS) if(!ids.includes(id)) e.push(`${p}${id} missing`); input.modules.forEach((m,i)=>{const r=validateMarketReasoningModuleReadiness(m,`${p}modules[${i}].`); if(r.ok===false)e.push(...r.errors);});} validNotes(input.notes,p,e); return e.length?{ok:false,errors:e}:{ok:true,value:input as MarketReasoningReadinessReport};}
export function validateExpectedMarketReasoningModuleReadiness(value:unknown, expectedModuleId: MarketReasoningModuleId, path=''):SchemaValidationResult<MarketReasoningModuleReadiness>{ const r=validateMarketReasoningModuleReadiness(value,path); if(r.ok===false) return r; const errors:string[]=[]; if(r.value.moduleId!==expectedModuleId) errors.push(`${path}moduleId must be ${expectedModuleId}`); return errors.length?{ok:false,errors}:{ok:true,value:r.value};}
