import type { EtfFlowFixturePayload, FilingFixturePayload, NarrativeClusterFixturePayload, NewsExtractionAdapterReadiness, NewsExtractionCoverageReport, NewsExtractionFixtureArticle, NewsExtractionFixturePayload, NewsExtractionNormalizedEvidence, NewsExtractionSourceDescriptor } from '@elceo/types';
import { ETF_FLOW_EVENT_KINDS, FILING_EVENT_KINDS, NARRATIVE_CLUSTER_KINDS, NEWS_EXTRACTION_ACTIVATION_STATUSES, NEWS_EXTRACTION_EVIDENCE_CLASSES, NEWS_EXTRACTION_EVENT_KINDS, NEWS_EXTRACTION_FAMILIES, NEWS_EXTRACTION_FRESHNESS_STATES, NEWS_EXTRACTION_RISK_LEVELS, NEWS_EXTRACTION_SENTIMENTS, NEWS_EXTRACTION_SOURCE_IDS, PROVIDER_SOURCE_IDS } from '@elceo/types';
import { isEnumValue, isIsoDateString, isNonEmptyString, isObjectRecord, type SchemaValidationResult } from './validation-utils';
const ASSETS=['xau_usd','eur_usd','gbp_usd','usd_jpy','aud_usd','usd_chf','nzd_usd','usd_cad','btc_usd','nasdaq_100','sp500','de30','dxy','vix'] as const; const BAN=/\b(buy|sell|hold|guaranteed profit|profit certainty)\b/i; const SECRET=/(api[_-]?key|secret|token|password)/i; const sorted=(v:readonly string[])=>v.every((x,i)=>i===0||x>=v[i-1]!); const scan=(o:Record<string,unknown>,e:string[],p:string)=>Object.keys(o).forEach((k)=>{if(SECRET.test(k))e.push(`${p}${k} forbidden`); const v=o[k]; if(typeof v==='string'&&BAN.test(v))e.push(`${p}${k} forbidden language`);});
export function validateNewsExtractionSourceDescriptor(i:unknown,p=''):SchemaValidationResult<NewsExtractionSourceDescriptor>{const e:string[]=[]; if(!isObjectRecord(i)) return {ok:false,errors:[`${p}source descriptor object`]}; scan(i,e,p); if(!isEnumValue(i.sourceId,NEWS_EXTRACTION_SOURCE_IDS)||!isEnumValue(i.providerSourceId,PROVIDER_SOURCE_IDS)||!isEnumValue(i.family,NEWS_EXTRACTION_FAMILIES)||!isNonEmptyString(i.displayName)||!Array.isArray(i.eventKinds)||!i.eventKinds.every((x)=>isEnumValue(x,NEWS_EXTRACTION_EVENT_KINDS))||!sorted(i.eventKinds)||!Array.isArray(i.evidenceClasses)||!i.evidenceClasses.every((x)=>isEnumValue(x,NEWS_EXTRACTION_EVIDENCE_CLASSES))||!sorted(i.evidenceClasses)||!Array.isArray(i.assetRelevance)||i.assetRelevance.length===0||!i.assetRelevance.every((x)=>isEnumValue(x,ASSETS))||!sorted(i.assetRelevance)||!isEnumValue(i.activationStatus,NEWS_EXTRACTION_ACTIVATION_STATUSES)||i.liveBlockedByDefault!==true) e.push(`${p}invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:i as NewsExtractionSourceDescriptor};}
export function validateNewsExtractionFixtureArticle(i:unknown,p=''):SchemaValidationResult<NewsExtractionFixtureArticle>{const e:string[]=[]; if(!isObjectRecord(i)) return {ok:false,errors:[`${p}article object`]}; scan(i,e,p); if(!isNonEmptyString(i.fixtureId)||!isEnumValue(i.sourceId,NEWS_EXTRACTION_SOURCE_IDS)||!isEnumValue(i.eventKind,NEWS_EXTRACTION_EVENT_KINDS)||!isEnumValue(i.evidenceClass,NEWS_EXTRACTION_EVIDENCE_CLASSES)||!isIsoDateString(i.observedAt)||!isNonEmptyString(i.title)||!isNonEmptyString(i.summary)||!isNonEmptyString(i.sourceName)||!isNonEmptyString(i.region)||!Array.isArray(i.affectedAssets)||i.affectedAssets.length===0||!i.affectedAssets.every((x)=>isEnumValue(x,ASSETS))||!sorted(i.affectedAssets)||!isEnumValue(i.sentiment,NEWS_EXTRACTION_SENTIMENTS)||!isEnumValue(i.riskLevel,NEWS_EXTRACTION_RISK_LEVELS)||!isEnumValue(i.freshnessState,NEWS_EXTRACTION_FRESHNESS_STATES)) e.push(`${p}invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:i as NewsExtractionFixtureArticle};}
export const validateNewsExtractionFixturePayload=(i:unknown,p=''):SchemaValidationResult<NewsExtractionFixturePayload>=>{if(!isObjectRecord(i)||!isEnumValue(i.sourceId,NEWS_EXTRACTION_SOURCE_IDS)||!isNonEmptyString(i.fixtureId)||!Array.isArray(i.articles)||i.articles.length===0) return {ok:false,errors:[`${p}invalid`]}; const e:string[]=[]; i.articles.forEach((x,n)=>{const r=validateNewsExtractionFixtureArticle(x,`${p}articles[${n}].`); if(r.ok===false)e.push(...r.errors);}); return e.length?{ok:false,errors:e}:{ok:true,value:i as NewsExtractionFixturePayload};};
export const validateNewsExtractionNormalizedEvidence=(i:unknown,p=''):SchemaValidationResult<NewsExtractionNormalizedEvidence>=>{if(!isObjectRecord(i)||!isNonEmptyString(i.evidenceId)||!isEnumValue(i.sourceId,NEWS_EXTRACTION_SOURCE_IDS)||!isEnumValue(i.sourceFamily,NEWS_EXTRACTION_FAMILIES)||!isEnumValue(i.eventKind,NEWS_EXTRACTION_EVENT_KINDS)||!isEnumValue(i.evidenceClass,NEWS_EXTRACTION_EVIDENCE_CLASSES)||!isIsoDateString(i.observedAt)||!isEnumValue(i.freshnessState,NEWS_EXTRACTION_FRESHNESS_STATES)||!Array.isArray(i.affectedAssets)||i.affectedAssets.length===0||!isEnumValue(i.sentiment,NEWS_EXTRACTION_SENTIMENTS)||!isEnumValue(i.riskLevel,NEWS_EXTRACTION_RISK_LEVELS)||!isNonEmptyString(i.narrativeSummary)) return {ok:false,errors:[`${p}invalid`]}; return {ok:true,value:i as NewsExtractionNormalizedEvidence};};
export const validateFilingFixturePayload=(i:unknown):SchemaValidationResult<FilingFixturePayload>=>(!isObjectRecord(i)||!isEnumValue(i.eventKind,FILING_EVENT_KINDS)||!isIsoDateString(i.observedAt)||!Array.isArray(i.affectedAssets)||!i.affectedAssets.length)?{ok:false,errors:['invalid']}:{ok:true,value:i as FilingFixturePayload};
export const validateEtfFlowFixturePayload=(i:unknown):SchemaValidationResult<EtfFlowFixturePayload>=>(!isObjectRecord(i)||!isEnumValue(i.eventKind,ETF_FLOW_EVENT_KINDS)||!isIsoDateString(i.observedAt)||!Array.isArray(i.affectedAssets)||!i.affectedAssets.length)?{ok:false,errors:['invalid']}:{ok:true,value:i as EtfFlowFixturePayload};
export const validateNarrativeClusterFixturePayload=(i:unknown):SchemaValidationResult<NarrativeClusterFixturePayload>=>(!isObjectRecord(i)||!isEnumValue(i.clusterKind,NARRATIVE_CLUSTER_KINDS)||!isIsoDateString(i.observedAt)||!Array.isArray(i.affectedAssets)||!i.affectedAssets.length)?{ok:false,errors:['invalid']}:{ok:true,value:i as NarrativeClusterFixturePayload};
export const validateNewsExtractionAdapterReadiness=(i:unknown):SchemaValidationResult<NewsExtractionAdapterReadiness>=>(!isObjectRecord(i)||!isEnumValue(i.sourceId,NEWS_EXTRACTION_SOURCE_IDS)||!isEnumValue(i.providerSourceId,PROVIDER_SOURCE_IDS)||!isEnumValue(i.status,NEWS_EXTRACTION_ACTIVATION_STATUSES)||i.liveBlockedByDefault!==true||i.noApiKeyRequiredInFixtureMode!==true)?{ok:false,errors:['invalid']}:{ok:true,value:i as NewsExtractionAdapterReadiness};
export const validateNewsExtractionCoverageReport=(i:unknown):SchemaValidationResult<NewsExtractionCoverageReport>=>(!isObjectRecord(i)||!isIsoDateString(i.generatedAt)||!Array.isArray(i.sources)||!Array.isArray(i.fixtureCounts)||!Array.isArray(i.assetsCovered))?{ok:false,errors:['invalid']}:{ok:true,value:i as NewsExtractionCoverageReport};
