import type { OfficialMacroAdapterReadiness, OfficialMacroCoverageReport, OfficialMacroFixturePayload, OfficialMacroNormalizedEvidence, OfficialMacroPolicyEventDescriptor, OfficialMacroReleaseDescriptor, OfficialMacroSeriesDescriptor, OfficialMacroSourceDescriptor } from '@elceo/types';
import { OFFICIAL_MACRO_ACTIVATION_STATUSES, OFFICIAL_MACRO_EVIDENCE_CLASSES, OFFICIAL_MACRO_FIXTURE_MODES, OFFICIAL_MACRO_FREQUENCIES, OFFICIAL_MACRO_POLICY_KINDS, OFFICIAL_MACRO_REGIONS, OFFICIAL_MACRO_RELEASE_KINDS, OFFICIAL_MACRO_SOURCE_IDS, PROVIDER_SOURCE_IDS, MARKET_REASONING_DIAGNOSTIC_ASSETS, TRADING_ASSET_COVERAGE } from '@elceo/types';
import { isEnumValue, isIsoDateString, isNonEmptyString, isObjectRecord, type SchemaValidationResult } from './validation-utils';

const REASONING_ASSETS = [...TRADING_ASSET_COVERAGE, ...MARKET_REASONING_DIAGNOSTIC_ASSETS] as const;
const BAN = /\b(buy|sell|hold)\b/i;
const SECRET = /(api[_-]?key|secret|token|password)/i;
const sorted = (values: readonly string[]): boolean => values.every((value, i) => i === 0 || value >= values[i - 1]!);
const check = (obj: Record<string, unknown>, errors: string[], path: string): void => { for (const key of Object.keys(obj)) { if (SECRET.test(key)) errors.push(`${path}${key} forbidden`); const value = obj[key]; if (typeof value === 'string' && BAN.test(value)) errors.push(`${path}${key} has forbidden language`); } };

export function validateOfficialMacroSourceDescriptor(input: unknown, p = ''): SchemaValidationResult<OfficialMacroSourceDescriptor> { const e: string[] = []; if (!isObjectRecord(input)) return { ok: false, errors: [`${p}OfficialMacroSourceDescriptor must be object`] }; check(input, e, p); if (!isEnumValue(input.sourceId, OFFICIAL_MACRO_SOURCE_IDS)) e.push(`${p}sourceId invalid`); if (!isEnumValue(input.providerSourceId, PROVIDER_SOURCE_IDS)) e.push(`${p}providerSourceId invalid`); if (!isNonEmptyString(input.displayName)) e.push(`${p}displayName invalid`); if (!isEnumValue(input.region, OFFICIAL_MACRO_REGIONS)) e.push(`${p}region invalid`); if (!Array.isArray(input.releaseKinds) || !input.releaseKinds.every((x) => isEnumValue(x, OFFICIAL_MACRO_RELEASE_KINDS)) || !sorted(input.releaseKinds)) e.push(`${p}releaseKinds invalid`); if (!Array.isArray(input.policyKinds) || !input.policyKinds.every((x) => isEnumValue(x, OFFICIAL_MACRO_POLICY_KINDS)) || !sorted(input.policyKinds)) e.push(`${p}policyKinds invalid`); if (!Array.isArray(input.evidenceClasses) || !input.evidenceClasses.every((x) => isEnumValue(x, OFFICIAL_MACRO_EVIDENCE_CLASSES)) || !sorted(input.evidenceClasses)) e.push(`${p}evidenceClasses invalid`); if (!Array.isArray(input.assetRelevance) || !input.assetRelevance.every((x) => isEnumValue(x, REASONING_ASSETS)) || !sorted(input.assetRelevance)) e.push(`${p}assetRelevance invalid`); if (!isEnumValue(input.fixtureMode, OFFICIAL_MACRO_FIXTURE_MODES)) e.push(`${p}fixtureMode invalid`); if (!isEnumValue(input.activationStatus, OFFICIAL_MACRO_ACTIVATION_STATUSES)) e.push(`${p}activationStatus invalid`); return e.length ? { ok: false, errors: e } : { ok: true, value: input as OfficialMacroSourceDescriptor }; }
export function validateOfficialMacroReleaseDescriptor(input: unknown, p = ''): SchemaValidationResult<OfficialMacroReleaseDescriptor> { const e: string[] = []; if (!isObjectRecord(input)) return { ok: false, errors: [`${p}OfficialMacroReleaseDescriptor must be object`] }; check(input, e, p); if (!isEnumValue(input.sourceId, OFFICIAL_MACRO_SOURCE_IDS) || !isEnumValue(input.releaseKind, OFFICIAL_MACRO_RELEASE_KINDS) || !isNonEmptyString(input.title) || !isEnumValue(input.frequency, OFFICIAL_MACRO_FREQUENCIES) || !isEnumValue(input.region, OFFICIAL_MACRO_REGIONS) || !isNonEmptyString(input.seriesId)) e.push(`${p}release descriptor invalid`); return e.length ? { ok: false, errors: e } : { ok: true, value: input as OfficialMacroReleaseDescriptor }; }
export function validateOfficialMacroPolicyEventDescriptor(input: unknown, p = ''): SchemaValidationResult<OfficialMacroPolicyEventDescriptor> { const e: string[] = []; if (!isObjectRecord(input)) return { ok: false, errors: [`${p}OfficialMacroPolicyEventDescriptor must be object`] }; check(input, e, p); if (!isEnumValue(input.sourceId, OFFICIAL_MACRO_SOURCE_IDS) || !isEnumValue(input.policyKind, OFFICIAL_MACRO_POLICY_KINDS) || !isNonEmptyString(input.title) || !isIsoDateString(input.observedAt) || !isEnumValue(input.region, OFFICIAL_MACRO_REGIONS)) e.push(`${p}policy descriptor invalid`); return e.length ? { ok: false, errors: e } : { ok: true, value: input as OfficialMacroPolicyEventDescriptor }; }
export function validateOfficialMacroSeriesDescriptor(input: unknown, p = ''): SchemaValidationResult<OfficialMacroSeriesDescriptor> { const e: string[] = []; if (!isObjectRecord(input)) return { ok: false, errors: [`${p}OfficialMacroSeriesDescriptor must be object`] }; check(input, e, p); if (!isEnumValue(input.sourceId, OFFICIAL_MACRO_SOURCE_IDS) || !isEnumValue(input.releaseKind, OFFICIAL_MACRO_RELEASE_KINDS) || !isNonEmptyString(input.seriesId) || !isNonEmptyString(input.title) || !isEnumValue(input.frequency, OFFICIAL_MACRO_FREQUENCIES) || !isEnumValue(input.region, OFFICIAL_MACRO_REGIONS) || !isEnumValue(input.evidenceClass, OFFICIAL_MACRO_EVIDENCE_CLASSES)) e.push(`${p}series descriptor invalid`); return e.length ? { ok: false, errors: e } : { ok: true, value: input as OfficialMacroSeriesDescriptor }; }
export function validateOfficialMacroFixturePayload(input: unknown, p = ''): SchemaValidationResult<OfficialMacroFixturePayload> { const e: string[] = []; if (!isObjectRecord(input)) return { ok: false, errors: [`${p}OfficialMacroFixturePayload must be object`] }; check(input, e, p); if (!isNonEmptyString(input.fixtureId) || !isEnumValue(input.sourceId, OFFICIAL_MACRO_SOURCE_IDS) || !isEnumValue(input.region, OFFICIAL_MACRO_REGIONS) || !isIsoDateString(input.observedAt) || !isNonEmptyString(input.period) || !isNonEmptyString(input.title) || !isEnumValue(input.evidenceClass, OFFICIAL_MACRO_EVIDENCE_CLASSES) || !Array.isArray(input.assetRelevance) || input.assetRelevance.length === 0 || !input.assetRelevance.every((x) => isEnumValue(x, REASONING_ASSETS)) || !sorted(input.assetRelevance) || !isNonEmptyString(input.narrativeSummary)) e.push(`${p}fixture payload invalid`); return e.length ? { ok: false, errors: e } : { ok: true, value: input as OfficialMacroFixturePayload }; }
export function validateOfficialMacroNormalizedEvidence(input: unknown, p = ''): SchemaValidationResult<OfficialMacroNormalizedEvidence> { const e: string[] = []; if (!isObjectRecord(input)) return { ok: false, errors: [`${p}OfficialMacroNormalizedEvidence must be object`] }; check(input, e, p); if (!isNonEmptyString(input.evidenceId) || !isEnumValue(input.sourceId, OFFICIAL_MACRO_SOURCE_IDS) || !isEnumValue(input.region, OFFICIAL_MACRO_REGIONS) || !isEnumValue(input.evidenceClass, OFFICIAL_MACRO_EVIDENCE_CLASSES) || !isIsoDateString(input.observedAt) || !Array.isArray(input.assetRelevance) || input.assetRelevance.length === 0 || !sorted(input.assetRelevance) || !Array.isArray(input.qualityHints) || !sorted(input.qualityHints) || !isNonEmptyString(input.narrative) || !isNonEmptyString(input.rawFixtureId)) e.push(`${p}normalized evidence invalid`); return e.length ? { ok: false, errors: e } : { ok: true, value: input as OfficialMacroNormalizedEvidence }; }
export function validateOfficialMacroAdapterReadiness(input: unknown, p = ''): SchemaValidationResult<OfficialMacroAdapterReadiness> { const e: string[] = []; if (!isObjectRecord(input)) return { ok: false, errors: [`${p}OfficialMacroAdapterReadiness must be object`] }; check(input, e, p); if (!isEnumValue(input.sourceId, OFFICIAL_MACRO_SOURCE_IDS) || !isEnumValue(input.providerSourceId, PROVIDER_SOURCE_IDS) || !isEnumValue(input.status, OFFICIAL_MACRO_ACTIVATION_STATUSES) || !isEnumValue(input.fixtureMode, OFFICIAL_MACRO_FIXTURE_MODES) || input.liveBlockedByDefault !== true || !Array.isArray(input.notes) || !sorted(input.notes)) e.push(`${p}readiness invalid`); return e.length ? { ok: false, errors: e } : { ok: true, value: input as OfficialMacroAdapterReadiness }; }
export function validateOfficialMacroCoverageReport(input: unknown, p = ''): SchemaValidationResult<OfficialMacroCoverageReport> { const e: string[] = []; if (!isObjectRecord(input)) return { ok: false, errors: [`${p}OfficialMacroCoverageReport must be object`] }; if (!isIsoDateString(input.generatedAt)) e.push(`${p}generatedAt invalid`); if (!Array.isArray(input.sources) || !sorted(input.sources.map((x) => String((x as { sourceId?: string }).sourceId ?? '')))) e.push(`${p}sources invalid`); else input.sources.forEach((x, i) => { const r = validateOfficialMacroSourceDescriptor(x, `${p}sources[${i}].`); if (r.ok === false) e.push(...r.errors); }); if (!Array.isArray(input.releases)) e.push(`${p}releases invalid`); else input.releases.forEach((x, i) => { const r = validateOfficialMacroReleaseDescriptor(x, `${p}releases[${i}].`); if (r.ok === false) e.push(...r.errors); }); if (!Array.isArray(input.fixtures)) e.push(`${p}fixtures invalid`); return e.length ? { ok: false, errors: e } : { ok: true, value: input as OfficialMacroCoverageReport }; }
