import type { OpsJobHealthSummary, OpsJobLeaseRecord, OpsJobRunReport } from '@elceo/types';
import { OPS_JOB_KINDS, OPS_JOB_RUN_STATUSES, OPS_JOB_SCOPES, OPS_JOB_TRIGGER_KINDS, OPS_LEASE_STATES } from '@elceo/types';
import { isEnumValue, isFiniteNumber, isIsoDateString, isNonEmptyString, isObjectRecord, isStringArray, type SchemaValidationResult } from './validation-utils';
const nn=(v:unknown)=>isFiniteNumber(v)&&Number(v)>=0;
export function validateOpsJobLeaseRecord(input:unknown,pathPrefix=''):SchemaValidationResult<OpsJobLeaseRecord>{const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${pathPrefix}OpsJobLeaseRecord must be object`]};
if(!isNonEmptyString(input.leaseId)) e.push(`${pathPrefix}leaseId must be non-empty string`); if(!isEnumValue(input.jobKind,OPS_JOB_KINDS)) e.push(`${pathPrefix}jobKind is invalid`); if(!isEnumValue(input.scopeKind,OPS_JOB_SCOPES)) e.push(`${pathPrefix}scopeKind is invalid`); if(!isNonEmptyString(input.scopeKey)) e.push(`${pathPrefix}scopeKey must be non-empty string`); if(!isEnumValue(input.leaseState,OPS_LEASE_STATES)) e.push(`${pathPrefix}leaseState is invalid`); if(!isIsoDateString(input.acquiredAt)) e.push(`${pathPrefix}acquiredAt must be ISO date string`); if(!isIsoDateString(input.expiresAt)) e.push(`${pathPrefix}expiresAt must be ISO date string`); if(!(input.releasedAt===null||isIsoDateString(input.releasedAt))) e.push(`${pathPrefix}releasedAt must be ISO date string or null`); if(!isNonEmptyString(input.holderId)) e.push(`${pathPrefix}holderId must be non-empty string`); if(!isIsoDateString(input.createdAt)) e.push(`${pathPrefix}createdAt must be ISO date string`);
return e.length?{ok:false,errors:e}:{ok:true,value:input as OpsJobLeaseRecord};}
export function validateOpsJobRunReport(input:unknown,pathPrefix=''):SchemaValidationResult<OpsJobRunReport>{const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${pathPrefix}OpsJobRunReport must be object`]};
if(!isNonEmptyString(input.runId)) e.push(`${pathPrefix}runId must be non-empty string`); if(!isEnumValue(input.jobKind,OPS_JOB_KINDS)) e.push(`${pathPrefix}jobKind is invalid`); if(!isEnumValue(input.triggerKind,OPS_JOB_TRIGGER_KINDS)) e.push(`${pathPrefix}triggerKind is invalid`); if(!isEnumValue(input.scopeKind,OPS_JOB_SCOPES)) e.push(`${pathPrefix}scopeKind is invalid`); if(!isNonEmptyString(input.scopeKey)) e.push(`${pathPrefix}scopeKey must be non-empty string`); if(!isIsoDateString(input.startedAt)||!isIsoDateString(input.endedAt)) e.push(`${pathPrefix}startedAt/endedAt must be ISO date string`); if(!nn(input.durationMs)) e.push(`${pathPrefix}durationMs must be number >= 0`); if(!isEnumValue(input.status,OPS_JOB_RUN_STATUSES)) e.push(`${pathPrefix}status is invalid`); if(!isStringArray(input.warnings)) e.push(`${pathPrefix}warnings must be string[]`); if(!(input.failureReason===null||isNonEmptyString(input.failureReason))) e.push(`${pathPrefix}failureReason must be non-empty string or null`); if(!isStringArray(input.childReportIds)) e.push(`${pathPrefix}childReportIds must be string[]`); if(!isNonEmptyString(input.metricsJson)) e.push(`${pathPrefix}metricsJson must be string`); if(!isIsoDateString(input.createdAt)) e.push(`${pathPrefix}createdAt must be ISO date string`);
return e.length?{ok:false,errors:e}:{ok:true,value:input as OpsJobRunReport};}
export function validateOpsJobHealthSummary(input:unknown,pathPrefix=''):SchemaValidationResult<OpsJobHealthSummary>{const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${pathPrefix}OpsJobHealthSummary must be object`]}; if(!isIsoDateString(input.generatedAt)) e.push(`${pathPrefix}generatedAt must be ISO date string`); for(const k of ['totalRecentRuns','failedRecentRuns','partialRecentRuns','blockedRecentRuns','staleLeaseCount'] as const){ if(!Number.isInteger(input[k])||Number(input[k])<0) e.push(`${pathPrefix}${k} must be integer >= 0`);} if(!(input.mostRecentFailureJobKind===null||isEnumValue(input.mostRecentFailureJobKind,OPS_JOB_KINDS))) e.push(`${pathPrefix}mostRecentFailureJobKind is invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:input as OpsJobHealthSummary};}
