import type { BillingExternalCustomerRecord, BillingExternalEventIngestResult, BillingExternalEventRecord, BillingExternalSubscriptionRecord, BillingProviderPlanMapping, StripeLikeWebhookEnvelope } from '@elceo/types';
import { isIsoDateString, isObjectRecord, isNonEmptyString, type SchemaValidationResult } from './validation-utils';

const providers = ['stripe','manual_test','internal_import'] as const;
const kinds = ['customer_created','customer_updated','subscription_created','subscription_updated','subscription_deleted','invoice_paid','invoice_payment_failed','checkout_completed','manual_event_ingested','unknown'] as const;
const planKinds = ['free','premium','admin_internal'] as const;
const intervals = ['monthly','quarterly','yearly','custom'] as const;
const has = (arr: readonly string[], v: unknown) => typeof v === 'string' && arr.includes(v);
const os = (v: unknown) => v === null || typeof v === 'string';

function obj(input: unknown){return isObjectRecord(input)?input:null;}
export function validateStripeLikeWebhookEnvelope(input:unknown):SchemaValidationResult<StripeLikeWebhookEnvelope>{const x=obj(input); if(!x) return {ok:false,errors:['envelope must be object']}; const e:string[]=[]; if(!has(providers,x.providerKind)) e.push('providerKind invalid'); if(!isNonEmptyString(x.externalEventId)) e.push('externalEventId invalid'); if(!isNonEmptyString(x.eventType)) e.push('eventType invalid'); if(!isIsoDateString(x.createdAt)) e.push('createdAt invalid'); if(typeof x.dataJson!=='string') e.push('dataJson invalid'); return e.length?{ok:false,errors:e}:{ok:true,value:x as StripeLikeWebhookEnvelope};}
export function validateBillingExternalEventRecord(input:unknown):SchemaValidationResult<BillingExternalEventRecord>{const x=obj(input); if(!x) return {ok:false,errors:['event must be object']}; const e:string[]=[]; if(!isNonEmptyString(x.externalEventId)) e.push('externalEventId invalid'); if(!has(providers,x.providerKind)) e.push('providerKind invalid'); if(!has(kinds,x.kind)) e.push('kind invalid'); if(!os(x.externalCustomerId)) e.push('externalCustomerId invalid'); if(!os(x.externalSubscriptionId)) e.push('externalSubscriptionId invalid'); if(!(x.subjectKind===null||x.subjectKind==='user')) e.push('subjectKind invalid'); if(!os(x.subjectId)) e.push('subjectId invalid'); if(!isIsoDateString(x.occurredAt)) e.push('occurredAt invalid'); if(typeof x.payloadJson!=='string') e.push('payloadJson invalid'); if(typeof x.processed!=='boolean') e.push('processed invalid'); if(!os(x.processingResultCode)) e.push('processingResultCode invalid'); if(!isIsoDateString(x.createdAt)||!isIsoDateString(x.updatedAt)) e.push('timestamps invalid'); return e.length?{ok:false,errors:e}:{ok:true,value:x as BillingExternalEventRecord};}
export function validateBillingExternalCustomerRecord(input:unknown):SchemaValidationResult<BillingExternalCustomerRecord>{const x=obj(input); if(!x) return {ok:false,errors:['customer must be object']}; const e:string[]=[]; if(!isNonEmptyString(x.externalCustomerId)) e.push('externalCustomerId invalid'); if(!has(providers,x.providerKind)) e.push('providerKind invalid'); if(x.subjectKind!=='user') e.push('subjectKind invalid'); if(!isNonEmptyString(x.subjectId)) e.push('subjectId invalid'); if(!os(x.email)) e.push('email invalid'); if(typeof x.metadataJson!=='string') e.push('metadataJson invalid'); if(!isIsoDateString(x.createdAt)||!isIsoDateString(x.updatedAt)) e.push('timestamps invalid'); return e.length?{ok:false,errors:e}:{ok:true,value:x as BillingExternalCustomerRecord};}
export function validateBillingExternalSubscriptionRecord(input:unknown):SchemaValidationResult<BillingExternalSubscriptionRecord>{const x=obj(input); if(!x) return {ok:false,errors:['subscription must be object']}; const e:string[]=[]; if(!isNonEmptyString(x.externalSubscriptionId)||!isNonEmptyString(x.externalCustomerId)) e.push('external ids invalid'); if(!has(providers,x.providerKind)) e.push('providerKind invalid'); if(x.subjectKind!=='user'||!isNonEmptyString(x.subjectId)) e.push('subject invalid'); if(!os(x.externalPriceId)||!os(x.externalProductId)) e.push('external price/product invalid'); if(!(x.mappedPlanKind===null||has(planKinds,x.mappedPlanKind))) e.push('mappedPlanKind invalid'); if(!isNonEmptyString(x.providerStatus)) e.push('providerStatus invalid'); if(typeof x.cancelAtPeriodEnd!=='boolean') e.push('cancelAtPeriodEnd invalid');
for (const k of ['currentPeriodStart','currentPeriodEnd','trialStartsAt','trialEndsAt']){const v=(x as Record<string,unknown>)[k]; if(!(v===null||isIsoDateString(v))) e.push(`${k} invalid`);} if(typeof x.metadataJson!=='string') e.push('metadataJson invalid'); if(!isIsoDateString(x.createdAt)||!isIsoDateString(x.updatedAt)) e.push('timestamps invalid'); return e.length?{ok:false,errors:e}:{ok:true,value:x as BillingExternalSubscriptionRecord};}
export function validateBillingExternalEventIngestResult(input:unknown):SchemaValidationResult<BillingExternalEventIngestResult>{const x=obj(input); if(!x) return {ok:false,errors:['result must be object']}; const e:string[]=[]; for(const k of ['accepted','deduplicated','translated']){ if(typeof (x as Record<string,unknown>)[k]!=='boolean') e.push(`${k} invalid`);} if(!isNonEmptyString(x.externalEventId)||!has(providers,x.providerKind)||!isNonEmptyString(x.processingResultCode)) e.push('identity invalid'); if(!os(x.linkedBillingSubscriptionId)||!os(x.linkedSubjectId)) e.push('linked invalid'); if(!isIsoDateString(x.processedAt)) e.push('processedAt invalid'); return e.length?{ok:false,errors:e}:{ok:true,value:x as BillingExternalEventIngestResult};}
export function validateBillingProviderPlanMapping(input:unknown):SchemaValidationResult<BillingProviderPlanMapping>{const x=obj(input); if(!x) return {ok:false,errors:['mapping must be object']}; const e:string[]=[]; if(!has(providers,x.providerKind)||!isNonEmptyString(x.externalPriceId)||!has(planKinds,x.mappedPlanKind)||!has(intervals,x.interval)) e.push('mapping invalid'); return e.length?{ok:false,errors:e}:{ok:true,value:x as BillingProviderPlanMapping};}
