import type { ProviderActivationApprovalGate, ProviderActivationChecklistItem, ProviderActivationCoverageReport, ProviderActivationEnvironmentRequirement, ProviderActivationProviderReadiness, ProviderActivationReadinessReport, ProviderActivationRollbackPlan, ProviderActivationSmokeTestPlan } from '@elceo/types';
import { ProviderActivationReadinessApprovalStatusValues, ProviderActivationReadinessCheckStatusValues, ProviderActivationReadinessModeValues, ProviderActivationReadinessProviderFamilyValues, ProviderActivationReadinessRiskLevelValues, ProviderActivationReadinessRollbackStatusValues, ProviderActivationReadinessSmokeTestStatusValues, ProviderActivationReadinessStageValues } from '@elceo/types';
import { isEnumValue, isIsoDateString, isNonEmptyString, isObjectRecord, isStringArray, type SchemaValidationResult } from './validation-utils';

const looksLikeSecret = (v: string) => /(?:sk_live|sk_test|pk_live|api[_-]?key|bearer\s+|-----BEGIN|x-api-key|token\s+)/i.test(v);
const bannedLanguage = (v: string) => /\b(buy|sell|hold|profit|guaranteed return|double your money)\b/i.test(v);
const sorted = (arr: string[]) => arr.every((x, i) => i === 0 || (arr[i - 1]?.localeCompare(x) ?? 0) <= 0);

export const validateProviderActivationChecklistItem = (input: unknown): SchemaValidationResult<ProviderActivationChecklistItem> => { const e: string[] = []; if (!isObjectRecord(input)) return { ok: false, errors: ['input must be object'] }; if (!isNonEmptyString(input.id) || !isNonEmptyString(input.providerId)) e.push('id/providerId required'); if (!isEnumValue(input.family, ProviderActivationReadinessProviderFamilyValues)) e.push('family invalid'); if (!isEnumValue(input.stage, ProviderActivationReadinessStageValues) || !isEnumValue(input.mode, ProviderActivationReadinessModeValues) || !isEnumValue(input.status, ProviderActivationReadinessCheckStatusValues)) e.push('stage/mode/status invalid'); if (!isNonEmptyString(input.description) || bannedLanguage(String(input.description))) e.push('description invalid'); if (typeof input.required !== 'boolean') e.push('required must be boolean'); if (!isNonEmptyString(input.ownerRole) || !isNonEmptyString(input.evidenceNote) || looksLikeSecret(String(input.evidenceNote))) e.push('ownerRole/evidenceNote invalid'); return e.length ? { ok: false, errors: e } : { ok: true, value: input as ProviderActivationChecklistItem }; };
export const validateProviderActivationEnvironmentRequirement = (input: unknown): SchemaValidationResult<ProviderActivationEnvironmentRequirement> => { const e: string[] = []; if (!isObjectRecord(input)) return { ok: false, errors: ['input must be object'] }; if (!isNonEmptyString(input.providerId) || !isNonEmptyString(input.envVar)) e.push('providerId/envVar required'); if (!isNonEmptyString(input.placeholderExample) || looksLikeSecret(String(input.placeholderExample))) e.push('placeholder invalid'); if (!Array.isArray(input.requiredForModes) || input.requiredForModes.some((x: unknown) => !isEnumValue(x, ProviderActivationReadinessModeValues))) e.push('requiredForModes invalid'); if (!isStringArray(input.notes) || input.notes.some((x) => looksLikeSecret(x) || bannedLanguage(x)) || !sorted([...input.notes])) e.push('notes invalid'); return e.length ? { ok: false, errors: e } : { ok: true, value: input as ProviderActivationEnvironmentRequirement }; };
export const validateProviderActivationSmokeTestPlan = (input: unknown): SchemaValidationResult<ProviderActivationSmokeTestPlan> => { const e: string[] = []; if (!isObjectRecord(input)) return { ok: false, errors: ['input must be object'] }; if (!isNonEmptyString(input.providerId) || !isEnumValue(input.status, ProviderActivationReadinessSmokeTestStatusValues)) e.push('providerId/status invalid'); if (!isStringArray(input.scenarios) || !isStringArray(input.safetyRules)) e.push('scenarios/safetyRules invalid'); if ((input.scenarios as string[]).some((x) => bannedLanguage(x) || looksLikeSecret(x)) || !sorted([...(input.scenarios as string[])])) e.push('scenarios invalid'); return e.length ? { ok: false, errors: e } : { ok: true, value: input as ProviderActivationSmokeTestPlan }; };
export const validateProviderActivationRollbackPlan = (input: unknown): SchemaValidationResult<ProviderActivationRollbackPlan> => { const e: string[] = []; if (!isObjectRecord(input)) return { ok: false, errors: ['input must be object'] }; if (!isNonEmptyString(input.providerId) || !isEnumValue(input.status, ProviderActivationReadinessRollbackStatusValues)) e.push('providerId/status invalid'); if (!isStringArray(input.steps) || !isStringArray(input.escalation) || !sorted([...(input.steps as string[])])) e.push('steps/escalation invalid'); return e.length ? { ok: false, errors: e } : { ok: true, value: input as ProviderActivationRollbackPlan }; };
export const validateProviderActivationApprovalGate = (input: unknown): SchemaValidationResult<ProviderActivationApprovalGate> => { const e: string[] = []; if (!isObjectRecord(input)) return { ok: false, errors: ['input must be object'] }; if (!isNonEmptyString(input.providerId) || !isEnumValue(input.status, ProviderActivationReadinessApprovalStatusValues)) e.push('providerId/status invalid'); if (!isStringArray(input.requiredApprovers) || !isStringArray(input.controls)) e.push('approvers/controls invalid'); return e.length ? { ok: false, errors: e } : { ok: true, value: input as ProviderActivationApprovalGate }; };
export const validateProviderActivationProviderReadiness = (input: unknown): SchemaValidationResult<ProviderActivationProviderReadiness> => { const e: string[] = []; if (!isObjectRecord(input)) return { ok: false, errors: ['input must be object'] }; if (!isNonEmptyString(input.providerId) || !isEnumValue(input.family, ProviderActivationReadinessProviderFamilyValues) || !isEnumValue(input.stage, ProviderActivationReadinessStageValues) || !isEnumValue(input.mode, ProviderActivationReadinessModeValues) || !isEnumValue(input.riskLevel, ProviderActivationReadinessRiskLevelValues)) e.push('base fields invalid'); if (typeof input.liveBlockedByDefault !== 'boolean') e.push('liveBlockedByDefault invalid'); if (!Array.isArray(input.checklist) || input.checklist.some((x: unknown) => !validateProviderActivationChecklistItem(x).ok)) e.push('checklist invalid'); return e.length ? { ok: false, errors: e } : { ok: true, value: input as ProviderActivationProviderReadiness }; };
export const validateProviderActivationReadinessReport = (input: unknown): SchemaValidationResult<ProviderActivationReadinessReport> => { const e: string[] = []; if (!isObjectRecord(input)) return { ok: false, errors: ['input must be object'] }; if (!isIsoDateString(input.generatedAt) || !isEnumValue(input.mode, ProviderActivationReadinessModeValues) || typeof input.liveActivationAllowed !== 'boolean') e.push('header invalid'); if (!Array.isArray(input.providers) || input.providers.some((x: unknown) => !validateProviderActivationProviderReadiness(x).ok)) e.push('providers invalid'); if (!isStringArray(input.warnings)) e.push('warnings invalid'); return e.length ? { ok: false, errors: e } : { ok: true, value: input as ProviderActivationReadinessReport }; };
export const validateProviderActivationCoverageReport = (input: unknown): SchemaValidationResult<ProviderActivationCoverageReport> => { const e: string[] = []; if (!isObjectRecord(input)) return { ok: false, errors: ['input must be object'] }; if (!isIsoDateString(input.generatedAt)) e.push('generatedAt invalid'); return e.length ? { ok: false, errors: e } : { ok: true, value: input as ProviderActivationCoverageReport }; };
