import type { ProviderAssetCoverageDescriptor, ProviderCapabilityDescriptor, ProviderSourceActivationChecklistItem, ProviderSourceDescriptor, ProviderSourceGap, ProviderSourceRegistrySnapshot } from '@elceo/types';
import { PROVIDER_ACTIVATION_STAGES, PROVIDER_SOURCE_CAPABILITY_KINDS, PROVIDER_CREDENTIAL_REQUIREMENTS, PROVIDER_FIXTURE_READINESS, PROVIDER_LIVE_ACTIVATION_MODES, PROVIDER_SOURCE_FAMILIES, PROVIDER_SOURCE_IDS, PROVIDER_SOURCE_STATUSES } from '@elceo/types';
import { isEnumValue, isIsoDateString, isNonEmptyString, isObjectRecord, isStringArray, type SchemaValidationResult } from './validation-utils';

const LAUNCH_ASSETS = ['xau_usd','eur_usd','gbp_usd','usd_jpy','btc_usd','nasdaq_100','sp500','de30','dxy','vix'] as const;
const SECRET_LIKE = /(api[_-]?key|client[_-]?secret|access[_-]?token|password)/i;
const deterministic=(a:string[])=>a.every((v,i)=>{ if(i===0) return true; const prev=a[i-1]; return typeof prev==='string' && prev<=v; });

export function validateProviderCapabilityDescriptor(input: unknown,p=''): SchemaValidationResult<ProviderCapabilityDescriptor> { const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${p}ProviderCapabilityDescriptor must be object`]};
if(!isEnumValue(input.capabilityKind,PROVIDER_SOURCE_CAPABILITY_KINDS)) e.push(`${p}capabilityKind invalid`); if(!isNonEmptyString(input.evidenceTypeId)) e.push(`${p}evidenceTypeId invalid`); if(!isEnumValue(input.activationStage,PROVIDER_ACTIVATION_STAGES)) e.push(`${p}activationStage invalid`); if(!isEnumValue(input.fixtureReadiness,PROVIDER_FIXTURE_READINESS)) e.push(`${p}fixtureReadiness invalid`); if(typeof input.dryRunSupported!=='boolean') e.push(`${p}dryRunSupported invalid`); if(!isEnumValue(input.liveActivationMode,PROVIDER_LIVE_ACTIVATION_MODES)) e.push(`${p}liveActivationMode invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:input as ProviderCapabilityDescriptor}; }

export function validateProviderAssetCoverageDescriptor(input: unknown,p=''): SchemaValidationResult<ProviderAssetCoverageDescriptor> { const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${p}ProviderAssetCoverageDescriptor must be object`]};
if(!isEnumValue(input.asset,LAUNCH_ASSETS)) e.push(`${p}asset invalid`); if(!Array.isArray(input.sourceIds)||!input.sourceIds.every((x)=>isEnumValue(x,PROVIDER_SOURCE_IDS))) e.push(`${p}sourceIds invalid`); else if(!deterministic(input.sourceIds as string[])) e.push(`${p}sourceIds must be sorted`); if(!isStringArray(input.themes)||input.themes.length===0) e.push(`${p}themes invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:input as ProviderAssetCoverageDescriptor}; }

export function validateProviderSourceDescriptor(input: unknown,p=''): SchemaValidationResult<ProviderSourceDescriptor> { const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${p}ProviderSourceDescriptor must be object`]};
for(const k of Object.keys(input)){ if(SECRET_LIKE.test(k)) e.push(`${p}${k} is forbidden`); }
if(!isEnumValue(input.sourceId,PROVIDER_SOURCE_IDS)) e.push(`${p}sourceId invalid`); if(!isEnumValue(input.family,PROVIDER_SOURCE_FAMILIES)) e.push(`${p}family invalid`); if(!isNonEmptyString(input.displayName)) e.push(`${p}displayName invalid`); if(!isEnumValue(input.status,PROVIDER_SOURCE_STATUSES)) e.push(`${p}status invalid`); if(!isEnumValue(input.activationStage,PROVIDER_ACTIVATION_STAGES)) e.push(`${p}activationStage invalid`); if(!isEnumValue(input.fixtureReadiness,PROVIDER_FIXTURE_READINESS)) e.push(`${p}fixtureReadiness invalid`); if(!isEnumValue(input.liveActivationMode,PROVIDER_LIVE_ACTIVATION_MODES)) e.push(`${p}liveActivationMode invalid`); if(!isEnumValue(input.credentialRequirement,PROVIDER_CREDENTIAL_REQUIREMENTS)) e.push(`${p}credentialRequirement invalid`); if(!Array.isArray(input.capabilities)||input.capabilities.length===0) e.push(`${p}capabilities invalid`); else input.capabilities.forEach((x,i)=>{const r=validateProviderCapabilityDescriptor(x,`${p}capabilities[${i}].`); if(r.ok===false) e.push(...r.errors);}); if(!Array.isArray(input.assets)||!input.assets.every((x)=>isEnumValue(x,LAUNCH_ASSETS))) e.push(`${p}assets invalid`); else if(!deterministic(input.assets as string[])) e.push(`${p}assets must be sorted`); if(!isNonEmptyString(input.notes)) e.push(`${p}notes invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:input as ProviderSourceDescriptor}; }

export function validateProviderSourceGap(input: unknown,p=''): SchemaValidationResult<ProviderSourceGap>{ const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${p}ProviderSourceGap must be object`]}; if(!isNonEmptyString(input.gapId)) e.push(`${p}gapId invalid`); if(!isEnumValue(input.sourceId,PROVIDER_SOURCE_IDS)) e.push(`${p}sourceId invalid`); if(!(input.asset==='all'||isEnumValue(input.asset,LAUNCH_ASSETS))) e.push(`${p}asset invalid`); if(!isEnumValue(input.severity,['low','medium','high'] as const)) e.push(`${p}severity invalid`); if(!isNonEmptyString(input.reason)) e.push(`${p}reason invalid`); if(!isEnumValue(input.blockedBy,['fixture_missing','dry_run_missing','live_blocked_by_policy','integration_not_started'] as const)) e.push(`${p}blockedBy invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:input as ProviderSourceGap}; }

export function validateProviderSourceActivationChecklistItem(input: unknown,p=''): SchemaValidationResult<ProviderSourceActivationChecklistItem>{ const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${p}ProviderSourceActivationChecklistItem must be object`]}; if(!isNonEmptyString(input.checklistItemId)) e.push(`${p}checklistItemId invalid`); if(!isEnumValue(input.sourceId,PROVIDER_SOURCE_IDS)) e.push(`${p}sourceId invalid`); if(!(typeof input.order==='number' && Number.isInteger(input.order) && input.order>=1)) e.push(`${p}order invalid`); if(!isNonEmptyString(input.description)) e.push(`${p}description invalid`); if(typeof input.required!=='boolean'||typeof input.done!=='boolean'||typeof input.blocked!=='boolean') e.push(`${p}state invalid`); return e.length?{ok:false,errors:e}:{ok:true,value:input as ProviderSourceActivationChecklistItem}; }

export function validateProviderSourceRegistrySnapshot(input: unknown,p=''): SchemaValidationResult<ProviderSourceRegistrySnapshot>{ const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${p}ProviderSourceRegistrySnapshot must be object`]}; if(!isIsoDateString(input.generatedAt)) e.push(`${p}generatedAt invalid`); if(!Array.isArray(input.sources)||input.sources.length===0) e.push(`${p}sources invalid`); else input.sources.forEach((x,i)=>{const r=validateProviderSourceDescriptor(x,`${p}sources[${i}].`); if(r.ok===false) e.push(...r.errors);}); if(!Array.isArray(input.launchAssetCoverage)||input.launchAssetCoverage.length!==LAUNCH_ASSETS.length) e.push(`${p}launchAssetCoverage invalid`); else input.launchAssetCoverage.forEach((x,i)=>{const r=validateProviderAssetCoverageDescriptor(x,`${p}launchAssetCoverage[${i}].`); if(r.ok===false) e.push(...r.errors);}); if(!Array.isArray(input.gaps)) e.push(`${p}gaps invalid`); else input.gaps.forEach((x,i)=>{const r=validateProviderSourceGap(x,`${p}gaps[${i}].`); if(r.ok===false) e.push(...r.errors);}); if(!isObjectRecord(input.activationChecklistBySource)) e.push(`${p}activationChecklistBySource invalid`); else for(const id of PROVIDER_SOURCE_IDS){ const items=(input.activationChecklistBySource as Record<string,unknown>)[id]; if(!Array.isArray(items)) {e.push(`${p}activationChecklistBySource.${id} missing`); continue;} items.forEach((x,i)=>{const r=validateProviderSourceActivationChecklistItem(x,`${p}activationChecklistBySource.${id}[${i}].`); if(r.ok===false) e.push(...r.errors);}); }
return e.length?{ok:false,errors:e}:{ok:true,value:input as ProviderSourceRegistrySnapshot}; }
