import type { ReasoningEvidenceFilterPolicy, ReasoningEvidenceInputAssemblyReport, ReasoningEvidenceInputExclusion, ReasoningEvidenceInputItem, ReasoningEvidenceInputSnapshot } from '@elceo/types';
import { EVIDENCE_CONFLICT_STATUSES, EVIDENCE_FRESHNESS_STATUSES, EVIDENCE_USABILITY_STATUSES, MARKET_EVIDENCE_CLASSES, MARKET_EVIDENCE_DATA_QUALITIES } from '@elceo/types';
import { validateEvidenceQualityScore } from './market-evidence-quality.schema';
import { isEnumValue, isIsoDateString, isNonEmptyString, isObjectRecord, isScore0to100, isStringArray, type SchemaValidationResult } from './validation-utils';

const ns=(v:unknown)=>v===null||typeof v==='string';
export function validateReasoningEvidenceFilterPolicy(input:unknown,p=''):SchemaValidationResult<ReasoningEvidenceFilterPolicy>{const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${p}ReasoningEvidenceFilterPolicy must be object`]}; if(!isScore0to100(input.minFinalQualityScore)) e.push(`${p}minFinalQualityScore must be 0..100`); for(const k of ['includeFixtureEvidence','includeExpiredEvidence','includeBlockedEvidence'] as const){if(typeof input[k]!=='boolean') e.push(`${p}${k} must be boolean`);} if(!Number.isInteger(input.maxEvidenceItems)||Number(input.maxEvidenceItems)<=0) e.push(`${p}maxEvidenceItems must be positive integer`); if(!isNonEmptyString(input.rationale)) e.push(`${p}rationale must be non-empty string`); return e.length?{ok:false,errors:e}:{ok:true,value:input as ReasoningEvidenceFilterPolicy};}
export function validateReasoningEvidenceInputItem(input:unknown,p=''):SchemaValidationResult<ReasoningEvidenceInputItem>{const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${p}ReasoningEvidenceInputItem must be object`]}; for(const k of ['payloadId','evidenceTypeId','providerId','region','observedAt','normalizedAt','valuesJson','metadataJson'] as const){if(!isNonEmptyString(input[k])) e.push(`${p}${k} must be non-empty string`);} if(!isEnumValue(input.evidenceClass,MARKET_EVIDENCE_CLASSES)) e.push(`${p}evidenceClass is invalid`); if(!ns(input.asset)) e.push(`${p}asset must be string|null`); if(!isIsoDateString(input.observedAt)||!isIsoDateString(input.normalizedAt)) e.push(`${p}observedAt/normalizedAt invalid`); if(!isEnumValue(input.usabilityStatus,EVIDENCE_USABILITY_STATUSES)) e.push(`${p}usabilityStatus is invalid`); if(!isEnumValue(input.freshnessStatus,EVIDENCE_FRESHNESS_STATUSES)) e.push(`${p}freshnessStatus is invalid`); if(!isEnumValue(input.conflictStatus,EVIDENCE_CONFLICT_STATUSES)) e.push(`${p}conflictStatus is invalid`); if(!isEnumValue(input.dataQuality,MARKET_EVIDENCE_DATA_QUALITIES)) e.push(`${p}dataQuality is invalid`); if(!isStringArray(input.reasons)) e.push(`${p}reasons must be string[]`); const qr=validateEvidenceQualityScore(input.qualityScore,`${p}qualityScore.`); if(qr.ok===false) e.push(...qr.errors); return e.length?{ok:false,errors:e}:{ok:true,value:input as ReasoningEvidenceInputItem};}
export function validateReasoningEvidenceInputExclusion(input:unknown,p=''):SchemaValidationResult<ReasoningEvidenceInputExclusion>{const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${p}ReasoningEvidenceInputExclusion must be object`]}; for(const k of ['payloadId','reasonCode','reason'] as const){if(!isNonEmptyString(input[k])) e.push(`${p}${k} must be non-empty string`);} return e.length?{ok:false,errors:e}:{ok:true,value:input as ReasoningEvidenceInputExclusion};}
export function validateReasoningEvidenceInputSnapshot(input:unknown,p=''):SchemaValidationResult<ReasoningEvidenceInputSnapshot>{const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${p}ReasoningEvidenceInputSnapshot must be object`]}; for(const k of ['snapshotId','generatedAt'] as const){if(!isNonEmptyString(input[k])) e.push(`${p}${k} must be non-empty string`);} if(!isIsoDateString(input.generatedAt)) e.push(`${p}generatedAt invalid`); if(!ns(input.asset)) e.push(`${p}asset must be string|null`); if(!(input.evidenceClass===null||isEnumValue(input.evidenceClass,MARKET_EVIDENCE_CLASSES))) e.push(`${p}evidenceClass is invalid`); const fp=validateReasoningEvidenceFilterPolicy(input.filterPolicy,`${p}filterPolicy.`); if(fp.ok===false) e.push(...fp.errors); if(!Array.isArray(input.items)) e.push(`${p}items must be array`); else input.items.forEach((x,i)=>{const r=validateReasoningEvidenceInputItem(x,`${p}items[${i}].`); if(r.ok===false)e.push(...r.errors);}); if(!Array.isArray(input.excludedItems)) e.push(`${p}excludedItems must be array`); else input.excludedItems.forEach((x,i)=>{const r=validateReasoningEvidenceInputExclusion(x,`${p}excludedItems[${i}].`); if(r.ok===false)e.push(...r.errors);}); if(!isStringArray(input.warnings)) e.push(`${p}warnings must be string[]`); return e.length?{ok:false,errors:e}:{ok:true,value:input as ReasoningEvidenceInputSnapshot};}
export function validateReasoningEvidenceInputAssemblyReport(input:unknown,p=''):SchemaValidationResult<ReasoningEvidenceInputAssemblyReport>{const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${p}ReasoningEvidenceInputAssemblyReport must be object`]}; if(!isIsoDateString(input.generatedAt)) e.push(`${p}generatedAt invalid`); if(!ns(input.asset)) e.push(`${p}asset must be string|null`); if(!(input.evidenceClass===null||isEnumValue(input.evidenceClass,MARKET_EVIDENCE_CLASSES))) e.push(`${p}evidenceClass is invalid`); for(const k of ['inputItemCount','excludedItemCount'] as const){if(!Number.isInteger(input[k])||Number(input[k])<0)e.push(`${p}${k} must be integer >= 0`);} if(!isStringArray(input.warnings)) e.push(`${p}warnings must be string[]`); if(typeof input.pass!=='boolean') e.push(`${p}pass must be boolean`); return e.length?{ok:false,errors:e}:{ok:true,value:input as ReasoningEvidenceInputAssemblyReport};}
