import type { SeoContentArchitectureSnapshot, SeoInternalLinkRule, SeoKeywordDefinition, SeoPageDefinition } from '@elceo/types';
import { MARKET_EVIDENCE_CLASSES, SEO_CONTENT_CLUSTERS, SEO_CONTENT_FRESHNESS_CLASSES, SEO_KEYWORD_INTENTS, SEO_PAGE_KINDS, TRADING_ASSET_COVERAGE } from '@elceo/types';
import { isEnumValue, isIsoDateString, isNonEmptyString, isObjectRecord, isStringArray, type SchemaValidationResult } from './validation-utils';

const DIFFICULTY=['low','medium','high'] as const; const STRUCT=['article','faq','howto','dataset','webpage'] as const;
export function validateSeoKeywordDefinition(input: unknown, p=''): SchemaValidationResult<SeoKeywordDefinition> { const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${p}SeoKeywordDefinition must be object`]};
if(!isNonEmptyString(input.keywordId)) e.push(`${p}keywordId must be non-empty string`); if(!isNonEmptyString(input.phrase)) e.push(`${p}phrase must be non-empty string`); if(!isEnumValue(input.intent,SEO_KEYWORD_INTENTS)) e.push(`${p}intent is invalid`); if(!isEnumValue(input.cluster,SEO_CONTENT_CLUSTERS)) e.push(`${p}cluster is invalid`); if(!(typeof input.priority === "number" && Number.isInteger(input.priority) && input.priority > 0)) e.push(`${p}priority must be integer > 0`); if(!isEnumValue(input.difficultyTier,DIFFICULTY)) e.push(`${p}difficultyTier is invalid`); if(!isEnumValue(input.mappedPageKind,SEO_PAGE_KINDS)) e.push(`${p}mappedPageKind is invalid`); if(!Array.isArray(input.relatedAssets)||!input.relatedAssets.every((x)=>isEnumValue(x,TRADING_ASSET_COVERAGE))) e.push(`${p}relatedAssets invalid`); if(!Array.isArray(input.relatedEvidenceClasses)||!input.relatedEvidenceClasses.every((x)=>isEnumValue(x,MARKET_EVIDENCE_CLASSES))) e.push(`${p}relatedEvidenceClasses invalid`);
return e.length?{ok:false,errors:e}:{ok:true,value:input as SeoKeywordDefinition}; }
export function validateSeoPageDefinition(input: unknown, p=''): SchemaValidationResult<SeoPageDefinition> { const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${p}SeoPageDefinition must be object`]};
['pageId','slug','titleTemplate','metaDescriptionTemplate','h1Template','canonicalPath'].forEach((f)=>{ if(!isNonEmptyString(input[f])) e.push(`${p}${f} must be non-empty string`);}); if(!isEnumValue(input.pageKind,SEO_PAGE_KINDS)) e.push(`${p}pageKind is invalid`); if(!isEnumValue(input.freshnessClass,SEO_CONTENT_FRESHNESS_CLASSES)) e.push(`${p}freshnessClass is invalid`); if(!isStringArray(input.targetKeywords)) e.push(`${p}targetKeywords must be string[]`); if(!isStringArray(input.relatedEvidenceTypes)) e.push(`${p}relatedEvidenceTypes must be string[]`); if(!Array.isArray(input.relatedAssets)||!input.relatedAssets.every((x)=>isEnumValue(x,TRADING_ASSET_COVERAGE))) e.push(`${p}relatedAssets invalid`); if(!isStringArray(input.internalLinkTargets)) e.push(`${p}internalLinkTargets must be string[]`); if(!isEnumValue(input.structuredDataKind,STRUCT)) e.push(`${p}structuredDataKind is invalid`); if(typeof input.isLaunchScope!=='boolean') e.push(`${p}isLaunchScope must be boolean`);
return e.length?{ok:false,errors:e}:{ok:true,value:input as SeoPageDefinition}; }
export function validateSeoInternalLinkRule(input: unknown, p=''): SchemaValidationResult<SeoInternalLinkRule> { const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${p}SeoInternalLinkRule must be object`]}; if(!isNonEmptyString(input.ruleId)) e.push(`${p}ruleId must be non-empty string`); if(!isEnumValue(input.sourcePageKind,SEO_PAGE_KINDS)) e.push(`${p}sourcePageKind invalid`); if(!isEnumValue(input.targetPageKind,SEO_PAGE_KINDS)) e.push(`${p}targetPageKind invalid`); if(!isNonEmptyString(input.anchorTemplate)) e.push(`${p}anchorTemplate must be non-empty string`); if(!isNonEmptyString(input.rationale)) e.push(`${p}rationale must be non-empty string`); return e.length?{ok:false,errors:e}:{ok:true,value:input as SeoInternalLinkRule}; }
export function validateSeoContentArchitectureSnapshot(input: unknown, p=''): SchemaValidationResult<SeoContentArchitectureSnapshot> { const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${p}SeoContentArchitectureSnapshot must be object`]}; if(!isIsoDateString(input.generatedAt)) e.push(`${p}generatedAt must be ISO date string`);
if(!Array.isArray(input.keywords)) e.push(`${p}keywords must be array`); else input.keywords.forEach((x,i)=>{const r=validateSeoKeywordDefinition(x,`${p}keywords[${i}].`); if(r.ok===false) e.push(...r.errors);});
if(!Array.isArray(input.pages)) e.push(`${p}pages must be array`); else input.pages.forEach((x,i)=>{const r=validateSeoPageDefinition(x,`${p}pages[${i}].`); if(r.ok===false) e.push(...r.errors);});
if(!Array.isArray(input.internalLinkRules)) e.push(`${p}internalLinkRules must be array`); else input.internalLinkRules.forEach((x,i)=>{const r=validateSeoInternalLinkRule(x,`${p}internalLinkRules[${i}].`); if(r.ok===false) e.push(...r.errors);});
return e.length?{ok:false,errors:e}:{ok:true,value:input as SeoContentArchitectureSnapshot}; }
