import type { SeoProgrammaticAssetIndexFeed, SeoProgrammaticCanonicalFeed, SeoProgrammaticCoverageReport, SeoProgrammaticRobotsPolicy, SeoProgrammaticSafetyReport, SeoProgrammaticSitemapFeed, SeoProgrammaticStructuredDataPayload, SeoProgrammaticSupportedAssetPage } from '@elceo/types';
import { SEO_PROGRAMMATIC_CONTENT_KINDS, SEO_PROGRAMMATIC_INDEXING_POLICIES, SEO_PROGRAMMATIC_CANONICAL_STATUSES, SEO_PROGRAMMATIC_STRUCTURED_DATA_KINDS } from '@elceo/types';
import { isEnumValue, isIsoDateString, isNonEmptyString, isObjectRecord, isStringArray, type SchemaValidationResult } from './validation-utils';
const bad=/(\bbuy\b|\bsell\b|\bhold\b|guaranteed profit|financial advice|will rise|will fall)/i;
const secret=/(api[_-]?key|secret|token|password|rawProviderPayload|admin_internal|cognitionSnapshot)/i;
const validPath=(x:unknown)=>typeof x==='string'&&x.startsWith('/');
export function validateSeoProgrammaticSupportedAssetPage(input:unknown,p=''):SchemaValidationResult<SeoProgrammaticSupportedAssetPage>{const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${p}object required`]}; ['displaySymbol','assetName','slug','title','metaDescription','publicSummary','premiumContentBoundaryNote'].forEach((k)=>{if(!isNonEmptyString(input[k]))e.push(`${p}${k} required`); if(typeof input[k]==='string'&&bad.test(input[k])) e.push(`${p}${k} contains forbidden advice wording`);}); if(!validPath(input.canonicalPath)) e.push(`${p}canonicalPath invalid`); if(!isEnumValue(input.indexingPolicy,SEO_PROGRAMMATIC_INDEXING_POLICIES)) e.push(`${p}indexingPolicy invalid`); if(!isEnumValue(input.structuredDataKind,SEO_PROGRAMMATIC_STRUCTURED_DATA_KINDS)) e.push(`${p}structuredDataKind invalid`); if(!Array.isArray(input.educationalSections)||input.educationalSections.length===0)e.push(`${p}educationalSections required`); if(!isStringArray(input.relatedGlossarySlugs)) e.push(`${p}relatedGlossarySlugs invalid`); if(input.visibility!=='public') e.push(`${p}visibility must be public`); if(!isIsoDateString(input.updatedAt)) e.push(`${p}updatedAt must be ISO`); return e.length?{ok:false,errors:e}:{ok:true,value:input as SeoProgrammaticSupportedAssetPage}; }
export function validateSeoProgrammaticAssetIndexFeed(input:unknown,p=''):SchemaValidationResult<SeoProgrammaticAssetIndexFeed>{const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${p}object required`]}; if(!isIsoDateString(input.generatedAt)) e.push(`${p}generatedAt invalid`); if(input.visibility!=='public') e.push(`${p}visibility must be public`); if(!Array.isArray(input.assets)) e.push(`${p}assets invalid`); else input.assets.forEach((x,i)=>{const r=validateSeoProgrammaticSupportedAssetPage(x,`${p}assets[${i}].`); if(r.ok===false) e.push(...r.errors);}); return e.length?{ok:false,errors:e}:{ok:true,value:input as SeoProgrammaticAssetIndexFeed};}
export function validateSeoProgrammaticSitemapFeed(input:unknown,p=''):SchemaValidationResult<SeoProgrammaticSitemapFeed>{const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${p}object required`]}; if(!isIsoDateString(input.generatedAt)) e.push(`${p}generatedAt invalid`); if(input.visibility!=='public') e.push(`${p}visibility`); if(!Array.isArray(input.entries)) e.push(`${p}entries invalid`); else { let prev=''; input.entries.forEach((x,i)=>{ if(!isObjectRecord(x)){e.push(`${p}entries[${i}] invalid`); return;} if(!validPath(x.path)) e.push(`${p}entries[${i}].path invalid`); if(typeof x.path==='string'&&x.path<prev) e.push(`${p}entries must be sorted`); prev=typeof x.path==='string'?x.path:prev; if(!isEnumValue(x.indexingPolicy,SEO_PROGRAMMATIC_INDEXING_POLICIES)) e.push(`${p}entries[${i}].indexingPolicy invalid`); if(!isEnumValue(x.contentKind,SEO_PROGRAMMATIC_CONTENT_KINDS)) e.push(`${p}entries[${i}].contentKind invalid`); }); } return e.length?{ok:false,errors:e}:{ok:true,value:input as SeoProgrammaticSitemapFeed};}
export function validateSeoProgrammaticRobotsPolicy(input:unknown,p=''):SchemaValidationResult<SeoProgrammaticRobotsPolicy>{const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${p}object required`]}; ['allowedPublicPaths','disallowedPaths','noindexPatterns','protectedPaths','adminPaths','apiPaths'].forEach((k)=>{ if(!isStringArray(input[k])) e.push(`${p}${k} invalid`); }); if(input.visibility!=='public') e.push(`${p}visibility`); return e.length?{ok:false,errors:e}:{ok:true,value:input as SeoProgrammaticRobotsPolicy}; }
export function validateSeoProgrammaticCanonicalFeed(input:unknown,p=''):SchemaValidationResult<SeoProgrammaticCanonicalFeed>{const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${p}object required`]}; if(!isIsoDateString(input.generatedAt)) e.push(`${p}generatedAt`); if(input.visibility!=='public') e.push(`${p}visibility`); if(!Array.isArray(input.entries)) e.push(`${p}entries invalid`); else input.entries.forEach((x,i)=>{ if(!isObjectRecord(x)) return e.push(`${p}entries[${i}]`); if(!validPath(x.path)||!validPath(x.canonicalPath)) e.push(`${p}entries[${i}] path invalid`); if(!isEnumValue(x.canonicalStatus,SEO_PROGRAMMATIC_CANONICAL_STATUSES)) e.push(`${p}entries[${i}] canonicalStatus`); }); return e.length?{ok:false,errors:e}:{ok:true,value:input as SeoProgrammaticCanonicalFeed}; }
export function validateSeoProgrammaticStructuredDataPayload(input:unknown,p=''):SchemaValidationResult<SeoProgrammaticStructuredDataPayload>{const e:string[]=[]; if(!isObjectRecord(input)) return {ok:false,errors:[`${p}object`]}; if(!isNonEmptyString(input.id)||!validPath(input.path)) e.push(`${p}id/path invalid`); if(!isEnumValue(input.kind,SEO_PROGRAMMATIC_STRUCTURED_DATA_KINDS)) e.push(`${p}kind`); if(!isObjectRecord(input.jsonLd)) e.push(`${p}jsonLd object required`); if(input.visibility!=='public') e.push(`${p}visibility`); if(secret.test(JSON.stringify(input.jsonLd))) e.push(`${p}jsonLd contains secret-like field`); return e.length?{ok:false,errors:e}:{ok:true,value:input as SeoProgrammaticStructuredDataPayload}; }
export function validateSeoProgrammaticSafetyReport(input:unknown,p=''):SchemaValidationResult<SeoProgrammaticSafetyReport>{return isObjectRecord(input)&&Array.isArray(input.checks)&&isStringArray(input.blockedTerms)&&isIsoDateString(input.generatedAt)?{ok:true,value:input as SeoProgrammaticSafetyReport}:{ok:false,errors:[`${p}safety report invalid`]};}
export function validateSeoProgrammaticCoverageReport(input:unknown,p=''):SchemaValidationResult<SeoProgrammaticCoverageReport>{return isObjectRecord(input)&&isIsoDateString(input.generatedAt)?{ok:true,value:input as SeoProgrammaticCoverageReport}:{ok:false,errors:[`${p}coverage invalid`]};}
