import { createHash, randomUUID } from 'node:crypto';
import type { ProviderRuntimeRequest } from '../provider-api-gate';
import type { ProviderCacheEntry, ProviderCacheIdentity, ProviderCacheOwnerExecution, ProviderCachePolicy, ProviderCacheSharedOutcome, ProviderCacheStore } from './contracts';
import { materialFromResponse, validateCachedMaterial } from './material';
export class ProviderL1Cache{private map=new Map<string,{entry:ProviderCacheEntry;bytes:number}>();private bytes=0;constructor(readonly maxEntries=256,readonly maxBytes=16*1024*1024){}get(i:ProviderCacheIdentity,p:ProviderCachePolicy,now=Date.now()){const v=this.map.get(i.hash);if(!v)return undefined;if(now>v.entry.freshUntil||!validateCachedMaterial(v.entry.material,i,p)){this.delete(i.hash);return undefined;}this.map.delete(i.hash);this.map.set(i.hash,v);return v.entry;}set(i:ProviderCacheIdentity,e:ProviderCacheEntry,p:ProviderCachePolicy){const bytes=Buffer.byteLength(JSON.stringify(e));if(bytes>p.maxEntryBytes||bytes>this.maxBytes)return;this.delete(i.hash);this.map.set(i.hash,{entry:e,bytes});this.bytes+=bytes;while(this.map.size>this.maxEntries||this.bytes>this.maxBytes)this.delete(this.map.keys().next().value!);}private delete(k:string){const old=this.map.get(k);if(old)this.bytes-=old.bytes;this.map.delete(k);}get size(){return this.map.size;}get totalBytes(){return this.bytes;}}
export function buildProviderCacheIdentity(req:ProviderRuntimeRequest,p:ProviderCachePolicy,pool:string,fingerprint:string):ProviderCacheIdentity{const canonical=`provider_cache_identity_v1\0${req.sourceId}\0${req.capabilityId}\0${pool}\0${p.policyVersion}\0${fingerprint}`,hash=createHash('sha256').update(canonical).digest('hex');return {hash,fingerprint,sourceId:req.sourceId,capabilityId:req.capabilityId,credentialPoolId:pool,policyVersion:p.policyVersion};}
export class ProviderCacheCoordinator{private inflight=new Map<string,Promise<ProviderCacheSharedOutcome>>();constructor(readonly store:ProviderCacheStore,readonly l1=new ProviderL1Cache(),readonly maxInflight=1024){}get localInflightSize(){return this.inflight.size;}
 async execute(req:ProviderRuntimeRequest,identity:ProviderCacheIdentity,policy:ProviderCachePolicy,owner:ProviderCacheOwnerExecution):Promise<ProviderCacheSharedOutcome>{const hit=this.l1.get(identity,policy);if(hit)return {material:hit.material,layer:'l1',freshness:'fresh',role:'none',entry:hit};const existing=this.inflight.get(identity.hash);if(existing)return {...await existing,role:'follower'};if(this.inflight.size>=this.maxInflight)return {failureReason:'provider_cache_local_capacity_exceeded',layer:'none',freshness:'miss',role:'none'};const promise=this.distributed(req,identity,policy,owner);this.inflight.set(identity.hash,promise);try{return await promise;}finally{if(this.inflight.get(identity.hash)===promise)this.inflight.delete(identity.hash);}}
 private async distributed(req:ProviderRuntimeRequest,i:ProviderCacheIdentity,p:ProviderCachePolicy,owner:ProviderCacheOwnerExecution):Promise<ProviderCacheSharedOutcome>{let stale:ProviderCacheEntry|undefined;try{const read=await this.store.read(i,p);if(read.state==='FRESH'&&read.entry){this.l1.set(i,read.entry,p);return {material:read.entry.material,layer:'l2',freshness:'fresh',role:'none',entry:read.entry};}if(read.state==='STALE_BUT_ELIGIBLE')stale=read.entry;}catch{return {failureReason:'provider_cache_control_unavailable',layer:'none',freshness:'miss',role:'none'};}
 const token=randomUUID(),deadline=Date.now()+p.followerWaitTimeoutMs;let role:'owner'|'follower'='follower';while(Date.now()<deadline){let acquired=false;try{acquired=await this.store.tryAcquireFlight(i,token,p.flightLeaseMs);}catch{return stale?{material:stale.material,layer:'l2',freshness:'stale',role:'follower',entry:stale}:{failureReason:'provider_cache_control_unavailable',layer:'none',freshness:'miss',role:'follower'};}if(acquired){role='owner';break;}await new Promise(r=>setTimeout(r,Math.min(250,25*2**Math.min(4,Math.floor((p.followerWaitTimeoutMs-(deadline-Date.now()))/100)))+Math.floor(Math.random()*20)));const read=await this.store.read(i,p);if(read.state==='FRESH'&&read.entry){this.l1.set(i,read.entry,p);return {material:read.entry.material,layer:'l2',freshness:'fresh',role:'follower',entry:read.entry};}const state=await this.store.readFlightState(i);if(state.completion)return stale?{material:stale.material,layer:'l2',freshness:'stale',role:'follower',entry:stale}:{failureReason:state.completion.reason,layer:'none',freshness:'miss',role:'follower'};}
 if(role==='follower')return stale?{material:stale.material,layer:'l2',freshness:'stale',role,entry:stale}:{failureReason:'provider_singleflight_wait_timeout',layer:'none',freshness:'miss',role};
 const abort=new AbortController();let lost=false;const heartbeat=setInterval(()=>void this.store.renewFlight(i,token,p.flightLeaseMs).then(ok=>{if(!ok){lost=true;abort.abort(new Error('provider_singleflight_ownership_lost'));}}).catch(()=>{lost=true;abort.abort(new Error('provider_cache_control_unavailable'));}),Math.max(10,Math.floor(p.flightLeaseMs/3)));try{const executed=await owner(abort.signal),response=executed.response;if(!lost&&response?.payloadSchemaStatus==='valid'&&executed.settlementState==='settled_committed'&&response.payloadSizeBytes<=p.maxEntryBytes){const material=materialFromResponse(response,i.fingerprint,p),entry=await this.store.publishSuccessAndComplete(i,token,material,p);if(entry){this.l1.set(i,entry,p);return {material,layer:'none',freshness:'fresh',role:'owner',entry};}}const reason=lost?'provider_singleflight_ownership_lost':response?.error?.category??executed.settlementState;await this.store.publishFailureAndComplete(i,token,reason,p.completionTtlMs);return stale?{material:stale.material,layer:'l2',freshness:'stale',role:'owner',entry:stale}:{failureReason:reason,layer:'none',freshness:'miss',role:'owner'};}catch(error){const reason=error instanceof Error?error.message:'provider_error';if(!lost)await this.store.publishFailureAndComplete(i,token,reason,p.completionTtlMs).catch(()=>false);return stale?{material:stale.material,layer:'l2',freshness:'stale',role:'owner',entry:stale}:{failureReason:reason,layer:'none',freshness:'miss',role:'owner'};}finally{clearInterval(heartbeat);}}
}
