import type { EventRealityEvaluation, EventExpectationRecord } from '../expectation-reality/contracts';
import type { HistoricalAnalogRetrievalResult } from '../historical-analog-memory/contracts';
import type { MarketContradictionMatrixResult, InvalidationState } from '@elceo/types';

export type ProtocolDecisionState = 'wait_for_confirmation' | 'review_required' | 'invalidate_thesis' | 'escalate_review' | 'archive_resolved';
export type EvidenceSufficiency = 'sufficient' | 'insufficient' | 'provisional' | 'provenance_limited' | 'pending_confirmation' | 'resolved';
export type TransitionReason = 'confirmed_canonical_invalidation' | 'provisional_assessment_stage' | 'pending_price_confirmation' | 'absorbed_reaction_pending_later_window' | 'delayed_reaction_pending_later_window' | 'ambiguous_reaction_pending_later_window' | 'pending_related_market_evidence' | 'insufficient_direct_evidence' | 'provenance_limitation' | 'source_disagreement_unresolved' | 'critical_direct_contradiction' | 'compound_direct_contradiction' | 'mispriced_candidate_critical_conflict' | 'material_contradiction' | 'rejected_expectation' | 'related_market_conflict' | 'analog_context_conflict_non_terminal' | 'final_resolved_non_actionable' | 'previous_decision_superseded';
export type BlockedActionClass = 'trade_execution' | 'position_entry' | 'position_exit' | 'position_sizing' | 'leverage_selection' | 'stop_placement' | 'target_placement';
export type EvidenceReference = { sourceType: 'event_evaluation'|'event_expectation'|'analog_retrieval'|'cognition_snapshot'|'invalidation_state'|'contradiction_matrix'; sourceId: string; contentHash: string; observedAt: string; reliability: 'verified'|'replay'|'fixture'|'unverified' };
export type ContradictionEvidenceSummary = { evidenceSnapshotId: string; matrixResultHash: string; severity: string; status: string; score: number | null; families: string[]; warnings: string[]; reasonCodes: string[] };
export type InvalidationEvidenceSummary = { invalidationStateHash: string; confirmed: boolean; canonicalConditions: string[]; state: InvalidationState | null };
export type AnalogContextSummary = { absent: boolean; analogContextHash: string | null; retrievalId: string | null; queryFeatureHash: string | null; evidenceSufficiency: string | null; limitations: string[]; warnings: string[]; outcomeContextAttachedAfterSelection: boolean };
export type ProvenanceSummary = { reliability: Array<'verified'|'replay'|'fixture'|'unverified'>; verifiedSourceCount: number; replaySourceCount: number; fixtureSourceCount: number; unverifiedSourceCount: number; limitations: string[] };
export type ReviewPrompt = { state: ProtocolDecisionState; text: string };
export type SupersessionLink = { previousProtocolDecisionId: string; transitionId: string; supersedes: boolean };
export type ProtocolAuditRecord = { protocolDecisionId: string; policyVersion: 'contradiction-action-protocol-v1'; sourceEventEvaluationId: string; sourceExpectationId: string; sourceAnalogRetrievalId: string | null; sourceCognitionSnapshotIds: string[]; contradictionEvidenceHash: string; invalidationStateHash: string; analogContextHash: string | null; evidenceCutoffAt: string; evidenceSufficiency: EvidenceSufficiency; protocolState: ProtocolDecisionState; transitionReasons: TransitionReason[]; reviewPrompts: ReviewPrompt[]; blockedActionClasses: BlockedActionClass[]; warnings: string[]; limitations: string[]; deterministicRationale: string; sourceEvidenceReferences: EvidenceReference[]; contradictionEvidence: ContradictionEvidenceSummary; invalidationEvidence: InvalidationEvidenceSummary; analogContext: AnalogContextSummary; provenance: ProvenanceSummary; previousDecision: SupersessionLink | null; createdAt: string; canonicalPayloadHash: string };
export type ProtocolDecisionRequest = { eventEvaluationId: string; analogRetrievalId?: string; previousProtocolDecisionId?: string; evidenceCutoffAt: string };
export type ProtocolEvidenceBundle = { eventEvaluation: EventRealityEvaluation; expectation: EventExpectationRecord; analogRetrieval?: HistoricalAnalogRetrievalResult | null; contradictionMatrix: MarketContradictionMatrixResult; invalidationState: InvalidationState | null };
