import { canonicalHash, canonicalJson } from '../expectation-reality/identity';
import { CONTRADICTION_ACTION_PROTOCOL_POLICY_VERSION } from './policy';
import type { ProtocolAuditRecord, ProtocolEvidenceBundle, SupersessionLink } from './contracts';
export { canonicalHash, canonicalJson };
function normalizedContradiction(value: unknown): unknown { const v=value as any; return v && typeof v === 'object' ? { ...v, warnings:[...(v.warnings ?? [])].sort(), reasonCodes:[...(v.reasonCodes ?? [])].sort(), signals:[...(v.signals ?? [])].map((s:any)=>({ ...s, warnings:[...(s.warnings ?? [])].sort(), reasonCodes:[...(s.reasonCodes ?? [])].sort(), evidencePointIds:[...(s.evidencePointIds ?? [])].sort() })).sort((a:any,b:any)=>String(a.signalId ?? a.ruleId ?? a.family).localeCompare(String(b.signalId ?? b.ruleId ?? b.family))) } : v; }
export function protocolEvidenceSnapshotId(bundle: ProtocolEvidenceBundle): string { return `cap-evidence:${canonicalHash({ eventEvaluationId: bundle.eventEvaluation.eventEvaluationId, assessmentEvidenceHash: bundle.eventEvaluation.assessmentEvidenceHash, expectationId: bundle.expectation.expectationId, contradictionHash: canonicalHash(normalizedContradiction(bundle.contradictionMatrix)), invalidationHash: canonicalHash(bundle.invalidationState), analogRetrievalId: bundle.analogRetrieval?.retrievalId ?? null, analogQueryFeatureHash: bundle.analogRetrieval?.queryFeatureHash ?? null })}`; }
export function protocolDecisionId(input: { bundle: ProtocolEvidenceBundle; evidenceCutoffAt: string; previousProtocolDecisionId?: string | null }): string { return `cap-decision:${canonicalHash({ policyVersion: CONTRADICTION_ACTION_PROTOCOL_POLICY_VERSION, eventEvaluationId: input.bundle.eventEvaluation.eventEvaluationId, assessmentEvidenceHash: input.bundle.eventEvaluation.assessmentEvidenceHash, expectationId: input.bundle.expectation.expectationId, cognitionSnapshotIds: [input.bundle.eventEvaluation.preEventCognitionSnapshotId, input.bundle.eventEvaluation.postEventCognitionSnapshotId].filter(Boolean).sort(), contradictionEvidenceHash: canonicalHash(normalizedContradiction(input.bundle.contradictionMatrix)), invalidationStateHash: canonicalHash(input.bundle.invalidationState), analogRetrievalId: input.bundle.analogRetrieval?.retrievalId ?? null, analogQueryFeatureHash: input.bundle.analogRetrieval?.queryFeatureHash ?? null, evidenceCutoffAt: input.evidenceCutoffAt, previousProtocolDecisionId: input.previousProtocolDecisionId ?? null })}`; }
export function transitionId(previousProtocolDecisionId: string, nextProtocolDecisionId: string): string { return `cap-transition:${canonicalHash({ previousProtocolDecisionId, nextProtocolDecisionId })}`; }
export function payloadHash(record: Omit<ProtocolAuditRecord,'canonicalPayloadHash'>): string { return canonicalHash(record); }
export function makeSupersession(previousProtocolDecisionId: string, nextProtocolDecisionId: string): SupersessionLink { return { previousProtocolDecisionId, transitionId: transitionId(previousProtocolDecisionId,nextProtocolDecisionId), supersedes: true }; }
