import { evaluateMarketContradictionMatrix } from '../contradiction-matrix/index';
import type { EventExpectationRepository, EventRealityRepository } from '../expectation-reality/repository';
import type { HistoricalAnalogRepository } from '../historical-analog-memory/contracts';
import type { MarketContradictionInput, MarketContradictionMatrixResult } from '@elceo/types';
import { canonicalHash } from '../expectation-reality/identity';
import { CONTRADICTION_ACTION_PROTOCOL_POLICY_VERSION, BLOCKED_ACTION_CLASSES, reviewPromptForState, validateNoAdviceRecord } from './policy';
import { makeSupersession, payloadHash, protocolDecisionId, protocolEvidenceSnapshotId } from './identity';
import { decideProtocolState, assessmentStageOrder } from './state-machine';
import type { ContradictionActionProtocolRepository } from './repository';
import type { ProtocolAuditRecord, ProtocolDecisionRequest, ProtocolEvidenceBundle, EvidenceReference } from './contracts';

export type ProtocolEvidenceLoaders = { eventRealityRepository: EventRealityRepository; eventExpectationRepository: EventExpectationRepository; analogRepository?: HistoricalAnalogRepository; protocolRepository: ContradictionActionProtocolRepository; contradictionInputForEvent?: (eventEvaluationId: string) => Promise<MarketContradictionInput | MarketContradictionMatrixResult> };
export class ContradictionActionProtocolService { constructor(private readonly deps: ProtocolEvidenceLoaders) {}
  async decide(request: ProtocolDecisionRequest): Promise<ProtocolAuditRecord> { const e=await this.deps.eventRealityRepository.getEventEvaluationById(request.eventEvaluationId); if(!e) throw new Error('event_evaluation_not_found'); const expectation=await this.deps.eventExpectationRepository.getEventExpectationById(e.expectationId); if(!expectation) throw new Error('event_expectation_not_found'); if(expectation.expectationId!==e.expectationId || expectation.asset!==e.asset) throw new Error('mismatched_event_expectation_identity'); if(Date.parse(e.interpretedAt)>Date.parse(request.evidenceCutoffAt) || Date.parse(e.createdAt)>Date.parse(request.evidenceCutoffAt)) throw new Error('evidence_after_protocol_cutoff'); if(!e.assessmentEvidenceHash || !e.observationContentHash) throw new Error('missing_content_hash'); const analog=request.analogRetrievalId && this.deps.analogRepository ? await this.deps.analogRepository.getRetrievalById(request.analogRetrievalId) : null; if(request.analogRetrievalId && !analog) throw new Error('analog_retrieval_not_found'); if(analog){ if(analog.queryEventEvaluationId!==e.eventEvaluationId) throw new Error('cross_event_analog_retrieval_mismatch'); if(Date.parse(analog.createdAt)>Date.parse(request.evidenceCutoffAt) || Date.parse(analog.queryCutoffAt)>Date.parse(request.evidenceCutoffAt)) throw new Error('analog_evidence_after_protocol_cutoff'); for(const snap of analog.memorySnapshot) if(snap.selectedStageAssessmentStageOrder>assessmentStageOrder(e.assessmentStage)) throw new Error('future_stage_evidence_rejected'); }
    const raw=this.deps.contradictionInputForEvent ? await this.deps.contradictionInputForEvent(e.eventEvaluationId) : this.defaultContradictionInput(e); const matrix = 'signals' in raw && 'resultId' in raw ? raw as MarketContradictionMatrixResult : evaluateMarketContradictionMatrix(raw as MarketContradictionInput); const bundle: ProtocolEvidenceBundle={ eventEvaluation:e, expectation, analogRetrieval:analog, contradictionMatrix:matrix, invalidationState:(expectation as any).invalidationState ?? null };
    const prior=request.previousProtocolDecisionId ? await this.deps.protocolRepository.getProtocolRecordById(request.previousProtocolDecisionId) : null; if(request.previousProtocolDecisionId && !prior) throw new Error('previous_protocol_decision_missing'); if(prior && (prior.sourceEventEvaluationId!==e.eventEvaluationId || prior.sourceExpectationId!==e.expectationId)) throw new Error('cross_event_supersession_rejected'); if(prior && assessmentStageOrder(e.assessmentStage)<assessmentStageOrder((prior as any).sourceAssessmentStage ?? e.assessmentStage)) throw new Error('evidence_stage_regression');
    const decision=decideProtocolState(bundle); const cognition=[e.preEventCognitionSnapshotId, e.postEventCognitionSnapshotId].filter((x): x is string => Boolean(x)).sort(); const analogHash=analog ? canonicalHash({ retrievalId:analog.retrievalId, queryFeatureHash:analog.queryFeatureHash, evidenceSufficiency:analog.evidenceSufficiency, warnings:analog.warnings, limitations:analog.limitations }) : null; const id=protocolDecisionId({ bundle, evidenceCutoffAt: request.evidenceCutoffAt, previousProtocolDecisionId: request.previousProtocolDecisionId ?? null });
    const refs: EvidenceReference[]=[{sourceType:'event_evaluation',sourceId:e.eventEvaluationId,contentHash:e.assessmentEvidenceHash,observedAt:e.interpretedAt,reliability:'verified'},{sourceType:'event_expectation',sourceId:expectation.expectationId,contentHash:canonicalHash(expectation),observedAt:expectation.createdAt,reliability:'verified'},{sourceType:'invalidation_state',sourceId:expectation.expectationId,contentHash:canonicalHash((expectation as any).invalidationState ?? null),observedAt:expectation.createdAt,reliability:'verified'},{sourceType:'contradiction_matrix',sourceId:(matrix as any).resultId ?? protocolEvidenceSnapshotId(bundle),contentHash:canonicalHash(matrix),observedAt:(matrix as any).generatedAt ?? e.interpretedAt,reliability:'verified'},...cognition.map((sid)=>({sourceType:'cognition_snapshot' as const,sourceId:sid,contentHash:sid,observedAt:e.interpretedAt,reliability:'verified' as const}))]; if(analog) refs.push({sourceType:'analog_retrieval',sourceId:analog.retrievalId,contentHash:canonicalHash({id:analog.retrievalId,queryFeatureHash:analog.queryFeatureHash}),observedAt:analog.createdAt,reliability:'verified'});
    const noHash: Omit<ProtocolAuditRecord,'canonicalPayloadHash'>={ protocolDecisionId:id, policyVersion:CONTRADICTION_ACTION_PROTOCOL_POLICY_VERSION, sourceEventEvaluationId:e.eventEvaluationId, sourceExpectationId:e.expectationId, sourceAnalogRetrievalId:analog?.retrievalId ?? null, sourceCognitionSnapshotIds:cognition, contradictionEvidenceHash:canonicalHash(matrix), invalidationStateHash:canonicalHash((expectation as any).invalidationState ?? null), analogContextHash:analogHash, evidenceCutoffAt:request.evidenceCutoffAt, evidenceSufficiency:decision.sufficiency, protocolState:decision.state, transitionReasons:decision.reasons, reviewPrompts:[reviewPromptForState(decision.state)], blockedActionClasses:BLOCKED_ACTION_CLASSES, warnings:[...new Set(decision.warnings)], limitations:[...new Set(decision.limitations.concat(analog?.evidenceSufficiency && analog.evidenceSufficiency !== 'sufficient' ? [`analog_${analog.evidenceSufficiency}`] : []))], deterministicRationale:decision.rationale, sourceEvidenceReferences:refs, contradictionEvidence:{ evidenceSnapshotId:protocolEvidenceSnapshotId(bundle), matrixResultHash:canonicalHash(matrix), severity:(matrix as any).highestSeverity ?? 'none', status:(matrix as any).status ?? 'unknown', score:e.reality.postEventContradiction, families:[...new Set<string>(((matrix as any).signals ?? []).map((s:any)=>String(s.family)))].sort(), warnings:(matrix as any).warnings ?? [], reasonCodes:(matrix as any).reasonCodes ?? [] }, invalidationEvidence:{ invalidationStateHash:canonicalHash((expectation as any).invalidationState ?? null), confirmed:decision.state==='invalidate_thesis', canonicalConditions:decision.state==='invalidate_thesis'?['direct_persisted_canonical_invalidation']:[], state:(expectation as any).invalidationState ?? null }, analogContext:{ absent:!analog, analogContextHash:analogHash, retrievalId:analog?.retrievalId ?? null, queryFeatureHash:analog?.queryFeatureHash ?? null, evidenceSufficiency:analog?.evidenceSufficiency ?? null, limitations:analog?.limitations ?? [], warnings:analog?.warnings ?? [], outcomeContextAttachedAfterSelection:Boolean(analog) }, provenance:{ reliability:['verified'], verifiedSourceCount:refs.length, replaySourceCount:0, fixtureSourceCount:0, unverifiedSourceCount:0, limitations:[] }, previousDecision:request.previousProtocolDecisionId ? makeSupersession(request.previousProtocolDecisionId,id) : null, createdAt:e.interpretedAt };
    const record={...noHash, canonicalPayloadHash:payloadHash(noHash)}; validateNoAdviceRecord(record); return this.deps.protocolRepository.saveProtocolRecord(record); }
  private defaultContradictionInput(e:any): MarketContradictionInput { return { asset:e.asset, horizon:'event', generatedAt:e.interpretedAt, providerReliabilitySupplied:true, sourceIndependenceVerified:!e.warnings?.includes('source_independence_unverified'), evidencePoints:[], evidenceItems:[], priceReaction:e.reality.primaryPriceReaction } as any; }
}
