import type { BiasState, CanonicalAssetSymbol, ConfidenceAnatomy, ContradictionRegime, InvalidationState, MarketMacroCurrency, MarketMacroEconomicMeaning, MarketMacroIndicatorCategory, MarketMacroIndicatorKind, MarketMacroReleaseImportance, MarketMacroRegion, MarketMacroSurpriseNormalizationResult, MarketPriceReactionInput, MarketPriceReactionResult, Timeframe } from '@elceo/types';

export type ExpectationBias = BiasState | 'mixed' | 'unsupported';
export type ExpectationHorizon = 'immediate' | 'confirmation' | 'follow_through';
export type ExpectationOutcome = 'confirmed' | 'partially_confirmed' | 'delayed_confirmation' | 'unresolved' | 'contradicted' | 'invalidated' | 'two_sided_whipsaw' | 'not_directionally_scorable' | 'insufficient_data';
export type PathClassification = 'clean_confirmation' | 'adverse_then_confirmed' | 'confirmation_then_reversal' | 'contradiction_first' | 'invalidation_first' | 'two_sided_expansion' | 'range_bound' | 'delayed_resolution' | 'insufficient_path' | 'intrabar_order_unknown';
export type DeltaSeverity = 'none' | 'minor' | 'moderate' | 'major' | 'critical';
export type FirstMaterialMoveDirection = 'expected' | 'opposite' | 'up' | 'down' | 'none';
export type EventExpectationBasis = { kind: 'numeric'; forecast: number | null; previous: number | null; unit: string | null } | { kind: 'non_numeric'; basisLabel: string; expectedState: string; unit?: string | null };
export type EventInterpretationOutcome = 'confirmed' | 'rejected' | 'absorbed' | 'delayed' | 'reversed' | 'ambiguous' | 'mispriced_candidate' | 'insufficient_data';
export type SourceProvenance = { sourceId: string; provider: string; publisher?: string | null; payloadRef?: string | null; reliability: 'verified' | 'replay' | 'fixture' | 'unverified'; contentHash?: string | null; effectiveReliability?: 'verified' | 'replay' | 'fixture' | 'unverified'; trustBasis?: string | null; verificationRef?: string | null; verifiedAt?: string | null };

export type EventExpectationRecord = {
  expectationId: string; expectationKind: 'event'; eventReleaseId: string; eventKind: string; scheduledReleaseTime: string; issuedAt: string; dataCutoffAt: string;
  asset: CanonicalAssetSymbol; affectedAssets: CanonicalAssetSymbol[]; affectedCurrencies: string[]; indicatorKind: MarketMacroIndicatorKind | string; indicatorCategory: MarketMacroIndicatorCategory | string;
  region: MarketMacroRegion | string; currency: MarketMacroCurrency | string; importance: MarketMacroReleaseImportance; expectationBasis: EventExpectationBasis; expectedEconomicMeaning: MarketMacroEconomicMeaning | string; expectedPolicyPressure: string;
  expectedAssetDirection: ExpectationBias; requiredRelatedAssets: CanonicalAssetSymbol[]; preEventCognitionSnapshotId: string; preEventConfidence: number; preEventContradiction: number; expectedConfirmationConditions: string[]; provenance: SourceProvenance[]; createdAt: string;
};

export type EventExpectationDraft = Omit<EventExpectationRecord, 'preEventConfidence' | 'preEventContradiction' | 'expectedAssetDirection'>;
export type EventReactionCandle = MarketPriceReactionInput['candles'][number] & { openedAt: string; closedAt: string; complete: boolean; verifiedPostEventSplit?: boolean; parentCandleRef?: string | null; splitAt?: string | null; splitProvenance?: string | null };
export type RelatedEvidenceStatus = 'confirmed' | 'conflicting_final' | 'insufficient_final' | 'explicitly_unavailable' | 'not_required' | 'pending';
export type RelatedEvidenceAvailabilityEvidence = { asset: CanonicalAssetSymbol; availability: 'available' | 'unavailable' | 'unknown'; verificationRef: string; verifiedAt: string; trustBasis: string };
export type RelatedEvidenceDecision = { status: RelatedEvidenceStatus; decidedAt: string | null; policyVersion: 'related-evidence-closure-v1'; reasonCodes: string[]; evidenceRefs?: string[]; availabilityEvidence?: RelatedEvidenceAvailabilityEvidence[]; policyParameters?: { deadlineMinutes: number } };
export type SplitVerificationResult = { parentCandleRef: string; splitAt: string; splitProvenance: string; segmentContentHash: string; splitVerificationRef: string; verifiedAt: string };
export type ReactionObservationEnvelope = { reactionInput: Omit<MarketPriceReactionInput, 'candles'> & { candles: EventReactionCandle[] }; sourceId: string; provider: string; payloadRef?: string | null; observationVersion: string; suppliedContentHash?: string | null; calculatedContentHash?: string | null; reliability: 'verified' | 'replay' | 'fixture' | 'unverified'; effectiveReliability?: 'verified' | 'replay' | 'fixture' | 'unverified'; trustBasis?: string | null; verificationRef?: string | null; verifiedAt?: string | null; splitVerifications?: SplitVerificationResult[]; timeframe?: Timeframe | null; barDurationMinutes?: number | null };
export type EventPriceTimelineState = 'confirmed' | 'rejected' | 'absorbed' | 'reversed' | 'delayed' | 'insufficient_data' | 'ambiguous' | 'unknown';
export type PriceReactionTimelinePhase = { state: EventPriceTimelineState; startTimestamp: string | null; endTimestamp: string | null; requiredBarCount: number; availableBarCount: number; moveFromOriginPct: number | null; volatilityAdjustedMove: number | null; observedDirection: 'bullish' | 'bearish' | 'neutral' | 'unknown'; reasonCodes: string[]; warnings: string[] };
export type PriceReactionTimeline = { policyVersion: 'event-price-timeline-v1'; primaryObservation: ReactionObservationEnvelope; immediate: PriceReactionTimelinePhase; confirmation: PriceReactionTimelinePhase; followThrough: PriceReactionTimelinePhase; laterAcceptance: PriceReactionTimelinePhase; initialState: EventPriceTimelineState; confirmationWindowState: EventPriceTimelineState; followThroughState: EventPriceTimelineState; laterAcceptanceState: EventPriceTimelineState; reversalAbsorptionState: 'none' | 'absorbed' | 'reversed'; acceptanceTimestamp: string | null; acceptancePhase: 'immediate' | 'confirmation' | 'follow_through' | null; firstAcceptanceTimestamp: string | null; firstAcceptancePhase: 'immediate' | 'confirmation' | 'follow_through' | null; acceptanceLostTimestamp: string | null; renewedAcceptanceTimestamp: string | null; renewedAcceptancePhase: 'immediate' | 'confirmation' | 'follow_through' | null; firstContradictionTimestamp: string | null; reversalTimestamp: string | null; initialRejectionThenAcceptance: boolean; initialConfirmationThenReversal: boolean };
export type RevisionAdjustedMeasures = { rawSurpriseDelta: number | null; revisionDelta: number | null; revisionAdjustedDelta: number | null; rawNormalizedSurpriseScore: number | null; normalizedRevisionContribution: number | null; rawSignedContribution?: number | null; revisionSignedContribution?: number | null; revisionPolicyVersion: 'event-revision-v1'; revisionFamily: 'inflation' | 'labour_strength' | 'inverted_labour' | 'growth_activity' | 'central_bank_policy' | 'non_additive'; revisionAdjustedDirection: 'economic_positive' | 'economic_negative' | 'inline' | 'unknown'; adjustedSurpriseScore: number | null; adjustedEconomicMeaning: string | null; adjustedPolicyPressure: string | null; adjustedGrowthPressure: string | null; adjustedInflationPressure: string | null; adjustedRiskPressure: string | null; revisionEffect: 'reinforces_surprise' | 'offsets_surprise' | 'reverses_interpretation' | 'immaterial' | 'unavailable'; revisionAdjustedMateriality: 'material' | 'immaterial' | 'unavailable'; limitations: string[] };
export type RelatedMarketState = 'confirmed' | 'conflicting' | 'insufficient' | 'unavailable';
export type ReleaseAlignmentState = 'aligned' | 'contradicted' | 'mixed' | 'inline' | 'insufficient_data';
export type ReleaseAlignment = { status: ReleaseAlignmentState; reasonCodes: string[]; economicMeaningAlignment: ReleaseAlignmentState; policyPressureAlignment: ReleaseAlignmentState; actualVsForecastAlignment: ReleaseAlignmentState; revisionEffect: 'reinforces_surprise' | 'offsets_surprise' | 'reverses_interpretation' | 'immaterial' | 'unavailable'; primaryAssetDirectionAlignment: ReleaseAlignmentState; relatedMarketDirectionAlignment: ReleaseAlignmentState; expectedEconomicMeaning: string; actualEconomicMeaning: string | null; expectedPolicyPressure: string; actualPolicyPressure: string | null; expectedDirection: ExpectationBias; actualDirection: ExpectationBias | null; revisionExpectationImpact?: 'reinforces_alignment' | 'weakens_alignment' | 'reverses_to_alignment' | 'reverses_to_contradiction' | 'immaterial' | 'unavailable' };

export type EventRealityRecord = {
  releaseAlignment: ReleaseAlignment; revisionAdjustedMeasures: RevisionAdjustedMeasures; priceReactionTimeline: PriceReactionTimeline; releaseId: string; releaseVersion: string; observedAt: string; actual: number | null; forecast: number | null; previous: number | null; revisedPrevious: number | null; normalizedSurprise: MarketMacroSurpriseNormalizationResult | null; nonNumericOutcome?: string | null;
  provenance: SourceProvenance[]; primaryPriceReaction: MarketPriceReactionResult; followThroughReaction: PriceReactionTimelinePhase; relatedMarketReactions: MarketPriceReactionResult[]; actualAssetDirections: { asset: CanonicalAssetSymbol; resolvedDirection: string; confidence: number; reasonCodes: string[]; warnings: string[] }[]; observationContentHash: string; reactionProvenance: ReactionObservationEnvelope[]; relatedMarketState: RelatedMarketState; relatedEvidenceDecision: RelatedEvidenceDecision; postEventCognitionSnapshotId: string | null; postEventCognitionEvaluatedAt: string | null;
  postEventConfidence: number | null; confidenceDelta: number | null; postEventContradiction: number | null; contradictionDelta: number | null; biasChange: { before: ExpectationBias; after: ExpectationBias | null; changed: boolean }; warnings: string[]; limitations: string[];
};

export type EventAssessmentStage = 'immediate' | 'confirmation' | 'follow_through';
export type EventFinalizationStatus = 'provisional' | 'finalizable' | 'final';
export type EventRealityEvaluation = { assessmentStage: EventAssessmentStage; finalizationStatus: EventFinalizationStatus; finalizationReadiness: { ready: boolean; reasonCodes: string[] }; eventEvaluationId: string; expectationId: string; releaseId: string; releaseVersion: string; asset: CanonicalAssetSymbol; preEventCognitionSnapshotId: string; postEventCognitionSnapshotId: string | null; observationContentHash: string; assessmentEvidenceHash: string; relatedEvidenceStatus: RelatedEvidenceStatus; relatedEvidenceDecisionAt: string | null; relatedEvidencePolicyVersion: 'related-evidence-closure-v1'; relatedEvidenceReasonCodes: string[]; reactionProvenance: ReactionObservationEnvelope[]; interpretedAt: string; outcome: EventInterpretationOutcome; reasonCodes: string[]; warnings: string[]; rationale: string; expectation: EventExpectationRecord; reality: EventRealityRecord; createdAt: string };

export type ExpectationRecord = {
  expectationId: string; asset: CanonicalAssetSymbol; timeframe: Timeframe; issuedAt: string; dataCutoffAt: string;
  reasoningRunId: string; cognitionSnapshotId: string; reasoningVersion: string; scoringVersion: string;
  basePrice: number; recentRangePct: number | null; expectedBias: ExpectationBias; confidenceScore: number;
  confidenceAnatomy: ConfidenceAnatomy; contradictionScore: number; contradictionRegime: ContradictionRegime;
  invalidationState: InvalidationState; topEvidenceIds: string[]; linkedEventIds: string[]; thesis: string;
  whatWouldChangeState: string[]; horizonPolicyVersion: 'expectation-reality-v1'; createdAt: string;
};
export type ObservationProvenance = { sourceId: string; provider: string; payloadRef?: string | null; contentHash?: string | null };
export type ObservationCandle = { openedAt: string; closedAt: string; open: number; high: number; low: number; close: number; complete: boolean; verifiedPostEventSplit?: boolean };
export type ObservationSet = { asset: CanonicalAssetSymbol; timeframe: Timeframe; source: ObservationProvenance; observedWindow: { start: string; end: string }; contentHash: string; observationVersion: string; candles: ObservationCandle[] };
export type RealityMeasures = { terminalReturnPct: number | null; maximumFavourableExcursionPct: number | null; maximumAdverseExcursionPct: number | null; terminalReturnVolUnits: number | null; favourableExcursionVolUnits: number | null; adverseExcursionVolUnits: number | null; firstMaterialMoveDirection: FirstMaterialMoveDirection; firstMaterialMoveAt: string | null; confirmationReachedAt: string | null; contradictionReachedAt: string | null; invalidationBreachedAt: string | null };
export type DeltaAnatomy = { directionDelta: number; pathDelta: number; magnitudeDelta: number; timingDelta: number; invalidationDelta: number; confidenceOutcomeConsistency: number; compositeDeltaScore: number; deltaSeverity: DeltaSeverity; reasonCodes: string[]; warnings: string[]; rationale: string };
export type ExpectationRealityEvaluation = { evaluationId: string; expectationId: string; asset: CanonicalAssetSymbol; timeframe: Timeframe; horizon: ExpectationHorizon; observationVersion: string; observationContentHash: string; evaluatedAt: string; policyVersion: 'expectation-reality-v1'; outcome: ExpectationOutcome; pathClassification: PathClassification; measures: RealityMeasures; delta: DeltaAnatomy; createdAt: string };
export type NumericReleaseFields = { releaseId: string; actual: number | null; revisedPrevious: number | null; observedAt: string; releaseVersion: string; provenance: SourceProvenance[] };

export type EventRealityAssessment = EventRealityEvaluation;
