import type { CanonicalAssetSymbol, Timeframe } from '@elceo/types';
import type { ExpectationRealityEvaluation, ExpectationRecord, ExpectationHorizon } from './contracts';

export type ExpectationRepository = { saveExpectation(r: ExpectationRecord): Promise<void>; getExpectationById(id: string): Promise<ExpectationRecord | null>; getExpectationByCognitionSnapshotId(id: string): Promise<ExpectationRecord | null>; listPendingExpectations(params?: { asset?: CanonicalAssetSymbol; timeframe?: Timeframe; limit?: number }): Promise<ExpectationRecord[]> };
export type ExpectationRealityRepository = { saveEvaluation(e: ExpectationRealityEvaluation): Promise<void>; getEvaluation(expectationId: string, horizon: ExpectationHorizon, observationVersion: string): Promise<ExpectationRealityEvaluation | null>; getLatestExpectationRealityForAssetTimeframe(asset: CanonicalAssetSymbol, timeframe: Timeframe): Promise<ExpectationRealityEvaluation | null>; listExpectationRealityHistory(params: { asset?: CanonicalAssetSymbol; timeframe?: Timeframe; expectationId?: string; limit: number }): Promise<ExpectationRealityEvaluation[]> };

export class MemoryExpectationRepository implements ExpectationRepository {
  private byId = new Map<string, ExpectationRecord>(); private bySnapshot = new Map<string, string>();
  async saveExpectation(r: ExpectationRecord): Promise<void> { const existing = this.byId.get(r.expectationId) ?? (this.bySnapshot.get(r.cognitionSnapshotId) ? this.byId.get(this.bySnapshot.get(r.cognitionSnapshotId)!) : null); if (existing) { if (JSON.stringify(existing) !== JSON.stringify(r)) throw new Error('immutable_expectation_conflict'); return; } this.byId.set(r.expectationId, Object.freeze({ ...r, topEvidenceIds: [...r.topEvidenceIds], linkedEventIds: [...r.linkedEventIds], whatWouldChangeState: [...r.whatWouldChangeState] })); this.bySnapshot.set(r.cognitionSnapshotId, r.expectationId); }
  async getExpectationById(id: string): Promise<ExpectationRecord | null> { return this.byId.get(id) ?? null; }
  async getExpectationByCognitionSnapshotId(id: string): Promise<ExpectationRecord | null> { const eid = this.bySnapshot.get(id); return eid ? this.byId.get(eid) ?? null : null; }
  async listPendingExpectations(params: { asset?: CanonicalAssetSymbol; timeframe?: Timeframe; limit?: number } = {}): Promise<ExpectationRecord[]> { let rows = [...this.byId.values()]; if (params.asset) rows = rows.filter(r => r.asset === params.asset); if (params.timeframe) rows = rows.filter(r => r.timeframe === params.timeframe); rows.sort((a,b)=>Date.parse(a.issuedAt)-Date.parse(b.issuedAt)||a.expectationId.localeCompare(b.expectationId)); return rows.slice(0, params.limit ?? 100); }
}
export class MemoryExpectationRealityRepository implements ExpectationRealityRepository {
  private byKey = new Map<string, ExpectationRealityEvaluation>(); private key(eid:string,h:string,v:string){return `${eid}|${h}|${v}`;}
  async saveEvaluation(e: ExpectationRealityEvaluation): Promise<void> { const k = this.key(e.expectationId,e.horizon,e.observationVersion); const existing = this.byKey.get(k); if (existing) { if (JSON.stringify(existing) !== JSON.stringify(e)) throw new Error('immutable_evaluation_conflict'); return; } this.byKey.set(k, e); }
  async getEvaluation(expectationId: string, horizon: ExpectationHorizon, observationVersion: string): Promise<ExpectationRealityEvaluation | null> { return this.byKey.get(this.key(expectationId,horizon,observationVersion)) ?? null; }
  async getLatestExpectationRealityForAssetTimeframe(asset: CanonicalAssetSymbol, timeframe: Timeframe): Promise<ExpectationRealityEvaluation | null> { return (await this.listExpectationRealityHistory({asset,timeframe,limit:1}))[0] ?? null; }
  async listExpectationRealityHistory(params: { asset?: CanonicalAssetSymbol; timeframe?: Timeframe; expectationId?: string; limit: number }): Promise<ExpectationRealityEvaluation[]> { let rows = [...this.byKey.values()]; if (params.asset) rows=rows.filter(r=>r.asset===params.asset); if(params.timeframe) rows=rows.filter(r=>r.timeframe===params.timeframe); if(params.expectationId) rows=rows.filter(r=>r.expectationId===params.expectationId); rows.sort((a,b)=>Date.parse(b.evaluatedAt)-Date.parse(a.evaluatedAt)||a.evaluationId.localeCompare(b.evaluationId)); return rows.slice(0, params.limit); }
}
