import type { CanonicalAssetSymbol, Timeframe } from '@elceo/types';
import type { EventRealityEvaluation, EventExpectationRecord, ExpectationRealityEvaluation, ExpectationRecord, ExpectationHorizon } from './contracts';
import { canonicalJson, deepCloneFreeze } from './identity';

export type ExpectationRepository = { saveExpectation(r: ExpectationRecord): Promise<ExpectationRecord>; getExpectationById(id: string): Promise<ExpectationRecord | null>; getExpectationByCognitionSnapshotId(id: string): Promise<ExpectationRecord | null>; listPendingExpectations(params?: { asset?: CanonicalAssetSymbol; timeframe?: Timeframe; horizon?: ExpectationHorizon; observationVersion?: string; limit?: number }): Promise<ExpectationRecord[]> };
export type ExpectationRealityRepository = { saveEvaluation(e: ExpectationRealityEvaluation): Promise<ExpectationRealityEvaluation>; getEvaluation(expectationId: string, horizon: ExpectationHorizon, observationVersion: string): Promise<ExpectationRealityEvaluation | null>; getLatestExpectationRealityForAssetTimeframe(asset: CanonicalAssetSymbol, timeframe: Timeframe): Promise<ExpectationRealityEvaluation | null>; listExpectationRealityHistory(params: { asset?: CanonicalAssetSymbol; timeframe?: Timeframe; expectationId?: string; limit: number }): Promise<ExpectationRealityEvaluation[]> };
export type EventExpectationRepository = { saveEventExpectation(r: EventExpectationRecord): Promise<EventExpectationRecord>; getEventExpectationById(id: string): Promise<EventExpectationRecord | null> };
export type EventRealityRepository = { saveEventEvaluation(e: EventRealityEvaluation): Promise<EventRealityEvaluation>; getEventEvaluation(expectationId: string, releaseVersion: string): Promise<EventRealityEvaluation | null> };

export class MemoryExpectationRealityRepository implements ExpectationRealityRepository {
  private byKey = new Map<string, ExpectationRealityEvaluation>(); private versionHashes = new Map<string, string>(); private key(eid:string,h:string,v:string){return `${eid}|${h}|${v}`;}
  async saveEvaluation(e: ExpectationRealityEvaluation): Promise<ExpectationRealityEvaluation> { const versionKey = `${e.expectationId}|${e.observationVersion}`; const priorHash = this.versionHashes.get(versionKey); if (priorHash && priorHash !== e.observationContentHash) throw new Error('observation_version_content_hash_conflict'); const k = this.key(e.expectationId,e.horizon,e.observationVersion); const existing = this.byKey.get(k); if (existing) { if (canonicalJson(existing) !== canonicalJson(e)) throw new Error('immutable_evaluation_conflict'); return existing; } this.versionHashes.set(versionKey, e.observationContentHash); const frozen = deepCloneFreeze(e); this.byKey.set(k, frozen); return frozen; }
  async getEvaluation(expectationId: string, horizon: ExpectationHorizon, observationVersion: string): Promise<ExpectationRealityEvaluation | null> { return this.byKey.get(this.key(expectationId,horizon,observationVersion)) ?? null; }
  async getLatestExpectationRealityForAssetTimeframe(asset: CanonicalAssetSymbol, timeframe: Timeframe): Promise<ExpectationRealityEvaluation | null> { return (await this.listExpectationRealityHistory({asset,timeframe,limit:1}))[0] ?? null; }
  async listExpectationRealityHistory(params: { asset?: CanonicalAssetSymbol; timeframe?: Timeframe; expectationId?: string; limit: number }): Promise<ExpectationRealityEvaluation[]> { let rows = [...this.byKey.values()]; if (params.asset) rows=rows.filter(r=>r.asset===params.asset); if(params.timeframe) rows=rows.filter(r=>r.timeframe===params.timeframe); if(params.expectationId) rows=rows.filter(r=>r.expectationId===params.expectationId); rows.sort((a,b)=>Date.parse(b.evaluatedAt)-Date.parse(a.evaluatedAt)||a.evaluationId.localeCompare(b.evaluationId)); return rows.slice(0, params.limit); }
}
export class MemoryExpectationRepository implements ExpectationRepository {
  private byId = new Map<string, ExpectationRecord>(); private bySnapshot = new Map<string, string>();
  constructor(private readonly evaluations?: ExpectationRealityRepository) {}
  async saveExpectation(r: ExpectationRecord): Promise<ExpectationRecord> { const existing = this.byId.get(r.expectationId) ?? (this.bySnapshot.get(r.cognitionSnapshotId) ? this.byId.get(this.bySnapshot.get(r.cognitionSnapshotId)!) : null); if (existing) { if (canonicalJson(existing) !== canonicalJson(r)) throw new Error('immutable_expectation_conflict'); return existing; } const frozen = deepCloneFreeze(r); this.byId.set(r.expectationId, frozen); this.bySnapshot.set(r.cognitionSnapshotId, r.expectationId); return frozen; }
  async getExpectationById(id: string): Promise<ExpectationRecord | null> { return this.byId.get(id) ?? null; }
  async getExpectationByCognitionSnapshotId(id: string): Promise<ExpectationRecord | null> { const eid = this.bySnapshot.get(id); return eid ? this.byId.get(eid) ?? null : null; }
  async listPendingExpectations(params: { asset?: CanonicalAssetSymbol; timeframe?: Timeframe; horizon?: ExpectationHorizon; observationVersion?: string; limit?: number } = {}): Promise<ExpectationRecord[]> { let rows = [...this.byId.values()]; if (params.asset) rows = rows.filter(r => r.asset === params.asset); if (params.timeframe) rows = rows.filter(r => r.timeframe === params.timeframe); if (params.horizon && params.observationVersion && this.evaluations) { const pending: ExpectationRecord[] = []; for (const row of rows) if (!(await this.evaluations.getEvaluation(row.expectationId, params.horizon, params.observationVersion))) pending.push(row); rows = pending; } rows.sort((a,b)=>Date.parse(a.issuedAt)-Date.parse(b.issuedAt)||a.expectationId.localeCompare(b.expectationId)); return rows.slice(0, params.limit ?? 100); }
}
export class MemoryEventExpectationRepository implements EventExpectationRepository { private byId = new Map<string, EventExpectationRecord>(); async saveEventExpectation(r: EventExpectationRecord){ const existing=this.byId.get(r.expectationId); if(existing){ if(canonicalJson(existing)!==canonicalJson(r)) throw new Error('immutable_event_expectation_conflict'); return existing; } const frozen=deepCloneFreeze(r); this.byId.set(r.expectationId, frozen); return frozen; } async getEventExpectationById(id:string){ return this.byId.get(id) ?? null; } }
export class MemoryEventRealityRepository implements EventRealityRepository { private byKey = new Map<string, EventRealityEvaluation>(); private key(e: EventRealityEvaluation){ return e.finalizationStatus === 'final' ? `${e.expectationId}|${e.releaseVersion}|final` : `${e.expectationId}|${e.releaseVersion}|${e.assessmentEvidenceHash}|${e.finalizationStatus}`; } async saveEventEvaluation(e: EventRealityEvaluation){ const k=this.key(e); const existing=this.byKey.get(k); if(existing){ if(canonicalJson(existing)!==canonicalJson(e)) throw new Error('immutable_event_evaluation_conflict'); return existing; } const frozen=deepCloneFreeze(e); this.byKey.set(k,frozen); return frozen; } async getEventEvaluation(expectationId:string,releaseVersion:string){ return this.byKey.get(`${expectationId}|${releaseVersion}|final`) ?? [...this.byKey.values()].filter((e)=>e.expectationId===expectationId&&e.releaseVersion===releaseVersion).sort((a,b)=>Date.parse(b.interpretedAt)-Date.parse(a.interpretedAt))[0] ?? null; } }
