import type { CanonicalAssetSymbol, Timeframe } from '@elceo/types';
import type { ExpectationRealityEvaluation, ExpectationHorizon, ExpectationRecord } from './contracts';
import type { ExpectationRealityRepository, ExpectationRepository } from './repository';
async function q<T extends Record<string, unknown>>(sql:string, params:unknown[]=[]):Promise<T[]> { const m=await import('pg'); const pool = new (m as any).Pool({ connectionString: (globalThis as any).process?.env?.DATABASE_URL }); return (await pool.query(sql,params)).rows as T[]; }
export class SqlExpectationRepository implements ExpectationRepository {
 async saveExpectation(r:ExpectationRecord){ await q(`INSERT INTO app_expectation_records (expectation_id,asset,timeframe,issued_at,data_cutoff_at,reasoning_run_id,cognition_snapshot_id,reasoning_version,scoring_version,base_price,recent_range_pct,expected_bias,confidence_score,contradiction_score,contradiction_regime,payload_json,created_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17) ON CONFLICT (expectation_id) DO NOTHING`,[r.expectationId,r.asset,r.timeframe,r.issuedAt,r.dataCutoffAt,r.reasoningRunId,r.cognitionSnapshotId,r.reasoningVersion,r.scoringVersion,r.basePrice,r.recentRangePct,r.expectedBias,r.confidenceScore,r.contradictionScore,r.contradictionRegime,JSON.stringify(r),r.createdAt]); }
 async getExpectationById(id:string){ const rows=await q<{payload_json:ExpectationRecord}>('SELECT payload_json FROM app_expectation_records WHERE expectation_id=$1',[id]); return rows[0]?.payload_json ?? null; }
 async getExpectationByCognitionSnapshotId(id:string){ const rows=await q<{payload_json:ExpectationRecord}>('SELECT payload_json FROM app_expectation_records WHERE cognition_snapshot_id=$1',[id]); return rows[0]?.payload_json ?? null; }
 async listPendingExpectations(params:{asset?:CanonicalAssetSymbol;timeframe?:Timeframe;limit?:number}={}){ const rows=await q<{payload_json:ExpectationRecord}>('SELECT payload_json FROM app_expectation_records WHERE ($1::text IS NULL OR asset=$1) AND ($2::text IS NULL OR timeframe=$2) ORDER BY issued_at ASC LIMIT $3',[params.asset??null,params.timeframe??null,params.limit??100]); return rows.map(r=>r.payload_json); }
}
export class SqlExpectationRealityRepository implements ExpectationRealityRepository {
 async saveEvaluation(e:ExpectationRealityEvaluation){ await q(`INSERT INTO app_expectation_reality_evaluations (evaluation_id,expectation_id,asset,timeframe,horizon,observation_version,evaluated_at,policy_version,outcome,path_classification,audit_json,created_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) ON CONFLICT (expectation_id,horizon,observation_version) DO NOTHING`,[e.evaluationId,e.expectationId,e.asset,e.timeframe,e.horizon,e.observationVersion,e.evaluatedAt,e.policyVersion,e.outcome,e.pathClassification,JSON.stringify(e),e.createdAt]); }
 async getEvaluation(expectationId:string,horizon:ExpectationHorizon,observationVersion:string){ const rows=await q<{audit_json:ExpectationRealityEvaluation}>('SELECT audit_json FROM app_expectation_reality_evaluations WHERE expectation_id=$1 AND horizon=$2 AND observation_version=$3',[expectationId,horizon,observationVersion]); return rows[0]?.audit_json ?? null; }
 async getLatestExpectationRealityForAssetTimeframe(asset:CanonicalAssetSymbol,timeframe:Timeframe){ return (await this.listExpectationRealityHistory({asset,timeframe,limit:1}))[0]??null; }
 async listExpectationRealityHistory(params:{asset?:CanonicalAssetSymbol;timeframe?:Timeframe;expectationId?:string;limit:number}){ const rows=await q<{audit_json:ExpectationRealityEvaluation}>('SELECT audit_json FROM app_expectation_reality_evaluations WHERE ($1::text IS NULL OR asset=$1) AND ($2::text IS NULL OR timeframe=$2) AND ($3::text IS NULL OR expectation_id=$3) ORDER BY evaluated_at DESC LIMIT $4',[params.asset??null,params.timeframe??null,params.expectationId??null,params.limit]); return rows.map(r=>r.audit_json); }
}
