import { randomUUID } from 'node:crypto';
import { buildCanonicalDashboardProjection, CANONICAL_DASHBOARD_DISPLAY_VERSION, CANONICAL_DASHBOARD_POLICY_VERSION, CANONICAL_DASHBOARD_PROJECTION_VERSION, CANONICAL_DASHBOARD_ZONE_RULE_VERSION, type CanonicalDashboardProjection } from '@elceo/chart-intelligence';
import { getCanonicalCandleObservation, validateMarketCognitionSnapshot } from '@elceo/schemas';
import type { CanonicalAssetSymbol, CanonicalEvent, CanonicalMarketCandleObservation, EvidenceWeightHorizon, MarketCognitionSnapshot } from '@elceo/types';
import type { AdaptiveOwnershipStore, CanonicalArtifact, DashboardProjectionArtifact, EvidenceOrCognitionArtifact, MaterializationLease, MaterializationRepository } from './contracts';
import { buildArtifactIntegrityHash, buildCanonicalPayloadHash, buildDashboardProjectionArtifactIdentity, buildDashboardProjectionCoordinationHash, buildMaterializationScopeHash } from './identity';

export const DASHBOARD_PROJECTION_FRESHNESS_POLICY_VERSION='dashboard-parent-cognition-boundary-v1' as const;
export type PersistedCanonicalCandleReader={getLatestEventsForAssetTimeframe(asset:CanonicalAssetSymbol,timeframe:'H4'):Promise<CanonicalEvent[]>};
export type DashboardProjectionMaterializationRequest={asset:CanonicalAssetSymbol;horizon:EvidenceWeightHorizon;timeframe:'H4';parentCognitionArtifactIdentity:string;leaseDurationMs:number;retryMaximumMs:number};

/** Adapter over persisted ingestion snapshots. It never parses rawPayload. */
export class PersistedCanonicalCandleObservationReader {
  constructor(private readonly repository:PersistedCanonicalCandleReader){}
  async read(asset:CanonicalAssetSymbol,evaluatedAt:string){const boundary=Date.parse(evaluatedAt),events=await this.repository.getLatestEventsForAssetTimeframe(asset,'H4');return events.map(getCanonicalCandleObservation).filter((value):value is CanonicalMarketCandleObservation=>value!==null&&Date.parse(value.observedAt)<=boundary)}
}

export class CanonicalDashboardProjectionMaterializationService {
  constructor(private readonly repository:MaterializationRepository,private readonly ownership:AdaptiveOwnershipStore,private readonly candles:PersistedCanonicalCandleObservationReader){}
  private coordination(r:DashboardProjectionMaterializationRequest){return buildDashboardProjectionCoordinationHash({asset:r.asset,horizon:r.horizon,timeframe:r.timeframe,projectionVersion:CANONICAL_DASHBOARD_PROJECTION_VERSION,displayVersion:CANONICAL_DASHBOARD_DISPLAY_VERSION,zoneRuleVersion:CANONICAL_DASHBOARD_ZONE_RULE_VERSION,productPolicyVersion:CANONICAL_DASHBOARD_POLICY_VERSION})}
  private scope(r:DashboardProjectionMaterializationRequest){return buildMaterializationScopeHash({asset:r.asset,horizon:r.horizon,kind:'dashboard_projection',timeframe:r.timeframe,projectionVersion:CANONICAL_DASHBOARD_PROJECTION_VERSION,displayVersion:CANONICAL_DASHBOARD_DISPLAY_VERSION,zoneRuleVersion:CANONICAL_DASHBOARD_ZONE_RULE_VERSION,productPolicyVersion:CANONICAL_DASHBOARD_POLICY_VERSION})}
  async materialize(r:DashboardProjectionMaterializationRequest):Promise<DashboardProjectionArtifact<CanonicalDashboardProjection>>{
    const coordination=this.coordination(r),scope=this.scope(r),ownershipIdentity=buildArtifactIntegrityHash({kind:'dashboard_projection',parentCognitionArtifactIdentity:r.parentCognitionArtifactIdentity,asset:r.asset,horizon:r.horizon,timeframe:r.timeframe,projectionVersion:CANONICAL_DASHBOARD_PROJECTION_VERSION,displayVersion:CANONICAL_DASHBOARD_DISPLAY_VERSION,zoneRuleVersion:CANONICAL_DASHBOARD_ZONE_RULE_VERSION,productPolicyVersion:CANONICAL_DASHBOARD_POLICY_VERSION}),ownerToken=randomUUID(),started=Date.now(),initialCompletion=await this.ownership.readMaterializationCompletion?.(coordination,ownershipIdentity,scope);let lease:MaterializationLease|undefined,followed=false;
    while(!lease){const acquired=await this.ownership.acquireMaterialization(coordination,ownershipIdentity,ownerToken,r.leaseDurationMs);if(acquired.acquired)lease=acquired.lease;else{followed=true;if(!('reason' in acquired))throw new Error('dashboard_projection_lease_state_invalid');if(acquired.reason==='adaptive_scheduler_unavailable'||Date.now()-started>=r.retryMaximumMs)throw new Error(acquired.reason);await new Promise(resolve=>setTimeout(resolve,Math.max(10,Math.floor(r.leaseDurationMs/3))))}}
    if(followed){const completion=await this.ownership.readMaterializationCompletion?.(coordination,ownershipIdentity,scope),published=await this.repository.readCurrent<CanonicalDashboardProjection>(coordination,scope);if(completion&&completion.completionToken!==initialCompletion?.completionToken&&published.artifact?.kind==='dashboard_projection'&&published.artifact.identity===completion.identity&&published.artifact.parentCognitionArtifactIdentity===r.parentCognitionArtifactIdentity){await this.ownership.release(lease);return published.artifact}}
    let lost=false;
    const heartbeat=setInterval(()=>void this.ownership.renew(lease!,r.leaseDurationMs).then(next=>{if(next)lease=next;else lost=true}),Math.max(10,Math.floor(r.leaseDurationMs/3)));
    try{
    const parent=await this.repository.getByIdentity<MarketCognitionSnapshot>(r.parentCognitionArtifactIdentity);
    this.validateParent(parent,r);
    const cognition=parent.payload,evaluatedAt=parent.evaluatedAt,observations=await this.candles.read(r.asset,evaluatedAt);
    const ordered=[...observations].sort((a,b)=>Date.parse(a.observedAt)-Date.parse(b.observedAt)||a.observationId.localeCompare(b.observationId));
    const projection=buildCanonicalDashboardProjection({asset:r.asset,timeframe:r.timeframe,horizon:r.horizon,cognition,cognitionArtifact:{identity:parent.identity,contentHash:buildCanonicalPayloadHash(parent.payload),contractVersion:'market-cognition-v1',provenance:[parent.evidenceIdentity]},candles:ordered,orderedCandleObservationIds:ordered.map(x=>x.observationId),orderedCandleContentHashes:ordered.map(x=>x.contentHash),evaluatedAt,projectionVersion:CANONICAL_DASHBOARD_PROJECTION_VERSION,dashboardDisplayContractVersion:CANONICAL_DASHBOARD_DISPLAY_VERSION,chartZoneRuleVersion:CANONICAL_DASHBOARD_ZONE_RULE_VERSION,productPolicyVersion:CANONICAL_DASHBOARD_POLICY_VERSION});
    const lineage={projectionIdentity:projection.projection_identity,schemaVersion:'canonical_materialization_v1'as const,parentCognitionArtifactIdentity:parent.identity,parentCognitionIntegrityHash:parent.integrityHash,orderedCandleObservationIds:projection.ordered_candle_observation_ids,orderedCandleContentHashes:projection.ordered_candle_content_hashes,freshnessPolicyVersion:DASHBOARD_PROJECTION_FRESHNESS_POLICY_VERSION},identity=buildDashboardProjectionArtifactIdentity(lineage),existing=await this.repository.getByIdentity<CanonicalDashboardProjection>(identity);if(existing){if(existing.kind!=='dashboard_projection')throw new Error('dashboard_projection_identity_kind_conflict');if(lost||!await this.ownership.isCurrent(lease))throw new Error('dashboard_projection_ownership_lost');if(!await this.repository.publish(lease,existing))throw new Error('dashboard_projection_stale_owner_publish_denied');return existing}
    const body={schemaVersion:'canonical_materialization_v1'as const,kind:'dashboard_projection'as const,identity,scopeHash:scope,payload:projection,asset:r.asset,horizon:r.horizon,timeframe:r.timeframe,projectionIdentity:projection.projection_identity,parentCognitionArtifactIdentity:parent.identity,parentCognitionIntegrityHash:parent.integrityHash,parentCognitionContentIdentity:buildCanonicalPayloadHash(parent.payload),parentCognitionContractVersion:'market-cognition-v1',orderedCandleObservationIds:projection.ordered_candle_observation_ids,orderedCandleContentHashes:projection.ordered_candle_content_hashes,projectionVersion:CANONICAL_DASHBOARD_PROJECTION_VERSION,dashboardDisplayContractVersion:CANONICAL_DASHBOARD_DISPLAY_VERSION,chartZoneRuleVersion:CANONICAL_DASHBOARD_ZONE_RULE_VERSION,dashboardProductPolicyVersion:CANONICAL_DASHBOARD_POLICY_VERSION,freshnessPolicyVersion:DASHBOARD_PROJECTION_FRESHNESS_POLICY_VERSION,generatedAt:evaluatedAt,evaluatedAt,freshUntil:parent.freshUntil},artifact:DashboardProjectionArtifact<CanonicalDashboardProjection>={...body,integrityHash:buildArtifactIntegrityHash(body)};
    if(lost||!await this.ownership.isCurrent(lease))throw new Error('dashboard_projection_ownership_lost');
    if(!await this.repository.publish(lease,artifact))throw new Error('dashboard_projection_stale_owner_publish_denied');return artifact
    }finally{clearInterval(heartbeat);await this.ownership.release(lease)}}
  private validateParent(parent:CanonicalArtifact<MarketCognitionSnapshot>|null,r:DashboardProjectionMaterializationRequest):asserts parent is EvidenceOrCognitionArtifact<MarketCognitionSnapshot>&{kind:'cognition'}{if(!parent||parent.kind!=='cognition'||parent.identity!==r.parentCognitionArtifactIdentity)throw new Error('dashboard_projection_parent_cognition_required');const{integrityHash,...body}=parent;if(integrityHash!==buildArtifactIntegrityHash(body))throw new Error('dashboard_projection_parent_integrity_invalid');if(!validateMarketCognitionSnapshot(parent.payload).ok||parent.payload.horizon!==r.horizon)throw new Error('dashboard_projection_parent_scope_mismatch');if(Date.parse(parent.payload.generatedAt)>Date.parse(parent.evaluatedAt))throw new Error('dashboard_projection_parent_future_boundary')}
}
