import { validateNormalizedMarketEvidencePayload } from '@elceo/schemas';
import type { NormalizedMarketEvidencePayload } from '@elceo/types';
import { buildProviderNormalizedRequestKey, type ProviderRuntimeRequest, type ProviderApiGateExecutionResult } from '../provider-sources/provider-api-gate';
import type { AdaptiveMaterializationMetrics, AdaptiveMaterializationPolicy, CanonicalArtifact, MaterializationLease, MaterializationRepository } from './contracts';
import { buildArtifactIntegrityHash, buildCanonicalEvidenceIdentity, buildCanonicalPayloadHash, buildMaterializationScopeHash } from './identity';
export type CanonicalEvidencePayload={normalizedPayloads:readonly NormalizedMarketEvidencePayload[]};
const extractNormalized=(payload:unknown):NormalizedMarketEvidencePayload[]|null=>{const values=Array.isArray(payload)?payload:payload&&typeof payload==='object'&&'normalizedPayloads'in payload&&Array.isArray(payload.normalizedPayloads)?payload.normalizedPayloads:null;if(!values)return null;const validated=(values as unknown[]).map(value=>validateNormalizedMarketEvidencePayload(value));return validated.every(x=>x.ok)?validated.flatMap(x=>x.ok?[x.value]:[]):null};
export class CanonicalEvidenceMaterializationService {constructor(private readonly repository:MaterializationRepository,private readonly evidenceContractVersion:string,private readonly metrics:AdaptiveMaterializationMetrics){}
 async materializeResult(lease:MaterializationLease,policy:AdaptiveMaterializationPolicy,request:ProviderRuntimeRequest,result:ProviderApiGateExecutionResult,evaluatedAt:number,schedulerRunId:string){const response=result.response,normalized=response?extractNormalized(response.payload):null;if(result.cacheSnapshot?.freshness==='stale')throw new Error('stale_provider_material_not_publishable');if(!response||response.payloadSchemaStatus!=='valid'||!normalized||normalized.length===0||result.settlementState==='settlement_unconfirmed'||result.settlementState==='settled_unknown_outcome')throw new Error(result.settlementState.startsWith('settlement_')?'provider_settlement_unconfirmed':'invalid_normalized_evidence');const receivedAt=Date.parse(response.receivedAt);if(!Number.isFinite(receivedAt))throw new Error('invalid_normalized_evidence');const authoritativeFreshUntil=result.cacheSnapshot?.freshUntil??receivedAt+policy.staleAfterMs,revision=response.revision??null,identity=buildCanonicalEvidenceIdentity({sourceId:policy.sourceId,capabilityId:policy.capabilityId,asset:policy.asset,region:policy.region,requestFingerprint:buildProviderNormalizedRequestKey(request),policyId:policy.policyId,policyHash:policy.canonicalPolicyHash,policyVersion:policy.policyVersion,evidenceContractVersion:this.evidenceContractVersion,payloadHash:buildCanonicalPayloadHash(normalized),revision,receivedAt:response.receivedAt}),scopeHash=buildMaterializationScopeHash({asset:policy.asset,horizon:policy.horizon,kind:'evidence',sourceId:policy.sourceId,capabilityId:policy.capabilityId,region:policy.region}),previous=await this.repository.readCurrent<CanonicalEvidencePayload>(lease.jobHash,scopeHash),body={schemaVersion:'canonical_materialization_v1'as const,kind:'evidence'as const,identity,scopeHash,payload:{normalizedPayloads:normalized} satisfies CanonicalEvidencePayload,evidenceIdentity:identity,policyVersion:policy.policyVersion,ruleVersions:[this.evidenceContractVersion],schedulerRunId,generatedAt:response.receivedAt,evaluatedAt:new Date(evaluatedAt).toISOString(),freshUntil:new Date(authoritativeFreshUntil).toISOString()},artifact:CanonicalArtifact<CanonicalEvidencePayload>={...body,integrityHash:buildArtifactIntegrityHash(body)};if(!await this.repository.publish(lease,artifact))throw new Error('adaptive_stale_owner_publish_denied');const publishedNewEvidence=previous.artifact?.identity!==identity;if(publishedNewEvidence)this.metrics.canonicalEvidencePublished++;return{artifact,publishedNewEvidence}}
}
