import { createHash, randomUUID } from 'node:crypto';
import { validateKickOffDashboardContextArtifact, validateKickOffDashboardViewModel, validateNormalizedGeopoliticalRiskEvent, validateNormalizedMarketNewsItem } from '@elceo/schemas';
import { cognitionAssetForCanonicalDashboardAsset, type CanonicalAssetSymbol, type DashboardChartWorkspaceViewModel, type InternalKickOffMacroHeadline, type KickOffDashboardContextArtifact, type KickOffDashboardViewModelV1, type MarketCognitionSnapshot } from '@elceo/types';
import type { CanonicalDashboardProjection } from '@elceo/chart-intelligence';
import { DEFAULT_FRESHNESS_POLICIES } from '../evidence-quality/quality-policies';
import type { ResolvedCanonicalReasoningInput } from './production-aggregate';
import type { AdaptiveOwnershipStore, DashboardProjectionArtifact, EvidenceOrCognitionArtifact, MaterializationLease, MaterializationRepository } from './contracts';
import { buildAggregateReasoningInputIdentity, buildArtifactIntegrityHash, buildCanonicalPayloadHash, buildKickOffContextCoordinationHash, buildKickOffContextIdentity, buildMaterializationScopeHash } from './identity';
import { PGS4_PRODUCTION_COGNITION_CONFIGURATION } from './production-cognition';

export const KICK_OFF_CONTEXT_VERSION='kick-off-dashboard-context-v1' as const;
export const KICK_OFF_EVIDENCE_SCORE_POLICY_VERSION='kick-off-evidence-score-v1' as const;
export const KICK_OFF_MACRO_HEADLINE_POLICY_VERSION='kick-off-macro-headlines-v1' as const;
export const KICK_OFF_EVIDENCE_FRESHNESS_POLICY_HASH=buildCanonicalPayloadHash({market_news:DEFAULT_FRESHNESS_POLICIES.market_news,geopolitical_risk:DEFAULT_FRESHNESS_POLICIES.geopolitical_risk});
const opaque=(id:string)=>createHash('sha256').update(`kick-off-headline-v1\0${id}`).digest('hex');
const validIntegrity=(artifact:{integrityHash:string}&Record<string,unknown>)=>{const{integrityHash,...body}=artifact;return integrityHash===buildArtifactIntegrityHash(body)};

function extractHeadlines(aggregate:ResolvedCanonicalReasoningInput):InternalKickOffMacroHeadline[]{
  const weighted=new Map(aggregate.weightedSnapshot.items.filter(item=>item.role!=='excluded'&&item.qualityAdjustedWeight>0).map(item=>[item.payloadId,item]));
  const freshness=new Map(aggregate.reasoningInputSnapshot.items.map(item=>[item.payloadId,item.freshnessStatus]));
  const sourceIdentity=new Map<string,string>();for(const artifact of aggregate.evidenceArtifacts)for(const payload of artifact.payload.normalizedPayloads)sourceIdentity.set(payload.payloadId,artifact.identity);
  const candidates:InternalKickOffMacroHeadline[]=[];
  for(const payload of aggregate.normalizedPayloads){
    const item=weighted.get(payload.payloadId),state=freshness.get(payload.payloadId);if(!item||!['market_news','geopolitical_risk'].includes(item.evidenceClass)||!['fresh','aging'].includes(String(state)))continue;
    let value:unknown;try{value=JSON.parse(payload.valuesJson)}catch{continue}const published=payload.publishedAt;if(!published||Date.parse(published)>Date.parse(aggregate.evaluatedAt))continue;
    if(item.evidenceClass==='market_news'){const checked=validateNormalizedMarketNewsItem(value);if(!checked.ok||checked.value.publishedAt!==published)continue;candidates.push({payload_id:payload.payloadId,evidence_class:'market_news',title:checked.value.title,source_name:checked.value.sourceName,source_url:checked.value.url,published_at:published,freshness:state as 'fresh'|'aging',source_evidence_artifact_identity:sourceIdentity.get(payload.payloadId)!});}
    else{const checked=validateNormalizedGeopoliticalRiskEvent(value);if(!checked.ok||checked.value.publishedAt!==published)continue;candidates.push({payload_id:payload.payloadId,evidence_class:'geopolitical_risk',title:checked.value.title,source_name:null,source_url:checked.value.sourceUrl,published_at:published,freshness:state as 'fresh'|'aging',source_evidence_artifact_identity:sourceIdentity.get(payload.payloadId)!});}
  }
  candidates.sort((a,b)=>b.published_at.localeCompare(a.published_at)||a.payload_id.localeCompare(b.payload_id));const seen=new Set<string>();return candidates.filter(item=>{const key=item.source_url?`url:${item.source_url}`:`exact:${item.source_name}\0${item.title}\0${item.published_at}`;if(seen.has(key))return false;seen.add(key);return true;}).slice(0,3);
}

type ContextBuildInput={asset:CanonicalAssetSymbol;dashboard:DashboardProjectionArtifact<CanonicalDashboardProjection>;cognition:EvidenceOrCognitionArtifact<MarketCognitionSnapshot>&{kind:'cognition'};aggregate:ResolvedCanonicalReasoningInput;evidenceArtifacts:readonly (EvidenceOrCognitionArtifact<unknown>&{kind:'evidence'})[]};
export function buildKickOffDashboardContext(input:ContextBuildInput):KickOffDashboardContextArtifact{
  const{dashboard,cognition,aggregate,evidenceArtifacts}=input,expectedAsset=cognitionAssetForCanonicalDashboardAsset(input.asset),sortedEvidence=[...aggregate.evidenceIdentities].sort();
  if(!validIntegrity(dashboard as never)||!validIntegrity(cognition as never)||evidenceArtifacts.some(artifact=>!validIntegrity(artifact as never)))throw new Error('kick_off_context_parent_integrity_invalid');
  if(dashboard.asset!==input.asset||aggregate.asset!==expectedAsset||aggregate.weightedSnapshot.asset!==expectedAsset||cognition.payload.asset!==expectedAsset||dashboard.horizon!==aggregate.horizon||aggregate.weightedSnapshot.horizon!==aggregate.horizon||cognition.payload.horizon!==aggregate.horizon||dashboard.timeframe!=='H4')throw new Error('kick_off_context_scope_mismatch');
  if(dashboard.parentCognitionArtifactIdentity!==cognition.identity||dashboard.parentCognitionIntegrityHash!==cognition.integrityHash||dashboard.evaluatedAt!==cognition.evaluatedAt||aggregate.evaluatedAt!==cognition.evaluatedAt)throw new Error('kick_off_context_epoch_or_parent_mismatch');
  if(aggregate.weightedSnapshot.snapshotId!==cognition.payload.weightedEvidenceSnapshotId)throw new Error('kick_off_context_weighted_snapshot_mismatch');
  const actualEvidence=evidenceArtifacts.map(artifact=>artifact.identity).sort();if(actualEvidence.join('\0')!==sortedEvidence.join('\0'))throw new Error('kick_off_context_evidence_universe_mismatch');
  const config=PGS4_PRODUCTION_COGNITION_CONFIGURATION,epoch=Date.parse(aggregate.evaluatedAt),reasoningIdentity=buildAggregateReasoningInputIdentity({evidenceIdentities:sortedEvidence,asset:aggregate.asset,horizon:aggregate.horizon,weightingPolicyVersion:config.weightingPolicyVersion,ruleVersions:config.ruleVersions,cognitionContractVersion:config.cognitionContractVersion,freshnessPolicyVersion:config.freshnessPolicyVersion,freshnessMs:config.freshnessMs,evaluationEpochMs:config.evaluationEpochMs,evaluationEpoch:epoch});if(reasoningIdentity!==cognition.evidenceIdentity)throw new Error('kick_off_context_reasoning_identity_mismatch');
  const payload={evidence_score:{value:aggregate.weightedSnapshot.usableWeight,basis:'weighted_evidence_usable_weight' as const},macro_headlines:{items:extractHeadlines(aggregate)}};
  const lineage={contextVersion:KICK_OFF_CONTEXT_VERSION,asset:input.asset,horizon:aggregate.horizon,timeframe:'H4' as const,evaluatedAt:dashboard.evaluatedAt,parentDashboardProjectionIdentity:dashboard.identity,parentDashboardProjectionIntegrityHash:dashboard.integrityHash,parentCognitionArtifactIdentity:cognition.identity,parentCognitionIntegrityHash:cognition.integrityHash,parentReasoningInputIdentity:reasoningIdentity,weightedEvidenceSnapshotId:aggregate.weightedSnapshot.snapshotId,weightedEvidenceContentHash:buildCanonicalPayloadHash(aggregate.weightedSnapshot),parentEvidenceArtifactIdentities:sortedEvidence,evidenceScorePolicyVersion:KICK_OFF_EVIDENCE_SCORE_POLICY_VERSION,macroHeadlinePolicyVersion:KICK_OFF_MACRO_HEADLINE_POLICY_VERSION,evidenceFreshnessPolicyHash:KICK_OFF_EVIDENCE_FRESHNESS_POLICY_HASH,payload};
  const identity=buildKickOffContextIdentity(lineage),freshUntil=new Date(Math.min(Date.parse(dashboard.freshUntil),Date.parse(cognition.freshUntil),...evidenceArtifacts.map(artifact=>Date.parse(artifact.freshUntil)))).toISOString(),body={schemaVersion:'canonical_materialization_v1' as const,kind:'kick_off_dashboard_context' as const,identity,scopeHash:buildMaterializationScopeHash({asset:input.asset,horizon:aggregate.horizon,kind:'kick_off_dashboard_context',timeframe:'H4'}),generatedAt:dashboard.evaluatedAt,freshUntil,...lineage},artifact={...body,integrityHash:buildArtifactIntegrityHash(body)};if(!validateKickOffDashboardContextArtifact(artifact).ok)throw new Error('kick_off_context_artifact_invalid');return artifact;
}

export class CanonicalKickOffContextMaterializationService{
  constructor(private readonly repository:MaterializationRepository,private readonly ownership:AdaptiveOwnershipStore){}
  async materialize(input:{asset:CanonicalAssetSymbol;dashboardArtifactIdentity:string;cognitionArtifactIdentity:string;aggregate:ResolvedCanonicalReasoningInput;leaseDurationMs:number}):Promise<KickOffDashboardContextArtifact>{
    const dashboard=await this.repository.getByIdentity<CanonicalDashboardProjection>(input.dashboardArtifactIdentity),cognition=await this.repository.getByIdentity<MarketCognitionSnapshot>(input.cognitionArtifactIdentity),evidence=await Promise.all(input.aggregate.evidenceIdentities.map(identity=>this.repository.getByIdentity<unknown>(identity)));
    if(!dashboard||dashboard.kind!=='dashboard_projection'||!cognition||cognition.kind!=='cognition'||evidence.some(artifact=>!artifact||artifact.kind!=='evidence'))throw new Error('kick_off_context_direct_parent_missing');
    const artifact=buildKickOffDashboardContext({asset:input.asset,dashboard:dashboard as DashboardProjectionArtifact<CanonicalDashboardProjection>,cognition:cognition as EvidenceOrCognitionArtifact<MarketCognitionSnapshot>&{kind:'cognition'},aggregate:input.aggregate,evidenceArtifacts:evidence as (EvidenceOrCognitionArtifact<unknown>&{kind:'evidence'})[]}),coordination=buildKickOffContextCoordinationHash({asset:input.asset,horizon:input.aggregate.horizon,timeframe:'H4'}),leaseResult=await this.ownership.acquireMaterialization(coordination,artifact.identity,randomUUID(),input.leaseDurationMs);if(leaseResult.acquired===false)throw new Error(leaseResult.reason);const lease:MaterializationLease=leaseResult.lease;try{if(!await this.ownership.isCurrent(lease))throw new Error('kick_off_context_ownership_lost');if(!await this.repository.publish(lease,artifact))throw new Error('kick_off_context_stale_owner_publish_denied');return artifact;}finally{await this.ownership.release(lease);}
  }
}

export function projectKickOffDashboard(workspace:DashboardChartWorkspaceViewModel,artifact:KickOffDashboardContextArtifact|null,input:{asset:CanonicalAssetSymbol;horizon:KickOffDashboardViewModelV1['horizon'];evaluatedAt:string;features?:{evidenceScore:boolean;macroHeadlines:boolean}}):KickOffDashboardViewModelV1{
  const features=input.features??{evidenceScore:true,macroHeadlines:true},base={contract_version:'kick-off-dashboard-v1' as const,access:'kick_off' as const,asset_code:input.asset,timeframe:'H4' as const,horizon:input.horizon,evaluated_at:input.evaluatedAt,chart:{candles:workspace.chart.candles.map(candle=>({...candle})),zones:workspace.chart.zones.map(({zone_id,lower,upper,center})=>({zone_id,lower,upper,center}))}},unavailable={...base,evidence_score:{availability:'unavailable' as const,value:null,scale:'0_100' as const},macro_headlines:{availability:'unavailable' as const,items:[] as []}};
  let result:KickOffDashboardViewModelV1=unavailable;if(artifact){const items=artifact.payload.macro_headlines.items.map(item=>({headline_id:opaque(item.payload_id),title:item.title,source_name:item.source_name,source_url:item.source_url,published_at:item.published_at,freshness:item.freshness}));result={...base,evidence_score:features.evidenceScore?{availability:'available',value:artifact.payload.evidence_score.value,scale:'0_100'}:unavailable.evidence_score,macro_headlines:features.macroHeadlines?(items.length?{availability:'available',items}:{availability:'empty',items:[]}):unavailable.macro_headlines};}
  const checked=validateKickOffDashboardViewModel(result);if(checked.ok===false)throw new Error(`kick_off_public_projection_invalid:${checked.errors.join('|')}`);return checked.value;
}
