import { EVIDENCE_WEIGHT_HORIZONS,TRADING_ASSET_COVERAGE,type EvidenceWeightHorizon,type MarketAssetCausalityAsset,type TradingAssetCoverage,type WeightedEvidenceSnapshot } from '@elceo/types';
import type { NormalizedMarketEvidencePayloadRepository } from '../persistence/market-evidence-ingestion-repository';
import { assembleReasoningEvidenceInputSnapshot } from '../reasoning-input/market-evidence-input-assembler';
import { buildWeightedEvidenceSnapshot } from '../evidence-weighting/weight-calculation';
import type { MaterializationRepository } from './contracts';
export type ProductionEvidenceScope={coordinationHash:string;scopeHash:string};
export class ProductionAggregateInputResolver{constructor(private readonly materializations:MaterializationRepository,private readonly payloads:NormalizedMarketEvidencePayloadRepository,private readonly scopes:(asset:string,horizon:string)=>readonly ProductionEvidenceScope[]){}
 async resolve(asset:string,horizon:string,evaluatedAt:number):Promise<{evidenceIdentities:readonly string[];weightedSnapshot:WeightedEvidenceSnapshot}>{if(!TRADING_ASSET_COVERAGE.includes(asset as TradingAssetCoverage)||!EVIDENCE_WEIGHT_HORIZONS.includes(horizon as EvidenceWeightHorizon))throw new Error('adaptive_cognition_scope_unsupported');const currents=await Promise.all(this.scopes(asset,horizon).map(s=>this.materializations.readCurrent(s.coordinationHash,s.scopeHash))),evidenceIdentities=currents.flatMap(x=>x.artifact?[x.artifact.identity]:[]).sort();if(evidenceIdentities.length===0)throw new Error('canonical_evidence_unavailable');const normalized=await this.payloads.listPayloadsByAsset(asset,200);if(normalized.length===0)throw new Error('reasoning_evidence_unavailable');const generatedAt=new Date(evaluatedAt).toISOString(),input=assembleReasoningEvidenceInputSnapshot({payloads:normalized,generatedAt,asset:asset as TradingAssetCoverage}),weightedSnapshot=buildWeightedEvidenceSnapshot(input,asset as MarketAssetCausalityAsset,horizon as EvidenceWeightHorizon,generatedAt);return{evidenceIdentities,weightedSnapshot}}
}
