import { validateMarketCognitionSnapshot } from '@elceo/schemas';
import type { MarketCognitionSnapshot, WeightedEvidenceSnapshot } from '@elceo/types';
import { buildMarketCognitionSnapshot } from '../market-cognition/market-cognition-builder';
import type { CognitionMaterializationInput, TrustedCognitionConfiguration } from './service';
import { EVIDENCE_WEIGHT_POLICY_VERSION } from '../evidence-weighting/weight-policies';
import { MARKET_COGNITION_BUILDER_VERSION } from '../market-cognition/market-cognition-builder';
import { REASONING_EVIDENCE_FILTER_POLICY_VERSION } from '../reasoning-input/market-evidence-input-policy';
export const MARKET_COGNITION_CONTRACT_VERSION='market-cognition-snapshot-v1' as const,PGS4_COGNITION_FRESHNESS_POLICY_VERSION='pgs4-cognition-freshness-v1' as const;
export const PGS4_PRODUCTION_COGNITION_CONFIGURATION:TrustedCognitionConfiguration={cognitionContractVersion:MARKET_COGNITION_CONTRACT_VERSION,weightingPolicyVersion:EVIDENCE_WEIGHT_POLICY_VERSION,ruleVersions:[MARKET_COGNITION_BUILDER_VERSION,REASONING_EVIDENCE_FILTER_POLICY_VERSION,PGS4_COGNITION_FRESHNESS_POLICY_VERSION],freshnessMs:60_000,validate:payload=>validateMarketCognitionSnapshot(payload).ok};
export type WeightedEvidenceSnapshotLoader=(input:CognitionMaterializationInput)=>Promise<WeightedEvidenceSnapshot>;
export const createProductionCognitionCompute=(load:WeightedEvidenceSnapshotLoader)=>(async(input:CognitionMaterializationInput):Promise<MarketCognitionSnapshot>=>buildMarketCognitionSnapshot(await load(input),new Date(input.evaluatedAt).toISOString()));
