import { EVIDENCE_WEIGHT_HORIZONS,TRADING_ASSET_COVERAGE,type EvidenceWeightHorizon,type MarketAssetCausalityAsset,type NormalizedMarketEvidencePayload,type ReasoningEvidenceInputSnapshot,type TradingAssetCoverage,type WeightedEvidenceSnapshot } from '@elceo/types';
import { assembleReasoningEvidenceInputSnapshot } from '../reasoning-input/market-evidence-input-assembler';
import { REASONING_EVIDENCE_FILTER_POLICY_VERSION } from '../reasoning-input/market-evidence-input-policy';
import { buildWeightedEvidenceSnapshot } from '../evidence-weighting/weight-calculation';
import { EVIDENCE_WEIGHT_POLICY_VERSION } from '../evidence-weighting/weight-policies';
import type { CanonicalArtifact,MaterializationRepository } from './contracts';
import type { CanonicalEvidencePayload } from './evidence';
export type ProductionEvidenceScope={coordinationHash:string;scopeHash:string};
export type ResolvedCanonicalReasoningInput={asset:TradingAssetCoverage;horizon:EvidenceWeightHorizon;evaluatedAt:string;evidenceArtifacts:readonly CanonicalArtifact<CanonicalEvidencePayload>[];evidenceIdentities:readonly string[];normalizedPayloads:readonly NormalizedMarketEvidencePayload[];reasoningInputSnapshot:ReasoningEvidenceInputSnapshot;weightedSnapshot:WeightedEvidenceSnapshot;policyVersions:{reasoningInput:string;evidenceWeighting:string}};
const isEvidenceArtifact=(artifact:CanonicalArtifact<CanonicalEvidencePayload>|null):artifact is CanonicalArtifact<CanonicalEvidencePayload>=>artifact?.kind==='evidence'&&Array.isArray(artifact.payload.normalizedPayloads);
export class ProductionAggregateInputResolver{constructor(private readonly materializations:MaterializationRepository,private readonly scopes:(asset:string,horizon:string)=>readonly ProductionEvidenceScope[]){}
 async resolve(asset:string,horizon:string,evaluatedAt:number):Promise<ResolvedCanonicalReasoningInput>{if(!TRADING_ASSET_COVERAGE.includes(asset as TradingAssetCoverage)||!EVIDENCE_WEIGHT_HORIZONS.includes(horizon as EvidenceWeightHorizon))throw new Error('adaptive_cognition_scope_unsupported');const resolvedAsset=asset as TradingAssetCoverage,resolvedHorizon=horizon as EvidenceWeightHorizon,currents=await Promise.all(this.scopes(asset,horizon).map(s=>this.materializations.readCurrent<CanonicalEvidencePayload>(s.coordinationHash,s.scopeHash))),evidenceArtifacts=currents.map(x=>x.artifact).filter(isEvidenceArtifact).sort((a,b)=>a.identity.localeCompare(b.identity));if(evidenceArtifacts.length===0||evidenceArtifacts.length!==currents.length)throw new Error('canonical_evidence_unavailable');const evidenceIdentities=evidenceArtifacts.map(x=>x.identity),normalizedPayloads=evidenceArtifacts.flatMap(x=>x.payload.normalizedPayloads),generatedAt=new Date(evaluatedAt).toISOString(),reasoningInputSnapshot=assembleReasoningEvidenceInputSnapshot({payloads:[...normalizedPayloads],generatedAt,asset:resolvedAsset}),weightedSnapshot=buildWeightedEvidenceSnapshot(reasoningInputSnapshot,resolvedAsset as MarketAssetCausalityAsset,resolvedHorizon,generatedAt);return Object.freeze({asset:resolvedAsset,horizon:resolvedHorizon,evaluatedAt:generatedAt,evidenceArtifacts,evidenceIdentities,normalizedPayloads,reasoningInputSnapshot,weightedSnapshot,policyVersions:{reasoningInput:REASONING_EVIDENCE_FILTER_POLICY_VERSION,evidenceWeighting:EVIDENCE_WEIGHT_POLICY_VERSION}})}
}
