import type { RedisClientType } from 'redis';
import type { CanonicalArtifactRead } from './contracts';
import { buildCognitionMarketCoordinationHash,buildMaterializationScopeHash } from './identity';
import { buildDashboardProjectionCoordinationHash } from './identity';
import { CANONICAL_DASHBOARD_DISPLAY_VERSION,CANONICAL_DASHBOARD_POLICY_VERSION,CANONICAL_DASHBOARD_PROJECTION_VERSION,CANONICAL_DASHBOARD_ZONE_RULE_VERSION,type CanonicalDashboardProjection } from '@elceo/chart-intelligence';
import { MARKET_COGNITION_CONTRACT_VERSION } from './production-cognition';
import { RedisAdaptiveOwnershipStore } from './redis-store';
import { FencedMaterializationRepository,ReadOptimizedImmutableMaterializationStore,SqlImmutableMaterializationStore,createImmutableReadMetrics } from './repository';

type SqlPool=ConstructorParameters<typeof SqlImmutableMaterializationStore>[0];
export type CanonicalReadMetrics=ReturnType<typeof createImmutableReadMetrics>&{logicalConsumerReads:number;currentPointerReads:number;availableReads:number;staleReads:number;unavailableReads:number};
export type CanonicalCognitionReader={read<T>(asset:string,horizon:string):Promise<CanonicalArtifactRead<T>>;readonly metrics:CanonicalReadMetrics};
/** Read-only composition: deliberately has no scheduler, provider or compute dependency. Clients remain caller-owned. */
export function createProductionCanonicalCognitionReader(input:{redisClient:RedisClientType;sqlPool:SqlPool;cacheLimits:{maxEntries:number;maxSerializedBytes:number};namespace?:string}):CanonicalCognitionReader{const metrics=Object.assign(createImmutableReadMetrics(),{logicalConsumerReads:0,currentPointerReads:0,availableReads:0,staleReads:0,unavailableReads:0}),ownership=new RedisAdaptiveOwnershipStore(input.redisClient,input.namespace),hot=new ReadOptimizedImmutableMaterializationStore(new SqlImmutableMaterializationStore(input.sqlPool),input.cacheLimits,metrics),repository=new FencedMaterializationRepository(ownership,hot);return{metrics,async read<T>(asset:string,horizon:string){metrics.logicalConsumerReads++;metrics.currentPointerReads++;const result=await repository.readCurrent<T>(buildCognitionMarketCoordinationHash({asset,horizon,cognitionContractVersion:MARKET_COGNITION_CONTRACT_VERSION}),buildMaterializationScopeHash({asset,horizon,kind:'cognition'}));if(result.state==='available')metrics.availableReads++;else if(result.state==='stale')metrics.staleReads++;else metrics.unavailableReads++;return result}}}

export type CanonicalDashboardProjectionReader={read(asset:string,horizon:string,timeframe:'H4'):Promise<CanonicalArtifactRead<CanonicalDashboardProjection>>;readonly metrics:CanonicalReadMetrics};
/** Passive D1-B reader. It has no projection, cognition, ingestion, scheduler, or provider execution dependency. */
export function createProductionCanonicalDashboardProjectionReader(input:{redisClient:RedisClientType;sqlPool:SqlPool;cacheLimits:{maxEntries:number;maxSerializedBytes:number};namespace?:string}):CanonicalDashboardProjectionReader{const metrics=Object.assign(createImmutableReadMetrics(),{logicalConsumerReads:0,currentPointerReads:0,availableReads:0,staleReads:0,unavailableReads:0}),ownership=new RedisAdaptiveOwnershipStore(input.redisClient,input.namespace),hot=new ReadOptimizedImmutableMaterializationStore(new SqlImmutableMaterializationStore(input.sqlPool),input.cacheLimits,metrics),repository=new FencedMaterializationRepository(ownership,hot);return{metrics,async read(asset,horizon,timeframe){metrics.logicalConsumerReads++;metrics.currentPointerReads++;const versions={projectionVersion:CANONICAL_DASHBOARD_PROJECTION_VERSION,displayVersion:CANONICAL_DASHBOARD_DISPLAY_VERSION,zoneRuleVersion:CANONICAL_DASHBOARD_ZONE_RULE_VERSION,productPolicyVersion:CANONICAL_DASHBOARD_POLICY_VERSION},result=await repository.readCurrent<CanonicalDashboardProjection>(buildDashboardProjectionCoordinationHash({asset,horizon,timeframe,...versions}),buildMaterializationScopeHash({asset,horizon,kind:'dashboard_projection',timeframe,...versions}));if(result.state==='available')metrics.availableReads++;else if(result.state==='stale')metrics.staleReads++;else metrics.unavailableReads++;return result}}}
