import type { RedisClientType } from 'redis';
import type { NormalizedMarketEvidencePayloadRepository } from '../persistence/market-evidence-ingestion-repository';
import type { MarketCognitionSnapshot } from '@elceo/types';
import type { AdaptiveMaterializationMetrics,ScheduledProviderExecutor,TrustedAdaptiveExecutionContext } from './contracts';
import { RedisAdaptiveOwnershipStore } from './redis-store';
import { FencedMaterializationRepository,SqlImmutableMaterializationStore } from './repository';
import { CanonicalEvidenceMaterializationService } from './evidence';
import { CanonicalCognitionMaterializationService } from './service';
import { AdaptiveMaterializationScheduler } from './scheduler';
import { AdaptiveMaterializationOrchestrator } from './orchestrator';
import { ProductionAggregateInputResolver,type ProductionEvidenceScope } from './production-aggregate';
import { PGS4_PRODUCTION_COGNITION_CONFIGURATION } from './production-cognition';
type SqlPool=ConstructorParameters<typeof SqlImmutableMaterializationStore>[0];
export function createProductionAdaptiveMaterializationRuntime(input:{redisClient:RedisClientType;sqlPool:SqlPool;normalizedPayloads:NormalizedMarketEvidencePayloadRepository;providerGateExecutor:ScheduledProviderExecutor;trustedExecutionContext:TrustedAdaptiveExecutionContext;evidenceScopes:(asset:string,horizon:string)=>readonly ProductionEvidenceScope[];metrics:AdaptiveMaterializationMetrics}){const ownership=new RedisAdaptiveOwnershipStore(input.redisClient),immutable=new SqlImmutableMaterializationStore(input.sqlPool),repository=new FencedMaterializationRepository(ownership,immutable),aggregate=new ProductionAggregateInputResolver(repository,input.normalizedPayloads,input.evidenceScopes),resolved=new Map<string,Awaited<ReturnType<ProductionAggregateInputResolver['resolve']>>>(),key=(asset:string,horizon:string,at:number)=>`${asset}|${horizon}|${at}`,load=async(asset:string,horizon:string,at:number)=>{const k=key(asset,horizon,at),existing=resolved.get(k);if(existing)return existing;const value=await aggregate.resolve(asset,horizon,at);resolved.set(k,value);return value},cognition=new CanonicalCognitionMaterializationService<MarketCognitionSnapshot>(repository,ownership,PGS4_PRODUCTION_COGNITION_CONFIGURATION,async cognitionInput=>{const aggregateInput=await load(cognitionInput.asset,cognitionInput.horizon,cognitionInput.evaluatedAt);return (await import('../market-cognition/market-cognition-builder')).buildMarketCognitionSnapshot(aggregateInput.weightedSnapshot,new Date(cognitionInput.evaluatedAt).toISOString())}),evidence=new CanonicalEvidenceMaterializationService(repository,'normalized-market-evidence-v1',payload=>payload!==null&&typeof payload==='object',input.metrics),scheduler=new AdaptiveMaterializationScheduler(ownership,input.providerGateExecutor,input.trustedExecutionContext,input.metrics),orchestrator=new AdaptiveMaterializationOrchestrator(scheduler,evidence,cognition,async(asset,horizon)=>{const latest=[...resolved.entries()].filter(([k])=>k.startsWith(`${asset}|${horizon}|`)).sort(([a],[b])=>b.localeCompare(a))[0]?.[1];return latest?.evidenceIdentities??(await aggregate.resolve(asset,horizon,Date.now())).evidenceIdentities});return{ownership,immutable,repository,aggregate,evidence,cognition,scheduler,orchestrator}}
