import { createClient, type RedisClientType } from 'redis';
import type { AdaptiveOwnershipStore, LeaseAcquireResult, MaterializationLease } from './contracts';
const ACQUIRE=`local t=redis.call('TIME');local now=tonumber(t[1])*1000+math.floor(tonumber(t[2])/1000);local exp=tonumber(redis.call('HGET',KEYS[1],'expiresAt') or 0);if exp>now then return cjson.encode({ok=false}) end;local gen=redis.call('INCR',KEYS[2]);local expires=now+tonumber(ARGV[2]);redis.call('HSET',KEYS[1],'token',ARGV[1],'generation',gen,'acquiredAt',now,'expiresAt',expires);redis.call('PEXPIRE',KEYS[1],ARGV[2]);redis.call('PEXPIRE',KEYS[2],ARGV[3]);return cjson.encode({ok=true,generation=gen,acquiredAt=now,expiresAt=expires})`;
const RENEW=`local t=redis.call('TIME');local now=tonumber(t[1])*1000+math.floor(tonumber(t[2])/1000);if redis.call('HGET',KEYS[1],'token')~=ARGV[1] or tonumber(redis.call('HGET',KEYS[1],'generation') or -1)~=tonumber(ARGV[2]) or tonumber(redis.call('HGET',KEYS[1],'expiresAt') or 0)<=now then return 0 end;local exp=now+tonumber(ARGV[3]);redis.call('HSET',KEYS[1],'expiresAt',exp);redis.call('PEXPIRE',KEYS[1],ARGV[3]);return exp`;
const CHECK=`local t=redis.call('TIME');local now=tonumber(t[1])*1000+math.floor(tonumber(t[2])/1000);if redis.call('HGET',KEYS[1],'token')==ARGV[1] and tonumber(redis.call('HGET',KEYS[1],'generation') or -1)==tonumber(ARGV[2]) and tonumber(redis.call('HGET',KEYS[1],'expiresAt') or 0)>now then return 1 end;return 0`;
const COMPLETE=`local t=redis.call('TIME');local now=tonumber(t[1])*1000+math.floor(tonumber(t[2])/1000);if redis.call('HGET',KEYS[1],'token')~=ARGV[1] or tonumber(redis.call('HGET',KEYS[1],'generation') or -1)~=tonumber(ARGV[2]) or tonumber(redis.call('HGET',KEYS[1],'expiresAt') or 0)<=now then return 0 end;redis.call('SET',KEYS[2],ARGV[3]);redis.call('DEL',KEYS[1]);return 1`;
const RELEASE=`if redis.call('HGET',KEYS[1],'token')==ARGV[1] and tonumber(redis.call('HGET',KEYS[1],'generation') or -1)==tonumber(ARGV[2]) then return redis.call('DEL',KEYS[1]) end;return 0`;
const keys=(h:string,n:string)=>{const tag=`{${h}}`;return{lease:`${n}:${tag}:lease`,generation:`${n}:${tag}:generation`,due:`${n}:${tag}:due`}};
export const createAdaptiveMaterializationRedisClient=(url=process.env.REDIS_URL):RedisClientType=>{if(!url)throw new Error('adaptive_scheduler_unavailable');const c=createClient({url,socket:{connectTimeout:3000,reconnectStrategy:r=>r<2?100:false}})as RedisClientType;c.on('error',()=>undefined);return c};
export class RedisAdaptiveOwnershipStore implements AdaptiveOwnershipStore { readonly kind='redis'as const; private connecting:Promise<unknown>|null=null; constructor(private client:RedisClientType,private namespace='elceo:adaptive-materialization:v1',private timeoutMs=3000){} private async bounded<T>(p:Promise<T>):Promise<T>{let timer:NodeJS.Timeout;try{return await Promise.race([p,new Promise<T>((_,reject)=>{timer=setTimeout(()=>reject(new Error('adaptive_scheduler_unavailable')),this.timeoutMs)})])}finally{clearTimeout(timer!)}} private async ensure(){if(this.connecting)await this.connecting;if(!this.client.isOpen){this.connecting=this.bounded(this.client.connect()).finally(()=>this.connecting=null);await this.connecting}if(!this.client.isReady)throw new Error('adaptive_scheduler_unavailable')}
 async acquire(jobHash:string,ownerToken:string,leaseMs:number):Promise<LeaseAcquireResult>{try{await this.ensure();const k=keys(jobHash,this.namespace),raw=JSON.parse(String(await this.bounded(this.client.eval(ACQUIRE,{keys:[k.lease,k.generation],arguments:[ownerToken,String(leaseMs),String(leaseMs*1000)]}))))as{ok:boolean;generation?:number;acquiredAt?:number;expiresAt?:number};return raw.ok?{acquired:true,lease:{jobHash,ownerToken,generation:raw.generation!,acquiredAt:raw.acquiredAt!,expiresAt:raw.expiresAt!}}:{acquired:false,reason:'adaptive_scheduler_follower'}}catch{return{acquired:false,reason:'adaptive_scheduler_unavailable'}}}
 async renew(l:MaterializationLease,ms:number){try{await this.ensure();const exp=Number(await this.bounded(this.client.eval(RENEW,{keys:[keys(l.jobHash,this.namespace).lease],arguments:[l.ownerToken,String(l.generation),String(ms)]})));return exp?{...l,expiresAt:exp}:null}catch{return null}} async isCurrent(l:MaterializationLease){try{await this.ensure();return Number(await this.bounded(this.client.eval(CHECK,{keys:[keys(l.jobHash,this.namespace).lease],arguments:[l.ownerToken,String(l.generation)]})))===1}catch{return false}} async complete(l:MaterializationLease,next:number){try{await this.ensure();const k=keys(l.jobHash,this.namespace);return Number(await this.bounded(this.client.eval(COMPLETE,{keys:[k.lease,k.due],arguments:[l.ownerToken,String(l.generation),String(next)]})))===1}catch{return false}} async release(l:MaterializationLease){try{await this.ensure();return Number(await this.bounded(this.client.eval(RELEASE,{keys:[keys(l.jobHash,this.namespace).lease],arguments:[l.ownerToken,String(l.generation)]})))===1}catch{return false}} async close(){if(this.client.isOpen)this.client.destroy()}}
