import { randomUUID } from 'node:crypto';
import type { AdaptiveMaterializationMetrics, AdaptiveMaterializationPolicy, AdaptiveOwnershipStore, CanonicalArtifact, CanonicalArtifactRead, MaterializationRepository } from './contracts';
import { evaluationEpoch } from './cadence';
import { buildAggregateReasoningInputIdentity,buildArtifactIntegrityHash,buildCanonicalCognitionIdentity,buildCognitionMarketCoordinationHash,buildMaterializationScopeHash } from './identity';
export type TrustedCognitionConfiguration={cognitionContractVersion:string;weightingPolicyVersion:string;ruleVersions:readonly string[];freshnessMs:number;validate:(payload:unknown)=>boolean};
export type CognitionMaterializationInput={evidenceIdentities:readonly string[];asset:string;horizon:string;evaluatedAt:number;schedulerRunId:string};
const emptyMetrics=():AdaptiveMaterializationMetrics=>({scheduleEvaluations:0,jobsDue:0,leaseAcquired:0,leaseDenied:0,providerRefreshAttempted:0,providerCacheSatisfied:0,canonicalEvidencePublished:0,cognitionComputed:0,cognitionReused:0,previousMaterializationServed:0,failures:{},nextDueAt:null});
export class CanonicalCognitionMaterializationService<T>{readonly metrics=emptyMetrics();constructor(private readonly repository:MaterializationRepository,private readonly ownership:AdaptiveOwnershipStore,private readonly configuration:TrustedCognitionConfiguration,private readonly compute:(input:CognitionMaterializationInput)=>Promise<T>){}
 async materialize(policy:AdaptiveMaterializationPolicy,input:CognitionMaterializationInput){const epoch=evaluationEpoch(input.evaluatedAt,policy.evaluationEpochMs),reasoningInputIdentity=buildAggregateReasoningInputIdentity({...input,weightingPolicyVersion:this.configuration.weightingPolicyVersion,ruleVersions:this.configuration.ruleVersions,evaluationEpoch:epoch}),identity=buildCanonicalCognitionIdentity({reasoningInputIdentity,asset:input.asset,horizon:input.horizon,weightingPolicyVersion:this.configuration.weightingPolicyVersion,ruleVersions:this.configuration.ruleVersions,evaluationEpoch:epoch}),existing=await this.repository.getByIdentity<T>(identity);if(existing){this.metrics.cognitionReused++;return existing}const coordinationHash=this.coordination(input.asset,input.horizon),acquired=await this.ownership.acquireMaterialization(coordinationHash,identity,randomUUID(),policy.leaseDurationMs);if(!acquired.acquired){for(let i=0;i<20;i++){await new Promise(r=>setTimeout(r,10));const follower=await this.repository.getByIdentity<T>(identity);if(follower){this.metrics.cognitionReused++;return follower}}throw new Error(acquired.reason)}try{const payload=await this.compute(input);if(!this.configuration.validate(payload))throw new Error('invalid_market_cognition_snapshot');this.metrics.cognitionComputed++;const generatedAt=new Date(input.evaluatedAt).toISOString(),body={schemaVersion:'canonical_materialization_v1'as const,kind:'cognition'as const,identity,scopeHash:this.scope(input.asset,input.horizon),payload,evidenceIdentity:reasoningInputIdentity,policyVersion:policy.policyVersion,ruleVersions:[...this.configuration.ruleVersions].sort(),schedulerRunId:input.schedulerRunId,generatedAt,evaluatedAt:new Date(epoch).toISOString(),freshUntil:new Date(input.evaluatedAt+this.configuration.freshnessMs).toISOString()},artifact:CanonicalArtifact<T>={...body,integrityHash:buildArtifactIntegrityHash(body)};if(!await this.repository.publish(acquired.lease,artifact))throw new Error('adaptive_stale_owner_publish_denied');return artifact}finally{await this.ownership.release(acquired.lease)}}
 private coordination(asset:string,horizon:string){return buildCognitionMarketCoordinationHash({asset,horizon,cognitionContractVersion:this.configuration.cognitionContractVersion})}private scope(asset:string,horizon:string){return buildMaterializationScopeHash({asset,horizon,kind:'cognition'})}
 async read(asset:string,horizon:string):Promise<CanonicalArtifactRead<T>>{const result=await this.repository.readCurrent<T>(this.coordination(asset,horizon),this.scope(asset,horizon));if(result.state==='stale')this.metrics.previousMaterializationServed++;return result}}
