import type { ProviderCapabilityKind, ProviderSourceId } from '@elceo/types';

export type CanonicalOfficialLiveState='verified_endpoint'|'credential_required'|'entitlement_required'|'parser_required'|'endpoint_profile_required';
export type CanonicalOfficialSourceContract={
 sourceId:ProviderSourceId;
 gateSourceId:string;
 origin:string;
 transport:'json'|'csv'|'xml'|'sdmx_json'|'sdmx_csv'|'xlsx'|'socrata'|'html_release';
 providerCapability:ProviderCapabilityKind|null;
 requestProfile:string|null;
 liveState:CanonicalOfficialLiveState;
 credentialEnv:string|null;
 endpointPath:string|null;
 notes:string;
};

/**
 * DFC-1 canonical official-source execution contracts.
 * Endpoints and request profiles are server-owned. A contract is not a staging-verification claim.
 * Sources whose exact series/table/profile cannot yet be executed safely remain explicit rather than
 * accepting caller supplied URLs, hosts, data-set identifiers or entitlement substitutions.
 */
export const CANONICAL_OFFICIAL_SOURCE_CONTRACTS:readonly CanonicalOfficialSourceContract[]=[
 {sourceId:'federal_reserve_official',gateSourceId:'federal_reserve',origin:'https://www.federalreserve.gov',transport:'xml',providerCapability:'central_bank_balance_sheet',requestProfile:'h41',liveState:'endpoint_profile_required',credentialEnv:null,endpointPath:'/releases/h41/',notes:'H.4.1 is authoritative; exact automated download profile must be pinned before live execution.'},
 {sourceId:'fred_macro',gateSourceId:'fred',origin:'https://api.stlouisfed.org',transport:'json',providerCapability:'real_yield_series',requestProfile:'DFII10',liveState:'credential_required',credentialEnv:'FRED_API_KEY',endpointPath:'/fred/series/observations',notes:'Existing executable adapter; FRED API key required for live calls.'},
 {sourceId:'us_treasury_official',gateSourceId:'us_treasury',origin:'https://home.treasury.gov',transport:'xml',providerCapability:'nominal_yield_series',requestProfile:'daily_treasury_yield_curve',liveState:'verified_endpoint',credentialEnv:null,endpointPath:'/resource-center/data-chart-center/interest-rates/pages/xml',notes:'Existing executable nominal and real yield adapters.'},
 {sourceId:'bls_official',gateSourceId:'bls_official',origin:'https://api.bls.gov',transport:'json',providerCapability:'macro_indicator_series',requestProfile:'CUUR0000SA0',liveState:'verified_endpoint',credentialEnv:'BLS_API_KEY',endpointPath:'/publicAPI/v2/timeseries/data/',notes:'CPI-U all items is pinned; BLS registration key is optional but supported server-side.'},
 {sourceId:'bea_official',gateSourceId:'bea_official',origin:'https://apps.bea.gov',transport:'json',providerCapability:'growth_activity_indicator',requestProfile:null,liveState:'endpoint_profile_required',credentialEnv:'BEA_API_KEY',endpointPath:'/api/data',notes:'BEA API endpoint is verified; NIPA table/line profile remains fail-closed until pinned from authoritative metadata.'},
 {sourceId:'census_official',gateSourceId:'census_official',origin:'https://api.census.gov',transport:'json',providerCapability:'macro_indicator_series',requestProfile:'eits_mrts',liveState:'credential_required',credentialEnv:'CENSUS_API_KEY',endpointPath:'/data/timeseries/eits/mrts',notes:'Monthly Retail Trade and Food Services endpoint; API key required by current Census API policy.'},
 {sourceId:'cftc_cot',gateSourceId:'cftc_cot',origin:'https://publicreporting.cftc.gov',transport:'socrata',providerCapability:'futures_positioning_report',requestProfile:'gpe5-46if',liveState:'verified_endpoint',credentialEnv:'CFTC_APP_TOKEN',endpointPath:'/api/v3/views/gpe5-46if/query.json',notes:'Traders in Financial Futures Futures Only PRE data set; app token optional but supported.'},
 {sourceId:'sec_edgar',gateSourceId:'sec_edgar',origin:'https://data.sec.gov',transport:'json',providerCapability:'regulatory_filing_reference',requestProfile:null,liveState:'endpoint_profile_required',credentialEnv:null,endpointPath:'/submissions/',notes:'EDGAR submissions API is verified; executable routes require server-owned CIK profiles and SEC-compliant User-Agent.'},
 {sourceId:'ecb_official',gateSourceId:'ecb_public',origin:'https://data-api.ecb.europa.eu',transport:'csv',providerCapability:'policy_rate_series',requestProfile:'deposit_facility',liveState:'verified_endpoint',credentialEnv:null,endpointPath:'/service/data/FM/',notes:'Existing executable adapter using official ECB Data API.'},
 {sourceId:'eurostat_official',gateSourceId:'eurostat_official',origin:'https://ec.europa.eu',transport:'sdmx_json',providerCapability:'inflation_indicator',requestProfile:'prc_hicp_minr',liveState:'verified_endpoint',credentialEnv:null,endpointPath:'/eurostat/api/dissemination/statistics/1.0/data/prc_hicp_minr',notes:'2026 HICP source; supersedes discontinued prc_hicp_midx.'},
 {sourceId:'destatis_official',gateSourceId:'destatis_official',origin:'https://www-genesis.destatis.de',transport:'json',providerCapability:'macro_indicator_series',requestProfile:null,liveState:'credential_required',credentialEnv:'DESTATIS_API_TOKEN',endpointPath:'/genesisWS/rest/2020/data/table',notes:'GENESIS REST endpoint verified; table profile and token remain server-owned.'},
 {sourceId:'boe_official',gateSourceId:'boe_official',origin:'https://www.bankofengland.co.uk',transport:'csv',providerCapability:'policy_rate_series',requestProfile:'IUDBEDR',liveState:'verified_endpoint',credentialEnv:null,endpointPath:'/boeapps/database/_iadb-fromshowcolumns.asp',notes:'IUDBEDR is the official Bank Rate series; CSV parameters are server-owned.'},
 {sourceId:'ons_official',gateSourceId:'ons_official',origin:'https://api.beta.ons.gov.uk',transport:'json',providerCapability:'inflation_indicator',requestProfile:'cpih01',liveState:'endpoint_profile_required',credentialEnv:null,endpointPath:'/v1/datasets/cpih01',notes:'Dataset identity is verified; latest-version resolution requires a controlled two-step contract before live execution.'},
 {sourceId:'uk_dmo_official',gateSourceId:'uk_dmo_official',origin:'https://www.dmo.gov.uk',transport:'csv',providerCapability:'debt_supply_calendar',requestProfile:'D5D',liveState:'endpoint_profile_required',credentialEnv:null,endpointPath:'/data/',notes:'DMO is authoritative for issuance/auction data, not current post-2017 end-of-day gilt yields.'},
 {sourceId:'boj_official',gateSourceId:'boj_public',origin:'https://www.stat-search.boj.or.jp',transport:'json',providerCapability:'policy_rate_series',requestProfile:null,liveState:'endpoint_profile_required',credentialEnv:null,endpointPath:'/api/v1/getDataCode',notes:'BoJ API v1 is live from February 2026; exact policy-rate series code must be pinned from metadata before execution.'},
 {sourceId:'japan_mof_official',gateSourceId:'japan_mof_official',origin:'https://www.mof.go.jp',transport:'csv',providerCapability:'macro_indicator_series',requestProfile:'fx_intervention',liveState:'endpoint_profile_required',credentialEnv:null,endpointPath:'/english/policy/international_policy/reference/feio/',notes:'MOF intervention history is authoritative; direct CSV asset path must be pinned before execution.'},
 {sourceId:'snb_official',gateSourceId:'snb_official',origin:'https://data.snb.ch',transport:'json',providerCapability:'policy_rate_series',requestProfile:'snboffzisa:D0(LZ)',liveState:'verified_endpoint',credentialEnv:null,endpointPath:'/api/cube/snboffzisa/data/json/en',notes:'Official interest-rates cube with SNB policy-rate selection.'},
 {sourceId:'swiss_fso_official',gateSourceId:'swiss_fso_official',origin:'https://www.pxweb.bfs.admin.ch',transport:'json',providerCapability:'macro_indicator_series',requestProfile:null,liveState:'endpoint_profile_required',credentialEnv:null,endpointPath:'/api/v1/en',notes:'PxWeb API is verified; CPI/GDP table path and dimensions must be pinned before execution.'},
 {sourceId:'rba_official',gateSourceId:'rba_official',origin:'https://www.rba.gov.au',transport:'xlsx',providerCapability:'policy_rate_series',requestProfile:'F1.1',liveState:'parser_required',credentialEnv:null,endpointPath:'/statistics/tables/',notes:'Cash-rate history is authoritative in RBA statistical tables; repository has no XLSX parser, so no fake executable state.'},
 {sourceId:'abs_official',gateSourceId:'abs_official',origin:'https://data.api.abs.gov.au',transport:'sdmx_csv',providerCapability:'inflation_indicator',requestProfile:'ABS,CPI,2.0.0/1.10001.10.50.M',liveState:'verified_endpoint',credentialEnv:null,endpointPath:'/rest/data/ABS,CPI,2.0.0/1.10001.10.50.M',notes:'Current ABS Data API host and documented CPI example profile.'},
 {sourceId:'rbnz_official',gateSourceId:'rbnz_official',origin:'https://www.rbnz.govt.nz',transport:'xlsx',providerCapability:'policy_rate_series',requestProfile:'B2',liveState:'parser_required',credentialEnv:null,endpointPath:'/statistics/series/b/b2/',notes:'RBNZ publishes stable statistical XLSX files for automated use; no JSON API is assumed.'},
 {sourceId:'stats_nz_official',gateSourceId:'stats_nz_official',origin:'https://api.stats.govt.nz',transport:'json',providerCapability:'macro_indicator_series',requestProfile:null,liveState:'credential_required',credentialEnv:'STATS_NZ_API_KEY',endpointPath:null,notes:'Aotearoa Data Explorer API requires subscription; exact resource profile remains fail-closed.'},
 {sourceId:'bank_of_canada_official',gateSourceId:'bank_of_canada_official',origin:'https://www.bankofcanada.ca',transport:'json',providerCapability:'policy_rate_series',requestProfile:'V39079',liveState:'verified_endpoint',credentialEnv:null,endpointPath:'/valet/observations/V39079/json',notes:'Valet V39079 is Target for the overnight rate.'},
 {sourceId:'statistics_canada_official',gateSourceId:'statistics_canada_official',origin:'https://www150.statcan.gc.ca',transport:'json',providerCapability:'macro_indicator_series',requestProfile:'18-10-0004-01',liveState:'endpoint_profile_required',credentialEnv:null,endpointPath:'/t1/wds/rest/',notes:'WDS is verified; table 18-10-0004-01 is CPI, but a bounded vector/PID query must be pinned before execution.'},
 {sourceId:'eia_official',gateSourceId:'eia_official',origin:'https://api.eia.gov',transport:'json',providerCapability:'energy_commodity_series',requestProfile:'RWTC',liveState:'credential_required',credentialEnv:'EIA_API_KEY',endpointPath:'/v2/seriesid/RWTC',notes:'WTI Cushing spot series context for CAD; EIA v2 key required.'},
 {sourceId:'imf_official',gateSourceId:'imf_official',origin:'https://www.imf.org',transport:'sdmx_json',providerCapability:'liquidity_conditions_indicator',requestProfile:null,liveState:'endpoint_profile_required',credentialEnv:null,endpointPath:null,notes:'IMF SDMX APIs are canonical, but current public host/dataflow must be pinned before execution.'},
 {sourceId:'world_bank_official',gateSourceId:'world_bank_official',origin:'https://api.worldbank.org',transport:'json',providerCapability:'growth_activity_indicator',requestProfile:'WLD:NY.GDP.MKTP.CD',liveState:'verified_endpoint',credentialEnv:null,endpointPath:'/v2/country/WLD/indicator/NY.GDP.MKTP.CD',notes:'World aggregate GDP context; no API key required.'},
 {sourceId:'oecd_official',gateSourceId:'oecd_official',origin:'https://sdmx.oecd.org',transport:'sdmx_csv',providerCapability:'growth_activity_indicator',requestProfile:'OECD.SDD.STES:DSD_STES@DF_CLI',liveState:'endpoint_profile_required',credentialEnv:null,endpointPath:'/public/rest/data/OECD.SDD.STES,DSD_STES@DF_CLI/',notes:'CLI dataflow is verified; bounded geography/measure key must be pinned before execution.'},
 {sourceId:'bis_official',gateSourceId:'bis_official',origin:'https://stats.bis.org',transport:'sdmx_csv',providerCapability:'cross_market_rate_series',requestProfile:null,liveState:'endpoint_profile_required',credentialEnv:null,endpointPath:'/api/v2/data/',notes:'BIS SDMX 2.1 API is canonical; exact cross-market dataflow/key must be pinned before execution.'},
 {sourceId:'cboe_official',gateSourceId:'cboe_official',origin:'https://cdn.cboe.com',transport:'csv',providerCapability:null,requestProfile:'VIX',liveState:'entitlement_required',credentialEnv:null,endpointPath:null,notes:'Direct VIX authority remains entitlement/legal blocked; futures/ETPs cannot satisfy direct-index authority.'},
 {sourceId:'ice_data_indices',gateSourceId:'ice_data_indices',origin:'https://www.ice.com',transport:'json',providerCapability:null,requestProfile:'DXY',liveState:'entitlement_required',credentialEnv:null,endpointPath:null,notes:'Direct ICE U.S. Dollar Index authority remains entitlement/legal blocked; DX/UUP/reconstruction are not direct substitutes.'}
] as const;

const bySource=new Map(CANONICAL_OFFICIAL_SOURCE_CONTRACTS.map(contract=>[contract.sourceId,contract]));
export const getCanonicalOfficialSourceContract=(sourceId:ProviderSourceId)=>bySource.get(sourceId)??null;
export const listCanonicalOfficialSourceContracts=()=>[...CANONICAL_OFFICIAL_SOURCE_CONTRACTS];
