import type { ProviderCapabilityKind } from '@elceo/types';

export type OfficialHttpMethod='GET'|'POST';
export type OfficialResponseShape='json'|'csv'|'xml'|'html'|'xlsx'|'sdmx_csv'|'sdmx_json';
export type OfficialExecutionState='http_executable'|'parser_only'|'blocked_entitlement'|'blocked_profile';
export type OfficialSourceContract={canonicalSourceId:string;gateSourceId:string;capability:ProviderCapabilityKind;origin:string;method:OfficialHttpMethod;path:string;responseShape:OfficialResponseShape;credential:'none'|'api_key'|'subscription_key'|'user_agent'|'entitlement';requestProfileId:string;executionState:OfficialExecutionState;freshness:'intraday'|'daily'|'weekly'|'monthly'|'quarterly'|'release_aware';notes:string};

/**
 * Capability-level execution projection of the canonical official-source registry.
 * `http_executable` means the source-specific request profile and parser contract are pinned; it does not claim
 * staging verification or production eligibility. Profile/parser/entitlement dependencies remain fail-closed.
 */
export const CANONICAL_OFFICIAL_SOURCE_CONTRACTS:readonly OfficialSourceContract[]=[
 {canonicalSourceId:'federal_reserve_official',gateSourceId:'federal_reserve',capability:'central_bank_balance_sheet',origin:'https://www.federalreserve.gov',method:'GET',path:'/releases/h41/current/',responseShape:'html',credential:'none',requestProfileId:'H41:H41/RESPPA_N.WW',executionState:'http_executable',freshness:'weekly',notes:'Current H.4.1 release; parse consolidated Total assets only. Retiring BYP is not used.'},
 {canonicalSourceId:'bls_official',gateSourceId:'bls_official',capability:'inflation_indicator',origin:'https://api.bls.gov',method:'POST',path:'/publicAPI/v2/timeseries/data/',responseShape:'json',credential:'api_key',requestProfileId:'CUSR0000SA0',executionState:'http_executable',freshness:'release_aware',notes:'BLS CPI-U all items, seasonally adjusted.'},
 {canonicalSourceId:'bls_official',gateSourceId:'bls_official',capability:'labor_market_indicator',origin:'https://api.bls.gov',method:'POST',path:'/publicAPI/v2/timeseries/data/',responseShape:'json',credential:'api_key',requestProfileId:'LNS14000000',executionState:'http_executable',freshness:'release_aware',notes:'BLS unemployment rate.'},
 {canonicalSourceId:'bea_official',gateSourceId:'bea_official',capability:'growth_activity_indicator',origin:'https://apps.bea.gov',method:'GET',path:'/api/data/',responseShape:'json',credential:'api_key',requestProfileId:'NIPA:T10101:Q',executionState:'http_executable',freshness:'release_aware',notes:'BEA NIPA table T10101 quarterly GDP profile.'},
 {canonicalSourceId:'census_official',gateSourceId:'census_official',capability:'growth_activity_indicator',origin:'https://api.census.gov',method:'GET',path:'/data/timeseries/eits/mrts',responseShape:'json',credential:'api_key',requestProfileId:'EITS:MRTS',executionState:'http_executable',freshness:'release_aware',notes:'Census Economic Indicators monthly retail trade profile.'},
 {canonicalSourceId:'cftc_cot',gateSourceId:'cftc_cot',capability:'cot_report',origin:'https://publicreporting.cftc.gov',method:'GET',path:'/api/v3/views/6dca-aqww/query.json',responseShape:'json',credential:'api_key',requestProfileId:'6dca-aqww:legacy_futures_only',executionState:'http_executable',freshness:'weekly',notes:'CFTC Public Reporting Legacy - Futures Only SODA v3 dataset; optional app token is supported server-side.'},
 {canonicalSourceId:'sec_edgar',gateSourceId:'sec_edgar',capability:'regulatory_filing_reference',origin:'https://data.sec.gov',method:'GET',path:'/submissions/CIK{server_owned_cik}.json',responseShape:'json',credential:'user_agent',requestProfileId:'company_submissions',executionState:'blocked_profile',freshness:'release_aware',notes:'EDGAR filings/XBRL only. A bounded CIK/use-case profile and descriptive User-Agent are required; no fabricated daily ETF-flow capability.'},
 {canonicalSourceId:'ecb_official',gateSourceId:'ecb_public',capability:'policy_rate_series',origin:'https://data-api.ecb.europa.eu',method:'GET',path:'/service/data/FM/{server_owned_key}',responseShape:'csv',credential:'none',requestProfileId:'deposit_facility',executionState:'http_executable',freshness:'daily',notes:'ECB deposit-facility profile.'},
 {canonicalSourceId:'us_treasury_official',gateSourceId:'us_treasury',capability:'nominal_yield_series',origin:'https://home.treasury.gov',method:'GET',path:'/resource-center/data-chart-center/interest-rates/pages/xml',responseShape:'xml',credential:'none',requestProfileId:'daily_treasury_yield_curve',executionState:'http_executable',freshness:'daily',notes:'Official nominal Treasury curve.'},
 {canonicalSourceId:'us_treasury_official',gateSourceId:'us_treasury',capability:'real_yield_series',origin:'https://home.treasury.gov',method:'GET',path:'/resource-center/data-chart-center/interest-rates/pages/xml',responseShape:'xml',credential:'none',requestProfileId:'daily_treasury_real_yield_curve',executionState:'http_executable',freshness:'daily',notes:'Official real Treasury curve.'},
 {canonicalSourceId:'fred_macro',gateSourceId:'fred',capability:'real_yield_series',origin:'https://api.stlouisfed.org',method:'GET',path:'/fred/series/observations',responseShape:'json',credential:'api_key',requestProfileId:'DFII10',executionState:'http_executable',freshness:'daily',notes:'FRED 10-year TIPS real-yield confirmation.'},
 {canonicalSourceId:'fred_macro',gateSourceId:'fred',capability:'financial_conditions_index',origin:'https://api.stlouisfed.org',method:'GET',path:'/fred/series/observations',responseShape:'json',credential:'api_key',requestProfileId:'NFCI',executionState:'http_executable',freshness:'weekly',notes:'Chicago Fed NFCI through FRED.'},
 {canonicalSourceId:'eurostat_official',gateSourceId:'eurostat_official',capability:'inflation_indicator',origin:'https://ec.europa.eu',method:'GET',path:'/eurostat/api/dissemination/sdmx/3.0/data/dataflow/ESTAT/prc_hicp_minr/1.0',responseShape:'sdmx_csv',credential:'none',requestProfileId:'prc_hicp_minr:M:RCH_A:TOTAL:EA21',executionState:'http_executable',freshness:'release_aware',notes:'HICP monthly annual rate; use component filters rather than positional dimension assumptions.'},
 {canonicalSourceId:'destatis_official',gateSourceId:'destatis_official',capability:'inflation_indicator',origin:'https://www-genesis.destatis.de',method:'POST',path:'/genesisWS/rest/2020/data/table',responseShape:'json',credential:'api_key',requestProfileId:'61111-0002',executionState:'blocked_profile',freshness:'release_aware',notes:'GENESIS current transport is POST. CPI table is pinned; exact token/header execution profile remains fail-closed.'},
 {canonicalSourceId:'boe_official',gateSourceId:'boe_official',capability:'policy_rate_series',origin:'https://www.bankofengland.co.uk',method:'GET',path:'/boeapps/database/_iadb-fromshowcolumns.asp',responseShape:'csv',credential:'none',requestProfileId:'IUDBEDR',executionState:'http_executable',freshness:'daily',notes:'Official Bank Rate IUDBEDR.'},
 {canonicalSourceId:'ons_official',gateSourceId:'ons_official',capability:'inflation_indicator',origin:'https://www.ons.gov.uk',method:'GET',path:'/generator?format=csv&uri=%2Feconomy%2Finflationandpriceindices%2Ftimeseries%2Fl55o%2Fmm23',responseShape:'csv',credential:'none',requestProfileId:'L55O:CPIH_ALL_ITEMS_ANNUAL_RATE',executionState:'http_executable',freshness:'release_aware',notes:'Direct CPIH All Items annual-rate series L55O.'},
 {canonicalSourceId:'uk_dmo_official',gateSourceId:'uk_dmo_official',capability:'debt_supply_calendar',origin:'https://www.dmo.gov.uk',method:'GET',path:'/data/pdfdatareport?reportCode=D5D',responseShape:'html',credential:'none',requestProfileId:'D5D:OUTRIGHT_GILT_ISSUANCE',executionState:'blocked_profile',freshness:'release_aware',notes:'Official gilt issuance/debt-supply authority only. Deterministic machine export remains unpinned; never a live gilt-yield source.'},
 {canonicalSourceId:'boj_official',gateSourceId:'boj_public',capability:'policy_rate_series',origin:'https://www.stat-search.boj.or.jp',method:'GET',path:'/api/v1/getDataCode',responseShape:'json',credential:'none',requestProfileId:'FM01:STRDCLUCON',executionState:'http_executable',freshness:'daily',notes:'BoJ Time-Series Data Search API; uncollateralized overnight call-rate series.'},
 {canonicalSourceId:'japan_mof_official',gateSourceId:'japan_mof_official',capability:'macro_indicator_series',origin:'https://www.mof.go.jp',method:'GET',path:'/english/policy/international_policy/reference/feio/index.html',responseShape:'html',credential:'none',requestProfileId:'FX_INTERVENTION_RELEASE_INDEX',executionState:'parser_only',freshness:'release_aware',notes:'Official intervention release index; follow first-party release/file links instead of inventing an API.'},
 {canonicalSourceId:'snb_official',gateSourceId:'snb_official',capability:'policy_rate_series',origin:'https://data.snb.ch',method:'GET',path:'/api/cube/snboffzisa/data/csv/en',responseShape:'csv',credential:'none',requestProfileId:'snboffzisa:D0(LZ)',executionState:'http_executable',freshness:'daily',notes:'SNB official-interest-rate cube with D0(LZ) policy-rate selection.'},
 {canonicalSourceId:'swiss_fso_official',gateSourceId:'swiss_fso_official',capability:'inflation_indicator',origin:'https://disseminate.stats.swiss',method:'GET',path:'/rest/dataflow/all/all/latest',responseShape:'sdmx_json',credential:'none',requestProfileId:'CPI_DATAFLOW_DISCOVERY',executionState:'blocked_profile',freshness:'release_aware',notes:'Current Swiss Stats Explorer SDMX catalogue. Exact national CPI dataflow remains deliberately unpinned; official release assets are the first-party fallback.'},
 {canonicalSourceId:'rba_official',gateSourceId:'rba_official',capability:'policy_rate_series',origin:'https://www.rba.gov.au',method:'GET',path:'/statistics/cash-rate/',responseShape:'html',credential:'none',requestProfileId:'cash_rate_target',executionState:'http_executable',freshness:'release_aware',notes:'Official cash-rate target history.'},
 {canonicalSourceId:'abs_official',gateSourceId:'abs_official',capability:'inflation_indicator',origin:'https://data.api.abs.gov.au',method:'GET',path:'/rest/data/ABS,CPI,2.0.0/1.10001.10.50.M?format=csvfilewithlabels',responseShape:'sdmx_csv',credential:'none',requestProfileId:'ABS,CPI,2.0.0/1.10001.10.50.M',executionState:'http_executable',freshness:'release_aware',notes:'ABS documented CPI series profile.'},
 {canonicalSourceId:'rbnz_official',gateSourceId:'rbnz_official',capability:'policy_rate_series',origin:'https://www.rbnz.govt.nz',method:'GET',path:'/monetary-policy/monetary-policy-decisions',responseShape:'html',credential:'none',requestProfileId:'OCR_DECISION_HISTORY',executionState:'http_executable',freshness:'release_aware',notes:'Official OCR decision history.'},
 {canonicalSourceId:'stats_nz_official',gateSourceId:'stats_nz_official',capability:'inflation_indicator',origin:'https://www.stats.govt.nz',method:'GET',path:'/information-releases/',responseShape:'csv',credential:'none',requestProfileId:'CPI_INFORMATION_RELEASE_ATTACHMENT',executionState:'blocked_profile',freshness:'quarterly',notes:'CPI information releases plus first-party CSV attachments. Rolling attachment resolver remains fail-closed; no undocumented ADE dataset ID or monthly cadence.'},
 {canonicalSourceId:'bank_of_canada_official',gateSourceId:'bank_of_canada_official',capability:'policy_rate_series',origin:'https://www.bankofcanada.ca',method:'GET',path:'/valet/observations/V39079/json',responseShape:'json',credential:'none',requestProfileId:'V39079',executionState:'http_executable',freshness:'daily',notes:'Target for the overnight rate.'},
 {canonicalSourceId:'statistics_canada_official',gateSourceId:'statistics_canada_official',capability:'macro_indicator_series',origin:'https://www150.statcan.gc.ca',method:'GET',path:'/t1/wds/rest/getDataFromVectorByReferencePeriodRange',responseShape:'json',credential:'none',requestProfileId:'vector:41690973',executionState:'http_executable',freshness:'release_aware',notes:'Bounded CPI vector profile.'},
 {canonicalSourceId:'eia_official',gateSourceId:'eia_official',capability:'energy_commodity_series',origin:'https://api.eia.gov',method:'GET',path:'/v2/petroleum/pri/spt/data/',responseShape:'json',credential:'api_key',requestProfileId:'RWTC',executionState:'http_executable',freshness:'daily',notes:'WTI spot-price profile.'},
 {canonicalSourceId:'imf_official',gateSourceId:'imf_official',capability:'liquidity_conditions_indicator',origin:'https://data.imf.org',method:'GET',path:'/',responseShape:'sdmx_json',credential:'none',requestProfileId:'IL:INTERNATIONAL_LIQUIDITY',executionState:'blocked_profile',freshness:'release_aware',notes:'International Liquidity is the correct ELCEO global-liquidity dataset; current operational API contract is account-gated, so broad money and legacy endpoint substitutions are forbidden.'},
 {canonicalSourceId:'world_bank_official',gateSourceId:'world_bank_official',capability:'growth_activity_indicator',origin:'https://api.worldbank.org',method:'GET',path:'/v2/country/WLD/indicator/NY.GDP.MKTP.KD.ZG',responseShape:'json',credential:'none',requestProfileId:'NY.GDP.MKTP.KD.ZG',executionState:'http_executable',freshness:'release_aware',notes:'World real-GDP growth indicator.'},
 {canonicalSourceId:'oecd_official',gateSourceId:'oecd_official',capability:'growth_activity_indicator',origin:'https://sdmx.oecd.org',method:'GET',path:'/public/rest/data/OECD.SDD.STES,DSD_STES@DF_CLI,4.1/G20.M.LI...AA...H',responseShape:'sdmx_csv',credential:'none',requestProfileId:'OECD.SDD.STES,DSD_STES@DF_CLI,4.1:G20.M.LI...AA...H',executionState:'http_executable',freshness:'monthly',notes:'G20 monthly Composite Leading Indicator, amplitude adjusted, OECD harmonised.'},
 {canonicalSourceId:'bis_official',gateSourceId:'bis_official',capability:'cross_market_rate_series',origin:'https://stats.bis.org',method:'GET',path:'/api/v1/data/WS_CBPOL/{server_owned_key}/all',responseShape:'sdmx_json',credential:'none',requestProfileId:'BIS,WS_CBPOL,1.0',executionState:'blocked_profile',freshness:'daily',notes:'Central-bank-policy-rate flow is pinned. Bounded multi-currency key/fan-out remains fail-closed until empirically validated; no unbounded pull.'},
 {canonicalSourceId:'cboe_official',gateSourceId:'cboe_official',capability:'end_of_day_prices',origin:'https://cdn.cboe.com',method:'GET',path:'/api/global/us_indices/daily_prices/VIX_History.csv',responseShape:'csv',credential:'none',requestProfileId:'VIX:EOD_DIRECT_INDEX',executionState:'http_executable',freshness:'daily',notes:'Public authoritative VIX historical/EOD direct-index series. Realtime VIX is a separate licensed route; futures/ETPs do not satisfy it.'},
 {canonicalSourceId:'ice_data_indices',gateSourceId:'ice_data_indices',capability:'end_of_day_prices',origin:'https://www.ice.com',method:'GET',path:'/',responseShape:'json',credential:'entitlement',requestProfileId:'DXY:DIRECT_INDEX',executionState:'blocked_entitlement',freshness:'intraday',notes:'ICE direct DXY authority. Licensed API operation/schema is not public; DX futures/UUP/reconstructed baskets never satisfy this contract.'}
] as const;

export const listExecutableOfficialSourceContracts=()=>CANONICAL_OFFICIAL_SOURCE_CONTRACTS.filter(x=>x.executionState==='http_executable');
export const getOfficialSourceContract=(gateSourceId:string,capability:ProviderCapabilityKind)=>CANONICAL_OFFICIAL_SOURCE_CONTRACTS.find(x=>x.gateSourceId===gateSourceId&&x.capability===capability)??null;
