import type { ProviderCapabilityKind } from '@elceo/types';

export type OfficialHttpMethod='GET'|'POST';
export type OfficialResponseShape='json'|'csv'|'xml'|'html'|'xlsx'|'sdmx_csv'|'sdmx_json';
export type OfficialExecutionState='http_executable'|'parser_only'|'blocked_entitlement'|'blocked_profile';
export type OfficialSourceContract={
 canonicalSourceId:string;
 gateSourceId:string;
 capability:ProviderCapabilityKind;
 origin:string;
 method:OfficialHttpMethod;
 path:string;
 responseShape:OfficialResponseShape;
 credential:'none'|'api_key'|'subscription_key'|'user_agent'|'entitlement';
 requestProfileId:string;
 executionState:OfficialExecutionState;
 freshness:'intraday'|'daily'|'weekly'|'monthly'|'quarterly'|'release_aware';
 notes:string;
};

/**
 * Server-owned official-source contracts for DFC-1. Paths and profiles are intentionally immutable.
 * A contract being present is not staging verification. `blocked_profile` means an official interface exists,
 * but ELCEO has not yet pinned a sufficiently narrow series/table/dataflow profile for live execution.
 */
export const CANONICAL_OFFICIAL_SOURCE_CONTRACTS:readonly OfficialSourceContract[]=[
 {canonicalSourceId:'federal_reserve_official',gateSourceId:'federal_reserve',capability:'central_bank_balance_sheet',origin:'https://www.federalreserve.gov',method:'GET',path:'/datadownload/Choose.aspx?rel=H41',responseShape:'html',credential:'none',requestProfileId:'h41_release_index',executionState:'parser_only',freshness:'weekly',notes:'Federal Reserve H.4.1 release authority. DDP BYP is being retired; live series extraction remains fail-closed until the replacement XML/FRED handoff profile is pinned.'},
 {canonicalSourceId:'bls_official',gateSourceId:'bls_official',capability:'inflation_indicator',origin:'https://api.bls.gov',method:'POST',path:'/publicAPI/v2/timeseries/data/',responseShape:'json',credential:'api_key',requestProfileId:'CUSR0000SA0',executionState:'http_executable',freshness:'release_aware',notes:'BLS Public Data API v2 CPI-U all items, seasonally adjusted. Registration key is server-owned.'},
 {canonicalSourceId:'bls_official',gateSourceId:'bls_official',capability:'labor_market_indicator',origin:'https://api.bls.gov',method:'POST',path:'/publicAPI/v2/timeseries/data/',responseShape:'json',credential:'api_key',requestProfileId:'LNS14000000',executionState:'http_executable',freshness:'release_aware',notes:'BLS Public Data API v2 unemployment rate profile.'},
 {canonicalSourceId:'bea_official',gateSourceId:'bea_official',capability:'growth_activity_indicator',origin:'https://apps.bea.gov',method:'GET',path:'/api/data/',responseShape:'json',credential:'api_key',requestProfileId:'NIPA:T10101:Q',executionState:'http_executable',freshness:'release_aware',notes:'BEA NIPA table T10101 quarterly GDP profile using GetData.'},
 {canonicalSourceId:'census_official',gateSourceId:'census_official',capability:'growth_activity_indicator',origin:'https://api.census.gov',method:'GET',path:'/data/timeseries/eits/mrts',responseShape:'json',credential:'api_key',requestProfileId:'mrts_retail_sales',executionState:'http_executable',freshness:'release_aware',notes:'Census Economic Indicators Time Series monthly retail trade profile.'},
 {canonicalSourceId:'cftc_cot',gateSourceId:'cftc_cot',capability:'cot_report',origin:'https://publicreporting.cftc.gov',method:'GET',path:'/resource/jun7-fc8e.json',responseShape:'json',credential:'none',requestProfileId:'legacy_futures_only_cot',executionState:'http_executable',freshness:'weekly',notes:'CFTC Public Reporting Socrata legacy futures-only COT dataset. Existing ELCEO COT normalizer remains authoritative for cognition.'},
 {canonicalSourceId:'sec_edgar',gateSourceId:'sec_edgar',capability:'regulatory_filing_reference',origin:'https://data.sec.gov',method:'GET',path:'/submissions/CIK{cik}.json',responseShape:'json',credential:'user_agent',requestProfileId:'company_submissions',executionState:'http_executable',freshness:'release_aware',notes:'SEC EDGAR submissions API. CIK is server-validated; descriptive User-Agent is mandatory.'},
 {canonicalSourceId:'eurostat_official',gateSourceId:'eurostat_official',capability:'inflation_indicator',origin:'https://ec.europa.eu',method:'GET',path:'/eurostat/api/dissemination/sdmx/3.0/data/dataflow/ESTAT/PRC_HICP_MINR/1.0',responseShape:'sdmx_csv',credential:'none',requestProfileId:'prc_hicp_minr',executionState:'http_executable',freshness:'release_aware',notes:'Eurostat SDMX 3.0 HICP monthly-rates dataflow; ELCEO requests bounded dimensions and CSV.'},
 {canonicalSourceId:'destatis_official',gateSourceId:'destatis_official',capability:'inflation_indicator',origin:'https://www-genesis.destatis.de',method:'GET',path:'/genesisWS/rest/2020/data/table',responseShape:'json',credential:'api_key',requestProfileId:'61111_cpi',executionState:'blocked_profile',freshness:'release_aware',notes:'GENESIS Webservice is official but exact CPI table/filter contract must be confirmed before live activation.'},
 {canonicalSourceId:'boe_official',gateSourceId:'boe_official',capability:'policy_rate_series',origin:'https://www.bankofengland.co.uk',method:'GET',path:'/boeapps/database/_iadb-fromshowcolumns.asp',responseShape:'csv',credential:'none',requestProfileId:'IUDBEDR',executionState:'http_executable',freshness:'daily',notes:'Bank of England IADB CSV, Official Bank Rate series IUDBEDR.'},
 {canonicalSourceId:'ons_official',gateSourceId:'ons_official',capability:'inflation_indicator',origin:'https://api.beta.ons.gov.uk',method:'GET',path:'/v1/datasets/cpih01',responseShape:'json',credential:'none',requestProfileId:'cpih01_latest',executionState:'http_executable',freshness:'release_aware',notes:'ONS beta API dataset/version discovery for CPIH; version and observation dimensions remain server-owned.'},
 {canonicalSourceId:'uk_dmo_official',gateSourceId:'uk_dmo_official',capability:'debt_supply_calendar',origin:'https://www.dmo.gov.uk',method:'GET',path:'/data/',responseShape:'csv',credential:'none',requestProfileId:'issuance_calendar',executionState:'blocked_profile',freshness:'release_aware',notes:'UK DMO is the issuance/auction authority. No market-yield authority is inferred; exact machine-download path must be pinned before live execution.'},
 {canonicalSourceId:'boj_official',gateSourceId:'boj_public',capability:'policy_rate_series',origin:'https://www.stat-search.boj.or.jp',method:'GET',path:'/ssi/cgi-bin/famecgi2',responseShape:'json',credential:'none',requestProfileId:'boj_timeseries_api_policy',executionState:'blocked_profile',freshness:'release_aware',notes:'BOJ Time-Series Data Search API launched February 2026. Live execution remains blocked until the API manual series-code/profile contract is pinned exactly.'},
 {canonicalSourceId:'japan_mof_official',gateSourceId:'japan_mof_official',capability:'macro_indicator_series',origin:'https://www.mof.go.jp',method:'GET',path:'/english/policy/international_policy/reference/feio/index.html',responseShape:'html',credential:'none',requestProfileId:'fx_intervention_release_index',executionState:'parser_only',freshness:'release_aware',notes:'Japan MOF official FX intervention release index; historical CSV exists but exact current file URL is release-derived and therefore not caller controlled.'},
 {canonicalSourceId:'snb_official',gateSourceId:'snb_official',capability:'policy_rate_series',origin:'https://data.snb.ch',method:'GET',path:'/api/cube/',responseShape:'json',credential:'none',requestProfileId:'policy_rate_cube',executionState:'blocked_profile',freshness:'daily',notes:'SNB data portal exposes cube JSON API. Exact policy-rate cube/dimensions must be pinned before live activation.'},
 {canonicalSourceId:'swiss_fso_official',gateSourceId:'swiss_fso_official',capability:'macro_indicator_series',origin:'https://www.pxweb.bfs.admin.ch',method:'POST',path:'/api/v1/en/',responseShape:'json',credential:'none',requestProfileId:'stat_tab_macro_table',executionState:'blocked_profile',freshness:'release_aware',notes:'Swiss FSO STAT-TAB PxWeb API. Exact table and dimension selections are server-owned and must be pinned before live activation.'},
 {canonicalSourceId:'rba_official',gateSourceId:'rba_official',capability:'policy_rate_series',origin:'https://www.rba.gov.au',method:'GET',path:'/statistics/cash-rate/',responseShape:'html',credential:'none',requestProfileId:'cash_rate_target',executionState:'http_executable',freshness:'release_aware',notes:'RBA official cash-rate target HTML table used instead of adding an XLSX parser dependency.'},
 {canonicalSourceId:'abs_official',gateSourceId:'abs_official',capability:'macro_indicator_series',origin:'https://data.api.abs.gov.au',method:'GET',path:'/rest/data/',responseShape:'sdmx_csv',credential:'none',requestProfileId:'abs_macro_dataflow',executionState:'blocked_profile',freshness:'release_aware',notes:'ABS SDMX REST API is public with no API key. Exact macro dataflows/dimension keys are pinned per indicator before activation.'},
 {canonicalSourceId:'rbnz_official',gateSourceId:'rbnz_official',capability:'policy_rate_series',origin:'https://www.rbnz.govt.nz',method:'GET',path:'/monetary-policy/monetary-policy-decisions',responseShape:'html',credential:'none',requestProfileId:'ocr_decision_history',executionState:'http_executable',freshness:'release_aware',notes:'RBNZ official OCR decision history HTML table; avoids synthetic JSON and XLSX dependency.'},
 {canonicalSourceId:'stats_nz_official',gateSourceId:'stats_nz_official',capability:'macro_indicator_series',origin:'https://api.stats.govt.nz',method:'GET',path:'/',responseShape:'json',credential:'subscription_key',requestProfileId:'aotearoa_data_explorer',executionState:'blocked_profile',freshness:'release_aware',notes:'Stats NZ Aotearoa Data Explorer requires subscription. Exact product route/profile remains fail-closed until pinned with credentials.'},
 {canonicalSourceId:'bank_of_canada_official',gateSourceId:'bank_of_canada_official',capability:'policy_rate_series',origin:'https://www.bankofcanada.ca',method:'GET',path:'/valet/observations/V39079/json',responseShape:'json',credential:'none',requestProfileId:'V39079',executionState:'http_executable',freshness:'daily',notes:'Bank of Canada Valet target for overnight rate series V39079.'},
 {canonicalSourceId:'statistics_canada_official',gateSourceId:'statistics_canada_official',capability:'macro_indicator_series',origin:'https://www150.statcan.gc.ca',method:'GET',path:'/t1/wds/rest/getDataFromVectorByReferencePeriodRange',responseShape:'json',credential:'none',requestProfileId:'bounded_vector_range',executionState:'http_executable',freshness:'release_aware',notes:'Statistics Canada WDS bounded vector/date-range method; vector IDs are server-owned.'},
 {canonicalSourceId:'eia_official',gateSourceId:'eia_official',capability:'energy_commodity_series',origin:'https://api.eia.gov',method:'GET',path:'/v2/petroleum/pri/spt/data/',responseShape:'json',credential:'api_key',requestProfileId:'RWTC',executionState:'http_executable',freshness:'daily',notes:'EIA API v2 WTI spot price facet RWTC; API key is server-owned.'},
 {canonicalSourceId:'imf_official',gateSourceId:'imf_official',capability:'macro_indicator_series',origin:'https://data.imf.org',method:'GET',path:'/',responseShape:'sdmx_json',credential:'none',requestProfileId:'imf_sdmx_public',executionState:'blocked_profile',freshness:'release_aware',notes:'IMF Data Portal exposes SDMX 2.1/3.0 APIs. Exact current dataset dataflow must be pinned before execution; legacy endpoints are not substituted.'},
 {canonicalSourceId:'world_bank_official',gateSourceId:'world_bank_official',capability:'growth_activity_indicator',origin:'https://api.worldbank.org',method:'GET',path:'/v2/country/{country}/indicator/NY.GDP.MKTP.KD.ZG',responseShape:'json',credential:'none',requestProfileId:'NY.GDP.MKTP.KD.ZG',executionState:'http_executable',freshness:'release_aware',notes:'World Bank V2 Indicators API; no authentication.'},
 {canonicalSourceId:'oecd_official',gateSourceId:'oecd_official',capability:'growth_activity_indicator',origin:'https://sdmx.oecd.org',method:'GET',path:'/public/rest/data/',responseShape:'sdmx_csv',credential:'none',requestProfileId:'cli_server_owned_dataflow',executionState:'blocked_profile',freshness:'release_aware',notes:'OECD Data Explorer SDMX REST v1/v2. Exact composite-leading-indicator flow/key remains server-owned and must be pinned.'},
 {canonicalSourceId:'bis_official',gateSourceId:'bis_official',capability:'cross_market_rate_series',origin:'https://stats.bis.org',method:'GET',path:'/api/v2/data/',responseShape:'sdmx_csv',credential:'none',requestProfileId:'bis_cross_market_server_owned_dataflow',executionState:'blocked_profile',freshness:'release_aware',notes:'BIS SDMX REST v2.1. Exact dataflow/key remains server-owned and must be pinned before execution.'},
 {canonicalSourceId:'cboe_official',gateSourceId:'cboe_official',capability:'end_of_day_prices',origin:'https://cdn.cboe.com',method:'GET',path:'/',responseShape:'csv',credential:'entitlement',requestProfileId:'vix_direct_index',executionState:'blocked_entitlement',freshness:'intraday',notes:'Cboe VIX direct-index authority remains entitlement/legal gated; futures/ETFs never satisfy this contract.'},
 {canonicalSourceId:'ice_data_indices',gateSourceId:'ice_data_indices',capability:'end_of_day_prices',origin:'https://www.ice.com',method:'GET',path:'/',responseShape:'json',credential:'entitlement',requestProfileId:'dxy_direct_index',executionState:'blocked_entitlement',freshness:'intraday',notes:'ICE U.S. Dollar Index direct authority remains entitlement/legal gated; DX futures/UUP/reconstructed basket never satisfy this contract.'}
] as const;

export const listExecutableOfficialSourceContracts=()=>CANONICAL_OFFICIAL_SOURCE_CONTRACTS.filter(x=>x.executionState==='http_executable');
export const getOfficialSourceContract=(gateSourceId:string,capability:ProviderCapabilityKind)=>CANONICAL_OFFICIAL_SOURCE_CONTRACTS.find(x=>x.gateSourceId===gateSourceId&&x.capability===capability)??null;
