import type { ProviderCapabilityKind } from '@elceo/types';

export type OfficialHttpMethod='GET'|'POST';
export type OfficialResponseShape='json'|'csv'|'xml'|'html'|'xlsx'|'sdmx_csv'|'sdmx_json';
export type OfficialExecutionState='http_executable'|'parser_only'|'blocked_entitlement'|'blocked_profile';
export type OfficialSourceContract={canonicalSourceId:string;gateSourceId:string;capability:ProviderCapabilityKind;origin:string;method:OfficialHttpMethod;path:string;responseShape:OfficialResponseShape;credential:'none'|'api_key'|'subscription_key'|'user_agent'|'entitlement';requestProfileId:string;executionState:OfficialExecutionState;freshness:'intraday'|'daily'|'weekly'|'monthly'|'quarterly'|'release_aware';notes:string};

/** Interface truth only. `http_executable` means ELCEO has pinned a real source-specific request profile and parser.
 * It does not imply staging verification or production eligibility. `parser_only`/`blocked_profile` remain non-live. */
export const CANONICAL_OFFICIAL_SOURCE_CONTRACTS:readonly OfficialSourceContract[]=[
 {canonicalSourceId:'federal_reserve_official',gateSourceId:'federal_reserve',capability:'central_bank_balance_sheet',origin:'https://www.federalreserve.gov',method:'GET',path:'/releases/h41/',responseShape:'html',credential:'none',requestProfileId:'h41_release_index',executionState:'parser_only',freshness:'weekly',notes:'H.4.1 authority. DDP BYP retirement makes machine-series activation fail-closed until the replacement profile is pinned.'},
 {canonicalSourceId:'bls_official',gateSourceId:'bls_official',capability:'inflation_indicator',origin:'https://api.bls.gov',method:'POST',path:'/publicAPI/v2/timeseries/data/',responseShape:'json',credential:'api_key',requestProfileId:'CUSR0000SA0',executionState:'http_executable',freshness:'release_aware',notes:'BLS CPI-U all items, seasonally adjusted.'},
 {canonicalSourceId:'bls_official',gateSourceId:'bls_official',capability:'labor_market_indicator',origin:'https://api.bls.gov',method:'POST',path:'/publicAPI/v2/timeseries/data/',responseShape:'json',credential:'api_key',requestProfileId:'LNS14000000',executionState:'http_executable',freshness:'release_aware',notes:'BLS unemployment rate.'},
 {canonicalSourceId:'bea_official',gateSourceId:'bea_official',capability:'growth_activity_indicator',origin:'https://apps.bea.gov',method:'GET',path:'/api/data/',responseShape:'json',credential:'api_key',requestProfileId:'NIPA:T10101:Q',executionState:'http_executable',freshness:'release_aware',notes:'BEA NIPA table T10101 quarterly GDP profile.'},
 {canonicalSourceId:'census_official',gateSourceId:'census_official',capability:'growth_activity_indicator',origin:'https://api.census.gov',method:'GET',path:'/data/timeseries/eits/mrts',responseShape:'json',credential:'api_key',requestProfileId:'mrts_retail_sales',executionState:'http_executable',freshness:'release_aware',notes:'Census Economic Indicators monthly retail trade profile.'},
 {canonicalSourceId:'cftc_cot',gateSourceId:'cftc_cot',capability:'cot_report',origin:'https://publicreporting.cftc.gov',method:'GET',path:'/stories/s/Legacy-Futures-Only/yjak-hhbj/',responseShape:'html',credential:'none',requestProfileId:'legacy_futures_only_cot',executionState:'parser_only',freshness:'weekly',notes:'Existing ELCEO COT adapter remains fixture/parser-only. No Socrata resource ID is promoted until the exact dataset API identifier is pinned.'},
 {canonicalSourceId:'sec_edgar',gateSourceId:'sec_edgar',capability:'regulatory_filing_reference',origin:'https://data.sec.gov',method:'GET',path:'/submissions/CIK{cik}.json',responseShape:'json',credential:'user_agent',requestProfileId:'company_submissions',executionState:'blocked_profile',freshness:'release_aware',notes:'SEC submissions interface is verified; live activation waits for a bounded server-owned CIK/use-case profile and compliant User-Agent.'},
 {canonicalSourceId:'ecb_official',gateSourceId:'ecb_public',capability:'policy_rate_series',origin:'https://data-api.ecb.europa.eu',method:'GET',path:'/service/data/FM/{server_owned_key}',responseShape:'csv',credential:'none',requestProfileId:'deposit_facility',executionState:'http_executable',freshness:'daily',notes:'ECB deposit-facility profile.'},
 {canonicalSourceId:'us_treasury_official',gateSourceId:'us_treasury',capability:'nominal_yield_series',origin:'https://home.treasury.gov',method:'GET',path:'/resource-center/data-chart-center/interest-rates/pages/xml',responseShape:'xml',credential:'none',requestProfileId:'daily_treasury_yield_curve',executionState:'http_executable',freshness:'daily',notes:'Official nominal Treasury curve.'},
 {canonicalSourceId:'us_treasury_official',gateSourceId:'us_treasury',capability:'real_yield_series',origin:'https://home.treasury.gov',method:'GET',path:'/resource-center/data-chart-center/interest-rates/pages/xml',responseShape:'xml',credential:'none',requestProfileId:'daily_treasury_real_yield_curve',executionState:'http_executable',freshness:'daily',notes:'Official real Treasury curve.'},
 {canonicalSourceId:'fred_macro',gateSourceId:'fred',capability:'real_yield_series',origin:'https://api.stlouisfed.org',method:'GET',path:'/fred/series/observations',responseShape:'json',credential:'api_key',requestProfileId:'DFII10',executionState:'http_executable',freshness:'daily',notes:'FRED 10-year TIPS real yield confirmation.'},
 {canonicalSourceId:'fred_macro',gateSourceId:'fred',capability:'financial_conditions_index',origin:'https://api.stlouisfed.org',method:'GET',path:'/fred/series/observations',responseShape:'json',credential:'api_key',requestProfileId:'NFCI',executionState:'http_executable',freshness:'weekly',notes:'Chicago Fed NFCI through FRED.'},
 {canonicalSourceId:'eurostat_official',gateSourceId:'eurostat_official',capability:'inflation_indicator',origin:'https://ec.europa.eu',method:'GET',path:'/eurostat/api/dissemination/sdmx/3.0/data/dataflow/ESTAT/PRC_HICP_MINR/1.0',responseShape:'sdmx_csv',credential:'none',requestProfileId:'prc_hicp_minr',executionState:'blocked_profile',freshness:'release_aware',notes:'HICP dataflow is identified; bounded dimensions are not yet pinned.'},
 {canonicalSourceId:'destatis_official',gateSourceId:'destatis_official',capability:'inflation_indicator',origin:'https://www-genesis.destatis.de',method:'GET',path:'/genesisWS/rest/2020/data/table',responseShape:'json',credential:'api_key',requestProfileId:'61111_cpi',executionState:'blocked_profile',freshness:'release_aware',notes:'GENESIS CPI table/filter contract must be confirmed before live activation.'},
 {canonicalSourceId:'boe_official',gateSourceId:'boe_official',capability:'policy_rate_series',origin:'https://www.bankofengland.co.uk',method:'GET',path:'/boeapps/database/_iadb-fromshowcolumns.asp',responseShape:'csv',credential:'none',requestProfileId:'IUDBEDR',executionState:'http_executable',freshness:'daily',notes:'Official Bank Rate IUDBEDR.'},
 {canonicalSourceId:'ons_official',gateSourceId:'ons_official',capability:'inflation_indicator',origin:'https://api.beta.ons.gov.uk',method:'GET',path:'/v1/datasets/cpih01',responseShape:'json',credential:'none',requestProfileId:'cpih01_latest',executionState:'blocked_profile',freshness:'release_aware',notes:'CPIH dataset identified; latest-version observation dimensions remain fail-closed.'},
 {canonicalSourceId:'uk_dmo_official',gateSourceId:'uk_dmo_official',capability:'debt_supply_calendar',origin:'https://www.dmo.gov.uk',method:'GET',path:'/data/',responseShape:'csv',credential:'none',requestProfileId:'issuance_calendar',executionState:'blocked_profile',freshness:'release_aware',notes:'Issuance/auction authority only; never used as current gilt-yield authority.'},
 {canonicalSourceId:'boj_official',gateSourceId:'boj_public',capability:'policy_rate_series',origin:'https://www.boj.or.jp',method:'GET',path:'/',responseShape:'json',credential:'none',requestProfileId:'boj_timeseries_api_policy',executionState:'blocked_profile',freshness:'release_aware',notes:'Official Time-Series Data Search API exists, but exact API path and policy-series code remain unpinned; no invented endpoint is executable.'},
 {canonicalSourceId:'japan_mof_official',gateSourceId:'japan_mof_official',capability:'macro_indicator_series',origin:'https://www.mof.go.jp',method:'GET',path:'/english/policy/international_policy/reference/feio/index.html',responseShape:'html',credential:'none',requestProfileId:'fx_intervention_release_index',executionState:'parser_only',freshness:'release_aware',notes:'Official FX intervention release index; current CSV is release-derived and requires a trusted index resolver.'},
 {canonicalSourceId:'snb_official',gateSourceId:'snb_official',capability:'policy_rate_series',origin:'https://data.snb.ch',method:'GET',path:'/api/cube/',responseShape:'json',credential:'none',requestProfileId:'policy_rate_cube',executionState:'blocked_profile',freshness:'daily',notes:'Exact policy-rate cube/dimensions remain unpinned.'},
 {canonicalSourceId:'swiss_fso_official',gateSourceId:'swiss_fso_official',capability:'macro_indicator_series',origin:'https://www.pxweb.bfs.admin.ch',method:'POST',path:'/api/v1/en/',responseShape:'json',credential:'none',requestProfileId:'stat_tab_macro_table',executionState:'blocked_profile',freshness:'release_aware',notes:'PxWeb table/dimensions remain server-owned and unpinned.'},
 {canonicalSourceId:'rba_official',gateSourceId:'rba_official',capability:'policy_rate_series',origin:'https://www.rba.gov.au',method:'GET',path:'/statistics/cash-rate/',responseShape:'html',credential:'none',requestProfileId:'cash_rate_target',executionState:'http_executable',freshness:'release_aware',notes:'Official cash-rate target table.'},
 {canonicalSourceId:'abs_official',gateSourceId:'abs_official',capability:'macro_indicator_series',origin:'https://data.api.abs.gov.au',method:'GET',path:'/rest/data/',responseShape:'sdmx_csv',credential:'none',requestProfileId:'abs_macro_dataflow',executionState:'blocked_profile',freshness:'release_aware',notes:'ABS SDMX API is public; exact macro dataflow/dimension key remains unpinned.'},
 {canonicalSourceId:'rbnz_official',gateSourceId:'rbnz_official',capability:'policy_rate_series',origin:'https://www.rbnz.govt.nz',method:'GET',path:'/monetary-policy/monetary-policy-decisions',responseShape:'html',credential:'none',requestProfileId:'ocr_decision_history',executionState:'http_executable',freshness:'release_aware',notes:'Official OCR decision-history table.'},
 {canonicalSourceId:'stats_nz_official',gateSourceId:'stats_nz_official',capability:'macro_indicator_series',origin:'https://api.stats.govt.nz',method:'GET',path:'/',responseShape:'json',credential:'subscription_key',requestProfileId:'aotearoa_data_explorer',executionState:'blocked_profile',freshness:'release_aware',notes:'Subscription/product profile remains fail-closed until pinned.'},
 {canonicalSourceId:'bank_of_canada_official',gateSourceId:'bank_of_canada_official',capability:'policy_rate_series',origin:'https://www.bankofcanada.ca',method:'GET',path:'/valet/observations/V39079/json',responseShape:'json',credential:'none',requestProfileId:'V39079',executionState:'http_executable',freshness:'daily',notes:'Target for the overnight rate.'},
 {canonicalSourceId:'statistics_canada_official',gateSourceId:'statistics_canada_official',capability:'macro_indicator_series',origin:'https://www150.statcan.gc.ca',method:'GET',path:'/t1/wds/rest/getDataFromVectorByReferencePeriodRange',responseShape:'json',credential:'none',requestProfileId:'vector:41690973',executionState:'http_executable',freshness:'release_aware',notes:'Bounded CPI vector profile.'},
 {canonicalSourceId:'eia_official',gateSourceId:'eia_official',capability:'energy_commodity_series',origin:'https://api.eia.gov',method:'GET',path:'/v2/petroleum/pri/spt/data/',responseShape:'json',credential:'api_key',requestProfileId:'RWTC',executionState:'http_executable',freshness:'daily',notes:'WTI spot-price profile.'},
 {canonicalSourceId:'imf_official',gateSourceId:'imf_official',capability:'macro_indicator_series',origin:'https://data.imf.org',method:'GET',path:'/',responseShape:'sdmx_json',credential:'none',requestProfileId:'imf_sdmx_public',executionState:'blocked_profile',freshness:'release_aware',notes:'Current Data Portal SDMX dataflow must be pinned; legacy endpoint substitution is forbidden.'},
 {canonicalSourceId:'world_bank_official',gateSourceId:'world_bank_official',capability:'growth_activity_indicator',origin:'https://api.worldbank.org',method:'GET',path:'/v2/country/WLD/indicator/NY.GDP.MKTP.KD.ZG',responseShape:'json',credential:'none',requestProfileId:'NY.GDP.MKTP.KD.ZG',executionState:'http_executable',freshness:'release_aware',notes:'World GDP growth indicator.'},
 {canonicalSourceId:'oecd_official',gateSourceId:'oecd_official',capability:'growth_activity_indicator',origin:'https://sdmx.oecd.org',method:'GET',path:'/public/rest/data/',responseShape:'sdmx_csv',credential:'none',requestProfileId:'cli_server_owned_dataflow',executionState:'blocked_profile',freshness:'release_aware',notes:'Exact growth/CLI dataflow/key remains unpinned.'},
 {canonicalSourceId:'bis_official',gateSourceId:'bis_official',capability:'cross_market_rate_series',origin:'https://stats.bis.org',method:'GET',path:'/api/v2/data/',responseShape:'sdmx_csv',credential:'none',requestProfileId:'bis_cross_market_server_owned_dataflow',executionState:'blocked_profile',freshness:'release_aware',notes:'Exact cross-market dataflow/key remains unpinned.'},
 {canonicalSourceId:'cboe_official',gateSourceId:'cboe_official',capability:'end_of_day_prices',origin:'https://cdn.cboe.com',method:'GET',path:'/',responseShape:'csv',credential:'entitlement',requestProfileId:'vix_direct_index',executionState:'blocked_entitlement',freshness:'intraday',notes:'Cboe VIX direct-index authority; futures/ETFs never satisfy this contract.'},
 {canonicalSourceId:'ice_data_indices',gateSourceId:'ice_data_indices',capability:'end_of_day_prices',origin:'https://www.ice.com',method:'GET',path:'/',responseShape:'json',credential:'entitlement',requestProfileId:'dxy_direct_index',executionState:'blocked_entitlement',freshness:'intraday',notes:'ICE DXY direct authority; DX futures/UUP/reconstructed basket never satisfy this contract.'}
] as const;

export const listExecutableOfficialSourceContracts=()=>CANONICAL_OFFICIAL_SOURCE_CONTRACTS.filter(x=>x.executionState==='http_executable');
export const getOfficialSourceContract=(gateSourceId:string,capability:ProviderCapabilityKind)=>CANONICAL_OFFICIAL_SOURCE_CONTRACTS.find(x=>x.gateSourceId===gateSourceId&&x.capability===capability)??null;
