import type { MarketDataProviderDescriptor, NormalizedMarketEvidencePayload, ProviderCapabilityKind, ProviderSourceRequest, ProviderSourceResponse } from '@elceo/types';
import type { MarketEvidenceProviderAdapter } from '../normalization-contracts';
import { getProviderDescriptor } from '../provider-capability-registry';
import { FredOfficialAdapter } from './fred-adapter';
import { EcbOfficialAdapter } from './ecb-adapter';
import { UsTreasuryOfficialAdapter } from './us-treasury-adapter';
import { createBankOfCanadaPolicyOfficialAdapter, createBeaGrowthOfficialAdapter, createBlsInflationOfficialAdapter, createBlsLaborOfficialAdapter, createBoePolicyOfficialAdapter, createCensusGrowthOfficialAdapter, createEiaEnergyOfficialAdapter, createRbaPolicyOfficialAdapter, createRbnzPolicyOfficialAdapter, createStatisticsCanadaMacroOfficialAdapter, createWorldBankGrowthOfficialAdapter, type VerifiedOfficialAdapterConfig } from './verified-series-adapters';
import { createAbsCpiOfficialAdapter, createBojPolicyOfficialAdapter, createCboeVixEodOfficialAdapter, createEurostatHicpOfficialAdapter, createFederalReserveH41OfficialAdapter, createOecdCliOfficialAdapter, createOnsCpihOfficialAdapter, createSnbPolicyOfficialAdapter, type ResearchOfficialAdapterConfig } from './research-verified-adapters';

export type OfficialAdapterReadiness='live_capable'|'fixture_parser_ready'|'blocked_profile'|'blocked_entitlement';
export type OfficialAdapterCatalogEntry={gateSourceId:string;canonicalSourceId:string;capability:ProviderCapabilityKind;readiness:OfficialAdapterReadiness;reason:string;factory:(config:OfficialAdapterFactoryConfig)=>MarketEvidenceProviderAdapter|null};
export type OfficialAdapterFactoryConfig=VerifiedOfficialAdapterConfig&{fredApiKey?:string|null;beaApiKey?:string|null;censusApiKey?:string|null;blsApiKey?:string|null;eiaApiKey?:string|null;statsNzSubscriptionKey?:string|null;secUserAgent?:string|null;timeoutMs?:number|null};
type BlockedFixture={date:string;value:number;label:string;region:string;evidenceClass:string};

const base=(r:ProviderSourceRequest):ProviderSourceResponse=>({requestId:r.requestId,providerId:r.providerId,capability:r.capability,status:'failed',fetchedAt:new Date().toISOString(),sourceUrl:null,rawPayloadJson:null,errorCode:null,errorMessage:null});
const createFailClosedAdapter=(providerId:string,canonicalSourceId:string,capability:ProviderCapabilityKind,reason:string,fixture:BlockedFixture):MarketEvidenceProviderAdapter|null=>{
 const descriptor:MarketDataProviderDescriptor|null=getProviderDescriptor(providerId);if(!descriptor)return null;
 return {descriptor,fetch:async request=>request.providerId===providerId&&request.capability===capability?{...base(request),status:'success',sourceUrl:`fixture://${providerId}/${capability}`,rawPayloadJson:JSON.stringify([fixture])}:{...base(request),errorCode:'official_source_request_mismatch',errorMessage:'official_source_request_mismatch'},normalize:async response=>{if(!response.rawPayloadJson)return[];const rows=JSON.parse(response.rawPayloadJson) as BlockedFixture[];return rows.map((row,index):NormalizedMarketEvidencePayload=>({payloadId:`${response.requestId}:${index}`,evidenceTypeId:response.capability,evidenceClass:row.evidenceClass,providerId:canonicalSourceId,sourceId:canonicalSourceId,region:row.region,asset:null,observedAt:/^\d{4}-Q[1-4]$/.test(row.date)?new Date(Date.UTC(Number(row.date.slice(0,4)),(Number(row.date.slice(-1))-1)*3,1)).toISOString():/^\d{4}$/.test(row.date)?`${row.date}-01-01T00:00:00.000Z`:new Date(row.date.length===10?`${row.date}T00:00:00Z`:row.date).toISOString(),publishedAt:null,normalizedAt:response.fetchedAt,confidenceScore:70,dataQuality:'partial',valuesJson:JSON.stringify({value:row.value,label:row.label}),metadataJson:JSON.stringify({canonicalSourceId,gateSourceId:providerId,requestId:response.requestId,readiness:'fixture_parser_ready',liveBlockedReason:reason})}));}};
};
const blocked=(gateSourceId:string,canonicalSourceId:string,capability:ProviderCapabilityKind,reason:string,fixture:BlockedFixture,readiness:OfficialAdapterReadiness='blocked_profile'):OfficialAdapterCatalogEntry=>({gateSourceId,canonicalSourceId,capability,readiness,reason,factory:()=>createFailClosedAdapter(gateSourceId,canonicalSourceId,capability,reason,fixture)});
const verifiedConfig=(c:OfficialAdapterFactoryConfig,apiKey?:string|null):VerifiedOfficialAdapterConfig=>({...c,...(apiKey!==undefined?{apiKey}:{}),...(c.fetchImpl?{fetchImpl:c.fetchImpl}:{})});
const fredConfig=(c:OfficialAdapterFactoryConfig)=>({...(c.mode?{mode:c.mode}:{}),...(c.fredApiKey??c.apiKey?{apiKey:c.fredApiKey??c.apiKey}:{}),...(c.fetchImpl?{fetchImpl:c.fetchImpl}:{})});
const simpleConfig=(c:OfficialAdapterFactoryConfig)=>({...(c.mode?{mode:c.mode}:{}),...(c.fetchImpl?{fetchImpl:c.fetchImpl}:{})});
const researchConfig=(c:OfficialAdapterFactoryConfig):ResearchOfficialAdapterConfig=>({...(c.mode?{mode:c.mode}:{}),...(c.fetchImpl?{fetchImpl:c.fetchImpl}:{}),...(c.timeoutMs?{timeoutMs:c.timeoutMs}:{})});

export const OFFICIAL_ADAPTER_CATALOG:readonly OfficialAdapterCatalogEntry[]=[
 {gateSourceId:'fred',canonicalSourceId:'fred_macro',capability:'real_yield_series',readiness:'live_capable',reason:'server-owned FRED DFII10 profile',factory:c=>new FredOfficialAdapter(fredConfig(c))},
 {gateSourceId:'fred',canonicalSourceId:'fred_macro',capability:'financial_conditions_index',readiness:'live_capable',reason:'server-owned FRED NFCI profile',factory:c=>new FredOfficialAdapter(fredConfig(c))},
 {gateSourceId:'ecb_public',canonicalSourceId:'ecb_official',capability:'policy_rate_series',readiness:'live_capable',reason:'server-owned ECB deposit-facility profile',factory:c=>new EcbOfficialAdapter(simpleConfig(c))},
 {gateSourceId:'us_treasury',canonicalSourceId:'us_treasury_official',capability:'nominal_yield_series',readiness:'live_capable',reason:'server-owned Treasury nominal curve profile',factory:c=>new UsTreasuryOfficialAdapter(simpleConfig(c))},
 {gateSourceId:'us_treasury',canonicalSourceId:'us_treasury_official',capability:'real_yield_series',readiness:'live_capable',reason:'server-owned Treasury real curve profile',factory:c=>new UsTreasuryOfficialAdapter(simpleConfig(c))},
 {gateSourceId:'bls_official',canonicalSourceId:'bls_official',capability:'inflation_indicator',readiness:'live_capable',reason:'BLS CPI-U series CUSR0000SA0',factory:c=>createBlsInflationOfficialAdapter(verifiedConfig(c,c.blsApiKey??c.apiKey))},
 {gateSourceId:'bls_official',canonicalSourceId:'bls_official',capability:'labor_market_indicator',readiness:'live_capable',reason:'BLS unemployment series LNS14000000',factory:c=>createBlsLaborOfficialAdapter(verifiedConfig(c,c.blsApiKey??c.apiKey))},
 {gateSourceId:'bea_official',canonicalSourceId:'bea_official',capability:'growth_activity_indicator',readiness:'live_capable',reason:'BEA NIPA T10101 quarterly GDP profile',factory:c=>createBeaGrowthOfficialAdapter(verifiedConfig(c,c.beaApiKey??c.apiKey))},
 {gateSourceId:'census_official',canonicalSourceId:'census_official',capability:'growth_activity_indicator',readiness:'live_capable',reason:'Census EITS monthly retail trade profile',factory:c=>createCensusGrowthOfficialAdapter(verifiedConfig(c,c.censusApiKey??c.apiKey))},
 {gateSourceId:'boe_official',canonicalSourceId:'boe_official',capability:'policy_rate_series',readiness:'live_capable',reason:'BoE IADB IUDBEDR Official Bank Rate',factory:c=>createBoePolicyOfficialAdapter(verifiedConfig(c))},
 {gateSourceId:'rba_official',canonicalSourceId:'rba_official',capability:'policy_rate_series',readiness:'live_capable',reason:'RBA official cash-rate target table',factory:c=>createRbaPolicyOfficialAdapter(verifiedConfig(c))},
 {gateSourceId:'rbnz_official',canonicalSourceId:'rbnz_official',capability:'policy_rate_series',readiness:'live_capable',reason:'RBNZ official OCR decision history',factory:c=>createRbnzPolicyOfficialAdapter(verifiedConfig(c))},
 {gateSourceId:'bank_of_canada_official',canonicalSourceId:'bank_of_canada_official',capability:'policy_rate_series',readiness:'live_capable',reason:'Bank of Canada Valet V39079',factory:c=>createBankOfCanadaPolicyOfficialAdapter(verifiedConfig(c))},
 {gateSourceId:'statistics_canada_official',canonicalSourceId:'statistics_canada_official',capability:'macro_indicator_series',readiness:'live_capable',reason:'Statistics Canada WDS CPI vector 41690973',factory:c=>createStatisticsCanadaMacroOfficialAdapter(verifiedConfig(c))},
 {gateSourceId:'eia_official',canonicalSourceId:'eia_official',capability:'energy_commodity_series',readiness:'live_capable',reason:'EIA API v2 WTI RWTC profile',factory:c=>createEiaEnergyOfficialAdapter(verifiedConfig(c,c.eiaApiKey??c.apiKey))},
 {gateSourceId:'world_bank_official',canonicalSourceId:'world_bank_official',capability:'growth_activity_indicator',readiness:'live_capable',reason:'World Bank V2 WLD real GDP growth indicator',factory:c=>createWorldBankGrowthOfficialAdapter(verifiedConfig(c))},
 {gateSourceId:'federal_reserve',canonicalSourceId:'federal_reserve_official',capability:'central_bank_balance_sheet',readiness:'live_capable',reason:'Federal Reserve H.4.1 consolidated total-assets profile',factory:c=>createFederalReserveH41OfficialAdapter(researchConfig(c))},
 {gateSourceId:'eurostat_official',canonicalSourceId:'eurostat_official',capability:'inflation_indicator',readiness:'live_capable',reason:'Eurostat HICP monthly annual-rate profile M/RCH_A/TOTAL/EA21',factory:c=>createEurostatHicpOfficialAdapter(researchConfig(c))},
 {gateSourceId:'ons_official',canonicalSourceId:'ons_official',capability:'inflation_indicator',readiness:'live_capable',reason:'ONS CPIH All Items annual-rate L55O profile',factory:c=>createOnsCpihOfficialAdapter(researchConfig(c))},
 {gateSourceId:'boj_public',canonicalSourceId:'boj_official',capability:'policy_rate_series',readiness:'live_capable',reason:'BoJ FM01 STRDCLUCON Time-Series Data Search API profile',factory:c=>createBojPolicyOfficialAdapter(researchConfig(c))},
 {gateSourceId:'snb_official',canonicalSourceId:'snb_official',capability:'policy_rate_series',readiness:'live_capable',reason:'SNB snboffzisa D0(LZ) policy-rate profile',factory:c=>createSnbPolicyOfficialAdapter(researchConfig(c))},
 {gateSourceId:'abs_official',canonicalSourceId:'abs_official',capability:'inflation_indicator',readiness:'live_capable',reason:'ABS CPI 2.0.0 All Groups Australia monthly profile',factory:c=>createAbsCpiOfficialAdapter(researchConfig(c))},
 {gateSourceId:'oecd_official',canonicalSourceId:'oecd_official',capability:'growth_activity_indicator',readiness:'live_capable',reason:'OECD G20 monthly Composite Leading Indicator profile',factory:c=>createOecdCliOfficialAdapter(researchConfig(c))},
 {gateSourceId:'cboe_official',canonicalSourceId:'cboe_official',capability:'end_of_day_prices',readiness:'live_capable',reason:'Cboe public VIX historical/end-of-day direct-index CSV',factory:c=>createCboeVixEodOfficialAdapter(researchConfig(c))},
 blocked('sec_edgar','sec_edgar','regulatory_filing_reference','SEC EDGAR bounded CIK/use-case profile not yet pinned',{date:'2026-06-30',value:1,label:'SEC filing fixture marker',region:'united_states',evidenceClass:'regulatory_filings'},'fixture_parser_ready'),
 blocked('destatis_official','destatis_official','inflation_indicator','GENESIS CPI table is pinned but exact token/header execution contract still requires empirical validation',{date:'2026-06-01',value:2,label:'Germany CPI fixture marker',region:'germany',evidenceClass:'inflation'},'fixture_parser_ready'),
 blocked('uk_dmo_official','uk_dmo_official','debt_supply_calendar','UK DMO deterministic machine-export contract not yet pinned',{date:'2026-06-01',value:1,label:'UK DMO issuance fixture marker',region:'united_kingdom',evidenceClass:'government_debt_supply'},'fixture_parser_ready'),
 blocked('japan_mof_official','japan_mof_official','macro_indicator_series','MOF intervention file requires trusted release-index resolution',{date:'2026-06-30',value:0,label:'Japan FX intervention fixture marker',region:'japan',evidenceClass:'economic_indicator'},'fixture_parser_ready'),
 blocked('swiss_fso_official','swiss_fso_official','inflation_indicator','Swiss Stats Explorer CPI dataflow must be resolved from first-party catalogue',{date:'2026-06-01',value:1,label:'Swiss CPI fixture marker',region:'switzerland',evidenceClass:'inflation'},'fixture_parser_ready'),
 blocked('stats_nz_official','stats_nz_official','inflation_indicator','Stats NZ rolling CPI release attachment resolver not yet pinned',{date:'2026-Q2',value:1,label:'New Zealand CPI fixture marker',region:'new_zealand',evidenceClass:'inflation'},'fixture_parser_ready'),
 blocked('imf_official','imf_official','liquidity_conditions_indicator','IMF International Liquidity operational Data Portal API contract remains account-gated',{date:'2025',value:1,label:'IMF international liquidity fixture marker',region:'global',evidenceClass:'liquidity_conditions'},'fixture_parser_ready'),
 blocked('bis_official','bis_official','cross_market_rate_series','BIS WS_CBPOL flow identified; bounded multi-currency execution key not yet empirically validated',{date:'2026-06-01',value:1,label:'BIS cross-market fixture marker',region:'global',evidenceClass:'cross_market_rates'},'fixture_parser_ready'),
 blocked('ice_data_indices','ice_data_indices','end_of_day_prices','ICE direct DXY delivery requires licensed entitlement and exact licensed operation/schema',{date:'2026-09-11',value:97,label:'DXY direct-index fixture marker',region:'global',evidenceClass:'cross_market_rates'},'blocked_entitlement')
] as const;

export const getOfficialAdapterCatalogEntry=(gateSourceId:string,capability:ProviderCapabilityKind)=>OFFICIAL_ADAPTER_CATALOG.find(x=>x.gateSourceId===gateSourceId&&x.capability===capability)??null;
export const createOfficialAdapter=(gateSourceId:string,capability:ProviderCapabilityKind,config:OfficialAdapterFactoryConfig={}):MarketEvidenceProviderAdapter|null=>getOfficialAdapterCatalogEntry(gateSourceId,capability)?.factory(config)??null;
export const listOfficialLiveCapableAdapters=()=>OFFICIAL_ADAPTER_CATALOG.filter(x=>x.readiness==='live_capable');
