import type { MarketDataProviderDescriptor } from '@elceo/types';

/** Source-specific descriptors used by Provider API Gate for canonical official authorities. */
export const OFFICIAL_PROVIDER_DESCRIPTORS:readonly MarketDataProviderDescriptor[]=[
 {providerId:'bls_official',providerFamily:'statistics_agency',displayName:'U.S. Bureau of Labor Statistics',homepageUrl:'https://www.bls.gov',accessRequirement:'api_key',supportedCapabilities:['macro_indicator_series','inflation_indicator','labor_market_indicator'],supportedRegions:['united_states'],supportedAssets:['macro_series'],launchEnabled:false,notes:'BLS Public Data API v2; ELCEO uses server-owned series profiles and a registration key. Staging verification is separate.'},
 {providerId:'bea_official',providerFamily:'statistics_agency',displayName:'U.S. Bureau of Economic Analysis',homepageUrl:'https://www.bea.gov',accessRequirement:'api_key',supportedCapabilities:['macro_indicator_series','growth_activity_indicator'],supportedRegions:['united_states'],supportedAssets:['macro_series'],launchEnabled:false,notes:'BEA API; server-owned NIPA request profiles only.'},
 {providerId:'census_official',providerFamily:'statistics_agency',displayName:'U.S. Census Bureau',homepageUrl:'https://www.census.gov',accessRequirement:'api_key',supportedCapabilities:['macro_indicator_series','growth_activity_indicator'],supportedRegions:['united_states'],supportedAssets:['macro_series'],launchEnabled:false,notes:'Economic Indicators Time Series profile; key/configuration remains server-owned.'},
 {providerId:'sec_edgar',providerFamily:'public_regulatory_filings',displayName:'SEC EDGAR',homepageUrl:'https://www.sec.gov/edgar',accessRequirement:'official_public_download',supportedCapabilities:['regulatory_filing_reference','institutional_liquidity_report','bank_health_metric'],supportedRegions:['united_states','global'],supportedAssets:['filings'],launchEnabled:false,notes:'data.sec.gov APIs; SEC-compliant descriptive User-Agent and server-owned CIK/use-case profile required.'},
 {providerId:'eurostat_official',providerFamily:'statistics_agency',displayName:'Eurostat',homepageUrl:'https://ec.europa.eu/eurostat',accessRequirement:'official_public_download',supportedCapabilities:['macro_indicator_series','inflation_indicator','growth_activity_indicator'],supportedRegions:['euro_area','europe'],supportedAssets:['macro_series'],launchEnabled:false,notes:'Eurostat SDMX 3.0. HICP dataflow is identified; exact dimensions remain fail-closed until pinned.'},
 {providerId:'destatis_official',providerFamily:'statistics_agency',displayName:'Destatis GENESIS',homepageUrl:'https://www.destatis.de',accessRequirement:'api_key',supportedCapabilities:['macro_indicator_series','inflation_indicator','growth_activity_indicator'],supportedRegions:['germany','euro_area'],supportedAssets:['macro_series'],launchEnabled:false,notes:'GENESIS Webservices 2020; server-owned token/table profiles.'},
 {providerId:'boe_official',providerFamily:'central_bank',displayName:'Bank of England',homepageUrl:'https://www.bankofengland.co.uk',accessRequirement:'official_public_download',supportedCapabilities:['policy_rate_series','nominal_yield_series','central_bank_balance_sheet'],supportedRegions:['united_kingdom'],supportedAssets:['gbp_rates'],launchEnabled:false,notes:'BoE IADB CSV; IUDBEDR is the server-owned Official Bank Rate profile.'},
 {providerId:'ons_official',providerFamily:'statistics_agency',displayName:'Office for National Statistics',homepageUrl:'https://www.ons.gov.uk',accessRequirement:'official_public_download',supportedCapabilities:['macro_indicator_series','inflation_indicator','labor_market_indicator','growth_activity_indicator'],supportedRegions:['united_kingdom'],supportedAssets:['macro_series'],launchEnabled:false,notes:'ONS beta API; CPIH dataset is identified but version/observation dimensions remain server-owned and fail-closed.'},
 {providerId:'uk_dmo_official',providerFamily:'treasury',displayName:'UK Debt Management Office',homepageUrl:'https://www.dmo.gov.uk',accessRequirement:'official_public_download',supportedCapabilities:['debt_supply_calendar','bond_auction_result'],supportedRegions:['united_kingdom'],supportedAssets:['uk_debt'],launchEnabled:false,notes:'Official issuance/auction authority only; never substituted for current gilt market yields.'},
 {providerId:'japan_mof_official',providerFamily:'treasury',displayName:'Japan Ministry of Finance',homepageUrl:'https://www.mof.go.jp',accessRequirement:'official_public_download',supportedCapabilities:['macro_indicator_series'],supportedRegions:['japan'],supportedAssets:['jpy_intervention'],launchEnabled:false,notes:'Official foreign-exchange intervention history; release-derived files require a trusted index resolver.'},
 {providerId:'snb_official',providerFamily:'central_bank',displayName:'Swiss National Bank',homepageUrl:'https://www.snb.ch',accessRequirement:'official_public_download',supportedCapabilities:['policy_rate_series','central_bank_balance_sheet'],supportedRegions:['switzerland'],supportedAssets:['chf_rates'],launchEnabled:false,notes:'SNB data portal cube API; exact policy-rate cube/dimensions must be pinned before live execution.'},
 {providerId:'swiss_fso_official',providerFamily:'statistics_agency',displayName:'Swiss Federal Statistical Office',homepageUrl:'https://www.bfs.admin.ch',accessRequirement:'official_public_download',supportedCapabilities:['macro_indicator_series','inflation_indicator','growth_activity_indicator'],supportedRegions:['switzerland'],supportedAssets:['macro_series'],launchEnabled:false,notes:'STAT-TAB PxWeb API; table and dimensions remain server-owned.'},
 {providerId:'rba_official',providerFamily:'central_bank',displayName:'Reserve Bank of Australia',homepageUrl:'https://www.rba.gov.au',accessRequirement:'official_public_download',supportedCapabilities:['policy_rate_series','nominal_yield_series'],supportedRegions:['australia'],supportedAssets:['aud_rates'],launchEnabled:false,notes:'Official cash-rate target history is consumed from the RBA published table; no invented JSON API.'},
 {providerId:'abs_official',providerFamily:'statistics_agency',displayName:'Australian Bureau of Statistics',homepageUrl:'https://www.abs.gov.au',accessRequirement:'official_public_download',supportedCapabilities:['macro_indicator_series','inflation_indicator','labor_market_indicator','growth_activity_indicator'],supportedRegions:['australia'],supportedAssets:['macro_series'],launchEnabled:false,notes:'ABS SDMX REST API at data.api.abs.gov.au; exact dataflow keys remain fail-closed until pinned.'},
 {providerId:'rbnz_official',providerFamily:'central_bank',displayName:'Reserve Bank of New Zealand',homepageUrl:'https://www.rbnz.govt.nz',accessRequirement:'official_public_download',supportedCapabilities:['policy_rate_series','nominal_yield_series'],supportedRegions:['new_zealand'],supportedAssets:['nzd_rates'],launchEnabled:false,notes:'Official OCR decision history is consumed from the RBNZ published table; no invented JSON endpoint.'},
 {providerId:'stats_nz_official',providerFamily:'statistics_agency',displayName:'Stats NZ',homepageUrl:'https://www.stats.govt.nz',accessRequirement:'api_key',supportedCapabilities:['macro_indicator_series','inflation_indicator','labor_market_indicator','growth_activity_indicator'],supportedRegions:['new_zealand'],supportedAssets:['macro_series'],launchEnabled:false,notes:'Aotearoa Data Explorer subscription required; exact product profile remains fail-closed.'},
 {providerId:'bank_of_canada_official',providerFamily:'central_bank',displayName:'Bank of Canada Valet',homepageUrl:'https://www.bankofcanada.ca',accessRequirement:'official_public_download',supportedCapabilities:['policy_rate_series','nominal_yield_series'],supportedRegions:['canada'],supportedAssets:['cad_rates'],launchEnabled:false,notes:'Valet API; V39079 is the server-owned target for the overnight rate profile.'},
 {providerId:'statistics_canada_official',providerFamily:'statistics_agency',displayName:'Statistics Canada',homepageUrl:'https://www.statcan.gc.ca',accessRequirement:'official_public_download',supportedCapabilities:['macro_indicator_series','inflation_indicator','labor_market_indicator','growth_activity_indicator'],supportedRegions:['canada'],supportedAssets:['macro_series'],launchEnabled:false,notes:'Web Data Service; bounded server-owned vector/table profiles only.'},
 {providerId:'eia_official',providerFamily:'statistics_agency',displayName:'U.S. Energy Information Administration',homepageUrl:'https://www.eia.gov',accessRequirement:'api_key',supportedCapabilities:['energy_commodity_series'],supportedRegions:['united_states','global'],supportedAssets:['wti','brent','energy'],launchEnabled:false,notes:'EIA API v2; WTI RWTC is the server-owned CAD energy-context profile.'},
 {providerId:'imf_official',providerFamily:'imf',displayName:'International Monetary Fund',homepageUrl:'https://www.imf.org',accessRequirement:'official_public_download',supportedCapabilities:['liquidity_conditions_indicator','macro_indicator_series'],supportedRegions:['global'],supportedAssets:['macro_series'],launchEnabled:false,notes:'Current IMF Data Portal SDMX interface only; exact current dataflow remains fail-closed and legacy endpoints are not substituted.'},
 {providerId:'world_bank_official',providerFamily:'world_bank',displayName:'World Bank Indicators API',homepageUrl:'https://data.worldbank.org',accessRequirement:'official_public_download',supportedCapabilities:['growth_activity_indicator','macro_indicator_series'],supportedRegions:['global'],supportedAssets:['macro_series'],launchEnabled:false,notes:'World Bank V2 Indicators API; no API key required.'},
 {providerId:'oecd_official',providerFamily:'oecd',displayName:'OECD Data Explorer',homepageUrl:'https://data-explorer.oecd.org',accessRequirement:'official_public_download',supportedCapabilities:['growth_activity_indicator','macro_indicator_series'],supportedRegions:['global'],supportedAssets:['macro_series'],launchEnabled:false,notes:'OECD SDMX public REST API; exact growth/CLI dataflow and key remain server-owned.'},
 {providerId:'bis_official',providerFamily:'exchange',displayName:'Bank for International Settlements Statistics',homepageUrl:'https://stats.bis.org',accessRequirement:'official_public_download',supportedCapabilities:['cross_market_rate_series','dollar_liquidity_indicator'],supportedRegions:['global'],supportedAssets:['fx_crosses','usd_baskets'],launchEnabled:false,notes:'BIS SDMX v2 API; exact dataflow/key remains server-owned.'}
] as const;

export const getOfficialProviderDescriptor=(providerId:string):MarketDataProviderDescriptor|null=>OFFICIAL_PROVIDER_DESCRIPTORS.find(descriptor=>descriptor.providerId===providerId)??null;
