import type { MarketDataProviderDescriptor, NormalizedMarketEvidencePayload, ProviderCapabilityKind, ProviderSourceRequest, ProviderSourceResponse } from '@elceo/types';
import type { MarketEvidenceProviderAdapter } from '../normalization-contracts';
import { getProviderDescriptor } from '../provider-capability-registry';
import { FredOfficialAdapter } from './fred-adapter';
import { EcbOfficialAdapter } from './ecb-adapter';
import { UsTreasuryOfficialAdapter } from './us-treasury-adapter';
import { createBankOfCanadaPolicyOfficialAdapter, createBeaGrowthOfficialAdapter, createBlsInflationOfficialAdapter, createBlsLaborOfficialAdapter, createBoePolicyOfficialAdapter, createCensusGrowthOfficialAdapter, createEiaEnergyOfficialAdapter, createRbaPolicyOfficialAdapter, createRbnzPolicyOfficialAdapter, createStatisticsCanadaMacroOfficialAdapter, createWorldBankGrowthOfficialAdapter, type VerifiedOfficialAdapterConfig } from './verified-series-adapters';

export type OfficialAdapterReadiness='live_capable'|'fixture_parser_ready'|'blocked_profile'|'blocked_entitlement';
export type OfficialAdapterCatalogEntry={gateSourceId:string;canonicalSourceId:string;capability:ProviderCapabilityKind;readiness:OfficialAdapterReadiness;reason:string;factory:(config:OfficialAdapterFactoryConfig)=>MarketEvidenceProviderAdapter|null};
export type OfficialAdapterFactoryConfig=VerifiedOfficialAdapterConfig&{fredApiKey?:string|null;beaApiKey?:string|null;censusApiKey?:string|null;blsApiKey?:string|null;eiaApiKey?:string|null;statsNzSubscriptionKey?:string|null;secUserAgent?:string|null};

type BlockedFixture={date:string;value:number;label:string;region:string;evidenceClass:string};
const createFailClosedAdapter=(providerId:string,canonicalSourceId:string,capability:ProviderCapabilityKind,reason:string,fixture:BlockedFixture):MarketEvidenceProviderAdapter|null=>{
 const descriptor:MarketDataProviderDescriptor|null=getProviderDescriptor(providerId);if(!descriptor)return null;
 const base=(r:ProviderSourceRequest):ProviderSourceResponse=>({requestId:r.requestId,providerId:r.providerId,capability:r.capability,status:'failed',fetchedAt:new Date().toISOString(),sourceUrl:null,rawPayloadJson:null,errorCode:null,errorMessage:null});
 return{descriptor,fetch:async request=>request.providerId===providerId&&request.capability===capability?{...base(request),status:'success',sourceUrl:`fixture://${providerId}/${capability}`,rawPayloadJson:JSON.stringify([fixture])}:{...base(request),errorCode:'official_source_request_mismatch',errorMessage:'official_source_request_mismatch'},normalize:async response=>{if(!response.rawPayloadJson)return[];const rows=JSON.parse(response.rawPayloadJson) as BlockedFixture[];return rows.map((row,index):NormalizedMarketEvidencePayload=>({payloadId:`${response.requestId}:${index}`,evidenceTypeId:response.capability,evidenceClass:row.evidenceClass,providerId:canonicalSourceId,sourceId:canonicalSourceId,region:row.region,asset:null,observedAt:new Date(row.date).toISOString(),publishedAt:null,normalizedAt:response.fetchedAt,confidenceScore:70,dataQuality:'partial',valuesJson:JSON.stringify({value:row.value,label:row.label}),metadataJson:JSON.stringify({canonicalSourceId,gateSourceId:providerId,requestId:response.requestId,readiness:'fixture_parser_ready',liveBlockedReason:reason})}))};
};
const blocked=(gateSourceId:string,canonicalSourceId:string,capability:ProviderCapabilityKind,reason:string,fixture:BlockedFixture,readiness:OfficialAdapterReadiness='blocked_profile'):OfficialAdapterCatalogEntry=>({gateSourceId,canonicalSourceId,capability,readiness,reason,factory:()=>createFailClosedAdapter(gateSourceId,canonicalSourceId,capability,reason,fixture)});

export const OFFICIAL_ADAPTER_CATALOG:readonly OfficialAdapterCatalogEntry[]=[
 {gateSourceId:'fred',canonicalSourceId:'fred_macro',capability:'real_yield_series',readiness:'live_capable',reason:'server-owned FRED DFII10 profile',factory:c=>new FredOfficialAdapter({mode:c.mode,apiKey:c.fredApiKey??c.apiKey,fetchImpl:c.fetchImpl})},
 {gateSourceId:'fred',canonicalSourceId:'fred_macro',capability:'financial_conditions_index',readiness:'live_capable',reason:'server-owned FRED NFCI profile',factory:c=>new FredOfficialAdapter({mode:c.mode,apiKey:c.fredApiKey??c.apiKey,fetchImpl:c.fetchImpl})},
 {gateSourceId:'ecb_public',canonicalSourceId:'ecb_official',capability:'policy_rate_series',readiness:'live_capable',reason:'server-owned ECB deposit-facility profile',factory:c=>new EcbOfficialAdapter({mode:c.mode,fetchImpl:c.fetchImpl})},
 {gateSourceId:'us_treasury',canonicalSourceId:'us_treasury_official',capability:'nominal_yield_series',readiness:'live_capable',reason:'server-owned Treasury nominal curve profile',factory:c=>new UsTreasuryOfficialAdapter({mode:c.mode,fetchImpl:c.fetchImpl})},
 {gateSourceId:'us_treasury',canonicalSourceId:'us_treasury_official',capability:'real_yield_series',readiness:'live_capable',reason:'server-owned Treasury real curve profile',factory:c=>new UsTreasuryOfficialAdapter({mode:c.mode,fetchImpl:c.fetchImpl})},
 {gateSourceId:'bls_official',canonicalSourceId:'bls_official',capability:'inflation_indicator',readiness:'live_capable',reason:'BLS CPI-U series CUSR0000SA0',factory:c=>createBlsInflationOfficialAdapter({...c,apiKey:c.blsApiKey??c.apiKey})},
 {gateSourceId:'bls_official',canonicalSourceId:'bls_official',capability:'labor_market_indicator',readiness:'live_capable',reason:'BLS unemployment series LNS14000000',factory:c=>createBlsLaborOfficialAdapter({...c,apiKey:c.blsApiKey??c.apiKey})},
 {gateSourceId:'bea_official',canonicalSourceId:'bea_official',capability:'growth_activity_indicator',readiness:'live_capable',reason:'BEA NIPA T10101 quarterly GDP profile',factory:c=>createBeaGrowthOfficialAdapter({...c,apiKey:c.beaApiKey??c.apiKey})},
 {gateSourceId:'census_official',canonicalSourceId:'census_official',capability:'growth_activity_indicator',readiness:'live_capable',reason:'Census EITS monthly retail trade profile',factory:c=>createCensusGrowthOfficialAdapter({...c,apiKey:c.censusApiKey??c.apiKey})},
 {gateSourceId:'boe_official',canonicalSourceId:'boe_official',capability:'policy_rate_series',readiness:'live_capable',reason:'BoE IADB IUDBEDR Official Bank Rate',factory:c=>createBoePolicyOfficialAdapter(c)},
 {gateSourceId:'rba_official',canonicalSourceId:'rba_official',capability:'policy_rate_series',readiness:'live_capable',reason:'RBA official cash-rate target table',factory:c=>createRbaPolicyOfficialAdapter(c)},
 {gateSourceId:'rbnz_official',canonicalSourceId:'rbnz_official',capability:'policy_rate_series',readiness:'live_capable',reason:'RBNZ official OCR decision history',factory:c=>createRbnzPolicyOfficialAdapter(c)},
 {gateSourceId:'bank_of_canada_official',canonicalSourceId:'bank_of_canada_official',capability:'policy_rate_series',readiness:'live_capable',reason:'Bank of Canada Valet V39079',factory:c=>createBankOfCanadaPolicyOfficialAdapter(c)},
 {gateSourceId:'statistics_canada_official',canonicalSourceId:'statistics_canada_official',capability:'macro_indicator_series',readiness:'live_capable',reason:'Statistics Canada WDS CPI vector 41690973',factory:c=>createStatisticsCanadaMacroOfficialAdapter(c)},
 {gateSourceId:'eia_official',canonicalSourceId:'eia_official',capability:'energy_commodity_series',readiness:'live_capable',reason:'EIA API v2 WTI RWTC profile',factory:c=>createEiaEnergyOfficialAdapter({...c,apiKey:c.eiaApiKey??c.apiKey})},
 {gateSourceId:'world_bank_official',canonicalSourceId:'world_bank_official',capability:'growth_activity_indicator',readiness:'live_capable',reason:'World Bank V2 WLD GDP growth indicator',factory:c=>createWorldBankGrowthOfficialAdapter(c)},
 blocked('federal_reserve','federal_reserve_official','central_bank_balance_sheet','Federal Reserve H.4.1 DDP transition requires a pinned replacement machine profile',{date:'2026-09-10',value:1,label:'H.4.1 fixture marker',region:'united_states',evidenceClass:'central_bank_balance_sheet'},'fixture_parser_ready'),
 blocked('sec_edgar','sec_edgar','regulatory_filing_reference','SEC EDGAR requires a server-owned CIK/use-case profile before live execution',{date:'2026-06-30',value:1,label:'SEC filing fixture marker',region:'united_states',evidenceClass:'regulatory_filings'},'fixture_parser_ready'),
 blocked('eurostat_official','eurostat_official','inflation_indicator','Eurostat HICP dimensions must be pinned before live execution',{date:'2026-06-01',value:2.2,label:'Euro-area HICP fixture marker',region:'euro_area',evidenceClass:'inflation'},'fixture_parser_ready'),
 blocked('destatis_official','destatis_official','inflation_indicator','GENESIS CPI table/filter contract is not yet pinned',{date:'2026-06-01',value:2.0,label:'Germany CPI fixture marker',region:'germany',evidenceClass:'inflation'},'fixture_parser_ready'),
 blocked('ons_official','ons_official','inflation_indicator','ONS CPIH latest-version observation dimensions must be pinned',{date:'2026-06-01',value:3.1,label:'UK CPIH fixture marker',region:'united_kingdom',evidenceClass:'inflation'},'fixture_parser_ready'),
 blocked('uk_dmo_official','uk_dmo_official','debt_supply_calendar','UK DMO machine-download profile is not pinned; no gilt market-yield substitution is allowed',{date:'2026-06-01',value:1,label:'UK DMO issuance fixture marker',region:'united_kingdom',evidenceClass:'government_debt_supply'},'fixture_parser_ready'),
 blocked('boj_public','boj_official','policy_rate_series','BOJ 2026 Time-Series API series code must be pinned from the official manual',{date:'2026-06-17',value:0.5,label:'BOJ policy fixture marker',region:'japan',evidenceClass:'central_bank_policy'},'fixture_parser_ready'),
 blocked('japan_mof_official','japan_mof_official','macro_indicator_series','MOF FX-intervention CSV is release-derived and requires a trusted release-index resolver',{date:'2026-06-30',value:0,label:'Japan FX intervention fixture marker',region:'japan',evidenceClass:'economic_indicator'},'fixture_parser_ready'),
 blocked('snb_official','snb_official','policy_rate_series','SNB policy-rate cube and dimensions must be pinned',{date:'2026-06-19',value:0,label:'SNB policy fixture marker',region:'switzerland',evidenceClass:'central_bank_policy'},'fixture_parser_ready'),
 blocked('swiss_fso_official','swiss_fso_official','macro_indicator_series','Swiss FSO PxWeb table/dimensions must be pinned',{date:'2026-06-01',value:1,label:'Swiss macro fixture marker',region:'switzerland',evidenceClass:'economic_indicator'},'fixture_parser_ready'),
 blocked('abs_official','abs_official','macro_indicator_series','ABS SDMX dataflow/dimension profile must be pinned',{date:'2026-Q2',value:1,label:'Australia macro fixture marker',region:'australia',evidenceClass:'economic_indicator'},'fixture_parser_ready'),
 blocked('stats_nz_official','stats_nz_official','macro_indicator_series','Stats NZ Aotearoa Data Explorer subscription and product profile are required',{date:'2026-Q2',value:1,label:'New Zealand macro fixture marker',region:'new_zealand',evidenceClass:'economic_indicator'},'fixture_parser_ready'),
 blocked('imf_official','imf_official','macro_indicator_series','IMF current SDMX dataflow profile must be pinned; legacy endpoint substitution is forbidden',{date:'2025',value:1,label:'IMF macro fixture marker',region:'global',evidenceClass:'economic_indicator'},'fixture_parser_ready'),
 blocked('oecd_official','oecd_official','growth_activity_indicator','OECD Data Explorer growth/CLI flow and key must be pinned',{date:'2026-06-01',value:1,label:'OECD growth fixture marker',region:'global',evidenceClass:'growth_activity'},'fixture_parser_ready'),
 blocked('bis_official','bis_official','cross_market_rate_series','BIS SDMX v2 dataflow/key must be pinned',{date:'2026-06-01',value:1,label:'BIS cross-market fixture marker',region:'global',evidenceClass:'cross_market_rates'},'fixture_parser_ready')
] as const;

export const getOfficialAdapterCatalogEntry=(gateSourceId:string,capability:ProviderCapabilityKind)=>OFFICIAL_ADAPTER_CATALOG.find(x=>x.gateSourceId===gateSourceId&&x.capability===capability)??null;
export const createOfficialAdapter=(gateSourceId:string,capability:ProviderCapabilityKind,config:OfficialAdapterFactoryConfig={}):MarketEvidenceProviderAdapter|null=>getOfficialAdapterCatalogEntry(gateSourceId,capability)?.factory(config)??null;
export const listOfficialLiveCapableAdapters=()=>OFFICIAL_ADAPTER_CATALOG.filter(x=>x.readiness==='live_capable');
