import type { MarketEvidenceClass, NormalizedMarketEvidencePayload, ProviderCapabilityKind, ProviderSourceRequest, ProviderSourceResponse } from '@elceo/types';
import type { MarketEvidenceProviderAdapter, ProviderManagedExecution } from '../normalization-contracts';
import { buildMetadataJson, buildNormalizedPayloadId, buildValuesJson } from '../normalization-helpers';
import { getProviderDescriptor } from '../provider-capability-registry';

export type ResearchOfficialAdapterMode='fixture'|'live_disabled'|'live_enabled';
export type ResearchOfficialAdapterConfig={mode?:ResearchOfficialAdapterMode;fetchImpl?:typeof fetch;timeoutMs?:number|null};
type Point={date:string;value:number;label:string;unit:string|null;metadata?:Record<string,unknown>};
type AdapterSpec={gateSourceId:string;canonicalSourceId:string;capability:ProviderCapabilityKind;evidenceClass:MarketEvidenceClass;region:string;label:string;buildUrl:(request:ProviderSourceRequest)=>string;parse:(raw:string)=>Point[];fixtureRaw:string};
type ResolvedConfig={mode:ResearchOfficialAdapterMode;fetchImpl:typeof fetch;timeoutMs:number};

class ResearchedOfficialAdapter implements MarketEvidenceProviderAdapter{
 readonly descriptor;
 constructor(private readonly spec:AdapterSpec,private readonly config:ResearchOfficialAdapterConfig={}){this.descriptor=getProviderDescriptor(spec.gateSourceId)??(()=>{throw new Error(`missing_official_descriptor:${spec.gateSourceId}`)})();}
 async fetch(request:ProviderSourceRequest):Promise<ProviderSourceResponse>{return this.fetchInternal(request);}
 async fetchManaged(request:ProviderSourceRequest,execution:ProviderManagedExecution):Promise<ProviderSourceResponse>{return this.fetchInternal(request,execution);}
 private async fetchInternal(request:ProviderSourceRequest,execution?:ProviderManagedExecution):Promise<ProviderSourceResponse>{
  if(request.providerId!==this.spec.gateSourceId||request.capability!==this.spec.capability)return fail(request,'official_source_request_mismatch','Official-source request does not match the server-owned adapter profile','unsupported');
  const cfg=resolveConfig(this.config);
  if(cfg.mode==='fixture')return{...base(request),status:'success',rawPayloadJson:this.spec.fixtureRaw,sourceUrl:`fixture://${this.spec.gateSourceId}/${this.spec.capability}`};
  if(cfg.mode!=='live_enabled')return fail(request,'official_source_live_disabled','Official-source live fetch is disabled');
  const url=this.spec.buildUrl(request),controller=execution?null:new AbortController(),timer=execution?null:setTimeout(()=>controller!.abort(),cfg.timeoutMs),signal=execution?.signal??controller!.signal;
  try{const response=await cfg.fetchImpl(url,{signal,headers:{Accept:'text/html,application/json,text/csv;q=0.9,*/*;q=0.5'}});if(!response.ok)return fail(request,response.status===429?'rate_limited':response.status>=500?'provider_5xx':'official_source_request_rejected',`${this.spec.gateSourceId} request failed (${response.status})`);const raw=await response.text();if(raw.trim()==='')return{...base(request),status:'empty',sourceUrl:url,rawPayloadJson:raw};return{...base(request),status:'success',sourceUrl:url,rawPayloadJson:raw};}catch(error){if(error instanceof Error&&error.name==='AbortError')return fail(request,'official_source_timeout',`${this.spec.gateSourceId} request timed out`);return fail(request,'official_source_fetch_error',`${this.spec.gateSourceId} request failed`);}finally{if(timer)clearTimeout(timer);}
 }
 async normalize(response:ProviderSourceResponse):Promise<NormalizedMarketEvidencePayload[]>{if(!response.rawPayloadJson||response.rawPayloadJson.trim()==='')return[];const points=this.spec.parse(response.rawPayloadJson);return points.map((point,index)=>{const observedAt=toObservedAt(point.date);return{payloadId:buildNormalizedPayloadId(this.spec.canonicalSourceId,this.spec.capability,observedAt,null),evidenceTypeId:this.spec.capability,evidenceClass:this.spec.evidenceClass,providerId:this.spec.canonicalSourceId,sourceId:this.spec.canonicalSourceId,region:this.spec.region,asset:null,observedAt,publishedAt:null,normalizedAt:response.fetchedAt,confidenceScore:96,dataQuality:'high',valuesJson:buildValuesJson({value:point.value,label:point.label,unit:point.unit,date:point.date}),metadataJson:buildMetadataJson({canonicalSourceId:this.spec.canonicalSourceId,gateSourceId:this.spec.gateSourceId,requestId:response.requestId,sourceUrl:response.sourceUrl,row:index,...(point.metadata??{})})};});}
}

const FED:AdapterSpec={gateSourceId:'federal_reserve',canonicalSourceId:'federal_reserve_official',capability:'central_bank_balance_sheet',evidenceClass:'central_bank_balance_sheet',region:'united_states',label:'Federal Reserve total assets',buildUrl:()=> 'https://www.federalreserve.gov/releases/h41/current/',parse:parseFederalReserveH41,fixtureRaw:'<table><caption>5. Consolidated Statement of Condition of All Federal Reserve Banks</caption><tr><th>Assets, liabilities, and capital</th><th>Eliminations from consolidation</th><th>Wednesday Sep 9, 2026</th></tr><tr><td>Total assets</td><td>(0)</td><td>6,740,619</td><td>+1</td></tr></table>'};
const EUROSTAT:AdapterSpec={gateSourceId:'eurostat_official',canonicalSourceId:'eurostat_official',capability:'inflation_indicator',evidenceClass:'inflation',region:'euro_area',label:'Euro area HICP annual rate',buildUrl:()=> 'https://ec.europa.eu/eurostat/api/dissemination/sdmx/3.0/data/dataflow/ESTAT/prc_hicp_minr/1.0?c%5Bfreq%5D=M&c%5Bunit%5D=RCH_A&c%5Bcoicop18%5D=TOTAL&c%5Bgeo%5D=EA21&format=csvdata&formatVersion=2.0&compress=false',parse:raw=>parseSdmxCsv(raw,'Euro area HICP annual rate','%'),fixtureRaw:'STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,freq,unit,coicop18,geo,TIME_PERIOD,OBS_VALUE\nDATAFLOW,ESTAT:prc_hicp_minr(1.0),HICP monthly data,,M,RCH_A,TOTAL,EA21,2026-07,2.1'};
const ONS:AdapterSpec={gateSourceId:'ons_official',canonicalSourceId:'ons_official',capability:'inflation_indicator',evidenceClass:'inflation',region:'united_kingdom',label:'UK CPIH All Items annual rate',buildUrl:()=> 'https://www.ons.gov.uk/economy/inflationandpriceindices/timeseries/l55o/mm23',parse:parseOnsL55OHtml,fixtureRaw:'<html><h1>CPIH ANNUAL RATE 00: ALL ITEMS 2015=100</h1><p>Series ID: L55O</p><table><tr><th>Period</th><th>Value</th></tr><tr><td>2026 JUN</td><td>2.8</td></tr><tr><td>2026 JUL</td><td>3.1</td></tr></table></html>'};
const BOJ:AdapterSpec={gateSourceId:'boj_public',canonicalSourceId:'boj_official',capability:'policy_rate_series',evidenceClass:'central_bank_policy',region:'japan',label:'BOJ uncollateralized overnight call rate average',buildUrl:request=>{const start=monthOffset(request.requestedAt,-2).replace('-','');return`https://www.stat-search.boj.or.jp/api/v1/getDataCode?format=json&lang=en&db=FM01&code=STRDCLUCON&startDate=${start}`;},parse:parseBojJson,fixtureRaw:JSON.stringify({STATUS:200,MESSAGEID:'M1810001',MESSAGE:'Successfully completed',PARAMETER:{FORMAT:'JSON',LANG:'EN',DB:'FM01'},NEXTPOSITION:null,RESULTSET:[{SERIES_CODE:'STRDCLUCON',NAME_OF_TIME_SERIES:'Call Rate, Uncollateralized Overnight, Average',UNIT:'percent per annum',FREQUENCY:'DAILY',CATEGORY:'Financial Markets',LAST_UPDATE:'20260911',VALUES:{SURVEY_DATES:[20260910,20260911],VALUES:[0.5,0.5]}}]})};
const SNB:AdapterSpec={gateSourceId:'snb_official',canonicalSourceId:'snb_official',capability:'policy_rate_series',evidenceClass:'central_bank_policy',region:'switzerland',label:'SNB policy rate',buildUrl:()=> 'https://data.snb.ch/api/cube/snboffzisa/data/json/en?dimSel=D0%28LZ%29',parse:parseSnbJson,fixtureRaw:JSON.stringify({timeseries:[{header:[{dim:'Official interest rates',dimItem:'SNB policy rate'}],metadata:{key:'EPB@SNB.snboffzisa{LZ}',frequency:'P1M',scale:'',unit:'In percent'},values:[{date:'2026-05',value:0},{date:'2026-06',value:0}]}]})};
const ABS:AdapterSpec={gateSourceId:'abs_official',canonicalSourceId:'abs_official',capability:'inflation_indicator',evidenceClass:'inflation',region:'australia',label:'Australia All Groups CPI',buildUrl:()=> 'https://data.api.abs.gov.au/rest/data/ABS,CPI,2.0.0/1.10001.10.50.M?format=csvfilewithlabels',parse:raw=>parseSdmxCsv(raw,'Australia All Groups CPI',null),fixtureRaw:'DATAFLOW,MEASURE,INDEX,REGION,FREQ,TIME_PERIOD,OBS_VALUE\nABS:CPI(2.0.0),1,10001,10,M,2026-07,140.2'};
const OECD:AdapterSpec={gateSourceId:'oecd_official',canonicalSourceId:'oecd_official',capability:'growth_activity_indicator',evidenceClass:'growth_activity',region:'global',label:'OECD G20 Composite Leading Indicator',buildUrl:request=>`https://sdmx.oecd.org/public/rest/data/OECD.SDD.STES,DSD_STES%40DF_CLI,4.1/G20.M.LI...AA...H?startPeriod=${encodeURIComponent(monthOffset(request.requestedAt,-24))}&dimensionAtObservation=AllDimensions`,parse:raw=>parseSdmxCsv(raw,'OECD G20 Composite Leading Indicator','index'),fixtureRaw:'REF_AREA,FREQ,MEASURE,ADJUSTMENT,TRANSFORMATION,UNIT_MEASURE,METHODOLOGY,TIME_PERIOD,OBS_VALUE\nG20,M,LI,,,AA,,2026-06,100.4'};
const CBOE:AdapterSpec={gateSourceId:'cboe_official',canonicalSourceId:'cboe_official',capability:'end_of_day_prices',evidenceClass:'risk_sentiment',region:'united_states',label:'Cboe VIX close',buildUrl:()=> 'https://cdn.cboe.com/api/global/us_indices/daily_prices/VIX_History.csv',parse:parseCboeVixCsv,fixtureRaw:'DATE,OPEN,HIGH,LOW,CLOSE\n09/10/2026,16.21,17.02,15.74,16.48\n09/11/2026,17.51,17.71,15.59,15.84'};

export const createFederalReserveH41OfficialAdapter=(config:ResearchOfficialAdapterConfig={})=>new ResearchedOfficialAdapter(FED,config);
export const createEurostatHicpOfficialAdapter=(config:ResearchOfficialAdapterConfig={})=>new ResearchedOfficialAdapter(EUROSTAT,config);
export const createOnsCpihOfficialAdapter=(config:ResearchOfficialAdapterConfig={})=>new ResearchedOfficialAdapter(ONS,config);
export const createBojPolicyOfficialAdapter=(config:ResearchOfficialAdapterConfig={})=>new ResearchedOfficialAdapter(BOJ,config);
export const createSnbPolicyOfficialAdapter=(config:ResearchOfficialAdapterConfig={})=>new ResearchedOfficialAdapter(SNB,config);
export const createAbsCpiOfficialAdapter=(config:ResearchOfficialAdapterConfig={})=>new ResearchedOfficialAdapter(ABS,config);
export const createOecdCliOfficialAdapter=(config:ResearchOfficialAdapterConfig={})=>new ResearchedOfficialAdapter(OECD,config);
export const createCboeVixEodOfficialAdapter=(config:ResearchOfficialAdapterConfig={})=>new ResearchedOfficialAdapter(CBOE,config);

function resolveConfig(config:ResearchOfficialAdapterConfig):ResolvedConfig{return{mode:config.mode??'live_disabled',fetchImpl:config.fetchImpl??fetch,timeoutMs:config.timeoutMs&&Number.isFinite(config.timeoutMs)&&config.timeoutMs>0?config.timeoutMs:10000};}
function base(request:ProviderSourceRequest):ProviderSourceResponse{return{requestId:request.requestId,providerId:request.providerId,capability:request.capability,status:'failed',fetchedAt:request.requestedAt,sourceUrl:null,rawPayloadJson:null,errorCode:null,errorMessage:null};}
function fail(request:ProviderSourceRequest,errorCode:string,errorMessage:string,status:'failed'|'unsupported'='failed'):ProviderSourceResponse{return{...base(request),status,errorCode,errorMessage};}

function parseFederalReserveH41(raw:string):Point[]{const compact=decodeHtml(raw).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ');const tableMatch=compact.match(/5\.\s*Consolidated Statement of Condition of All Federal Reserve Banks[\s\S]*?(?:6\.\s|$)/i);const scope=tableMatch?.[0]??compact;const dateMatch=scope.match(/Wednesday[\s\u00a0]+([A-Z][a-z]{2,8})[\s\u00a0]+(\d{1,2}),?[\s\u00a0]+(20\d{2})/i);const assetMatch=scope.match(/Total assets[\s\S]{0,500}?(-?\d[\d,]*)/i);if(!dateMatch||!assetMatch)throw new Error('federal_reserve_h41_malformed_payload');const date=`${dateMatch[3]}-${monthNumber(dateMatch[1]!)}-${String(Number(dateMatch[2])).padStart(2,'0')}`,value=Number(assetMatch[1]!.replace(/,/g,''));if(!Number.isFinite(value))throw new Error('federal_reserve_h41_invalid_total_assets');return[{date,value,label:'Federal Reserve total assets',unit:'USD millions',metadata:{series:'H41/H41/RESPPA_N.WW',table:'5. Consolidated Statement of Condition of All Federal Reserve Banks'}}];}
function parseOnsL55OHtml(raw:string):Point[]{const text=decodeHtml(raw).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ');if(!/Series ID\s*:?\s*L55O/i.test(text)&&!/CPIH ANNUAL RATE 00:\s*ALL ITEMS/i.test(text))throw new Error('ons_l55o_identity_missing');const matches=[...text.matchAll(/\b(20\d{2})\s+(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)\s+(-?\d+(?:\.\d+)?)/gi)];if(matches.length===0)throw new Error('ons_l55o_no_monthly_observations');return matches.map(m=>({date:`${m[1]}-${monthNumber(m[2]!)}`,value:Number(m[3]),label:'UK CPIH All Items annual rate',unit:'%'})).filter(p=>Number.isFinite(p.value));}
function parseBojJson(raw:string):Point[]{const value=JSON.parse(raw) as unknown;if(!isRecord(value)||Number(value.STATUS)!==200||!Array.isArray(value.RESULTSET))throw new Error('boj_malformed_response');const series=value.RESULTSET.find(x=>isRecord(x)&&x.SERIES_CODE==='STRDCLUCON');if(!isRecord(series)||!isRecord(series.VALUES)||!Array.isArray(series.VALUES.SURVEY_DATES)||!Array.isArray(series.VALUES.VALUES))throw new Error('boj_strdclucon_missing');const dates=series.VALUES.SURVEY_DATES,values=series.VALUES.VALUES;if(dates.length!==values.length)throw new Error('boj_date_value_length_mismatch');return dates.map((date,index)=>({date:normalizeCompactPeriod(date),value:requiredFinite(values[index],'boj_value'),label:typeof series.NAME_OF_TIME_SERIES==='string'?series.NAME_OF_TIME_SERIES:'BOJ uncollateralized overnight call rate average',unit:typeof series.UNIT==='string'?series.UNIT:'percent per annum',metadata:{seriesCode:'FM01:STRDCLUCON',lastUpdate:series.LAST_UPDATE??null}}));}
function parseSnbJson(raw:string):Point[]{const value=JSON.parse(raw) as unknown;if(!isRecord(value)||!Array.isArray(value.timeseries))throw new Error('snb_malformed_response');const series=value.timeseries.find(x=>isRecord(x)&&isRecord(x.metadata)&&typeof x.metadata.key==='string'&&/snboffzisa\{LZ\}/i.test(x.metadata.key));if(!isRecord(series)||!isRecord(series.metadata)||!Array.isArray(series.values))throw new Error('snb_policy_series_missing');return series.values.filter(isRecord).filter(x=>x.value!==undefined&&x.value!==null).map(x=>({date:requiredString(x.date,'snb_date'),value:requiredFinite(x.value,'snb_value'),label:'SNB policy rate',unit:typeof series.metadata.unit==='string'?series.metadata.unit:'%',metadata:{seriesKey:series.metadata.key,frequency:series.metadata.frequency??null}}));}
function parseSdmxCsv(raw:string,label:string,unit:string|null):Point[]{const rows=parseCsv(raw);if(rows.length<2)throw new Error('sdmx_csv_empty');const headers=rows[0]!.map(x=>x.trim().replace(/^\uFEFF/,'')),timeIndex=headers.indexOf('TIME_PERIOD'),valueIndex=headers.indexOf('OBS_VALUE');if(timeIndex<0||valueIndex<0)throw new Error('sdmx_csv_required_columns_missing');return rows.slice(1).filter(r=>r.some(Boolean)).map(r=>({date:r[timeIndex]??'',value:requiredFinite(r[valueIndex],'sdmx_obs_value'),label,unit,metadata:{sdmxDimensions:Object.fromEntries(headers.map((h,i)=>[h,r[i]??null]).filter(([h])=>h!=='OBS_VALUE'))}}));}
function parseCboeVixCsv(raw:string):Point[]{const rows=parseCsv(raw);if(rows.length<2)throw new Error('cboe_vix_empty');const headers=rows[0]!.map(x=>x.trim().toUpperCase().replace(/^\uFEFF/,'')),dateIndex=headers.indexOf('DATE'),closeIndex=headers.indexOf('CLOSE');if(dateIndex<0||closeIndex<0)throw new Error('cboe_vix_required_columns_missing');return rows.slice(1).filter(r=>r.some(Boolean)).map(r=>({date:r[dateIndex]??'',value:requiredFinite(r[closeIndex],'cboe_vix_close'),label:'Cboe VIX close',unit:'index points',metadata:{index:'VIX',priceField:'CLOSE'}}));}
function parseCsv(raw:string):string[][]{const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<raw.length;i++){const ch=raw[i]!;if(quoted){if(ch==='"'&&raw[i+1]==='"'){cell+='"';i++;}else if(ch==='"')quoted=false;else cell+=ch;}else if(ch==='"')quoted=true;else if(ch===','){row.push(cell);cell='';}else if(ch==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell='';}else cell+=ch;}if(cell!==''||row.length){row.push(cell.replace(/\r$/,''));rows.push(row);}return rows;}
function toObservedAt(date:string):string{const value=date.trim();if(/^\d{4}-\d{2}-\d{2}$/.test(value))return`${value}T00:00:00.000Z`;if(/^\d{2}\/\d{2}\/\d{4}$/.test(value)){const [m,d,y]=value.split('/');return`${y}-${m}-${d}T00:00:00.000Z`;}if(/^\d{4}-\d{2}$/.test(value))return`${value}-01T00:00:00.000Z`;if(/^\d{4}-Q[1-4]$/.test(value)){const q=Number(value.at(-1));return`${value.slice(0,4)}-${String((q-1)*3+1).padStart(2,'0')}-01T00:00:00.000Z`;}if(/^\d{4}$/.test(value))return`${value}-01-01T00:00:00.000Z`;const timestamp=Date.parse(value);if(!Number.isFinite(timestamp))throw new Error(`official_invalid_observation_date:${value}`);return new Date(timestamp).toISOString();}
function normalizeCompactPeriod(value:unknown):string{const s=String(value);if(/^\d{8}$/.test(s))return`${s.slice(0,4)}-${s.slice(4,6)}-${s.slice(6,8)}`;if(/^\d{6}$/.test(s))return`${s.slice(0,4)}-${s.slice(4,6)}`;if(/^\d{4}$/.test(s))return s;throw new Error('boj_invalid_survey_date');}
function monthOffset(iso:string,offset:number):string{const date=new Date(iso);if(Number.isNaN(date.getTime()))throw new Error('official_invalid_requested_at');date.setUTCDate(1);date.setUTCMonth(date.getUTCMonth()+offset);return`${date.getUTCFullYear()}-${String(date.getUTCMonth()+1).padStart(2,'0')}`;}
function monthNumber(name:string):string{const months:Record<string,string>={JAN:'01',JANUARY:'01',FEB:'02',FEBRUARY:'02',MAR:'03',MARCH:'03',APR:'04',APRIL:'04',MAY:'05',JUN:'06',JUNE:'06',JUL:'07',JULY:'07',AUG:'08',AUGUST:'08',SEP:'09',SEPT:'09',SEPTEMBER:'09',OCT:'10',OCTOBER:'10',NOV:'11',NOVEMBER:'11',DEC:'12',DECEMBER:'12'};const value=months[name.trim().toUpperCase()];if(!value)throw new Error(`invalid_month:${name}`);return value;}
function decodeHtml(value:string):string{return value.replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/&minus;|&#8722;/gi,'-').replace(/&#44;/g,',');}
function requiredFinite(value:unknown,name:string):number{const number=typeof value==='number'?value:typeof value==='string'?Number(value.replace(/[,\s]/g,'')):NaN;if(!Number.isFinite(number))throw new Error(`${name}_invalid`);return number;}
function requiredString(value:unknown,name:string):string{if(typeof value!=='string'||value.trim()==='')throw new Error(`${name}_missing`);return value.trim();}
function isRecord(value:unknown):value is Record<string,any>{return typeof value==='object'&&value!==null&&!Array.isArray(value);}
