import type { MarketEvidenceClass, NormalizedMarketEvidencePayload, ProviderCapabilityKind, ProviderSourceRequest, ProviderSourceResponse } from '@elceo/types';
import type { MarketEvidenceProviderAdapter, ProviderManagedExecution } from '../normalization-contracts';
import { buildMetadataJson, buildNormalizedPayloadId, buildValuesJson } from '../normalization-helpers';
import { getProviderDescriptor } from '../provider-capability-registry';

export type StructuralMacroAdapterMode='fixture'|'live_disabled'|'live_enabled';
export type StructuralMacroAdapterConfig={mode?:StructuralMacroAdapterMode;apiKey?:string|null;fetchImpl?:typeof fetch;timeoutMs?:number|null};
type ResolvedConfig={mode:StructuralMacroAdapterMode;apiKey:string|null;fetchImpl:typeof fetch;timeoutMs:number};
type StructuralPoint={date:string;value:number;region:string;indicator:string;unit:string|null;metadata:Record<string,unknown>};
type StructuralSpec={gateSourceId:string;canonicalSourceId:'bls_official'|'census_official'|'oecd_official'|'bis_official';capability:ProviderCapabilityKind;evidenceClass:MarketEvidenceClass;indicatorFamily:string;buildRequest:(request:ProviderSourceRequest,cfg:ResolvedConfig)=>{url:string;init?:RequestInit};parse:(raw:string)=>StructuralPoint[];fixtureRaw:string;confidence:number};

const LAUNCH_OECD_AREAS='USA+EA+GBR+JPN+CHE+AUS+NZL+CAN';
const LAUNCH_BIS_AREAS='US+XM+GB+JP+CH+AU+NZ+CA';

class StructuralMacroAdapter implements MarketEvidenceProviderAdapter{
 readonly descriptor;
 constructor(private readonly spec:StructuralSpec,private readonly config:StructuralMacroAdapterConfig={}){this.descriptor=getProviderDescriptor(spec.gateSourceId)??(()=>{throw new Error(`missing_structural_macro_descriptor:${spec.gateSourceId}`)})();}
 async fetch(request:ProviderSourceRequest):Promise<ProviderSourceResponse>{return this.fetchInternal(request);}
 async fetchManaged(request:ProviderSourceRequest,execution:ProviderManagedExecution):Promise<ProviderSourceResponse>{return this.fetchInternal(request,execution);}
 private async fetchInternal(request:ProviderSourceRequest,execution?:ProviderManagedExecution):Promise<ProviderSourceResponse>{
  if(request.providerId!==this.spec.gateSourceId||request.capability!==this.spec.capability)return fail(request,'structural_macro_request_mismatch','Structural macro request does not match its server-owned profile','unsupported');
  const cfg=resolveConfig(this.config);
  if(cfg.mode==='fixture')return{...base(request),status:'success',sourceUrl:`fixture://${this.spec.gateSourceId}/${this.spec.indicatorFamily}`,rawPayloadJson:this.spec.fixtureRaw};
  if(cfg.mode!=='live_enabled')return fail(request,'structural_macro_live_disabled','Structural macro live fetch is disabled');
  const built=this.spec.buildRequest(request,cfg),controller=execution?null:new AbortController(),timer=execution?null:setTimeout(()=>controller!.abort(),cfg.timeoutMs),signal=execution?.signal??controller!.signal;
  try{
   const headers={Accept:'text/csv,application/json;q=0.9,*/*;q=0.5',...((built.init?.headers??{}) as Record<string,string>)};
   const response=await cfg.fetchImpl(built.url,{...built.init,headers,signal});
   if(!response.ok)return fail(request,response.status===429?'rate_limited':response.status===401||response.status===403?'structural_macro_access_denied':response.status>=500?'provider_5xx':'structural_macro_request_rejected',`${this.spec.gateSourceId} request failed (${response.status})`);
   const raw=await response.text();
   if(raw.trim()==='')return{...base(request),status:'empty',sourceUrl:sanitizeUrl(built.url),rawPayloadJson:raw};
   return{...base(request),status:'success',sourceUrl:sanitizeUrl(built.url),rawPayloadJson:raw};
  }catch(error){if(error instanceof Error&&error.name==='AbortError')return fail(request,'structural_macro_timeout',`${this.spec.gateSourceId} request timed out`);return fail(request,'structural_macro_fetch_error',`${this.spec.gateSourceId} request failed`);}finally{if(timer)clearTimeout(timer);}
 }
 async normalize(response:ProviderSourceResponse):Promise<NormalizedMarketEvidencePayload[]>{
  if(!response.rawPayloadJson?.trim())return[];
  const points=this.spec.parse(response.rawPayloadJson);
  return points.map((point,index)=>{const observedAt=toObservedAt(point.date);return{payloadId:`${buildNormalizedPayloadId(this.spec.canonicalSourceId,this.spec.capability,observedAt,null)}:${this.spec.indicatorFamily}:${point.region}:${index}`,evidenceTypeId:this.spec.capability,evidenceClass:this.spec.evidenceClass,providerId:this.spec.canonicalSourceId,sourceId:this.spec.canonicalSourceId,region:point.region,asset:null,observedAt,publishedAt:null,normalizedAt:response.fetchedAt,confidenceScore:this.spec.confidence,dataQuality:'high',valuesJson:buildValuesJson({value:point.value,indicator:point.indicator,unit:point.unit,date:point.date}),metadataJson:buildMetadataJson({canonicalSourceId:this.spec.canonicalSourceId,gateSourceId:this.spec.gateSourceId,indicatorFamily:this.spec.indicatorFamily,requestId:response.requestId,sourceUrl:response.sourceUrl,...point.metadata})};});
 }
}

const BLS_PAYROLLS:StructuralSpec={gateSourceId:'bls_payrolls',canonicalSourceId:'bls_official',capability:'labor_market_indicator',evidenceClass:'labor_market',indicatorFamily:'nonfarm_payrolls_change',confidence:99,buildRequest:(request,cfg)=>{const year=new Date(request.requestedAt).getUTCFullYear();const body:Record<string,unknown>={seriesid:['CES0000000001'],startyear:String(year-2),endyear:String(year)};if(cfg.apiKey)body.registrationkey=cfg.apiKey;return{url:'https://api.bls.gov/publicAPI/v2/timeseries/data/',init:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}};},parse:parseBlsPayrollChange,fixtureRaw:JSON.stringify({status:'REQUEST_SUCCEEDED',Results:{series:[{seriesID:'CES0000000001',data:[{year:'2026',period:'M08',periodName:'August',value:'159850'},{year:'2026',period:'M07',periodName:'July',value:'159705'},{year:'2026',period:'M06',periodName:'June',value:'159632'}]}]}})};

const CENSUS_HOUSING:StructuralSpec={gateSourceId:'census_housing',canonicalSourceId:'census_official',capability:'macro_indicator_series',evidenceClass:'economic_indicator',indicatorFamily:'housing_starts_permits',confidence:98,buildRequest:(request,cfg)=>{const end=month(request.requestedAt),start=monthOffset(request.requestedAt,-18);const url=new URL('https://api.census.gov/data/timeseries/eits/resconst');url.searchParams.set('get','cell_value,data_type_code,time_slot_id,error_data,category_code,seasonally_adj');url.searchParams.set('time',`from ${start} to ${end}`);if(cfg.apiKey)url.searchParams.set('key',cfg.apiKey);return{url:url.toString()};},parse:parseCensusHousing,fixtureRaw:JSON.stringify([['cell_value','data_type_code','time_slot_id','error_data','category_code','seasonally_adj','time'],['1239','TOTAL','0','0','ASTARTS','yes','2026-07'],['1443','TOTAL','0','0','APERMITS','yes','2026-07']])};

const OECD_CONSUMER:StructuralSpec=oecdSpec('oecd_consumer_confidence','confidence_consumer',`OECD.SDD.STES,DSD_STES%40DF_CS,4.0/${LAUNCH_OECD_AREAS}.M.CCICP......`,'Composite consumer confidence');
const OECD_BUSINESS:StructuralSpec=oecdSpec('oecd_business_confidence','confidence_business',`OECD.SDD.STES,DSD_STES%40DF_CLI,4.1/${LAUNCH_OECD_AREAS}.M.BCICP...AA.IX..H`,'Composite business confidence');
const OECD_MONEY:StructuralSpec=oecdSpec('oecd_monetary','money_supply',`OECD.SDD.STES,DSD_STES%40DF_MONAGG,4.0/${LAUNCH_OECD_AREAS}.M.......`,'Monetary aggregates M1/M2/M3',row=>{const label=field(row,'Measure','MEASURE');return /\bM[123]\b/i.test(label);});
const OECD_BOP:StructuralSpec=oecdSpec('oecd_bop','external_balance_capital_flows',`OECD.SDD.TPS,DSD_BOP%40DF_BOP,1.0/${LAUNCH_OECD_AREAS}.....Q.XDC.Y`,'Balance of payments / financial flows');
const OECD_PPP:StructuralSpec=oecdSpec('oecd_ppp','purchasing_power_parity',`OECD.SDD.TPS,DSD_PPP%40DF_PPP_PPP,1.0/.A..E011..USA+EA+GBR+JPN+CHE+AUS+NZL+CAN`,'GDP purchasing power parity');

const BIS_CREDIT:StructuralSpec=bisSpec('bis_credit','credit_growth',`BIS/WS_TC/2.0/Q.${LAUNCH_BIS_AREAS}.P.A.M.XDC.A`,'Private non-financial sector credit');
const BIS_HOUSING:StructuralSpec=bisSpec('bis_housing','housing_prices',`BIS/WS_SPP/1.0/Q.${LAUNCH_BIS_AREAS}.N.628`,'Selected residential property price index');
const BIS_REER:StructuralSpec=bisSpec('bis_reer','real_effective_exchange_rate',`BIS/WS_EER/1.0/M.R.B.${LAUNCH_BIS_AREAS}`,'Real effective exchange rate, broad basket');

function oecdSpec(gateSourceId:string,indicatorFamily:string,path:string,label:string,filter?:(row:Record<string,string>)=>boolean):StructuralSpec{return{gateSourceId,canonicalSourceId:'oecd_official',capability:'macro_indicator_series',evidenceClass:'economic_indicator',indicatorFamily,confidence:96,buildRequest:request=>{const url=new URL(`https://sdmx.oecd.org/public/rest/data/${path}`);url.searchParams.set('startPeriod',indicatorFamily==='purchasing_power_parity'?String(new Date(request.requestedAt).getUTCFullYear()-4):monthOffset(request.requestedAt,-24));url.searchParams.set('dimensionAtObservation','AllDimensions');url.searchParams.set('format','csvfilewithlabels');return{url:url.toString()};},parse:raw=>parseSdmxRows(raw,label,filter),fixtureRaw:`REF_AREA,Reference area,FREQ,MEASURE,Measure,UNIT_MEASURE,Unit of measure,TIME_PERIOD,OBS_VALUE\nUSA,United States,M,TEST,${label},IX,Index,2026-07,100.2\nGBR,United Kingdom,M,TEST,${label},IX,Index,2026-07,99.8`};}
function bisSpec(gateSourceId:string,indicatorFamily:string,path:string,label:string):StructuralSpec{return{gateSourceId,canonicalSourceId:'bis_official',capability:'macro_indicator_series',evidenceClass:'economic_indicator',indicatorFamily,confidence:97,buildRequest:request=>{const url=new URL(`https://stats.bis.org/api/v2/data/dataflow/${path}`);url.searchParams.set('startPeriod',indicatorFamily==='real_effective_exchange_rate'?monthOffset(request.requestedAt,-24):quarterOffset(request.requestedAt,-12));url.searchParams.set('format','csv');url.searchParams.set('labels','both');return{url:url.toString()};},parse:raw=>parseSdmxRows(raw,label),fixtureRaw:`FREQ,REF_AREA,Reference area,TYPE,BASKET,UNIT_MEASURE,TIME_PERIOD,OBS_VALUE\nM,US,United States,R,B,628,2026-07,101.4\nM,GB,United Kingdom,R,B,628,2026-07,98.7`};}

export const createBlsPayrollOfficialAdapter=(config:StructuralMacroAdapterConfig={})=>new StructuralMacroAdapter(BLS_PAYROLLS,config);
export const createCensusHousingOfficialAdapter=(config:StructuralMacroAdapterConfig={})=>new StructuralMacroAdapter(CENSUS_HOUSING,config);
export const createOecdConsumerConfidenceOfficialAdapter=(config:StructuralMacroAdapterConfig={})=>new StructuralMacroAdapter(OECD_CONSUMER,config);
export const createOecdBusinessConfidenceOfficialAdapter=(config:StructuralMacroAdapterConfig={})=>new StructuralMacroAdapter(OECD_BUSINESS,config);
export const createOecdMonetaryOfficialAdapter=(config:StructuralMacroAdapterConfig={})=>new StructuralMacroAdapter(OECD_MONEY,config);
export const createOecdBopOfficialAdapter=(config:StructuralMacroAdapterConfig={})=>new StructuralMacroAdapter(OECD_BOP,config);
export const createOecdPppOfficialAdapter=(config:StructuralMacroAdapterConfig={})=>new StructuralMacroAdapter(OECD_PPP,config);
export const createBisCreditOfficialAdapter=(config:StructuralMacroAdapterConfig={})=>new StructuralMacroAdapter(BIS_CREDIT,config);
export const createBisHousingOfficialAdapter=(config:StructuralMacroAdapterConfig={})=>new StructuralMacroAdapter(BIS_HOUSING,config);
export const createBisReerOfficialAdapter=(config:StructuralMacroAdapterConfig={})=>new StructuralMacroAdapter(BIS_REER,config);

function parseBlsPayrollChange(raw:string):StructuralPoint[]{const root=JSON.parse(raw) as Record<string,unknown>;if(root.status!=='REQUEST_SUCCEEDED'||!isRecord(root.Results)||!Array.isArray(root.Results.series))throw new Error('bls_payroll_malformed_payload');const series=root.Results.series.find(x=>isRecord(x)&&x.seriesID==='CES0000000001');if(!isRecord(series)||!Array.isArray(series.data))throw new Error('bls_payroll_series_missing');const levels=series.data.filter(isRecord).flatMap(row=>{const period=String(row.period??'');const year=String(row.year??'');const value=number(row.value);if(!/^M(0[1-9]|1[0-2])$/.test(period)||!/^20\d{2}$/.test(year)||value===null)return[];return[{date:`${year}-${period.slice(1)}`,level:value}];}).sort((a,b)=>a.date.localeCompare(b.date));const out:StructuralPoint[]=[];for(let i=1;i<levels.length;i++){const previous=levels[i-1]!,current=levels[i]!;const delta=current.level-previous.level;out.push({date:current.date,value:delta,region:'united_states',indicator:'Nonfarm payroll employment monthly change',unit:'thousands of persons',metadata:{seriesId:'CES0000000001',levelThousands:current.level,previousLevelThousands:previous.level,derivation:'month_over_month_difference_of_seasonally_adjusted_total_nonfarm_payroll_employment',authoritativeLevelSource:'bls_ces'}});}return out.slice(-24);}
function parseCensusHousing(raw:string):StructuralPoint[]{const value=JSON.parse(raw) as unknown;if(!Array.isArray(value)||!Array.isArray(value[0]))throw new Error('census_housing_malformed_payload');const header=value[0].map(String),index=(name:string)=>header.indexOf(name),ci=index('cell_value'),cat=index('category_code'),sa=index('seasonally_adj'),time=index('time');if([ci,cat,sa,time].some(x=>x<0))throw new Error('census_housing_columns_missing');return value.slice(1).flatMap(row=>{if(!Array.isArray(row))return[];const category=String(row[cat]??''),seasonal=String(row[sa]??'').toLowerCase();if(!['ASTARTS','APERMITS'].includes(category)||!['yes','1','true'].includes(seasonal))return[];const v=number(row[ci]),date=String(row[time]??'');if(v===null||!/^20\d{2}-\d{2}$/.test(date))return[];return[{date,value:v,region:'united_states',indicator:category==='ASTARTS'?'Housing starts':'Building permits',unit:'thousands, seasonally adjusted annual rate',metadata:{categoryCode:category,program:'RESCONST',seasonallyAdjusted:true}}];});}
function parseSdmxRows(raw:string,label:string,filter?:(row:Record<string,string>)=>boolean):StructuralPoint[]{const rows=parseCsv(raw);if(rows.length===0)throw new Error('sdmx_csv_empty');return rows.flatMap(row=>{if(filter&&!filter(row))return[];const date=field(row,'TIME_PERIOD','Time period');const value=number(field(row,'OBS_VALUE','Observation value'));const regionCode=field(row,'REF_AREA','Reference area code','BORROWERS_CTY','Reference area');if(!date||value===null||!regionCode)return[];const indicator=field(row,'Measure','MEASURE','Series','UNIT_MEASURE')||label;const unit=field(row,'Unit of measure','UNIT_MEASURE','UNIT_TYPE')||null;const regionLabel=field(row,'Reference area','Borrowers country','BORROWERS_CTY')||regionCode;return[{date,value,region:normalizeRegion(regionCode,regionLabel),indicator:indicator||label,unit,metadata:{refArea:regionCode,refAreaLabel:regionLabel,measure:field(row,'MEASURE','Measure')||null,accountingEntry:field(row,'ACCOUNTING_ENTRY','Accounting entry')||null,flowOrStock:field(row,'FLOW_OR_STOCK_ENTRY','Flow or stock entry')||null,adjustment:field(row,'ADJUSTMENT','Adjustment')||null,basket:field(row,'BASKET','Basket')||null,type:field(row,'TYPE','Type','VALUE')||null}}];});}
function parseCsv(raw:string):Record<string,string>[]{const lines=raw.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());if(lines.length<2)return[];const headers=splitCsv(lines[0]!);return lines.slice(1).map(line=>{const values=splitCsv(line),row:Record<string,string>={};headers.forEach((h,i)=>{row[h.trim()]=values[i]?.trim()??'';});return row;});}
function splitCsv(line:string):string[]{const out:string[]=[],chars=[...line];let value='',quoted=false;for(let i=0;i<chars.length;i++){const ch=chars[i]!;if(ch==='"'){if(quoted&&chars[i+1]==='"'){value+='"';i++;}else quoted=!quoted;}else if(ch===','&&!quoted){out.push(value);value='';}else value+=ch;}out.push(value);return out;}
function field(row:Record<string,string>,...keys:string[]):string{for(const key of keys){const exact=row[key];if(exact?.trim())return exact.trim();const found=Object.entries(row).find(([k,v])=>k.toLowerCase()===key.toLowerCase()&&v.trim());if(found)return found[1].trim();}return'';}
function normalizeRegion(code:string,label:string):string{const map:Record<string,string>={USA:'united_states',US:'united_states',EA:'euro_area',XM:'euro_area',GBR:'united_kingdom',GB:'united_kingdom',JPN:'japan',JP:'japan',CHE:'switzerland',CH:'switzerland',AUS:'australia',AU:'australia',NZL:'new_zealand',NZ:'new_zealand',CAN:'canada',CA:'canada'};return map[code]??label.toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');}
function resolveConfig(config:StructuralMacroAdapterConfig):ResolvedConfig{return{mode:config.mode??'live_disabled',apiKey:config.apiKey?.trim()||null,fetchImpl:config.fetchImpl??fetch,timeoutMs:config.timeoutMs&&Number.isFinite(config.timeoutMs)&&config.timeoutMs>0?config.timeoutMs:12000};}
function base(request:ProviderSourceRequest):ProviderSourceResponse{return{requestId:request.requestId,providerId:request.providerId,capability:request.capability,status:'failed',fetchedAt:request.requestedAt,sourceUrl:null,rawPayloadJson:null,errorCode:null,errorMessage:null};}
function fail(request:ProviderSourceRequest,errorCode:string,errorMessage:string,status:'failed'|'unsupported'='failed'):ProviderSourceResponse{return{...base(request),status,errorCode,errorMessage};}
function sanitizeUrl(value:string):string{try{const url=new URL(value);url.searchParams.delete('key');url.searchParams.delete('registrationkey');return url.toString();}catch{return value;}}
function isRecord(value:unknown):value is Record<string,unknown>{return typeof value==='object'&&value!==null&&!Array.isArray(value);}
function number(value:unknown):number|null{const n=typeof value==='number'?value:Number(String(value??'').replace(/[,\s]/g,''));return Number.isFinite(n)?n:null;}
function month(value:string):string{return new Date(value).toISOString().slice(0,7);}
function monthOffset(value:string,delta:number):string{const d=new Date(value);d.setUTCMonth(d.getUTCMonth()+delta);return d.toISOString().slice(0,7);}
function quarterOffset(value:string,deltaMonths:number):string{const d=new Date(value);d.setUTCMonth(d.getUTCMonth()+deltaMonths);return`${d.getUTCFullYear()}-Q${Math.floor(d.getUTCMonth()/3)+1}`;}
function toObservedAt(value:string):string{if(/^\d{4}-Q[1-4]$/.test(value)){const [y,q]=value.split('-Q');return new Date(Date.UTC(Number(y),(Number(q)-1)*3,1)).toISOString();}if(/^\d{4}-\d{2}$/.test(value))return`${value}-01T00:00:00.000Z`;if(/^\d{4}$/.test(value))return`${value}-01-01T00:00:00.000Z`;const t=Date.parse(value);if(!Number.isFinite(t))throw new Error(`invalid_structural_macro_period:${value}`);return new Date(t).toISOString();}
