import type { MarketDataProviderDescriptor, NormalizedMarketEvidencePayload, ProviderCapabilityKind, ProviderSourceRequest, ProviderSourceResponse } from '@elceo/types';
import type { MarketEvidenceProviderAdapter, ProviderManagedExecution } from '../normalization-contracts';
import { getProviderDescriptor } from '../provider-capability-registry';

type Mode='fixture'|'live_disabled'|'live_enabled';
type Point={date:string;value:number;label:string;unit?:string|null;metadata?:Record<string,unknown>};
type RequestSpec={url:URL;init?:RequestInit};
type AdapterSpec={providerId:string;canonicalSourceId:string;capability:ProviderCapabilityKind;region:string;evidenceClass:string;fixture:readonly Point[];build:(request:ProviderSourceRequest,credentials:OfficialAdapterCredentials)=>RequestSpec;parse:(response:Response)=>Promise<Point[]>};
export type OfficialAdapterCredentials={apiKey?:string|null;subscriptionKey?:string|null;userAgent?:string|null};
export type VerifiedOfficialAdapterConfig=OfficialAdapterCredentials&{mode?:Mode;fetchImpl?:typeof fetch};

const createAdapter=(spec:AdapterSpec,config:VerifiedOfficialAdapterConfig={}):MarketEvidenceProviderAdapter=>{
 const descriptor:MarketDataProviderDescriptor=getProviderDescriptor(spec.providerId)??(()=>{throw new Error(`missing_official_descriptor:${spec.providerId}`);})();
 const fetchInternal=async(request:ProviderSourceRequest,execution?:ProviderManagedExecution):Promise<ProviderSourceResponse>=>{
  if(request.providerId!==spec.providerId||request.capability!==spec.capability)return fail(request,'official_source_request_mismatch');
  const mode=config.mode??'live_disabled';
  if(mode==='fixture')return success(request,spec.fixture,`fixture://${spec.providerId}/${spec.capability}`);
  if(mode!=='live_enabled')return fail(request,'official_source_live_disabled');
  let built:RequestSpec;try{built=spec.build(request,config);}catch(error){return fail(request,error instanceof Error?error.message:'official_source_request_invalid');}
  const init:RequestInit={...(built.init??{}),...(execution?{signal:execution.signal}:{})};
  try{const response=await (config.fetchImpl??fetch)(built.url,init);if(!response.ok)return fail(request,response.status===429?'rate_limited':`${spec.providerId}_http_${response.status}`);const points=await spec.parse(response);if(!points.length)return fail(request,`${spec.providerId}_empty_or_malformed`);return success(request,points,sanitize(built.url));}
  catch(error){if(error instanceof Error&&error.name==='AbortError')return fail(request,`${spec.providerId}_timeout`);return fail(request,`${spec.providerId}_fetch_error`);}
 };
 return{descriptor,fetch:(request)=>fetchInternal(request),fetchManaged:(request,execution)=>fetchInternal(request,execution),normalize:async(response)=>normalizePoints(spec,response)};
};

const normalizePoints=async(spec:AdapterSpec,response:ProviderSourceResponse):Promise<NormalizedMarketEvidencePayload[]>=>{
 if(!response.rawPayloadJson)return[];let points:Point[];try{points=JSON.parse(response.rawPayloadJson) as Point[];}catch{return[];}
 return points.filter(p=>Number.isFinite(p.value)&&validDate(p.date)).map((p,index)=>({payloadId:`${response.requestId}:${index}`,evidenceTypeId:response.capability,evidenceClass:spec.evidenceClass,providerId:spec.canonicalSourceId,sourceId:spec.canonicalSourceId,region:spec.region,asset:null,observedAt:toIso(p.date),publishedAt:null,normalizedAt:response.fetchedAt,confidenceScore:96,dataQuality:'high',valuesJson:JSON.stringify({value:p.value,label:p.label,unit:p.unit??null,date:p.date}),metadataJson:JSON.stringify({canonicalSourceId:spec.canonicalSourceId,gateSourceId:spec.providerId,requestId:response.requestId,sourceUrl:response.sourceUrl,...(p.metadata??{})})}));
};
const requireApiKey=(c:OfficialAdapterCredentials)=>{if(!c.apiKey)throw new Error('missing_api_key');return c.apiKey;};
const isoYear=(request:ProviderSourceRequest)=>String(new Date(request.requestedAt).getUTCFullYear());
const htmlText=(html:string)=>html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/g,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim();
const csvCells=(line:string)=>{const out:string[]=[],re=/(?:^|,)("(?:[^"]|"")*"|[^,]*)/g;let m:RegExpExecArray|null;while((m=re.exec(line)))out.push((m[1]??'').replace(/^"|"$/g,'').replace(/""/g,'"').trim());return out;};
const number=(v:unknown)=>{const n=Number(String(v??'').replace(/,/g,'').trim());return Number.isFinite(n)?n:null;};
const validDate=(value:string)=>Number.isFinite(Date.parse(value.length===10?`${value}T00:00:00Z`:value))||/^\d{4}(?:-Q[1-4]|-\d{2})?$/.test(value);
const toIso=(value:string)=>{if(/^\d{4}-Q[1-4]$/.test(value)){const [,y,q]=/^(\d{4})-Q([1-4])$/.exec(value)!;return new Date(Date.UTC(Number(y),(Number(q)-1)*3,1)).toISOString();}if(/^\d{4}-\d{2}$/.test(value))return new Date(`${value}-01T00:00:00Z`).toISOString();if(/^\d{4}$/.test(value))return new Date(`${value}-01-01T00:00:00Z`).toISOString();const t=Date.parse(value.length===10?`${value}T00:00:00Z`:value);return Number.isFinite(t)?new Date(t).toISOString():new Date(0).toISOString();};
const base=(r:ProviderSourceRequest):ProviderSourceResponse=>({requestId:r.requestId,providerId:r.providerId,capability:r.capability,status:'failed',fetchedAt:new Date().toISOString(),sourceUrl:null,rawPayloadJson:null,errorCode:null,errorMessage:null});
const fail=(r:ProviderSourceRequest,code:string):ProviderSourceResponse=>({...base(r),errorCode:code,errorMessage:code});
const success=(r:ProviderSourceRequest,points:readonly Point[],url:string):ProviderSourceResponse=>({...base(r),status:'success',sourceUrl:url,rawPayloadJson:JSON.stringify(points)});
const sanitize=(url:URL)=>{const clean=new URL(url);for(const key of [...clean.searchParams.keys()])if(/key|token|authorization|userid/i.test(key))clean.searchParams.delete(key);return clean.toString();};
const parsePolicyHtml=(html:string,label:string):Point[]=>{const text=htmlText(html),out:Point[]=[];const re=/(\d{1,2}\s+[A-Z][a-z]{2,8}\s+20\d{2})\s+(?:\+?[-\d.]+\s+)?(\d+(?:\.\d+)?)\b/g;for(const m of text.matchAll(re)){const t=Date.parse(m[1]!),n=number(m[2]);if(Number.isFinite(t)&&n!==null)out.push({date:new Date(t).toISOString().slice(0,10),value:n,label,unit:'percent'});}return out;};
const blsParse=async(response:Response):Promise<Point[]>=>{const body=await response.json() as any,series=body?.Results?.series?.[0],rows=series?.data;if(!Array.isArray(rows))return[];return rows.flatMap((row:any)=>{const n=number(row.value);if(n===null||typeof row.year!=='string'||typeof row.period!=='string'||!/^M\d{2}$/.test(row.period))return[];return[{date:`${row.year}-${row.period.slice(1)}-01`,value:n,label:String(series.seriesID??'BLS series'),unit:null,metadata:{periodName:row.periodName??null}}];});};
const blsSpec=(capability:ProviderCapabilityKind,seriesId:string,evidenceClass:string,fixtureValue:number,label:string):AdapterSpec=>({providerId:'bls_official',canonicalSourceId:'bls_official',capability,region:'united_states',evidenceClass,fixture:[{date:'2026-06-01',value:fixtureValue,label}],build:(request,c)=>{const url=new URL('/publicAPI/v2/timeseries/data/','https://api.bls.gov'),year=isoYear(request);return{url,init:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({seriesid:[seriesId],startyear:String(Number(year)-1),endyear:year,registrationKey:requireApiKey(c)})}};},parse:blsParse});

export const createBlsInflationOfficialAdapter=(config:VerifiedOfficialAdapterConfig={})=>createAdapter(blsSpec('inflation_indicator','CUSR0000SA0','inflation',324.8,'CPI-U all items'),config);
export const createBlsLaborOfficialAdapter=(config:VerifiedOfficialAdapterConfig={})=>createAdapter(blsSpec('labor_market_indicator','LNS14000000','labor_market',4.1,'US unemployment rate'),config);
export const createBeaGrowthOfficialAdapter=(config:VerifiedOfficialAdapterConfig={})=>createAdapter({providerId:'bea_official',canonicalSourceId:'bea_official',capability:'growth_activity_indicator',region:'united_states',evidenceClass:'growth_activity',fixture:[{date:'2026-Q2',value:2.4,label:'Real GDP percent change',unit:'percent'}],build:(request,c)=>{const url=new URL('/api/data/','https://apps.bea.gov'),y=isoYear(request);url.searchParams.set('UserID',requireApiKey(c));url.searchParams.set('method','GetData');url.searchParams.set('DataSetName','NIPA');url.searchParams.set('TableName','T10101');url.searchParams.set('Frequency','Q');url.searchParams.set('Year',`${Number(y)-1},${y}`);url.searchParams.set('ResultFormat','JSON');return{url};},parse:async response=>{const body=await response.json() as any,rows=body?.BEAAPI?.Results?.Data;if(!Array.isArray(rows))return[];return rows.flatMap((row:any)=>{const n=number(row.DataValue);return n!==null&&typeof row.TimePeriod==='string'?[{date:row.TimePeriod.replace(/Q([1-4])$/,'-Q$1'),value:n,label:String(row.LineDescription??row.SeriesCode??'BEA NIPA'),unit:null}]:[];});}},config);
export const createCensusGrowthOfficialAdapter=(config:VerifiedOfficialAdapterConfig={})=>createAdapter({providerId:'census_official',canonicalSourceId:'census_official',capability:'growth_activity_indicator',region:'united_states',evidenceClass:'growth_activity',fixture:[{date:'2026-06-01',value:705.2,label:'Monthly retail trade'}],build:(request,c)=>{const url=new URL('/data/timeseries/eits/mrts','https://api.census.gov');url.searchParams.set('get','cell_value,data_type_code,time_slot_id,category_code,seasonally_adj');url.searchParams.set('time',isoYear(request));url.searchParams.set('key',requireApiKey(c));return{url};},parse:async response=>{const body=await response.json() as unknown;if(!Array.isArray(body)||!Array.isArray(body[0]))return[];const headers=(body[0] as unknown[]).map(String),valueIndex=headers.indexOf('cell_value'),timeIndex=headers.indexOf('time');if(valueIndex<0)return[];return (body.slice(1) as unknown[][]).flatMap(row=>{const n=number(row[valueIndex]),m=/^(\d{4})(?:-(\d{2}))?/.exec(timeIndex>=0?String(row[timeIndex]??''):'');return n!==null&&m?[{date:`${m[1]}-${m[2]??'01'}-01`,value:n,label:'Census monthly retail trade'}]:[];});}},config);
export const createBoePolicyOfficialAdapter=(config:VerifiedOfficialAdapterConfig={})=>createAdapter({providerId:'boe_official',canonicalSourceId:'boe_official',capability:'policy_rate_series',region:'united_kingdom',evidenceClass:'central_bank_policy',fixture:[{date:'2026-06-18',value:3.75,label:'Official Bank Rate',unit:'percent'}],build:()=>{const url=new URL('/boeapps/database/_iadb-fromshowcolumns.asp','https://www.bankofengland.co.uk');for(const [k,v] of Object.entries({'csv.x':'yes',Datefrom:'01/Jan/2025',Dateto:'now',SeriesCodes:'IUDBEDR',CSVF:'TN',UsingCodes:'Y',VPD:'Y'}))url.searchParams.set(k,v);return{url};},parse:async response=>(await response.text()).split(/\r?\n/).filter(Boolean).flatMap(line=>{const cells=csvCells(line),date=cells.find(x=>/\d{1,2}[/-][A-Za-z]{3}[/-]\d{4}|\d{2}\/\d{2}\/\d{4}/.test(x)),raw=cells.find((x,i)=>i>0&&number(x)!==null),n=number(raw);if(!date||n===null)return[];const t=Date.parse(date);return Number.isFinite(t)?[{date:new Date(t).toISOString().slice(0,10),value:n,label:'Official Bank Rate',unit:'percent'}]:[];})},config);
export const createRbaPolicyOfficialAdapter=(config:VerifiedOfficialAdapterConfig={})=>createAdapter({providerId:'rba_official',canonicalSourceId:'rba_official',capability:'policy_rate_series',region:'australia',evidenceClass:'central_bank_policy',fixture:[{date:'2026-08-12',value:4.35,label:'Cash rate target',unit:'percent'}],build:()=>({url:new URL('/statistics/cash-rate/','https://www.rba.gov.au')}),parse:async response=>parsePolicyHtml(await response.text(),'Cash rate target')},config);
export const createRbnzPolicyOfficialAdapter=(config:VerifiedOfficialAdapterConfig={})=>createAdapter({providerId:'rbnz_official',canonicalSourceId:'rbnz_official',capability:'policy_rate_series',region:'new_zealand',evidenceClass:'central_bank_policy',fixture:[{date:'2026-09-02',value:2.75,label:'Official Cash Rate',unit:'percent'}],build:()=>({url:new URL('/monetary-policy/monetary-policy-decisions','https://www.rbnz.govt.nz')}),parse:async response=>parsePolicyHtml(await response.text(),'Official Cash Rate')},config);
export const createBankOfCanadaPolicyOfficialAdapter=(config:VerifiedOfficialAdapterConfig={})=>createAdapter({providerId:'bank_of_canada_official',canonicalSourceId:'bank_of_canada_official',capability:'policy_rate_series',region:'canada',evidenceClass:'central_bank_policy',fixture:[{date:'2026-06-10',value:2.75,label:'Target for the overnight rate',unit:'percent'}],build:request=>{const url=new URL('/valet/observations/V39079/json','https://www.bankofcanada.ca'),y=isoYear(request);url.searchParams.set('start_date',`${Number(y)-1}-01-01`);url.searchParams.set('end_date',`${y}-12-31`);return{url};},parse:async response=>{const rows=(await response.json() as any)?.observations;if(!Array.isArray(rows))return[];return rows.flatMap((row:any)=>{const n=number(row?.V39079?.v);return typeof row?.d==='string'&&n!==null?[{date:row.d,value:n,label:'Target for the overnight rate',unit:'percent'}]:[];});}},config);
export const createStatisticsCanadaMacroOfficialAdapter=(config:VerifiedOfficialAdapterConfig={})=>createAdapter({providerId:'statistics_canada_official',canonicalSourceId:'statistics_canada_official',capability:'macro_indicator_series',region:'canada',evidenceClass:'inflation',fixture:[{date:'2026-06-01',value:162.1,label:'All-items CPI Canada',unit:'index'}],build:request=>{const url=new URL('/t1/wds/rest/getDataFromVectorByReferencePeriodRange','https://www150.statcan.gc.ca'),y=isoYear(request);url.searchParams.set('vectorIds','41690973');url.searchParams.set('startRefPeriod',`${Number(y)-1}-01-01`);url.searchParams.set('endReferencePeriod',`${y}-12-31`);return{url};},parse:async response=>{const body=await response.json() as any,roots=Array.isArray(body)?body:[body],out:Point[]=[];for(const root of roots){const groups=Array.isArray(root?.object)?root.object:[root?.object??root];for(const group of groups){if(!Array.isArray(group?.vectorDataPoint))continue;for(const p of group.vectorDataPoint){const n=number(p?.value),date=String(p?.refPerRaw??p?.refPer??'');if(n!==null&&date)out.push({date,value:n,label:'All-items CPI Canada',unit:'index'});}}}return out;}},config);
export const createEiaEnergyOfficialAdapter=(config:VerifiedOfficialAdapterConfig={})=>createAdapter({providerId:'eia_official',canonicalSourceId:'eia_official',capability:'energy_commodity_series',region:'united_states',evidenceClass:'energy_commodities',fixture:[{date:'2026-06-17',value:74.2,label:'WTI spot price',unit:'USD per barrel'}],build:(request,c)=>{const url=new URL('/v2/petroleum/pri/spt/data/','https://api.eia.gov'),y=isoYear(request);url.searchParams.set('api_key',requireApiKey(c));url.searchParams.set('frequency','daily');url.searchParams.append('data[0]','value');url.searchParams.append('facets[series][]','RWTC');url.searchParams.set('start',`${Number(y)-1}-01-01`);url.searchParams.set('end',`${y}-12-31`);url.searchParams.append('sort[0][column]','period');url.searchParams.append('sort[0][direction]','desc');url.searchParams.set('length','5000');return{url};},parse:async response=>{const rows=(await response.json() as any)?.response?.data;if(!Array.isArray(rows))return[];return rows.flatMap((row:any)=>{const n=number(row?.value);return typeof row?.period==='string'&&n!==null?[{date:row.period,value:n,label:'WTI spot price',unit:String(row['price-units']??row.units??'USD per barrel')}]:[];});}},config);
export const createWorldBankGrowthOfficialAdapter=(config:VerifiedOfficialAdapterConfig={})=>createAdapter({providerId:'world_bank_official',canonicalSourceId:'world_bank_official',capability:'growth_activity_indicator',region:'global',evidenceClass:'growth_activity',fixture:[{date:'2025',value:2.8,label:'World GDP growth',unit:'percent'}],build:request=>{const url=new URL('/v2/country/WLD/indicator/NY.GDP.MKTP.KD.ZG','https://api.worldbank.org'),y=Number(isoYear(request));url.searchParams.set('format','json');url.searchParams.set('date',`${y-3}:${y}`);url.searchParams.set('per_page','100');return{url};},parse:async response=>{const body=await response.json() as any;if(!Array.isArray(body)||!Array.isArray(body[1]))return[];return body[1].flatMap((row:any)=>{const n=number(row?.value);return typeof row?.date==='string'&&n!==null?[{date:row.date,value:n,label:'World GDP growth',unit:'percent'}]:[];});}},config);
