import type { ElceoAccountEntitlementState, ElceoAccountState, ElceoPlanKind, PlanEntitlementProfile } from '@elceo/types';
import type { AccountEntitlementRepository } from '../persistence';
import { buildPlanProfile } from './plan-definitions';
export class AccountEntitlementService { constructor(private readonly repo: AccountEntitlementRepository) {}
  async getOrCreateDefaultAccountEntitlement(subjectKind:'user',subjectId:string){ const row=await this.repo.getAccountEntitlement(subjectKind,subjectId); if(row) return row as ElceoAccountEntitlementState; const now=new Date().toISOString(); const created:ElceoAccountEntitlementState={subjectKind,subjectId,planKind:'free',accountState:'active',planStartedAt:null,planEndsAt:null,trialEndsAt:null,internalOverride:false,updatedAt:now}; await this.repo.saveAccountEntitlement(created); return created; }
  async updateAccountPlan(subjectKind:'user',subjectId:string,planKind:ElceoPlanKind,params?:{planStartedAt?:string|null;planEndsAt?:string|null;trialEndsAt?:string|null}){ const current=await this.getOrCreateDefaultAccountEntitlement(subjectKind,subjectId); const next={...current,planKind,planStartedAt:params?.planStartedAt??current.planStartedAt,planEndsAt:params?.planEndsAt??current.planEndsAt,trialEndsAt:params?.trialEndsAt??current.trialEndsAt,updatedAt:new Date().toISOString()}; await this.repo.saveAccountEntitlement(next); return next; }
  async updateAccountState(subjectKind:'user',subjectId:string,accountState:ElceoAccountState){ const c=await this.getOrCreateDefaultAccountEntitlement(subjectKind,subjectId); const n={...c,accountState,updatedAt:new Date().toISOString()}; await this.repo.saveAccountEntitlement(n); return n; }
  async setInternalOverride(subjectKind:'user',subjectId:string,internalOverride:boolean){ const c=await this.getOrCreateDefaultAccountEntitlement(subjectKind,subjectId); const n={...c,internalOverride,updatedAt:new Date().toISOString()}; await this.repo.saveAccountEntitlement(n); return n; }
  getPlanEntitlementProfile(planKind:ElceoPlanKind,accountState:ElceoAccountState,asOfIso:string): PlanEntitlementProfile { return buildPlanProfile(planKind,accountState,asOfIso); }
}
