import assert from 'node:assert/strict';
import type { DashboardChartWorkspaceViewModel,KickOffDashboardViewModelV1,UserCommercialEntitlementSnapshot } from '@elceo/types';
import { createDashboardGetHandler } from '../lib/dashboard-route-handler';
import { resolveDashboardCommercialAccess,type DashboardCommercialAccess } from '../lib/server/dashboard-commercial-authority';
import { resolveDashboardPageExperience } from '../lib/server/dashboard-page-orchestration';
import type { withDashboardReadAdmission } from '../lib/inbound-read-admission';

const evaluatedAt='2026-08-30T00:00:00.000Z',workspace={dashboard:{modules:[],confidence_total:55,directional_bias:'neutral'},chart:{candles:[{timestamp_utc:evaluatedAt,open:100,high:110,low:90,close:105}],zones:[{zone_id:'z',lower:95,upper:105,center:100}]}} as unknown as DashboardChartWorkspaceViewModel;
const model=(features:{evidenceScore:boolean;macroHeadlines:boolean},context=true):KickOffDashboardViewModelV1=>({contract_version:'kick-off-dashboard-v1',access:'kick_off',asset_code:'XAU/USD',timeframe:'H4',horizon:'intraday',evaluated_at:evaluatedAt,chart:{candles:[{timestamp_utc:evaluatedAt,open:100,high:110,low:90,close:105}],zones:[{zone_id:'z',lower:95,upper:105,center:100}]},evidence_score:features.evidenceScore&&context?{availability:'available',value:73.428,scale:'0_100'}:{availability:'unavailable',value:null,scale:'0_100'},macro_headlines:features.macroHeadlines&&context?{availability:'available',items:[{headline_id:'h',title:'Source headline',source_name:'Wire',source_url:'https://example.test/h',published_at:evaluatedAt,freshness:'fresh'}]}:{availability:'unavailable',items:[]}});
const leakGuard=(value:unknown)=>{const denied=new Set(['directional_bias','confidence','confidence_total','confidence_anatomy','contradiction','reasoning','rationale','narrative','cognition','weightedSnapshot','parentEvidenceArtifactIdentities','modules','evidence_notes']);const visit=(node:unknown)=>{if(Array.isArray(node))return node.forEach(visit);if(node&&typeof node==='object')for(const[key,child]of Object.entries(node)){assert.equal(denied.has(key),false,`premium leak: ${key}`);visit(child)}};visit(value)};
const snapshot=(overrides:Partial<UserCommercialEntitlementSnapshot>):UserCommercialEntitlementSnapshot=>({userId:'authority-user',nowIso:'2026-08-30T00:00:00.000Z',trialStartedAt:null,activePlanCode:null,subscriptionActive:false,socialIdentifiers:[],userRestrictionStatus:'none',...overrides});
const admit=(async(_subject:string,work:(signal:AbortSignal)=>Promise<unknown>)=>({ok:true as const,value:await work(new AbortController().signal)}))as typeof withDashboardReadAdmission;

export async function runKickOffFinalAuthorityAcceptance(){
 const accessFor=(value:UserCommercialEntitlementSnapshot,allowed:readonly string[])=>resolveDashboardCommercialAccess(value,(({featureKey}:{featureKey:string})=>({decision:allowed.includes(featureKey)?'allow':'deny',status:'active',reason:'a4_authority_fixture',subscriptionWall:null}))as never),focus=accessFor(snapshot({activePlanCode:'focus_plan',subscriptionActive:true}),['premium.full_access']),gift=accessFor(snapshot({superAdminGift:{status:'active',endsAt:'2026-09-01T00:00:00.000Z'}}),['premium.full_access']),trial=accessFor(snapshot({trialStartedAt:'2026-08-25T00:00:00.000Z'}),['dashboard.chart','dashboard.evidence_score','dashboard.macro_headlines']),expired=accessFor(snapshot({trialStartedAt:'2026-01-01T00:00:00.000Z'}),[]),suspended=accessFor(snapshot({activePlanCode:'focus_plan',subscriptionActive:true,userRestrictionStatus:'suspended'}),[]),banned=accessFor(snapshot({activePlanCode:'focus_plan',subscriptionActive:true,userRestrictionStatus:'banned'}),[]);assert.equal(focus,'focus_plan');assert.equal(gift,'focus_plan');assert.notEqual(trial,'denied');assert.equal(expired,'denied');assert.equal(suspended,'denied');assert.equal(banned,'denied');
 const cases:Array<{id:string;access:DashboardCommercialAccess;context?:boolean;expected:'focus_plan'|'kick_off'|'denied'|'warming';score?:boolean;headlines?:boolean;alerts:number}>=[{id:'focus_plan',access:'focus_plan',expected:'focus_plan',alerts:1},{id:'chart_only',access:{access:'kick_off',features:{evidenceScore:false,macroHeadlines:false}},expected:'kick_off',score:false,headlines:false,alerts:0},{id:'chart_score',access:{access:'kick_off',features:{evidenceScore:true,macroHeadlines:false}},expected:'kick_off',score:true,headlines:false,alerts:0},{id:'chart_headlines',access:{access:'kick_off',features:{evidenceScore:false,macroHeadlines:true}},expected:'kick_off',score:false,headlines:true,alerts:0},{id:'full_kick_off',access:{access:'kick_off',features:{evidenceScore:true,macroHeadlines:true}},expected:'kick_off',score:true,headlines:true,alerts:0},{id:'denied',access:'denied',expected:'denied',alerts:0},{id:'missing_context',access:{access:'kick_off',features:{evidenceScore:true,macroHeadlines:true}},context:false,expected:'kick_off',score:false,headlines:false,alerts:0},{id:'corrupt_context',access:{access:'kick_off',features:{evidenceScore:true,macroHeadlines:true}},context:false,expected:'kick_off',score:false,headlines:false,alerts:0}];
 const matrix=[];for(const value of cases){let alerts=0,dashboardReads=0,kickOffReads=0;const experience=await resolveDashboardPageExperience({userId:'authority-user',asset:'XAU/USD',access:value.access,readDashboard:async()=>{dashboardReads++;return workspace},readKickOff:async(_asset,_signal,features)=>{kickOffReads++;return model(features,value.context!==false)},evaluatePremiumAlerts:async input=>{alerts++;assert.equal(input.current,workspace)}});assert.equal(experience.kind,value.expected,value.id);assert.equal(alerts,value.alerts,value.id);if(experience.kind==='kick_off'){leakGuard(experience.model);assert.equal(experience.model.evidence_score.availability,value.score?'available':'unavailable');assert.equal(experience.model.macro_headlines.availability,value.headlines?'available':'unavailable');assert.equal(dashboardReads,0)}if(experience.kind==='focus_plan'){assert.equal(experience.workspace,workspace);assert.equal(kickOffReads,0)}if(experience.kind==='denied'){assert.equal(dashboardReads,0);assert.equal(kickOffReads,0)}matrix.push({case_id:value.id,page_kind:experience.kind,alert_calls:alerts,dashboard_reads:dashboardReads,kick_off_reads:kickOffReads})}
 let malformedAlerts=0,malformedDashboardReads=0;const malformed=await resolveDashboardPageExperience({userId:'authority-user',asset:'XAU/USD',access:{access:'kick_off'}as never,readDashboard:async()=>{malformedDashboardReads++;return workspace},evaluatePremiumAlerts:async()=>{malformedAlerts++}});assert.equal(malformed.kind,'denied');assert.equal(malformedAlerts,0);assert.equal(malformedDashboardReads,0);const missingReader=await resolveDashboardPageExperience({userId:'authority-user',asset:'XAU/USD',access:{access:'kick_off',features:{evidenceScore:true,macroHeadlines:true}},readDashboard:async()=>workspace,evaluatePremiumAlerts:async()=>{malformedAlerts++}});assert.equal(missingReader.kind,'denied');assert.equal(malformedAlerts,0);
 let invalidAlerts=0;const invalidD1=await resolveDashboardPageExperience({userId:'authority-user',asset:'XAU/USD',access:'focus_plan',readDashboard:async()=>null,evaluatePremiumAlerts:async()=>{invalidAlerts++}});assert.equal(invalidD1.kind,'warming');assert.equal(invalidAlerts,0);const invalidKickOff=await resolveDashboardPageExperience({userId:'authority-user',asset:'XAU/USD',access:{access:'kick_off',features:{evidenceScore:true,macroHeadlines:true}},readDashboard:async()=>workspace,readKickOff:async()=>null,evaluatePremiumAlerts:async()=>{invalidAlerts++}});assert.equal(invalidKickOff.kind,'warming');assert.equal(invalidAlerts,0);
 const request=new Request('https://elceo.test/api/dashboard/XAU%2FUSD'),auth=async()=>({session:{user:{id:'authority-user'}},appState:{watchlist:{assets:['XAU/USD']}}});for(const value of cases.filter(item=>!['missing_context','corrupt_context'].includes(item.id))){let dashboardReads=0,kickOffReads=0;const handler=createDashboardGetHandler({authenticate:auth,admit,resolveCommercialAccess:async()=>value.access,readDashboard:async()=>{dashboardReads++;return workspace},readKickOff:async(_asset,_signal,features)=>{kickOffReads++;return model(features)}}),response=await handler(request,{params:Promise.resolve({asset:'XAU%2FUSD'})}),expectedStatus=value.access==='denied'?403:200;assert.equal(response.status,expectedStatus);assert.equal(value.access==='focus_plan'?dashboardReads:kickOffReads,value.access==='denied'?0:1);matrix.find(entry=>entry.case_id===value.id)!.api_status=response.status}
 const unauth=createDashboardGetHandler({authenticate:async()=>({session:{},appState:{watchlist:{assets:[]}}}),admit,readDashboard:async()=>workspace});assert.equal((await unauth(request,{params:Promise.resolve({asset:'XAU%2FUSD'})})).status,401);const onboarding=createDashboardGetHandler({authenticate:async()=>{throw new Error('ONBOARDING_REQUIRED')},admit,readDashboard:async()=>workspace});assert.equal((await onboarding(request,{params:Promise.resolve({asset:'XAU%2FUSD'})})).status,403);let failCloseDashboardReads=0;const incomplete=createDashboardGetHandler({authenticate:auth,admit,resolveCommercialAccess:(async()=>({access:'kick_off'}))as never,readDashboard:async()=>{failCloseDashboardReads++;return workspace}});assert.equal((await incomplete(request,{params:Promise.resolve({asset:'XAU%2FUSD'})})).status,500);assert.equal(failCloseDashboardReads,0);
 console.log(JSON.stringify({acceptance:'kick-off-final-commercial-authority',entitlements:{focus,gift,trial,expired,suspended,banned},matrix,actual_alert_dependency:'resolveDashboardPageExperience.evaluatePremiumAlerts; production DashboardPage supplies evaluateAndPersistAlerts',alerts:{focus_plan:1,kick_off:0,denied:0,malformed:0,degraded:0},unauthenticated:401,onboarding_required:403,malformed_api:500,api_page_authority_consistent:true,premium_leak:false}));
}
