import { getMarketAssetCausalityDescriptor } from '../asset-causality-map/index';
import type { EventRealityEvaluation, PriceReactionTimelinePhase } from '../expectation-reality/contracts';
import { HISTORICAL_ANALOG_FEATURE_POLICY_VERSION } from './policy';
import type { AnalogFeatureGroup, AnalogMatchFeatures, HistoricalAnalogMemoryRecord, HistoricalAnalogProvenanceSummary, HistoricalDatasetClass, HistoricalOutcomeContext } from './contracts';
import { buildAnalogMemoryId, buildEventInstanceKey, historicalHash } from './identity';

const reliability = (x: { effectiveReliability?: HistoricalDatasetClass; reliability?: HistoricalDatasetClass }): HistoricalDatasetClass => x.effectiveReliability ?? x.reliability ?? 'unverified';
const worst = (values: HistoricalDatasetClass[]): HistoricalDatasetClass => values.includes('unverified') ? 'unverified' : values.includes('fixture') ? 'fixture' : values.includes('replay') ? 'replay' : 'verified';
const phaseEnd = (phase: PriceReactionTimelinePhase): string | null => phase.endTimestamp;
const group = <T extends Record<string, unknown>>(state: AnalogFeatureGroup<T>['state'], availableAt: string | null, sourcePaths: string[], values: T, limitations: string[] = []): AnalogFeatureGroup<T> => ({ state, availableAt, sourcePaths, values, limitations });
const phaseValues = (p: PriceReactionTimelinePhase) => ({ state: p.state, observedDirection: p.observedDirection, moveFromOriginPct: p.moveFromOriginPct });

export function deriveHistoricalDatasetClass(e: EventRealityEvaluation): HistoricalDatasetClass { return worst([...e.reality.provenance.map(reliability), ...e.reactionProvenance.map(reliability)]); }
export function summarizeProvenance(e: EventRealityEvaluation): HistoricalAnalogProvenanceSummary { const all = [...e.reality.provenance, ...e.reactionProvenance]; return { datasetClass: deriveHistoricalDatasetClass(e), requiredEvidenceReliability: all.map(reliability), sourceIds: all.map((p) => p.sourceId), optionalUnverifiedRelatedEvidence: e.relatedEvidenceStatus === 'pending' || e.reality.relatedMarketReactions.length === 0 }; }
export function assertRuntimeIndexingEligible(e: EventRealityEvaluation): void { if (e.finalizationStatus !== 'final') throw new Error('analog_memory_requires_final_event_evaluation'); const required = [...e.reality.provenance.map(reliability), ...e.reactionProvenance.map(reliability)]; if (required.some((r) => r === 'fixture')) throw new Error('fixture_history_cannot_enter_runtime_analog_memory'); if (required.some((r) => r === 'unverified')) throw new Error('unverified_required_evidence_cannot_enter_runtime_analog_memory'); }
export function buildAnalogMatchFeatures(e: EventRealityEvaluation): AnalogMatchFeatures { const exp = e.expectation; const r = e.reality; const optionalUnverifiedRelatedEvidence = e.reality.relatedMarketReactions.length === 0 || e.relatedEvidenceStatus === 'pending'; return {
  eventContext: group('available', exp.dataCutoffAt || exp.issuedAt, ['expectation.eventKind','expectation.indicatorKind','expectation.indicatorCategory'], { eventKind: exp.eventKind, indicatorKind: String(exp.indicatorKind), indicatorCategory: String(exp.indicatorCategory), importance: exp.importance, region: String(exp.region), currency: String(exp.currency) }),
  releaseRevisionContext: group('available', r.observedAt, ['reality.revisionAdjustedMeasures'], { adjustedSurpriseScore: r.revisionAdjustedMeasures.adjustedSurpriseScore, revisionDelta: r.revisionAdjustedMeasures.revisionDelta, revisionEffect: r.revisionAdjustedMeasures.revisionEffect, revisionAdjustedDirection: r.revisionAdjustedMeasures.revisionAdjustedDirection }, r.revisionAdjustedMeasures.limitations),
  assetDirectionContext: group('available', r.observedAt, ['expectation.expectedAssetDirection','reality.releaseAlignment'], { expectedAssetDirection: exp.expectedAssetDirection, actualDirection: r.releaseAlignment.actualDirection, releaseAlignment: r.releaseAlignment.status }),
  immediatePathContext: group(r.priceReactionTimeline.immediate.endTimestamp ? 'available' : 'unavailable', phaseEnd(r.priceReactionTimeline.immediate), ['reality.priceReactionTimeline.immediate'], phaseValues(r.priceReactionTimeline.immediate), r.priceReactionTimeline.immediate.warnings),
  confirmationPathContext: group(r.priceReactionTimeline.confirmation.endTimestamp ? 'available' : 'unavailable', phaseEnd(r.priceReactionTimeline.confirmation), ['reality.priceReactionTimeline.confirmation'], phaseValues(r.priceReactionTimeline.confirmation), r.priceReactionTimeline.confirmation.warnings),
  followThroughPathContext: group(r.priceReactionTimeline.followThrough.endTimestamp ? 'available' : 'unavailable', phaseEnd(r.priceReactionTimeline.followThrough), ['reality.priceReactionTimeline.followThrough'], phaseValues(r.priceReactionTimeline.followThrough), r.priceReactionTimeline.followThrough.warnings),
  relatedMarketContext: group(r.relatedEvidenceDecision.decidedAt ? 'available' : (e.expectation.requiredRelatedAssets.length ? 'unavailable' : 'structurally_unavailable'), r.relatedEvidenceDecision.decidedAt, ['reality.relatedEvidenceDecision'], { status: e.relatedEvidenceStatus, relatedMarketState: r.relatedMarketState }, optionalUnverifiedRelatedEvidence ? ['optional_unverified_related_evidence_not_positive_similarity_support'] : []),
  volatilityContext: group('available', r.priceReactionTimeline.confirmation.endTimestamp ?? r.observedAt, ['reality.priceReactionTimeline.volatilityAdjustedMove'], { immediateVolatilityAdjustedMove: r.priceReactionTimeline.immediate.volatilityAdjustedMove, confirmationVolatilityAdjustedMove: r.priceReactionTimeline.confirmation.volatilityAdjustedMove, followThroughVolatilityAdjustedMove: r.priceReactionTimeline.followThrough.volatilityAdjustedMove }),
  cognitionShiftContext: group(r.postEventCognitionEvaluatedAt ? 'available' : 'unavailable', r.postEventCognitionEvaluatedAt, ['reality.confidenceDelta','reality.contradictionDelta'], { confidenceDelta: r.confidenceDelta, contradictionDelta: r.contradictionDelta, biasChanged: r.biasChange.changed }),
  provenanceContext: group('available', e.createdAt, ['reality.provenance','reactionProvenance'], { requiredReliability: deriveHistoricalDatasetClass(e), optionalUnverifiedRelatedEvidence })
}; }
export function buildHistoricalOutcomeContext(e: EventRealityEvaluation): HistoricalOutcomeContext { return { usedInSimilarity: false, finalOutcome: e.outcome, finalPricePathState: e.reality.priceReactionTimeline.followThroughState, laterAcceptanceOrReversalState: e.reality.priceReactionTimeline.reversalAbsorptionState, finalConfidenceDelta: e.reality.confidenceDelta, finalContradictionDelta: e.reality.contradictionDelta, finalRelatedEvidenceState: e.relatedEvidenceStatus, finalRationale: e.rationale, limitations: e.reality.limitations }; }
export function buildHistoricalAnalogMemoryRecord(e: EventRealityEvaluation, availableAt = e.interpretedAt): HistoricalAnalogMemoryRecord { assertRuntimeIndexingEligible(e); const features = buildAnalogMatchFeatures(e); const featureContentHash = historicalHash(features); const outcome = buildHistoricalOutcomeContext(e); const family = getMarketAssetCausalityDescriptor(e.asset as any).family; return { analogMemoryId: buildAnalogMemoryId(e.eventEvaluationId, HISTORICAL_ANALOG_FEATURE_POLICY_VERSION, featureContentHash), sourceEventEvaluationId: e.eventEvaluationId, sourceExpectationId: e.expectationId, sourceAssessmentEvidenceHash: e.assessmentEvidenceHash, sourceObservationContentHash: e.observationContentHash, sourceEventInstanceKey: buildEventInstanceKey(e.expectation), sourceReleaseId: e.releaseId, sourceReleaseVersion: e.releaseVersion, sourceAsset: e.asset, canonicalAssetFamily: family, eventKind: e.expectation.eventKind, indicatorKind: String(e.expectation.indicatorKind), indicatorCategory: String(e.expectation.indicatorCategory), sourceEventObservedAt: e.reality.observedAt, sourceEvaluationInterpretedAt: e.interpretedAt, availableAt, sourceDatasetClass: deriveHistoricalDatasetClass(e), featurePolicyVersion: HISTORICAL_ANALOG_FEATURE_POLICY_VERSION, featureContentHash, matchFeatures: features, historicalOutcomeContextHash: historicalHash(outcome), historicalOutcomeContext: outcome, sourceProvenanceSummary: summarizeProvenance(e), warnings: e.warnings, limitations: e.reality.limitations.concat(features.relatedMarketContext.limitations), createdAt: e.createdAt }; }
export function sliceFeaturesAt(features: AnalogMatchFeatures, cutoffAt: string): AnalogMatchFeatures { const cutoff = Date.parse(cutoffAt); const out: any = {}; for (const [k, v] of Object.entries(features) as [keyof AnalogMatchFeatures, any][]) out[k] = v.state === 'available' && v.availableAt && Date.parse(v.availableAt) <= cutoff ? v : { ...v, state: v.state === 'structurally_unavailable' ? 'structurally_unavailable' : 'unavailable', limitations: [...v.limitations, 'not_available_at_equal_elapsed_horizon'] }; return out; }
