import { canonicalJson, deepCloneFreeze } from '../expectation-reality/identity';
import type { HistoricalAnalogRepository, HistoricalAnalogMemoryRecord, HistoricalAnalogRetrievalResult, HistoricalAnalogMatch } from './contracts';
import { isAfterTuple } from './identity';
import { normalizeHistoricalAnalogPageLimit } from './policy';

export function assertRetrievalInvariants(r: HistoricalAnalogRetrievalResult): void { const ranks=new Set<number>(); const ids=new Set<string>(); let prev=0; for (const [i,m] of r.matches.entries()) { if (m.rank <= 0) throw new Error('invalid_analog_retrieval_rank'); if (m.rank !== i + 1) throw new Error('noncontiguous_analog_retrieval_rank'); if (ranks.has(m.rank)) throw new Error('duplicate_analog_retrieval_rank'); if (ids.has(m.analogMemoryId)) throw new Error('duplicate_analog_retrieval_match'); if (m.rank <= prev) throw new Error('nondeterministic_analog_retrieval_rank_order'); if (!m.sourceEventEvaluationId || !m.sourceEventInstanceKey || !m.analogMemoryId) throw new Error('inconsistent_analog_retrieval_match_identity'); ranks.add(m.rank); ids.add(m.analogMemoryId); prev=m.rank; } }
export class MemoryHistoricalAnalogRepository implements HistoricalAnalogRepository {
  private memory = new Map<string, HistoricalAnalogMemoryRecord>(); private bySource = new Map<string, string>(); private retrievals = new Map<string, HistoricalAnalogRetrievalResult>();
  async saveAnalogMemoryRecord(r: HistoricalAnalogMemoryRecord) { const key=`${r.sourceEventEvaluationId}|${r.featurePolicyVersion}`; const priorId=this.bySource.get(key); const existing=priorId ? this.memory.get(priorId) : this.memory.get(r.analogMemoryId); if (existing) { if (canonicalJson(existing)!==canonicalJson(r)) throw new Error('immutable_analog_memory_conflict'); return existing; } const frozen=deepCloneFreeze(r); this.memory.set(r.analogMemoryId,frozen); this.bySource.set(key,r.analogMemoryId); return frozen; }
  async getAnalogMemoryById(id: string) { return this.memory.get(id) ?? null; }
  async getAnalogMemoryBySource(sourceEventEvaluationId: string, featurePolicyVersion: string) { const id=this.bySource.get(`${sourceEventEvaluationId}|${featurePolicyVersion}`); return id ? this.memory.get(id) ?? null : null; }
  async listAnalogMemory(params: { before: string; asset?: any; limit?: number; cursor?: string }) { let rows=[...this.memory.values()].filter((r)=>Date.parse(r.availableAt)<Date.parse(params.before)); if(params.asset) rows=rows.filter((r)=>r.sourceAsset===params.asset); rows.sort((a,b)=>a.availableAt.localeCompare(b.availableAt)||a.analogMemoryId.localeCompare(b.analogMemoryId)); rows=rows.filter((r)=>isAfterTuple({at:r.availableAt,id:r.analogMemoryId}, params.cursor)); return rows.slice(0, normalizeHistoricalAnalogPageLimit(params.limit)); }
  async saveRetrievalResult(r: HistoricalAnalogRetrievalResult) { assertRetrievalInvariants(r); const existing=this.retrievals.get(r.retrievalId); if(existing){ if(canonicalJson(existing)!==canonicalJson(r)) throw new Error('immutable_analog_retrieval_conflict'); return existing; } const frozen=deepCloneFreeze(r); this.retrievals.set(r.retrievalId,frozen); return frozen; }
  async getRetrievalById(id: string) { return this.retrievals.get(id) ?? null; }
  async listRetrievalMatches(retrievalId: string): Promise<HistoricalAnalogMatch[]> { return this.retrievals.get(retrievalId)?.matches ?? []; }
}
