import type { AnalogFeatureGroupName, AnalogMatchFeatures, HistoricalAnalogMatch, HistoricalAnalogMemoryRecord } from './contracts';
import { HISTORICAL_ANALOG_POLICY, type HistoricalAnalogComponent } from './policy';

const clamp = (n: number) => Math.max(0, Math.min(100, n));
const num = (a: number | null, b: number | null, bound: number) => a == null || b == null ? null : clamp(100 - Math.abs(a - b) / bound * 100);
const cat = (a: unknown, b: unknown, partial = 0) => a === b ? 100 : partial;
const available = (q: any, c: any) => q.state === 'available' && c.state === 'available';
const avg = (xs: (number | null)[]) => { const ok = xs.filter((x): x is number => x != null); return ok.length ? ok.reduce((a,b)=>a+b,0)/ok.length : null; };
const componentGroups: Record<HistoricalAnalogComponent, AnalogFeatureGroupName[]> = { eventContext:['eventContext'], surpriseRevision:['releaseRevisionContext'], assetDirection:['assetDirectionContext'], pricePath:['immediatePathContext','confirmationPathContext','followThroughPathContext'], relatedMarket:['relatedMarketContext'], volatility:['volatilityContext'], cognitionShift:['cognitionShiftContext'], provenanceQuality:['provenanceContext'] };
function scoreComponent(component: HistoricalAnalogComponent, q: AnalogMatchFeatures, c: AnalogMatchFeatures): { score: number; coverage: number; matched: AnalogFeatureGroupName[]; unavailable: string[]; reasons: string[]; limitations: string[] } {
  const groups = componentGroups[component]; const mutually = groups.filter((g)=>available(q[g], c[g])); const unavailable = groups.filter((g)=>!available(q[g], c[g])); const limitations = groups.flatMap((g)=>[...q[g].limitations,...c[g].limitations]);
  if (!mutually.length) return { score: 0, coverage: 0, matched: [], unavailable, reasons: [`${component}_unavailable_at_cutoff`], limitations };
  let score: number | null = null; const r: string[] = [];
  if (component === 'eventContext') { const qv=q.eventContext.values, cv=c.eventContext.values; score=avg([cat(qv.eventKind,cv.eventKind), cat(qv.indicatorCategory,cv.indicatorCategory), cat(qv.indicatorKind,cv.indicatorKind,65), cat(qv.importance,cv.importance,70)]); r.push(qv.indicatorKind===cv.indicatorKind?'exact_indicator_kind':'same_category_different_indicator_kind'); }
  if (component === 'surpriseRevision') { const qv=q.releaseRevisionContext.values, cv=c.releaseRevisionContext.values; score=avg([num(qv.adjustedSurpriseScore,cv.adjustedSurpriseScore,HISTORICAL_ANALOG_POLICY.bounds.surprise), num(qv.revisionDelta,cv.revisionDelta,HISTORICAL_ANALOG_POLICY.bounds.revision), cat(qv.revisionEffect,cv.revisionEffect,35), cat(qv.revisionAdjustedDirection,cv.revisionAdjustedDirection,0)]); r.push('revision_adjusted_surprise_compared'); }
  if (component === 'assetDirection') { const qv=q.assetDirectionContext.values, cv=c.assetDirectionContext.values; score=avg([cat(qv.expectedAssetDirection,cv.expectedAssetDirection,20), cat(qv.actualDirection,cv.actualDirection,20), cat(qv.releaseAlignment,cv.releaseAlignment,30)]); }
  if (component === 'pricePath') { score=avg(mutually.flatMap((g)=>{ const qv=(q[g] as any).values, cv=(c[g] as any).values; return [cat(qv.state,cv.state,20), cat(qv.observedDirection,cv.observedDirection,25), num(qv.moveFromOriginPct,cv.moveFromOriginPct,2)]; })); }
  if (component === 'relatedMarket') { const qv=q.relatedMarketContext.values, cv=c.relatedMarketContext.values; score=avg([cat(qv.status,cv.status,20), cat(qv.relatedMarketState,cv.relatedMarketState,20)]); }
  if (component === 'volatility') { const qv=q.volatilityContext.values, cv=c.volatilityContext.values; score=avg([num(qv.immediateVolatilityAdjustedMove,cv.immediateVolatilityAdjustedMove,HISTORICAL_ANALOG_POLICY.bounds.volatilityAdjustedMove), num(qv.confirmationVolatilityAdjustedMove,cv.confirmationVolatilityAdjustedMove,HISTORICAL_ANALOG_POLICY.bounds.volatilityAdjustedMove), available(q.followThroughPathContext,c.followThroughPathContext) ? num(qv.followThroughVolatilityAdjustedMove,cv.followThroughVolatilityAdjustedMove,HISTORICAL_ANALOG_POLICY.bounds.volatilityAdjustedMove) : null]); }
  if (component === 'cognitionShift') { const qv=q.cognitionShiftContext.values, cv=c.cognitionShiftContext.values; score=avg([num(qv.confidenceDelta,cv.confidenceDelta,HISTORICAL_ANALOG_POLICY.bounds.confidenceDelta), num(qv.contradictionDelta,cv.contradictionDelta,HISTORICAL_ANALOG_POLICY.bounds.contradictionDelta), cat(qv.biasChanged,cv.biasChanged,40)]); }
  if (component === 'provenanceQuality') { const qv=q.provenanceContext.values, cv=c.provenanceContext.values; score=avg([cat(qv.requiredReliability,cv.requiredReliability,60), qv.optionalUnverifiedRelatedEvidence || cv.optionalUnverifiedRelatedEvidence ? 50 : 100]); }
  return { score: clamp(score ?? 0), coverage: mutually.length / groups.length, matched: mutually, unavailable, reasons: r.length?r:[`${component}_structured_values_compared`], limitations };
}
export function scoreAnalogMatch(query: AnalogMatchFeatures, candidate: HistoricalAnalogMemoryRecord, candidateFeatures: AnalogMatchFeatures): Omit<HistoricalAnalogMatch, 'rank'> {
  const componentScores: any = {}; let weighted = 0; let coveredWeight = 0; const matched = new Set<AnalogFeatureGroupName>(); const unavailable = new Set<AnalogFeatureGroupName>();
  for (const component of Object.keys(HISTORICAL_ANALOG_POLICY.weights) as HistoricalAnalogComponent[]) { const weight = HISTORICAL_ANALOG_POLICY.weights[component]; const s = scoreComponent(component, query, candidateFeatures); const contribution = s.coverage ? s.score * weight : 0; weighted += contribution; coveredWeight += s.coverage ? weight : 0; s.matched.forEach((g)=>matched.add(g)); s.unavailable.forEach((g)=>unavailable.add(g as AnalogFeatureGroupName)); componentScores[component] = { component, componentScore: Number(s.score.toFixed(4)), componentWeight: weight, weightedContribution: Number(contribution.toFixed(4)), featureCoverage: s.coverage, unavailableFeatureSlices: s.unavailable, reasonCodes: s.reasons, limitations: s.limitations }; }
  const featureCoverageRatio = coveredWeight / 100; const similarityScore = coveredWeight ? clamp(weighted / coveredWeight) : 0;
  const rationale = `Comparable because both events were ${query.eventContext.values.indicatorCategory} releases with structured revision-adjusted surprise, asset direction, price-path, volatility, cognition and provenance components compared only where mutually available. Historical follow-through was not used when unavailable at the query's comparable elapsed horizon. This is non-predictive historical memory, not financial advice.`;
  return { analogMemoryId: candidate.analogMemoryId, sourceEventEvaluationId: candidate.sourceEventEvaluationId, sourceEventInstanceKey: candidate.sourceEventInstanceKey, sourceAsset: candidate.sourceAsset, sourceAssetFamily: candidate.canonicalAssetFamily, similarityScore: Number(similarityScore.toFixed(4)), featureCoverageRatio: Number(featureCoverageRatio.toFixed(4)), componentScores, matchedFeatureGroups: [...matched].sort(), unavailableFeatureGroups: [...unavailable].sort(), reasonCodes: ['deterministic_structured_similarity','historical_outcome_not_used_in_similarity'], sourceProvenanceSummary: candidate.sourceProvenanceSummary, sourceLimitations: candidate.limitations, historicalOutcomeContext: candidate.historicalOutcomeContext, comparisonRationale: rationale };
}
