import type { SqlReasoningQueryExecutor } from '../persistence/sql-reasoning-repository';
import type { HistoricalAnalogRepository, HistoricalAnalogMemoryRecord, HistoricalAnalogRetrievalResult } from './contracts';
import { canonicalJson } from '../expectation-reality/identity';

export class SqlHistoricalAnalogRepository implements HistoricalAnalogRepository {
  constructor(private readonly query: SqlReasoningQueryExecutor) {}
  async saveAnalogMemoryRecord(r: HistoricalAnalogMemoryRecord) { await this.query(`INSERT INTO app_historical_analog_memory (analog_memory_id, source_event_evaluation_id, source_expectation_id, source_event_instance_key, source_asset, canonical_asset_family, event_kind, indicator_kind, indicator_category, available_at, feature_policy_version, feature_content_hash, assessment_evidence_hash, outcome_context_hash, audit_json, created_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16) ON CONFLICT (source_event_evaluation_id, feature_policy_version) DO NOTHING`, [r.analogMemoryId,r.sourceEventEvaluationId,r.sourceExpectationId,r.sourceEventInstanceKey,r.sourceAsset,r.canonicalAssetFamily,r.eventKind,r.indicatorKind,r.indicatorCategory,r.availableAt,r.featurePolicyVersion,r.featureContentHash,r.sourceAssessmentEvidenceHash,r.historicalOutcomeContextHash,JSON.stringify(r),r.createdAt]); const existing=await this.getAnalogMemoryBySource(r.sourceEventEvaluationId,r.featurePolicyVersion); if(!existing || canonicalJson(existing)!==canonicalJson(r)) throw new Error('immutable_analog_memory_conflict'); return existing; }
  async getAnalogMemoryById(id: string) { const rows=await this.query<{audit_json: HistoricalAnalogMemoryRecord}>('SELECT audit_json FROM app_historical_analog_memory WHERE analog_memory_id=$1',[id]); return rows[0]?.audit_json ?? null; }
  async getAnalogMemoryBySource(sourceEventEvaluationId: string, featurePolicyVersion: string) { const rows=await this.query<{audit_json: HistoricalAnalogMemoryRecord}>('SELECT audit_json FROM app_historical_analog_memory WHERE source_event_evaluation_id=$1 AND feature_policy_version=$2',[sourceEventEvaluationId,featurePolicyVersion]); return rows[0]?.audit_json ?? null; }
  async listAnalogMemory(params: { before: string; asset?: any; limit?: number; cursor?: string }) { const sql=`SELECT audit_json FROM app_historical_analog_memory WHERE available_at < $1 ${params.asset?'AND source_asset=$2':''} ORDER BY available_at ASC, analog_memory_id ASC LIMIT ${Math.max(1, Math.min(params.limit ?? 100, 500))}`; const rows=await this.query<{audit_json: HistoricalAnalogMemoryRecord}>(sql, params.asset?[params.before,params.asset]:[params.before]); return rows.map((r)=>r.audit_json); }
  async saveRetrievalResult(r: HistoricalAnalogRetrievalResult) { await this.query(`INSERT INTO app_historical_analog_retrievals (retrieval_id, query_event_evaluation_id, query_event_instance_key, query_cutoff_at, retrieval_policy_version, feature_policy_version, query_feature_hash, memory_snapshot_hash, evidence_sufficiency, audit_json, created_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT (query_event_evaluation_id, query_cutoff_at, retrieval_policy_version, memory_snapshot_hash) DO NOTHING`, [r.retrievalId,r.queryEventEvaluationId,r.queryEventInstanceKey,r.queryCutoffAt,r.retrievalPolicyVersion,r.featurePolicyVersion,r.queryFeatureHash,r.memorySnapshotHash,r.evidenceSufficiency,JSON.stringify(r),r.createdAt]); for (const m of r.matches) await this.query(`INSERT INTO app_historical_analog_retrieval_matches (retrieval_id, rank, analog_memory_id, source_event_evaluation_id, similarity_score, feature_coverage_ratio, audit_json) VALUES ($1,$2,$3,$4,$5,$6,$7) ON CONFLICT (retrieval_id, rank) DO NOTHING`, [r.retrievalId,m.rank,m.analogMemoryId,m.sourceEventEvaluationId,m.similarityScore,m.featureCoverageRatio,JSON.stringify(m)]); const existing=await this.getRetrievalById(r.retrievalId); if(!existing || canonicalJson(existing)!==canonicalJson(r)) throw new Error('immutable_analog_retrieval_conflict'); return existing; }
  async getRetrievalById(id: string) { const rows=await this.query<{audit_json: HistoricalAnalogRetrievalResult}>('SELECT audit_json FROM app_historical_analog_retrievals WHERE retrieval_id=$1',[id]); return rows[0]?.audit_json ?? null; }
  async listRetrievalMatches(retrievalId: string) { const rows=await this.query<{audit_json: any}>('SELECT audit_json FROM app_historical_analog_retrieval_matches WHERE retrieval_id=$1 ORDER BY rank ASC',[retrievalId]); return rows.map((r)=>r.audit_json); }
}
