import type { EvidenceWeightHorizon, ReasoningEvidenceInputItem, ReasoningEvidenceInputSnapshot, TradingAssetCoverage, WeightedEvidenceAssemblyReport, WeightedEvidenceDirection, WeightedEvidenceItem, WeightedEvidenceSnapshot } from '@elceo/types';
import { getWeightPolicy } from './weight-policies';

const ps=(s:string)=>{try{return JSON.parse(s) as Record<string,unknown>;}catch{return {};}};
const dir=(m:Record<string,unknown>):WeightedEvidenceDirection=>{const v=(m.direction??m.sentiment??m.bias); if(typeof v!=='string') return 'unknown'; const n=v.toLowerCase(); if(['bullish','positive','risk_on','hawkish'].includes(n)) return 'bullish'; if(['bearish','negative','risk_off','dovish'].includes(n)) return 'bearish'; if(['neutral'].includes(n)) return 'neutral'; if(['mixed','two_sided'].includes(n)) return 'mixed'; return 'unknown';};
export function inferWeightedEvidenceDirection(item: ReasoningEvidenceInputItem):WeightedEvidenceDirection{const d=dir(ps(item.metadataJson)); if(d!=='unknown') return d; return item.evidenceClass==='market_news'?'neutral':'unknown';}
export function buildWeightedEvidenceItem(inputItem:ReasoningEvidenceInputItem,asset:TradingAssetCoverage,horizon:EvidenceWeightHorizon):WeightedEvidenceItem{const p=getWeightPolicy(asset,inputItem.evidenceClass,horizon); const q=inputItem.qualityScore.finalQualityScore; const aw=(p.baseWeight*q)/100; const d=inferWeightedEvidenceDirection(inputItem); const s=d==='bullish'?1:d==='bearish'?-1:0; return {payloadId:inputItem.payloadId,asset,horizon,evidenceTypeId:inputItem.evidenceTypeId,evidenceClass:inputItem.evidenceClass,providerId:inputItem.providerId,observedAt:inputItem.observedAt,finalQualityScore:q,baseWeight:p.baseWeight,qualityAdjustedWeight:aw,role:p.role,direction:d,contributionScore:aw*s,reasons:[...inputItem.reasons]};}
export function buildWeightedEvidenceSnapshot(inputSnapshot:ReasoningEvidenceInputSnapshot,asset:TradingAssetCoverage,horizon:EvidenceWeightHorizon,generatedAt?:string):WeightedEvidenceSnapshot{const items=inputSnapshot.items.map((x)=>buildWeightedEvidenceItem(x,asset,horizon)).sort((a,b)=>Math.abs(b.contributionScore)-Math.abs(a.contributionScore)||b.qualityAdjustedWeight-a.qualityAdjustedWeight||Date.parse(b.observedAt)-Date.parse(a.observedAt)||a.payloadId.localeCompare(b.payloadId)); const total=items.reduce((n,x)=>n+x.baseWeight,0); const usable=items.filter((x)=>x.role!=='excluded').reduce((n,x)=>n+x.qualityAdjustedWeight,0); const excluded=items.filter((x)=>x.role==='excluded').reduce((n,x)=>n+x.qualityAdjustedWeight,0); const warnings=[...inputSnapshot.warnings]; if(usable<=0) warnings.push('no_usable_weighted_evidence'); return {snapshotId:`weighted|${asset}|${horizon}|${generatedAt??new Date().toISOString()}`,generatedAt:generatedAt??new Date().toISOString(),asset,horizon,totalWeight:Math.min(100,total),usableWeight:Math.min(100,usable),excludedWeight:Math.min(100,excluded),items,warnings};}
export function buildWeightedEvidenceAssemblyReport(snapshot:WeightedEvidenceSnapshot):WeightedEvidenceAssemblyReport{return{generatedAt:snapshot.generatedAt,asset:snapshot.asset,horizon:snapshot.horizon,itemCount:snapshot.items.length,totalWeight:snapshot.totalWeight,usableWeight:snapshot.usableWeight,warnings:[...snapshot.warnings],pass:snapshot.usableWeight>0};}
