import type { AssetEvidenceWeightPolicy, EvidenceWeightHorizon, TradingAssetCoverage, MarketEvidenceClass, WeightedEvidencePolicySnapshot } from '@elceo/types';
import { EVIDENCE_WEIGHT_HORIZONS, MARKET_EVIDENCE_CLASSES, TRADING_ASSET_COVERAGE } from '@elceo/types';

const HMULT:Record<EvidenceWeightHorizon,number>={intraday:0.85,short_term:1,swing:1.1,medium_term:1.2};
const mk=(asset:TradingAssetCoverage,h:EvidenceWeightHorizon,c:MarketEvidenceClass,b:number,r:string):AssetEvidenceWeightPolicy=>({asset,horizon:h,evidenceClass:c,baseWeight:Math.max(0,Math.min(100,Math.round(b*HMULT[h]))),role:b===0?'excluded':b>=80?'primary_driver':b>=60?'secondary_driver':b>=35?'context':'caution',rationale:r});
const pro:Record<TradingAssetCoverage,Partial<Record<MarketEvidenceClass,number>>>= {xau_usd:{real_yields:90,interest_rates:85,central_bank_policy:85,dollar_liquidity:80,inflation:80,labor_market:65,geopolitical_risk:60,precious_metals_flows:65,cot_positioning:50},eur_usd:{central_bank_policy:85,interest_rates:80,inflation:75,labor_market:65,growth_activity:65,cross_market_rates:80,dollar_liquidity:70,cot_positioning:55},gbp_usd:{central_bank_policy:85,interest_rates:80,inflation:75,labor_market:65,growth_activity:65,cross_market_rates:75,dollar_liquidity:70,cot_positioning:55},usd_jpy:{interest_rates:90,real_yields:80,central_bank_policy:90,risk_sentiment:70,dollar_liquidity:65,cross_market_rates:75},usd_chf:{central_bank_policy:75,interest_rates:70,risk_sentiment:65,dollar_liquidity:65,geopolitical_risk:55},aud_usd:{risk_sentiment:70,cross_market_rates:70,growth_activity:65,central_bank_policy:70,dollar_liquidity:65,energy_commodities:50},nzd_usd:{risk_sentiment:70,cross_market_rates:65,growth_activity:60,central_bank_policy:65,dollar_liquidity:65},usd_cad:{interest_rates:75,central_bank_policy:75,dollar_liquidity:70,energy_commodities:70,cross_market_rates:65},btc_usd:{crypto_market_structure:90,dollar_liquidity:80,risk_sentiment:80,interest_rates:65,real_yields:60,market_news:55,geopolitical_risk:45},nasdaq_100:{risk_sentiment:85,interest_rates:80,real_yields:75,earnings_macro:80,financial_conditions:75,equity_index_breadth:75,volatility_surface:75,labor_market:65,growth_activity:65},sp500:{risk_sentiment:80,interest_rates:75,real_yields:70,earnings_macro:75,financial_conditions:75,equity_index_breadth:75,volatility_surface:75,labor_market:65,growth_activity:65},de30:{risk_sentiment:75,interest_rates:70,real_yields:70,earnings_macro:70,financial_conditions:70,equity_index_breadth:70,volatility_surface:70,labor_market:60,growth_activity:65,central_bank_policy:75}};

const DEF='Launch weighting reflects practical macro/market-structure relevance by asset and horizon; non-mapped classes are excluded by default in C5-A17 foundation.';
export function getDefaultAssetEvidenceWeightPolicies(): AssetEvidenceWeightPolicy[]{const out:AssetEvidenceWeightPolicy[]=[]; for(const a of TRADING_ASSET_COVERAGE){for(const h of EVIDENCE_WEIGHT_HORIZONS){for(const c of MARKET_EVIDENCE_CLASSES){out.push(mk(a,h,c,pro[a][c]??0,DEF));}}} return out;}
export function listWeightPoliciesForAsset(asset:TradingAssetCoverage,horizon?:EvidenceWeightHorizon){const all=getDefaultAssetEvidenceWeightPolicies().filter((x)=>x.asset===asset); return horizon?all.filter((x)=>x.horizon===horizon):all;}
export function getWeightPolicy(asset:TradingAssetCoverage,evidenceClass:MarketEvidenceClass,horizon:EvidenceWeightHorizon){return listWeightPoliciesForAsset(asset,horizon).find((x)=>x.evidenceClass===evidenceClass) ?? mk(asset,horizon,evidenceClass,0,DEF);}
export function getWeightedEvidencePolicySnapshot(asOfIso?:string):WeightedEvidencePolicySnapshot{return{generatedAt:asOfIso??new Date().toISOString(),policies:getDefaultAssetEvidenceWeightPolicies()};}
