import type { ProviderCapabilityKind, ScheduledIngestionJobPolicy } from '@elceo/types';

type Seed=Omit<ScheduledIngestionJobPolicy,'jobId'|'jobKey'>&{jobKey:string;providerId:string;capability:ProviderCapabilityKind};
const seed=(s:Seed):ScheduledIngestionJobPolicy=>({...s,jobId:`sched-${s.providerId}-${s.capability}${s.asset?`-${s.asset}`:''}`});

/**
 * Source-level jobs fetch once and fan out to dependent assets. Daily polling is deliberate for release-driven
 * sources because the scheduler contract has no release-aware cadence; freshness/known-at semantics determine usability.
 */
export const CANONICAL_OFFICIAL_SCHEDULE_POLICIES:readonly ScheduledIngestionJobPolicy[]=[
 seed({jobKey:'official-bls-inflation',providerId:'bls_official',capability:'inflation_indicator',asset:null,region:'united_states',cadence:'daily',runMode:'dry_run_fixture',enabled:true,maxRetries:2,retryBackoffSeconds:120,staleAfterMinutes:44640,expiresAfterMinutes:89280,rationale:'BLS CPI release polling; one source observation fans out to USD-sensitive assets.'}),
 seed({jobKey:'official-bls-labor',providerId:'bls_official',capability:'labor_market_indicator',asset:null,region:'united_states',cadence:'daily',runMode:'dry_run_fixture',enabled:true,maxRetries:2,retryBackoffSeconds:120,staleAfterMinutes:44640,expiresAfterMinutes:89280,rationale:'BLS labor release polling with source-level fan-out.'}),
 seed({jobKey:'official-bea-growth',providerId:'bea_official',capability:'growth_activity_indicator',asset:null,region:'united_states',cadence:'daily',runMode:'dry_run_fixture',enabled:true,maxRetries:2,retryBackoffSeconds:180,staleAfterMinutes:100800,expiresAfterMinutes:201600,rationale:'BEA GDP release polling; no per-asset duplicate requests.'}),
 seed({jobKey:'official-census-growth',providerId:'census_official',capability:'growth_activity_indicator',asset:null,region:'united_states',cadence:'daily',runMode:'dry_run_fixture',enabled:true,maxRetries:2,retryBackoffSeconds:120,staleAfterMinutes:44640,expiresAfterMinutes:89280,rationale:'Census economic-indicator release polling.'}),
 seed({jobKey:'official-boe-policy',providerId:'boe_official',capability:'policy_rate_series',asset:null,region:'united_kingdom',cadence:'daily',runMode:'dry_run_fixture',enabled:true,maxRetries:2,retryBackoffSeconds:120,staleAfterMinutes:10080,expiresAfterMinutes:44640,rationale:'BoE Official Bank Rate source-level observation.'}),
 seed({jobKey:'official-rba-policy',providerId:'rba_official',capability:'policy_rate_series',asset:null,region:'australia',cadence:'daily',runMode:'dry_run_fixture',enabled:true,maxRetries:2,retryBackoffSeconds:120,staleAfterMinutes:10080,expiresAfterMinutes:44640,rationale:'RBA cash-rate target source-level observation.'}),
 seed({jobKey:'official-rbnz-policy',providerId:'rbnz_official',capability:'policy_rate_series',asset:null,region:'new_zealand',cadence:'daily',runMode:'dry_run_fixture',enabled:true,maxRetries:2,retryBackoffSeconds:120,staleAfterMinutes:10080,expiresAfterMinutes:44640,rationale:'RBNZ OCR source-level observation.'}),
 seed({jobKey:'official-boc-policy',providerId:'bank_of_canada_official',capability:'policy_rate_series',asset:null,region:'canada',cadence:'daily',runMode:'dry_run_fixture',enabled:true,maxRetries:2,retryBackoffSeconds:120,staleAfterMinutes:10080,expiresAfterMinutes:44640,rationale:'Bank of Canada target overnight rate source-level observation.'}),
 seed({jobKey:'official-statcan-macro',providerId:'statistics_canada_official',capability:'macro_indicator_series',asset:null,region:'canada',cadence:'daily',runMode:'dry_run_fixture',enabled:true,maxRetries:2,retryBackoffSeconds:120,staleAfterMinutes:44640,expiresAfterMinutes:89280,rationale:'Statistics Canada CPI/macro source-level observation.'}),
 seed({jobKey:'official-eia-energy',providerId:'eia_official',capability:'energy_commodity_series',asset:null,region:'united_states',cadence:'daily',runMode:'dry_run_fixture',enabled:true,maxRetries:2,retryBackoffSeconds:120,staleAfterMinutes:2880,expiresAfterMinutes:10080,rationale:'EIA WTI context for CAD and cross-asset cognition.'}),
 seed({jobKey:'official-worldbank-growth',providerId:'world_bank_official',capability:'growth_activity_indicator',asset:null,region:'global',cadence:'weekly',runMode:'dry_run_fixture',enabled:true,maxRetries:1,retryBackoffSeconds:300,staleAfterMinutes:525600,expiresAfterMinutes:1051200,rationale:'World Bank global-growth context; weekly polling is sufficient for annual/low-frequency revisions.'}),
 seed({jobKey:'official-fed-h41-fixture',providerId:'federal_reserve',capability:'central_bank_balance_sheet',asset:null,region:'united_states',cadence:'weekly',runMode:'dry_run_fixture',enabled:true,maxRetries:1,retryBackoffSeconds:120,staleAfterMinutes:10080,expiresAfterMinutes:20160,rationale:'H.4.1 parser readiness only while replacement machine profile is pinned.'}),
 seed({jobKey:'official-eurostat-fixture',providerId:'eurostat_official',capability:'inflation_indicator',asset:null,region:'euro_area',cadence:'daily',runMode:'dry_run_fixture',enabled:true,maxRetries:1,retryBackoffSeconds:120,staleAfterMinutes:44640,expiresAfterMinutes:89280,rationale:'Eurostat HICP parser readiness; live dimensions remain fail-closed.'}),
 seed({jobKey:'official-ons-fixture',providerId:'ons_official',capability:'inflation_indicator',asset:null,region:'united_kingdom',cadence:'daily',runMode:'dry_run_fixture',enabled:true,maxRetries:1,retryBackoffSeconds:120,staleAfterMinutes:44640,expiresAfterMinutes:89280,rationale:'ONS CPIH parser readiness; observation dimensions remain fail-closed.'}),
 seed({jobKey:'official-boj-fixture',providerId:'boj_public',capability:'policy_rate_series',asset:null,region:'japan',cadence:'daily',runMode:'dry_run_fixture',enabled:true,maxRetries:1,retryBackoffSeconds:120,staleAfterMinutes:10080,expiresAfterMinutes:44640,rationale:'BOJ API parser readiness while official series-code profile is pinned.'}),
 seed({jobKey:'official-snb-fixture',providerId:'snb_official',capability:'policy_rate_series',asset:null,region:'switzerland',cadence:'daily',runMode:'dry_run_fixture',enabled:true,maxRetries:1,retryBackoffSeconds:120,staleAfterMinutes:10080,expiresAfterMinutes:44640,rationale:'SNB cube parser readiness; live cube dimensions remain fail-closed.'}),
 seed({jobKey:'official-abs-fixture',providerId:'abs_official',capability:'macro_indicator_series',asset:null,region:'australia',cadence:'daily',runMode:'dry_run_fixture',enabled:true,maxRetries:1,retryBackoffSeconds:120,staleAfterMinutes:44640,expiresAfterMinutes:89280,rationale:'ABS SDMX parser readiness; dataflow key remains fail-closed.'}),
 seed({jobKey:'official-statsnz-fixture',providerId:'stats_nz_official',capability:'macro_indicator_series',asset:null,region:'new_zealand',cadence:'daily',runMode:'dry_run_fixture',enabled:true,maxRetries:1,retryBackoffSeconds:120,staleAfterMinutes:44640,expiresAfterMinutes:89280,rationale:'Stats NZ parser readiness; subscription/product profile remains fail-closed.'}),
 seed({jobKey:'official-imf-fixture',providerId:'imf_official',capability:'macro_indicator_series',asset:null,region:'global',cadence:'weekly',runMode:'dry_run_fixture',enabled:true,maxRetries:1,retryBackoffSeconds:300,staleAfterMinutes:44640,expiresAfterMinutes:89280,rationale:'IMF SDMX parser readiness; current dataflow remains fail-closed.'}),
 seed({jobKey:'official-oecd-fixture',providerId:'oecd_official',capability:'growth_activity_indicator',asset:null,region:'global',cadence:'weekly',runMode:'dry_run_fixture',enabled:true,maxRetries:1,retryBackoffSeconds:300,staleAfterMinutes:44640,expiresAfterMinutes:89280,rationale:'OECD SDMX parser readiness; exact growth/CLI flow remains fail-closed.'}),
 seed({jobKey:'official-bis-fixture',providerId:'bis_official',capability:'cross_market_rate_series',asset:null,region:'global',cadence:'weekly',runMode:'dry_run_fixture',enabled:true,maxRetries:1,retryBackoffSeconds:300,staleAfterMinutes:44640,expiresAfterMinutes:89280,rationale:'BIS SDMX parser readiness; exact cross-market dataflow remains fail-closed.'})
] as const;
