import type { ProviderCapabilityKind, ScheduledIngestionJobPolicy, ScheduledIngestionPolicySnapshot } from '@elceo/types';

type Seed = Omit<ScheduledIngestionJobPolicy, 'jobId'> & { jobKey: string };
const buildJobId = (providerId: string, capability: ProviderCapabilityKind, asset: string | null): string => `sched-${providerId}-${capability}${asset ? `-${asset}` : ''}`;
const seed = (s: Seed): ScheduledIngestionJobPolicy => ({ ...s, jobId: buildJobId(s.providerId, s.capability, s.asset) });

const DEFAULT_POLICIES: ScheduledIngestionJobPolicy[] = [
  seed({ jobKey: '1', providerId: 'tiingo_market_data', capability: 'market_price_history', asset: 'xau_usd', region: 'global', cadence: 'hourly', runMode: 'dry_run_fixture', enabled: true, maxRetries: 2, retryBackoffSeconds: 30, staleAfterMinutes: 90, expiresAfterMinutes: 360, rationale: 'Fixture-safe Tiingo XAU dry-run ingestion.' }),
  seed({ jobKey: '2', providerId: 'tiingo_market_data', capability: 'market_price_history', asset: 'eur_usd', region: 'global', cadence: 'hourly', runMode: 'dry_run_fixture', enabled: true, maxRetries: 2, retryBackoffSeconds: 30, staleAfterMinutes: 90, expiresAfterMinutes: 360, rationale: 'Fixture-safe Tiingo EUR dry-run ingestion.' }),
  seed({ jobKey: '3', providerId: 'tiingo_market_data', capability: 'market_price_history', asset: 'btc_usd', region: 'global', cadence: 'hourly', runMode: 'dry_run_fixture', enabled: true, maxRetries: 2, retryBackoffSeconds: 30, staleAfterMinutes: 90, expiresAfterMinutes: 360, rationale: 'Fixture-safe Tiingo BTC dry-run ingestion.' }),
  seed({ jobKey: '4', providerId: 'tiingo_market_data', capability: 'market_price_history', asset: 'nasdaq_100', region: 'global', cadence: 'hourly', runMode: 'dry_run_fixture', enabled: true, maxRetries: 2, retryBackoffSeconds: 30, staleAfterMinutes: 90, expiresAfterMinutes: 360, rationale: 'Fixture-safe Tiingo Nasdaq dry-run ingestion.' }),
  seed({ jobKey: '5', providerId: 'cftc_cot', capability: 'cot_report', asset: 'xau_usd', region: 'united_states', cadence: 'weekly', runMode: 'dry_run_fixture', enabled: true, maxRetries: 2, retryBackoffSeconds: 60, staleAfterMinutes: 10080, expiresAfterMinutes: 20160, rationale: 'Fixture-safe COT XAU dry-run ingestion.' }),
  seed({ jobKey: '6', providerId: 'cftc_cot', capability: 'cot_report', asset: 'eur_usd', region: 'united_states', cadence: 'weekly', runMode: 'dry_run_fixture', enabled: true, maxRetries: 2, retryBackoffSeconds: 60, staleAfterMinutes: 10080, expiresAfterMinutes: 20160, rationale: 'Fixture-safe COT EUR dry-run ingestion.' }),
  seed({ jobKey: '7', providerId: 'cftc_cot', capability: 'cot_report', asset: 'btc_usd', region: 'united_states', cadence: 'weekly', runMode: 'dry_run_fixture', enabled: true, maxRetries: 2, retryBackoffSeconds: 60, staleAfterMinutes: 10080, expiresAfterMinutes: 20160, rationale: 'Fixture-safe COT BTC dry-run ingestion.' }),
  seed({ jobKey: '8', providerId: 'cftc_cot', capability: 'cot_report', asset: 'nasdaq_100', region: 'united_states', cadence: 'weekly', runMode: 'dry_run_fixture', enabled: true, maxRetries: 2, retryBackoffSeconds: 60, staleAfterMinutes: 10080, expiresAfterMinutes: 20160, rationale: 'Fixture-safe COT Nasdaq dry-run ingestion.' }),
  seed({ jobKey: '9', providerId: 'federal_reserve', capability: 'central_bank_balance_sheet', asset: null, region: 'united_states', cadence: 'weekly', runMode: 'dry_run_fixture', enabled: true, maxRetries: 1, retryBackoffSeconds: 60, staleAfterMinutes: 10080, expiresAfterMinutes: 20160, rationale: 'Foundation policy for central-bank balance-sheet fixture scheduling.' }),
  seed({ jobKey: '10', providerId: 'us_treasury', capability: 'real_yield_series', asset: null, region: 'united_states', cadence: 'daily', runMode: 'dry_run_fixture', enabled: true, maxRetries: 1, retryBackoffSeconds: 60, staleAfterMinutes: 1440, expiresAfterMinutes: 10080, rationale: 'Foundation policy for treasury real-yield fixture scheduling.' }),
  seed({ jobKey: '11', providerId: 'fred', capability: 'credit_stress_indicator', asset: null, region: 'united_states', cadence: 'daily', runMode: 'dry_run_fixture', enabled: true, maxRetries: 1, retryBackoffSeconds: 60, staleAfterMinutes: 1440, expiresAfterMinutes: 10080, rationale: 'Foundation policy for credit-stress fixture scheduling.' }),
  seed({ jobKey: '12', providerId: 'calculated_internal_macro_calendar', capability: 'economic_calendar', asset: null, region: 'global', cadence: 'daily', runMode: 'dry_run_fixture', enabled: true, maxRetries: 1, retryBackoffSeconds: 60, staleAfterMinutes: 1440, expiresAfterMinutes: 10080, rationale: 'Foundation policy for macro-calendar fixture scheduling.' }),
  seed({ jobKey: '13', providerId: 'public_statistics_agencies', capability: 'macro_indicator_series', asset: null, region: 'global', cadence: 'daily', runMode: 'dry_run_fixture', enabled: true, maxRetries: 1, retryBackoffSeconds: 60, staleAfterMinutes: 1440, expiresAfterMinutes: 10080, rationale: 'Foundation policy for macro-indicator fixture scheduling.' }),
  seed({ jobKey: '14', providerId: 'calculated_internal_conditions', capability: 'financial_conditions_index', asset: null, region: 'global', cadence: 'daily', runMode: 'dry_run_fixture', enabled: true, maxRetries: 1, retryBackoffSeconds: 60, staleAfterMinutes: 1440, expiresAfterMinutes: 10080, rationale: 'Foundation policy for financial-conditions fixture scheduling.' }),
  seed({ jobKey: '15', providerId: 'public_equity_breadth_sources', capability: 'equity_index_breadth_indicator', asset: null, region: 'global', cadence: 'daily', runMode: 'dry_run_fixture', enabled: true, maxRetries: 1, retryBackoffSeconds: 60, staleAfterMinutes: 1440, expiresAfterMinutes: 10080, rationale: 'Foundation policy for equity-breadth fixture scheduling.' }),
  seed({ jobKey: '16', providerId: 'geopolitical_public_news', capability: 'geopolitical_risk_event', asset: null, region: 'global', cadence: 'daily', runMode: 'dry_run_fixture', enabled: true, maxRetries: 1, retryBackoffSeconds: 60, staleAfterMinutes: 360, expiresAfterMinutes: 1440, rationale: 'Foundation policy for geopolitical-risk fixture scheduling.' })
];

export const getDefaultScheduledIngestionPolicies = (): ScheduledIngestionJobPolicy[] => DEFAULT_POLICIES;
export const listScheduledIngestionPolicies = (providerId?: string): ScheduledIngestionJobPolicy[] => providerId ? DEFAULT_POLICIES.filter((x) => x.providerId === providerId) : DEFAULT_POLICIES;
export const getScheduledIngestionPolicy = (jobId: string): ScheduledIngestionJobPolicy | null => DEFAULT_POLICIES.find((x) => x.jobId === jobId) ?? null;
export const getScheduledIngestionPolicySnapshot = (asOfIso?: string): ScheduledIngestionPolicySnapshot => ({ generatedAt: asOfIso ?? new Date().toISOString(), policies: DEFAULT_POLICIES });
