import { MemoryNotificationOutboxRepository } from '../persistence/memory-notification-repository.js';
import { resendIdempotencyKey, oneSignalIdempotencyKey } from '../providers/production-transports.js';
import type { NotificationOutboxRecord } from '../delivery/outbox-contracts.js';
const assert=(v:boolean,m:string)=>{if(!v)throw new Error(m)};
export async function runSecGNotificationRecoveryTests(){
 const repo=new MemoryNotificationOutboxRepository(),base:NotificationOutboxRecord={outboxId:'sec-g-outbox',outboxKey:'sec-g-key',decisionId:'d',decisionKey:'dk',asset:'BTC/USD',timeframe:'H1',ruleKey:'r',channel:'email',targetId:'t',subjectKind:'user',subjectId:'u',targetKey:'tk',deliveryAddressJson:'{}',status:'staged',availableAt:'2026-01-01T00:00:00.000Z',lastAttemptAt:null,deliveredAt:null,deadAt:null,attemptCount:0,lastErrorCode:null,lastErrorMessage:null,payloadJson:'{}',createdAt:'2026-01-01T00:00:00.000Z',updatedAt:'2026-01-01T00:00:00.000Z'};
 await repo.stageOutbox(base);const races=await Promise.all(Array.from({length:20},(_,i)=>repo.claimDueOutboxItems('2026-01-01T00:00:00.000Z','2026-01-01T00:00:01.000Z',1,`worker-${i}`)));assert(races.flat().length===1,'twenty claimers must yield one owner');const first=races.flat()[0]!;
 const successor=(await repo.claimDueOutboxItems('2026-01-01T00:00:02.000Z','2026-01-01T00:00:03.000Z',1,'successor'))[0]!;assert(successor.claimGeneration===2,'takeover generation advances');assert(!await repo.markClaimDelivered(first,'2026-01-01T00:00:02.000Z'),'stale delivered rejected');assert(!await repo.markClaimDead(first,'2026-01-01T00:00:02.000Z','x','x'),'stale dead rejected');assert(await repo.markClaimAmbiguous(successor,'2026-01-01T00:00:02.000Z','provider_ambiguous','manual_reconciliation'),'current owner records ambiguity');assert((await repo.listDueOutboxItems('2027-01-01T00:00:00.000Z',10)).length===0,'ambiguous Postmark work is never blindly resent');
 assert(resendIdempotencyKey(first.outboxId)===resendIdempotencyKey(successor.outboxId),'Resend identity survives reclaim');assert(oneSignalIdempotencyKey(first.outboxId)===oneSignalIdempotencyKey(successor.outboxId),'OneSignal identity survives reclaim');
}
