import type { CognitionCalibrationAsset, CognitionCalibrationConfidenceDecomposition, CognitionCalibrationContradictionDetectionResult, CognitionCalibrationCoverageReport, CognitionCalibrationEvidenceCredibilityScore, CognitionCalibrationEvidenceFreshnessScore, CognitionCalibrationEvidenceQualityScore, CognitionCalibrationGuardrailCheck, CognitionCalibrationPressureScoreResult, CognitionCalibrationResult, CognitionCalibrationWeightingHorizon, CognitionCalibrationWeightedEvidenceItem } from '@elceo/types';
import { COGNITION_CALIBRATION_CONFIDENCE_COMPONENT_KINDS, COGNITION_CALIBRATION_CONTRADICTION_KINDS } from '@elceo/types';
import { getGoldenScenarioDefinitions, runGoldenScenario } from '../golden-scenario-reasoning/index';

const cred:Record<string,number>={federal_reserve:0.98,ecb:0.98,boj:0.98,snb:0.97,rba:0.96,rbnz:0.96,boc:0.96,marketaux_news:0.62,newsapi_news:0.58,gdelt_news:0.57,finnhub_news:0.65};
const terms=['buy','sell','hold','guaranteed profit','risk-free profit'];
const contradictionSet=new Set(COGNITION_CALIBRATION_CONTRADICTION_KINDS);
const defaultAsset:CognitionCalibrationAsset='xau_usd';

export const scoreSourceCredibility=(sourceId:string):CognitionCalibrationEvidenceCredibilityScore=>{const score=cred[sourceId]??0.55; return {sourceId,score,band:score>0.9?'official':score>0.7?'trusted':'weak'};};
export const scoreEvidenceFreshness=(observedAt:string,evaluatedAt:string,evidenceId='unknown'):CognitionCalibrationEvidenceFreshnessScore=>{const h=Math.max(0,(Date.parse(evaluatedAt)-Date.parse(observedAt))/36e5); const score=h<=24?1:h<=72?0.75:h<=168?0.45:0.2; return {evidenceId,observedAt,evaluatedAt,ageHours:h,score,band:score>=0.75?'fresh':score>=0.45?'aging':'stale'};};
export const scoreEvidenceQuality=(input:{evidenceId:string;sourceId:string;observedAt:string;evaluatedAt:string;completeness:number;scenarioRelevance:number;extractionConfidence?:number;officialSource?:boolean;marketStructure?:boolean;}):CognitionCalibrationEvidenceQualityScore=>{const c=scoreSourceCredibility(input.sourceId).score; const f=scoreEvidenceFreshness(input.observedAt,input.evaluatedAt,input.evidenceId).score; const ex=input.extractionConfidence??1; let s=(c*0.3+f*0.2+input.completeness*0.2+input.scenarioRelevance*0.2+ex*0.1); if(input.officialSource)s+=0.04; if(input.marketStructure)s+=0.03; s=Math.max(0,Math.min(1,s)); return {evidenceId:input.evidenceId,score:s,band:s>0.75?'high':s>0.5?'medium':'low',reasons:['deterministic_score']};};
const weights:Record<CognitionCalibrationAsset,Record<string,number>>={xau_usd:{real_yields:1,fed_policy:0.95,dxy_liquidity:0.9,inflation:0.85,safe_haven:0.85,etf_flows:0.8},eur_usd:{ecb_policy:0.95,fed_policy:0.9,euro_macro:0.88,us_yields:0.85,dxy:0.8,cot:0.78},gbp_usd:{boe_policy:0.95,uk_inflation:0.9,uk_growth:0.85,fed_usd:0.85,fiscal_risk:0.75},usd_jpy:{us_yields:0.96,boj_policy:0.95,intervention_risk:0.88,safe_haven:0.82,risk_regime:0.78},btc_usd:{liquidity:0.95,etf_regulatory_flow:0.9,crypto_derivatives:0.88,on_chain:0.8,risk_sentiment:0.8},nasdaq_100:{real_yields:0.9,earnings:0.95,breadth:0.9,volatility:0.84,credit_stress:0.8,liquidity:0.86},sp500:{real_yields:0.9,earnings:0.95,breadth:0.9,volatility:0.84,credit_stress:0.82,liquidity:0.86},de30:{ecb_policy:0.9,german_industrial:0.9,euro_growth:0.88,energy_shock:0.82,eu_financial_conditions:0.8},dxy:{fed_policy:0.95,us_macro:0.88,yield_differentials:0.9,risk_off:0.8,dollar_liquidity:0.86},vix:{equity_stress:0.92,volatility_regime:0.92,credit_stress:0.85,macro_event_risk:0.8,risk_off:0.88},aud_usd:{rba_policy:0.94,australia_macro:0.88,china_demand:0.88,commodities:0.86,fed_dxy:0.84,risk_sentiment:0.82},usd_chf:{snb_policy:0.94,swiss_inflation:0.86,safe_haven:0.9,fed_dxy:0.84,europe_risk:0.82},nzd_usd:{rbnz_policy:0.94,nz_macro:0.86,dairy_proxy:0.82,china_demand:0.88,fed_dxy:0.84,risk_sentiment:0.82},usd_cad:{boc_policy:0.94,canada_macro:0.88,oil_energy:0.9,fed_dxy:0.84,yield_differential:0.84}};
export const getAssetEvidenceWeights=(asset:CognitionCalibrationAsset,horizon:CognitionCalibrationWeightingHorizon='swing')=>Object.entries(weights[asset]).map(([theme,weight])=>({asset,theme,weight:Math.max(0,Math.min(1,horizon==='intraday'?weight*0.95:horizon==='position'?weight*1.02:weight)),horizon}));
export const weightEvidenceForAsset=(asset:CognitionCalibrationAsset,items:CognitionCalibrationWeightedEvidenceItem[],_horizon:CognitionCalibrationWeightingHorizon='swing')=>[...items].filter((x)=>x.asset===asset).map((x)=>({...x,weightedScore:Math.max(0,Math.min(1,x.baseWeight*x.qualityScore*(weights[asset][x.theme]??0.6)))})).sort((a,b)=>b.weightedScore-a.weightedScore||a.evidenceId.localeCompare(b.evidenceId));
export const scorePressureForAsset=(asset:CognitionCalibrationAsset,w:CognitionCalibrationWeightedEvidenceItem[]):CognitionCalibrationPressureScoreResult=>{const bull=w.filter((x)=>x.pressureDirection==='bullish').reduce((a,b)=>a+b.weightedScore,0); const bear=w.filter((x)=>x.pressureDirection==='bearish').reduce((a,b)=>a+b.weightedScore,0); const t=bull+bear||1; const d=Math.abs(bull-bear)/t; const direction=d<0.15?'mixed':bull>bear?'bullish':'bearish'; return {asset,direction,strength:d>0.45?'high':d>0.25?'medium':'low',score:Math.max(bull,bear),drivers:w.slice(0,3).map((x)=>x.theme)};};
export const detectEvidenceContradictions=(asset:CognitionCalibrationAsset,w:CognitionCalibrationWeightedEvidenceItem[]):CognitionCalibrationContradictionDetectionResult=>{const kinds:Set<string>=new Set(); if(w.some((x)=>x.theme.includes('real_yields'))&&w.some((x)=>x.theme.includes('safe_haven')))kinds.add('yields_safe_haven_divergence'); if(w.some((x)=>x.theme.includes('earnings'))&&w.some((x)=>x.theme.includes('real_yields')))kinds.add('earnings_yield_divergence'); const contradictionKinds=[...kinds].filter((k)=>contradictionSet.has(k as typeof COGNITION_CALIBRATION_CONTRADICTION_KINDS[number])) as CognitionCalibrationContradictionDetectionResult['contradictionKinds']; return {contradictionDetected:contradictionKinds.length>0,contradictionKinds,involvedEvidenceIds:w.slice(0,2).map((x)=>x.evidenceId).sort(),explanation:contradictionKinds.length?`Contradictions detected for ${asset}`:'No material contradiction.',severity:Math.min(1,contradictionKinds.length*0.25),confidencePenalty:Math.min(1,contradictionKinds.length*0.12)};};
export const decomposeConfidence=(asset:CognitionCalibrationAsset,w:CognitionCalibrationWeightedEvidenceItem[],c:CognitionCalibrationContradictionDetectionResult,f:CognitionCalibrationEvidenceFreshnessScore[]):CognitionCalibrationConfidenceDecomposition=>{const freshness=f.length?f.reduce((a,b)=>a+b.score,0)/f.length:0.5; const quality=w.length?w.reduce((a,b)=>a+b.qualityScore,0)/w.length:0.4; const agreement=Math.max(0,1-c.severity); const completeness=Math.min(1,w.length/6); const score=Math.max(0,Math.min(1,quality*0.3+freshness*0.2+agreement*0.2+completeness*0.2-c.confidencePenalty*0.1)); const componentMap={source_quality:{score:quality,note:'deterministic quality blend'},evidence_freshness:{score:freshness,note:'time decay applied'},evidence_agreement:{score:agreement,note:'contradiction-adjusted'},evidence_completeness:{score:completeness,note:`${asset} theme coverage`},asset_relevance:{score:0.8,note:'asset weighting map'},contradiction_penalty:{score:1-c.confidencePenalty,note:'penalty component'},extraction_confidence:{score:0.8,note:'fixture extraction baseline'},regime_clarity:{score:agreement,note:'pressure coherence'}} as const; return {confidenceBand:score>0.72?'high':score>0.48?'medium':'low',score,components:COGNITION_CALIBRATION_CONFIDENCE_COMPONENT_KINDS.map((kind)=>({kind,score:componentMap[kind].score,note:componentMap[kind].note})),majorReasons:['fixture-only deterministic calibration'],uncertaintyFlags:[...(freshness<0.5?['freshness_warning' as const]:[]),...(c.contradictionDetected?['contradiction_detected' as const]:[]),...(completeness<0.5?['incomplete_evidence' as const]:[])]};};
export const checkCognitionGuardrails=(textOrResult:unknown):CognitionCalibrationGuardrailCheck=>{const str=typeof textOrResult==='string'?textOrResult:JSON.stringify(textOrResult); const found=terms.filter((t)=>new RegExp(`\\b${t.replace('-','[- ]?')}\\b`,'i').test(str)); return {passed:found.length===0,forbiddenTermsFound:[...new Set(found)].sort(),checkedFields:['summary','reasoningNotes'],guardrailStatus:found.length?'fail':'pass'};};
export const runCognitionCalibrationForScenario=(scenarioId:string):CognitionCalibrationResult=>{const g=runGoldenScenario(scenarioId); const asset=g.affectedAssets[0]??defaultAsset; const guardrails=checkCognitionGuardrails(g); return {scenarioId,asset,status:guardrails.passed?'pass':'fail',pressure:{asset,direction:g.pressure==='mixed_caution'||g.pressure==='mixed_positive'?'mixed':g.pressure,strength:g.confidenceBand==='high'?'high':'medium',score:g.confidenceBand==='high'?0.8:g.confidenceBand==='medium'?0.6:0.4,drivers:[...g.topEvidenceClasses].sort()},contradictions:{contradictionDetected:g.contradictionDetected,contradictionKinds:g.contradictionDetected?['risk_regime_divergence']:[],involvedEvidenceIds:[...g.sourceFixtureIds].sort(),explanation:'Derived from golden scenario deterministic output.',severity:g.contradictionDetected?0.4:0,confidencePenalty:g.contradictionDetected?0.12:0},confidence:{confidenceBand:g.confidenceBand,score:g.confidenceBand==='high'?0.8:g.confidenceBand==='medium'?0.6:0.4,components:COGNITION_CALIBRATION_CONFIDENCE_COMPONENT_KINDS.map((kind)=>({kind,score:0.7,note:'scenario-level calibration component'})),majorReasons:[...g.reasoningNotes].sort(),uncertaintyFlags:g.uncertaintyFlags.filter((f)=>f==='freshness_warning'||f==='contradiction_detected'||f==='incomplete_evidence'||f==='weak_source_mix') as CognitionCalibrationConfidenceDecomposition['uncertaintyFlags']},guardrails,summary:'Deterministic fixture-only cognition calibration output.'};};
export const runAllCognitionCalibrationScenarios=()=>getGoldenScenarioDefinitions().map((x)=>runCognitionCalibrationForScenario(x.scenarioId));
export const getCognitionCalibrationCoverageReport=():CognitionCalibrationCoverageReport=>{const r=runAllCognitionCalibrationScenarios(); return {generatedAt:new Date().toISOString(),scenarioCount:r.length,assetCoverage:[...new Set(r.map((x)=>x.asset))].sort(),statusBreakdown:{pass:r.filter((x)=>x.status==='pass').length,warning:r.filter((x)=>x.status==='warning').length,fail:r.filter((x)=>x.status==='fail').length}};};
