import { queryDb } from '../db/client';
import type { BillingOrchestrationRunRepository, PersistedBillingOrchestrationRunRecord } from './contracts';

const cap=(n?:number)=>Math.max(1,Math.min(200,n??20));
const sort=(a:PersistedBillingOrchestrationRunRecord,b:PersistedBillingOrchestrationRunRecord)=>Date.parse(b.createdAt)-Date.parse(a.createdAt)||a.runId.localeCompare(b.runId);

export class MemoryBillingOrchestrationRunRepository implements BillingOrchestrationRunRepository { private rows=new Map<string,PersistedBillingOrchestrationRunRecord>();
 async saveRun(record:PersistedBillingOrchestrationRunRecord){this.rows.set(record.runId,{...record});}
 async getRunById(runId:string){return this.rows.get(runId)??null;}
 async getLatestRunForSubject(subjectKind:'user',subjectId:string){return (await this.listRecentRunsForSubject(subjectKind,subjectId,1))[0]??null;}
 async listRecentRunsForSubject(subjectKind:'user',subjectId:string,limit?:number){return [...this.rows.values()].filter((r)=>r.subjectKind===subjectKind&&r.subjectId===subjectId).sort(sort).slice(0,cap(limit));}
 async getLatestRunForRetrySource(sourceReconciliationRunId?:string|null,sourcePolicyTransitionId?:string|null){if(!sourceReconciliationRunId&&!sourcePolicyTransitionId) return null; return [...this.rows.values()].filter((r)=>r.sourceReconciliationRunId===sourceReconciliationRunId&&r.sourcePolicyTransitionId===sourcePolicyTransitionId).sort(sort)[0]??null;}
}

type Row={run_id:string;subject_kind:'user';subject_id:string;provider_kind:PersistedBillingOrchestrationRunRecord['providerKind'];retry_plan_json:string;status:PersistedBillingOrchestrationRunRecord['status'];changed_lifecycle:boolean;changed_policy:boolean;changed_entitlement:boolean;latest_reconciliation_run_id:string|null;latest_policy_transition_id:string|null;started_at:string;ended_at:string;run_json:string;created_at:string};
const map=(r:Row):PersistedBillingOrchestrationRunRecord=>({runId:r.run_id,subjectKind:r.subject_kind,subjectId:r.subject_id,providerKind:r.provider_kind,retryPlanJson:r.retry_plan_json,status:r.status,changedLifecycle:r.changed_lifecycle,changedPolicy:r.changed_policy,changedEntitlement:r.changed_entitlement,sourceReconciliationRunId:r.latest_reconciliation_run_id,sourcePolicyTransitionId:r.latest_policy_transition_id,startedAt:r.started_at,endedAt:r.ended_at,runJson:r.run_json,createdAt:r.created_at});

export class SQLBillingOrchestrationRunRepository implements BillingOrchestrationRunRepository {
 async saveRun(r:PersistedBillingOrchestrationRunRecord){await queryDb('INSERT INTO app_billing_orchestration_runs (run_id,subject_kind,subject_id,provider_kind,retry_plan_json,status,changed_lifecycle,changed_policy,changed_entitlement,latest_reconciliation_run_id,latest_policy_transition_id,started_at,ended_at,run_json,created_at) VALUES ($1,$2,$3,$4,$5::jsonb,$6,$7,$8,$9,$10,$11,$12,$13,$14::jsonb,$15) ON CONFLICT (run_id) DO UPDATE SET status=EXCLUDED.status,run_json=EXCLUDED.run_json,ended_at=EXCLUDED.ended_at',[r.runId,r.subjectKind,r.subjectId,r.providerKind,r.retryPlanJson,r.status,r.changedLifecycle,r.changedPolicy,r.changedEntitlement,r.sourceReconciliationRunId,r.sourcePolicyTransitionId,r.startedAt,r.endedAt,r.runJson,r.createdAt]);}
 async getRunById(runId:string){const rows=await queryDb<Row>('SELECT run_id,subject_kind,subject_id,provider_kind,retry_plan_json::text AS retry_plan_json,status,changed_lifecycle,changed_policy,changed_entitlement,latest_reconciliation_run_id,latest_policy_transition_id,started_at,ended_at,run_json::text AS run_json,created_at FROM app_billing_orchestration_runs WHERE run_id=$1',[runId]); return rows[0]?map(rows[0]):null;}
 async getLatestRunForSubject(subjectKind:'user',subjectId:string){const rows=await this.listRecentRunsForSubject(subjectKind,subjectId,1); return rows[0]??null;}
 async listRecentRunsForSubject(subjectKind:'user',subjectId:string,limit?:number){const rows=await queryDb<Row>('SELECT run_id,subject_kind,subject_id,provider_kind,retry_plan_json::text AS retry_plan_json,status,changed_lifecycle,changed_policy,changed_entitlement,latest_reconciliation_run_id,latest_policy_transition_id,started_at,ended_at,run_json::text AS run_json,created_at FROM app_billing_orchestration_runs WHERE subject_kind=$1 AND subject_id=$2 ORDER BY created_at DESC, run_id ASC LIMIT $3',[subjectKind,subjectId,cap(limit)]); return rows.map(map);}
 async getLatestRunForRetrySource(sourceReconciliationRunId?:string|null,sourcePolicyTransitionId?:string|null){if(!sourceReconciliationRunId&&!sourcePolicyTransitionId) return null; const rows=await queryDb<Row>('SELECT run_id,subject_kind,subject_id,provider_kind,retry_plan_json::text AS retry_plan_json,status,changed_lifecycle,changed_policy,changed_entitlement,latest_reconciliation_run_id,latest_policy_transition_id,started_at,ended_at,run_json::text AS run_json,created_at FROM app_billing_orchestration_runs WHERE latest_reconciliation_run_id IS NOT DISTINCT FROM $1 AND latest_policy_transition_id IS NOT DISTINCT FROM $2 ORDER BY created_at DESC, run_id ASC LIMIT 1',[sourceReconciliationRunId??null,sourcePolicyTransitionId??null]); return rows[0]?map(rows[0]):null;}
}
