import { queryDb } from '../db/client';
import type { BillingEventRepository, BillingSubscriptionRepository, PersistedBillingEventRecord, PersistedBillingSubscriptionRecord } from './contracts';
const cap=(n?:number)=>Math.max(1,Math.min(500,n??50));
export class MemoryBillingSubscriptionRepository implements BillingSubscriptionRepository { private rows=new Map<string,PersistedBillingSubscriptionRecord>();
  async getLatestSubscriptionForSubject(subjectKind:'user',subjectId:string){return (await this.listSubscriptionsForSubject(subjectKind,subjectId))[0]??null;}
  async getSubscriptionById(subscriptionId:string){return this.rows.get(subscriptionId)??null;}
  async saveSubscription(record:PersistedBillingSubscriptionRecord){this.rows.set(record.subscriptionId,record);}
  async listSubscriptionsForSubject(subjectKind:'user',subjectId:string){return [...this.rows.values()].filter(r=>r.subjectKind===subjectKind&&r.subjectId===subjectId).sort((a,b)=>Date.parse(b.updatedAt)-Date.parse(a.updatedAt)||a.subscriptionId.localeCompare(b.subscriptionId));}
}
export class MemoryBillingEventRepository implements BillingEventRepository { private rows=new Map<string,PersistedBillingEventRecord>(); async saveEvent(r:PersistedBillingEventRecord){this.rows.set(r.eventId,r);} async listEventsForSubscription(subscriptionId:string,limit?:number){return [...this.rows.values()].filter(r=>r.subscriptionId===subscriptionId).sort((a,b)=>Date.parse(b.occurredAt)-Date.parse(a.occurredAt)||a.eventId.localeCompare(b.eventId)).slice(0,cap(limit));} async listEventsForSubject(subjectKind:'user',subjectId:string,limit?:number){return [...this.rows.values()].filter(r=>r.subjectKind===subjectKind&&r.subjectId===subjectId).sort((a,b)=>Date.parse(b.occurredAt)-Date.parse(a.occurredAt)||a.eventId.localeCompare(b.eventId)).slice(0,cap(limit));}}
export class SQLBillingSubscriptionRepository implements BillingSubscriptionRepository {
  async getLatestSubscriptionForSubject(subjectKind:'user',subjectId:string){const rows=await this.listSubscriptionsForSubject(subjectKind,subjectId); return rows[0]??null;}
  async getSubscriptionById(subscriptionId:string){const r=await queryDb<any>(`SELECT * FROM app_billing_subscriptions WHERE subscription_id=$1`,[subscriptionId]);const x=r[0]; if(!x) return null; return {subscriptionId:x.subscription_id,subjectKind:x.subject_kind,subjectId:x.subject_id,providerKind:x.provider_kind,externalSubscriptionId:x.external_subscription_id,planKind:x.plan_kind,subscriptionState:x.subscription_state,interval:x.interval,startedAt:x.started_at,currentPeriodStart:x.current_period_start,currentPeriodEnd:x.current_period_end,cancelAtPeriodEnd:x.cancel_at_period_end,canceledAt:x.canceled_at,trialStartedAt:x.trial_started_at,trialEndsAt:x.trial_ends_at,updatedAt:x.updated_at};}
  async saveSubscription(v:PersistedBillingSubscriptionRecord){await queryDb(`INSERT INTO app_billing_subscriptions (subscription_id,subject_kind,subject_id,provider_kind,external_subscription_id,plan_kind,subscription_state,interval,started_at,current_period_start,current_period_end,cancel_at_period_end,canceled_at,trial_started_at,trial_ends_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16) ON CONFLICT (subscription_id) DO UPDATE SET subject_kind=EXCLUDED.subject_kind,subject_id=EXCLUDED.subject_id,provider_kind=EXCLUDED.provider_kind,external_subscription_id=EXCLUDED.external_subscription_id,plan_kind=EXCLUDED.plan_kind,subscription_state=EXCLUDED.subscription_state,interval=EXCLUDED.interval,started_at=EXCLUDED.started_at,current_period_start=EXCLUDED.current_period_start,current_period_end=EXCLUDED.current_period_end,cancel_at_period_end=EXCLUDED.cancel_at_period_end,canceled_at=EXCLUDED.canceled_at,trial_started_at=EXCLUDED.trial_started_at,trial_ends_at=EXCLUDED.trial_ends_at,updated_at=EXCLUDED.updated_at`,[v.subscriptionId,v.subjectKind,v.subjectId,v.providerKind,v.externalSubscriptionId,v.planKind,v.subscriptionState,v.interval,v.startedAt,v.currentPeriodStart,v.currentPeriodEnd,v.cancelAtPeriodEnd,v.canceledAt,v.trialStartedAt,v.trialEndsAt,v.updatedAt]);}
  async listSubscriptionsForSubject(subjectKind:'user',subjectId:string){const r=await queryDb<any>(`SELECT * FROM app_billing_subscriptions WHERE subject_kind=$1 AND subject_id=$2 ORDER BY updated_at DESC, subscription_id ASC`,[subjectKind,subjectId]); return r.map(x=>({subscriptionId:x.subscription_id,subjectKind:x.subject_kind,subjectId:x.subject_id,providerKind:x.provider_kind,externalSubscriptionId:x.external_subscription_id,planKind:x.plan_kind,subscriptionState:x.subscription_state,interval:x.interval,startedAt:x.started_at,currentPeriodStart:x.current_period_start,currentPeriodEnd:x.current_period_end,cancelAtPeriodEnd:x.cancel_at_period_end,canceledAt:x.canceled_at,trialStartedAt:x.trial_started_at,trialEndsAt:x.trial_ends_at,updatedAt:x.updated_at}));}
}
export class SQLBillingEventRepository implements BillingEventRepository { async saveEvent(v:PersistedBillingEventRecord){await queryDb(`INSERT INTO app_billing_events (event_id,subscription_id,subject_kind,subject_id,kind,provider_kind,external_event_id,occurred_at,event_json,created_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10) ON CONFLICT (event_id) DO UPDATE SET event_json=EXCLUDED.event_json`,[v.eventId,v.subscriptionId,v.subjectKind,v.subjectId,v.kind,v.providerKind,v.externalEventId,v.occurredAt,v.eventJson,v.createdAt]);} async listEventsForSubscription(subscriptionId:string,limit?:number){const r=await queryDb<any>(`SELECT event_id,subscription_id,subject_kind,subject_id,kind,provider_kind,external_event_id,occurred_at,event_json::text,created_at FROM app_billing_events WHERE subscription_id=$1 ORDER BY occurred_at DESC,event_id ASC LIMIT $2`,[subscriptionId,cap(limit)]); return r.map(x=>({eventId:x.event_id,subscriptionId:x.subscription_id,subjectKind:x.subject_kind,subjectId:x.subject_id,kind:x.kind,providerKind:x.provider_kind,externalEventId:x.external_event_id,occurredAt:x.occurred_at,eventJson:x.event_json,createdAt:x.created_at}));} async listEventsForSubject(subjectKind:'user',subjectId:string,limit?:number){const r=await queryDb<any>(`SELECT event_id,subscription_id,subject_kind,subject_id,kind,provider_kind,external_event_id,occurred_at,event_json::text,created_at FROM app_billing_events WHERE subject_kind=$1 AND subject_id=$2 ORDER BY occurred_at DESC,event_id ASC LIMIT $3`,[subjectKind,subjectId,cap(limit)]); return r.map(x=>({eventId:x.event_id,subscriptionId:x.subscription_id,subjectKind:x.subject_kind,subjectId:x.subject_id,kind:x.kind,providerKind:x.provider_kind,externalEventId:x.external_event_id,occurredAt:x.occurred_at,eventJson:x.event_json,createdAt:x.created_at}));}}
