import type { BillingLifecycleProviderKind } from '@elceo/types';
import { queryDb } from '../db/client';
import type { BillingCustomerRepository, BillingLifecycleSubscriptionRepository, BillingReconciliationRunRepository, PersistedBillingCustomerRecord, PersistedBillingLifecycleSubscriptionRecord, PersistedBillingReconciliationRunRecord } from './contracts';

const cap = (n?: number) => Math.max(1, Math.min(200, n ?? 20));

export class MemoryBillingCustomerRepository implements BillingCustomerRepository { private rows = new Map<string, PersistedBillingCustomerRecord>();
  async getCustomerBySubject(subjectKind:'user', subjectId:string, providerKind?:BillingLifecycleProviderKind){const list=[...this.rows.values()].filter((r)=>r.subjectKind===subjectKind&&r.subjectId===subjectId&&(!providerKind||r.providerKind===providerKind)).sort((a,b)=>Date.parse(b.updatedAt)-Date.parse(a.updatedAt)||a.customerId.localeCompare(b.customerId)); return list[0]??null;}
  async getCustomerByProviderId(providerKind:BillingLifecycleProviderKind, providerCustomerId:string){return [...this.rows.values()].find((r)=>r.providerKind===providerKind&&r.providerCustomerId===providerCustomerId)??null;}
  async saveCustomer(record:PersistedBillingCustomerRecord){this.rows.set(record.customerId,{...record});}
}

export class MemoryBillingLifecycleSubscriptionRepository implements BillingLifecycleSubscriptionRepository { private rows = new Map<string, PersistedBillingLifecycleSubscriptionRecord>();
  async getSubscriptionBySubject(subjectKind:'user', subjectId:string, providerKind?:BillingLifecycleProviderKind){const list=[...this.rows.values()].filter((r)=>r.subjectKind===subjectKind&&r.subjectId===subjectId&&(!providerKind||r.providerKind===providerKind)).sort((a,b)=>Date.parse(b.updatedAt)-Date.parse(a.updatedAt)||a.subscriptionId.localeCompare(b.subscriptionId)); return list[0]??null;}
  async getSubscriptionByProviderId(providerKind:BillingLifecycleProviderKind, providerSubscriptionId:string){return [...this.rows.values()].find((r)=>r.providerKind===providerKind&&r.providerSubscriptionId===providerSubscriptionId)??null;}
  async saveSubscription(record:PersistedBillingLifecycleSubscriptionRecord){this.rows.set(record.subscriptionId,{...record});}
}

export class MemoryBillingReconciliationRunRepository implements BillingReconciliationRunRepository { private rows = new Map<string, PersistedBillingReconciliationRunRecord>();
  async saveRun(record:PersistedBillingReconciliationRunRecord){this.rows.set(record.runId,{...record});}
  async getRunById(runId:string){return this.rows.get(runId)??null;}
  async getLatestRunForSubject(subjectKind:'user',subjectId:string){return (await this.listRecentRunsForSubject(subjectKind,subjectId,1))[0]??null;}
  async listRecentRunsForSubject(subjectKind:'user',subjectId:string,limit?:number){return [...this.rows.values()].filter((r)=>r.subjectKind===subjectKind&&r.subjectId===subjectId).sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt)||a.runId.localeCompare(b.runId)).slice(0,cap(limit));}
  async getLatestRunForProviderEvent(providerKind:BillingLifecycleProviderKind,sourceEventId:string){const rows=[...this.rows.values()].filter((r)=>r.providerKind===providerKind&&r.sourceEventId===sourceEventId).sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt)||a.runId.localeCompare(b.runId)); return rows[0]??null;}
}

type CustomerRow = { customer_id:string; subject_kind:'user'; subject_id:string; provider_kind:BillingLifecycleProviderKind; provider_customer_id:string; state:PersistedBillingCustomerRecord['state']; email:string|null; created_at:string; updated_at:string };
type SubscriptionRow = { subscription_id:string; subject_kind:'user'; subject_id:string; provider_kind:BillingLifecycleProviderKind; provider_subscription_id:string; provider_price_id:string|null; provider_product_id:string|null; provider_plan_code:string|null; canonical_plan_kind:PersistedBillingLifecycleSubscriptionRecord['canonicalPlanKind']; plan_source:PersistedBillingLifecycleSubscriptionRecord['planSource']; state:PersistedBillingLifecycleSubscriptionRecord['state']; current_period_start:string|null; current_period_end:string|null; trial_ends_at:string|null; canceled_at:string|null; will_cancel_at_period_end:boolean; latest_provider_event_id:string|null; updated_at:string };
type RunRow = { run_id:string; provider_kind:BillingLifecycleProviderKind; source_event_id:string|null; subject_kind:'user'; subject_id:string; status:PersistedBillingReconciliationRunRecord['status']; summary:string; customer_changed:boolean; subscription_changed:boolean; entitlement_changed:boolean; previous_plan_kind:PersistedBillingReconciliationRunRecord['previousPlanKind']|null; next_plan_kind:PersistedBillingReconciliationRunRecord['nextPlanKind']|null; started_at:string; ended_at:string; run_json:string; created_at:string };

const mapCustomer=(r:CustomerRow):PersistedBillingCustomerRecord=>({customerId:r.customer_id,subjectKind:r.subject_kind,subjectId:r.subject_id,providerKind:r.provider_kind,providerCustomerId:r.provider_customer_id,state:r.state,email:r.email,createdAt:r.created_at,updatedAt:r.updated_at});
const mapSub=(r:SubscriptionRow):PersistedBillingLifecycleSubscriptionRecord=>({subscriptionId:r.subscription_id,subjectKind:r.subject_kind,subjectId:r.subject_id,providerKind:r.provider_kind,providerSubscriptionId:r.provider_subscription_id,providerPriceId:r.provider_price_id,providerProductId:r.provider_product_id,providerPlanCode:r.provider_plan_code,canonicalPlanKind:r.canonical_plan_kind,planSource:r.plan_source,state:r.state,currentPeriodStart:r.current_period_start,currentPeriodEnd:r.current_period_end,trialEndsAt:r.trial_ends_at,canceledAt:r.canceled_at,willCancelAtPeriodEnd:r.will_cancel_at_period_end,latestProviderEventId:r.latest_provider_event_id,updatedAt:r.updated_at});
const mapRun=(r:RunRow):PersistedBillingReconciliationRunRecord=>({runId:r.run_id,providerKind:r.provider_kind,sourceEventId:r.source_event_id,subjectKind:r.subject_kind,subjectId:r.subject_id,status:r.status,summary:r.summary,customerChanged:r.customer_changed,subscriptionChanged:r.subscription_changed,entitlementChanged:r.entitlement_changed,previousPlanKind:r.previous_plan_kind,nextPlanKind:r.next_plan_kind,startedAt:r.started_at,endedAt:r.ended_at,createdAt:r.created_at,runJson:r.run_json});

export class SQLBillingCustomerRepository implements BillingCustomerRepository { async getCustomerBySubject(subjectKind:'user',subjectId:string,providerKind?:BillingLifecycleProviderKind){const rows=providerKind?await queryDb<CustomerRow>('SELECT customer_id,subject_kind,subject_id,provider_kind,provider_customer_id,state,email,created_at,updated_at FROM app_billing_customers WHERE subject_kind=$1 AND subject_id=$2 AND provider_kind=$3 ORDER BY updated_at DESC, customer_id ASC LIMIT 1',[subjectKind,subjectId,providerKind]):await queryDb<CustomerRow>('SELECT customer_id,subject_kind,subject_id,provider_kind,provider_customer_id,state,email,created_at,updated_at FROM app_billing_customers WHERE subject_kind=$1 AND subject_id=$2 ORDER BY updated_at DESC, customer_id ASC LIMIT 1',[subjectKind,subjectId]); return rows[0]?mapCustomer(rows[0]):null; }
  async getCustomerByProviderId(providerKind:BillingLifecycleProviderKind,providerCustomerId:string){const rows=await queryDb<CustomerRow>('SELECT customer_id,subject_kind,subject_id,provider_kind,provider_customer_id,state,email,created_at,updated_at FROM app_billing_customers WHERE provider_kind=$1 AND provider_customer_id=$2 LIMIT 1',[providerKind,providerCustomerId]); return rows[0]?mapCustomer(rows[0]):null; }
  async saveCustomer(r:PersistedBillingCustomerRecord){await queryDb('INSERT INTO app_billing_customers (customer_id,subject_kind,subject_id,provider_kind,provider_customer_id,state,email,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT (customer_id) DO UPDATE SET subject_kind=EXCLUDED.subject_kind,subject_id=EXCLUDED.subject_id,provider_kind=EXCLUDED.provider_kind,provider_customer_id=EXCLUDED.provider_customer_id,state=EXCLUDED.state,email=EXCLUDED.email,updated_at=EXCLUDED.updated_at',[r.customerId,r.subjectKind,r.subjectId,r.providerKind,r.providerCustomerId,r.state,r.email,r.createdAt,r.updatedAt]); }}
export class SQLBillingLifecycleSubscriptionRepository implements BillingLifecycleSubscriptionRepository { async getSubscriptionBySubject(subjectKind:'user',subjectId:string,providerKind?:BillingLifecycleProviderKind){const rows=providerKind?await queryDb<SubscriptionRow>('SELECT subscription_id,subject_kind,subject_id,provider_kind,provider_subscription_id,provider_price_id,provider_product_id,provider_plan_code,canonical_plan_kind,plan_source,state,current_period_start,current_period_end,trial_ends_at,canceled_at,will_cancel_at_period_end,latest_provider_event_id,updated_at FROM app_billing_subscriptions_lifecycle WHERE subject_kind=$1 AND subject_id=$2 AND provider_kind=$3 ORDER BY updated_at DESC, subscription_id ASC LIMIT 1',[subjectKind,subjectId,providerKind]):await queryDb<SubscriptionRow>('SELECT subscription_id,subject_kind,subject_id,provider_kind,provider_subscription_id,provider_price_id,provider_product_id,provider_plan_code,canonical_plan_kind,plan_source,state,current_period_start,current_period_end,trial_ends_at,canceled_at,will_cancel_at_period_end,latest_provider_event_id,updated_at FROM app_billing_subscriptions_lifecycle WHERE subject_kind=$1 AND subject_id=$2 ORDER BY updated_at DESC, subscription_id ASC LIMIT 1',[subjectKind,subjectId]); return rows[0]?mapSub(rows[0]):null; }
  async getSubscriptionByProviderId(providerKind:BillingLifecycleProviderKind,providerSubscriptionId:string){const rows=await queryDb<SubscriptionRow>('SELECT subscription_id,subject_kind,subject_id,provider_kind,provider_subscription_id,provider_price_id,provider_product_id,provider_plan_code,canonical_plan_kind,plan_source,state,current_period_start,current_period_end,trial_ends_at,canceled_at,will_cancel_at_period_end,latest_provider_event_id,updated_at FROM app_billing_subscriptions_lifecycle WHERE provider_kind=$1 AND provider_subscription_id=$2 LIMIT 1',[providerKind,providerSubscriptionId]); return rows[0]?mapSub(rows[0]):null; }
  async saveSubscription(r:PersistedBillingLifecycleSubscriptionRecord){await queryDb('INSERT INTO app_billing_subscriptions_lifecycle (subscription_id,subject_kind,subject_id,provider_kind,provider_subscription_id,provider_price_id,provider_product_id,provider_plan_code,canonical_plan_kind,plan_source,state,current_period_start,current_period_end,trial_ends_at,canceled_at,will_cancel_at_period_end,latest_provider_event_id,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18) ON CONFLICT (subscription_id) DO UPDATE SET subject_kind=EXCLUDED.subject_kind,subject_id=EXCLUDED.subject_id,provider_kind=EXCLUDED.provider_kind,provider_subscription_id=EXCLUDED.provider_subscription_id,provider_price_id=EXCLUDED.provider_price_id,provider_product_id=EXCLUDED.provider_product_id,provider_plan_code=EXCLUDED.provider_plan_code,canonical_plan_kind=EXCLUDED.canonical_plan_kind,plan_source=EXCLUDED.plan_source,state=EXCLUDED.state,current_period_start=EXCLUDED.current_period_start,current_period_end=EXCLUDED.current_period_end,trial_ends_at=EXCLUDED.trial_ends_at,canceled_at=EXCLUDED.canceled_at,will_cancel_at_period_end=EXCLUDED.will_cancel_at_period_end,latest_provider_event_id=EXCLUDED.latest_provider_event_id,updated_at=EXCLUDED.updated_at',[r.subscriptionId,r.subjectKind,r.subjectId,r.providerKind,r.providerSubscriptionId,r.providerPriceId,r.providerProductId,r.providerPlanCode,r.canonicalPlanKind,r.planSource,r.state,r.currentPeriodStart,r.currentPeriodEnd,r.trialEndsAt,r.canceledAt,r.willCancelAtPeriodEnd,r.latestProviderEventId,r.updatedAt]); }}
export class SQLBillingReconciliationRunRepository implements BillingReconciliationRunRepository { async saveRun(r:PersistedBillingReconciliationRunRecord){await queryDb('INSERT INTO app_billing_reconciliation_runs (run_id,provider_kind,source_event_id,subject_kind,subject_id,status,summary,customer_changed,subscription_changed,entitlement_changed,previous_plan_kind,next_plan_kind,started_at,ended_at,run_json,created_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15::jsonb,$16) ON CONFLICT (run_id) DO UPDATE SET status=EXCLUDED.status,summary=EXCLUDED.summary,run_json=EXCLUDED.run_json,ended_at=EXCLUDED.ended_at',[r.runId,r.providerKind,r.sourceEventId,r.subjectKind,r.subjectId,r.status,r.summary,r.customerChanged,r.subscriptionChanged,r.entitlementChanged,r.previousPlanKind,r.nextPlanKind,r.startedAt,r.endedAt,r.runJson,r.createdAt]); }
  async getRunById(runId:string){const rows=await queryDb<RunRow>('SELECT run_id,provider_kind,source_event_id,subject_kind,subject_id,status,summary,customer_changed,subscription_changed,entitlement_changed,previous_plan_kind,next_plan_kind,started_at,ended_at,run_json::text AS run_json,created_at FROM app_billing_reconciliation_runs WHERE run_id=$1',[runId]); return rows[0]?mapRun(rows[0]):null; }
  async getLatestRunForSubject(subjectKind:'user',subjectId:string){const rows=await this.listRecentRunsForSubject(subjectKind,subjectId,1); return rows[0]??null; }
  async listRecentRunsForSubject(subjectKind:'user',subjectId:string,limit?:number){const rows=await queryDb<RunRow>('SELECT run_id,provider_kind,source_event_id,subject_kind,subject_id,status,summary,customer_changed,subscription_changed,entitlement_changed,previous_plan_kind,next_plan_kind,started_at,ended_at,run_json::text AS run_json,created_at FROM app_billing_reconciliation_runs WHERE subject_kind=$1 AND subject_id=$2 ORDER BY created_at DESC, run_id ASC LIMIT $3',[subjectKind,subjectId,cap(limit)]); return rows.map(mapRun); }
  async getLatestRunForProviderEvent(providerKind:BillingLifecycleProviderKind,sourceEventId:string){const rows=await queryDb<RunRow>('SELECT run_id,provider_kind,source_event_id,subject_kind,subject_id,status,summary,customer_changed,subscription_changed,entitlement_changed,previous_plan_kind,next_plan_kind,started_at,ended_at,run_json::text AS run_json,created_at FROM app_billing_reconciliation_runs WHERE provider_kind=$1 AND source_event_id=$2 ORDER BY created_at DESC, run_id ASC LIMIT 1',[providerKind,sourceEventId]); return rows[0]?mapRun(rows[0]):null; }
}
