import { queryDb } from '../db/client';
import type { OpsJobKind, OpsJobScope } from '@elceo/types';
import type { OpsJobLeaseRepository, OpsJobRunListQuery, OpsJobRunRepository, PersistedOpsJobLeaseRecord, PersistedOpsJobRunRecord } from './contracts';

type OpsLeaseRow = {
  lease_id: string; job_kind: OpsJobKind; scope_kind: OpsJobScope; scope_key: string; lease_state: PersistedOpsJobLeaseRecord['leaseState']; acquired_at: string; expires_at: string; released_at: string | null; holder_id: string; created_at: string;
};
type OpsRunRow = {
  run_id: string; job_kind: OpsJobKind; trigger_kind: PersistedOpsJobRunRecord['triggerKind']; scope_kind: OpsJobScope; scope_key: string; started_at: string; ended_at: string; duration_ms: number; status: PersistedOpsJobRunRecord['status']; warnings_json: string; failure_reason: string | null; child_report_ids_json: string; metrics_json: string; report_json: string; created_at: string;
};

type CountRow = { affected_count: string };

const cap = (n?: number): number => Math.max(1, Math.min(500, n ?? 50));
const runSort = (a: PersistedOpsJobRunRecord, b: PersistedOpsJobRunRecord): number => Date.parse(b.createdAt) - Date.parse(a.createdAt) || a.runId.localeCompare(b.runId);
const leaseSort = (a: PersistedOpsJobLeaseRecord, b: PersistedOpsJobLeaseRecord): number => Date.parse(a.expiresAt) - Date.parse(b.expiresAt) || a.leaseId.localeCompare(b.leaseId);

const mapLease = (r: OpsLeaseRow): PersistedOpsJobLeaseRecord => ({ leaseId: r.lease_id, jobKind: r.job_kind, scopeKind: r.scope_kind, scopeKey: r.scope_key, leaseState: r.lease_state, acquiredAt: r.acquired_at, expiresAt: r.expires_at, releasedAt: r.released_at, holderId: r.holder_id, createdAt: r.created_at });
const mapRun = (r: OpsRunRow): PersistedOpsJobRunRecord => ({ runId: r.run_id, jobKind: r.job_kind, triggerKind: r.trigger_kind, scopeKind: r.scope_kind, scopeKey: r.scope_key, startedAt: r.started_at, endedAt: r.ended_at, durationMs: r.duration_ms, status: r.status, warningsJson: r.warnings_json, failureReason: r.failure_reason, childReportIdsJson: r.child_report_ids_json, metricsJson: r.metrics_json, reportJson: r.report_json, createdAt: r.created_at });

export class MemoryOpsJobLeaseRepository implements OpsJobLeaseRepository { private leases = new Map<string, PersistedOpsJobLeaseRecord>(); async acquireLease(params: PersistedOpsJobLeaseRecord) { const active = [...this.leases.values()].find((l) => l.jobKind === params.jobKind && l.scopeKind === params.scopeKind && l.scopeKey === params.scopeKey && l.leaseState === 'acquired' && Date.parse(l.expiresAt) > Date.parse(params.acquiredAt)); if (active) return { acquired: false as const, existingLease: active }; this.leases.set(params.leaseId, params); return { acquired: true as const, lease: params }; } async releaseLease(leaseId: string, releasedAt: string) { const row = this.leases.get(leaseId); if (!row) return; this.leases.set(leaseId, { ...row, leaseState: 'released', releasedAt }); } async getLeaseByJobScope(jobKind: OpsJobKind, scopeKind: OpsJobScope, scopeKey: string) { return [...this.leases.values()].filter((l) => l.jobKind === jobKind && l.scopeKind === scopeKind && l.scopeKey === scopeKey).sort((a, b) => Date.parse(b.createdAt) - Date.parse(a.createdAt) || a.leaseId.localeCompare(b.leaseId))[0] ?? null; } async cleanupExpiredLeases(asOfIso: string) { let c = 0; for (const [k, v] of this.leases) { if (v.leaseState === 'acquired' && Date.parse(v.expiresAt) <= Date.parse(asOfIso)) { this.leases.set(k, { ...v, leaseState: 'expired' }); c++; } } return c; } async listStaleLeases(asOfIso: string) { return [...this.leases.values()].filter((l) => Date.parse(l.expiresAt) <= Date.parse(asOfIso) && l.releasedAt === null).sort(leaseSort); } }

export class MemoryOpsJobRunRepository implements OpsJobRunRepository { private runs = new Map<string, PersistedOpsJobRunRecord>(); async saveRun(r: PersistedOpsJobRunRecord) { this.runs.set(r.runId, r); } async getRunById(runId: string) { return this.runs.get(runId) ?? null; } async getLatestRun(jobKind: OpsJobKind, scopeKind: OpsJobScope, scopeKey: string) { return [...this.runs.values()].filter((r) => r.jobKind === jobKind && r.scopeKind === scopeKind && r.scopeKey === scopeKey).sort(runSort)[0] ?? null; } async listRecentRuns(q: OpsJobRunListQuery = {}) { return [...this.runs.values()].filter((r) => (!q.jobKind || r.jobKind === q.jobKind) && (!q.scopeKind || r.scopeKind === q.scopeKind) && (!q.scopeKey || r.scopeKey === q.scopeKey) && (!q.status || r.status === q.status)).sort(runSort).slice(0, cap(q.limit)); } async listRecentFailedRuns(limit?: number) { return [...this.runs.values()].filter((r) => r.status === 'failed').sort(runSort).slice(0, cap(limit)); } }

export class SqlOpsJobLeaseRepository implements OpsJobLeaseRepository {
  async acquireLease(p: PersistedOpsJobLeaseRecord) { const ex = await queryDb<OpsLeaseRow>(`SELECT lease_id,job_kind,scope_kind,scope_key,lease_state,acquired_at,expires_at,released_at,holder_id,created_at FROM app_ops_job_leases WHERE job_kind=$1 AND scope_kind=$2 AND scope_key=$3 AND lease_state='acquired' AND expires_at > $4 ORDER BY created_at DESC LIMIT 1`, [p.jobKind, p.scopeKind, p.scopeKey, p.acquiredAt]); if (ex[0]) return { acquired: false as const, existingLease: mapLease(ex[0]) }; await queryDb(`INSERT INTO app_ops_job_leases (lease_id,job_kind,scope_kind,scope_key,lease_state,acquired_at,expires_at,released_at,holder_id,created_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`, [p.leaseId, p.jobKind, p.scopeKind, p.scopeKey, p.leaseState, p.acquiredAt, p.expiresAt, p.releasedAt, p.holderId, p.createdAt]); return { acquired: true as const, lease: p }; }
  async releaseLease(leaseId: string, releasedAt: string) { await queryDb(`UPDATE app_ops_job_leases SET lease_state='released',released_at=$2 WHERE lease_id=$1`, [leaseId, releasedAt]); }
  async getLeaseByJobScope(jobKind: OpsJobKind, scopeKind: OpsJobScope, scopeKey: string) { const r = await queryDb<OpsLeaseRow>(`SELECT lease_id,job_kind,scope_kind,scope_key,lease_state,acquired_at,expires_at,released_at,holder_id,created_at FROM app_ops_job_leases WHERE job_kind=$1 AND scope_kind=$2 AND scope_key=$3 ORDER BY created_at DESC LIMIT 1`, [jobKind, scopeKind, scopeKey]); return r[0] ? mapLease(r[0]) : null; }
  async cleanupExpiredLeases(asOfIso: string) { const rows = await queryDb<CountRow>(`WITH updated AS (UPDATE app_ops_job_leases SET lease_state='expired' WHERE lease_state='acquired' AND expires_at <= $1 RETURNING lease_id) SELECT COUNT(*)::text AS affected_count FROM updated`, [asOfIso]); return Number(rows[0]?.affected_count ?? '0'); }
  async listStaleLeases(asOfIso: string) { const r = await queryDb<OpsLeaseRow>(`SELECT lease_id,job_kind,scope_kind,scope_key,lease_state,acquired_at,expires_at,released_at,holder_id,created_at FROM app_ops_job_leases WHERE expires_at <= $1 AND released_at IS NULL ORDER BY expires_at ASC, lease_id ASC`, [asOfIso]); return r.map(mapLease); }
}

export class SqlOpsJobRunRepository implements OpsJobRunRepository {
  async saveRun(r: PersistedOpsJobRunRecord) { await queryDb(`INSERT INTO app_ops_job_runs (run_id,job_kind,trigger_kind,scope_kind,scope_key,started_at,ended_at,duration_ms,status,warnings_json,failure_reason,child_report_ids_json,metrics_json,report_json,created_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb,$11,$12::jsonb,$13::jsonb,$14::jsonb,$15) ON CONFLICT (run_id) DO UPDATE SET report_json=EXCLUDED.report_json`, [r.runId, r.jobKind, r.triggerKind, r.scopeKind, r.scopeKey, r.startedAt, r.endedAt, r.durationMs, r.status, r.warningsJson, r.failureReason, r.childReportIdsJson, r.metricsJson, r.reportJson, r.createdAt]); }
  async getRunById(runId: string) { const r = await queryDb<OpsRunRow>(`SELECT run_id,job_kind,trigger_kind,scope_kind,scope_key,started_at,ended_at,duration_ms,status,warnings_json::text AS warnings_json,failure_reason,child_report_ids_json::text AS child_report_ids_json,metrics_json::text AS metrics_json,report_json::text AS report_json,created_at FROM app_ops_job_runs WHERE run_id=$1`, [runId]); return r[0] ? mapRun(r[0]) : null; }
  async getLatestRun(jobKind: OpsJobKind, scopeKind: OpsJobScope, scopeKey: string) { const r = await this.listRecentRuns({ jobKind, scopeKind, scopeKey, limit: 1 }); return r[0] ?? null; }
  async listRecentRuns(q: OpsJobRunListQuery = {}) { const r = await queryDb<OpsRunRow>(`SELECT run_id,job_kind,trigger_kind,scope_kind,scope_key,started_at,ended_at,duration_ms,status,warnings_json::text AS warnings_json,failure_reason,child_report_ids_json::text AS child_report_ids_json,metrics_json::text AS metrics_json,report_json::text AS report_json,created_at FROM app_ops_job_runs WHERE ($1::text IS NULL OR job_kind=$1) AND ($2::text IS NULL OR scope_kind=$2) AND ($3::text IS NULL OR scope_key=$3) AND ($4::text IS NULL OR status=$4) ORDER BY created_at DESC, run_id ASC LIMIT $5`, [q.jobKind ?? null, q.scopeKind ?? null, q.scopeKey ?? null, q.status ?? null, cap(q.limit)]); return r.map(mapRun); }
  async listRecentFailedRuns(limit?: number) { return this.listRecentRuns(limit === undefined ? { status: 'failed' } : { status: 'failed', limit }); }
}

let leaseRepo: OpsJobLeaseRepository | null = null;
let runRepo: OpsJobRunRepository | null = null;
export function getOpsJobLeaseRepository(): OpsJobLeaseRepository { if (!leaseRepo) leaseRepo = process.env.APP_STATE_REPOSITORY === 'sql' ? new SqlOpsJobLeaseRepository() : new MemoryOpsJobLeaseRepository(); return leaseRepo; }
export function getOpsJobRunRepository(): OpsJobRunRepository { if (!runRepo) runRepo = process.env.APP_STATE_REPOSITORY === 'sql' ? new SqlOpsJobRunRepository() : new MemoryOpsJobRunRepository(); return runRepo; }
