import { createHash, randomUUID } from 'node:crypto';
import type { SuperAdminCommercialActionKind, SuperAdminCommercialControlSnapshot, SuperAdminFocusPlanGiftRecord, SuperAdminFocusPlanGiftRequest, SuperAdminFocusPlanGiftResult, SuperAdminRetractGiftRequest, SuperAdminRetractGiftResult, SuperAdminUserRestrictionRecord, SuperAdminUserRestrictionRequest, SuperAdminUserRestrictionResult } from '@elceo/types';
import { queryDb, withDbTransaction, type DbTransactionClient } from '../db/client';
import { CommercialPersistenceError, type CommercialPersistenceStatus } from './commercial-persistence-error';

const days=(d:number)=>d*24*60*60*1000;
const buildGiftEnd=(start:string,d:'two_weeks'|'one_month')=>new Date(new Date(start).getTime()+(d==='two_weeks'?days(14):days(30))).toISOString();
const runtimeEnv=()=> (globalThis as {process?:{env?:Record<string,string|undefined>}}).process?.env ?? {};
const hash=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
type AnyResult=(SuperAdminFocusPlanGiftResult|SuperAdminRetractGiftResult|SuperAdminUserRestrictionResult)&{persistenceStatus:CommercialPersistenceStatus};

type Op={requestHash:string; response:AnyResult};
export interface SuperAdminCommercialRepository { createFocusPlanGiftAtomically(input:SuperAdminFocusPlanGiftRequest):Promise<AnyResult>; retractFocusPlanGiftAtomically(input:SuperAdminRetractGiftRequest):Promise<AnyResult>; createUserRestrictionAtomically(input:SuperAdminUserRestrictionRequest):Promise<AnyResult>; getControlSnapshot(targetUserId:string, asOfIso?:string):Promise<SuperAdminCommercialControlSnapshot>; getOperationByIdempotency(actorUserId:string, actionKind:SuperAdminCommercialActionKind, idempotencyKey:string):Promise<AnyResult|null>; getPersistenceReadiness():Promise<{selectedRepositoryMode:'sql'|'memory'|'unavailable';databaseConfigured:boolean;requiredRelationsAvailable:boolean;persistenceStatus:CommercialPersistenceStatus}>; clear?():void; }

function giftReq(i:SuperAdminFocusPlanGiftRequest){return hash({actor:i.actorSuperAdminId,action:'focus_plan_gift',target:i.targetUserId,duration:i.duration,reasonCode:i.reasonCode,operatorNote:i.operatorNote});}
function retractReq(i:SuperAdminRetractGiftRequest){return hash({actor:i.actorSuperAdminId,action:'focus_plan_gift_retract',target:i.targetUserId,giftRecordId:i.giftRecordId,reasonCode:i.reasonCode,operatorNote:i.operatorNote});}
function restrictionReq(i:SuperAdminUserRestrictionRequest){return hash({actor:i.actorSuperAdminId,action:'user_restriction',target:i.targetUserId,restrictionKind:i.restrictionKind,reasonCode:i.reasonCode,operatorNote:i.operatorNote});}
function entitlement(gift:SuperAdminFocusPlanGiftRecord|null, restricted:boolean, subscriptionActive=false, nowIso=new Date().toISOString()) { if(restricted) return 'restricted'; if(subscriptionActive) return 'focus_plan_active'; return gift && gift.status==='active' && new Date(nowIso).getTime()<new Date(gift.endsAt).getTime() ? 'focus_plan_active' : 'subscription_required'; }
function blocked(reason:any, persistenceStatus:CommercialPersistenceStatus, kind:'gift'|'restriction'='gift'):AnyResult { return kind==='restriction' ? {status:'blocked',failureReason:reason,restrictionRecord:null,resultingEntitlementState:'restricted',persistenceStatus} as AnyResult : {status:'blocked',failureReason:reason,giftRecord:null,resultingEntitlementState:'subscription_required',persistenceStatus} as AnyResult; }

export class MemorySuperAdminCommercialRepository implements SuperAdminCommercialRepository {
  private gifts=new Map<string,SuperAdminFocusPlanGiftRecord>(); private restrictions=new Map<string,SuperAdminUserRestrictionRecord>(); private ops=new Map<string,Op>(); private chain=Promise.resolve();
  private async serial<T>(fn:()=>Promise<T>|T):Promise<T>{ const run=this.chain.then(fn,fn); this.chain=run.then(()=>undefined,()=>undefined); return run; }
  private opKey(actor:string,action:string,key:string){return `${actor}\0${action}\0${key}`;}
  private replay(actor:string,action:SuperAdminCommercialActionKind,key:string|null,requestHash:string){ if(!key) return null; const op=this.ops.get(this.opKey(actor,action,key)); if(!op) return null; return op.requestHash===requestHash ? op.response : blocked('idempotency_conflict','memory_fallback'); }
  private store(actor:string,action:SuperAdminCommercialActionKind,key:string|null,requestHash:string,response:AnyResult){ if(key) this.ops.set(this.opKey(actor,action,key),{requestHash,response}); }
  async createFocusPlanGiftAtomically(input:SuperAdminFocusPlanGiftRequest){ return this.serial(()=>{ const requestHash=giftReq(input); const replay=this.replay(input.actorSuperAdminId,'focus_plan_gift',input.idempotencyKey,requestHash); if(replay) return replay; const now=input.requestedAt; for(const g of this.gifts.values()) if(g.targetUserId===input.targetUserId&&g.status==='active'&&new Date(now).getTime()>=new Date(g.endsAt).getTime()) this.gifts.set(g.giftRecordId,{...g,status:'expired',updatedAt:now}); const active=[...this.gifts.values()].find(g=>g.targetUserId===input.targetUserId&&g.status==='active'&&new Date(now).getTime()<new Date(g.endsAt).getTime()); if(active){const res=blocked('gift_already_active','memory_fallback'); this.store(input.actorSuperAdminId,'focus_plan_gift',input.idempotencyKey,requestHash,res); return res;} const giftRecord:SuperAdminFocusPlanGiftRecord={giftRecordId:`gift_${randomUUID()}`,actorSuperAdminId:input.actorSuperAdminId,targetUserId:input.targetUserId,planCode:'focus_plan',duration:input.duration,status:'active',startsAt:now,endsAt:buildGiftEnd(now,input.duration),reasonCode:input.reasonCode,operatorNote:input.operatorNote,stepUpStatus:'verified',idempotencyKey:input.idempotencyKey,createdAt:now,updatedAt:now}; this.gifts.set(giftRecord.giftRecordId,giftRecord); const res={status:'success' as const,failureReason:null,giftRecord,resultingEntitlementState:'focus_plan_active' as const,persistenceStatus:'memory_fallback' as const}; this.store(input.actorSuperAdminId,'focus_plan_gift',input.idempotencyKey,requestHash,res); return res; }); }
  async retractFocusPlanGiftAtomically(input:SuperAdminRetractGiftRequest){ return this.serial(()=>{ const requestHash=retractReq(input); const replay=this.replay(input.actorSuperAdminId,'focus_plan_gift_retract',input.idempotencyKey,requestHash); if(replay) return replay; const g=this.gifts.get(input.giftRecordId); const nowMs=new Date(input.requestedAt).getTime(); if(!g||g.targetUserId!==input.targetUserId){const res=blocked('gift_not_found','memory_fallback'); this.store(input.actorSuperAdminId,'focus_plan_gift_retract',input.idempotencyKey,requestHash,res); return res;} if(g.status!=='active'||nowMs>=new Date(g.endsAt).getTime()){const res=blocked('gift_not_active','memory_fallback'); this.store(input.actorSuperAdminId,'focus_plan_gift_retract',input.idempotencyKey,requestHash,res); return res;} const next={...g,status:'retracted' as const,updatedAt:input.requestedAt}; this.gifts.set(g.giftRecordId,next); const res={status:'success' as const,failureReason:null,giftRecord:next,resultingEntitlementState:'subscription_required' as const,persistenceStatus:'memory_fallback' as const}; this.store(input.actorSuperAdminId,'focus_plan_gift_retract',input.idempotencyKey,requestHash,res); return res; }); }
  async createUserRestrictionAtomically(input:SuperAdminUserRestrictionRequest){ return this.serial(()=>{ const requestHash=restrictionReq(input); const replay=this.replay(input.actorSuperAdminId,'user_restriction',input.idempotencyKey,requestHash); if(replay) return replay; if([...this.restrictions.values()].some(r=>r.targetUserId===input.targetUserId&&r.status==='active')){const res=blocked('restriction_already_active','memory_fallback','restriction'); this.store(input.actorSuperAdminId,'user_restriction',input.idempotencyKey,requestHash,res); return res;} const restrictionRecord:SuperAdminUserRestrictionRecord={restrictionRecordId:`restriction_${randomUUID()}`,actorSuperAdminId:input.actorSuperAdminId,targetUserId:input.targetUserId,restrictionKind:input.restrictionKind,status:'active',reasonCode:input.reasonCode,operatorNote:input.operatorNote,stepUpStatus:'verified',idempotencyKey:input.idempotencyKey,createdAt:input.requestedAt,updatedAt:input.requestedAt}; this.restrictions.set(restrictionRecord.restrictionRecordId,restrictionRecord); const res={status:'success' as const,failureReason:null,restrictionRecord,resultingEntitlementState:'restricted' as const,persistenceStatus:'memory_fallback' as const}; this.store(input.actorSuperAdminId,'user_restriction',input.idempotencyKey,requestHash,res); return res; }); }
  async getControlSnapshot(targetUserId:string, asOfIso=new Date().toISOString()){ const asOf=new Date(asOfIso).getTime(); const gifts=[...this.gifts.values()].filter(g=>g.targetUserId===targetUserId&&g.status==='active'&&asOf<new Date(g.endsAt).getTime()).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)||b.giftRecordId.localeCompare(a.giftRecordId)); const restrictions=[...this.restrictions.values()].filter(r=>r.targetUserId===targetUserId&&r.status==='active').sort((a,b)=>b.createdAt.localeCompare(a.createdAt)||b.restrictionRecordId.localeCompare(a.restrictionRecordId)); return {generatedAt:asOfIso,targetUserId,activeGiftCount:gifts.length,activeRestrictionCount:restrictions.length,activeGift:gifts[0]??null,activeRestriction:restrictions[0]??null,persistenceStatus:'memory_fallback' as const,stepUpReadinessState:'provider_pending' as const}; }
  async getOperationByIdempotency(actorUserId:string, actionKind:SuperAdminCommercialActionKind, idempotencyKey:string){ return this.ops.get(this.opKey(actorUserId,actionKind,idempotencyKey))?.response ?? null; }
  async getPersistenceReadiness(){ return {selectedRepositoryMode:'memory' as const,databaseConfigured:false,requiredRelationsAvailable:true,persistenceStatus:'memory_fallback' as const}; }
  clear(){this.gifts.clear();this.restrictions.clear();this.ops.clear();}
}

function fromGift(r:any):SuperAdminFocusPlanGiftRecord{return {giftRecordId:r.gift_id,actorSuperAdminId:r.actor_user_id,targetUserId:r.target_user_id,planCode:'focus_plan',duration:r.duration,status:r.status,startsAt:new Date(r.starts_at).toISOString(),endsAt:new Date(r.ends_at).toISOString(),reasonCode:r.reason_code??'commercial_support',operatorNote:r.operator_note??'',stepUpStatus:'verified',idempotencyKey:r.idempotency_key??null,createdAt:new Date(r.created_at).toISOString(),updatedAt:new Date(r.updated_at).toISOString()};}
function fromRestriction(r:any):SuperAdminUserRestrictionRecord{return {restrictionRecordId:r.restriction_id,actorSuperAdminId:r.actor_user_id,targetUserId:r.target_user_id,restrictionKind:r.restriction_kind,status:r.status,reasonCode:r.reason,operatorNote:r.operator_note??'',stepUpStatus:'verified',idempotencyKey:r.idempotency_key??null,createdAt:new Date(r.created_at).toISOString(),updatedAt:new Date(r.updated_at).toISOString()};}
export class SQLSuperAdminCommercialRepository implements SuperAdminCommercialRepository {
  private fail(_error: unknown): never { throw new CommercialPersistenceError(); }
  async getOperationByIdempotency(actorUserId:string, actionKind:SuperAdminCommercialActionKind, idempotencyKey:string){ try{ const row=(await queryDb<any>('SELECT response_json FROM super_admin_commercial_operations WHERE actor_user_id=$1 AND action_kind=$2 AND idempotency_key=$3 AND operation_status IN (\'completed\',\'business_denied\') LIMIT 1',[actorUserId,actionKind,idempotencyKey]))[0]; return row?.response_json ?? null;}catch(e){this.fail(e);} }
  private async claim(tx:DbTransactionClient,input:{actor:string;target:string;action:SuperAdminCommercialActionKind;key:string|null;requestHash:string;challenge:string;now:string;state:string}){ if(!input.key) return null; await tx.query('INSERT INTO super_admin_commercial_operations(operation_id,action_kind,actor_user_id,target_user_id,step_up_challenge_id,idempotency_key,request_hash,operation_status,resulting_entitlement_state,response_json,created_at,version) VALUES($1,$2,$3,$4,$5,$6,$7,\'pending\',$8,\'{}\',$9,0) ON CONFLICT DO NOTHING',[`op_${randomUUID()}`,input.action,input.actor,input.target,input.challenge,input.key,input.requestHash,input.state,input.now]); const row=(await tx.query('SELECT * FROM super_admin_commercial_operations WHERE actor_user_id=$1 AND action_kind=$2 AND idempotency_key=$3 FOR UPDATE',[input.actor,input.action,input.key])).rows[0] as any; if(row.request_hash!==input.requestHash) return blocked('idempotency_conflict','durable'); if((row.operation_status==='completed'||row.operation_status==='business_denied')) return row.response_json as AnyResult; return null; }
  private async complete(tx:DbTransactionClient,input:{actor:string;action:SuperAdminCommercialActionKind;key:string|null;response:AnyResult;requestHash:string;now:string;giftId?:string|null;restrictionId?:string|null}){ if(!input.key) { await tx.query('INSERT INTO super_admin_commercial_operations(operation_id,action_kind,actor_user_id,target_user_id,step_up_challenge_id,idempotency_key,request_hash,operation_status,failure_reason,gift_id,restriction_id,resulting_entitlement_state,response_json,created_at,completed_at,version) VALUES($1,$2,$3,$4,$5,NULL,$6,$7,$8,$9,$10,$11,$12,$13,$13,0)',[`op_${randomUUID()}`,input.action,input.actor,(input.response as any).giftRecord?.targetUserId ?? (input.response as any).restrictionRecord?.targetUserId ?? '', '',input.requestHash,input.response.status==='success'?'completed':'business_denied',input.response.failureReason,input.giftId??null,input.restrictionId??null,input.response.resultingEntitlementState,JSON.stringify(input.response),input.now]); return; } await tx.query('UPDATE super_admin_commercial_operations SET operation_status=$1,failure_reason=$2,gift_id=$3,restriction_id=$4,resulting_entitlement_state=$5,response_json=$6,completed_at=$7,version=version+1 WHERE actor_user_id=$8 AND action_kind=$9 AND idempotency_key=$10',[input.response.status==='success'?'completed':'business_denied',input.response.failureReason,input.giftId??null,input.restrictionId??null,input.response.resultingEntitlementState,JSON.stringify(input.response),input.now,input.actor,input.action,input.key]); }
  async createFocusPlanGiftAtomically(input:SuperAdminFocusPlanGiftRequest){ try{return await withDbTransaction(async tx=>{const requestHash=giftReq(input); const replay=await this.claim(tx,{actor:input.actorSuperAdminId,target:input.targetUserId,action:'focus_plan_gift',key:input.idempotencyKey,requestHash,challenge:input.stepUpChallengeId,now:input.requestedAt,state:'subscription_required'}); if(replay) return replay; await tx.query('INSERT INTO super_admin_commercial_target_state(target_user_id,updated_at,version) VALUES($1,$2,0) ON CONFLICT DO NOTHING',[input.targetUserId,input.requestedAt]); await tx.query('SELECT target_user_id FROM super_admin_commercial_target_state WHERE target_user_id=$1 FOR UPDATE',[input.targetUserId]); await tx.query('UPDATE super_admin_focus_plan_gifts SET status=\'expired\', updated_at=$2, version=version+1 WHERE target_user_id=$1 AND status=\'active\' AND ends_at <= $2',[input.targetUserId,input.requestedAt]); const active=(await tx.query('SELECT * FROM super_admin_focus_plan_gifts WHERE target_user_id=$1 AND status=\'active\' AND ends_at > $2 ORDER BY created_at DESC, gift_id DESC LIMIT 1',[input.targetUserId,input.requestedAt])).rows[0]; if(active){const res=blocked('gift_already_active','durable'); await this.complete(tx,{actor:input.actorSuperAdminId,action:'focus_plan_gift',key:input.idempotencyKey,response:res,requestHash,now:input.requestedAt}); return res;} const giftId=`gift_${randomUUID()}`; const ends=buildGiftEnd(input.requestedAt,input.duration); await tx.query('INSERT INTO super_admin_focus_plan_gifts(gift_id,target_user_id,actor_user_id,status,duration,starts_at,ends_at,operator_note,created_at,updated_at,plan_code,reason_code,step_up_challenge_id,idempotency_key,version) VALUES($1,$2,$3,\'active\',$4,$5,$6,$7,$5,$5,\'focus_plan\',$8,$9,$10,0)',[giftId,input.targetUserId,input.actorSuperAdminId,input.duration,input.requestedAt,ends,input.operatorNote,input.reasonCode,input.stepUpChallengeId,input.idempotencyKey]); const giftRecord={giftRecordId:giftId,actorSuperAdminId:input.actorSuperAdminId,targetUserId:input.targetUserId,planCode:'focus_plan' as const,duration:input.duration,status:'active' as const,startsAt:input.requestedAt,endsAt:ends,reasonCode:input.reasonCode,operatorNote:input.operatorNote,stepUpStatus:'verified' as const,idempotencyKey:input.idempotencyKey,createdAt:input.requestedAt,updatedAt:input.requestedAt}; const res={status:'success' as const,failureReason:null,giftRecord,resultingEntitlementState:'focus_plan_active' as const,persistenceStatus:'durable' as const}; await this.complete(tx,{actor:input.actorSuperAdminId,action:'focus_plan_gift',key:input.idempotencyKey,response:res,requestHash,now:input.requestedAt,giftId}); return res;});}catch(e){this.fail(e);} }
  async retractFocusPlanGiftAtomically(input:SuperAdminRetractGiftRequest){ try{return await withDbTransaction(async tx=>{const requestHash=retractReq(input); const replay=await this.claim(tx,{actor:input.actorSuperAdminId,target:input.targetUserId,action:'focus_plan_gift_retract',key:input.idempotencyKey,requestHash,challenge:input.stepUpChallengeId,now:input.requestedAt,state:'subscription_required'}); if(replay) return replay; await tx.query('INSERT INTO super_admin_commercial_target_state(target_user_id,updated_at,version) VALUES($1,$2,0) ON CONFLICT DO NOTHING',[input.targetUserId,input.requestedAt]); await tx.query('SELECT target_user_id FROM super_admin_commercial_target_state WHERE target_user_id=$1 FOR UPDATE',[input.targetUserId]); const row=(await tx.query('SELECT * FROM super_admin_focus_plan_gifts WHERE gift_id=$1 AND target_user_id=$2 FOR UPDATE',[input.giftRecordId,input.targetUserId])).rows[0] as any; if(!row){const res=blocked('gift_not_found','durable'); await this.complete(tx,{actor:input.actorSuperAdminId,action:'focus_plan_gift_retract',key:input.idempotencyKey,response:res,requestHash,now:input.requestedAt}); return res;} if(row.status!=='active'||new Date(input.requestedAt).getTime()>=new Date(row.ends_at).getTime()){const res=blocked('gift_not_active','durable'); await this.complete(tx,{actor:input.actorSuperAdminId,action:'focus_plan_gift_retract',key:input.idempotencyKey,response:res,requestHash,now:input.requestedAt,giftId:input.giftRecordId}); return res;} await tx.query('UPDATE super_admin_focus_plan_gifts SET status=\'retracted\',retracted_at=$1,retracted_by=$2,retraction_reason_code=$3,retraction_operator_note=$4,retraction_step_up_challenge_id=$5,retraction_idempotency_key=$6,updated_at=$1,version=version+1 WHERE gift_id=$7',[input.requestedAt,input.actorSuperAdminId,input.reasonCode,input.operatorNote,input.stepUpChallengeId,input.idempotencyKey,input.giftRecordId]); const giftRecord={...fromGift(row),status:'retracted' as const,updatedAt:input.requestedAt}; const res={status:'success' as const,failureReason:null,giftRecord,resultingEntitlementState:'subscription_required' as const,persistenceStatus:'durable' as const}; await this.complete(tx,{actor:input.actorSuperAdminId,action:'focus_plan_gift_retract',key:input.idempotencyKey,response:res,requestHash,now:input.requestedAt,giftId:input.giftRecordId}); return res;});}catch(e){this.fail(e);} }
  async createUserRestrictionAtomically(input:SuperAdminUserRestrictionRequest){ try{return await withDbTransaction(async tx=>{const requestHash=restrictionReq(input); const replay=await this.claim(tx,{actor:input.actorSuperAdminId,target:input.targetUserId,action:'user_restriction',key:input.idempotencyKey,requestHash,challenge:input.stepUpChallengeId,now:input.requestedAt,state:'restricted'}); if(replay) return replay; await tx.query('INSERT INTO super_admin_commercial_target_state(target_user_id,updated_at,version) VALUES($1,$2,0) ON CONFLICT DO NOTHING',[input.targetUserId,input.requestedAt]); await tx.query('SELECT target_user_id FROM super_admin_commercial_target_state WHERE target_user_id=$1 FOR UPDATE',[input.targetUserId]); const active=(await tx.query('SELECT * FROM super_admin_user_restrictions WHERE target_user_id=$1 AND status=\'active\' ORDER BY created_at DESC, restriction_id DESC LIMIT 1',[input.targetUserId])).rows[0]; if(active){const res=blocked('restriction_already_active','durable','restriction'); await this.complete(tx,{actor:input.actorSuperAdminId,action:'user_restriction',key:input.idempotencyKey,response:res,requestHash,now:input.requestedAt}); return res;} const restrictionId=`restriction_${randomUUID()}`; await tx.query('INSERT INTO super_admin_user_restrictions(restriction_id,target_user_id,actor_user_id,restriction_kind,status,reason,operator_note,created_at,updated_at,step_up_challenge_id,idempotency_key,version) VALUES($1,$2,$3,$4,\'active\',$5,$6,$7,$7,$8,$9,0)',[restrictionId,input.targetUserId,input.actorSuperAdminId,input.restrictionKind,input.reasonCode,input.operatorNote,input.requestedAt,input.stepUpChallengeId,input.idempotencyKey]); const restrictionRecord={restrictionRecordId:restrictionId,actorSuperAdminId:input.actorSuperAdminId,targetUserId:input.targetUserId,restrictionKind:input.restrictionKind,status:'active' as const,reasonCode:input.reasonCode,operatorNote:input.operatorNote,stepUpStatus:'verified' as const,idempotencyKey:input.idempotencyKey,createdAt:input.requestedAt,updatedAt:input.requestedAt}; const res={status:'success' as const,failureReason:null,restrictionRecord,resultingEntitlementState:'restricted' as const,persistenceStatus:'durable' as const}; await this.complete(tx,{actor:input.actorSuperAdminId,action:'user_restriction',key:input.idempotencyKey,response:res,requestHash,now:input.requestedAt,restrictionId}); return res;});}catch(e){this.fail(e);} }
  async getControlSnapshot(targetUserId:string, asOfIso=new Date().toISOString()){ try{ const row=(await queryDb<any>(`WITH active_gifts AS (SELECT * FROM super_admin_focus_plan_gifts WHERE target_user_id=$1 AND status='active' AND ends_at > $2), active_restrictions AS (SELECT * FROM super_admin_user_restrictions WHERE target_user_id=$1 AND status='active') SELECT (SELECT count(*)::int FROM active_gifts) AS gift_count, (SELECT count(*)::int FROM active_restrictions) AS restriction_count, (SELECT row_to_json(g) FROM (SELECT * FROM active_gifts ORDER BY created_at DESC, gift_id DESC LIMIT 1) g) AS gift, (SELECT row_to_json(r) FROM (SELECT * FROM active_restrictions ORDER BY created_at DESC, restriction_id DESC LIMIT 1) r) AS restriction`,[targetUserId,asOfIso]))[0]; return {generatedAt:asOfIso,targetUserId,activeGiftCount:row?.gift_count??0,activeRestrictionCount:row?.restriction_count??0,activeGift:row?.gift?fromGift(row.gift):null,activeRestriction:row?.restriction?fromRestriction(row.restriction):null,persistenceStatus:'durable' as const,stepUpReadinessState:'provider_pending' as const};}catch(e){this.fail(e);} }
  async getPersistenceReadiness(){ try{ await queryDb('SELECT 1 FROM super_admin_commercial_operations LIMIT 1'); return {selectedRepositoryMode:'sql' as const,databaseConfigured:true,requiredRelationsAvailable:true,persistenceStatus:'durable' as const}; }catch{return {selectedRepositoryMode:'sql' as const,databaseConfigured:Boolean(runtimeEnv().DATABASE_URL),requiredRelationsAvailable:false,persistenceStatus:'unavailable' as const};} }
}
let defaultRepo:SuperAdminCommercialRepository|null=null;
export function buildDefaultSuperAdminCommercialRepository(){const env=runtimeEnv(); if(env.NODE_ENV==='production'&&(env.APP_STATE_REPOSITORY!=='sql'||!env.DATABASE_URL)) throw new CommercialPersistenceError(); if(env.APP_STATE_REPOSITORY==='sql'){ if(!env.DATABASE_URL) throw new CommercialPersistenceError(); return new SQLSuperAdminCommercialRepository(); } if(env.NODE_ENV==='production') throw new CommercialPersistenceError(); return new MemorySuperAdminCommercialRepository();}
export const getDefaultSuperAdminCommercialRepository=()=> defaultRepo ??= buildDefaultSuperAdminCommercialRepository();
export const resetSuperAdminCommercialRepositoryForTests=()=>{defaultRepo=null;};
export { entitlement as evaluateCommercialEntitlementFromControls };
