import { createHash, randomUUID } from 'node:crypto';
import type { SuperAdminCommercialActionKind, SuperAdminCommercialControlSnapshot, SuperAdminFocusPlanGiftRecord, SuperAdminFocusPlanGiftRequest, SuperAdminFocusPlanGiftResult, SuperAdminRetractGiftRequest, SuperAdminRetractGiftResult, SuperAdminUserRestrictionRecord, SuperAdminUserRestrictionRequest, SuperAdminUserRestrictionResult } from '@elceo/types';
import { queryDb, withDbTransaction, type DbTransactionClient } from '../db/client';
import { CommercialPersistenceError, type CommercialPersistenceStatus } from './commercial-persistence-error';

const days = (d: number) => d * 24 * 60 * 60 * 1000;
const buildGiftEnd = (start: string, d: 'two_weeks' | 'one_month') => new Date(new Date(start).getTime() + (d === 'two_weeks' ? days(14) : days(30))).toISOString();
const runtimeEnv = () => (globalThis as { process?: { env?: Record<string, string | undefined> } }).process?.env ?? {};
const hash = (v: unknown) => createHash('sha256').update(JSON.stringify(v)).digest('hex');

type Readiness = { selectedRepositoryMode: 'sql' | 'memory' | 'unavailable'; databaseConfigured: boolean; requiredRelationsAvailable: boolean; persistenceStatus: CommercialPersistenceStatus };
type GiftCreateOutcome = SuperAdminFocusPlanGiftResult & { persistenceStatus: CommercialPersistenceStatus };
type GiftRetractOutcome = SuperAdminRetractGiftResult & { persistenceStatus: CommercialPersistenceStatus };
type RestrictionOutcome = SuperAdminUserRestrictionResult & { persistenceStatus: CommercialPersistenceStatus };
type OutcomeByAction = { focus_plan_gift: GiftCreateOutcome; focus_plan_gift_retract: GiftRetractOutcome; user_restriction: RestrictionOutcome };

type OperationContext<A extends SuperAdminCommercialActionKind> = {
  actor: string;
  target: string;
  action: A;
  stepUpChallengeId: string;
  idempotencyKey: string | null;
  requestHash: string;
  reasonCode: string;
  operatorNote: string;
  requestedResourceId: string | null;
  nowIso: string;
};

type StoredOperation<A extends SuperAdminCommercialActionKind> = { operationId: string; requestHash: string; response: OutcomeByAction[A] };

type EventRecord = {
  operationId: string | null;
  actor: string;
  target: string;
  action: SuperAdminCommercialActionKind;
  idempotencyKey: string | null;
  requestHash: string;
  stepUpChallengeId: string;
  eventKind: string;
  outcome: string;
  failureReason: string | null;
  reasonCode: string;
  operatorNote: string;
  requestedResourceId: string | null;
  resultingResourceId: string | null;
  occurredAt: string;
};

export interface SuperAdminCommercialRepository {
  createFocusPlanGiftAtomically(input: SuperAdminFocusPlanGiftRequest): Promise<GiftCreateOutcome>;
  retractFocusPlanGiftAtomically(input: SuperAdminRetractGiftRequest): Promise<GiftRetractOutcome>;
  createUserRestrictionAtomically(input: SuperAdminUserRestrictionRequest): Promise<RestrictionOutcome>;
  getControlSnapshot(targetUserId: string, asOfIso?: string): Promise<SuperAdminCommercialControlSnapshot>;
  getOperationByIdempotency(actorUserId: string, actionKind: SuperAdminCommercialActionKind, idempotencyKey: string): Promise<GiftCreateOutcome | GiftRetractOutcome | RestrictionOutcome | null>;
  getPersistenceReadiness(): Promise<Readiness>;
  clear?(): void;
}

export function buildGiftRequestHash(i: SuperAdminFocusPlanGiftRequest): string { return hash({ actor: i.actorSuperAdminId, action: 'focus_plan_gift', target: i.targetUserId, duration: i.duration, reasonCode: i.reasonCode, operatorNote: i.operatorNote }); }
export function buildRetractRequestHash(i: SuperAdminRetractGiftRequest): string { return hash({ actor: i.actorSuperAdminId, action: 'focus_plan_gift_retract', target: i.targetUserId, giftRecordId: i.giftRecordId, reasonCode: i.reasonCode, operatorNote: i.operatorNote }); }
export function buildRestrictionRequestHash(i: SuperAdminUserRestrictionRequest): string { return hash({ actor: i.actorSuperAdminId, action: 'user_restriction', target: i.targetUserId, restrictionKind: i.restrictionKind, reasonCode: i.reasonCode, operatorNote: i.operatorNote }); }
export function evaluateCommercialEntitlementFromControls(gift: SuperAdminFocusPlanGiftRecord | null, restricted: boolean, subscriptionActive = false, nowIso = new Date().toISOString()) { if (restricted) return 'restricted'; if (subscriptionActive) return 'focus_plan_active'; return gift && gift.status === 'active' && new Date(nowIso).getTime() < new Date(gift.endsAt).getTime() ? 'focus_plan_active' : 'subscription_required'; }

const giftBlocked = (failureReason: NonNullable<SuperAdminFocusPlanGiftResult['failureReason']>, persistenceStatus: CommercialPersistenceStatus): GiftCreateOutcome => ({ status: 'blocked', failureReason, giftRecord: null, resultingEntitlementState: 'subscription_required', persistenceStatus });
const retractBlocked = (failureReason: NonNullable<SuperAdminRetractGiftResult['failureReason']>, persistenceStatus: CommercialPersistenceStatus): GiftRetractOutcome => ({ status: 'blocked', failureReason, giftRecord: null, resultingEntitlementState: 'subscription_required', persistenceStatus });
const restrictionBlocked = (failureReason: NonNullable<SuperAdminUserRestrictionResult['failureReason']>, persistenceStatus: CommercialPersistenceStatus): RestrictionOutcome => ({ status: 'blocked', failureReason, restrictionRecord: null, resultingEntitlementState: 'restricted', persistenceStatus });

function cloneMap<T>(m: Map<string, T>): Map<string, T> { return new Map([...m.entries()].map(([k, v]) => [k, structuredClone(v)])); }
function resourceIdFor(response: GiftCreateOutcome | GiftRetractOutcome | RestrictionOutcome): string | null { if ('giftRecord' in response) return response.giftRecord?.giftRecordId ?? null; return response.restrictionRecord?.restrictionRecordId ?? null; }

export class MemorySuperAdminCommercialRepository implements SuperAdminCommercialRepository {
  private gifts = new Map<string, SuperAdminFocusPlanGiftRecord>();
  private restrictions = new Map<string, SuperAdminUserRestrictionRecord>();
  private operations = new Map<string, StoredOperation<SuperAdminCommercialActionKind>>();
  private events: EventRecord[] = [];
  private targetState = new Map<string, { updatedAt: string; version: number }>();
  private chain = Promise.resolve();
  private failAfterResourceMutation = false;

  injectFailureAfterResourceMutationForTests() { this.failAfterResourceMutation = true; }
  getAuditEventsForTests() { return this.events.map((event) => ({ ...event })); }
  getTargetStateForTests(target: string) { return this.targetState.get(target) ?? null; }

  private async serial<T>(fn: () => Promise<T> | T): Promise<T> { const run = this.chain.then(fn, fn); this.chain = run.then(() => undefined, () => undefined); return run; }
  private opKey(actor: string, action: SuperAdminCommercialActionKind, key: string) { return `${actor}\0${action}\0${key}`; }
  private saveEvent(event: EventRecord) { this.events.push(event); }
  private updateTarget(target: string, nowIso: string) { const current = this.targetState.get(target); this.targetState.set(target, { updatedAt: nowIso, version: (current?.version ?? 0) + 1 }); }
  private rollback(gifts: Map<string, SuperAdminFocusPlanGiftRecord>, restrictions: Map<string, SuperAdminUserRestrictionRecord>, operations: Map<string, StoredOperation<SuperAdminCommercialActionKind>>, events: EventRecord[], targetState: Map<string, { updatedAt: string; version: number }>) { this.gifts = gifts; this.restrictions = restrictions; this.operations = operations; this.events = events; this.targetState = targetState; this.failAfterResourceMutation = false; }
  private complete<A extends SuperAdminCommercialActionKind>(ctx: OperationContext<A>, response: OutcomeByAction[A]) {
    const operationId = `op_${randomUUID()}`;
    if (ctx.idempotencyKey) this.operations.set(this.opKey(ctx.actor, ctx.action, ctx.idempotencyKey), { operationId, requestHash: ctx.requestHash, response } as StoredOperation<SuperAdminCommercialActionKind>);
    this.saveEvent({ operationId, actor: ctx.actor, target: ctx.target, action: ctx.action, idempotencyKey: ctx.idempotencyKey, requestHash: ctx.requestHash, stepUpChallengeId: ctx.stepUpChallengeId, eventKind: response.status === 'success' ? 'operation_completed' : 'operation_business_denied', outcome: response.status, failureReason: response.failureReason, reasonCode: ctx.reasonCode, operatorNote: ctx.operatorNote, requestedResourceId: ctx.requestedResourceId, resultingResourceId: resourceIdFor(response), occurredAt: ctx.nowIso });
    this.updateTarget(ctx.target, ctx.nowIso);
  }
  private replay<A extends SuperAdminCommercialActionKind>(ctx: OperationContext<A>, conflict: () => OutcomeByAction[A]): OutcomeByAction[A] | null {
    if (!ctx.idempotencyKey) return null;
    const stored = this.operations.get(this.opKey(ctx.actor, ctx.action, ctx.idempotencyKey));
    if (!stored) return null;
    if (stored.requestHash !== ctx.requestHash) {
      const response = conflict();
      this.saveEvent({ operationId: stored.operationId, actor: ctx.actor, target: ctx.target, action: ctx.action, idempotencyKey: ctx.idempotencyKey, requestHash: ctx.requestHash, stepUpChallengeId: ctx.stepUpChallengeId, eventKind: 'idempotency_conflict', outcome: 'blocked', failureReason: 'idempotency_conflict', reasonCode: ctx.reasonCode, operatorNote: ctx.operatorNote, requestedResourceId: ctx.requestedResourceId, resultingResourceId: null, occurredAt: ctx.nowIso });
      return response;
    }
    return stored.response as OutcomeByAction[A];
  }

  async createFocusPlanGiftAtomically(input: SuperAdminFocusPlanGiftRequest): Promise<GiftCreateOutcome> { return this.serial(() => { const ctx: OperationContext<'focus_plan_gift'> = { actor: input.actorSuperAdminId, target: input.targetUserId, action: 'focus_plan_gift', stepUpChallengeId: input.stepUpChallengeId, idempotencyKey: input.idempotencyKey, requestHash: buildGiftRequestHash(input), reasonCode: input.reasonCode, operatorNote: input.operatorNote, requestedResourceId: null, nowIso: input.requestedAt }; const replay = this.replay(ctx, () => giftBlocked('idempotency_conflict', 'memory_fallback')); if (replay) return replay; const gifts0 = cloneMap(this.gifts); const restrictions0 = cloneMap(this.restrictions); const ops0 = cloneMap(this.operations); const events0 = this.events.map((event) => ({ ...event })); const target0 = cloneMap(this.targetState); try { for (const gift of this.gifts.values()) if (gift.targetUserId === input.targetUserId && gift.status === 'active' && Date.parse(input.requestedAt) >= Date.parse(gift.endsAt)) this.gifts.set(gift.giftRecordId, { ...gift, status: 'expired', updatedAt: input.requestedAt }); const active = [...this.gifts.values()].find((gift) => gift.targetUserId === input.targetUserId && gift.status === 'active' && Date.parse(input.requestedAt) < Date.parse(gift.endsAt)); if (active) { const response = giftBlocked('gift_already_active', 'memory_fallback'); this.complete(ctx, response); return response; } const giftRecord: SuperAdminFocusPlanGiftRecord = { giftRecordId: `gift_${randomUUID()}`, actorSuperAdminId: input.actorSuperAdminId, targetUserId: input.targetUserId, planCode: 'focus_plan', duration: input.duration, status: 'active', startsAt: input.requestedAt, endsAt: buildGiftEnd(input.requestedAt, input.duration), reasonCode: input.reasonCode, operatorNote: input.operatorNote, stepUpStatus: 'verified', idempotencyKey: input.idempotencyKey, createdAt: input.requestedAt, updatedAt: input.requestedAt }; this.gifts.set(giftRecord.giftRecordId, giftRecord); if (this.failAfterResourceMutation) throw new CommercialPersistenceError('Injected commercial operation/audit failure'); const response: GiftCreateOutcome = { status: 'success', failureReason: null, giftRecord, resultingEntitlementState: 'focus_plan_active', persistenceStatus: 'memory_fallback' }; this.complete(ctx, response); return response; } catch (error) { this.rollback(gifts0, restrictions0, ops0, events0, target0); throw error; } }); }
  async retractFocusPlanGiftAtomically(input: SuperAdminRetractGiftRequest): Promise<GiftRetractOutcome> { return this.serial(() => { const ctx: OperationContext<'focus_plan_gift_retract'> = { actor: input.actorSuperAdminId, target: input.targetUserId, action: 'focus_plan_gift_retract', stepUpChallengeId: input.stepUpChallengeId, idempotencyKey: input.idempotencyKey, requestHash: buildRetractRequestHash(input), reasonCode: input.reasonCode, operatorNote: input.operatorNote, requestedResourceId: input.giftRecordId, nowIso: input.requestedAt }; const replay = this.replay(ctx, () => retractBlocked('idempotency_conflict', 'memory_fallback')); if (replay) return replay; const gifts0 = cloneMap(this.gifts); const restrictions0 = cloneMap(this.restrictions); const ops0 = cloneMap(this.operations); const events0 = this.events.map((event) => ({ ...event })); const target0 = cloneMap(this.targetState); try { const gift = this.gifts.get(input.giftRecordId); if (!gift || gift.targetUserId !== input.targetUserId) { const response = retractBlocked('gift_not_found', 'memory_fallback'); this.complete(ctx, response); return response; } if (gift.status !== 'active' || Date.parse(input.requestedAt) >= Date.parse(gift.endsAt)) { const response = retractBlocked('gift_not_active', 'memory_fallback'); this.complete(ctx, response); return response; } const giftRecord = { ...gift, status: 'retracted' as const, updatedAt: input.requestedAt }; this.gifts.set(gift.giftRecordId, giftRecord); if (this.failAfterResourceMutation) throw new CommercialPersistenceError('Injected commercial operation/audit failure'); const response: GiftRetractOutcome = { status: 'success', failureReason: null, giftRecord, resultingEntitlementState: 'subscription_required', persistenceStatus: 'memory_fallback' }; this.complete(ctx, response); return response; } catch (error) { this.rollback(gifts0, restrictions0, ops0, events0, target0); throw error; } }); }
  async createUserRestrictionAtomically(input: SuperAdminUserRestrictionRequest): Promise<RestrictionOutcome> { return this.serial(() => { const ctx: OperationContext<'user_restriction'> = { actor: input.actorSuperAdminId, target: input.targetUserId, action: 'user_restriction', stepUpChallengeId: input.stepUpChallengeId, idempotencyKey: input.idempotencyKey, requestHash: buildRestrictionRequestHash(input), reasonCode: input.reasonCode, operatorNote: input.operatorNote, requestedResourceId: null, nowIso: input.requestedAt }; const replay = this.replay(ctx, () => restrictionBlocked('idempotency_conflict', 'memory_fallback')); if (replay) return replay; const gifts0 = cloneMap(this.gifts); const restrictions0 = cloneMap(this.restrictions); const ops0 = cloneMap(this.operations); const events0 = this.events.map((event) => ({ ...event })); const target0 = cloneMap(this.targetState); try { if ([...this.restrictions.values()].some((restriction) => restriction.targetUserId === input.targetUserId && restriction.status === 'active')) { const response = restrictionBlocked('restriction_already_active', 'memory_fallback'); this.complete(ctx, response); return response; } const restrictionRecord: SuperAdminUserRestrictionRecord = { restrictionRecordId: `restriction_${randomUUID()}`, actorSuperAdminId: input.actorSuperAdminId, targetUserId: input.targetUserId, restrictionKind: input.restrictionKind, status: 'active', reasonCode: input.reasonCode, operatorNote: input.operatorNote, stepUpStatus: 'verified', idempotencyKey: input.idempotencyKey, createdAt: input.requestedAt, updatedAt: input.requestedAt }; this.restrictions.set(restrictionRecord.restrictionRecordId, restrictionRecord); if (this.failAfterResourceMutation) throw new CommercialPersistenceError('Injected commercial operation/audit failure'); const response: RestrictionOutcome = { status: 'success', failureReason: null, restrictionRecord, resultingEntitlementState: 'restricted', persistenceStatus: 'memory_fallback' }; this.complete(ctx, response); return response; } catch (error) { this.rollback(gifts0, restrictions0, ops0, events0, target0); throw error; } }); }
  async getControlSnapshot(targetUserId: string, asOfIso = new Date().toISOString()): Promise<SuperAdminCommercialControlSnapshot> { const activeGifts = [...this.gifts.values()].filter((gift) => gift.targetUserId === targetUserId && gift.status === 'active' && Date.parse(asOfIso) < Date.parse(gift.endsAt)).sort((a, b) => b.createdAt.localeCompare(a.createdAt) || b.giftRecordId.localeCompare(a.giftRecordId)); const activeRestrictions = [...this.restrictions.values()].filter((restriction) => restriction.targetUserId === targetUserId && restriction.status === 'active').sort((a, b) => b.createdAt.localeCompare(a.createdAt) || b.restrictionRecordId.localeCompare(a.restrictionRecordId)); return { generatedAt: asOfIso, targetUserId, activeGiftCount: activeGifts.length, activeRestrictionCount: activeRestrictions.length, activeGift: activeGifts[0] ?? null, activeRestriction: activeRestrictions[0] ?? null, persistenceStatus: 'memory_fallback', stepUpReadinessState: 'provider_pending' }; }
  async getOperationByIdempotency(actorUserId: string, actionKind: SuperAdminCommercialActionKind, idempotencyKey: string) { return this.operations.get(this.opKey(actorUserId, actionKind, idempotencyKey))?.response ?? null; }
  async getPersistenceReadiness(): Promise<Readiness> { return { selectedRepositoryMode: 'memory', databaseConfigured: false, requiredRelationsAvailable: true, persistenceStatus: 'memory_fallback' }; }
  clear() { this.gifts.clear(); this.restrictions.clear(); this.operations.clear(); this.events = []; this.targetState.clear(); this.failAfterResourceMutation = false; }
}

function fromGift(row: any): SuperAdminFocusPlanGiftRecord { return { giftRecordId: row.gift_id, actorSuperAdminId: row.actor_user_id, targetUserId: row.target_user_id, planCode: 'focus_plan', duration: row.duration, status: row.status, startsAt: new Date(row.starts_at).toISOString(), endsAt: new Date(row.ends_at).toISOString(), reasonCode: row.reason_code ?? 'commercial_support', operatorNote: row.operator_note ?? '', stepUpStatus: 'verified', idempotencyKey: row.idempotency_key ?? null, createdAt: new Date(row.created_at).toISOString(), updatedAt: new Date(row.updated_at).toISOString() }; }
function fromRestriction(row: any): SuperAdminUserRestrictionRecord { return { restrictionRecordId: row.restriction_id, actorSuperAdminId: row.actor_user_id, targetUserId: row.target_user_id, restrictionKind: row.restriction_kind, status: row.status, reasonCode: row.reason, operatorNote: row.operator_note ?? '', stepUpStatus: 'verified', idempotencyKey: row.idempotency_key ?? null, createdAt: new Date(row.created_at).toISOString(), updatedAt: new Date(row.updated_at).toISOString() }; }

export class SQLSuperAdminCommercialRepository implements SuperAdminCommercialRepository {
  private fail(_error: unknown): never { throw new CommercialPersistenceError(); }
  private async event(tx: DbTransactionClient, event: EventRecord) { await tx.query('INSERT INTO super_admin_commercial_operation_events(event_id,operation_id,actor_user_id,target_user_id,action_kind,idempotency_key,request_hash,step_up_challenge_id,event_kind,outcome,failure_reason,reason_code,operator_note,requested_resource_id,resulting_resource_id,occurred_at,redaction_status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,\'safe\')', [`event_${randomUUID()}`, event.operationId, event.actor, event.target, event.action, event.idempotencyKey, event.requestHash, event.stepUpChallengeId, event.eventKind, event.outcome, event.failureReason, event.reasonCode, event.operatorNote, event.requestedResourceId, event.resultingResourceId, event.occurredAt]); }
  private async claim<A extends SuperAdminCommercialActionKind>(tx: DbTransactionClient, ctx: OperationContext<A>, conflict: () => OutcomeByAction[A]): Promise<OutcomeByAction[A] | { operationId: string } | null> { if (!ctx.idempotencyKey) return { operationId: `op_${randomUUID()}` }; await tx.query('INSERT INTO super_admin_commercial_operations(operation_id,action_kind,actor_user_id,target_user_id,step_up_challenge_id,idempotency_key,request_hash,reason_code,operator_note,requested_resource_id,operation_status,resulting_entitlement_state,response_json,created_at,version) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,\'pending\',\'subscription_required\',\'{}\',$11,0) ON CONFLICT DO NOTHING', [`op_${randomUUID()}`, ctx.action, ctx.actor, ctx.target, ctx.stepUpChallengeId, ctx.idempotencyKey, ctx.requestHash, ctx.reasonCode, ctx.operatorNote, ctx.requestedResourceId, ctx.nowIso]); const row = (await tx.query('SELECT * FROM super_admin_commercial_operations WHERE actor_user_id=$1 AND action_kind=$2 AND idempotency_key=$3 FOR UPDATE', [ctx.actor, ctx.action, ctx.idempotencyKey])).rows[0] as any; if (row.request_hash !== ctx.requestHash) { const response = conflict(); await this.event(tx, { operationId: row.operation_id, actor: ctx.actor, target: ctx.target, action: ctx.action, idempotencyKey: ctx.idempotencyKey, requestHash: ctx.requestHash, stepUpChallengeId: ctx.stepUpChallengeId, eventKind: 'idempotency_conflict', outcome: 'blocked', failureReason: 'idempotency_conflict', reasonCode: ctx.reasonCode, operatorNote: ctx.operatorNote, requestedResourceId: ctx.requestedResourceId, resultingResourceId: null, occurredAt: ctx.nowIso }); return response; } if (row.operation_status === 'completed' || row.operation_status === 'business_denied') return row.response_json as OutcomeByAction[A]; return { operationId: row.operation_id }; }
  private async complete<A extends SuperAdminCommercialActionKind>(tx: DbTransactionClient, ctx: OperationContext<A>, operationId: string, response: OutcomeByAction[A]) { const status = response.status === 'success' ? 'completed' : 'business_denied'; await tx.query('INSERT INTO super_admin_commercial_operations(operation_id,action_kind,actor_user_id,target_user_id,step_up_challenge_id,idempotency_key,request_hash,reason_code,operator_note,requested_resource_id,operation_status,failure_reason,gift_id,restriction_id,resulting_entitlement_state,response_json,created_at,completed_at,version) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$17,0) ON CONFLICT (operation_id) DO UPDATE SET operation_status=EXCLUDED.operation_status,failure_reason=EXCLUDED.failure_reason,gift_id=EXCLUDED.gift_id,restriction_id=EXCLUDED.restriction_id,resulting_entitlement_state=EXCLUDED.resulting_entitlement_state,response_json=EXCLUDED.response_json,completed_at=EXCLUDED.completed_at,version=super_admin_commercial_operations.version+1', [operationId, ctx.action, ctx.actor, ctx.target, ctx.stepUpChallengeId, ctx.idempotencyKey, ctx.requestHash, ctx.reasonCode, ctx.operatorNote, ctx.requestedResourceId, status, response.failureReason, 'giftRecord' in response ? response.giftRecord?.giftRecordId ?? null : null, 'restrictionRecord' in response ? response.restrictionRecord?.restrictionRecordId ?? null : null, response.resultingEntitlementState, JSON.stringify(response), ctx.nowIso]); await this.event(tx, { operationId, actor: ctx.actor, target: ctx.target, action: ctx.action, idempotencyKey: ctx.idempotencyKey, requestHash: ctx.requestHash, stepUpChallengeId: ctx.stepUpChallengeId, eventKind: status === 'completed' ? 'operation_completed' : 'operation_business_denied', outcome: response.status, failureReason: response.failureReason, reasonCode: ctx.reasonCode, operatorNote: ctx.operatorNote, requestedResourceId: ctx.requestedResourceId, resultingResourceId: resourceIdFor(response), occurredAt: ctx.nowIso }); await tx.query('UPDATE super_admin_commercial_target_state SET updated_at=$2, version=version+1 WHERE target_user_id=$1', [ctx.target, ctx.nowIso]); }
  private async lockTarget(tx: DbTransactionClient, ctx: OperationContext<SuperAdminCommercialActionKind>) { await tx.query('INSERT INTO super_admin_commercial_target_state(target_user_id,updated_at,version) VALUES($1,$2,0) ON CONFLICT DO NOTHING', [ctx.target, ctx.nowIso]); await tx.query('SELECT target_user_id FROM super_admin_commercial_target_state WHERE target_user_id=$1 FOR UPDATE', [ctx.target]); }
  async getOperationByIdempotency(actorUserId: string, actionKind: SuperAdminCommercialActionKind, idempotencyKey: string) { try { const row = (await queryDb<any>('SELECT response_json FROM super_admin_commercial_operations WHERE actor_user_id=$1 AND action_kind=$2 AND idempotency_key=$3 AND operation_status IN (\'completed\',\'business_denied\') LIMIT 1', [actorUserId, actionKind, idempotencyKey]))[0]; return row?.response_json ?? null; } catch (error) { this.fail(error); } }
  async createFocusPlanGiftAtomically(input: SuperAdminFocusPlanGiftRequest): Promise<GiftCreateOutcome> { try { return await withDbTransaction(async (tx) => { const ctx: OperationContext<'focus_plan_gift'> = { actor: input.actorSuperAdminId, target: input.targetUserId, action: 'focus_plan_gift', stepUpChallengeId: input.stepUpChallengeId, idempotencyKey: input.idempotencyKey, requestHash: buildGiftRequestHash(input), reasonCode: input.reasonCode, operatorNote: input.operatorNote, requestedResourceId: null, nowIso: input.requestedAt }; const claim = await this.claim(tx, ctx, () => giftBlocked('idempotency_conflict', 'durable')); if (claim && !('operationId' in claim)) return claim; const operationId = claim && 'operationId' in claim ? claim.operationId : `op_${randomUUID()}`; await this.lockTarget(tx, ctx); await tx.query('UPDATE super_admin_focus_plan_gifts SET status=\'expired\', updated_at=$2, version=version+1 WHERE target_user_id=$1 AND status=\'active\' AND ends_at <= $2', [ctx.target, ctx.nowIso]); const active = (await tx.query('SELECT * FROM super_admin_focus_plan_gifts WHERE target_user_id=$1 AND status=\'active\' AND ends_at > $2 ORDER BY created_at DESC, gift_id DESC LIMIT 1', [ctx.target, ctx.nowIso])).rows[0]; if (active) { const response = giftBlocked('gift_already_active', 'durable'); await this.complete(tx, ctx, operationId, response); return response; } const giftId = `gift_${randomUUID()}`; const endsAt = buildGiftEnd(ctx.nowIso, input.duration); await tx.query('INSERT INTO super_admin_focus_plan_gifts(gift_id,target_user_id,actor_user_id,status,duration,starts_at,ends_at,operator_note,created_at,updated_at,plan_code,reason_code,step_up_challenge_id,idempotency_key,version) VALUES($1,$2,$3,\'active\',$4,$5,$6,$7,$5,$5,\'focus_plan\',$8,$9,$10,0)', [giftId, ctx.target, ctx.actor, input.duration, ctx.nowIso, endsAt, ctx.operatorNote, ctx.reasonCode, ctx.stepUpChallengeId, ctx.idempotencyKey]); const giftRecord: SuperAdminFocusPlanGiftRecord = { giftRecordId: giftId, actorSuperAdminId: ctx.actor, targetUserId: ctx.target, planCode: 'focus_plan', duration: input.duration, status: 'active', startsAt: ctx.nowIso, endsAt, reasonCode: input.reasonCode, operatorNote: input.operatorNote, stepUpStatus: 'verified', idempotencyKey: input.idempotencyKey, createdAt: ctx.nowIso, updatedAt: ctx.nowIso }; const response: GiftCreateOutcome = { status: 'success', failureReason: null, giftRecord, resultingEntitlementState: 'focus_plan_active', persistenceStatus: 'durable' }; await this.complete(tx, ctx, operationId, response); return response; }); } catch (error) { this.fail(error); } }
  async retractFocusPlanGiftAtomically(input: SuperAdminRetractGiftRequest): Promise<GiftRetractOutcome> { try { return await withDbTransaction(async (tx) => { const ctx: OperationContext<'focus_plan_gift_retract'> = { actor: input.actorSuperAdminId, target: input.targetUserId, action: 'focus_plan_gift_retract', stepUpChallengeId: input.stepUpChallengeId, idempotencyKey: input.idempotencyKey, requestHash: buildRetractRequestHash(input), reasonCode: input.reasonCode, operatorNote: input.operatorNote, requestedResourceId: input.giftRecordId, nowIso: input.requestedAt }; const claim = await this.claim(tx, ctx, () => retractBlocked('idempotency_conflict', 'durable')); if (claim && !('operationId' in claim)) return claim; const operationId = claim && 'operationId' in claim ? claim.operationId : `op_${randomUUID()}`; await this.lockTarget(tx, ctx); const row = (await tx.query('SELECT * FROM super_admin_focus_plan_gifts WHERE gift_id=$1 AND target_user_id=$2 FOR UPDATE', [input.giftRecordId, ctx.target])).rows[0] as any; if (!row) { const response = retractBlocked('gift_not_found', 'durable'); await this.complete(tx, ctx, operationId, response); return response; } if (row.status !== 'active' || Date.parse(ctx.nowIso) >= Date.parse(row.ends_at)) { const response = retractBlocked('gift_not_active', 'durable'); await this.complete(tx, ctx, operationId, response); return response; } await tx.query('UPDATE super_admin_focus_plan_gifts SET status=\'retracted\',retracted_at=$1,retracted_by=$2,retraction_reason_code=$3,retraction_operator_note=$4,retraction_step_up_challenge_id=$5,retraction_idempotency_key=$6,updated_at=$1,version=version+1 WHERE gift_id=$7', [ctx.nowIso, ctx.actor, ctx.reasonCode, ctx.operatorNote, ctx.stepUpChallengeId, ctx.idempotencyKey, input.giftRecordId]); const giftRecord = { ...fromGift(row), status: 'retracted' as const, updatedAt: ctx.nowIso }; const response: GiftRetractOutcome = { status: 'success', failureReason: null, giftRecord, resultingEntitlementState: 'subscription_required', persistenceStatus: 'durable' }; await this.complete(tx, ctx, operationId, response); return response; }); } catch (error) { this.fail(error); } }
  async createUserRestrictionAtomically(input: SuperAdminUserRestrictionRequest): Promise<RestrictionOutcome> { try { return await withDbTransaction(async (tx) => { const ctx: OperationContext<'user_restriction'> = { actor: input.actorSuperAdminId, target: input.targetUserId, action: 'user_restriction', stepUpChallengeId: input.stepUpChallengeId, idempotencyKey: input.idempotencyKey, requestHash: buildRestrictionRequestHash(input), reasonCode: input.reasonCode, operatorNote: input.operatorNote, requestedResourceId: null, nowIso: input.requestedAt }; const claim = await this.claim(tx, ctx, () => restrictionBlocked('idempotency_conflict', 'durable')); if (claim && !('operationId' in claim)) return claim; const operationId = claim && 'operationId' in claim ? claim.operationId : `op_${randomUUID()}`; await this.lockTarget(tx, ctx); const active = (await tx.query('SELECT * FROM super_admin_user_restrictions WHERE target_user_id=$1 AND status=\'active\' ORDER BY created_at DESC, restriction_id DESC LIMIT 1', [ctx.target])).rows[0]; if (active) { const response = restrictionBlocked('restriction_already_active', 'durable'); await this.complete(tx, ctx, operationId, response); return response; } const restrictionId = `restriction_${randomUUID()}`; await tx.query('INSERT INTO super_admin_user_restrictions(restriction_id,target_user_id,actor_user_id,restriction_kind,status,reason,operator_note,created_at,updated_at,step_up_challenge_id,idempotency_key,version) VALUES($1,$2,$3,$4,\'active\',$5,$6,$7,$7,$8,$9,0)', [restrictionId, ctx.target, ctx.actor, input.restrictionKind, ctx.reasonCode, ctx.operatorNote, ctx.nowIso, ctx.stepUpChallengeId, ctx.idempotencyKey]); const restrictionRecord: SuperAdminUserRestrictionRecord = { restrictionRecordId: restrictionId, actorSuperAdminId: ctx.actor, targetUserId: ctx.target, restrictionKind: input.restrictionKind, status: 'active', reasonCode: input.reasonCode, operatorNote: input.operatorNote, stepUpStatus: 'verified', idempotencyKey: input.idempotencyKey, createdAt: ctx.nowIso, updatedAt: ctx.nowIso }; const response: RestrictionOutcome = { status: 'success', failureReason: null, restrictionRecord, resultingEntitlementState: 'restricted', persistenceStatus: 'durable' }; await this.complete(tx, ctx, operationId, response); return response; }); } catch (error) { this.fail(error); } }
  async getControlSnapshot(targetUserId: string, asOfIso = new Date().toISOString()): Promise<SuperAdminCommercialControlSnapshot> { try { const row = (await queryDb<any>(`WITH active_gifts AS (SELECT * FROM super_admin_focus_plan_gifts WHERE target_user_id=$1 AND status='active' AND ends_at > $2), active_restrictions AS (SELECT * FROM super_admin_user_restrictions WHERE target_user_id=$1 AND status='active') SELECT (SELECT count(*)::int FROM active_gifts) AS gift_count, (SELECT count(*)::int FROM active_restrictions) AS restriction_count, (SELECT row_to_json(g) FROM (SELECT * FROM active_gifts ORDER BY created_at DESC, gift_id DESC LIMIT 1) g) AS gift, (SELECT row_to_json(r) FROM (SELECT * FROM active_restrictions ORDER BY created_at DESC, restriction_id DESC LIMIT 1) r) AS restriction`, [targetUserId, asOfIso]))[0]; return { generatedAt: asOfIso, targetUserId, activeGiftCount: row?.gift_count ?? 0, activeRestrictionCount: row?.restriction_count ?? 0, activeGift: row?.gift ? fromGift(row.gift) : null, activeRestriction: row?.restriction ? fromRestriction(row.restriction) : null, persistenceStatus: 'durable', stepUpReadinessState: 'provider_pending' }; } catch (error) { this.fail(error); } }
  async getPersistenceReadiness(): Promise<Readiness> { const checks = [
    'SELECT operation_id, action_kind, actor_user_id, target_user_id, step_up_challenge_id, idempotency_key, request_hash, reason_code, operator_note, requested_resource_id, operation_status, resulting_entitlement_state, response_json, created_at, completed_at, version FROM super_admin_commercial_operations LIMIT 0',
    'SELECT target_user_id, updated_at, version FROM super_admin_commercial_target_state LIMIT 0',
    'SELECT plan_code, reason_code, step_up_challenge_id, idempotency_key, version, retraction_reason_code, retraction_operator_note, retraction_step_up_challenge_id, retraction_idempotency_key FROM super_admin_focus_plan_gifts LIMIT 0',
    'SELECT step_up_challenge_id, idempotency_key, version FROM super_admin_user_restrictions LIMIT 0',
    'SELECT event_id, operation_id, actor_user_id, target_user_id, action_kind, idempotency_key, request_hash, step_up_challenge_id, event_kind, outcome, failure_reason, reason_code, operator_note, requested_resource_id, resulting_resource_id, occurred_at, redaction_status FROM super_admin_commercial_operation_events LIMIT 0'
  ]; try { for (const sql of checks) await queryDb(sql); return { selectedRepositoryMode: 'sql', databaseConfigured: true, requiredRelationsAvailable: true, persistenceStatus: 'durable' }; } catch { return { selectedRepositoryMode: 'sql', databaseConfigured: Boolean(runtimeEnv().DATABASE_URL), requiredRelationsAvailable: false, persistenceStatus: 'unavailable' }; } }
}

let defaultRepo: SuperAdminCommercialRepository | null = null;
export function buildDefaultSuperAdminCommercialRepository(): SuperAdminCommercialRepository { const env = runtimeEnv(); if (env.NODE_ENV === 'production' && (env.APP_STATE_REPOSITORY !== 'sql' || !env.DATABASE_URL)) throw new CommercialPersistenceError(); if (env.APP_STATE_REPOSITORY === 'sql') { if (!env.DATABASE_URL) throw new CommercialPersistenceError(); return new SQLSuperAdminCommercialRepository(); } if (env.NODE_ENV === 'production') throw new CommercialPersistenceError(); return new MemorySuperAdminCommercialRepository(); }
export const getDefaultSuperAdminCommercialRepository = () => (defaultRepo ??= buildDefaultSuperAdminCommercialRepository());
export const resetSuperAdminCommercialRepositoryForTests = () => { defaultRepo = null; };
