import type { GoldenScenarioAssetId, GoldenScenarioDefinition, GoldenScenarioCoverageReport } from '@elceo/types';
const t='2026-01-15T00:00:00.000Z';
const mk=(id:string,asset:GoldenScenarioAssetId,title:string,pressure:any,contr:boolean,themes:string[],classes:string[],fresh=false):GoldenScenarioDefinition=>({scenarioId:id,family:'asset_specific',tier:['aud_usd','usd_chf','nzd_usd','usd_cad'].includes(asset)?'tier_1b':'tier_1a',title,affectedAssets:[asset],inputEvidence:[{evidenceId:`${id}-e1`,evidenceClass:classes[0] ?? 'macro',observedAt:t,weight:0.7,note:title,sourceFixtureId:`fixture-${id}-1`}],expectedBehavior:{acceptedPressure:[pressure],acceptedConfidenceBand:[id.includes('stale')?'low':'medium'] as any,contradictionExpectation:contr?'required':'not_required',freshnessExpectation:fresh?'warning_required':'fresh',requiredTopEvidenceClasses:[...classes].sort(),requiredThemes:[...themes].sort()},deterministicResult:{evaluatedAt:t,pressure,confidenceBand:fresh?'low':'medium',contradictionDetected:contr,freshnessWarning:fresh,topEvidenceClasses:[...classes].sort(),cognitionThemes:[...themes].sort(),reasoningNotes:[`Fixture-driven scenario: ${title}`],uncertaintyFlags:contr?['contradiction_present']:[],guardrailStatus:'pass',forbiddenTermsFound:[],sourceFixtureIds:[`fixture-${id}-1`]}});
export const GOLDEN_SCENARIOS = [
mk('xau_usd_hot_inflation_real_yield','xau_usd','Hot US inflation + rising real yields','bearish',false,['dollar_strength_context','real_yield_pressure'],['dxy_liquidity','fed_policy','inflation','real_yield']),
mk('xau_usd_safe_haven_shock','xau_usd','Rising yields but safe-haven shock','mixed',true,['real_yield_vs_safe_haven'],['real_yield','risk_regime']),
mk('eur_usd_ecb_hawkish','eur_usd','ECB hawkish surprise vs Fed neutral','mixed_positive',false,['ecb_repricing','yield_differential'],['fed_policy','inflation']),
mk('gbp_usd_wages_cpi_weak_growth','gbp_usd','Strong UK wages/CPI but weak growth','mixed',true,['inflation_vs_growth'],['inflation','macro_growth']),
mk('usd_jpy_yields_intervention','usd_jpy','US yields rising + intervention risk','mixed',true,['yield_differential_vs_intervention'],['real_yield','risk_regime']),
mk('btc_usd_etf_liquidity_tightening','btc_usd','ETF inflow but macro liquidity tightening','mixed',true,['etf_demand_vs_liquidity_tightening'],['etf_flow','liquidity']),
mk('nasdaq_earnings_real_yields','nasdaq_100','Strong megacap earnings but rising real yields','mixed',true,['earnings_vs_rate_pressure'],['earnings','real_yield']),
mk('sp500_price_breadth_divergence','sp500','Index strong but breadth weakening','mixed_caution',true,['price_strength_vs_breadth'],['market_breadth','market_price_history']),
mk('de30_industrial_weakness_risk_on','de30','German industrial weakness + global risk-on','mixed',true,['domestic_weakness_vs_global_risk_on'],['macro_growth','risk_regime']),
mk('dxy_hawkish_risk_off','dxy','Fed hawkish repricing + global risk-off','bullish',false,['usd_yield_advantage','risk_off_dollar_demand'],['fed_policy','risk_regime']),
mk('vix_selloff_credit_stress','vix','Equity selloff + credit stress widening','bullish',false,['volatility_expansion','credit_stress'],['credit_stress','volatility']),
mk('aud_usd_rba_china_drag','aud_usd','RBA hawkish surprise but China demand deterioration','mixed',true,['rba_support_vs_china_drag'],['macro_growth','real_yield']),
mk('usd_chf_risk_off_vs_usd_yields','usd_chf','Risk-off safe-haven CHF vs strong USD yields','mixed',true,['chf_safe_haven_vs_usd_yield_support'],['real_yield','risk_regime']),
mk('nzd_usd_rbnz_risk_off','nzd_usd','RBNZ hawkish but global risk-off','mixed',true,['rbnz_support_vs_risk_off'],['real_yield','risk_regime']),
mk('usd_cad_oil_vs_fed','usd_cad','Oil supports CAD but Fed hawkish repricing supports USD','mixed',true,['oil_support_vs_usd_repricing'],['commodities','fed_policy']),
{...mk('cross_asset_risk_off_shock','vix','Broad risk-off shock','bullish',true,['safe_haven_and_volatility_shock'],['risk_regime','volatility']),family:'cross_asset',tier:'cross_asset',affectedAssets:['vix','sp500','nasdaq_100','xau_usd','usd_jpy','usd_chf','dxy']},
{...mk('cross_asset_liquidity_tightening','dxy','Liquidity tightening regime','bullish',true,['liquidity_pressure_regime'],['dxy_liquidity','liquidity']),family:'cross_asset',tier:'cross_asset',affectedAssets:['btc_usd','nasdaq_100','sp500','xau_usd','dxy']},
{...mk('stale_evidence_warning','sp500','Stale evidence warning scenario','mixed_caution',true,['freshness_decay_guardrail'],['market_price_history','risk_regime'],true),family:'freshness',tier:'cross_asset'}
].sort((a,b)=>a.scenarioId.localeCompare(b.scenarioId));
export const getGoldenScenarioCoverageReport=():GoldenScenarioCoverageReport=>({totalScenarios:GOLDEN_SCENARIOS.length,tier1AAssetsCovered:[...new Set(GOLDEN_SCENARIOS.filter(x=>x.tier==='tier_1a').flatMap(x=>x.affectedAssets))].sort() as GoldenScenarioAssetId[],tier1BAssetsCovered:[...new Set(GOLDEN_SCENARIOS.filter(x=>x.tier==='tier_1b').flatMap(x=>x.affectedAssets))].sort() as GoldenScenarioAssetId[],crossAssetScenarioIds:GOLDEN_SCENARIOS.filter(x=>x.family==='cross_asset').map(x=>x.scenarioId).sort(),freshnessScenarioIds:GOLDEN_SCENARIOS.filter(x=>x.family==='freshness').map(x=>x.scenarioId).sort()});
