import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { Pool } from 'pg';
import { CanonicalCognitionMaterializationService, createAdaptiveMaterializationPolicy, createAdaptiveMaterializationRedisClient, FencedMaterializationRepository, RedisAdaptiveOwnershipStore, SqlImmutableMaterializationStore, type CanonicalArtifact } from '../adaptive-materialization/index.js';
export async function runAdaptiveMaterializationIntegrationTests(){
 if(process.env.ADAPTIVE_MATERIALIZATION_INTEGRATION!=='1')return;if(!process.env.DATABASE_URL||!process.env.REDIS_URL)throw new Error('adaptive_materialization_integration_infrastructure_missing');
 const pool=new Pool({connectionString:process.env.DATABASE_URL}),client=createAdaptiveMaterializationRedisClient(),namespace=`elceo:pgs4:integration:${process.pid}:${Date.now()}`,ownership=new RedisAdaptiveOwnershipStore(client,namespace),sql={query:async(sql:string,params?:unknown[])=>{const result=await pool.query(sql,params);return{rows:result.rows as{artifact_json:string}[]}}},immutable=new SqlImmutableMaterializationStore(sql),repository=new FencedMaterializationRepository(ownership,immutable);
 try{await pool.query(await readFile('infra/db/schema/0050_adaptive_materialization.sql','utf8'));const acquired=await ownership.acquire('integration-job','owner',500);assert.ok(acquired.acquired);if(!acquired.acquired)throw new Error('missing_integration_owner');const now=new Date().toISOString(),base={schemaVersion:'canonical_materialization_v1'as const,kind:'evidence'as const,scopeHash:'integration-evidence-scope',policyVersion:'integration-v1',ruleVersions:['evidence-v1'],schedulerRunId:'integration-run',generatedAt:now,evaluatedAt:now,freshUntil:new Date(Date.now()+5000).toISOString()},a:CanonicalArtifact<{observation:string}>={...base,identity:`evidence:A:${Date.now()}`,payload:{observation:'A'},evidenceIdentity:'evidence-A',integrityHash:'sha256:A'},b:CanonicalArtifact<{observation:string}>={...base,identity:`evidence:B:${Date.now()}`,payload:{observation:'B'},evidenceIdentity:'evidence-B',integrityHash:'sha256:B'};assert.equal(await repository.publish(acquired.lease,a),true);assert.equal(await repository.publish(acquired.lease,b),true);assert.deepEqual((await repository.readCurrent<{observation:string}>('integration-job',b.scopeHash)).artifact?.payload,{observation:'B'});assert.deepEqual((await immutable.getImmutable<{observation:string}>(a.identity))?.payload,{observation:'A'});await ownership.release(acquired.lease);
 const policy=createAdaptiveMaterializationPolicy({policyId:'integration',policyVersion:'v1',status:'test_only',provenance:'integration',effectiveFrom:'2020-01-01T00:00:00.000Z',effectiveTo:null,sourceId:'fixture_source',capabilityId:'market_price_history',credentialPoolId:'fixture_pool',asset:'xau_usd',region:null,horizon:'intraday',minimumRefreshIntervalMs:100,baseRefreshIntervalMs:200,maximumRefreshIntervalMs:500,staleAfterMs:1000,retryMinimumMs:120,retryMaximumMs:1000,leaseDurationMs:60,evaluationEpochMs:1000,expectedReleaseMinuteUtc:null});let computes=0;const configuration={cognitionContractVersion:'integration-cognition-v1',weightingPolicyVersion:'integration-weight-v1',ruleVersions:['integration-rule-v1'],freshnessMs:1000,validate:()=>true},compute=async()=>{computes++;await new Promise(r=>setTimeout(r,180));return{bias:'neutral'}},one=new CanonicalCognitionMaterializationService(repository,ownership,configuration,compute),two=new CanonicalCognitionMaterializationService(repository,ownership,configuration,compute),input={evidenceIdentities:[a.identity,b.identity],asset:'xau_usd',horizon:'intraday',evaluatedAt:Date.now(),schedulerRunId:'integration-cognition'};const cognition=await Promise.all([one.materialize(policy,input),two.materialize(policy,input)]);assert.equal(computes,1);assert.equal(cognition[0]?.identity,cognition[1]?.identity);const reads=await Promise.all(Array.from({length:1000},()=>one.read('xau_usd','intraday')));assert.equal(computes,1);assert.equal(new Set(reads.flatMap(x=>x.artifact?[x.artifact.identity]:[])).size,1);console.log('adaptive materialization Redis+PostgreSQL integration passed: cognition_compute=1 reads=1000')
 }finally{if(client.isOpen){const keys=await client.keys(`${namespace}:*`);if(keys.length)await client.del(keys)}await ownership.close();await pool.end()}
}
