import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { Pool } from 'pg';
import { AdaptiveMaterializationOrchestrator, AdaptiveMaterializationScheduler, CanonicalCognitionMaterializationService, CanonicalEvidenceMaterializationService, createAdaptiveMaterializationPolicy, createAdaptiveMaterializationRedisClient, FencedMaterializationRepository, PGS4_PRODUCTION_COGNITION_CONFIGURATION, ProductionAggregateInputResolver, RedisAdaptiveOwnershipStore, SqlImmutableMaterializationStore, buildAdaptiveJobIdentity, buildMaterializationScopeHash, type AdaptiveMaterializationMetrics, type AdaptiveMaterializationPolicy, type ScheduledProviderExecutor } from '../adaptive-materialization/index.js';
import { buildMarketCognitionSnapshot } from '../market-cognition/market-cognition-builder.js';
import { buildProviderApiGateSnapshot, resolveProviderRuntimeRequest, type ProviderRuntimeRequest } from '../provider-sources/provider-api-gate.js';

const metrics=():AdaptiveMaterializationMetrics=>({scheduleEvaluations:0,jobsDue:0,leaseAcquired:0,leaseDenied:0,providerRefreshAttempted:0,providerCacheSatisfied:0,canonicalEvidencePublished:0,cognitionComputed:0,cognitionReused:0,previousMaterializationServed:0,failures:{},nextDueAt:null});
const policy=(sourceId:string,capabilityId:AdaptiveMaterializationPolicy['capabilityId'])=>createAdaptiveMaterializationPolicy({policyId:`integration-${sourceId}`,policyVersion:'v1',status:'approved',provenance:'pgs4_production_composite_acceptance',effectiveFrom:'2020-01-01T00:00:00.000Z',effectiveTo:null,sourceId,capabilityId,credentialPoolId:'integration_pool',asset:'xau_usd',region:null,horizon:'intraday',minimumRefreshIntervalMs:100,baseRefreshIntervalMs:200,maximumRefreshIntervalMs:1000,staleAfterMs:60_000,retryMinimumMs:120,retryMaximumMs:1000,leaseDurationMs:60,evaluationEpochMs:1000,expectedReleaseMinuteUtc:null});
const request=(p:AdaptiveMaterializationPolicy,id:string):ProviderRuntimeRequest=>({requestId:id,sourceId:p.sourceId,capabilityId:p.capabilityId,asset:p.asset,region:p.region,activationMode:'staging_live_allowed',provenance:{actor:'pgs4_scheduler',purpose:'canonical_evidence_refresh'},policy:{explicitStagingLiveAllow:true,requestMetadata:{credentialPresent:true}}});

export async function runAdaptiveMaterializationIntegrationTests(){
 if(process.env.ADAPTIVE_MATERIALIZATION_INTEGRATION!=='1')return;if(!process.env.DATABASE_URL||!process.env.REDIS_URL)throw new Error('adaptive_materialization_integration_infrastructure_missing');
 const pool=new Pool({connectionString:process.env.DATABASE_URL}),client=createAdaptiveMaterializationRedisClient(),namespace=`elceo:pgs4:integration:${process.pid}:${Date.now()}`,ownership=new RedisAdaptiveOwnershipStore(client,namespace),sql={query:async(sql:string,params?:unknown[])=>{const result=await pool.query(sql,params);return{rows:result.rows as{artifact_json:string}[]}}},immutable=new SqlImmutableMaterializationStore(sql),repository=new FencedMaterializationRepository(ownership,immutable);
 try{await pool.query(await readFile('../../infra/db/schema/0050_adaptive_materialization.sql','utf8'));const first=policy('tiingo_market_data','market_price_history'),second=policy('geopolitical_public_news','market_news_feed'),firstRequest=request(first,'provider-one'),secondRequest=request(second,'provider-two');let providerExecutions=0,cognitionComputations=0;const gate:ScheduledProviderExecutor=async req=>{providerExecutions++;const decision=resolveProviderRuntimeRequest(req),receivedAt=new Date().toISOString(),evidenceClass=req.sourceId===first.sourceId?'real_yields' as const:'market_news' as const,normalized={payloadId:`${req.sourceId}-current`,evidenceTypeId:evidenceClass,evidenceClass,providerId:req.sourceId,sourceId:req.sourceId,region:'global',asset:'xau_usd',observedAt:receivedAt,publishedAt:null,normalizedAt:receivedAt,confidenceScore:90,dataQuality:'high' as const,valuesJson:'{}',metadataJson:'{"sourceMode":"live","direction":"bullish"}'},response={requestId:req.requestId,responseId:`response-${req.sourceId}`,sourceId:req.sourceId,capabilityId:req.capabilityId,adapterId:decision.adapterId??`${req.sourceId}_${req.capabilityId}_adapter` as const,receivedAt,payload:{normalizedPayloads:[normalized]},payloadSchemaStatus:'valid' as const,payloadSizeBytes:100,recordCount:1,revision:'revision-1',provenance:{requestId:req.requestId,sourceId:req.sourceId},error:null,rateLimit:null};return{decision,response,snapshot:buildProviderApiGateSnapshot(decision,req.requestId,response),settlementState:'settled_committed' as const}};
 const scope=(p:AdaptiveMaterializationPolicy)=>({coordinationHash:buildAdaptiveJobIdentity(p),scopeHash:buildMaterializationScopeHash({asset:p.asset,horizon:p.horizon,kind:'evidence',sourceId:p.sourceId,capabilityId:p.capabilityId,region:p.region})}),allScopes=[scope(first),scope(second)],aggregateResolver=new ProductionAggregateInputResolver(repository,()=>allScopes),makeCognition=()=>new CanonicalCognitionMaterializationService(repository,ownership,PGS4_PRODUCTION_COGNITION_CONFIGURATION,async input=>{cognitionComputations++;await new Promise(r=>setTimeout(r,180));if(!input.weightedSnapshot)throw new Error('missing_weighted_snapshot');return buildMarketCognitionSnapshot(input.weightedSnapshot,new Date(input.evaluatedAt).toISOString())});
 const seedMetrics=metrics(),seedScheduler=new AdaptiveMaterializationScheduler(ownership,gate,{credentialPoolId:'integration_pool'},seedMetrics),seedEvidence=new CanonicalEvidenceMaterializationService(repository,'normalized-market-evidence-v1',seedMetrics),seed=await seedScheduler.execute(second,secondRequest);assert.ok(seed);if(!seed)throw new Error('missing_seed_owner');const seeded=await seedEvidence.materializeResult(seed.lease,second,secondRequest,seed.result,Date.now(),'seed-source-two');await seedScheduler.finalize(seed,second,{evaluatedAt:Date.now(),lastPublishedAt:Date.parse(seeded.artifact.generatedAt),lastAttemptSucceeded:true,publishedNewEvidence:seeded.publishedNewEvidence,resilienceRetryAt:null,expectedReleaseAt:null});
 const contenders=Array.from({length:100},()=>{const localMetrics=metrics(),scheduler=new AdaptiveMaterializationScheduler(ownership,gate,{credentialPoolId:'integration_pool'},localMetrics),evidence=new CanonicalEvidenceMaterializationService(repository,'normalized-market-evidence-v1',localMetrics),cognition=makeCognition();return new AdaptiveMaterializationOrchestrator(scheduler,evidence,cognition,(asset,horizon,evaluatedAt)=>aggregateResolver.resolve(asset,horizon,evaluatedAt))});const beforeContenders=providerExecutions,results=await Promise.all(contenders.map((orchestrator,index)=>orchestrator.run(first,{...firstRequest,requestId:`provider-one-${index}`},Date.now(),`scheduler-run-${index}`)));assert.equal(providerExecutions-beforeContenders,1);assert.equal(results.filter(Boolean).length,1);const completed=results.find(result=>result!==null);assert.ok(completed);if(!completed)throw new Error('missing_composite_result');assert.equal(completed.aggregate.evidenceIdentities.length,2);assert.deepEqual(completed.aggregate.evidenceIdentities,completed.aggregate.evidenceArtifacts.map(x=>x.identity));assert.deepEqual(completed.aggregate.normalizedPayloads.map(x=>x.payloadId).sort(),['geopolitical_public_news-current','tiingo_market_data-current']);assert.equal(cognitionComputations,1);const nextEvaluation=Date.now()+first.evaluationEpochMs,aggregateNext=await aggregateResolver.resolve('xau_usd','intraday',nextEvaluation),distributedBefore=cognitionComputations,distributedInput={evidenceIdentities:aggregateNext.evidenceIdentities,asset:'xau_usd',horizon:'intraday',evaluatedAt:nextEvaluation,schedulerRunId:'distributed-contention',weightedSnapshot:aggregateNext.weightedSnapshot};const distributed=await Promise.all([makeCognition().materialize(first,distributedInput),makeCognition().materialize(first,{...distributedInput,schedulerRunId:'different-runtime-provenance'})]);assert.equal(cognitionComputations-distributedBefore,1);assert.equal(distributed[0]?.identity,distributed[1]?.identity);
 const consumer=new CanonicalCognitionMaterializationService(repository,ownership,PGS4_PRODUCTION_COGNITION_CONFIGURATION,async()=>{throw new Error('consumer_must_not_compute')}),providersBeforeReads=providerExecutions,computesBeforeReads=cognitionComputations,reads=await Promise.all(Array.from({length:1000},()=>consumer.read('xau_usd','intraday')));assert.equal(providerExecutions,providersBeforeReads);assert.equal(cognitionComputations,computesBeforeReads);assert.equal(new Set(reads.flatMap(x=>x.artifact?[x.artifact.identity]:[])).size,1);assert.ok(await immutable.getImmutable(seeded.artifact.identity));console.log('adaptive materialization production composite passed: contenders=100 provider_executions=1 cognition_compute=1 reads=1000')
 }finally{if(client.isOpen){const keys=await client.keys(`${namespace}:*`);if(keys.length)await client.del(keys)}await ownership.close();await pool.end()}
}
