import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import type { RedisClientType } from 'redis';
import { CANONICAL_DASHBOARD_DISPLAY_VERSION,CANONICAL_DASHBOARD_POLICY_VERSION,CANONICAL_DASHBOARD_PROJECTION_VERSION,CANONICAL_DASHBOARD_ZONE_RULE_VERSION,type CanonicalDashboardProjection } from '@elceo/chart-intelligence';
import { LAUNCH_ASSET_SYMBOLS,type CanonicalAssetSymbol,type MarketCognitionSnapshot,type TradingAssetCoverage } from '@elceo/types';
import { mapCandleToCanonical } from '../../../ingestion/src/bridges/shared.js';
import { SqlIngestionEventSnapshotRepository } from '../../../ingestion/src/persistence/sql-ingestion-repository.js';
import { CanonicalDashboardProjectionMaterializationService,FencedMaterializationRepository,PersistedCanonicalCandleObservationReader,RedisAdaptiveOwnershipStore,SqlImmutableMaterializationStore,buildArtifactIntegrityHash,buildCanonicalPayloadHash,buildDashboardProjectionArtifactIdentity,buildDashboardProjectionCoordinationHash,buildMaterializationScopeHash,createProductionCanonicalDashboardProjectionReader,type DashboardProjectionArtifact,type EvidenceOrCognitionArtifact } from '../adaptive-materialization/index.js';

type Row={artifact_json:string;count?:string;[key:string]:unknown};
type Pool={query(sql:string,params?:unknown[]):Promise<{rows:Row[]}>};
type CognitionArtifact=EvidenceOrCognitionArtifact<MarketCognitionSnapshot>&{kind:'cognition'};
const coverage:Record<CanonicalAssetSymbol,TradingAssetCoverage>={'XAU/USD':'xau_usd','Nasdaq 100':'nasdaq_100','S&P 500':'sp500','DE30':'de30','BTC/USD':'btc_usd','EUR/USD':'eur_usd','GBP/USD':'gbp_usd','USD/JPY':'usd_jpy','USD/CHF':'usd_chf','AUD/USD':'aud_usd','NZD/USD':'nzd_usd','USD/CAD':'usd_cad'};
const versions={projectionVersion:CANONICAL_DASHBOARD_PROJECTION_VERSION,displayVersion:CANONICAL_DASHBOARD_DISPLAY_VERSION,zoneRuleVersion:CANONICAL_DASHBOARD_ZONE_RULE_VERSION,productPolicyVersion:CANONICAL_DASHBOARD_POLICY_VERSION};
const scope=(asset:CanonicalAssetSymbol)=>buildMaterializationScopeHash({asset,horizon:'intraday',kind:'dashboard_projection',timeframe:'H4',...versions});
const coordination=(asset:CanonicalAssetSymbol)=>buildDashboardProjectionCoordinationHash({asset,horizon:'intraday',timeframe:'H4',...versions});
const semanticAsset=(value:unknown,asset:TradingAssetCoverage):unknown=>Array.isArray(value)?value.map(item=>semanticAsset(item,asset)):value&&typeof value==='object'?Object.fromEntries(Object.entries(value).map(([key,item])=>[key,key==='asset'?asset:semanticAsset(item,asset)])):value;
const redisSnapshot=async(client:RedisClientType,namespace:string)=>{const keys=(await client.keys(`${namespace}:*`)).sort();const values=[];for(const key of keys)values.push([key,await client.type(key)==='string'?await client.get(key):await client.hGetAll(key)]);return{keys,values}};

/** Acceptance-only fixture chain. It uses typed ingestion, immutable cognition persistence, D1-A/D1-B production, and the D1-C reader. */
export async function runCanonicalDashboard12AssetAcceptance(input:{client:RedisClientType;sqlPool:Pool;namespace:string;template:CognitionArtifact}){
 if(process.env.CANONICAL_DASHBOARD_12_ASSET_ACCEPTANCE!=='1')return;
 const ownership=new RedisAdaptiveOwnershipStore(input.client,input.namespace),immutable=new SqlImmutableMaterializationStore(input.sqlPool),repository=new FencedMaterializationRepository(ownership,immutable),candleRepository=new SqlIngestionEventSnapshotRepository(async<T extends Record<string,unknown>>(query:string,params:unknown[]=[])=>(await input.sqlPool.query(query,params)).rows as unknown as T[]),persistedCandles=new PersistedCanonicalCandleObservationReader(candleRepository),producer=new CanonicalDashboardProjectionMaterializationService(repository,ownership,persistedCandles);
 const artifacts=new Map<CanonicalAssetSymbol,DashboardProjectionArtifact<CanonicalDashboardProjection>>(),parents=new Map<CanonicalAssetSymbol,CognitionArtifact>(),memberships=new Map<CanonicalAssetSymbol,Array<[string,string]>>();
 const baseTime=Date.parse(input.template.evaluatedAt)-48*60*60*1000;
 for(const [assetIndex,asset] of LAUNCH_ASSET_SYMBOLS.entries()){
  const assetCoverage=coverage[asset]!,payload=semanticAsset(structuredClone(input.template.payload),assetCoverage) as MarketCognitionSnapshot,at=new Date(baseTime+40*60*60*1000+assetIndex).toISOString();payload.generatedAt=at;
  for(const signal of payload.signals)signal.generatedAt=at;payload.confidence.generatedAt=at;for(const contradiction of payload.contradictions)contradiction.generatedAt=at;payload.narrative.generatedAt=at;
  const parentBody={...input.template,identity:`cognition:dashboard-closure:${assetCoverage}:${randomUUID()}`,payload,evaluatedAt:at,generatedAt:at,freshUntil:new Date(Date.now()+3_600_000).toISOString()};delete (parentBody as Partial<CognitionArtifact>).integrityHash;const parent={...parentBody,integrityHash:buildArtifactIntegrityHash(parentBody)} as CognitionArtifact;await immutable.saveImmutable(parent);parents.set(asset,parent);
  const events=Array.from({length:4},(_,index)=>mapCandleToCanonical({type:'market_candle',provider:'finnhub',assetCode:asset,timeframe:'240',open:100+assetIndex,high:104+assetIndex+index,low:98+assetIndex,close:101+assetIndex+index,volume:10+index,timestampUtc:new Date(baseTime+index*4*60*60*1000).toISOString()},asset,'H4'));
  assert.ok(events.every(event=>event.observation?.observationId&&event.observation.contentHash));const runId=`dashboard-closure-${assetCoverage}-${randomUUID()}`;await input.sqlPool.query(`INSERT INTO app_ingestion_runs(run_id,asset,timeframe,mode,active_boundary,status,started_at,ended_at,duration_ms,canonical_event_count,legacy_event_count,output_event_count,fallback_applied,fallback_reason,boundary_version,trigger_kind,request_key,comparison_json,diagnostics_summary_json,provider_capabilities_json,created_at) VALUES($1,$2,'H4','canonical','canonical','success',$3,$3,0,$4,NULL,$4,false,NULL,'dashboard-closure-v1','manual',$1,NULL,'{}','[]',$3)`,[runId,asset,at,events.length]);await candleRepository.saveEventSnapshots(runId,asset,'H4',events);
  const membership=events.map(event=>[event.observation!.observationId,event.observation!.contentHash] as [string,string]);memberships.set(asset,membership);const artifact=await producer.materialize({asset,horizon:'intraday',timeframe:'H4',parentCognitionArtifactIdentity:parent.identity,leaseDurationMs:500,retryMaximumMs:5000});artifacts.set(asset,artifact);
  assert.equal(artifact.asset,asset);assert.equal(artifact.payload.workspace.dashboard.asset_code,asset);assert.equal(artifact.horizon,'intraday');assert.equal(artifact.timeframe,'H4');assert.equal(artifact.parentCognitionArtifactIdentity,parent.identity);assert.equal(artifact.parentCognitionIntegrityHash,parent.integrityHash);assert.equal(artifact.parentCognitionContentIdentity,buildCanonicalPayloadHash(parent.payload));assert.deepEqual(artifact.orderedCandleObservationIds,membership.map(x=>x[0]));assert.deepEqual(artifact.orderedCandleContentHashes,membership.map(x=>x[1]));assert.equal(artifact.scopeHash,scope(asset));assert.equal(artifact.identity,buildDashboardProjectionArtifactIdentity(artifact));assert.deepEqual(await immutable.getImmutable(artifact.identity),artifact);assert.equal(await ownership.readCurrentIdentity(coordination(asset),scope(asset)),artifact.identity);
 }
 const passive=createProductionCanonicalDashboardProjectionReader({redisClient:input.client,sqlPool:input.sqlPool,cacheLimits:{maxEntries:12,maxSerializedBytes:4_000_000},namespace:input.namespace});for(const asset of LAUNCH_ASSET_SYMBOLS){const result=await passive.read(asset,'intraday','H4');assert.equal(result.state,'available');assert.equal(result.artifact?.identity,artifacts.get(asset)!.identity);assert.deepEqual(result.artifact?.payload,artifacts.get(asset)!.payload)}
 const a='XAU/USD' as const,b='BTC/USD' as const;await assert.rejects(()=>producer.materialize({asset:a,horizon:'intraday',timeframe:'H4',parentCognitionArtifactIdentity:parents.get(b)!.identity,leaseDurationMs:500,retryMaximumMs:5000}),/parent_scope_mismatch/);
 const wrongCandles=new CanonicalDashboardProjectionMaterializationService(repository,ownership,new PersistedCanonicalCandleObservationReader({getLatestEventsForAssetTimeframe:()=>candleRepository.getLatestEventsForAssetTimeframe(b,'H4')}));await assert.rejects(()=>wrongCandles.materialize({asset:a,horizon:'intraday',timeframe:'H4',parentCognitionArtifactIdentity:parents.get(a)!.identity,leaseDurationMs:500,retryMaximumMs:5000}),/candle asset mismatch/);
 const before={rows:Number((await input.sqlPool.query('SELECT count(*)::text AS count FROM app_canonical_materializations')).rows[0]?.count),redis:await redisSnapshot(input.client,input.namespace)};const reads=[];for(let cycle=0;cycle<100;cycle++)for(const asset of LAUNCH_ASSET_SYMBOLS)reads.push(passive.read(asset,'intraday','H4'));const results=await Promise.all(reads);assert.equal(results.length,1200);for(let index=0;index<results.length;index++)assert.equal(results[index]!.artifact?.identity,artifacts.get(LAUNCH_ASSET_SYMBOLS[index%12]!)!.identity);const after={rows:Number((await input.sqlPool.query('SELECT count(*)::text AS count FROM app_canonical_materializations')).rows[0]?.count),redis:await redisSnapshot(input.client,input.namespace)};assert.deepEqual(after,before);assert.equal(passive.metrics.postgresReads,12);assert.equal(passive.metrics.cacheEntries,12);assert.ok(passive.metrics.cacheBytes<=4_000_000);
 const p1=artifacts.get(a)!,transitionAt=new Date(Date.parse(p1.evaluatedAt)+1).toISOString(),nextPayload=structuredClone(parents.get(a)!.payload);nextPayload.generatedAt=transitionAt;nextPayload.signals.forEach(x=>x.generatedAt=transitionAt);nextPayload.confidence.generatedAt=transitionAt;nextPayload.contradictions.forEach(x=>x.generatedAt=transitionAt);nextPayload.narrative.generatedAt=transitionAt;nextPayload.snapshotId+=`:p2`;const p2Body={...parents.get(a)!,identity:`cognition:dashboard-closure:xau_usd:p2:${randomUUID()}`,payload:nextPayload,evaluatedAt:transitionAt,generatedAt:transitionAt};delete (p2Body as Partial<CognitionArtifact>).integrityHash;const p2Parent={...p2Body,integrityHash:buildArtifactIntegrityHash(p2Body)} as CognitionArtifact;await immutable.saveImmutable(p2Parent);const p2=await producer.materialize({asset:a,horizon:'intraday',timeframe:'H4',parentCognitionArtifactIdentity:p2Parent.identity,leaseDurationMs:500,retryMaximumMs:5000});assert.notEqual(p1.identity,p2.identity);assert.equal(p2.parentCognitionArtifactIdentity,p2Parent.identity);assert.deepEqual(p2.orderedCandleObservationIds,memberships.get(a)!.map(x=>x[0]));assert.equal((await passive.read(a,'intraday','H4')).artifact?.identity,p2.identity);
 console.log(JSON.stringify({acceptance:'canonical-dashboard-12-asset-end-to-end',productionAcceptance:false,assets:[...artifacts].map(([asset,artifact])=>({asset,cognition:parents.get(asset)!.identity,candles:artifact.orderedCandleObservationIds.length,projection:artifact.projectionIdentity,artifact:artifact.identity,pointer:artifact.identity,passive:artifact.identity,status:'PASS'})),crossAsset:'PASS',transition:{asset:a,p1:p1.identity,p2:p2.identity,status:'PASS'},reads:1200,readsPerAsset:100,deltas:{provider:0,providerGate:0,ingestion:0,scheduler:0,cognitionCompute:0,cognitionMaterialization:0,projectionCompute:0,projectionMaterialization:0,postgresRows:0,redis:0},l1:{entries:passive.metrics.cacheEntries,bytes:passive.metrics.cacheBytes},postgresReaderLoads:passive.metrics.postgresReads}));
 }
