import { validateMarketConfidenceCalibrationCoverageReport, validateMarketConfidenceCalibrationInput, validateMarketConfidenceCalibrationResult, validateMarketConfidenceCalibrationRuleSetSnapshot } from '@elceo/schemas';
import type { EvidenceWeightHorizon, MarketConfidenceCalibrationInput, WeightedEvidenceItem, WeightedEvidenceSnapshot } from '@elceo/types';
import { buildMarketCognitionSnapshot } from '../market-cognition/index.js';
import { calibrateConfidenceFromWeightedSnapshot, calibrateMarketConfidence, getMarketConfidenceCalibrationCoverageReport, getMarketConfidenceCalibrationRuleSetSnapshot } from '../confidence-calibration/index.js';
import { CanonicalMarketIntelligenceBoundaryService } from '../runtime/canonical-market-intelligence-boundary.js';
import { MemoryMarketEvidenceRegistrySnapshotRepository, MemorySeoContentArchitectureSnapshotRepository } from '../persistence/registry-snapshot-repository.js';
function assert(condition: boolean, message: string): void { if (!condition) throw new Error(`Assertion failed: ${message}`); }
const at = '2026-06-04T00:00:00.000Z';
const item = (id: string, evidenceClass: WeightedEvidenceItem['evidenceClass'], direction: WeightedEvidenceItem['direction'], reasons: string[] = [], quality = 90): WeightedEvidenceItem => ({ payloadId:id, asset:'sp500', horizon:'intraday', evidenceTypeId:evidenceClass, evidenceClass, providerId:'fixture', observedAt:at, finalQualityScore:quality, baseWeight:50, qualityAdjustedWeight:45, role:'primary_driver', direction, contributionScore:45, reasons });
const snapshot = (items: WeightedEvidenceItem[], warnings: string[] = []): WeightedEvidenceSnapshot => ({ snapshotId:`w-${items.map((i)=>i.payloadId).join('-')}`, generatedAt:at, asset:items[0]?.asset ?? 'sp500', horizon:'intraday' as EvidenceWeightHorizon, totalWeight:100, usableWeight:90, excludedWeight:0, items, warnings });
const input = (partial: Partial<MarketConfidenceCalibrationInput>): MarketConfidenceCalibrationInput => ({ asset:'sp500', horizon:'intraday', generatedAt:at, baseConfidence:75, evidenceQuality:90, usableWeight:90, freshness:90, coverage:70, warnings:[], reasonCodes:[], options:{ providerReliabilitySupplied:true, sourceIndependenceVerified:true, priceReactionAvailable:true }, ...partial });
export function runConfidenceCalibrationTests(): void {
  const cleanInput = input({ options:{ sourceIndependenceVerified:true, priceReactionAvailable:true } });
  assert(validateMarketConfidenceCalibrationInput(cleanInput).ok, 'schema validator accepts calibration input');
  const clean = calibrateMarketConfidence(cleanInput);
  assert(validateMarketConfidenceCalibrationResult(clean).ok, 'schema validator accepts calibration result');
  assert(clean.confidenceTier === 'high' && clean.finalConfidence < 80, 'clean strong evidence can reach high but provider reliability pending blocks very high by default when omitted only in result pending');
  const ruleSet = getMarketConfidenceCalibrationRuleSetSnapshot(at); const coverage = getMarketConfidenceCalibrationCoverageReport(at);
  assert(validateMarketConfidenceCalibrationRuleSetSnapshot(ruleSet).ok, 'rule set validates');
  assert(validateMarketConfidenceCalibrationCoverageReport(coverage).ok && coverage.pending.priceReactionR7 && coverage.pending.providerReliabilityExpansion && coverage.pending.goldenScenarioExpansion && coverage.pending.empiricalBacktesting, 'coverage report keeps pending expansions');
  assert(!JSON.stringify(clean).match(/\b(buy|sell|hold|guaranteed profit|risk-free)\b/i), 'no direct advice language');
  const severe = calibrateMarketConfidence(input({ contradictionMatrix:{ resultId:'m', asset:'sp500', horizon:'intraday', generatedAt:at, status:'contradiction', highestSeverity:'high', signals:[{ signalId:'s', ruleId:'r', family:'risk_vs_credit', asset:'sp500', horizon:'intraday', generatedAt:at, status:'contradiction', severity:'high', confidenceTier:'high', evidencePointIds:['a','b'], warnings:[], reasonCodes:['contradiction_matrix_rule_applied'], rationale:'High severity contradiction context' }], evidencePoints:[], warnings:[], reasonCodes:['contradiction_matrix_rule_applied'], rationale:'matrix', complete:false, pending:{ confidenceCalibrationR6:true, priceReactionR7:true, providerReliabilityExpansion:true } } }));
  assert(severe.finalConfidence <= clean.finalConfidence - 15 && severe.confidenceTier !== 'high' && severe.confidenceTier !== 'very_high', 'severe contradiction lowers confidence materially and blocks high tiers');
  const moderateSignals = (count: number) => calibrateMarketConfidence(input({ contradictionMatrix:{ resultId:`mod${count}`, asset:'sp500', horizon:'intraday', generatedAt:at, status:'tension', highestSeverity:'moderate', signals:Array.from({length:count},(_,i)=>({ signalId:`s${i}`, ruleId:'r', family:'risk_vs_credit', asset:'sp500' as const, horizon:'intraday' as const, generatedAt:at, status:'tension' as const, severity:'moderate' as const, confidenceTier:'medium' as const, evidencePointIds:['a'], warnings:[], reasonCodes:['contradiction_matrix_rule_applied' as const], rationale:'Moderate tension context' })), evidencePoints:[], warnings:[], reasonCodes:['contradiction_matrix_rule_applied'], rationale:'matrix', complete:false, pending:{ confidenceCalibrationR6:true, priceReactionR7:true, providerReliabilityExpansion:true } } }));
  assert(moderateSignals(3).finalConfidence < moderateSignals(1).finalConfidence, 'multiple moderate tensions lower confidence more than one low/moderate tension');
  assert(calibrateMarketConfidence(input({ options:{ eventSensitive:true, priceReactionAvailable:false, providerReliabilitySupplied:true, sourceIndependenceVerified:true } })).confidenceTier === 'medium', 'pending price confirmation caps below high');
  assert(calibrateMarketConfidence(input({ warnings:['missing_forecast'], options:{ macroDriven:true, providerReliabilitySupplied:true, sourceIndependenceVerified:true, priceReactionAvailable:true } })).confidenceTier === 'medium', 'missing macro forecast lowers and caps confidence');
  assert(calibrateMarketConfidence(input({ warnings:['previous_used_without_forecast'] })).finalConfidence < clean.finalConfidence, 'previous-only macro fallback lowers confidence');
  assert(calibrateMarketConfidence(input({ warnings:['missing_actual'] })).finalConfidence <= clean.finalConfidence - 20, 'missing macro actual heavily lowers confidence');
  assert(calibrateMarketConfidence(input({ asset:'eur_usd', warnings:['missing_base_pressure'] })).confidenceTier !== 'high', 'one-sided FX evidence lowers and caps confidence');
  assert(calibrateMarketConfidence(input({ asset:'eur_usd', warnings:['pending_fx_relative_strength'] })).finalConfidence < clean.finalConfidence, 'pending FX relative strength lowers confidence');
  assert(calibrateMarketConfidence(input({ asset:'eur_usd', warnings:['weighted_snapshot_metadata_limited'] })).finalConfidence < clean.finalConfidence, 'weighted snapshot metadata limitation lowers confidence');
  assert(calibrateMarketConfidence(input({ asset:'dxy', options:{ fxDiagnosticPath:true, providerReliabilitySupplied:true, sourceIndependenceVerified:true, priceReactionAvailable:true } })).confidenceTier !== 'very_high', 'DXY diagnostic-limited path cannot reach very high');
  const unverified = calibrateMarketConfidence(input({ warnings:['source_independence_unverified'] })); const duplicate = calibrateMarketConfidence(input({ warnings:['source_independence_unverified','duplicate_source_risk'], reasonCodes:['source_disagreement_detected'] }));
  assert(duplicate.finalConfidence < unverified.finalConfidence - 8 && clean.finalConfidence - unverified.finalConfidence <= 5, 'duplicate/source disagreement is stronger than mild source independence caveat');
  assert(calibrateMarketConfidence(input({ freshness:40 })).finalConfidence < clean.finalConfidence, 'stale evidence lowers confidence');
  assert(calibrateMarketConfidence(input({ warnings:['stale_evidence_conflict'] })).finalConfidence < clean.finalConfidence, 'stale/fresh conflict lowers confidence');
  assert(calibrateMarketConfidence(input({ warnings:['provider_activation_gap'] })).confidenceTier === 'medium', 'provider activation gap lowers and caps confidence');
  assert(clean.boosts.length > 0, 'high quality/fresh/broad evidence can modestly improve when severe penalties are absent');
  assert(severe.finalConfidence >= 0 && clean.finalConfidence <= 100, 'confidence never goes below 0 or above 100');
  const cleanWeighted = snapshot([item('risk','risk_sentiment','bullish'), item('liq','liquidity_conditions','bullish'), item('macro','economic_indicator','bullish')]);
  const cognition = buildMarketCognitionSnapshot(cleanWeighted);
  assert(cognition.confidence.rationale.includes('C6-R6 deterministic calibration'), 'market cognition uses calibrated final confidence');
  const contradictory = snapshot([item('risk','risk_sentiment','bullish'), item('credit','credit_stress','bullish')]);
  assert(buildMarketCognitionSnapshot(contradictory).confidence.conflictPenalty > 0 && buildMarketCognitionSnapshot(contradictory).confidence.finalConfidence < 80, 'expanded contradiction matrix severity affects final confidence');
  const unverifiedOnly = snapshot([item('risk','risk_sentiment','bullish'), item('liq','liquidity_conditions','bullish')]);
  const duplicateBurst = snapshot([item('dup1','market_news','bullish',['duplicate headline']), item('dup2','market_news','bullish',['scraped duplicate']), item('dup3','market_news','bullish',['same headline burst'])]);
  assert(buildMarketCognitionSnapshot(duplicateBurst).confidence.finalConfidence < buildMarketCognitionSnapshot(unverifiedOnly).confidence.finalConfidence, 'duplicate burst/source disagreement stronger than unverified warning alone');
  assert(validateMarketConfidenceCalibrationResult(calibrateConfidenceFromWeightedSnapshot(cleanWeighted)).ok, 'existing cognition confidence calibration result schema validates');
  const boundary = new CanonicalMarketIntelligenceBoundaryService(new MemoryMarketEvidenceRegistrySnapshotRepository(), new MemorySeoContentArchitectureSnapshotRepository());
  assert(boundary.getMarketConfidenceCalibrationCoverageReport(at).pending.empiricalBacktesting, 'canonical boundary exposes calibration methods');
}
