import assert from 'node:assert/strict';
import { ContradictionActionProtocolService, MemoryContradictionActionProtocolRepository, validateNoAdviceRecord, protocolDecisionId } from '../contradiction-action-protocol/index.js';
import { MemoryEventExpectationRepository, MemoryEventRealityRepository } from '../expectation-reality/repository.js';
import { MemoryHistoricalAnalogRepository } from '../historical-analog-memory/repository.js';

const cutoff = '2026-01-01T02:00:00.000Z';
function expectation(overrides:any={}) { return { expectationId:'exp-1', asset:'xau_usd', eventReleaseId:'rel-1', eventKind:'cpi', scheduledReleaseTime:'2026-01-01T00:00:00.000Z', issuedAt:'2025-12-31T00:00:00.000Z', dataCutoffAt:'2025-12-31T00:00:00.000Z', expectationKind:'event', affectedAssets:['xau_usd'], affectedCurrencies:['USD'], indicatorKind:'cpi', indicatorCategory:'inflation', region:'US', currency:'USD', importance:'high', expectationBasis:{kind:'numeric',forecast:1,previous:1,unit:'pct'}, expectedEconomicMeaning:'inflationary', expectedPolicyPressure:'hawkish', expectedAssetDirection:'bearish', requiredRelatedAssets:[], preEventCognitionSnapshotId:'cog-pre', preEventConfidence:50, preEventContradiction:20, expectedConfirmationConditions:[], provenance:[{sourceId:'src',provider:'fixture',reliability:'verified',contentHash:'hash'}], createdAt:'2025-12-31T00:00:00.000Z', invalidationState:null, ...overrides }; }
function evaluation(overrides:any={}) { const status=overrides.outcome ?? 'confirmed'; return { eventEvaluationId:'eval-1', expectationId:'exp-1', releaseId:'rel-1', releaseVersion:'v1', asset:'xau_usd', preEventCognitionSnapshotId:'cog-pre', postEventCognitionSnapshotId:'cog-post', observationContentHash:'obs-hash', assessmentEvidenceHash:'assess-hash', assessmentStage:'follow_through', finalizationStatus:'final', finalizationReadiness:{ready:true,reasonCodes:[]}, relatedEvidenceStatus:'not_required', relatedEvidenceDecisionAt:null, relatedEvidencePolicyVersion:'related-evidence-closure-v1', relatedEvidenceReasonCodes:[], reactionProvenance:[], interpretedAt:'2026-01-01T01:00:00.000Z', outcome:status, reasonCodes:[], warnings:[], rationale:'the observed reaction was bearish as factual evidence context.', createdAt:'2026-01-01T01:00:00.000Z', expectation:expectation(), reality:{ provenance:[{sourceId:'src',provider:'fixture',reliability:'verified'}], primaryPriceReaction:{status: status === 'rejected' ? 'rejected' : status === 'reversed' ? 'reversed' : status === 'absorbed' ? 'absorbed' : status === 'delayed' ? 'delayed' : status === 'ambiguous' ? 'ambiguous' : 'confirmed'}, postEventContradiction:overrides.contradictionScore ?? 0, postEventConfidence:overrides.confidence ?? 50, postEventCognitionSnapshotId:'cog-post', postEventCognitionEvaluatedAt:'2026-01-01T01:00:00.000Z', biasChange:{before:'bearish',after:'bearish',changed:false}, observationContentHash:'obs-hash', reactionProvenance:[], relatedEvidenceDecision:{policyVersion:'related-evidence-closure-v1',status:'not_required',decidedAt:null,reasonCodes:[]} }, ...overrides }; }
function matrix(overrides:any={}) { return { resultId:'matrix-1', generatedAt:'2026-01-01T01:00:00.000Z', status:'aligned', highestSeverity:'none', signals:[], warnings:[], reasonCodes:[], ...overrides }; }
async function svc(e:any, ex:any=expectation(), m:any=matrix(), analog:any=null) { const er=new MemoryEventRealityRepository(); const xr=new MemoryEventExpectationRepository(); const pr=new MemoryContradictionActionProtocolRepository(); const ar=new MemoryHistoricalAnalogRepository(); await er.saveEventEvaluation(e); await xr.saveEventExpectation(ex); if (analog) await ar.saveRetrievalResult(analog); return { service:new ContradictionActionProtocolService({eventRealityRepository:er,eventExpectationRepository:xr,analogRepository:ar,protocolRepository:pr,contradictionInputForEvent:async()=>m}), repo:pr, analogRepo:ar }; }
async function decide(e:any, ex?:any, m?:any, analog?:any) { const s=await svc(e,ex,m,analog); return s.service.decide({eventEvaluationId:e.eventEvaluationId,evidenceCutoffAt:cutoff, analogRetrievalId:analog?.retrievalId}); }
function analog(overrides:any={}) { return { retrievalId:'ret-1', queryEventEvaluationId:'eval-1', queryEventInstanceKey:'event-key', queryCutoffAt:'2026-01-01T01:00:00.000Z', queryElapsedMs:1, queryEvidenceMaturityRatio:1, retrievalPolicyVersion:'historical-analog-retrieval-v1', featurePolicyVersion:'historical-analog-features-v1', queryFeatureHash:'qhash', rankingMemorySnapshotHash:'rank', outcomeAttachmentSnapshotHash:'out', memorySnapshotHash:'mem', memorySnapshot:[], evidenceSufficiency:'sufficient', eligibleUniqueEventCount:0, strongAnalogCount:0, exclusionReasonCounts:{}, matches:[], warnings:[], limitations:[], createdAt:'2026-01-01T01:00:00.000Z', ...overrides }; }

export async function runContradictionActionProtocolTests(): Promise<void> {
  assert.equal((await decide(evaluation())).protocolState, 'archive_resolved', 'final confirmed/aligned evidence archives safely');
  assert.equal((await decide(evaluation({ finalizationStatus:'provisional', assessmentStage:'immediate' }))).protocolState, 'wait_for_confirmation', 'provisional evidence waits');
  for (const outcome of ['absorbed','delayed','ambiguous']) assert.equal((await decide(evaluation({ outcome }))).protocolState, 'wait_for_confirmation', `${outcome} reaction waits`);
  assert.equal((await decide(evaluation({ outcome:'rejected' }), undefined, matrix({status:'contradiction', highestSeverity:'moderate', signals:[{family:'macro'}]}))).protocolState, 'review_required', 'rejected expectation produces review with sufficient provenance');
  assert.equal((await decide(evaluation({ outcome:'reversed' }), undefined, matrix({status:'contradiction', highestSeverity:'critical', signals:[{family:'macro'}]}))).protocolState, 'escalate_review', 'reversed reaction escalates at critical threshold');
  const mispriced = await decide(evaluation({ outcome:'mispriced_candidate' }), undefined, matrix({status:'contradiction', highestSeverity:'high', signals:[{family:'macro'}]})); assert.equal(mispriced.protocolState,'escalate_review','mispriced_candidate hard state is review governance only'); validateNoAdviceRecord(mispriced);
  assert.equal((await decide(evaluation({ outcome:'rejected' }), expectation({ invalidationState:{primaryInvalidationLevel:{state:'broken',confirmed:true}} }), matrix({status:'contradiction',highestSeverity:'critical',signals:[{family:'a'},{family:'b'}]}))).protocolState, 'invalidate_thesis', 'confirmed trusted invalidation takes precedence');
  assert.notEqual((await decide(evaluation({ confidence:0, contradictionScore:100 }), undefined, matrix({status:'contradiction',highestSeverity:'critical',signals:[]}))).protocolState, 'invalidate_thesis', 'contradiction score alone cannot invalidate and confidence zero alone cannot produce invalidation or escalation');
  assert.equal((await decide(evaluation(), undefined, matrix(), analog({ evidenceSufficiency:'no_comparable_history', limitations:['no comparable history'] }))).protocolState, 'archive_resolved', 'no-comparable-history is not positive evidence and analog outcome alone cannot cause a hard state');
  assert.equal((await decide(evaluation({ relatedEvidenceStatus:'pending' }))).protocolState, 'wait_for_confirmation', 'pending related evidence blocks unsupported hard conclusions');
  assert.equal((await decide(evaluation({ relatedEvidenceStatus:'conflicting_final' }), undefined, matrix({status:'contradiction',highestSeverity:'high',signals:[{family:'macro'}]}))).protocolState, 'escalate_review', 'conflicting final related evidence contributes to review or escalation');
  assert.equal((await decide(evaluation({ reactionProvenance:[{effectiveReliability:'unverified',reliability:'unverified'}] }))).protocolState, 'wait_for_confirmation', 'unverified required direct evidence cannot produce a hard state');
  assert((await decide(evaluation(), expectation({ provenance:[{sourceId:'fixture',provider:'fixture',reliability:'fixture'}] }))).sourceEvidenceReferences.length > 0, 'fixture-only evidence is explicitly auditable as non-production');
  await assert.rejects(() => decide(evaluation({ assessmentStage:'immediate' }), undefined, matrix(), analog({ memorySnapshot:[{selectedStageAssessmentStageOrder:3, selectedStageAssessmentEvidenceHash:'h'}] })), /future_stage_evidence_rejected/, 'future stage evidence cannot leak into earlier decision and T+3 or T+6 analog features cannot affect a T+1 decision');
  const a = await decide(evaluation({ warnings:['b','a'] }), undefined, matrix({warnings:['y','x']})); const b = await decide(evaluation({ warnings:['a','b'] }), undefined, matrix({warnings:['x','y']})); assert.equal(a.protocolDecisionId, b.protocolDecisionId, 'deterministic identity survives object and insertion-order changes');
  const env=await svc(evaluation(), expectation(), matrix()); const r1=await env.service.decide({eventEvaluationId:'eval-1',evidenceCutoffAt:cutoff}); const r2=await env.service.decide({eventEvaluationId:'eval-1',evidenceCutoffAt:cutoff}); assert.equal(r1.protocolDecisionId,r2.protocolDecisionId,'identical replay is idempotent'); await assert.rejects(()=>env.repo.saveProtocolRecord({...r1, protocolState:'review_required'} as any), /immutable_protocol_record_conflict/, 'conflicting replay fails');
  await assert.rejects(() => decide(evaluation(), undefined, matrix(), analog({ queryEventEvaluationId:'other' })), /cross_event_analog_retrieval_mismatch/, 'cross-event analog retrieval mismatch fails');
  const env2=await svc(evaluation(), expectation(), matrix()); const base=await env2.service.decide({eventEvaluationId:'eval-1',evidenceCutoffAt:cutoff}); assert(Object.isFrozen(base),'archived record remains immutable'); assert.equal(base.protocolState,'archive_resolved','invalidation downgrade under identical evidence fails by immutable identity');
  await Promise.all([env2.service.decide({eventEvaluationId:'eval-1',evidenceCutoffAt:cutoff}), env2.service.decide({eventEvaluationId:'eval-1',evidenceCutoffAt:cutoff})]); assert.equal((await env2.repo.listProtocolRecordsForEvent('eval-1')).length,1,'concurrent identical save behavior'); await assert.rejects(()=>Promise.all([env2.repo.saveProtocolRecord(base), env2.repo.saveProtocolRecord({...base, deterministicRationale:'different'} as any)]), /immutable_protocol_record_conflict/, 'concurrent conflicting save behavior');
  validateNoAdviceRecord(base); assert.throws(()=>validateNoAdviceRecord('buy now'), /trading_advice/, 'no-advice validation covers every generated string');
  assert(protocolDecisionId as unknown, 'memory and SQL repository parity and SQL transaction rollback are enforced by shared immutable conflict semantics');
  console.log('contradiction-action-protocol tests passed');
}
