import { validateNormalizedMarketEvidencePayload } from '@elceo/schemas';
import type { ProviderSourceRequest } from '@elceo/types';
import { getProviderDescriptor } from '../provider-sources/provider-capability-registry.js';
import { CFTC_LEGACY_MARKET_CODES, COT_FIXTURES, CftcCotAdapter, buildCotPositioningPayload, deriveNetNonCommercial, derivePositioningSentiment, mapAssetToCotMarket } from '../provider-sources/cot/index.js';

const req=(o:Partial<ProviderSourceRequest>={}):ProviderSourceRequest=>({requestId:'req-cot-1',providerId:'cftc_cot',capability:'cot_report',asset:'xau_usd',region:'united_states',evidenceTypeId:'cot_positioning',requestedAt:'2026-04-01T00:00:00.000Z',paramsJson:'{}',...o});
export async function runCotAdapterTests():Promise<void>{
 const a=new CftcCotAdapter(); const d=getProviderDescriptor('cftc_cot'); if(!d||a.descriptor.providerId!==d.providerId) throw new Error('descriptor mismatch');
 const f=await a.fetch(req()); if(f.status!=='success'||!f.rawPayloadJson) throw new Error('fixture fetch expected success');
 const u=await a.fetch(req({capability:'market_price_history'})); if(u.status!=='unsupported') throw new Error('unsupported expected');
 const p=await a.normalize(f); if(!p.length||p.some((x)=>!validateNormalizedMarketEvidencePayload(x).ok)) throw new Error('normalized payload invalid');
 const ids=await a.normalize(f); if(ids[0]?.payloadId!==p[0]?.payloadId) throw new Error('payloadId should be deterministic');
 if(mapAssetToCotMarket('eur_usd')!=='Euro FX'||mapAssetToCotMarket('gbp_usd')!=='British Pound'||mapAssetToCotMarket('usd_jpy')!=='Japanese Yen'||mapAssetToCotMarket('btc_usd')!=='Bitcoin'||mapAssetToCotMarket('nasdaq_100')!=='NASDAQ MINI'||mapAssetToCotMarket('sp500')!=='S&P 500 Consolidated'||mapAssetToCotMarket('dxy')!=='U.S. Dollar Index'||mapAssetToCotMarket('xau_usd')!=='Gold') throw new Error('asset mapping failed');
 if(CFTC_LEGACY_MARKET_CODES.nasdaq_100!=='209742'||CFTC_LEGACY_MARKET_CODES.sp500!=='13874+'||CFTC_LEGACY_MARKET_CODES.dxy!=='098662') throw new Error('canonical CFTC market code drift');
 if(Object.values(COT_FIXTURES).some((fixture)=>fixture.request.reportKind!=='legacy_futures_only')) throw new Error('fixture/live report-kind divergence');
 const legacyValues=JSON.parse(p[0]!.valuesJson) as Record<string,unknown>; if(legacyValues.nrl!==18000||legacyValues.nrs!==14000||legacyValues.orl!==null||legacyValues.ors!==null) throw new Error('legacy non-reportable semantics failed');
 let liveBody='';
 const live=new CftcCotAdapter({mode:'live_enabled',liveEnabled:true,fetchImpl:async(_input,init)=>{liveBody=String(init?.body??'');return new Response(JSON.stringify([{market_and_exchange_names:'NASDAQ MINI - CHICAGO MERCANTILE EXCHANGE',report_date_as_yyyy_mm_dd:'2026-09-08T00:00:00.000Z',cftc_contract_market_code:'209742',open_interest_all:'295151',noncomm_positions_long_all:'85927',noncomm_positions_short_all:'65032',noncomm_postions_spread_all:'8597',comm_positions_long_all:'154226',comm_positions_short_all:'195244',nonrept_positions_long_all:'46401',nonrept_positions_short_all:'26278'}]),{status:200,headers:{'Content-Type':'application/json'}});}});
 const liveFetch=await live.fetch(req({requestId:'req-cot-live-nasdaq',asset:'nasdaq_100',requestedAt:'2026-09-09T00:00:00.000Z'})); if(liveFetch.status!=='success'||!liveFetch.rawPayloadJson||!liveBody.includes("209742")) throw new Error('live CFTC canonical market query failed');
 const liveEnvelope=JSON.parse(liveFetch.rawPayloadJson) as {request?:{reportKind?:string};rows?:Array<{marketName?:string;cftcMarketCode?:string;nonReportableLong?:number;otherReportablesLong?:number|null}>}; if(liveEnvelope.request?.reportKind!=='legacy_futures_only'||liveEnvelope.rows?.[0]?.marketName!=='NASDAQ MINI - CHICAGO MERCANTILE EXCHANGE'||liveEnvelope.rows?.[0]?.cftcMarketCode!=='209742'||liveEnvelope.rows?.[0]?.nonReportableLong!==46401||liveEnvelope.rows?.[0]?.otherReportablesLong!==null) throw new Error('live CFTC legacy semantics failed');
 const liveNormalized=await live.normalize(liveFetch); const liveValues=JSON.parse(liveNormalized[0]!.valuesJson) as Record<string,unknown>; if(liveValues.nrl!==46401||liveValues.nrs!==26278||liveValues.orl!==null||liveValues.ors!==null) throw new Error('live CFTC normalized non-reportable semantics failed');
 if(deriveNetNonCommercial({reportDate:'2026-01-01T00:00:00.000Z',marketName:'m',cftcMarketCode:null,exchangeName:null,asset:null,openInterest:1,commercialLong:null,commercialShort:null,nonCommercialLong:9,nonCommercialShort:4,nonCommercialSpreading:null,dealerLong:null,dealerShort:null,assetManagerLong:null,assetManagerShort:null,leveragedFundsLong:null,leveragedFundsShort:null,otherReportablesLong:null,otherReportablesShort:null})!==5) throw new Error('net derivation failed');
 if(derivePositioningSentiment({reportDate:'2026-01-01T00:00:00.000Z',marketName:'m',cftcMarketCode:null,exchangeName:null,asset:null,openInterest:1,commercialLong:null,commercialShort:null,nonCommercialLong:null,nonCommercialShort:null,nonCommercialSpreading:null,dealerLong:null,dealerShort:null,assetManagerLong:null,assetManagerShort:null,leveragedFundsLong:2,leveragedFundsShort:5,otherReportablesLong:null,otherReportablesShort:null})!=='bearish') throw new Error('sentiment fallback failed');
 let malformed=false; try{await a.normalize({...f,rawPayloadJson:'{"bad":true}'})}catch(e){malformed=(e as Error).message==='cot_malformed_payload';} if(!malformed) throw new Error('malformed should fail');
 let invalid=false; try{buildCotPositioningPayload({asset:'xau_usd',reportKind:'legacy_futures_only',requestedAt:'2026-01-01T00:00:00.000Z',region:'united_states'},{reportDate:'2026-01-01T00:00:00.000Z',marketName:'Gold',cftcMarketCode:null,exchangeName:null,asset:'xau_usd',openInterest:-1,commercialLong:null,commercialShort:null,nonCommercialLong:null,nonCommercialShort:null,nonCommercialSpreading:null,dealerLong:null,dealerShort:null,assetManagerLong:null,assetManagerShort:null,leveragedFundsLong:null,leveragedFundsShort:null,otherReportablesLong:null,otherReportablesShort:null})}catch(e){invalid=(e as Error).message==='cot_invalid_open_interest';} if(!invalid) throw new Error('open interest validation failed');
 const partial=buildCotPositioningPayload({asset:'btc_usd',reportKind:'traders_in_financial_futures',requestedAt:'2026-01-01T00:00:00.000Z',region:'united_states'},{reportDate:'2026-01-01T00:00:00.000Z',marketName:'Bitcoin',cftcMarketCode:null,exchangeName:null,asset:'btc_usd',openInterest:1,commercialLong:null,commercialShort:null,nonCommercialLong:null,nonCommercialShort:null,nonCommercialSpreading:null,dealerLong:null,dealerShort:null,assetManagerLong:1,assetManagerShort:1,leveragedFundsLong:2,leveragedFundsShort:3,otherReportablesLong:null,otherReportablesShort:null});
 if(partial.dataQuality!=='partial') throw new Error('partial data quality expected');
 const base={reportDate:'2026-01-01T00:00:00.000Z',marketName:'Market',cftcMarketCode:'code',exchangeName:'CME',asset:'xau_usd',openInterest:100,commercialLong:null,commercialShort:null,nonCommercialLong:null,nonCommercialShort:null,nonCommercialSpreading:null,dealerLong:null,dealerShort:null,assetManagerLong:null,assetManagerShort:null,leveragedFundsLong:null,leveragedFundsShort:null,otherReportablesLong:10,otherReportablesShort:9};
 const disaggregated=buildCotPositioningPayload({asset:'xau_usd',reportKind:'disaggregated',requestedAt:'2026-01-02T00:00:00.000Z',region:'united_states'},{...base,producerMerchantLong:20,producerMerchantShort:21,swapDealerLong:15,swapDealerShort:16,swapDealerSpreading:2,managedMoneyLong:30,managedMoneyShort:20,managedMoneySpreading:3,otherReportablesSpreading:1});if(disaggregated.dataQuality!=='high'||!disaggregated.metadataJson.includes('bullish'))throw new Error('disaggregated report-kind semantics failed');
 const tff=buildCotPositioningPayload({asset:'xau_usd',reportKind:'traders_in_financial_futures',requestedAt:'2026-01-02T00:00:00.000Z',region:'united_states'},{...base,dealerLong:20,dealerShort:21,assetManagerLong:30,assetManagerShort:22,leveragedFundsLong:15,leveragedFundsShort:25});if(tff.dataQuality!=='high'||!tff.metadataJson.includes('bearish'))throw new Error('TFF report-kind semantics failed');
}
