import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import type { RedisClientType } from 'redis';
import { CANONICAL_DASHBOARD_DISPLAY_VERSION,CANONICAL_DASHBOARD_POLICY_VERSION,CANONICAL_DASHBOARD_PROJECTION_VERSION,CANONICAL_DASHBOARD_ZONE_RULE_VERSION,type CanonicalDashboardProjection } from '@elceo/chart-intelligence';
import { LAUNCH_ASSET_SYMBOLS } from '@elceo/types';
import { buildArtifactIntegrityHash,buildDashboardProjectionArtifactIdentity,buildDashboardProjectionCoordinationHash,buildMaterializationScopeHash,createProductionCanonicalDashboardProjectionReader,type AdaptiveOwnershipStore,type CanonicalArtifact,type DashboardProjectionArtifact,type ImmutableMaterializationStore } from '../adaptive-materialization/index.js';

type Row={artifact_json:string;count?:string};type Pool={query(sql:string,params?:unknown[]):Promise<{rows:Row[]}>};
type Counters={providerExecutions:number;providerGateExecutions:number;schedulerExecutions:number;cognitionComputations:number;projectionComputations:number};
type Input={client:RedisClientType;sqlPool:Pool;namespace:string;ownership:AdaptiveOwnershipStore;immutable:ImmutableMaterializationStore;template:DashboardProjectionArtifact<CanonicalDashboardProjection>;counters:()=>Counters};
const versions={projectionVersion:CANONICAL_DASHBOARD_PROJECTION_VERSION,displayVersion:CANONICAL_DASHBOARD_DISPLAY_VERSION,zoneRuleVersion:CANONICAL_DASHBOARD_ZONE_RULE_VERSION,productPolicyVersion:CANONICAL_DASHBOARD_POLICY_VERSION};
const scope=(asset:string)=>buildMaterializationScopeHash({asset,horizon:'intraday',kind:'dashboard_projection',timeframe:'H4',...versions});
const coordination=(asset:string)=>buildDashboardProjectionCoordinationHash({asset,horizon:'intraday',timeframe:'H4',...versions});
const withIntegrity=<T extends CanonicalArtifact<unknown>>(artifact:T):T=>{const{integrityHash:_,...body}=artifact;void _;return{...body,integrityHash:buildArtifactIntegrityHash(body)} as T};
const fixture=(base:DashboardProjectionArtifact<CanonicalDashboardProjection>,asset:string,tag:string,overrides:Record<string,unknown>={})=>{const projectionIdentity=`d1c:${tag}:${asset}`,evaluatedAt=new Date(Date.now()-1000).toISOString(),payload={...base.payload,projection_identity:projectionIdentity,evaluated_at:evaluatedAt,workspace:{...base.payload.workspace,dashboard:{...base.payload.workspace.dashboard,asset_code:asset}}},lineage={projectionIdentity,schemaVersion:'canonical_materialization_v1'as const,parentCognitionArtifactIdentity:base.parentCognitionArtifactIdentity,parentCognitionIntegrityHash:base.parentCognitionIntegrityHash,orderedCandleObservationIds:base.orderedCandleObservationIds,orderedCandleContentHashes:base.orderedCandleContentHashes,freshnessPolicyVersion:base.freshnessPolicyVersion},body={...base,identity:buildDashboardProjectionArtifactIdentity(lineage),scopeHash:scope(asset),asset,projectionIdentity,payload,evaluatedAt,generatedAt:evaluatedAt,freshUntil:new Date(Date.now()+60_000).toISOString(),...overrides};return withIntegrity(body as DashboardProjectionArtifact<CanonicalDashboardProjection>)};
const redisSnapshot=async(client:RedisClientType,namespace:string)=>{const keys=(await client.keys(`${namespace}:*`)).sort(),values:Record<string,string>={};for(const key of keys){const kind=await client.type(key);values[key]=kind==='string'?(await client.get(key))??'':kind==='hash'?JSON.stringify(await client.hGetAll(key)):kind;}return{keys,values}};
async function publish(input:Input,artifact:DashboardProjectionArtifact<CanonicalDashboardProjection>,targetAsset=artifact.asset){const job=coordination(targetAsset),owner=`d1c-fixture:${randomUUID()}`,acquired=await input.ownership.acquireMaterialization(job,`fixture:${artifact.identity}`,owner,10_000);assert.ok(acquired.acquired);if(!acquired.acquired)throw new Error('fixture_lease_unavailable');await input.immutable.saveImmutable(artifact);assert.equal(await input.ownership.publishCurrent(acquired.lease,scope(targetAsset),artifact.identity),true);await input.ownership.release(acquired.lease)}
const reader=(input:Input,client=input.client,namespace=input.namespace)=>createProductionCanonicalDashboardProjectionReader({redisClient:client,sqlPool:input.sqlPool,cacheLimits:{maxEntries:12,maxSerializedBytes:4_000_000},namespace});

/** Dedicated D1-C acceptance. All mutation below is producer/test setup, never consumer behavior. */
export async function runD1cPassiveConsumerIntegration(input:Input){
 if(process.env.D1C_PASSIVE_CONSUMER_INTEGRATION!=='1')return;
 const artifacts=new Map<string,DashboardProjectionArtifact<CanonicalDashboardProjection>>();for(const asset of LAUNCH_ASSET_SYMBOLS){const artifact=fixture(input.template,asset,`launch:${randomUUID()}`);await publish(input,artifact);artifacts.set(asset,artifact)}
 const passive=reader(input);for(const asset of LAUNCH_ASSET_SYMBOLS){const result=await passive.read(asset,'intraday','H4'),expected=artifacts.get(asset)!;assert.equal(result.state,'available');assert.equal(result.artifact?.identity,expected.identity);assert.equal((result.artifact as DashboardProjectionArtifact<CanonicalDashboardProjection>|null)?.asset,asset);assert.equal(result.artifact?.scopeHash,scope(asset));assert.equal(result.artifact?.payload.workspace.dashboard.asset_code,asset);assert.equal(await input.ownership.readCurrentIdentity(coordination(asset),scope(asset)),expected.identity)}
 const a=artifacts.get('XAU/USD')!,beforeA=await passive.read('XAU/USD','intraday','H4');assert.equal(beforeA.artifact?.identity,a.identity);const b=fixture(input.template,'XAU/USD',`transition-b:${randomUUID()}`,{orderedCandleObservationIds:[...a.orderedCandleObservationIds,'transition-b'],orderedCandleContentHashes:[...a.orderedCandleContentHashes,'sha256:transition-b']});b.payload.ordered_candle_observation_ids=[...b.orderedCandleObservationIds];b.payload.ordered_candle_content_hashes=[...b.orderedCandleContentHashes];const correctedB=withIntegrity({...b,identity:buildDashboardProjectionArtifactIdentity({projectionIdentity:b.projectionIdentity,schemaVersion:b.schemaVersion,parentCognitionArtifactIdentity:b.parentCognitionArtifactIdentity,parentCognitionIntegrityHash:b.parentCognitionIntegrityHash,orderedCandleObservationIds:b.orderedCandleObservationIds,orderedCandleContentHashes:b.orderedCandleContentHashes,freshnessPolicyVersion:b.freshnessPolicyVersion})});await publish(input,correctedB);assert.notEqual(a.identity,correctedB.identity);const afterB=await passive.read('XAU/USD','intraday','H4');assert.equal(afterB.artifact?.identity,correctedB.identity);assert.deepEqual(afterB.artifact?.payload,correctedB.payload);assert.equal(await input.ownership.readCurrentIdentity(coordination('XAU/USD'),scope('XAU/USD')),correctedB.identity);
 const before={counters:input.counters(),materializations:Number((await input.sqlPool.query('SELECT count(*)::text AS count FROM app_canonical_materializations')).rows[0]?.count),ingestion:Number((await input.sqlPool.query("SELECT count(*)::text AS count FROM app_ingestion_runs WHERE request_key LIKE 'd1b-%'")).rows[0]?.count),redis:await redisSnapshot(input.client,input.namespace),pointer:await input.ownership.readCurrentIdentity(coordination('XAU/USD'),scope('XAU/USD'))};const cold=reader(input),reads=await Promise.all(Array.from({length:1000},()=>cold.read('XAU/USD','intraday','H4')));assert.ok(reads.every(x=>x.state==='available'&&x.artifact?.identity===correctedB.identity));const after={counters:input.counters(),materializations:Number((await input.sqlPool.query('SELECT count(*)::text AS count FROM app_canonical_materializations')).rows[0]?.count),ingestion:Number((await input.sqlPool.query("SELECT count(*)::text AS count FROM app_ingestion_runs WHERE request_key LIKE 'd1b-%'")).rows[0]?.count),redis:await redisSnapshot(input.client,input.namespace),pointer:await input.ownership.readCurrentIdentity(coordination('XAU/USD'),scope('XAU/USD'))};assert.deepEqual(after,before);assert.equal(cold.metrics.postgresReads,1);assert.equal(cold.metrics.cacheEntries,1);assert.ok(cold.metrics.cacheBytes<=4_000_000);
 const noPointer=await reader(input,input.client,`${input.namespace}:no-pointer`).read('XAU/USD','intraday','H4');assert.equal(noPointer.state,'unavailable');const missing=fixture(input.template,'XAU/USD',`missing:${randomUUID()}`);const lease=await input.ownership.acquireMaterialization(coordination('XAU/USD'),`missing:${randomUUID()}`,randomUUID(),10_000);assert.ok(lease.acquired);if(lease.acquired){await input.ownership.publishCurrent(lease.lease,missing.scopeHash,missing.identity);await input.ownership.release(lease.lease)}assert.equal((await reader(input).read('XAU/USD','intraday','H4')).state,'unavailable');
 const cases:Array<[string,(x:DashboardProjectionArtifact<CanonicalDashboardProjection>)=>void,'unavailable'|'stale']>=[['tampered',x=>{x.integrityHash='sha256:tampered'},'unavailable'],['wrong-kind',x=>{(x as unknown as{kind:string}).kind='cognition'},'unavailable'],['wrong-scope',x=>{x.scopeHash='wrong'},'unavailable'],['wrong-asset',x=>{x.asset='BTC/USD'},'unavailable'],['wrong-horizon',x=>{x.horizon='swing'},'unavailable'],['wrong-timeframe',x=>{x.timeframe='H1' as 'H4'},'unavailable'],['projection-version',x=>{x.projectionVersion='wrong'},'unavailable'],['display-version',x=>{x.dashboardDisplayContractVersion='wrong'},'unavailable'],['zone-version',x=>{x.chartZoneRuleVersion='wrong'},'unavailable'],['policy-version',x=>{x.dashboardProductPolicyVersion='wrong'},'unavailable'],['freshness-version',x=>{x.freshnessPolicyVersion='wrong'},'unavailable'],['projection-payload',x=>{x.payload.projection_identity='wrong'},'unavailable'],['payload-version',x=>{x.payload.projection_version='wrong' as typeof x.payload.projection_version},'unavailable'],['evaluated-at',x=>{x.payload.evaluated_at='2020-01-01T00:00:00.000Z'},'unavailable'],['payload-asset',x=>{x.payload.workspace.dashboard.asset_code='BTC/USD'},'unavailable'],['payload-display',x=>{(x.payload.workspace.dashboard as {contract_version:string}).contract_version='wrong'},'unavailable'],['candle-ids',x=>{x.payload.ordered_candle_observation_ids=['wrong']},'unavailable'],['candle-hashes',x=>{x.payload.ordered_candle_content_hashes=['wrong']},'unavailable'],['cognition-lineage',x=>{x.parentCognitionArtifactIdentity=''},'unavailable'],['materialization-identity',x=>{x.identity=`dashboard-projection:wrong-${randomUUID()}`},'unavailable'],['stale',x=>{x.freshUntil='2020-01-01T00:00:00.000Z'},'stale'],['future-generated',x=>{x.generatedAt=new Date(Date.now()+60_000).toISOString()},'unavailable'],['future-evaluated',x=>{x.evaluatedAt=new Date(Date.now()+60_000).toISOString();x.payload.evaluated_at=x.evaluatedAt},'unavailable']];
 for(const[name,mutate,state]of cases){const artifact=fixture(input.template,'XAU/USD',`${name}:${randomUUID()}`);mutate(artifact);if(name!=='tampered'){const valid=withIntegrity(artifact);Object.assign(artifact,valid)}await publish(input,artifact,'XAU/USD');assert.equal((await reader(input).read('XAU/USD','intraday','H4')).state,state,name)}
 const failingRedis=new Proxy(input.client as object,{get(target,key){if(key==='get'||key==='connect'||key==='sendCommand')return()=>Promise.reject(new Error('redis unavailable'));const value=Reflect.get(target,key,input.client);return typeof value==='function'?value.bind(input.client):value}}) as RedisClientType;assert.equal((await reader(input,failingRedis).read('XAU/USD','intraday','H4')).state,'unavailable');
 console.log(`D1-C closure passed assets=${LAUNCH_ASSET_SYMBOLS.length} A=${a.identity} B=${correctedB.identity} reads=1000 pg_reads=1 l1_entries=1 matrix=${cases.length+3}`)
}
