import { strict as a } from 'node:assert';
import { validateEvidenceQualityScore } from '@elceo/schemas';
import { buildEvidenceQualityReport, deriveConflictStatus, deriveFreshnessStatus, evaluateEvidencePayloadQuality, evaluateEvidencePayloadsQuality, getFreshnessPolicyForEvidenceClass, scoreConflict, scoreFreshness } from '../evidence-quality/index.js';
import { MemoryNormalizedMarketEvidencePayloadRepository, MemoryProviderSourceRequestRepository, MemoryProviderSourceResponseRepository } from '../persistence/market-evidence-ingestion-repository';
import { MemoryMarketEvidenceRegistrySnapshotRepository, MemorySeoContentArchitectureSnapshotRepository } from '../persistence/registry-snapshot-repository';
import { CanonicalMarketIntelligenceBoundaryService } from '../runtime/canonical-market-intelligence-boundary.js';
const p=(id:string,dq:'high'|'partial'|'failed',meta='{"sourceMode":"live_provider"}',obs='2026-01-01T00:00:00.000Z',v='{"value":100}')=>({payloadId:id,evidenceTypeId:'market_price_history',evidenceClass:'cross_market_rates',providerId:'tiingo_market_data',sourceId:null,region:'global',asset:'xau_usd',observedAt:obs,publishedAt:null,normalizedAt:obs,confidenceScore:90,dataQuality:dq,valuesJson:v,metadataJson:meta});
export async function runEvidenceQualityTests(){const pol=getFreshnessPolicyForEvidenceClass('cross_market_rates'); a.equal(pol.freshWithinMinutes,15); const fs=scoreFreshness('2026-01-01T00:00:00.000Z','2026-01-01T00:10:00.000Z',pol); a.equal(deriveFreshnessStatus(fs),'fresh'); a.equal(deriveFreshnessStatus(50),'stale'); a.equal(deriveFreshnessStatus(10),'expired'); const fix=evaluateEvidencePayloadQuality(p('f1','partial','{"sourceMode":"fixture"}')); a.equal(fix.provenanceKind,'fixture'); const mal=evaluateEvidencePayloadQuality(p('m1','high','{')); a.ok(mal.reasons.includes('malformed_or_missing_metadata')); const hi=evaluateEvidencePayloadQuality(p('h1','high')); const lo=evaluateEvidencePayloadQuality(p('l1','partial','{"sourceMode":"fixture"}')); a.ok(hi.finalQualityScore>lo.finalQualityScore); const failed=evaluateEvidencePayloadQuality(p('x1','failed')); a.equal(failed.usabilityStatus,'blocked'); const c0=scoreConflict([{evidenceTypeId:'a',evidenceClass:'cross_market_rates',asset:'x',region:'global',observedAt:'2026-01-01T00:00:00.000Z',providerId:'a',valueKey:'v',numericValue:100,tolerance:1,payloadId:'1'}]); a.equal(deriveConflictStatus(c0),'none'); const cm=scoreConflict([{evidenceTypeId:'a',evidenceClass:'cross_market_rates',asset:'x',region:'global',observedAt:'2026-01-01T00:00:00.000Z',providerId:'a',valueKey:'v',numericValue:100,tolerance:1,payloadId:'1'},{evidenceTypeId:'a',evidenceClass:'cross_market_rates',asset:'x',region:'global',observedAt:'2026-01-01T00:00:00.000Z',providerId:'b',valueKey:'v',numericValue:220,tolerance:1,payloadId:'2'}]); a.equal(deriveConflictStatus(cm),'severe'); const arr=evaluateEvidencePayloadsQuality([p('a1','high'),p('a2','high','{"sourceMode":"live_provider"}','2026-01-01T00:00:00.000Z','{"value":180}')]); a.ok(arr.some(x=>x.conflictScore>0)); a.ok(validateEvidenceQualityScore(hi).ok); a.ok(!validateEvidenceQualityScore({...hi,finalQualityScore:120}).ok); const rep=buildEvidenceQualityReport([p('r1','high'),p('r2','failed')]); a.equal(rep.pass,false);
const boundary=new CanonicalMarketIntelligenceBoundaryService(new MemoryMarketEvidenceRegistrySnapshotRepository(),new MemorySeoContentArchitectureSnapshotRepository(),new MemoryProviderSourceRequestRepository(),new MemoryProviderSourceResponseRepository(),new MemoryNormalizedMarketEvidencePayloadRepository());
await boundary.persistIngestionResult({requestId:'q1',providerId:'tiingo_market_data',capability:'market_price_history',asset:'xau_usd',region:'global',evidenceTypeId:'market_price_history',requestedAt:'2026-01-01T00:00:00.000Z',paramsJson:'{}'},{requestId:'q1',providerId:'tiingo_market_data',capability:'market_price_history',status:'success',fetchedAt:'2026-01-01T00:01:00.000Z',sourceUrl:null,rawPayloadJson:'{}',errorCode:null,errorMessage:null},[p('z1','high')]);
const withQ=await boundary.listEvidencePayloadsByAssetWithQuality('xau_usd',10); a.equal(withQ.length,1);}
