import { strict as a } from 'node:assert';
import { validateAssetEvidenceWeightPolicy, validateWeightedEvidenceItem } from '@elceo/schemas';
import { MemoryMarketEvidenceRegistrySnapshotRepository, MemorySeoContentArchitectureSnapshotRepository } from '../persistence/registry-snapshot-repository';
import { MemoryNormalizedMarketEvidencePayloadRepository, MemoryProviderSourceRequestRepository, MemoryProviderSourceResponseRepository } from '../persistence/market-evidence-ingestion-repository';
import { buildWeightedEvidenceItem, buildWeightedEvidenceSnapshot, getDefaultAssetEvidenceWeightPolicies, getWeightPolicy } from '../evidence-weighting/index.js';
import { CanonicalMarketIntelligenceBoundaryService } from '../runtime/canonical-market-intelligence-boundary.js';
import { assembleReasoningEvidenceInputSnapshot, getDefaultReasoningEvidenceFilterPolicy } from '../reasoning-input/index.js';

const item=(id:string,evidenceClass='real_yields',meta='{}')=>({payloadId:id,evidenceTypeId:evidenceClass,evidenceClass:evidenceClass as never,providerId:'p',asset:'xau_usd' as const,region:'global',observedAt:'2026-01-01T00:00:00.000Z',normalizedAt:'2026-01-01T00:00:00.000Z',qualityScore:{payloadId:id,evidenceTypeId:evidenceClass,evidenceClass:evidenceClass as never,providerId:'p',asset:'xau_usd',region:'global',observedAt:'2026-01-01T00:00:00.000Z',evaluatedAt:'2026-01-01T01:00:00.000Z',provenanceKind:'live_provider' as const,sourceQualityScore:100,freshnessScore:100,completenessScore:100,conflictScore:100,finalQualityScore:80,freshnessStatus:'fresh' as const,conflictStatus:'none' as const,usabilityStatus:'usable' as const,reasons:[]},usabilityStatus:'usable' as const,freshnessStatus:'fresh' as const,conflictStatus:'none' as const,dataQuality:'high' as const,valuesJson:'{}',metadataJson:meta,reasons:[]});
export async function runEvidenceWeightingTests(){const p=getWeightPolicy('xau_usd','real_yields','intraday'); a.ok(validateAssetEvidenceWeightPolicy(p).ok); a.ok(!validateAssetEvidenceWeightPolicy({...p,baseWeight:101}).ok);
const it=buildWeightedEvidenceItem(item('1'),'xau_usd','intraday'); a.ok(it.qualityAdjustedWeight<=it.baseWeight*0.8); a.ok(it.reasons.some((r)=>r.startsWith('provider_reliability_score:'))); a.ok(validateWeightedEvidenceItem(it).ok); const low=buildWeightedEvidenceItem({...item('2'),qualityScore:{...item('2').qualityScore,finalQualityScore:20}},'xau_usd','intraday'); a.ok(low.qualityAdjustedWeight<it.qualityAdjustedWeight);
const withDir=buildWeightedEvidenceItem(item('3','risk_sentiment','{"direction":"bearish"}'),'sp500','short_term'); a.equal(withDir.direction,'bearish'); const noDir=buildWeightedEvidenceItem(item('4','risk_sentiment','{}'),'sp500','short_term'); a.equal(noDir.direction,'unknown');

const excludedItem=buildWeightedEvidenceItem(item('5','macro_calendar'),'xau_usd','intraday'); a.equal(excludedItem.role,'excluded');
const snapWithExcluded=buildWeightedEvidenceSnapshot({snapshotId:'s',generatedAt:'2026-01-01T00:00:00.000Z',asset:'xau_usd',evidenceClass:null,filterPolicy:getDefaultReasoningEvidenceFilterPolicy(),items:[item('6','real_yields'),item('7','macro_calendar')],excludedItems:[],warnings:[]},'xau_usd','intraday');
const usableFromIncluded=snapWithExcluded.items.filter((x)=>x.role!=='excluded').reduce((n,x)=>n+x.qualityAdjustedWeight,0);
a.equal(snapWithExcluded.usableWeight,usableFromIncluded);
const orderedSnap=buildWeightedEvidenceSnapshot({snapshotId:'o',generatedAt:'2026-01-01T00:00:00.000Z',asset:'xau_usd',evidenceClass:null,filterPolicy:getDefaultReasoningEvidenceFilterPolicy(),items:[{...item('z','risk_sentiment','{"direction":"bearish"}'),qualityScore:{...item('z').qualityScore,finalQualityScore:100}},{...item('a','risk_sentiment','{"direction":"bullish"}'),qualityScore:{...item('a').qualityScore,finalQualityScore:100}}],excludedItems:[],warnings:[]},'sp500','short_term');
a.equal(orderedSnap.items[0]?.payloadId,'a');

const snap=buildWeightedEvidenceSnapshot(assembleReasoningEvidenceInputSnapshot({payloads:[],generatedAt:'2026-01-01T00:00:00.000Z',filterPolicy:getDefaultReasoningEvidenceFilterPolicy()}),'xau_usd','intraday'); a.ok(snap.warnings.includes('no_usable_weighted_evidence'));
const all=getDefaultAssetEvidenceWeightPolicies(); a.equal(all.length,12*4*(new Set(all.map((x)=>x.evidenceClass)).size)); a.ok(all.every((x)=>x.rationale.length>0));
const xau=(c:string)=>getWeightPolicy('xau_usd',c as never,'short_term').baseWeight; a.ok(xau('real_yields')>=80&&xau('inflation')>=70&&xau('central_bank_policy')>=80&&xau('dollar_liquidity')>=70&&xau('precious_metals_flows')>=55);
const btc=(c:string)=>getWeightPolicy('btc_usd',c as never,'short_term').baseWeight; a.ok(btc('crypto_market_structure')>=80&&btc('dollar_liquidity')>=70&&btc('risk_sentiment')>=70);
const sp=(c:string)=>getWeightPolicy('sp500',c as never,'short_term').baseWeight; a.ok(sp('risk_sentiment')>=70&&sp('volatility_surface')>=70&&sp('equity_index_breadth')>=70&&sp('earnings_macro')>=70);
const b=new CanonicalMarketIntelligenceBoundaryService(new MemoryMarketEvidenceRegistrySnapshotRepository(),new MemorySeoContentArchitectureSnapshotRepository(),new MemoryProviderSourceRequestRepository(),new MemoryProviderSourceResponseRepository(),new MemoryNormalizedMarketEvidencePayloadRepository());
await b.persistIngestionResult({requestId:'rqw',providerId:'tiingo_market_data',capability:'market_price_history',asset:'xau_usd',region:'global',evidenceTypeId:'real_yields',requestedAt:'2026-01-01T00:00:00.000Z',paramsJson:'{}'},{requestId:'rqw',providerId:'tiingo_market_data',capability:'market_price_history',status:'success',fetchedAt:'2026-01-01T00:00:00.000Z',sourceUrl:null,rawPayloadJson:'{}',errorCode:null,errorMessage:null},[{...item('px'),sourceId:null,publishedAt:null,confidenceScore:90}]);
const ws=await b.getWeightedEvidenceByAsset('xau_usd','intraday',10,'2026-01-01T00:00:00.000Z'); a.equal(ws.asset,'xau_usd'); a.ok(!JSON.stringify(ws).includes('buy')&&!JSON.stringify(ws).includes('sell')&&!JSON.stringify(ws).includes('hold'));}
