import assert from 'node:assert/strict';
import { createMarketSessionLiquidityContext, evaluateMarketCleanliness, MemoryMarketCleanlinessRepository, buildMarketCleanlinessDistributionReport, cleanlinessId } from '../market-cleanliness/index.js';

const cutoff='2026-01-01T02:00:00.000Z';
const provenance={sourceId:'verified-source',provider:'certified-replay',reliability:'verified' as const,contentHash:'content'};
function event(overrides:any={}):any{const direction=overrides.direction??'bearish', primaryDirection=overrides.primaryDirection??direction,stage=overrides.stage??'follow_through', related=overrides.related??'confirmed';const phase=(state='confirmed')=>({state,startTimestamp:'2026-01-01T00:01:00.000Z',endTimestamp:'2026-01-01T00:10:00.000Z',requiredBarCount:3,availableBarCount:3,moveFromOriginPct:1,volatilityAdjustedMove:2,observedDirection:primaryDirection,reasonCodes:[],warnings:[]});const envelope={sourceId:'price',provider:'certified',observationVersion:'v1',reliability:'verified',effectiveReliability:'verified',trustBasis:'certified',verificationRef:'verify-price',verifiedAt:'2026-01-01T00:20:00.000Z',calculatedContentHash:'price-hash',reactionInput:{asset:'xau_usd',horizon:'intraday',eventKind:'macro_release',eventTime:'2026-01-01T00:00:00.000Z',volatilityBasisPct:1,volatilityBasis:'supplied',candles:[]}};return {eventEvaluationId:'eval-1',expectationId:'exp-1',releaseId:'release-1',releaseVersion:'v1',asset:'xau_usd',preEventCognitionSnapshotId:'pre',postEventCognitionSnapshotId:'post',observationContentHash:'obs',assessmentEvidenceHash:'assessment',assessmentStage:stage,finalizationStatus:'final',finalizationReadiness:{ready:true,reasonCodes:[]},relatedEvidenceStatus:related,relatedEvidenceDecisionAt:'2026-01-01T00:30:00.000Z',relatedEvidencePolicyVersion:'related-evidence-closure-v1',relatedEvidenceReasonCodes:[],reactionProvenance:[envelope],interpretedAt:'2026-01-01T01:00:00.000Z',outcome:overrides.outcome??'confirmed',reasonCodes:overrides.reasonCodes??[],warnings:[],rationale:'Persisted event interpretation.',createdAt:'2026-01-01T01:00:00.000Z',expectation:{expectationId:'exp-1',eventReleaseId:'release-1',eventKind:'cpi',expectedAssetDirection:overrides.expectationDirection??'bullish'},reality:{observedAt:'2026-01-01T00:00:01.000Z',provenance:[provenance],releaseAlignment:{status:overrides.releaseStatus??'contradicted',actualDirection:direction},primaryPriceReaction:{observedDirection:primaryDirection,status:overrides.primaryStatus??'confirmed',absorptionScore:0,wickRejectionScore:0,reversalScore:0,volatilityAdjustedMove:2,warnings:[],reasonCodes:[]},priceReactionTimeline:{primaryObservation:envelope,immediate:phase(),confirmation:phase(),followThrough:phase(),initialConfirmationThenReversal:overrides.reversal??false,acceptanceLostTimestamp:overrides.reversal?'2026-01-01T00:20:00.000Z':null,reversalTimestamp:overrides.reversal?'2026-01-01T00:21:00.000Z':null},relatedEvidenceDecision:{status:related,policyVersion:'related-evidence-closure-v1',reasonCodes:[]},reactionProvenance:[envelope],limitations:[]}} as never;}
function context(overrides:any={}){return createMarketSessionLiquidityContext({policyVersion:'market-cleanliness-v1',eventEvaluationId:'eval-1',asset:'xau_usd',observedAt:'2026-01-01T00:30:00.000Z',availableAt:'2026-01-01T00:31:00.000Z',evidenceCutoffAt:cutoff,marketState:'open',sessionState:'active',liquidityState:'normal',spreadState:'normal',activityState:'normal',sourceEvidenceIds:['liquidity'],provenance:[{...provenance,sourceId:'liquidity'}],warnings:[],limitations:[],...overrides} as never);}
const rank=(e:any,c:any=context())=>evaluateMarketCleanliness({event:e,analog:null,session:c,evidenceCutoffAt:cutoff});
export async function runMarketCleanlinessTests(){
 const rejection=rank(event());assert.equal(rejection.cleanlinessState,'clean','IFP4 clean rejection: bullish expectation and coherent bearish reality can be clean');assert.equal(rejection.components.length,8,'IFP4 visible components: all components remain visible');
 const confirmation=rank(event({expectationDirection:'bearish',releaseStatus:'aligned'}));assert.equal(confirmation.cleanlinessState,'clean','IFP4 clean confirmation');
 const conflict=rank(event({direction:'bullish',primaryDirection:'bearish',releaseStatus:'aligned'}));assert.equal(conflict.cleanlinessState,'conflicted','IFP4 release/primary conflict');assert(conflict.hardConflictFlags.includes('release_primary_direction_conflict'),'IFP4 hard-conflict visibility');
 const related=rank(event({direction:'bullish',primaryDirection:'bearish',releaseStatus:'aligned',related:'conflicting_final'}));assert(related.hardConflictFlags.includes('related_market_final_conflict'),'IFP4 related-market conflict');
 const reversal=rank(event({reversal:true}));assert.equal(reversal.cleanlinessState,'conflicted','confirmation followed by reversal conflicts');
 const missingRelated=rank(event({related:'pending'}));assert.notEqual(missingRelated.cleanlinessState,'clean','missing related market cannot be clean');
 const missingVolEvent:any=event();missingVolEvent.reality.priceReactionTimeline.primaryObservation.reactionInput.volatilityBasisPct=null;assert.equal(rank(missingVolEvent).cleanlinessState,'insufficient_data','IFP4 missing volatility insufficiency');
 const thin=rank(event(),context({liquidityState:'thin',spreadState:'wide'}));assert(thin.components.find(x=>x.component==='session_liquidity_quality')!.score!<60,'thin liquidity and wide spread reduce cleanliness');
 const unknown=rank(event(),context({liquidityState:'unknown'}));assert.equal(unknown.components.find(x=>x.component==='session_liquidity_quality')!.score,null,'unknown liquidity stays unavailable');
 const immediate=rank(event({stage:'immediate',related:'pending'}));assert.equal(immediate.components.find(x=>x.component==='path_continuity')!.availability,'structurally_unavailable','IFP4 stage-safe evaluation');assert.notEqual(immediate.cleanlinessState,'insufficient_data','immediate does not require future evidence');
 const fixtureContext=context({provenance:[{sourceId:'fixture',provider:'fixture',reliability:'fixture'}]});assert.notEqual(rank(event(),fixtureContext).cleanlinessState,'clean','fixture context cannot support clean');
 let late=false;try{rank({...event(),createdAt:'2026-01-02T00:00:00.000Z'});}catch{late=true;}assert(late,'IFP4 point-in-time rejection');
 const reordered={...rejection,hardConflictFlags:[...rejection.hardConflictFlags].reverse(),warnings:[...rejection.warnings].reverse()};assert.equal(cleanlinessId('proof',rejection),cleanlinessId('proof',reordered),'set-like reordering preserves identity');assert.notEqual(cleanlinessId('proof',rejection),cleanlinessId('proof',{...rejection,evidenceQualifiedScore:1}),'substantive changes alter identity');
 const memory=new MemoryMarketCleanlinessRepository();assert.equal(await memory.saveEvaluation(rejection),await memory.saveEvaluation(rejection),'IFP4 memory/SQL parity: memory identical replay');let immutable=false;try{await memory.saveEvaluation({...rejection,deterministicRationale:'changed'});}catch{immutable=true;}assert(immutable,'immutable conflict rejected');
 const report=buildMarketCleanlinessDistributionReport([rejection,conflict],'asset',cutoff);assert.equal(report.groups[0]?.sampleSize,2,'report grouping and samples');assert(!JSON.stringify([rejection,report]).match(/\b(buy|sell|hold|entry|exit|stop|target|leverage|position-sizing)\b/i),'IFP4 no-advice boundary');
 console.log('market cleanliness tests passed');
}
