import type {
  EventAssessmentStage,
  EventInterpretationOutcome,
  EventPriceTimelineState,
  EventRealityEvaluation,
  EventReactionCandle,
  ReactionObservationEnvelope,
  RelatedEvidenceStatus,
  SourceProvenance,
} from '../expectation-reality/contracts';
import type { MarketPriceReactionImpulseClass, MarketPriceReactionStatus, MarketReasoningModuleReadiness } from '@elceo/types';
import type { MarketSessionLiquidityContextDraft } from '../market-cleanliness/contracts';

export const CLEANLINESS_CUTOFF = '2026-01-01T02:00:00.000Z';
export const verifiedProvenance: SourceProvenance = { sourceId:'verified-source', provider:'certified-replay', reliability:'verified', contentHash:'content' };
export const readyPriceReaction: MarketReasoningModuleReadiness = { moduleId:'price_reaction', contractShapeStatus:'valid', deterministicFoundationStatus:'implemented', liveProviderIntegrationStatus:'not_applicable', empiricalValidationStatus:'pending', productionCalibrationStatus:'pending', notes:[] };

export type CleanlinessEventFixtureOverrides = {
  direction?: 'bullish'|'bearish'|'neutral'|'unknown';
  primaryDirection?: 'bullish'|'bearish'|'neutral'|'unknown';
  stage?: EventAssessmentStage;
  related?: RelatedEvidenceStatus;
  expectationDirection?: 'bullish'|'bearish'|'neutral';
  releaseStatus?: 'aligned'|'contradicted'|'mixed'|'inline'|'insufficient_data';
  primaryStatus?: MarketPriceReactionStatus;
  primaryConfidence?: number;
  impulseClass?: MarketPriceReactionImpulseClass;
  readiness?: MarketReasoningModuleReadiness;
  outcome?: EventInterpretationOutcome;
  reasonCodes?: string[];
  reversal?: boolean;
  releaseProvenance?: SourceProvenance[];
  primaryProvenance?: SourceProvenance;
  relatedProvenance?: SourceProvenance;
  eventEvaluationId?: string;
  expectationId?: string;
  asset?: 'xau_usd';
  interpretedAt?: string;
  immediateState?: EventPriceTimelineState;
  confirmationState?: EventPriceTimelineState;
  immediateDirection?: 'bullish'|'bearish'|'neutral'|'unknown';
  confirmationDirection?: 'bullish'|'bearish'|'neutral'|'unknown';
};

const candle=(minute:number):EventReactionCandle=>({timestamp:`2026-01-01T00:${String(minute).padStart(2,'0')}:00.000Z`,openedAt:`2026-01-01T00:${String(minute).padStart(2,'0')}:00.000Z`,closedAt:`2026-01-01T00:${String(minute+1).padStart(2,'0')}:00.000Z`,open:100,high:101,low:99,close:100,complete:true});
const envelope=(sourceId:string,asset:'xau_usd'|'dxy',provenance:SourceProvenance):ReactionObservationEnvelope=>({sourceId,provider:provenance.provider,payloadRef:null,observationVersion:'v1',suppliedContentHash:null,calculatedContentHash:`${sourceId}-hash`,reliability:provenance.reliability,...(provenance.effectiveReliability?{effectiveReliability:provenance.effectiveReliability}:{}),...(provenance.trustBasis?{trustBasis:provenance.trustBasis}:{}),...(provenance.verificationRef?{verificationRef:provenance.verificationRef}:{}),...(provenance.verifiedAt?{verifiedAt:provenance.verifiedAt}:{}),reactionInput:{asset,horizon:'intraday',eventKind:'macro_release',eventTime:'2026-01-01T00:00:00.000Z',expectedDirection:'bullish',volatilityBasisPct:1,volatilityBasis:'supplied',candles:[candle(0),candle(1),candle(2)]}});

export function buildCleanlinessEventFixture(overrides:CleanlinessEventFixtureOverrides={}):EventRealityEvaluation {
 const direction=overrides.direction??'bearish';const primaryDirection=overrides.primaryDirection??direction;const stage=overrides.stage??'follow_through';const related=overrides.related??'confirmed';const asset=overrides.asset??'xau_usd';
 const releaseProvenance=overrides.releaseProvenance??[verifiedProvenance];const primarySource=overrides.primaryProvenance??{...verifiedProvenance,sourceId:'price'};const relatedSource=overrides.relatedProvenance??{...verifiedProvenance,sourceId:'related-price'};const primaryEnvelope=envelope('price',asset,primarySource);const relatedEnvelope=envelope('related-price','dxy',relatedSource);
 const phase=(state:EventPriceTimelineState='confirmed',observedDirection:'bullish'|'bearish'|'neutral'|'unknown'=primaryDirection)=>({state,startTimestamp:'2026-01-01T00:01:00.000Z',endTimestamp:'2026-01-01T00:10:00.000Z',requiredBarCount:3,availableBarCount:3,moveFromOriginPct:observedDirection==='bearish'?-1:observedDirection==='bullish'?1:0,volatilityAdjustedMove:2,observedDirection,reasonCodes:[],warnings:[]});
 const expectationId=overrides.expectationId??'exp-1';const eventEvaluationId=overrides.eventEvaluationId??'eval-1';const releaseStatus=overrides.releaseStatus??'contradicted';const reversal=overrides.reversal??false;
 const expectation={expectationId,expectationKind:'event' as const,eventReleaseId:'release-1',eventKind:'cpi',scheduledReleaseTime:'2026-01-01T00:00:00.000Z',issuedAt:'2025-12-31T00:00:00.000Z',dataCutoffAt:'2025-12-31T00:00:00.000Z',asset,affectedAssets:[asset],affectedCurrencies:['USD'],indicatorKind:'cpi',indicatorCategory:'inflation',region:'US',currency:'USD',importance:'high' as const,expectationBasis:{kind:'numeric' as const,forecast:1,previous:1,unit:'pct'},expectedEconomicMeaning:'inflationary',expectedPolicyPressure:'hawkish',expectedAssetDirection:overrides.expectationDirection??'bullish',requiredRelatedAssets:related==='not_required'?[]:['dxy' as const],preEventCognitionSnapshotId:'pre',preEventConfidence:60,preEventContradiction:10,expectedConfirmationConditions:[],provenance:releaseProvenance,createdAt:'2025-12-31T00:00:00.000Z'};
 const decision={status:related,decidedAt:'2026-01-01T00:30:00.000Z',policyVersion:'related-evidence-closure-v1' as const,reasonCodes:[]};
 const primaryPriceReaction={reactionId:'primary-reaction',asset,horizon:'intraday' as const,eventKind:'macro_release' as const,eventTime:'2026-01-01T00:00:00.000Z',expectedDirection:expectation.expectedAssetDirection==='neutral'?'neutral' as const:expectation.expectedAssetDirection,observedDirection:primaryDirection,status:overrides.primaryStatus??(expectation.expectedAssetDirection!==primaryDirection?'rejected':'confirmed'),impulseClass:overrides.impulseClass??(primaryDirection==='neutral'?'none':'strong'),confidence:overrides.primaryConfidence??90,immediateMovePct:primaryDirection==='bearish'?-1:1,followThroughMovePct:primaryDirection==='bearish'?-1:1,volatilityAdjustedMove:2,wickRejectionScore:0,absorptionScore:0,reversalScore:reversal?90:0,windows:[],warnings:[],reasonCodes:[],rationale:'Canonical persisted primary reaction.',readiness:overrides.readiness??readyPriceReaction};
 const timeline={policyVersion:'event-price-timeline-v1' as const,primaryObservation:primaryEnvelope,immediate:phase(overrides.immediateState??'confirmed',overrides.immediateDirection??primaryDirection),confirmation:phase(overrides.confirmationState??'confirmed',overrides.confirmationDirection??primaryDirection),followThrough:phase(),laterAcceptance:phase('unknown'),initialState:'confirmed' as const,confirmationWindowState:'confirmed' as const,followThroughState:'confirmed' as const,laterAcceptanceState:'unknown' as const,reversalAbsorptionState:reversal?'reversed' as const:'none' as const,acceptanceTimestamp:'2026-01-01T00:01:00.000Z',acceptancePhase:'immediate' as const,firstAcceptanceTimestamp:'2026-01-01T00:01:00.000Z',firstAcceptancePhase:'immediate' as const,acceptanceLostTimestamp:reversal?'2026-01-01T00:20:00.000Z':null,renewedAcceptanceTimestamp:null,renewedAcceptancePhase:null,firstContradictionTimestamp:reversal?'2026-01-01T00:20:00.000Z':null,reversalTimestamp:reversal?'2026-01-01T00:21:00.000Z':null,initialRejectionThenAcceptance:false,initialConfirmationThenReversal:reversal};
 const reactionProvenance=related==='confirmed'||related==='conflicting_final'?[primaryEnvelope,relatedEnvelope]:[primaryEnvelope];
 const actualDirection=direction==='unknown'?null:direction;
 return {eventEvaluationId,expectationId,releaseId:'release-1',releaseVersion:'v1',asset,preEventCognitionSnapshotId:'pre',postEventCognitionSnapshotId:'post',observationContentHash:'obs',assessmentEvidenceHash:'assessment',assessmentStage:stage,finalizationStatus:'final',finalizationReadiness:{ready:true,reasonCodes:[]},relatedEvidenceStatus:related,relatedEvidenceDecisionAt:decision.decidedAt,relatedEvidencePolicyVersion:'related-evidence-closure-v1',relatedEvidenceReasonCodes:[],reactionProvenance,interpretedAt:overrides.interpretedAt??'2026-01-01T01:00:00.000Z',outcome:overrides.outcome??'confirmed',reasonCodes:overrides.reasonCodes??[],warnings:[],rationale:'Persisted event interpretation.',expectation,reality:{releaseAlignment:{status:releaseStatus,reasonCodes:[],economicMeaningAlignment:releaseStatus,policyPressureAlignment:releaseStatus,actualVsForecastAlignment:releaseStatus,revisionEffect:'immaterial',primaryAssetDirectionAlignment:releaseStatus,relatedMarketDirectionAlignment:releaseStatus,expectedEconomicMeaning:expectation.expectedEconomicMeaning,actualEconomicMeaning:'resolved',expectedPolicyPressure:expectation.expectedPolicyPressure,actualPolicyPressure:'resolved',expectedDirection:expectation.expectedAssetDirection,actualDirection},revisionAdjustedMeasures:{rawSurpriseDelta:1,revisionDelta:0,revisionAdjustedDelta:1,rawNormalizedSurpriseScore:50,normalizedRevisionContribution:0,revisionPolicyVersion:'event-revision-v1',revisionFamily:'inflation',revisionAdjustedDirection:direction==='bearish'?'economic_negative':direction==='bullish'?'economic_positive':direction==='neutral'?'inline':'unknown',adjustedSurpriseScore:50,adjustedEconomicMeaning:'resolved',adjustedPolicyPressure:'resolved',adjustedGrowthPressure:'resolved',adjustedInflationPressure:'resolved',adjustedRiskPressure:'resolved',revisionEffect:'immaterial',revisionAdjustedMateriality:'material',limitations:[]},priceReactionTimeline:timeline,releaseId:'release-1',releaseVersion:'v1',observedAt:'2026-01-01T00:00:01.000Z',actual:1,forecast:1,previous:1,revisedPrevious:1,normalizedSurprise:null,provenance:releaseProvenance,primaryPriceReaction,followThroughReaction:timeline.followThrough,relatedMarketReactions:[],actualAssetDirections:[{asset,resolvedDirection:direction,confidence:1,reasonCodes:[],warnings:[]}],observationContentHash:'obs',reactionProvenance,relatedMarketState:related==='confirmed'?'confirmed':related==='conflicting_final'?'conflicting':'insufficient',relatedEvidenceDecision:decision,postEventCognitionSnapshotId:'post',postEventCognitionEvaluatedAt:'2026-01-01T00:30:00.000Z',postEventConfidence:60,confidenceDelta:0,postEventContradiction:10,contradictionDelta:0,biasChange:{before:expectation.expectedAssetDirection,after:actualDirection,changed:expectation.expectedAssetDirection!==actualDirection},warnings:[],limitations:[]},createdAt:'2026-01-01T01:00:00.000Z'};
}

export function buildSessionContextDraft(overrides:Partial<MarketSessionLiquidityContextDraft>={}):MarketSessionLiquidityContextDraft{return{policyVersion:'market-cleanliness-v1',eventEvaluationId:'eval-1',asset:'xau_usd',observedAt:'2026-01-01T00:30:00.000Z',availableAt:'2026-01-01T00:31:00.000Z',evidenceCutoffAt:CLEANLINESS_CUTOFF,marketState:'open',sessionState:'active',liquidityState:'normal',spreadState:'normal',activityState:'normal',sourceEvidenceIds:['liquidity'],provenance:[{...verifiedProvenance,sourceId:'liquidity'}],warnings:[],limitations:[],...overrides};}

import type { AnalogComponentScore, HistoricalAnalogMatch, HistoricalAnalogRetrievalResult } from '../historical-analog-memory/contracts';
import type { HistoricalAnalogComponent } from '../historical-analog-memory/policy';
const analogScore=(component:HistoricalAnalogComponent):AnalogComponentScore=>({component,componentScore:90,componentWeight:1,weightedContribution:.9,featureCoverage:1,effectiveComponentWeight:1,unavailableFeatureSlices:[],reasonCodes:[],limitations:[]});
const analogScores=():HistoricalAnalogMatch['componentScores']=>({eventContext:analogScore('eventContext'),surpriseRevision:analogScore('surpriseRevision'),assetDirection:analogScore('assetDirection'),pricePath:analogScore('pricePath'),relatedMarket:analogScore('relatedMarket'),volatility:analogScore('volatility'),cognitionShift:analogScore('cognitionShift'),provenanceQuality:analogScore('provenanceQuality')});
export function buildAnalogRetrievalFixture(overrides:Partial<HistoricalAnalogRetrievalResult>={}):HistoricalAnalogRetrievalResult {
 const matches:HistoricalAnalogMatch[]=[1,2,3].map((rank)=>({rank,analogMemoryId:`memory-${rank}`,sourceEventEvaluationId:`historical-eval-${rank}`,sourceEventInstanceKey:`historical-event-${rank}`,sourceAsset:'xau_usd',sourceAssetFamily:'metals',similarityScore:90-rank,featureCoverageRatio:.9,queryEvidenceMaturityRatio:1,componentScores:analogScores(),matchedFeatureGroups:[],unavailableFeatureGroups:[],reasonCodes:[],sourceProvenanceSummary:{datasetClass:'verified',requiredEvidenceReliability:['verified'],sourceIds:[`historical-source-${rank}`],trustedReleaseWitnessSourceIds:[`historical-source-${rank}`],trustedReleaseVerificationRefs:[`verification-${rank}`],secondaryReleaseSourceIds:[],releaseTrustSatisfiedAt:'2025-01-01T00:00:00.000Z',releaseVerificationArtifacts:[],releaseEvidenceReliability:['verified'],primaryEvidenceReliability:['verified'],requiredRelatedEvidenceReliability:['verified'],optionalRelatedEvidenceReliability:[],optionalUnverifiedRelatedEvidence:false},sourceLimitations:[],historicalOutcomeContext:{usedInSimilarity:false,finalOutcome:'confirmed',finalPricePathState:'confirmed',laterAcceptanceOrReversalState:'none',finalConfidenceDelta:0,finalContradictionDelta:0,finalRelatedEvidenceState:'confirmed',finalRationale:`Historical context ${rank}.`,limitations:[]},comparisonRationale:'Similarity is persisted IFP-2 context.'}));
 const memorySnapshot=matches.map((match)=>({analogMemoryId:match.analogMemoryId,sourceEventEvaluationId:match.sourceEventEvaluationId,sourceEventInstanceKey:match.sourceEventInstanceKey,selectedStageSourceEventEvaluationId:match.sourceEventEvaluationId,selectedStageAssessmentEvidenceHash:`assessment-${match.rank}`,selectedStageObservationContentHash:`observation-${match.rank}`,selectedStageInterpretedAt:'2025-01-01T01:00:00.000Z',selectedStageElapsedMs:180000,selectedStageFinalizationStatus:'final',selectedStageAssessmentStageOrder:2,selectedStageCreatedAt:'2025-01-01T01:00:00.000Z',selectedStageProvenanceEligibility:'eligible' as const,selectedStageMatchFeatureHash:`feature-${match.rank}`,availableAt:'2025-01-01T01:01:00.000Z'}));
 return{retrievalId:'analog-sufficient',queryEventEvaluationId:'eval-1',queryEventInstanceKey:'event',queryCutoffAt:'2026-01-01T01:00:00.000Z',queryElapsedMs:180000,queryEvidenceMaturityRatio:1,retrievalPolicyVersion:'historical-analog-retrieval-v1',featurePolicyVersion:'historical-analog-features-v1',queryFeatureHash:'query',rankingMemorySnapshotHash:'rank',outcomeAttachmentSnapshotHash:'outcome',memorySnapshotHash:'memory',memorySnapshot,evidenceSufficiency:'sufficient',eligibleUniqueEventCount:3,strongAnalogCount:3,exclusionReasonCounts:{},matches,warnings:[],limitations:[],createdAt:'2026-01-01T01:00:00.000Z',...overrides};
}
