import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { Pool } from 'pg';
import { createClient,type RedisClientType } from 'redis';
import { buildArtifactIntegrityHash,buildAdaptiveJobIdentity,buildMaterializationScopeHash,createAdaptiveMaterializationPolicy,createProductionAdaptiveMaterializationRuntime,createProductionCanonicalCognitionReader,PGS4_PRODUCTION_COGNITION_CONFIGURATION,ReadOptimizedImmutableMaterializationStore,type AdaptiveMaterializationMetrics,type AdaptiveMaterializationPolicy,type CanonicalArtifact,type ImmutableMaterializationStore,type ScheduledProviderExecutor } from '../adaptive-materialization/index.js';
import { buildProviderApiGateSnapshot,resolveProviderRuntimeRequest,type ProviderRuntimeRequest } from '../provider-sources/provider-api-gate.js';
import { DASHBOARD_READ_ROUTE_FAMILY,inboundPolicyHash,RedisInboundReadAdmission,validateInboundReadPolicy,type InboundReadPolicy } from '../inbound-read/index.js';

const adaptiveMetrics=():AdaptiveMaterializationMetrics=>({scheduleEvaluations:0,jobsDue:0,leaseAcquired:0,leaseDenied:0,providerRefreshAttempted:0,providerCacheSatisfied:0,canonicalEvidencePublished:0,cognitionComputed:0,cognitionReused:0,previousMaterializationServed:0,failures:{},nextDueAt:null});
const policy=(overrides:Partial<Omit<AdaptiveMaterializationPolicy,'canonicalPolicyHash'>>={})=>createAdaptiveMaterializationPolicy({policyId:'pgs5-seed',policyVersion:'v1',status:'approved',provenance:'pgs5_real_pgs4_seed',effectiveFrom:'2020-01-01T00:00:00.000Z',effectiveTo:null,sourceId:'tiingo_market_data',capabilityId:'market_price_history',credentialPoolId:'pgs5_pool',asset:'xau_usd',region:null,horizon:'intraday',minimumRefreshIntervalMs:10,baseRefreshIntervalMs:100,maximumRefreshIntervalMs:1000,staleAfterMs:60_000,retryMinimumMs:10,retryMaximumMs:100,leaseDurationMs:500,evaluationEpochMs:1000,expectedReleaseMinuteUtc:null,...overrides});
const request=(p:AdaptiveMaterializationPolicy):ProviderRuntimeRequest=>({requestId:'pgs5-seed-request',sourceId:p.sourceId,capabilityId:p.capabilityId,asset:p.asset,region:p.region,activationMode:'staging_live_allowed',provenance:{actor:'pgs4_scheduler',purpose:'canonical_evidence_refresh'},policy:{explicitStagingLiveAllow:true,requestMetadata:{credentialPresent:true}}});
const admissionPolicy=(overrides:Partial<Omit<InboundReadPolicy,'canonicalPolicyHash'>>={}):InboundReadPolicy=>{const body:Omit<InboundReadPolicy,'canonicalPolicyHash'>={policyId:'pgs5-admission',policyVersion:'1',status:'test_only',provenance:'PGS-5 acceptance fixture',effectiveFrom:'2020-01-01T00:00:00.000Z',effectiveTo:null,routeFamily:DASHBOARD_READ_ROUTE_FAMILY,windowMs:1000,requestAllowance:20,concurrentAllowance:3,leaseMs:60,stateTtlMs:2000,...overrides};return{...body,canonicalPolicyHash:inboundPolicyHash(body)}};

export async function runProviderScaleAcceptanceTests(){
 const now=new Date().toISOString(),body={schemaVersion:'canonical_materialization_v1'as const,kind:'cognition'as const,identity:'cognition:unit',scopeHash:'scope',payload:{value:1},evidenceIdentity:'reasoning-input:unit',policyVersion:'unit',ruleVersions:['unit'],schedulerRunId:'unit',generatedAt:now,evaluatedAt:now,freshUntil:now},artifact={...body,integrityHash:buildArtifactIntegrityHash(body)};let durableReads=0;
 const durable:ImmutableMaterializationStore={saveImmutable:async()=>undefined,getImmutable:async<T>()=>{durableReads++;await new Promise(r=>setTimeout(r,2));return structuredClone(artifact) as unknown as CanonicalArtifact<T>}};const hot=new ReadOptimizedImmutableMaterializationStore(durable,{maxEntries:2,maxSerializedBytes:4096});const first=(await Promise.all(Array.from({length:100},()=>hot.getImmutable<{value:number}>('cognition:unit'))))[0]!;assert.equal(durableReads,1);assert.equal(hot.metrics.inFlightFollowers,99);assert.throws(()=>{(first!.payload as {value:number}).value=999},TypeError);assert.equal((await hot.getImmutable<{value:number}>('cognition:unit'))!.payload.value,1);assert.equal((await hot.getImmutable('cognition:unit'))!.integrityHash,artifact.integrityHash);
 const artifacts=new Map<string,CanonicalArtifact<unknown>>();for(let i=0;i<4;i++){const entryBody={...body,identity:`cognition:evict-${i}`,payload:{value:i}},entry={...entryBody,integrityHash:buildArtifactIntegrityHash(entryBody)};artifacts.set(entry.identity,entry)}const bounded=new ReadOptimizedImmutableMaterializationStore({saveImmutable:async()=>undefined,getImmutable:async<T>(id:string)=>artifacts.get(id) as CanonicalArtifact<T>??null},{maxEntries:2,maxSerializedBytes:4096});for(const id of artifacts.keys())await bounded.getImmutable(id);assert.ok(bounded.snapshot().entries<=2);assert.ok(bounded.snapshot().bytes<=4096);assert.ok(bounded.snapshot().evictions>0);
 const basePolicy=admissionPolicy();assert.equal(validateInboundReadPolicy(basePolicy,'test'),true);assert.equal(validateInboundReadPolicy(admissionPolicy({status:'disabled'}),'test'),false);assert.equal(validateInboundReadPolicy(admissionPolicy({routeFamily:'wrong'}),'test'),false);assert.equal(validateInboundReadPolicy(admissionPolicy({effectiveFrom:'not-a-date'}),'test'),false);assert.equal(validateInboundReadPolicy(admissionPolicy({effectiveFrom:'2030-01-01T00:00:00.000Z',effectiveTo:'2020-01-01T00:00:00.000Z'}),'test'),false);
 const tampered={...artifact,payload:{value:2}},invalid=new ReadOptimizedImmutableMaterializationStore({...durable,getImmutable:async<T>()=>tampered as unknown as CanonicalArtifact<T>},{maxEntries:2,maxSerializedBytes:4096});assert.equal(await invalid.getImmutable('cognition:unit'),null);assert.equal(invalid.snapshot().entries,0);
 if(process.env.PROVIDER_SCALE_ACCEPTANCE!=='1')return;if(!process.env.REDIS_URL||!process.env.DATABASE_URL)throw new Error('PGS-5 requires REDIS_URL and DATABASE_URL');
 const redisUrl=process.env.REDIS_URL,databaseUrl=process.env.DATABASE_URL,pool=new Pool({connectionString:databaseUrl}),namespace=`elceo:pgs5:${process.pid}:${Date.now()}`,clients:RedisClientType[]=[];const client=()=>{const c=createClient({url:redisUrl}) as RedisClientType;clients.push(c);return c};let sqlReads=0,sqlUnavailable=false;const sqlPool={query:async(sql:string,params?:unknown[])=>{if(sqlUnavailable&&sql.startsWith('SELECT artifact_json'))throw new Error('postgres_unavailable');if(sql.startsWith('SELECT artifact_json'))sqlReads++;const result=await pool.query(sql,params);return{rows:result.rows as {artifact_json:string}[]}}};
 try{await pool.query(await readFile('../../infra/db/schema/0050_adaptive_materialization.sql','utf8'));const p=policy(),req=request(p),metrics=adaptiveMetrics();let providerExecutions=0;const gate:ScheduledProviderExecutor=async runtimeRequest=>{providerExecutions++;const decision=resolveProviderRuntimeRequest(runtimeRequest),receivedAt=new Date().toISOString(),normalized={payloadId:'pgs5-real-yields',evidenceTypeId:'real_yields' as const,evidenceClass:'real_yields' as const,providerId:p.sourceId,sourceId:p.sourceId,region:'global',asset:p.asset,observedAt:receivedAt,publishedAt:null,normalizedAt:receivedAt,confidenceScore:90,dataQuality:'high' as const,valuesJson:'{}',metadataJson:'{"sourceMode":"live","direction":"bullish"}'},response={requestId:runtimeRequest.requestId,responseId:'pgs5-response',sourceId:runtimeRequest.sourceId,capabilityId:runtimeRequest.capabilityId,adapterId:decision.adapterId??'tiingo_market_data_market_price_history_adapter',receivedAt,payload:{normalizedPayloads:[normalized]},payloadSchemaStatus:'valid' as const,payloadSizeBytes:100,recordCount:1,revision:'pgs5-1',provenance:{requestId:runtimeRequest.requestId,sourceId:runtimeRequest.sourceId},error:null,rateLimit:null};return{decision,response,snapshot:buildProviderApiGateSnapshot(decision,runtimeRequest.requestId,response),settlementState:'settled_committed' as const}};const evidenceScope={coordinationHash:buildAdaptiveJobIdentity(p),scopeHash:buildMaterializationScopeHash({asset:p.asset,horizon:p.horizon,kind:'evidence',sourceId:p.sourceId,capabilityId:p.capabilityId,region:p.region})},runtime=createProductionAdaptiveMaterializationRuntime({redisClient:client(),sqlPool,providerGateExecutor:gate,trustedExecutionContext:{credentialPoolId:'pgs5_pool'},evidenceScopes:()=>[evidenceScope],metrics,namespace});const seeded=await runtime.orchestrator.run(p,req,Date.now(),'pgs5-seed-run');assert.ok(seeded);if(!seeded)throw new Error('pgs5_seed_failed');const seedCounts={provider:providerExecutions,cognition:metrics.cognitionComputed,scheduler:metrics.scheduleEvaluations};
 const readerClients=Array.from({length:4},client),readers=readerClients.map(redisClient=>createProductionCanonicalCognitionReader({redisClient,sqlPool,cacheLimits:{maxEntries:2,maxSerializedBytes:128_000},namespace}));await Promise.all(Array.from({length:200},()=>readers[0]!.read(p.asset,p.horizon)));assert.equal(readers[0]!.metrics.postgresReads,1);await Promise.all(readers.slice(1).flatMap(reader=>Array.from({length:50},()=>reader.read(p.asset,p.horizon))));assert.ok(readers.reduce((n,r)=>n+r.metrics.postgresReads,0)<=readers.length);const beforeWarm=sqlReads;for(let offset=0;offset<100000;offset+=250)await Promise.all(Array.from({length:250},(_,i)=>readers[(offset+i)%readers.length]!.read(p.asset,p.horizon).then(result=>assert.equal(result.artifact?.identity,seeded.cognition.identity))));assert.equal(sqlReads,beforeWarm);assert.equal(providerExecutions-seedCounts.provider,0);assert.equal(metrics.cognitionComputed-seedCounts.cognition,0);assert.equal(metrics.scheduleEvaluations-seedCounts.scheduler,0);
 sqlUnavailable=true;assert.equal((await readers[0]!.read(p.asset,p.horizon)).artifact?.identity,seeded.cognition.identity);sqlUnavailable=false;const nextAt=Date.parse(seeded.cognition.evaluatedAt)+PGS4_PRODUCTION_COGNITION_CONFIGURATION.evaluationEpochMs,aggregate=await runtime.aggregate.resolve(p.asset,p.horizon,nextAt),next=await runtime.cognition.materialize(p,{evidenceIdentities:aggregate.evidenceIdentities,asset:p.asset,horizon:p.horizon,evaluatedAt:nextAt,schedulerRunId:'pgs5-pointer-b',weightedSnapshot:aggregate.weightedSnapshot});assert.notEqual(next.identity,seeded.cognition.identity);const beforeB=sqlReads;await Promise.all(readers.flatMap(reader=>Array.from({length:20},()=>reader.read(p.asset,p.horizon))));assert.ok(sqlReads-beforeB<=readers.length);assert.ok(await runtime.immutable.getImmutable(seeded.cognition.identity));
 sqlUnavailable=true;const coldClient=client(),cold=createProductionCanonicalCognitionReader({redisClient:coldClient,sqlPool,cacheLimits:{maxEntries:1,maxSerializedBytes:128_000},namespace});assert.equal((await cold.read(p.asset,p.horizon)).state,'unavailable');sqlUnavailable=false;assert.equal((await cold.read(p.asset,p.horizon)).artifact?.identity,next.identity);
 const admissionClients=Array.from({length:3},client),services=admissionClients.map(c=>new RedisInboundReadAdmission(c,admissionPolicy(),`${namespace}:admission`,3000,undefined,'test')),raced=await Promise.all(Array.from({length:20},(_,i)=>services[i%3]!.admit('subject-a')));assert.equal(raced.filter(x=>x.admitted).length,3);const leases=raced.flatMap(x=>x.admitted?[x.lease]:[]);assert.equal(await services[0]!.renew({...leases[0]!,ownerToken:'wrong'}),null);assert.equal(await services[0]!.release({...leases[0]!,ownerToken:'wrong'}),false);await new Promise(r=>setTimeout(r,250));assert.equal(await services[0]!.confirm(leases[0]!),false);await Promise.all(leases.map((lease,i)=>services[i%3]!.release(lease)));
 const longService=new RedisInboundReadAdmission(client(),admissionPolicy({policyId:'long',concurrentAllowance:1,requestAllowance:10,windowMs:100,stateTtlMs:200}),`${namespace}:long`,3000,undefined,'test'),long=await longService.admit('long-subject');assert.ok(long.admitted);if(!long.admitted)throw new Error('long_admission_failed');const heartbeat=setInterval(()=>void longService.renew(long.lease),20);await new Promise(r=>setTimeout(r,260));assert.equal(await longService.confirm(long.lease),true);const competing=await longService.admit('long-subject');assert.equal(competing.admitted,false);if(competing.admitted===false)assert.equal(competing.reason,'inbound_concurrency_limited');clearInterval(heartbeat);await longService.release(long.lease);assert.equal((await longService.admit('long-subject')).admitted,true);
 const wrongRoute=new RedisInboundReadAdmission(client(),admissionPolicy({policyId:'wrong-route',routeFamily:'other'}),`${namespace}:wrong`,3000,undefined,'test'),disabled=new RedisInboundReadAdmission(client(),admissionPolicy({policyId:'disabled',status:'disabled'}),`${namespace}:disabled`,3000,undefined,'test');const wrongResult=await wrongRoute.admit('x'),disabledResult=await disabled.admit('x'),otherSubject=await services[0]!.admit('subject-b');assert.equal(wrongResult.admitted,false);if(wrongResult.admitted===false)assert.equal(wrongResult.status,503);assert.equal(disabledResult.admitted,false);if(disabledResult.admitted===false)assert.equal(disabledResult.status,503);assert.equal(otherSubject.admitted,true);
 const totals=readers.reduce((a,r)=>({logical:a.logical+r.metrics.logicalConsumerReads,pointer:a.pointer+r.metrics.currentPointerReads,hits:a.hits+r.metrics.l1Hits,misses:a.misses+r.metrics.l1Misses,postgres:a.postgres+r.metrics.postgresReads,available:a.available+r.metrics.availableReads,stale:a.stale+r.metrics.staleReads,unavailable:a.unavailable+r.metrics.unavailableReads}),{logical:0,pointer:0,hits:0,misses:0,postgres:0,available:0,stale:0,unavailable:0});console.log(JSON.stringify({schema:'pgs5-scale-report-v1',...totals,providerExecutionDelta:providerExecutions-seedCounts.provider,cognitionComputationDelta:metrics.cognitionComputed-seedCounts.cognition,schedulerExecutionDelta:metrics.scheduleEvaluations-seedCounts.scheduler,cacheEntries:readers.map(r=>r.metrics.cacheEntries),cacheBytes:readers.map(r=>r.metrics.cacheBytes),evictions:readers.reduce((n,r)=>n+r.metrics.evictions,0),inbound:services.reduce((a,s)=>({admitted:a.admitted+s.metrics.admitted,rejectedRate:a.rejectedRate+s.metrics.rejectedRate,rejectedConcurrency:a.rejectedConcurrency+s.metrics.rejectedConcurrency,unavailable:a.unavailable+s.metrics.unavailable}),{admitted:0,rejectedRate:0,rejectedConcurrency:0,unavailable:0})}));
 }finally{for(const c of clients)if(c.isOpen)c.destroy();await pool.end()}
}
