import assert from 'node:assert/strict';
import { buildProviderRequestFingerprint, hashProviderControlPolicy, MemoryProviderControlStore, providerControlKeys, validateProviderControlPolicy, type ProviderControlPolicy } from '../provider-sources/provider-control/index.js';

function policy(overrides:Partial<ProviderControlPolicy>={}):ProviderControlPolicy { const unsigned:Omit<ProviderControlPolicy,'canonicalPolicyHash'>={policyId:'test-policy',policyVersion:'1',sourceId:'tiingo_market_data',capabilityId:'market_price_history',credentialPoolId:'primary',status:'test_only',effectiveFrom:'1970-01-01T00:00:00.000Z',effectiveTo:null,provenance:'PGS-1 deterministic test policy; not a provider limit',rate:{capacity:10,refillAmount:10,refillIntervalMs:60_000,requestTokens:1},quota:{limit:7,windowMs:60_000},cost:{budgetUnits:5,windowMs:60_000,requestCostUnits:1},concurrency:{maxConcurrent:3,leaseDurationMs:10_000,providerTimeoutMs:5_000},...overrides};return {...unsigned,canonicalPolicyHash:hashProviderControlPolicy(unsigned)}; }
export async function runProviderControlTests(){
  validateProviderControlPolicy(policy()); assert.throws(()=>validateProviderControlPolicy({...policy(),canonicalPolicyHash:'bad'}),/hash_mismatch/);assert.throws(()=>policy({concurrency:{maxConcurrent:1,leaseDurationMs:5,providerTimeoutMs:5}})&&validateProviderControlPolicy(policy({concurrency:{maxConcurrent:1,leaseDurationMs:5,providerTimeoutMs:5}})),/provider_timeout/);
  const keys=providerControlKeys(policy());assert.ok(keys.rate.includes('{tiingo_market_data|market_price_history|primary|1}'));assert.equal(new Set(Object.values(keys).map(k=>k.slice(k.indexOf('{'),k.indexOf('}')+1))).size,1);
  const base={sourceId:'tiingo_market_data',capabilityId:'market_price_history',asset:'eur_usd',region:'global',startAt:'2026-01-01',endAt:'2026-01-02',paginationCursor:'a',providerRequestParams:{interval:'1h',adjusted:true}};const f=buildProviderRequestFingerprint(base);assert.equal(f,buildProviderRequestFingerprint({...base,providerRequestParams:{adjusted:true,interval:'1h'}}));assert.notEqual(f,buildProviderRequestFingerprint({...base,asset:'gbp_usd'}));assert.notEqual(f,buildProviderRequestFingerprint({...base,endAt:'2026-01-03'}));assert.notEqual(f,buildProviderRequestFingerprint({...base,paginationCursor:'b'}));assert.notEqual(f,buildProviderRequestFingerprint({...base,providerRequestParams:{interval:'1d'}}));assert.throws(()=>buildProviderRequestFingerprint({...base,providerRequestParams:{apiKey:'secret'}}),/secret_like/);
  let now=1_000_000;const store=new MemoryProviderControlStore(()=>now);const p=policy();const admits=await Promise.all(Array.from({length:100},(_,i)=>store.admit({requestId:`r${i}`,ownerToken:`o${i}`,fingerprint:f,policy:p})));assert.equal(admits.filter(x=>x.allowed).length,3);assert.equal(admits.find(x=>!x.allowed)?.reason,'provider_concurrency_exhausted');for(const a of admits)if(a.allowed)await store.settle(a.reservation,'RELEASED');
  const burstStore=new MemoryProviderControlStore(()=>now);const ratePolicy=policy({policyVersion:'burst',quota:{limit:100,windowMs:60_000},cost:{budgetUnits:100,windowMs:60_000,requestCostUnits:1},concurrency:{maxConcurrent:100,leaseDurationMs:10_000,providerTimeoutMs:5_000}});const burst=await Promise.all(Array.from({length:100},(_,i)=>burstStore.admit({requestId:`b${i}`,ownerToken:`bo${i}`,fingerprint:f,policy:ratePolicy})));assert.equal(burst.filter(x=>x.allowed).length,10);now+=60_000;assert.equal((await burstStore.admit({requestId:'refill',ownerToken:'refill',fingerprint:f,policy:ratePolicy})).allowed,true);
  const rollbackStore=new MemoryProviderControlStore(()=>now);const impossible=policy({cost:{budgetUnits:1,windowMs:60_000,requestCostUnits:2}});assert.equal((await rollbackStore.admit({requestId:'denied',ownerToken:'x',fingerprint:f,policy:impossible})).reason,'provider_cost_exhausted');const after=await rollbackStore.admit({requestId:'ok',ownerToken:'y',fingerprint:f,policy:policy({cost:{budgetUnits:1,windowMs:60_000,requestCostUnits:1}})});assert.equal(after.allowed,true);if(after.allowed){assert.equal(await rollbackStore.settle(after.reservation,'COMMIT_REQUIRED_UNKNOWN_OUTCOME'),true);assert.equal(await rollbackStore.settle(after.reservation,'RELEASED'),false);}await store.close();
}
export { policy as buildTestProviderControlPolicy };
