import assert from 'node:assert/strict';
import { executeProviderApiGateRequest } from '../provider-sources/provider-api-gate.js';
import { TiingoMarketDataAdapter } from '../provider-sources/tiingo/tiingo-adapter.js';
import { createProviderControlRedisClient,RedisProviderControlStore,providerControlKeys,type ProviderControlPolicy } from '../provider-sources/provider-control/index.js';
import { buildTestAdmission,buildTestProviderControlPolicy } from './provider-control.test.js';
function scoped(version:string,overrides:Partial<ProviderControlPolicy>):ProviderControlPolicy{return buildTestProviderControlPolicy({policyVersion:version,...overrides});}
async function race(store:RedisProviderControlStore,p:ProviderControlPolicy,n=100,offset=0){return Promise.all(Array.from({length:n},(_,i)=>store.admit(buildTestAdmission(p,`${p.policyVersion}-${i+offset}`))));}
export async function runProviderControlRedisIntegrationTests(){if(process.env.PROVIDER_CONTROL_REDIS_INTEGRATION!=='1')return;const namespace=`elceo:provider-control:test:${process.pid}:${Date.now()}`,clientA=createProviderControlRedisClient(),clientB=createProviderControlRedisClient(),a=new RedisProviderControlStore(clientA,namespace),b=new RedisProviderControlStore(clientB,namespace);
 try{const broad={quota:{kind:'fixed_duration' as const,limit:100,windowMs:60_000},cost:{kind:'fixed_duration' as const,budgetUnits:100,windowMs:60_000,requestCostUnits:1},concurrency:{maxConcurrent:100,leaseDurationMs:10_000,providerTimeoutMs:5_000}};
  const rate=scoped('rate',broad),rr=(await Promise.all([race(a,rate,50),race(b,rate,50,50)])).flat();assert.equal(rr.filter(x=>x.allowed).length,10);
  const quota=scoped('quota',{...broad,rate:{capacity:100,refillAmount:100,refillIntervalMs:60_000,requestTokens:1},quota:{kind:'fixed_duration',limit:7,windowMs:60_000}});assert.equal((await race(a,quota)).filter(x=>x.allowed).length,7);
  const cost=scoped('cost',{...broad,rate:{capacity:100,refillAmount:100,refillIntervalMs:60_000,requestTokens:1},cost:{kind:'fixed_duration',budgetUnits:5,windowMs:60_000,requestCostUnits:1}});assert.equal((await race(a,cost)).filter(x=>x.allowed).length,5);
  const concurrency=scoped('concurrency',{...broad,rate:{capacity:100,refillAmount:100,refillIntervalMs:60_000,requestTokens:1},concurrency:{maxConcurrent:3,leaseDurationMs:10_000,providerTimeoutMs:5_000}});assert.equal((await race(a,concurrency)).filter(x=>x.allowed).length,3);
  const duplicate=scoped('duplicate',broad),same=buildTestAdmission(duplicate,'same');const duplicates=(await Promise.all([Promise.all(Array.from({length:50},()=>a.admit(same))),Promise.all(Array.from({length:50},()=>b.admit(same)))])).flat();assert.equal(duplicates.filter(x=>x.allowed&&!x.reused).length,1);assert.equal(duplicates.filter(x=>x.allowed).length,100);assert.equal((await b.admit({...same,fingerprint:'conflict'})).reason,'provider_control_idempotency_conflict');assert.equal((await b.admit({...same,policy:scoped('duplicate-policy-conflict',broad)})).reason,'provider_control_idempotency_conflict');
  const rollback=scoped('rollback',{...broad,cost:{kind:'fixed_duration',budgetUnits:1,windowMs:60_000,requestCostUnits:2}}),denied=await a.admit(buildTestAdmission(rollback,'denied'));assert.equal(denied.reason,'provider_cost_exhausted');if(!denied.allowed){assert.equal(denied.snapshot?.rate.remaining,10);assert.equal(denied.snapshot?.quota?.used,0);assert.equal(denied.snapshot?.cost.reserved,0);assert.equal(denied.snapshot?.concurrency.active,0);}
  const limited=scoped('release',{rate:{capacity:1,refillAmount:1,refillIntervalMs:60_000,requestTokens:1},quota:{kind:'fixed_duration',limit:1,windowMs:60_000},cost:{kind:'fixed_duration',budgetUnits:1,windowMs:60_000,requestCostUnits:1},concurrency:{maxConcurrent:1,leaseDurationMs:10_000,providerTimeoutMs:5_000}}),released=await a.admit(buildTestAdmission(limited,'release'));if(released.allowed)assert.equal(await a.settle(released.reservation,'RELEASED'),true);assert.equal((await b.admit(buildTestAdmission(limited,'after-release'))).allowed,true);
  const lease=scoped('lease',{...broad,concurrency:{maxConcurrent:1,leaseDurationMs:80,providerTimeoutMs:40}}),workerA=await a.admit(buildTestAdmission(lease,'lease-a'));await new Promise(resolve=>setTimeout(resolve,100));const workerB=await b.admit(buildTestAdmission(lease,'lease-b'));assert.equal(workerB.allowed,true);if(workerA.allowed)await a.settle(workerA.reservation,'RELEASED');assert.equal((await a.admit(buildTestAdmission(lease,'lease-c'))).reason,'provider_concurrency_exhausted');if(workerB.allowed)await b.settle(workerB.reservation,'COMMITTED');
  const admissionKey=providerControlKeys(duplicate,namespace).admission(same.admissionId);assert.ok(await clientA.pTTL(admissionKey)>0);
  let adapterCalls=0;const fixture=new TiingoMarketDataAdapter({mode:'fixture'}),adapter={descriptor:fixture.descriptor,fetch:async(request:never)=>{adapterCalls++;return fixture.fetch(request);},normalize:async()=>[]};const unreachableClient=createProviderControlRedisClient({url:'redis://127.0.0.1:1',connectTimeoutMs:30}),unreachable=new RedisProviderControlStore(unreachableClient,`${namespace}:outage`,50);const outagePolicy=scoped('outage',broad);const outage=await executeProviderApiGateRequest({requestId:'outage',sourceId:'tiingo_market_data',capabilityId:'market_price_history',asset:'eur_usd',activationMode:'staging_live_allowed',provenance:{actor:'test',purpose:'outage'},policy:{explicitStagingLiveAllow:true,requestMetadata:{credentialPresent:true}}},adapter,{providerControlStore:unreachable,policyResolver:{resolve:async()=>outagePolicy},credentialPoolId:'primary'});assert.equal(outage.decision.reason,'provider_control_unavailable');assert.equal(adapterCalls,0);await unreachable.close();
  console.log('provider control Redis integration passed: rate=10 quota=7 cost=5 concurrency=3 duplicate=once rollback=clean cross-instance=shared lease=owner-safe bounded=true');
 }finally{for(const client of [clientA,clientB])if(client.isOpen){const keys=await client.keys(`${namespace}:*`);if(keys.length)await client.del(keys);}await Promise.all([a.close(),b.close()]);}}
