import assert from 'node:assert/strict';
import { validateMarketProviderReliabilityCoverageReport, validateMarketProviderReliabilityInput, validateMarketProviderReliabilityResult, validateMarketProviderReliabilityRule, validateMarketProviderReliabilityRuleSetSnapshot } from '@elceo/schemas';
import type { MarketProviderReliabilityInput, ReasoningEvidenceInputItem } from '@elceo/types';
import { buildWeightedEvidenceItem, buildWeightedEvidenceSnapshot } from '../evidence-weighting/index.js';
import { getDefaultReasoningEvidenceFilterPolicy } from '../reasoning-input/index.js';
import { calibrateMarketConfidence } from '../confidence-calibration/index.js';
import { evaluateContradictionsFromWeightedSnapshot } from '../contradiction-matrix/index.js';
import { CanonicalMarketIntelligenceBoundaryService } from '../runtime/canonical-market-intelligence-boundary.js';
import { MemoryMarketEvidenceRegistrySnapshotRepository, MemorySeoContentArchitectureSnapshotRepository } from '../persistence/registry-snapshot-repository.js';
import { assertMarketProviderReliabilityRuleSetValid, buildAssetProviderDependencies, evaluateAssetProviderCoverage, evaluateProviderReliability, getMarketProviderReliabilityCoverageReport, getMarketProviderReliabilityRuleSetSnapshot } from '../provider-reliability/index.js';

const at = '2026-06-05T00:00:00.000Z';
const baseInput: MarketProviderReliabilityInput = { asset:'sp500', horizon:'intraday', generatedAt:at, providerId:'federal_reserve_official', evidenceClass:'central_bank_policy', freshnessTier:'recent', independenceStatus:'independent', extractionQuality:'high', rationale:'deterministic test input' };
function input(partial: Partial<MarketProviderReliabilityInput>): MarketProviderReliabilityInput { return { ...baseInput, ...partial }; }
function evidence(id: string, providerId: string, reasons: string[] = [], metadataJson = '{}'): ReasoningEvidenceInputItem { return { payloadId:id, evidenceTypeId:'market_news', evidenceClass:'market_news', providerId, asset:'sp500', region:'global', observedAt:at, normalizedAt:at, qualityScore:{ payloadId:id, evidenceTypeId:'market_news', evidenceClass:'market_news', providerId, asset:'sp500', region:'global', observedAt:at, evaluatedAt:at, provenanceKind:'live_provider', sourceQualityScore:90, freshnessScore:90, completenessScore:90, conflictScore:90, finalQualityScore:90, freshnessStatus:'fresh', conflictStatus:'none', usabilityStatus:'usable', reasons:[] }, usabilityStatus:'usable', freshnessStatus:'fresh', conflictStatus:'none', dataQuality:'high', valuesJson:'{}', metadataJson, reasons }; }
function confidence(providerReliability = evaluateProviderReliability(input({ providerId:'unknown_provider', authorityTier:'unknown', activationState:'unknown', freshnessTier:'stale' }))) { return calibrateMarketConfidence({ asset:'sp500', horizon:'intraday', generatedAt:at, baseConfidence:88, evidenceQuality:90, usableWeight:90, freshness:90, coverage:90, warnings:[], reasonCodes:[], options:{ providerReliabilitySupplied:true, providerReliability, priceReactionAvailable:true, sourceIndependenceVerified:true } }); }

export function runProviderReliabilityTests(): void {
  const official = evaluateProviderReliability(input({ providerId:'federal_reserve_official', providerKind:'central_bank', authorityTier:'official', activationState:'live_verified', coverageTier:'critical_complete' }));
  const unknownScraped = evaluateProviderReliability(input({ providerId:'unknown_scraper', providerKind:'scraped_news', authorityTier:'scraped_or_unverified', activationState:'unknown', freshnessTier:'stale', independenceStatus:'scraped_duplicate', extractionQuality:'low', evidenceClass:'market_news' }));
  assert.equal(validateMarketProviderReliabilityInput(baseInput).ok, true);
  assert.equal(validateMarketProviderReliabilityResult(official).ok, true);
  assert.equal(validateMarketProviderReliabilityResult({ ...official, reliabilityScore:101 }).ok, false);
  assert.equal(validateMarketProviderReliabilityResult({ ...official, weightMultiplier:1.5 }).ok, false);
  assert.equal(validateMarketProviderReliabilityResult({ ...official, confidenceCap:101 }).ok, false);
  assert.equal(validateMarketProviderReliabilityRuleSetSnapshot(getMarketProviderReliabilityRuleSetSnapshot(at)).ok, true);
  assert.equal(validateMarketProviderReliabilityCoverageReport(getMarketProviderReliabilityCoverageReport(at)).ok, true);
  assert.equal(validateMarketProviderReliabilityRule(getMarketProviderReliabilityRuleSetSnapshot(at).rules[0]).ok, true);
  assert.equal(assertMarketProviderReliabilityRuleSetValid().readiness.moduleId, 'provider_reliability');
  assert.ok(getMarketProviderReliabilityCoverageReport(at).readiness.moduleId === 'provider_reliability' && getMarketProviderReliabilityCoverageReport(at).readiness.liveProviderIntegrationStatus === 'blocked');
  assert.ok(!JSON.stringify(getMarketProviderReliabilityRuleSetSnapshot(at)).match(/\b(buy|sell|hold|guaranteed profit|risk-free)\b/i));
  assert.ok(official.reliabilityScore > unknownScraped.reliabilityScore, 'official recent source scores higher than unknown scraped source');
  const centralBank = evaluateProviderReliability(input({ providerId:'federal_reserve_official', providerKind:'central_bank', authorityTier:'official' }));
  assert.ok(centralBank.reliabilityScore >= 40 && centralBank.readiness.moduleId === 'provider_reliability', 'central bank source remains pending unless explicitly live verified');
  const fixture = evaluateProviderReliability(input({ providerId:'tiingo_market_data', activationState:'fixture_only', providerKind:'internal_fixture', authorityTier:'fixture_only' }));
  assert.ok(fixture.warnings.includes('provider_fixture_only') && fixture.warnings.includes('pending_live_provider_activation') && fixture.confidenceCap <= 64);
  const dryRun = evaluateProviderReliability(input({ providerId:'public_market_price_exchange', activationState:'dry_run', providerKind:'exchange_market_data', authorityTier:'primary_market' }));
  assert.ok(dryRun.warnings.includes('provider_dry_run_only') && dryRun.weightMultiplier < official.weightMultiplier);
  const disabled = evaluateProviderReliability(input({ providerId:'disabled_provider', activationState:'disabled', authorityTier:'unknown', providerKind:'unknown' }));
  assert.ok(disabled.warnings.includes('provider_disabled') && disabled.warnings.includes('provider_activation_gap') && disabled.confidenceCap <= 64);
  assert.ok(unknownScraped.warnings.includes('unknown_provider') && unknownScraped.reasonCodes.includes('provider_registry_missing'));
  assert.ok(unknownScraped.warnings.includes('scraped_source_risk') && unknownScraped.warnings.includes('duplicate_source_risk'));
  assert.ok(evaluateProviderReliability(input({ providerId:'unknown_feed', independenceStatus:'unverified', authorityTier:'unknown', activationState:'unknown' })).warnings.includes('source_independence_unverified'));
  const coveredDeps = [{ dependencyId:'covered-policy', evidenceClasses:['central_bank_policy' as const], critical:true, covered:true, sourceIds:['federal_reserve_official'], rationale:'covered critical policy context' }];
  const stale = evaluateProviderReliability(input({ freshnessTier:'stale', activationState:'live_verified', coverageTier:'critical_complete', assetDependencies:coveredDeps }));
  const fresh = evaluateProviderReliability(input({ freshnessTier:'recent', activationState:'live_verified', coverageTier:'critical_complete', assetDependencies:coveredDeps }));
  assert.ok(stale.reliabilityScore < fresh.reliabilityScore && stale.warnings.includes('stale_provider_data'));
  const failed = evaluateProviderReliability(input({ extractionQuality:'failed', activationState:'live_verified', coverageTier:'critical_complete' }));
  assert.ok(failed.reliabilityScore < fresh.reliabilityScore && failed.weightMultiplier < fresh.weightMultiplier && failed.warnings.includes('extraction_failed'));
  const highExtractionFixture = evaluateProviderReliability(input({ providerId:'tiingo_market_data', extractionQuality:'high', activationState:'fixture_only' }));
  assert.ok(highExtractionFixture.confidenceCap <= 64, 'high extraction quality does not override activation gap');
  const criticalMissing = evaluateProviderReliability(input({ assetDependencies:[{ dependencyId:'critical-real-yields', evidenceClasses:['real_yields'], critical:true, covered:false, sourceIds:['fred_macro'], rationale:'critical dependency missing for test' }], evidenceClass:'real_yields' }));
  const niceMissing = evaluateProviderReliability(input({ assetDependencies:[{ dependencyId:'nice-news', evidenceClasses:['market_news'], critical:false, covered:false, sourceIds:['marketaux_news'], rationale:'non-critical dependency missing for test' }], evidenceClass:'market_news' }));
  assert.ok((criticalMissing.dataGapSeverity === 'critical' || criticalMissing.dataGapSeverity === 'high') && criticalMissing.warnings.includes('missing_critical_asset_dependency'));
  assert.ok(['low','moderate'].includes(niceMissing.dataGapSeverity), 'nice-to-have dependency missing is lower severity');
  assert.ok(evaluateAssetProviderCoverage('xau_usd',[],{ asOfIso:at }).warnings.includes('missing_critical_asset_dependency'), 'XAU/USD missing real-yields/DXY context is high/critical gap');
  assert.ok(evaluateAssetProviderCoverage('eur_usd',['central_bank_policy'],{ asOfIso:at }).warnings.includes('partial_asset_dependency_coverage'), 'EUR/USD one-sided macro/policy context reduces coverage');
  assert.ok(evaluateAssetProviderCoverage('btc_usd',['crypto_market_structure'],{ asOfIso:at }).warnings.length > 0, 'BTC/USD crypto/on-chain/ETF coverage remains diagnostic');
  assert.ok(evaluateAssetProviderCoverage('nasdaq_100',['equity_index_breadth','volatility_surface','credit_stress'],{ asOfIso:at }).warnings.length > 0, 'Nasdaq breadth/vol/credit coverage remains weighted');
  assert.ok(evaluateAssetProviderCoverage('usd_cad',['energy_commodities'],{ asOfIso:at }).warnings.length > 0, 'USD/CAD oil/energy context reduces coverage when incomplete');
  assert.ok(evaluateAssetProviderCoverage('dxy',undefined,{ asOfIso:at }).warnings.includes('diagnostic_only_provider_context'), 'DXY remains diagnostic-limited until basket coverage is complete');
  assert.ok(evaluateAssetProviderCoverage('vix',undefined,{ asOfIso:at }).warnings.length > 0, 'VIX requires volatility/equity/risk/credit context');
  const officialItem = { ...evidence('official','federal_reserve_official'), evidenceClass:'central_bank_policy' as const, evidenceTypeId:'central_bank_policy' };
  const scrapedItem = evidence('scraped','unknown_scraper',['scraped duplicate','same headline burst']);
  const officialWeighted = buildWeightedEvidenceItem(officialItem,'sp500','intraday');
  const scrapedWeighted = buildWeightedEvidenceItem(scrapedItem,'sp500','intraday');
  assert.ok(officialWeighted.reasons.some((r)=>r.startsWith('provider_reliability_score:')) && scrapedWeighted.reasons.includes('provider_warning:duplicate_source_risk'));
  assert.ok(scrapedWeighted.qualityAdjustedWeight < officialWeighted.qualityAdjustedWeight, 'scraped/duplicate provider reliability reduces evidence weight');
  const lowConfidence = confidence(unknownScraped);
  const highConfidence = confidence(official);
  assert.ok(!lowConfidence.penalties.some((p)=>p.kind === 'missing_provider_reliability') && lowConfidence.finalConfidence < highConfidence.finalConfidence && lowConfidence.finalConfidence <= unknownScraped.confidenceCap);
  assert.ok(lowConfidence.readiness.moduleId === 'confidence_calibration', 'supplied provider context does not complete pending expansions');
  const snapshot = buildWeightedEvidenceSnapshot({ snapshotId:'provider-snapshot', generatedAt:at, asset:'sp500', evidenceClass:null, filterPolicy:getDefaultReasoningEvidenceFilterPolicy(), items:[scrapedItem], excludedItems:[], warnings:[] }, 'sp500','intraday');
  const matrix = evaluateContradictionsFromWeightedSnapshot(snapshot, { providerReliabilitySupplied:true });
  assert.ok(matrix.readiness.moduleId === 'contradiction_matrix', 'provider reliability remains caveat context rather than automatic market contradiction');
  const unverifiedOnly = buildWeightedEvidenceSnapshot({ snapshotId:'unverified', generatedAt:at, asset:'sp500', evidenceClass:null, filterPolicy:getDefaultReasoningEvidenceFilterPolicy(), items:[evidence('unverified','marketaux_news',['source_independence_unverified'])], excludedItems:[], warnings:[] }, 'sp500','intraday');
  const unverifiedMatrix = evaluateContradictionsFromWeightedSnapshot(unverifiedOnly, { providerReliabilitySupplied:true });
  assert.ok(unverifiedMatrix.signals.length <= matrix.signals.length, 'source independence caveat alone stays milder than duplicate/scraped risk');
  const boundary = new CanonicalMarketIntelligenceBoundaryService(new MemoryMarketEvidenceRegistrySnapshotRepository(), new MemorySeoContentArchitectureSnapshotRepository());
  assert.equal(boundary.evaluateProviderReliability(baseInput).providerId,'federal_reserve_official');
  assert.equal(boundary.evaluateProviderReliabilityForEvidenceItem(officialItem,{ asset:'sp500', horizon:'intraday' }).asset,'sp500');
  assert.equal(boundary.evaluateProviderReliabilityForWeightedItem(officialWeighted).providerId,'federal_reserve_official');
  assert.equal(boundary.evaluateProviderReliabilityForWeightedSnapshot(snapshot).length,1);
  assert.equal(boundary.evaluateAssetProviderCoverage('xau_usd',['real_yields'],{ asOfIso:at }).assets[0],'xau_usd');
  assert.equal(boundary.getMarketProviderReliabilityRuleSetSnapshot(at).readiness.moduleId,'provider_reliability');
  assert.equal(boundary.getMarketProviderReliabilityCoverageReport(at).readiness.moduleId,'provider_reliability');
  assert.equal(boundary.assertMarketProviderReliabilityRuleSetValid().readiness.moduleId,'provider_reliability');
  assert.ok(boundary.listMarketProviderReliabilityWarnings('dxy').includes('diagnostic_only_provider_context'));
  assert.ok(boundary.listMarketProviderReliabilityRules('sp500').length > 0);
  assert.ok(buildAssetProviderDependencies('xau_usd').length > 0);
}
