import assert from 'node:assert/strict';
import { createProviderControlRedisClient, RedisProviderControlStore, providerControlKeys, type ProviderControlPolicy } from '../provider-sources/provider-control/index.js';
import { buildTestProviderControlPolicy } from './provider-control.test.js';
const fp='v1:sha256:integration';
function scoped(version:string,overrides:Partial<ProviderControlPolicy>):ProviderControlPolicy{return buildTestProviderControlPolicy({policyVersion:version,...overrides});}
async function race(store:RedisProviderControlStore,p:ProviderControlPolicy,n=100){return Promise.all(Array.from({length:n},(_,i)=>store.admit({requestId:`${p.policyVersion}-${i}`,ownerToken:`${p.policyVersion}-owner-${i}`,fingerprint:fp,policy:p})));}
export async function runProviderControlRedisIntegrationTests(){if(process.env.PROVIDER_CONTROL_REDIS_INTEGRATION!=='1')return;const namespace=`elceo:provider-control:test:${process.pid}:${Date.now()}`;const clientA=createProviderControlRedisClient(),clientB=createProviderControlRedisClient();const a=new RedisProviderControlStore(clientA,namespace),b=new RedisProviderControlStore(clientB,namespace);
 try {
  const rate=scoped('rate',{quota:{limit:100,windowMs:60_000},cost:{budgetUnits:100,windowMs:60_000,requestCostUnits:1},concurrency:{maxConcurrent:100,leaseDurationMs:10_000,providerTimeoutMs:5_000}});const rr=await Promise.all([race(a,rate,50),race(b,rate,50)]).then(x=>x.flat());assert.equal(rr.filter(x=>x.allowed).length,10,'100-concurrent token bucket must admit exactly 10');
  const quota=scoped('quota',{rate:{capacity:100,refillAmount:100,refillIntervalMs:60_000,requestTokens:1},cost:{budgetUnits:100,windowMs:60_000,requestCostUnits:1},concurrency:{maxConcurrent:100,leaseDurationMs:10_000,providerTimeoutMs:5_000}});assert.equal((await race(a,quota)).filter(x=>x.allowed).length,7,'quota race must admit exactly 7');
  const cost=scoped('cost',{rate:{capacity:100,refillAmount:100,refillIntervalMs:60_000,requestTokens:1},quota:{limit:100,windowMs:60_000},concurrency:{maxConcurrent:100,leaseDurationMs:10_000,providerTimeoutMs:5_000}});assert.equal((await race(a,cost)).filter(x=>x.allowed).length,5,'cost race must admit exactly 5');
  const concurrency=scoped('concurrency',{rate:{capacity:100,refillAmount:100,refillIntervalMs:60_000,requestTokens:1},quota:{limit:100,windowMs:60_000},cost:{budgetUnits:100,windowMs:60_000,requestCostUnits:1}});const cr=await race(a,concurrency);assert.equal(cr.filter(x=>x.allowed).length,3);assert.ok(cr.every(x=>x.allowed?x.reservation.snapshot.concurrency.active<=3:true));
  const deny=scoped('rollback',{rate:{capacity:10,refillAmount:10,refillIntervalMs:60_000,requestTokens:1},quota:{limit:10,windowMs:60_000},cost:{budgetUnits:1,windowMs:60_000,requestCostUnits:2},concurrency:{maxConcurrent:10,leaseDurationMs:10_000,providerTimeoutMs:5_000}});const denied=await a.admit({requestId:'rollback-deny',ownerToken:'rollback-owner',fingerprint:fp,policy:deny});assert.equal(denied.reason,'provider_cost_exhausted');if(!denied.allowed){assert.equal(denied.snapshot?.rate.remaining,10);assert.equal(denied.snapshot?.quota?.used,0);assert.equal(denied.snapshot?.cost.reserved,0);assert.equal(denied.snapshot?.concurrency.active,0);}
  const lease=scoped('lease',{rate:{capacity:10,refillAmount:10,refillIntervalMs:60_000,requestTokens:1},quota:{limit:10,windowMs:60_000},cost:{budgetUnits:10,windowMs:60_000,requestCostUnits:1},concurrency:{maxConcurrent:1,leaseDurationMs:80,providerTimeoutMs:40}});const workerA=await a.admit({requestId:'lease-a',ownerToken:'worker-a',fingerprint:fp,policy:lease});assert.equal(workerA.allowed,true);await new Promise(resolve=>setTimeout(resolve,100));const workerB=await b.admit({requestId:'lease-b',ownerToken:'worker-b',fingerprint:fp,policy:lease});assert.equal(workerB.allowed,true);if(workerA.allowed)assert.equal(await a.settle(workerA.reservation,'RELEASED'),true);const blocked=await a.admit({requestId:'lease-c',ownerToken:'worker-c',fingerprint:fp,policy:lease});assert.equal(blocked.reason,'provider_concurrency_exhausted','expired owner must not release replacement lease');if(workerB.allowed)await b.settle(workerB.reservation,'COMMITTED');
  const ttlKeys=providerControlKeys(rate,namespace);assert.ok(await clientA.pTTL(ttlKeys.rate)>0);assert.ok(await clientA.pTTL(ttlKeys.leases)>0);
  console.log('provider control Redis integration passed: rate=10 quota=7 cost=5 concurrency=3 rollback=clean cross-instance=shared lease=owner-safe');
 } finally {for(const c of [clientA,clientB]){if(c.isOpen){const keys=await c.keys(`${namespace}:*`);if(keys.length)await c.del(keys);}}await Promise.all([a.close(),b.close()]);}}
