import assert from 'node:assert/strict';
import { assertLivePolicyAuthority,buildProviderAdmissionId,buildProviderRequestFingerprint,hashProviderControlPolicy,MemoryProviderControlStore,providerControlKeys,validateProviderControlPolicy,type ProviderAdmissionRequest,type ProviderControlPolicy } from '../provider-sources/provider-control/index.js';
function policy(overrides:Partial<ProviderControlPolicy>={}):ProviderControlPolicy {const unsigned:Omit<ProviderControlPolicy,'canonicalPolicyHash'>={policyId:'test-policy',policyVersion:'1',sourceId:'tiingo_market_data',capabilityId:'market_price_history',credentialPoolId:'primary',status:'approved',effectiveFrom:'1970-01-01T00:00:00.000Z',effectiveTo:null,provenance:'PGS-1A deterministic test policy; not a provider limit',rate:{capacity:10,refillAmount:10,refillIntervalMs:60_000,requestTokens:1},quota:{kind:'fixed_duration',limit:7,windowMs:60_000},cost:{kind:'fixed_duration',budgetUnits:5,windowMs:60_000,requestCostUnits:1},concurrency:{maxConcurrent:3,leaseDurationMs:10_000,providerTimeoutMs:5_000},...overrides};return {...unsigned,canonicalPolicyHash:hashProviderControlPolicy(unsigned)};}
function admission(p:ProviderControlPolicy,id:string,fingerprint='fp'):ProviderAdmissionRequest{return {admissionId:buildProviderAdmissionId(id),reservationId:`reservation-${id}`,ownerToken:`owner-${id}`,requestId:id,fingerprint,policy:p};}
async function claimSettle(store:MemoryProviderControlStore,reservation:import('../provider-sources/provider-control/index.js').ProviderReservation,status:'RELEASED'|'COMMITTED'|'COMMIT_REQUIRED_UNKNOWN_OUTCOME'){const claim=await store.claimExecution(reservation,`execution-${reservation.reservationId}`);return claim.claimed?store.settle(claim.reservation,status):false;}
export async function runProviderControlTests(){
 const valid=policy();validateProviderControlPolicy(valid);assert.throws(()=>validateProviderControlPolicy({...valid,canonicalPolicyHash:'bad'}),/hash_mismatch/);for(const bad of [policy({policyId:''}),policy({provenance:''}),policy({effectiveFrom:'bad'}),policy({effectiveFrom:'2024-01-02',effectiveTo:'2024-01-01'})])assert.throws(()=>validateProviderControlPolicy(bad));assert.throws(()=>assertLivePolicyAuthority(policy({status:'test_only'}),{sourceId:valid.sourceId,capabilityId:valid.capabilityId},'primary'),/not_approved/);assert.throws(()=>assertLivePolicyAuthority(policy({sourceId:'fred'}),{sourceId:valid.sourceId,capabilityId:valid.capabilityId},'primary'),/scope_mismatch/);assert.throws(()=>assertLivePolicyAuthority(valid,{sourceId:valid.sourceId,capabilityId:'intraday_quotes'},'primary'),/scope_mismatch/);assert.throws(()=>assertLivePolicyAuthority(valid,{sourceId:valid.sourceId,capabilityId:valid.capabilityId},'secondary'),/scope_mismatch/);assert.doesNotThrow(()=>assertLivePolicyAuthority(policy({capabilityId:'*'}),{sourceId:valid.sourceId,capabilityId:'intraday_quotes'},'primary'));
 const keys=providerControlKeys(valid);assert.ok(keys.admission('x').includes('{tiingo_market_data|market_price_history|primary}'));const input={sourceId:'tiingo_market_data',capabilityId:'market_price_history',asset:'eur_usd',providerRequestParams:{b:2,a:1}};assert.equal(buildProviderRequestFingerprint(input),buildProviderRequestFingerprint({...input,providerRequestParams:{a:1,b:2}}));
 let now=1_000_000;const concurrencyStore=new MemoryProviderControlStore(()=>now);const concurrent=await Promise.all(Array.from({length:100},(_,i)=>concurrencyStore.admit(admission(valid,`c${i}`))));assert.equal(concurrent.filter(x=>x.allowed).length,3);for(const result of concurrent)if(result.allowed)await claimSettle(concurrencyStore,result.reservation,'RELEASED');
 const duplicateStore=new MemoryProviderControlStore(()=>now);const duplicate=await Promise.all(Array.from({length:100},()=>duplicateStore.admit(admission(valid,'same'))));assert.equal(duplicate.filter(x=>x.allowed&&!x.reused).length,1);assert.equal(duplicate.filter(x=>x.allowed).length,100);const baseReservation=duplicate.find(x=>x.allowed)?.reservation;assert.ok(baseReservation);const claims=await Promise.all(Array.from({length:100},(_,i)=>duplicateStore.claimExecution(baseReservation!,`executor-${i}`)));assert.equal(claims.filter(x=>x.claimed).length,1);assert.equal((await duplicateStore.admit(admission(valid,'same','different'))).reason,'provider_control_idempotency_conflict');assert.equal((await duplicateStore.admit({...admission(policy({policyVersion:'2'}),'same'),admissionId:buildProviderAdmissionId('same')})).reason,'provider_control_idempotency_conflict');
 const releaseStore=new MemoryProviderControlStore(()=>now);const limited=policy({rate:{capacity:1,refillAmount:1,refillIntervalMs:60_000,requestTokens:1},quota:{kind:'fixed_duration',limit:1,windowMs:60_000},cost:{kind:'fixed_duration',budgetUnits:1,windowMs:60_000,requestCostUnits:1},concurrency:{maxConcurrent:1,leaseDurationMs:10_000,providerTimeoutMs:5_000}});const released=await releaseStore.admit(admission(limited,'release'));assert.equal(released.allowed,true);if(released.allowed)assert.equal(await claimSettle(releaseStore,released.reservation,'RELEASED'),true);assert.equal((await releaseStore.admit(admission(limited,'after-release'))).allowed,true);
 const committedStore=new MemoryProviderControlStore(()=>now);const committed=await committedStore.admit(admission(limited,'commit'));if(committed.allowed)await claimSettle(committedStore,committed.reservation,'COMMITTED');assert.equal((await committedStore.admit(admission(limited,'after-commit'))).allowed,false);const unknownStore=new MemoryProviderControlStore(()=>now);const unknown=await unknownStore.admit(admission(limited,'unknown'));if(unknown.allowed)await claimSettle(unknownStore,unknown.reservation,'COMMIT_REQUIRED_UNKNOWN_OUTCOME');assert.equal((await unknownStore.admit(admission(limited,'after-unknown'))).allowed,false);
 const renewalStore=new MemoryProviderControlStore(()=>now);const renewalPolicy=policy({concurrency:{maxConcurrent:1,leaseDurationMs:600,providerTimeoutMs:100}}),renewal=await renewalStore.admit(admission(renewalPolicy,'renew'));now+=450;if(renewal.allowed){const claim=await renewalStore.claimExecution(renewal.reservation,'renew-exec');assert.equal(claim.claimed,true);if(claim.claimed)assert.equal(claim.reservation.executionLeaseExpiresAt,now+600);}
 const abandonedStore=new MemoryProviderControlStore(()=>now);const abandonedPolicy=policy({rate:{capacity:1,refillAmount:1,refillIntervalMs:60_000,requestTokens:1},quota:{kind:'fixed_duration',limit:1,windowMs:60_000},cost:{kind:'fixed_duration',budgetUnits:1,windowMs:60_000,requestCostUnits:1},concurrency:{maxConcurrent:1,leaseDurationMs:80,providerTimeoutMs:40}}),abandoned=await abandonedStore.admit(admission(abandonedPolicy,'abandon'));now+=100;if(abandoned.allowed)assert.equal((await abandonedStore.claimExecution(abandoned.reservation,'no-exec')).claimed,false);assert.equal((await abandonedStore.admit(admission(abandonedPolicy,'after-abandon'))).allowed,true);
 const executingStore=new MemoryProviderControlStore(()=>now);const executingPolicy=policy({rate:{capacity:1,refillAmount:1,refillIntervalMs:60_000,requestTokens:1},quota:{kind:'fixed_duration',limit:1,windowMs:60_000},cost:{kind:'fixed_duration',budgetUnits:1,windowMs:60_000,requestCostUnits:1},concurrency:{maxConcurrent:1,leaseDurationMs:600,providerTimeoutMs:100}}),executing=await executingStore.admit(admission(executingPolicy,'executing'));if(executing.allowed)assert.equal((await executingStore.claimExecution(executing.reservation,'exec-owner')).claimed,true);now+=700;assert.equal((await executingStore.admit(admission(executingPolicy,'after-executing-expiry'))).allowed,false,'EXECUTING lease expiry must not refund rate quota or cost');
 const rolloverStore=new MemoryProviderControlStore(()=>now,10);const old=await rolloverStore.admit(admission(limited,'old'));const oldClaim=old.allowed?await rolloverStore.claimExecution(old.reservation,'old-exec'):null;now+=60_000;const fresh=await rolloverStore.admit(admission(limited,'fresh'));assert.equal(fresh.allowed,true);if(oldClaim?.claimed)assert.equal(await rolloverStore.settle(oldClaim.reservation,'RELEASED'),true);assert.equal((await rolloverStore.admit(admission(limited,'must-stay-full'))).allowed,false);now+=20;assert.equal(rolloverStore.admissionCount(),1);
}
export {policy as buildTestProviderControlPolicy,admission as buildTestAdmission};
