import { strict as a } from 'node:assert';
import type { EvidenceQualityScore } from '@elceo/types';
import { validateReasoningEvidenceFilterPolicy, validateReasoningEvidenceInputItem, validateReasoningEvidenceInputSnapshot } from '@elceo/schemas';
import { MemoryNormalizedMarketEvidencePayloadRepository, MemoryProviderSourceRequestRepository, MemoryProviderSourceResponseRepository } from '../persistence/market-evidence-ingestion-repository';
import { MemoryMarketEvidenceRegistrySnapshotRepository, MemorySeoContentArchitectureSnapshotRepository } from '../persistence/registry-snapshot-repository';
import { CanonicalMarketIntelligenceBoundaryService } from '../runtime/canonical-market-intelligence-boundary.js';
import { assembleReasoningEvidenceInputSnapshot, buildReasoningEvidenceInputAssemblyReport, getDefaultReasoningEvidenceFilterPolicy } from '../reasoning-input/index.js';
import { evaluateEvidencePayloadQuality } from '../evidence-quality/index.js';
const p=(id:string,obs:string,meta='{"sourceMode":"live_provider"}',dq:'high'|'failed'='high')=>({payloadId:id,evidenceTypeId:'market_price_history',evidenceClass:'cross_market_rates',providerId:'tiingo_market_data',sourceId:null,region:'global',asset:'xau_usd',observedAt:obs,publishedAt:null,normalizedAt:obs,confidenceScore:90,dataQuality:dq,valuesJson:'{"v":1}',metadataJson:meta});
const q=(payload:ReturnType<typeof p>,generatedAt:string,overrides:Partial<EvidenceQualityScore>={}):EvidenceQualityScore=>({ ...evaluateEvidencePayloadQuality(payload,generatedAt), ...overrides });
export async function runReasoningMarketInputTests(){const pol=getDefaultReasoningEvidenceFilterPolicy(); a.equal(pol.includeFixtureEvidence,false); a.ok(validateReasoningEvidenceFilterPolicy(pol).ok); a.ok(!validateReasoningEvidenceFilterPolicy({...pol,maxEvidenceItems:0}).ok);
const generatedAt='2026-01-01T01:05:00.000Z'; const fixture=p('f','2026-01-01T00:00:00.000Z','{"sourceMode":"fixture"}'); const expired=p('e','2026-01-01T00:30:00.000Z'); const blocked=p('b','2026-01-01T00:59:00.000Z','{"sourceMode":"live_provider"}','failed'); const good=p('a','2026-01-01T01:00:00.000Z'); const s=assembleReasoningEvidenceInputSnapshot({payloads:[fixture,expired,blocked,good],qualityScores:[q(fixture,generatedAt,{provenanceKind:'fixture'}),q(expired,generatedAt,{freshnessStatus:'expired',usabilityStatus:'usable',finalQualityScore:90,reasons:['forced_expired_for_test']}),q(blocked,generatedAt,{usabilityStatus:'blocked',finalQualityScore:0}),q(good,generatedAt,{finalQualityScore:95})],generatedAt,filterPolicy:{...pol,minFinalQualityScore:0,maxEvidenceItems:1}}); a.equal(s.items.length,1); a.ok(s.excludedItems.some((x)=>x.reasonCode==='fixture')); a.ok(s.excludedItems.some((x)=>x.reasonCode==='expired')); a.ok(s.excludedItems.some((x)=>x.reasonCode==='blocked'));
const inc=assembleReasoningEvidenceInputSnapshot({payloads:[fixture],generatedAt,filterPolicy:{...pol,includeFixtureEvidence:true,minFinalQualityScore:0}}); a.equal(inc.items.length,1); a.ok(inc.warnings.includes('only_fixture_evidence_included'));
const ordered=assembleReasoningEvidenceInputSnapshot({payloads:[p('c','2026-01-01T01:00:01.000Z'),p('a','2026-01-01T01:00:01.000Z')],generatedAt,filterPolicy:{...pol,minFinalQualityScore:0,includeFixtureEvidence:true}}); a.equal(ordered.items[0]?.payloadId,'a');
const empty=assembleReasoningEvidenceInputSnapshot({payloads:[fixture],generatedAt,filterPolicy:pol}); a.ok(empty.warnings.includes('no_usable_reasoning_evidence_items')); const rep=buildReasoningEvidenceInputAssemblyReport(empty); a.equal(rep.pass,false);
if(empty.items[0]) a.ok(validateReasoningEvidenceInputItem(empty.items[0]).ok); a.ok(validateReasoningEvidenceInputSnapshot(empty).ok); a.ok(!validateReasoningEvidenceInputSnapshot({...empty,generatedAt:'bad'}).ok);
const boundary=new CanonicalMarketIntelligenceBoundaryService(new MemoryMarketEvidenceRegistrySnapshotRepository(),new MemorySeoContentArchitectureSnapshotRepository(),new MemoryProviderSourceRequestRepository(),new MemoryProviderSourceResponseRepository(),new MemoryNormalizedMarketEvidencePayloadRepository());
await boundary.persistIngestionResult({requestId:'rq',providerId:'tiingo_market_data',capability:'market_price_history',asset:'xau_usd',region:'global',evidenceTypeId:'market_price_history',requestedAt:generatedAt,paramsJson:'{}'},{requestId:'rq',providerId:'tiingo_market_data',capability:'market_price_history',status:'success',fetchedAt:generatedAt,sourceUrl:null,rawPayloadJson:'{}',errorCode:null,errorMessage:null},[good]);
const byAsset=await boundary.getReasoningEvidenceInputByAsset('xau_usd',10,generatedAt); a.equal(byAsset.asset,'xau_usd'); const byClass=await boundary.getReasoningEvidenceInputByEvidenceClass('cross_market_rates',10,generatedAt); a.equal(byClass.evidenceClass,'cross_market_rates');}
