import { runReasoningTests } from './reasoning.test.js';
import { runEvidenceProjectionTests } from './evidence-projection.test.js';
import { runSourceSelectorTests } from './source-selector.test.js';
import { runInputAssemblerTests } from './input-assembler.test.js';
import { runPersistenceReplayTests } from './persistence-replay.test.js';
import { runCanonicalReasoningBoundaryTests } from './canonical-reasoning-boundary.test.js';
import { runDirectionalSupportTests } from './directional-support.test.js';
import { runContradictionComposerTests } from './contradiction-composer.test.js';
import { runConfidenceComposerTests } from './confidence-composer.test.js';
import { runFreshnessComposerTests } from './freshness-composer.test.js';
import { runInvalidationComposerTests } from './invalidation-composer.test.js';
import { runExplanationBuilderTests } from './explanation-builder.test.js';
import { runDeterministicReasoningEngineTests } from './deterministic-reasoning-engine.test.js';
import { runEvidenceDeltaTests } from './evidence-delta.test.js';
import { runInvalidationDeltaTests } from './invalidation-delta.test.js';
import { runChartProjectionDeltaTests } from './chart-projection-delta.test.js';
import { runCognitionDriftTests } from './cognition-drift.test.js';
import { runZoneAnchoringTests } from './zone-anchoring.test.js';
import { runPriceLevelProjectionTests } from './price-level-projection.test.js';
import { runChartProjectionBuilderTests } from './chart-projection-builder.test.js';
import { runJournalInfluenceAdoptionTests } from './journal-influence-adoption.test.js';
import { runMarketEvidenceRegistryTests } from './market-evidence-registry.test.js';
import { runSeoContentArchitectureTests } from './seo-content-architecture.test.js';
import { runMarketEvidencePersistenceTests } from './market-evidence-persistence.test.js';
import { runSeoContentPersistenceTests } from './seo-content-persistence.test.js';
import { runProviderSourcesTests } from './provider-sources.test.js';
import { runTiingoAdapterTests } from './tiingo-adapter.test.js';
import { runMarketEvidenceIngestionPersistenceTests } from './market-evidence-ingestion-persistence.test.js';
import { runTiingoFixtureIngestionTests } from './tiingo-fixture-ingestion.test.js';
import { runCotAdapterTests } from './cot-adapter.test.js';
import { runCentralBankAdapterTests } from './central-bank-adapter.test.js';
import { runTreasuryAdapterTests } from './treasury-adapter.test.js';
import { runStressConditionsAdapterTests } from './stress-conditions-adapter.test.js';
import { runRiskMarketAdapterTests } from './risk-market-adapter.test.js';
import { runMacroCalendarAdapterTests } from './macro-calendar-adapter.test.js';
import { runMacroIndicatorAdapterTests } from './macro-indicator-adapter.test.js';
import { runMarketEvidenceCoverageAuditTests } from './market-evidence-coverage-audit.test.js';
import { runEvidenceQualityTests } from './evidence-quality.test.js';
import { runReasoningMarketInputTests } from './reasoning-market-input.test.js';
import { runEvidenceWeightingTests } from './evidence-weighting.test.js';
import { runMarketCognitionTests } from './market-cognition.test.js';
import { runSeoContentFeedTests } from './seo-content-feed.test.js';
import { runProviderLiveReadinessTests } from './provider-live-readiness.test.js';
import { runScheduledIngestionTests } from './scheduled-ingestion.test.js';
import { runProviderSourceRegistryTests } from './provider-source-registry.test.js';
import { runNewsExtractionFilingsTests } from './news-extraction-filings.test.js';
import { runCryptoRiskLiquidityTests } from './crypto-risk-liquidity.test.js';
import './golden-scenario-reasoning.test.js';
import { runCognitionCalibrationTests } from './cognition-calibration.test.js';
import { runAssetCausalityMapTests } from './asset-causality-map.test.js';
import { runEconomicContextResolutionTests } from './economic-context-resolution.test.js';
import { runAssetDirectionResolutionTests } from './asset-direction-resolution.test.js';
import { runFxRelativeStrengthTests } from './fx-relative-strength.test.js';
import { runMacroSurpriseNormalizationTests } from './macro-surprise-normalization.test.js';
import { runContradictionMatrixTests } from './contradiction-matrix.test.js';
import { runConfidenceCalibrationTests } from './confidence-calibration.test.js';
import { runPriceReactionTests } from './price-reaction.test.js';
import { runProviderReliabilityTests } from './provider-reliability.test.js';
import { runMarketGoldenScenarioAcceptanceTests } from './golden-scenarios.test.js';
import { runMarketReasoningReadinessTests } from './market-reasoning-readiness.test.js';
import { runFrontendContractSchemaTests } from './frontend-contracts.test.js';
import { runRcAFormulaRegressionTests } from './rc-a-formula-regression.test.js';
import { runProviderApiGateTests } from './provider-api-gate.test.js';
import { runProviderUnmanagedCallInventoryTests } from './provider-unmanaged-call-inventory.test.js';
import { runProviderLivePayloadValidationTests } from './provider-live-payload-validation.test.js';
import { runExpectationRealityTests } from './expectation-reality.test.js';
import { runHistoricalAnalogMemoryTests } from './historical-analog-memory.test.js';
import { runContradictionActionProtocolTests } from './contradiction-action-protocol.test.js';
import { runMarketCleanlinessTests } from './market-cleanliness.test.js';
import { runNarrativeDecayTests } from './narrative-decay.test.js';

async function run(): Promise<void> {
  await runNarrativeDecayTests();
  runReasoningTests();
  runEvidenceProjectionTests();
  runDirectionalSupportTests();
  runContradictionComposerTests();
  runConfidenceComposerTests();
  runFreshnessComposerTests();
  runInvalidationComposerTests();
  runExplanationBuilderTests();
  runZoneAnchoringTests();
  runPriceLevelProjectionTests();
  runChartProjectionBuilderTests();
  runDeterministicReasoningEngineTests();
  runEvidenceDeltaTests();
  runInvalidationDeltaTests();
  runChartProjectionDeltaTests();
  runCognitionDriftTests();
  await runSourceSelectorTests();
  await runInputAssemblerTests();
  await runPersistenceReplayTests();
  await runCanonicalReasoningBoundaryTests();
  await runJournalInfluenceAdoptionTests();
  runMarketEvidenceRegistryTests();
  runSeoContentArchitectureTests();
  await runMarketEvidencePersistenceTests();
  await runSeoContentPersistenceTests();
  runProviderSourcesTests();
  await runTiingoAdapterTests();
  await runMarketEvidenceIngestionPersistenceTests();
  await runTiingoFixtureIngestionTests();
  await runCotAdapterTests();
  await runCentralBankAdapterTests();
  await runTreasuryAdapterTests();
  await runStressConditionsAdapterTests();
  await runRiskMarketAdapterTests();
  await runMacroCalendarAdapterTests();
  await runMacroIndicatorAdapterTests();
  runMarketEvidenceCoverageAuditTests();
  await runEvidenceQualityTests();
  await runReasoningMarketInputTests();
  await runEvidenceWeightingTests();
  await runMarketCognitionTests();
  runSeoContentFeedTests();
  await runProviderLiveReadinessTests();
  await runScheduledIngestionTests();
  await runProviderSourceRegistryTests();
  runNewsExtractionFilingsTests();
  runCryptoRiskLiquidityTests();
  runCognitionCalibrationTests();
  runAssetCausalityMapTests();
  runEconomicContextResolutionTests();
  runAssetDirectionResolutionTests();
  runFxRelativeStrengthTests();
  runMacroSurpriseNormalizationTests();
  runContradictionMatrixTests();
  runConfidenceCalibrationTests();
  runPriceReactionTests();
  runProviderReliabilityTests();
  runMarketGoldenScenarioAcceptanceTests();
  runMarketReasoningReadinessTests();
  runFrontendContractSchemaTests();
  await runProviderApiGateTests();
  runProviderUnmanagedCallInventoryTests();
  await runProviderLivePayloadValidationTests();
  await runExpectationRealityTests();
  await runHistoricalAnalogMemoryTests();
  await runContradictionActionProtocolTests();
  await runMarketCleanlinessTests();
  runRcAFormulaRegressionTests();
  console.log('reasoning runtime contract tests passed');
}

void run();
