import type { MarketCognitionAssemblyReport, MarketCognitionSignalKind, MarketCognitionSnapshot, MarketConfidenceCalibrationBuildOptions, WeightedEvidenceSnapshot } from '@elceo/types';
import { validateMarketCognitionSnapshot } from '@elceo/schemas';
import { evaluateContradictionsFromWeightedSnapshot } from '../contradiction-matrix/index';
import { buildConfidenceDecomposition } from './confidence-decomposition';
import { buildContradictionFlagsWithExpandedMatrix } from './contradiction-signals';
import { buildMarketCognitionNarrativeSummary } from './narrative-summary';
import { buildFreshnessWarningSignals, buildPressureSignal, groupWeightedEvidenceBySignalKind } from './pressure-signals';
export function buildMarketCognitionSnapshot(weightedSnapshot: WeightedEvidenceSnapshot, generatedAt?: string, options?: MarketConfidenceCalibrationBuildOptions): MarketCognitionSnapshot { const at=generatedAt??weightedSnapshot.generatedAt; const snapshotForAt={...weightedSnapshot,generatedAt:at}; const grouped=groupWeightedEvidenceBySignalKind(snapshotForAt); const pressureKinds=Object.keys(grouped) as MarketCognitionSignalKind[]; const pressureSignals=pressureKinds.map((k)=>buildPressureSignal(k,snapshotForAt,grouped[k]??[])); const freshnessSignals=buildFreshnessWarningSignals(snapshotForAt); const signals=[...pressureSignals,...freshnessSignals]; const contradictionMatrix=options?.contradictionMatrix ?? evaluateContradictionsFromWeightedSnapshot(snapshotForAt, { providerReliabilitySupplied:false, sourceIndependenceVerified:false, ...(options?.priceReaction ? { priceReaction: options.priceReaction } : {}), ...(options?.priceReactionAvailable !== undefined ? { priceReactionAvailable: options.priceReactionAvailable } : {}) }); const contradictions=buildContradictionFlagsWithExpandedMatrix(snapshotForAt,signals,contradictionMatrix); const confidence=buildConfidenceDecomposition(snapshotForAt,signals,contradictions,{ ...options, contradictionMatrix }); const narrative=buildMarketCognitionNarrativeSummary(snapshotForAt,signals,contradictions,confidence); const snapshot={snapshotId:`cognition|${weightedSnapshot.asset}|${weightedSnapshot.horizon}|${at}`,generatedAt:at,asset:weightedSnapshot.asset,horizon:weightedSnapshot.horizon,weightedEvidenceSnapshotId:weightedSnapshot.snapshotId,signals,confidence,contradictions,narrative,warnings:[...weightedSnapshot.warnings,...freshnessSignals.flatMap((s)=>s.warnings)]}; const v=validateMarketCognitionSnapshot(snapshot); if(v.ok===false) throw new Error(`invalid_market_cognition_snapshot:${v.errors.join('|')}`); return snapshot; }
export function buildMarketCognitionAssemblyReport(snapshot: MarketCognitionSnapshot): MarketCognitionAssemblyReport { return {generatedAt:snapshot.generatedAt,asset:snapshot.asset,horizon:snapshot.horizon,signalCount:snapshot.signals.length,contradictionCount:snapshot.contradictions.length,finalConfidence:snapshot.confidence.finalConfidence,warnings:[...snapshot.warnings],pass:snapshot.signals.length>0&&snapshot.confidence.finalConfidence>=0}; }
