import type { MarketEvidenceClass, NormalizedMarketEvidencePayload, ProviderSourceRequest, ProviderSourceResponse } from '@elceo/types';
import type { MarketEvidenceProviderAdapter, ProviderManagedExecution } from '../normalization-contracts';
import { buildMetadataJson, buildNormalizedPayloadId, buildValuesJson, clampConfidenceScore } from '../normalization-helpers';
import { getProviderDescriptor } from '../provider-capability-registry';

export type FinnhubAdapterMode='fixture'|'live_disabled'|'live_enabled';
export type FinnhubRuntimeConfig={mode?:FinnhubAdapterMode;apiKey?:string|null;timeoutMs?:number|null;fetchImpl?:typeof fetch};
type ResolvedConfig={mode:FinnhubAdapterMode;apiKey:string|null;timeoutMs:number;fetchImpl:typeof fetch};
type CandleEnvelope={s?:string;t?:number[];o?:number[];h?:number[];l?:number[];c?:number[];v?:number[]};
type EconomicEvent={actual?:number|string|null;country?:string|null;estimate?:number|string|null;event?:string|null;impact?:string|null;prev?:number|string|null;time?:string|null;unit?:string|null};
type EconomicCalendarEnvelope={economicCalendar?:EconomicEvent[]};

const ORIGIN='https://finnhub.io';
const API='/api/v1';
const FX_SYMBOLS:Readonly<Record<string,string>>={eur_usd:'OANDA:EUR_USD',gbp_usd:'OANDA:GBP_USD',usd_jpy:'OANDA:USD_JPY',usd_chf:'OANDA:USD_CHF',aud_usd:'OANDA:AUD_USD',nzd_usd:'OANDA:NZD_USD',usd_cad:'OANDA:USD_CAD'};
const CRYPTO_SYMBOLS:Readonly<Record<string,string>>={btc_usd:'BINANCE:BTCUSDT'};
const SYMBOL_TO_ASSET:Readonly<Record<string,string>>=Object.fromEntries([...Object.entries(FX_SYMBOLS),...Object.entries(CRYPTO_SYMBOLS)].map(([asset,symbol])=>[symbol,asset]));
const MARKET_FIXTURE:CandleEnvelope={s:'ok',t:[1789344000],o:[1.172],h:[1.178],l:[1.169],c:[1.175]};
const MACRO_FIXTURE:EconomicCalendarEnvelope={economicCalendar:[{actual:2.8,country:'US',estimate:2.9,event:'CPI YoY',impact:'high',prev:3,time:'2026-09-14T12:30:00',unit:'%'}]};

export class FinnhubMarketDataFallbackAdapter implements MarketEvidenceProviderAdapter{
 readonly descriptor=getProviderDescriptor('finnhub_market_data')??(()=>{throw new Error('missing_finnhub_market_descriptor')})();
 constructor(private readonly config:FinnhubRuntimeConfig={}){}
 async fetch(request:ProviderSourceRequest):Promise<ProviderSourceResponse>{return this.fetchInternal(request);}
 async fetchManaged(request:ProviderSourceRequest,execution:ProviderManagedExecution):Promise<ProviderSourceResponse>{return this.fetchInternal(request,execution);}
 private async fetchInternal(request:ProviderSourceRequest,execution?:ProviderManagedExecution):Promise<ProviderSourceResponse>{
  if(request.providerId!=='finnhub_market_data'||request.capability!=='market_price_history')return fail(request,'finnhub_market_request_mismatch','Finnhub market request does not match the bounded fallback profile','unsupported');
  if(!request.asset)return fail(request,'missing_asset','Finnhub market fallback requires an asset');
  const symbol=FX_SYMBOLS[request.asset]??CRYPTO_SYMBOLS[request.asset];if(!symbol)return fail(request,'finnhub_unsupported_fallback_asset',`Finnhub fallback is not approved for ${request.asset}`,'unsupported');
  const cfg=resolveConfig(this.config);if(cfg.mode==='fixture')return success(request,JSON.stringify(MARKET_FIXTURE),`fixture://finnhub_market_data/${request.asset}`);if(cfg.mode!=='live_enabled')return fail(request,'finnhub_live_disabled','Finnhub live market fallback is disabled');if(!cfg.apiKey)return fail(request,'missing_api_key','FINNHUB_API_KEY is required');
  const params=parseMarketParams(request.paramsJson,request.requestedAt),endpoint=FX_SYMBOLS[request.asset]?'/forex/candle':'/crypto/candle',url=new URL(`${API}${endpoint}`,ORIGIN);url.searchParams.set('symbol',symbol);url.searchParams.set('resolution','D');url.searchParams.set('from',String(Math.floor(Date.parse(`${params.startDate}T00:00:00Z`)/1000)));url.searchParams.set('to',String(Math.floor(Date.parse(`${params.endDate}T23:59:59Z`)/1000)));url.searchParams.set('token',cfg.apiKey);
  return fetchText(request,url,cfg,execution);
 }
 async normalize(response:ProviderSourceResponse):Promise<NormalizedMarketEvidencePayload[]>{if(!response.rawPayloadJson)return[];const body=JSON.parse(response.rawPayloadJson) as CandleEnvelope;if(body.s!=='ok'||!Array.isArray(body.t)||!Array.isArray(body.c)||!Array.isArray(body.o)||!Array.isArray(body.h)||!Array.isArray(body.l))return[];const asset=assetFromSource(response.sourceUrl);if(!asset)return[];return body.t.flatMap((timestamp,index)=>{const close=finite(body.c?.[index]),open=finite(body.o?.[index]),high=finite(body.h?.[index]),low=finite(body.l?.[index]);if(close===null||open===null||high===null||low===null||high<low)return[];const observedAt=new Date(timestamp*1000).toISOString(),evidenceClass:MarketEvidenceClass=asset==='btc_usd'?'crypto_market_structure':'cross_market_rates',volume=finite(body.v?.[index]);return[{payloadId:buildNormalizedPayloadId('finnhub_market_data','market_price_history',observedAt,asset),evidenceTypeId:'market_price_history',evidenceClass,providerId:'finnhub_market_data',sourceId:'finnhub_market_data',region:'global',asset,observedAt,publishedAt:null,normalizedAt:response.fetchedAt,confidenceScore:clampConfidenceScore(82),dataQuality:volume===null?'medium':'high',valuesJson:buildValuesJson({o:open,h:high,l:low,c:close,v:volume}),metadataJson:buildMetadataJson({canonicalSourceId:'finnhub_market_data',role:'uptime_fallback',primarySourceId:'tiingo_market_data',providerEndpoint:asset==='btc_usd'?'crypto/candle':'forex/candle',timeframe:'1d',sourceUrl:response.sourceUrl})}];});}
}

export class FinnhubMacroCalendarEvidenceAdapter implements MarketEvidenceProviderAdapter{
 readonly descriptor=getProviderDescriptor('finnhub_macro')??(()=>{throw new Error('missing_finnhub_macro_descriptor')})();
 constructor(private readonly config:FinnhubRuntimeConfig={}){}
 async fetch(request:ProviderSourceRequest):Promise<ProviderSourceResponse>{return this.fetchInternal(request);}
 async fetchManaged(request:ProviderSourceRequest,execution:ProviderManagedExecution):Promise<ProviderSourceResponse>{return this.fetchInternal(request,execution);}
 private async fetchInternal(request:ProviderSourceRequest,execution?:ProviderManagedExecution):Promise<ProviderSourceResponse>{
  if(request.providerId!=='finnhub_macro'||request.capability!=='economic_calendar')return fail(request,'finnhub_macro_request_mismatch','Finnhub macro request does not match the calendar profile','unsupported');
  const cfg=resolveConfig(this.config);if(cfg.mode==='fixture')return success(request,JSON.stringify(MACRO_FIXTURE),'fixture://finnhub_macro/economic_calendar');if(cfg.mode!=='live_enabled')return fail(request,'finnhub_live_disabled','Finnhub live macro calendar is disabled');if(!cfg.apiKey)return fail(request,'missing_api_key','FINNHUB_API_KEY is required');
  const range=parseCalendarParams(request.paramsJson,request.requestedAt),url=new URL(`${API}/calendar/economic`,ORIGIN);url.searchParams.set('from',range.from);url.searchParams.set('to',range.to);url.searchParams.set('token',cfg.apiKey);return fetchText(request,url,cfg,execution);
 }
 async normalize(response:ProviderSourceResponse):Promise<NormalizedMarketEvidencePayload[]>{if(!response.rawPayloadJson)return[];const body=JSON.parse(response.rawPayloadJson) as EconomicCalendarEnvelope;if(!Array.isArray(body.economicCalendar))return[];return body.economicCalendar.flatMap((event,index)=>{const name=clean(event.event);const country=clean(event.country);const time=toUtc(event.time);if(!name||!country||!time)return[];const actual=nullableNumber(event.actual),estimate=nullableNumber(event.estimate),previous=nullableNumber(event.prev),unit=clean(event.unit),impact=normalizeImpact(event.impact),key=`${country}:${name}:${time}`;return[{payloadId:buildNormalizedPayloadId('finnhub_macro','economic_calendar',time,null)+`:${index}`,evidenceTypeId:'economic_calendar',evidenceClass:'macro_calendar',providerId:'finnhub_macro',sourceId:'finnhub_macro',region:country.toLowerCase(),asset:null,observedAt:time,publishedAt:null,normalizedAt:response.fetchedAt,confidenceScore:clampConfidenceScore(actual===null?76:80),dataQuality:'medium',valuesJson:buildValuesJson({event:name,country,actual,estimate,previous,unit,impact}),metadataJson:buildMetadataJson({canonicalSourceId:'finnhub_macro',correlationKey:key,authority:'secondary_aggregator',authoritativeActual:false,role:'calendar_expectation_and_continuity',officialActualRequired:true,sourceUrl:response.sourceUrl})}];});}
}

function resolveConfig(config:FinnhubRuntimeConfig):ResolvedConfig{return{mode:config.mode??'live_disabled',apiKey:config.apiKey?.trim()||null,timeoutMs:config.timeoutMs&&Number.isFinite(config.timeoutMs)&&config.timeoutMs>0?config.timeoutMs:10000,fetchImpl:config.fetchImpl??fetch};}
async function fetchText(request:ProviderSourceRequest,url:URL,cfg:ResolvedConfig,managed?:ProviderManagedExecution):Promise<ProviderSourceResponse>{const controller=managed?null:new AbortController(),timer=managed?null:setTimeout(()=>controller!.abort(),cfg.timeoutMs),signal=managed?.signal??controller!.signal;try{const response=await cfg.fetchImpl(url,{signal,headers:{'X-Finnhub-Token':cfg.apiKey??''}});if(!response.ok)return fail(request,response.status===429?'rate_limited':response.status===401||response.status===403?'finnhub_access_denied':response.status>=500?'provider_5xx':'finnhub_request_rejected',`Finnhub request failed (${response.status})`);const raw=await response.text();return raw.trim()?success(request,raw,sanitize(url)):({...base(request),status:'empty',sourceUrl:sanitize(url)});}catch(error){if(error instanceof Error&&error.name==='AbortError')return fail(request,'finnhub_timeout','Finnhub request timed out');return fail(request,'finnhub_fetch_error','Finnhub request failed');}finally{if(timer)clearTimeout(timer);}}
function parseMarketParams(paramsJson:string,requestedAt:string):{startDate:string;endDate:string}{const raw=parseObject(paramsJson),endDate=validDate(raw.endDate)?String(raw.endDate):new Date(requestedAt).toISOString().slice(0,10),startDate=validDate(raw.startDate)?String(raw.startDate):offsetDate(endDate,-7);if(startDate>endDate)throw new Error('finnhub_invalid_market_date_range');if((Date.parse(`${endDate}T00:00:00Z`)-Date.parse(`${startDate}T00:00:00Z`))/86400000>31)throw new Error('finnhub_market_window_too_large');return{startDate,endDate};}
function parseCalendarParams(paramsJson:string,requestedAt:string):{from:string;to:string}{const raw=parseObject(paramsJson),center=new Date(requestedAt).toISOString().slice(0,10),from=validDate(raw.from)?String(raw.from):offsetDate(center,-1),to=validDate(raw.to)?String(raw.to):offsetDate(center,2);if(from>to)throw new Error('finnhub_invalid_calendar_range');if((Date.parse(`${to}T00:00:00Z`)-Date.parse(`${from}T00:00:00Z`))/86400000>7)throw new Error('finnhub_calendar_window_too_large');return{from,to};}
function parseObject(value:string):Record<string,unknown>{try{const parsed=JSON.parse(value);return parsed&&typeof parsed==='object'&&!Array.isArray(parsed)?parsed as Record<string,unknown>:{};}catch{return{};}}
function validDate(value:unknown):boolean{return typeof value==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(value)&&!Number.isNaN(Date.parse(`${value}T00:00:00Z`));}
function offsetDate(value:string,days:number):string{const date=new Date(`${value}T00:00:00Z`);date.setUTCDate(date.getUTCDate()+days);return date.toISOString().slice(0,10);}
function sanitize(url:URL):string{const clean=new URL(url);clean.searchParams.delete('token');return clean.toString();}
function success(request:ProviderSourceRequest,rawPayloadJson:string,sourceUrl:string):ProviderSourceResponse{return{...base(request),status:'success',rawPayloadJson,sourceUrl};}
function base(request:ProviderSourceRequest):ProviderSourceResponse{return{requestId:request.requestId,providerId:request.providerId,capability:request.capability,status:'failed',fetchedAt:new Date().toISOString(),sourceUrl:null,rawPayloadJson:null,errorCode:null,errorMessage:null};}
function fail(request:ProviderSourceRequest,errorCode:string,errorMessage:string,status:'failed'|'unsupported'='failed'):ProviderSourceResponse{return{...base(request),status,errorCode,errorMessage};}
function finite(value:unknown):number|null{const n=typeof value==='number'?value:Number(value);return Number.isFinite(n)?n:null;}
function nullableNumber(value:unknown):number|null{return value===undefined||value===null||value===''?null:finite(value);}
function clean(value:unknown):string|null{return typeof value==='string'&&value.trim()?value.trim():null;}
function normalizeImpact(value:unknown):'low'|'medium'|'high'{const s=String(value??'').toLowerCase();return s.includes('high')?'high':s.includes('low')?'low':'medium';}
function toUtc(value:unknown):string|null{if(typeof value!=='string'||!value.trim())return null;const raw=value.trim(),withZone=/Z$|[+-]\d{2}:?\d{2}$/.test(raw)?raw:`${raw}Z`,time=Date.parse(withZone);return Number.isFinite(time)?new Date(time).toISOString():null;}
function assetFromSource(sourceUrl:string|null):string|null{if(!sourceUrl)return null;if(sourceUrl.startsWith('fixture://finnhub_market_data/'))return sourceUrl.slice('fixture://finnhub_market_data/'.length)||null;try{const url=new URL(sourceUrl),symbol=url.searchParams.get('symbol');return symbol?SYMBOL_TO_ASSET[symbol]??null:null;}catch{return null;}}
