import { createHash, randomUUID } from 'node:crypto';
import { queryDb, withDbTransaction } from '../db/client';

export type BillingInterval='monthly'|'quarterly'|'yearly';
export type PaymentProvider='stripe'|'korapay';
export type CommercialPrice={id:string;planCode:string;billingInterval:BillingInterval;currency:string;amountMinor:string;version:number;effectiveFrom:string};
const currency=(value:string)=>{const v=value.toUpperCase();if(!/^[A-Z0-9]{3,12}$/.test(v))throw new Error('invalid_commercial_currency');return v};
export async function resolveActiveCommercialPrice(input:{planCode:string;billingInterval:BillingInterval;currency:string}):Promise<CommercialPrice>{
 const rows=await queryDb<any>(`SELECT commercial_price_version_id,plan_code,billing_interval,currency,amount_minor::text,version,effective_from FROM commercial_price_versions WHERE plan_code=$1 AND billing_interval=$2 AND currency=$3 AND status='active' AND effective_from<=now() ORDER BY version DESC LIMIT 1`,[input.planCode,input.billingInterval,currency(input.currency)]);
 if(!rows[0])throw new Error('commercial_price_not_configured');const x=rows[0];return {id:x.commercial_price_version_id,planCode:x.plan_code,billingInterval:x.billing_interval,currency:x.currency,amountMinor:x.amount_minor,version:Number(x.version),effectiveFrom:x.effective_from};
}
export async function assertProviderCapability(input:{provider:PaymentProvider;environment:'sandbox'|'production';rail:string;currency:string;recurring?:boolean}){
 const rows=await queryDb<any>(`SELECT * FROM payment_provider_capabilities WHERE provider=$1 AND environment=$2 AND rail=$3 AND currency=$4 AND merchant_enabled AND checkout_supported`,[input.provider,input.environment,input.rail,currency(input.currency)]);
 if(!rows[0]||(input.recurring&&!rows[0].recurring_supported))throw new Error('payment_provider_capability_not_configured');return rows[0];
}
export async function createCommercialPriceVersion(input:{actorSuperAdminId:string;planCode:string;billingInterval:BillingInterval;currency:string;amountMinor:string;effectiveFrom:string;reasonCode:string;operatorNote:string;idempotencyKey:string}){
 if(!/^[1-9][0-9]*$/.test(input.amountMinor)||input.idempotencyKey.length<8||input.idempotencyKey.length>255||!input.reasonCode||!input.operatorNote)throw new Error('invalid_commercial_price_update');
 const normalized={...input,currency:currency(input.currency)};const hash=createHash('sha256').update(JSON.stringify(normalized)).digest('hex');
 return withDbTransaction(async tx=>{const prior=await tx.query(`SELECT commercial_price_version_id,mutation_payload_hash FROM commercial_price_versions WHERE actor_super_admin_id=$1 AND mutation_idempotency_key=$2`,[input.actorSuperAdminId,input.idempotencyKey]);if(prior.rows[0]){if(prior.rows[0].mutation_payload_hash!==hash)throw new Error('commercial_price_idempotency_conflict');return {id:prior.rows[0].commercial_price_version_id,reused:true};}await tx.query(`SELECT pg_advisory_xact_lock(hashtextextended($1,0))`,[`${normalized.planCode}:${normalized.billingInterval}:${normalized.currency}`]);const version=Number((await tx.query(`SELECT COALESCE(max(version),0)+1 v FROM commercial_price_versions WHERE plan_code=$1 AND billing_interval=$2 AND currency=$3`,[normalized.planCode,normalized.billingInterval,normalized.currency])).rows[0]?.v??1);await tx.query(`UPDATE commercial_price_versions SET status='superseded',retired_at=$4 WHERE plan_code=$1 AND billing_interval=$2 AND currency=$3 AND status='active'`,[normalized.planCode,normalized.billingInterval,normalized.currency,normalized.effectiveFrom]);const id=randomUUID();await tx.query(`INSERT INTO commercial_price_versions(commercial_price_version_id,plan_code,billing_interval,currency,amount_minor,status,effective_from,actor_super_admin_id,reason_code,operator_note,version,mutation_idempotency_key,mutation_payload_hash) VALUES($1,$2,$3,$4,$5,'active',$6,$7,$8,$9,$10,$11,$12)`,[id,normalized.planCode,normalized.billingInterval,normalized.currency,normalized.amountMinor,normalized.effectiveFrom,normalized.actorSuperAdminId,normalized.reasonCode,normalized.operatorNote,version,normalized.idempotencyKey,hash]);return {id,version,reused:false};});
}
