import type { FrontendAssetDashboardPayload, FrontendContractCoverageReport, FrontendEvidenceFeedPayload, FrontendGoldenScenarioPreviewPayload, FrontendJournalPortfolioContextPlaceholder, FrontendMacroContextPayload, FrontendMarketCognitionSnapshot, FrontendMarketOverviewPayload, FrontendMockPayloadRegistry, FrontendNewsNarrativePayload, FrontendProviderReadinessPayload, FrontendRiskLiquidityPayload, FrontendScheduledIngestionStatusPayload, FrontendSupportedAsset, FrontendReasoningDiagnostic, TradableLaunchAsset } from '@elceo/types';
import { FRONTEND_CONTRACT_SURFACES, MARKET_REASONING_DIAGNOSTIC_ASSETS } from '@elceo/types';
import { getProviderSourceRegistrySnapshot } from '../provider-source-registry/index';
import { listMarketGoldenScenarios } from '../golden-scenarios/index';

const UPDATED_AT='2026-05-15T00:00:00.000Z';
const assets: FrontendSupportedAsset[]=[
{assetId:'aud_usd',displaySymbol:'AUD/USD',assetName:'Australian Dollar vs US Dollar',tier:'tier_1b',marketFamily:'fx',supportedStatus:'supported',mockDataStatus:'fixture_ready',userVisibility:'public'},
{assetId:'btc_usd',displaySymbol:'BTC/USD',assetName:'Bitcoin vs US Dollar',tier:'tier_1a',marketFamily:'crypto',supportedStatus:'supported',mockDataStatus:'fixture_ready',userVisibility:'public'},
{assetId:'de30',displaySymbol:'DE30',assetName:'Germany 30 Index',tier:'tier_1a',marketFamily:'equity_index',supportedStatus:'supported',mockDataStatus:'fixture_ready',userVisibility:'public'},
{assetId:'eur_usd',displaySymbol:'EUR/USD',assetName:'Euro vs US Dollar',tier:'tier_1a',marketFamily:'fx',supportedStatus:'supported',mockDataStatus:'fixture_ready',userVisibility:'public'},
{assetId:'gbp_usd',displaySymbol:'GBP/USD',assetName:'British Pound vs US Dollar',tier:'tier_1a',marketFamily:'fx',supportedStatus:'supported',mockDataStatus:'fixture_ready',userVisibility:'public'},
{assetId:'nasdaq_100',displaySymbol:'NASDAQ 100',assetName:'Nasdaq 100 Index',tier:'tier_1a',marketFamily:'equity_index',supportedStatus:'supported',mockDataStatus:'fixture_ready',userVisibility:'public'},
{assetId:'nzd_usd',displaySymbol:'NZD/USD',assetName:'New Zealand Dollar vs US Dollar',tier:'tier_1b',marketFamily:'fx',supportedStatus:'supported',mockDataStatus:'fixture_ready',userVisibility:'public'},
{assetId:'sp500',displaySymbol:'S&P 500',assetName:'S&P 500 Index',tier:'tier_1a',marketFamily:'equity_index',supportedStatus:'supported',mockDataStatus:'fixture_ready',userVisibility:'public'},
{assetId:'usd_cad',displaySymbol:'USD/CAD',assetName:'US Dollar vs Canadian Dollar',tier:'tier_1b',marketFamily:'fx',supportedStatus:'supported',mockDataStatus:'fixture_ready',userVisibility:'public'},
{assetId:'usd_chf',displaySymbol:'USD/CHF',assetName:'US Dollar vs Swiss Franc',tier:'tier_1b',marketFamily:'fx',supportedStatus:'supported',mockDataStatus:'fixture_ready',userVisibility:'public'},
{assetId:'usd_jpy',displaySymbol:'USD/JPY',assetName:'US Dollar vs Japanese Yen',tier:'tier_1a',marketFamily:'fx',supportedStatus:'supported',mockDataStatus:'fixture_ready',userVisibility:'public'},
{assetId:'xau_usd',displaySymbol:'XAU/USD',assetName:'Gold Spot',tier:'tier_1a',marketFamily:'metals',supportedStatus:'supported',mockDataStatus:'fixture_ready',userVisibility:'public'}
];
const cog=(asset:TradableLaunchAsset): FrontendMarketCognitionSnapshot=>({pressureState:'mixed',confidenceBand:'medium' as const,confidenceScore:0.62,topEvidenceClasses:['macro','news','risk_liquidity'],cognitionThemes:[`fixture:${asset}`,'cross-asset-context'],reasoningNotes:['Fixture-derived deterministic snapshot.','No live provider calls enabled.'],uncertaintyFlags:['contradiction_window_open'],contradictionDetected:true,freshnessWarning:false,guardrailStatus:'pass',sourceFixtureRefs:[`fixture/${asset}/baseline`]});
const evidence=(asset?:TradableLaunchAsset):FrontendEvidenceFeedPayload=>({payloadKind:'fixture_mock',userVisibility:'public',updatedAt:UPDATED_AT,items:[1,2,3].map((n)=>({evidenceId:`ev-${asset??'all'}-${n}`,displayTitle:`Fixture evidence ${n}`,displaySummary:'Deterministic evidence item for UI wiring.',evidenceKind:n===1?'macro':n===2?'news':'risk_liquidity',sourceFamily:n===1?'macro_official':n===2?'news_extraction':'risk_liquidity',affectedAssets:[asset??'eur_usd'],observedAt:'2026-05-14T00:00:00.000Z',freshnessState:'fresh',qualityBand:'medium',importanceScore:80-n,displayTags:['fixture','mock','ui-safe'],mockFixtureMarker:'mock_fixture_data'}))});
const macro=(asset?:TradableLaunchAsset):FrontendMacroContextPayload=>({payloadKind:'fixture_mock',userVisibility:'public',headline:`Macro context ${asset??'all assets'}`,contextPoints:['Official-macro fixture aligned.','Decision-support only.'],updatedAt:UPDATED_AT});
const narrative=(asset?:TradableLaunchAsset):FrontendNewsNarrativePayload=>({payloadKind:'fixture_mock',userVisibility:'public',headline:`Narrative context ${asset??'all assets'}`,contextPoints:['News/extraction fixtures only.','No recommendation language.'],updatedAt:UPDATED_AT});
const risk=(asset?:TradableLaunchAsset):FrontendRiskLiquidityPayload=>({payloadKind:'fixture_mock',userVisibility:'public',headline:`Risk/liquidity ${asset??'all assets'}`,contextPoints:['Risk regime uses fixture rails.'],riskState:'contained',updatedAt:UPDATED_AT});

export const getFrontendSupportedAssets=()=>assets;
export const getFrontendReasoningDiagnostics=():FrontendReasoningDiagnostic[]=>MARKET_REASONING_DIAGNOSTIC_ASSETS.map((assetId)=>({assetId,supportRole:'reasoning_diagnostic',tradable:false,displaySymbol:assetId.toUpperCase(),assetName:assetId==='dxy'?'US Dollar Index':'Volatility Index',marketFamily:assetId==='dxy'?'macro_index':'volatility',userVisibility:'public'}));
export const getFrontendMarketOverviewPayload=():FrontendMarketOverviewPayload=>({payloadKind:'fixture_mock',userVisibility:'public',assets,highlights:['Mock fixture mode active','Live provider activation blocked'],updatedAt:UPDATED_AT});
export const getFrontendMarketCognitionSnapshot=(asset:TradableLaunchAsset)=>cog(asset);
export const getFrontendEvidenceFeedPayload=(asset?:TradableLaunchAsset)=>evidence(asset);
export const getFrontendMacroContextPayload=(asset?:TradableLaunchAsset)=>macro(asset);
export const getFrontendNewsNarrativePayload=(asset?:TradableLaunchAsset)=>narrative(asset);
export const getFrontendRiskLiquidityPayload=(asset?:TradableLaunchAsset)=>risk(asset);
export const getFrontendConfidenceDecompositionPayload=(asset:TradableLaunchAsset)=>({assetId:asset,factors:[{label:'evidence_quality',score:0.67},{label:'freshness',score:0.63},{label:'contradiction_penalty',score:0.54}],confidenceBand:'medium' as const,updatedAt:UPDATED_AT});
export const getFrontendContradictionPanelPayload=(asset:TradableLaunchAsset)=>({assetId:asset,contradictionDetected:true,contradictionItems:['Macro surprise vs positioning'],uncertaintyFlags:['event-risk-window'],updatedAt:UPDATED_AT});
export const getFrontendAssetDashboardPayload=(asset:TradableLaunchAsset):FrontendAssetDashboardPayload=>{ const a=assets.find(x=>x.assetId===asset)!; return { ...a, marketCognitionSnapshot:cog(asset), evidenceFeedPreview:evidence(asset), macroContext:macro(asset), newsNarrative:narrative(asset), riskLiquidity:risk(asset), confidenceDecomposition:getFrontendConfidenceDecompositionPayload(asset), contradictionPanel:getFrontendContradictionPanelPayload(asset), freshnessState:'fresh', updatedAt:UPDATED_AT, disclaimerNote:'Decision-support preview. No trade recommendation.'}; };
export const getFrontendProviderReadinessPayload=():FrontendProviderReadinessPayload=>{ const snap=getProviderSourceRegistrySnapshot(UPDATED_AT); const counts=snap.sources.reduce((acc,s)=>({...acc,[s.family]:(acc[s.family]??0)+1}),{market_data:0,macro_official:0,positioning:0,news_extraction:0,filings_company_etf:0,crypto:0,risk_liquidity:0}); return {payloadKind:'internal_admin_mock',totalSources:snap.sources.length,fixtureReadyCount:snap.sources.filter(s=>s.fixtureReadiness==='ready').length,dryRunReadyCount:snap.sources.filter(s=>s.activationStage==='dry_run_ready').length,liveBlockedCount:snap.sources.filter(s=>s.liveActivationMode==='blocked_by_default').length,plannedCount:snap.sources.filter(s=>s.activationStage==='not_started').length,sourceFamilyCounts:counts,activationBlocked:true,operatorNote:'Fixture and dry-run only. Live activation blocked by policy.',statuses:['fixture_ready','dry_run_ready','live_blocked','not_started'],userVisibility:'admin_internal',updatedAt:UPDATED_AT}; };
export const getFrontendScheduledIngestionStatusPayload=():FrontendScheduledIngestionStatusPayload=>({payloadKind:'internal_admin_mock',dryRunAvailable:true,replayAvailable:true,latestRunStatus:'succeeded',replayCount:12,blockedLiveCount:4,freshnessWarningCount:1,fixtureModeStatus:'fixture_only',operatorNote:'Scheduled ingestion preview uses fixture/dry-run execution.',userVisibility:'admin_internal',updatedAt:UPDATED_AT});
export const getFrontendGoldenScenarioPreviewPayload=(asset?:TradableLaunchAsset):FrontendGoldenScenarioPreviewPayload=>({payloadKind:'fixture_mock',asset:asset??'all',scenarioCount:listMarketGoldenScenarios().length,calibrationStatus:'pass',notes:['Golden scenarios referenced for UI contract only'],updatedAt:UPDATED_AT,userVisibility:'authenticated'});
export const getFrontendJournalPortfolioContextPlaceholder=(asset?:TradableLaunchAsset):FrontendJournalPortfolioContextPlaceholder=>({payloadKind:'fixture_mock',asset:asset??'all',enabled:false,note:'Placeholder only; journal/portfolio integration deferred.',updatedAt:UPDATED_AT,userVisibility:'authenticated'});
export const getFrontendMockPayloadRegistry=():FrontendMockPayloadRegistry=>({status:'mock_fixture_only',surfaces:Object.fromEntries(FRONTEND_CONTRACT_SURFACES.map((s)=>[s,{status:'active_mock',userVisibility:s.includes('admin_internal')?'admin_internal':'public'}])) as FrontendMockPayloadRegistry['surfaces'],updatedAt:UPDATED_AT});
export const getFrontendContractCoverageReport=():FrontendContractCoverageReport=>({updatedAt:UPDATED_AT,supportedTradableAssets:assets.map(a=>a.assetId),reasoningDiagnosticAssets:[...MARKET_REASONING_DIAGNOSTIC_ASSETS],surfaces:[...FRONTEND_CONTRACT_SURFACES],deterministicOrdering:true,liveCallsUsed:false});