import type { BillingReconciliationStatus, BillingLifecycleProviderKind, BillingLifecycleSnapshot, BillingReconciliationRun, BillingLifecycleSubscriptionState } from './billing-lifecycle';
import type { BillingPolicyDecisionCode, BillingPolicySeverity, BillingPolicySnapshot, BillingPolicyTransition, BillingOperationalState } from './billing-policy';
import type { ElceoAccountState, ElceoPlanKind } from './entitlements';

export type BillingAdminHealthState='healthy'|'attention_needed'|'degraded'|'critical';
export type BillingReconciliationFailureKind='subject_resolution_failed'|'provider_mapping_missing'|'provider_mapping_fallback_free'|'entitlement_sync_failed'|'persistence_failed'|'policy_restricted'|'policy_free_fallback'|'replay_deserialize_failed'|'unknown_failure';
export type BillingRetryCandidateReason='latest_reconciliation_failed'|'provider_mapping_fallback_free'|'restricted_due_to_past_due'|'restricted_due_to_paused'|'restricted_due_to_incomplete'|'pending_re_evaluation_after_recovery'|'missing_subscription_after_provider_event';
export type BillingOperationalSummaryLite={operationalState:BillingOperationalState;summary:string;};
export type BillingAdminOperationalSummary={generatedAt:string;healthState:BillingAdminHealthState;totalSubjectsWithBillingState:number;activePremiumCount:number;trialingPremiumCount:number;restrictedPremiumCount:number;freeFallbackCount:number;failedRecentReconciliations:number;degradedRecentReconciliations:number;providerMappingFallbackCount:number;recentPolicyRestrictionCount:number;recentRecoveredCount:number;latestReconciliationStatus:BillingReconciliationStatus|null;latestPolicyDecisionCode:BillingPolicyDecisionCode|null;};
export type BillingReconciliationFailureRecord={failureId:string;subjectKind:'user';subjectId:string;providerKind:BillingLifecycleProviderKind;reconciliationRunId:string|null;sourceEventId:string|null;failureKind:BillingReconciliationFailureKind;severity:BillingPolicySeverity;summary:string;retryCandidate:boolean;occurredAt:string;metadataJson:string;};
export type BillingRetryCandidate={candidateId:string;subjectKind:'user';subjectId:string;providerKind:BillingLifecycleProviderKind;reason:BillingRetryCandidateReason;latestReconciliationRunId:string|null;latestPolicyTransitionId:string|null;latestSubscriptionState:BillingLifecycleSubscriptionState|null;currentPlanKind:ElceoPlanKind;currentAccountState:ElceoAccountState;createdAt:string;};
export type BillingAdminSubjectSnapshot={generatedAt:string;subjectKind:'user';subjectId:string;lifecycleSnapshot:BillingLifecycleSnapshot;policySnapshot:BillingPolicySnapshot;latestReconciliationRun:BillingReconciliationRun|null;latestPolicyTransition:BillingPolicyTransition|null;operationalState:BillingOperationalSummaryLite|null;};
