import type { MarketReasoningModuleReadiness } from './market-reasoning-readiness';
import type { ReasoningEvidenceInputItem } from './reasoning-market-input';

export const MARKET_MACRO_INDICATOR_CATEGORIES = ['inflation','labor_market','growth_activity','consumption','business_activity','central_bank_policy','housing','trade_balance','confidence_sentiment','fiscal','commodity_inventory','unknown'] as const;
export type MarketMacroIndicatorCategory = typeof MARKET_MACRO_INDICATOR_CATEGORIES[number];
export const MARKET_MACRO_INDICATOR_KINDS = ['cpi_headline','cpi_core','pce_headline','pce_core','average_hourly_earnings','nonfarm_payrolls','unemployment_rate','jobless_claims','jolt_openings','gdp','retail_sales','pmi_manufacturing','pmi_services','ism_manufacturing','ism_services','consumer_confidence','policy_rate_decision','central_bank_statement_tone','oil_inventory','unknown'] as const;
export type MarketMacroIndicatorKind = typeof MARKET_MACRO_INDICATOR_KINDS[number];
export const MARKET_MACRO_REGIONS = ['US','eurozone','UK','Japan','Switzerland','Australia','New_Zealand','Canada','global','unknown'] as const;
export type MarketMacroRegion = typeof MARKET_MACRO_REGIONS[number];
export const MARKET_MACRO_CURRENCIES = ['USD','EUR','GBP','JPY','CHF','AUD','NZD','CAD','global','unknown'] as const;
export type MarketMacroCurrency = typeof MARKET_MACRO_CURRENCIES[number];
export const MARKET_MACRO_RELEASE_IMPORTANCES = ['low','medium','high','systemic','unknown'] as const;
export type MarketMacroReleaseImportance = typeof MARKET_MACRO_RELEASE_IMPORTANCES[number];
export const MARKET_MACRO_COMPARISON_BASES = ['actual_vs_forecast','actual_vs_previous_fallback','missing_actual','insufficient_data'] as const;
export type MarketMacroComparisonBasis = typeof MARKET_MACRO_COMPARISON_BASES[number];
export const MARKET_MACRO_SURPRISE_DIRECTIONS = ['upside_surprise','downside_surprise','inline','mixed','unknown'] as const;
export type MarketMacroSurpriseDirection = typeof MARKET_MACRO_SURPRISE_DIRECTIONS[number];
export const MARKET_MACRO_ECONOMIC_MEANINGS = ['hotter_inflation','cooler_inflation','stronger_growth','weaker_growth','tighter_labor','weaker_labor','hawkish_policy_surprise','dovish_policy_surprise','risk_supportive','risk_negative','mixed','unknown'] as const;
export type MarketMacroEconomicMeaning = typeof MARKET_MACRO_ECONOMIC_MEANINGS[number];
export const MARKET_MACRO_POLICY_PRESSURES = ['hawkish','dovish','neutral','mixed','unknown'] as const;
export type MarketMacroPolicyPressure = typeof MARKET_MACRO_POLICY_PRESSURES[number];
export const MARKET_MACRO_RISK_PRESSURES = ['risk_supportive','risk_negative','neutral','mixed','unknown'] as const;
export type MarketMacroRiskPressure = typeof MARKET_MACRO_RISK_PRESSURES[number];
export const MARKET_MACRO_GROWTH_PRESSURES = ['stronger','weaker','neutral','mixed','unknown'] as const;
export type MarketMacroGrowthPressure = typeof MARKET_MACRO_GROWTH_PRESSURES[number];
export const MARKET_MACRO_INFLATION_PRESSURES = ['hotter','cooler','neutral','mixed','unknown'] as const;
export type MarketMacroInflationPressure = typeof MARKET_MACRO_INFLATION_PRESSURES[number];
export const MARKET_MACRO_SURPRISE_SEVERITIES = ['inline','mild','moderate','large','extreme','unknown'] as const;
export type MarketMacroSurpriseSeverity = typeof MARKET_MACRO_SURPRISE_SEVERITIES[number];
export const MARKET_MACRO_SURPRISE_CONFIDENCE_TIERS = ['low','medium','high'] as const;
export type MarketMacroSurpriseConfidenceTier = typeof MARKET_MACRO_SURPRISE_CONFIDENCE_TIERS[number];
export const MARKET_MACRO_SURPRISE_WARNINGS = ['missing_actual','missing_forecast','missing_previous','previous_used_without_forecast','revision_present','revision_missing','consensus_dispersion_missing','historical_distribution_missing','unit_ambiguous','indicator_direction_ambiguous','low_magnitude_surprise','outlier_surprise','pending_asset_direction_resolution','pending_fx_relative_strength','requires_price_confirmation','provider_activation_gap'] as const;
export type MarketMacroSurpriseWarning = typeof MARKET_MACRO_SURPRISE_WARNINGS[number];
export const MARKET_MACRO_SURPRISE_REASON_CODES = ['actual_vs_forecast','actual_vs_previous_fallback','revision_adjusted','indicator_direction_inverted','inflation_policy_pressure','labor_policy_pressure','growth_policy_pressure','central_bank_policy_surprise','magnitude_bucket_applied','normalized_surprise_score','forecast_missing_penalty','consensus_dispersion_missing_penalty','historical_distribution_missing_penalty','asset_direction_pending','fx_relative_strength_pending'] as const;
export type MarketMacroSurpriseReasonCode = typeof MARKET_MACRO_SURPRISE_REASON_CODES[number];

export type MarketMacroReleaseInput = {
  releaseId: string;
  indicatorKind?: MarketMacroIndicatorKind | string;
  indicatorName?: string;
  category?: MarketMacroIndicatorCategory | string;
  region?: MarketMacroRegion | string;
  currency?: MarketMacroCurrency | string;
  importance?: MarketMacroReleaseImportance;
  actual?: number | null;
  forecast?: number | null;
  previous?: number | null;
  revisedPrevious?: number | null;
  unit?: string | null;
  observedAt?: string | null;
  historicalStandardDeviation?: number | null;
  consensusDispersion?: number | null;
  providerQualityScore?: number | null;
  metadata?: Record<string, unknown>;
};
export type MarketMacroSurpriseNormalizationResult = {
  releaseId: string;
  indicatorKind: MarketMacroIndicatorKind;
  category: MarketMacroIndicatorCategory;
  region: MarketMacroRegion;
  currency: MarketMacroCurrency;
  actual: number | null;
  forecast: number | null;
  previous: number | null;
  revisedPrevious: number | null;
  rawDelta: number | null;
  percentDelta: number | null;
  normalizedSurpriseScore: number;
  surpriseDirection: MarketMacroSurpriseDirection;
  severity: MarketMacroSurpriseSeverity;
  economicMeaning: MarketMacroEconomicMeaning;
  policyPressure: MarketMacroPolicyPressure;
  growthPressure: MarketMacroGrowthPressure;
  inflationPressure: MarketMacroInflationPressure;
  riskPressure: MarketMacroRiskPressure;
  confidence: number;
  confidenceTier: MarketMacroSurpriseConfidenceTier;
  comparisonBasis: MarketMacroComparisonBasis;
  reasonCodes: MarketMacroSurpriseReasonCode[];
  warnings: MarketMacroSurpriseWarning[];
  requiresAssetDirectionResolution: boolean;
  requiresFxRelativeStrength: boolean;
  requiresPriceConfirmation: boolean;
  rationale: string;
};
export type MarketMacroSurpriseRule = { ruleId: string; indicatorKinds: MarketMacroIndicatorKind[]; category: MarketMacroIndicatorCategory; inverted: boolean; economicMeanings: MarketMacroEconomicMeaning[]; reasonCodes: MarketMacroSurpriseReasonCode[]; warnings: MarketMacroSurpriseWarning[]; rationale: string };
export type MarketMacroSurpriseRuleSetSnapshot = { generatedAt: string; rules: MarketMacroSurpriseRule[]; coverageReport: MarketMacroSurpriseCoverageReport };
export type MarketMacroSurpriseCoverageReport = { generatedAt: string; representedIndicatorKinds: MarketMacroIndicatorKind[]; representedCategories: MarketMacroIndicatorCategory[]; readiness: MarketReasoningModuleReadiness; warnings: MarketMacroSurpriseWarning[]; notes: string[] };
export type MarketMacroSurpriseEvidenceItem = ReasoningEvidenceInputItem;
