import type { MarketAssetCausalityAsset } from './market-asset-causality';
import type { EvidenceWeightHorizon, WeightedEvidenceSnapshot } from './market-evidence-weighting';
import type { ReasoningEvidenceInputItem } from './reasoning-market-input';

export type MarketPriceReactionAsset = MarketAssetCausalityAsset;
export type MarketPriceReactionHorizon = EvidenceWeightHorizon;
export const MARKET_PRICE_REACTION_EVENT_KINDS = ['macro_release','policy_decision','central_bank_speech','geopolitical_headline','risk_event','earnings_event','crypto_event','commodity_inventory','generic_news','unknown'] as const;
export type MarketPriceReactionEventKind = typeof MARKET_PRICE_REACTION_EVENT_KINDS[number];
export const MARKET_PRICE_REACTION_DIRECTIONS = ['bullish','bearish','neutral','mixed','unknown'] as const;
export type MarketPriceReactionExpectedDirection = typeof MARKET_PRICE_REACTION_DIRECTIONS[number];
export type MarketPriceReactionObservedDirection = typeof MARKET_PRICE_REACTION_DIRECTIONS[number];
export const MARKET_PRICE_REACTION_STATUSES = ['confirmed','rejected','absorbed','reversed','delayed','insufficient_data','ambiguous','unknown'] as const;
export type MarketPriceReactionStatus = typeof MARKET_PRICE_REACTION_STATUSES[number];
export const MARKET_PRICE_REACTION_IMPULSE_CLASSES = ['none','weak','moderate','strong','extreme','outlier'] as const;
export type MarketPriceReactionImpulseClass = typeof MARKET_PRICE_REACTION_IMPULSE_CLASSES[number];
export const MARKET_PRICE_REACTION_WINDOW_KINDS = ['pre_event','immediate','confirmation','follow_through','post_event'] as const;
export type MarketPriceReactionWindowKind = typeof MARKET_PRICE_REACTION_WINDOW_KINDS[number];
export const MARKET_PRICE_REACTION_VOLATILITY_BASES = ['supplied','pre_event_average_range','fallback_range'] as const;
export type MarketPriceReactionVolatilityBasis = typeof MARKET_PRICE_REACTION_VOLATILITY_BASES[number];
export const MARKET_PRICE_REACTION_WARNINGS = ['missing_event_time','missing_expected_direction','missing_price_window','insufficient_candles','missing_pre_event_context','missing_post_event_context','volatility_basis_missing','low_liquidity_window','spread_risk_unavailable','event_window_too_short','event_window_too_long','wick_rejection_detected','absorption_detected','reversal_detected','delayed_follow_through','outlier_move','provider_activation_gap','pending_provider_reliability','pending_golden_scenario_expansion'] as const;
export type MarketPriceReactionWarning = typeof MARKET_PRICE_REACTION_WARNINGS[number];
export const MARKET_PRICE_REACTION_REASON_CODES = ['expected_direction_from_resolver','event_window_return','volatility_adjusted_move','impulse_bucket_applied','wick_rejection_rule','absorption_rule','reversal_rule','follow_through_rule','confirmation_rule','insufficient_data_penalty','price_reaction_confirmed','price_reaction_rejected','price_reaction_absorbed','price_reaction_ambiguous','deterministic_foundation_only'] as const;
export type MarketPriceReactionReasonCode = typeof MARKET_PRICE_REACTION_REASON_CODES[number];

export type MarketPriceCandle = { timestamp: string; open: number; high: number; low: number; close: number; volume?: number | null };
export type MarketPriceReactionInput = {
  reactionId?: string;
  asset: MarketPriceReactionAsset;
  horizon: MarketPriceReactionHorizon;
  eventKind: MarketPriceReactionEventKind;
  eventTime?: string | null;
  expectedDirection?: MarketPriceReactionExpectedDirection | null;
  candles: MarketPriceCandle[];
  volatilityBasisPct?: number | null;
  volatilityBasis?: MarketPriceReactionVolatilityBasis | null;
  metadata?: Record<string, string | number | boolean | null>;
};
export type MarketPriceReactionWindow = { kind: MarketPriceReactionWindowKind; startTime: string | null; endTime: string | null; candleCount: number; open: number | null; high: number | null; low: number | null; close: number | null; movePct: number | null; rangePct: number | null };
export type MarketPriceReactionResult = {
  reactionId: string;
  asset: MarketPriceReactionAsset;
  horizon: MarketPriceReactionHorizon;
  eventKind: MarketPriceReactionEventKind;
  eventTime: string | null;
  expectedDirection: MarketPriceReactionExpectedDirection;
  observedDirection: MarketPriceReactionObservedDirection;
  status: MarketPriceReactionStatus;
  impulseClass: MarketPriceReactionImpulseClass;
  confidence: number;
  immediateMovePct: number;
  followThroughMovePct: number;
  volatilityAdjustedMove: number;
  wickRejectionScore: number;
  absorptionScore: number;
  reversalScore: number;
  windows: MarketPriceReactionWindow[];
  warnings: MarketPriceReactionWarning[];
  reasonCodes: MarketPriceReactionReasonCode[];
  rationale: string;
  complete: false;
  pending: { providerReliabilityExpansion: true; goldenScenarioExpansion: true; empiricalBacktesting: true };
};
export type MarketPriceReactionRule = { ruleId: string; asset?: MarketPriceReactionAsset; status?: MarketPriceReactionStatus; warning?: MarketPriceReactionWarning; reasonCodes: MarketPriceReactionReasonCode[]; rationale: string };
export type MarketPriceReactionRuleSetSnapshot = { generatedAt: string; rules: MarketPriceReactionRule[]; warnings: MarketPriceReactionWarning[]; complete: false; pending: MarketPriceReactionResult['pending'] };
export type MarketPriceReactionCoverageReport = { generatedAt: string; assetCount: number; statusCoverage: MarketPriceReactionStatus[]; windowKinds: MarketPriceReactionWindowKind[]; warnings: MarketPriceReactionWarning[]; notes: string[]; complete: false; pending: MarketPriceReactionResult['pending'] };
export type MarketPriceReactionEvidenceItem = ReasoningEvidenceInputItem;
export type MarketPriceReactionWeightedSnapshot = WeightedEvidenceSnapshot;
