import { createHash,randomUUID } from 'node:crypto';
import { createClient,type RedisClientType } from 'redis';
export type InboundReadPolicy={policyId:string;policyVersion:string;canonicalPolicyHash:string;status:'approved'|'test_only'|'disabled';provenance:string;effectiveFrom:string;effectiveTo:string|null;routeFamily:string;windowMs:number;requestAllowance:number;concurrentAllowance:number;leaseMs:number;stateTtlMs:number};
export type InboundLease={subjectDigest:string;ownerToken:string;policy:InboundReadPolicy;expiresAt:number};
export type InboundAdmission={admitted:true;lease:InboundLease}|{admitted:false;status:429|503;reason:'inbound_rate_limited'|'inbound_concurrency_limited'|'inbound_control_unavailable'|'inbound_policy_unavailable'};
const canonical=(v:unknown):unknown=>Array.isArray(v)?v.map(canonical):v&&typeof v==='object'?Object.fromEntries(Object.entries(v).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>[k,canonical(x)])):v;
export const inboundPolicyHash=(p:Omit<InboundReadPolicy,'canonicalPolicyHash'>)=>`sha256:${createHash('sha256').update(JSON.stringify(canonical(p))).digest('hex')}`;
export const subjectDigest=(subject:string)=>createHash('sha256').update(`elceo-inbound-subject-v1\0${subject}`).digest('hex').slice(0,32);
export function validateInboundReadPolicy(p:InboundReadPolicy,environment=process.env.NODE_ENV,now=Date.now()){const{canonicalPolicyHash,...body}=p;if(canonicalPolicyHash!==inboundPolicyHash(body)||!p.policyId||!p.policyVersion||!p.provenance||!p.routeFamily)return false;if(!Number.isInteger(p.windowMs)||p.windowMs<1||!Number.isInteger(p.requestAllowance)||p.requestAllowance<1||!Number.isInteger(p.concurrentAllowance)||p.concurrentAllowance<1||!Number.isInteger(p.leaseMs)||p.leaseMs<1||!Number.isInteger(p.stateTtlMs)||p.stateTtlMs<p.windowMs)return false;if(Date.parse(p.effectiveFrom)>now||(p.effectiveTo!==null&&Date.parse(p.effectiveTo)<=now))return false;return p.status==='approved'||(p.status==='test_only'&&environment==='test')||p.status==='disabled'}
const ADMIT=`local t=redis.call('TIME');local now=tonumber(t[1])*1000+math.floor(tonumber(t[2])/1000);local window=math.floor(now/tonumber(ARGV[2]));local rate=KEYS[1]..':'..window;local count=tonumber(redis.call('GET',rate) or 0);if count>=tonumber(ARGV[3]) then return cjson.encode({ok=false,reason='rate'}) end;redis.call('ZREMRANGEBYSCORE',KEYS[2],'-inf',now);if redis.call('ZCARD',KEYS[2])>=tonumber(ARGV[4]) then return cjson.encode({ok=false,reason='concurrency'}) end;redis.call('INCR',rate);redis.call('PEXPIRE',rate,tonumber(ARGV[5]));local exp=now+tonumber(ARGV[6]);redis.call('ZADD',KEYS[2],exp,ARGV[1]);redis.call('PEXPIRE',KEYS[2],tonumber(ARGV[5]));return cjson.encode({ok=true,expiresAt=exp})`;
const RELEASE=`return redis.call('ZREM',KEYS[1],ARGV[1])`;
const RENEW=`local t=redis.call('TIME');local now=tonumber(t[1])*1000+math.floor(tonumber(t[2])/1000);local score=tonumber(redis.call('ZSCORE',KEYS[1],ARGV[1]) or 0);if score<=now then redis.call('ZREM',KEYS[1],ARGV[1]);return 0 end;local exp=now+tonumber(ARGV[2]);redis.call('ZADD',KEYS[1],exp,ARGV[1]);return exp`;
export class RedisInboundReadAdmission {private connecting:Promise<unknown>|null=null;constructor(private readonly client:RedisClientType,private readonly policy:InboundReadPolicy,private readonly namespace='elceo:inbound:v1',private readonly timeoutMs=3000){}private async bounded<T>(p:Promise<T>){let timer:NodeJS.Timeout;try{return await Promise.race([p,new Promise<T>((_,reject)=>{timer=setTimeout(()=>reject(new Error('unavailable')),this.timeoutMs)})])}finally{clearTimeout(timer!)}}private async ensure(){if(this.connecting)await this.connecting;if(!this.client.isOpen){this.connecting=this.bounded(this.client.connect()).finally(()=>this.connecting=null);await this.connecting}if(!this.client.isReady)throw new Error('unavailable')}private key(d:string){const tag=`{${d}}`;return{rate:`${this.namespace}:${tag}:rate:${this.policy.policyId}:${this.policy.policyVersion}`,owners:`${this.namespace}:${tag}:owners:${this.policy.routeFamily}`}}
async admit(authenticatedSubject:string):Promise<InboundAdmission>{if(!validateInboundReadPolicy(this.policy))return{admitted:false,status:503,reason:'inbound_policy_unavailable'};if(this.policy.status==='disabled')return{admitted:true,lease:{subjectDigest:subjectDigest(authenticatedSubject),ownerToken:'disabled',policy:this.policy,expiresAt:0}};const digest=subjectDigest(authenticatedSubject),ownerToken=randomUUID(),k=this.key(digest);try{await this.ensure();const raw=JSON.parse(String(await this.bounded(this.client.eval(ADMIT,{keys:[k.rate,k.owners],arguments:[ownerToken,String(this.policy.windowMs),String(this.policy.requestAllowance),String(this.policy.concurrentAllowance),String(this.policy.stateTtlMs),String(this.policy.leaseMs)]}))));return raw.ok?{admitted:true,lease:{subjectDigest:digest,ownerToken,policy:this.policy,expiresAt:raw.expiresAt}}:{admitted:false,status:429,reason:raw.reason==='rate'?'inbound_rate_limited':'inbound_concurrency_limited'}}catch{return{admitted:false,status:503,reason:'inbound_control_unavailable'}}}
async renew(l:InboundLease){if(l.ownerToken==='disabled')return l;try{await this.ensure();const exp=Number(await this.bounded(this.client.eval(RENEW,{keys:[this.key(l.subjectDigest).owners],arguments:[l.ownerToken,String(l.policy.leaseMs)]})));return exp?{...l,expiresAt:exp}:null}catch{return null}}
async release(l:InboundLease){if(l.ownerToken==='disabled')return true;try{await this.ensure();return Number(await this.bounded(this.client.eval(RELEASE,{keys:[this.key(l.subjectDigest).owners],arguments:[l.ownerToken]})))===1}catch{return false}}
}
export const createInboundRedisClient=(url=process.env.REDIS_URL)=>{if(!url)throw new Error('inbound_control_unavailable');const client=createClient({url,socket:{connectTimeout:3000,reconnectStrategy:r=>r<2?100:false}})as RedisClientType;client.on('error',()=>undefined);return client};
