import { createHash, randomUUID } from 'node:crypto';
import { createClient, type RedisClientType } from 'redis';

export const DASHBOARD_READ_ROUTE_FAMILY = 'dashboard-read' as const;
const MAX_DURATION_MS = 2_147_483_647;
export type InboundReadPolicy = { policyId:string;policyVersion:string;canonicalPolicyHash:string;status:'approved'|'test_only'|'disabled';provenance:string;effectiveFrom:string;effectiveTo:string|null;routeFamily:string;windowMs:number;requestAllowance:number;concurrentAllowance:number;leaseMs:number;stateTtlMs:number };
export type InboundLease = Readonly<{ subjectDigest:string;ownerToken:string;expiresAt:number }>;
export type InboundAdmission = {admitted:true;lease:InboundLease}|{admitted:false;status:429|503;reason:'inbound_rate_limited'|'inbound_concurrency_limited'|'inbound_control_unavailable'|'inbound_policy_unavailable'};
export type InboundReadMetrics={admitted:number;rejectedRate:number;rejectedConcurrency:number;unavailable:number};
export const createInboundReadMetrics=():InboundReadMetrics=>({admitted:0,rejectedRate:0,rejectedConcurrency:0,unavailable:0});
const canonical=(v:unknown):unknown=>Array.isArray(v)?v.map(canonical):v&&typeof v==='object'?Object.fromEntries(Object.entries(v).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>[k,canonical(x)])):v;
export const inboundPolicyHash=(p:Omit<InboundReadPolicy,'canonicalPolicyHash'>)=>`sha256:${createHash('sha256').update(JSON.stringify(canonical(p))).digest('hex')}`;
export const subjectDigest=(subject:string)=>createHash('sha256').update(`elceo-inbound-subject-v1\0${subject}`).digest('hex').slice(0,32);
const safePositive=(n:number)=>Number.isSafeInteger(n)&&n>0&&n<=MAX_DURATION_MS;
/** Shape/hash validation only. Effective authorization is performed atomically using Redis TIME. */
export function validateInboundReadPolicy(p:InboundReadPolicy,environment=process.env.NODE_ENV,requiredRouteFamily:string=DASHBOARD_READ_ROUTE_FAMILY){const{canonicalPolicyHash,...body}=p;const from=Date.parse(p.effectiveFrom),to=p.effectiveTo===null?null:Date.parse(p.effectiveTo);if(canonicalPolicyHash!==inboundPolicyHash(body)||!p.policyId||!p.policyVersion||!p.provenance||p.routeFamily!==requiredRouteFamily)return false;if(!Number.isFinite(from)||(to!==null&&(!Number.isFinite(to)||to<=from)))return false;if(!safePositive(p.windowMs)||!safePositive(p.requestAllowance)||!safePositive(p.concurrentAllowance)||!safePositive(p.leaseMs)||!safePositive(p.stateTtlMs)||p.stateTtlMs<p.windowMs||p.stateTtlMs<p.leaseMs)return false;return p.status==='approved'||(p.status==='test_only'&&environment==='test')}
const ADMIT=`local t=redis.call('TIME');local now=tonumber(t[1])*1000+math.floor(tonumber(t[2])/1000);local effectiveFrom=tonumber(ARGV[7]);local effectiveTo=tonumber(ARGV[8]);if now<effectiveFrom or (effectiveTo>0 and now>=effectiveTo) then return cjson.encode({ok=false,reason='policy'}) end;local window=math.floor(now/tonumber(ARGV[2]));local rate=KEYS[1]..':'..window;local count=tonumber(redis.call('GET',rate) or 0);if count>=tonumber(ARGV[3]) then return cjson.encode({ok=false,reason='rate'}) end;redis.call('ZREMRANGEBYSCORE',KEYS[2],'-inf',now);if redis.call('ZCARD',KEYS[2])>=tonumber(ARGV[4]) then return cjson.encode({ok=false,reason='concurrency'}) end;redis.call('INCR',rate);redis.call('PEXPIRE',rate,tonumber(ARGV[5]));local exp=now+tonumber(ARGV[6]);redis.call('ZADD',KEYS[2],exp,ARGV[1]);redis.call('PEXPIRE',KEYS[2],tonumber(ARGV[5]));return cjson.encode({ok=true,expiresAt=exp})`;
const RELEASE=`return redis.call('ZREM',KEYS[1],ARGV[1])`;
const RENEW=`local t=redis.call('TIME');local now=tonumber(t[1])*1000+math.floor(tonumber(t[2])/1000);local score=tonumber(redis.call('ZSCORE',KEYS[1],ARGV[1]) or 0);if score<=now then redis.call('ZREM',KEYS[1],ARGV[1]);return 0 end;local exp=now+tonumber(ARGV[2]);redis.call('ZADD',KEYS[1],exp,ARGV[1]);redis.call('PEXPIRE',KEYS[1],tonumber(ARGV[3]));return exp`;
const CONFIRM=`local t=redis.call('TIME');local now=tonumber(t[1])*1000+math.floor(tonumber(t[2])/1000);return tonumber(redis.call('ZSCORE',KEYS[1],ARGV[1]) or 0)>now and 1 or 0`;
export class RedisInboundReadAdmission {
 private connecting:Promise<unknown>|null=null;
 constructor(private readonly client:RedisClientType,private readonly policy:InboundReadPolicy,private readonly namespace='elceo:inbound:v1',private readonly timeoutMs=3000,readonly metrics:InboundReadMetrics=createInboundReadMetrics(),private readonly environment=process.env.NODE_ENV){}
 private async bounded<T>(p:Promise<T>){let timer:NodeJS.Timeout;try{return await Promise.race([p,new Promise<T>((_,reject)=>{timer=setTimeout(()=>reject(new Error('unavailable')),this.timeoutMs)})])}finally{clearTimeout(timer!)}}
 private async ensure(){if(this.connecting)await this.connecting;if(!this.client.isOpen){this.connecting=this.bounded(this.client.connect()).finally(()=>this.connecting=null);await this.connecting}if(!this.client.isReady)throw new Error('unavailable')}
 heartbeatIntervalMs(){return Math.max(10,Math.floor(this.policy.leaseMs/3))}
  private owners(d:string){return`${this.namespace}:{${d}}:owners:${this.policy.routeFamily}`}
 private rate(d:string){return`${this.namespace}:{${d}}:rate:${this.policy.policyId}:${this.policy.policyVersion}`}
 async admit(authenticatedSubject:string):Promise<InboundAdmission>{if(!validateInboundReadPolicy(this.policy,this.environment)){this.metrics.unavailable++;return{admitted:false,status:503,reason:'inbound_policy_unavailable'}}const digest=subjectDigest(authenticatedSubject),ownerToken=randomUUID();try{await this.ensure();const raw=JSON.parse(String(await this.bounded(this.client.eval(ADMIT,{keys:[this.rate(digest),this.owners(digest)],arguments:[ownerToken,String(this.policy.windowMs),String(this.policy.requestAllowance),String(this.policy.concurrentAllowance),String(this.policy.stateTtlMs),String(this.policy.leaseMs),String(Date.parse(this.policy.effectiveFrom)),String(this.policy.effectiveTo===null?0:Date.parse(this.policy.effectiveTo))]})))) as {ok:boolean;reason?:string;expiresAt?:number};if(raw.ok){this.metrics.admitted++;return{admitted:true,lease:{subjectDigest:digest,ownerToken,expiresAt:raw.expiresAt!}}}if(raw.reason==='rate'){this.metrics.rejectedRate++;return{admitted:false,status:429,reason:'inbound_rate_limited'}}if(raw.reason==='concurrency'){this.metrics.rejectedConcurrency++;return{admitted:false,status:429,reason:'inbound_concurrency_limited'}}this.metrics.unavailable++;return{admitted:false,status:503,reason:'inbound_policy_unavailable'}}catch{this.metrics.unavailable++;return{admitted:false,status:503,reason:'inbound_control_unavailable'}}}
 async renew(l:InboundLease){try{await this.ensure();const exp=Number(await this.bounded(this.client.eval(RENEW,{keys:[this.owners(l.subjectDigest)],arguments:[l.ownerToken,String(this.policy.leaseMs),String(this.policy.stateTtlMs)]})));return exp?{...l,expiresAt:exp}:null}catch{return null}}
 async confirm(l:InboundLease){try{await this.ensure();return Number(await this.bounded(this.client.eval(CONFIRM,{keys:[this.owners(l.subjectDigest)],arguments:[l.ownerToken]})))===1}catch{return false}}
 async release(l:InboundLease){try{await this.ensure();return Number(await this.bounded(this.client.eval(RELEASE,{keys:[this.owners(l.subjectDigest)],arguments:[l.ownerToken]})))===1}catch{return false}}
}
export const createInboundRedisClient=(url=process.env.REDIS_URL)=>{if(!url)throw new Error('inbound_control_unavailable');const client=createClient({url,socket:{connectTimeout:3000,reconnectStrategy:r=>r<2?100:false}})as RedisClientType;client.on('error',()=>undefined);return client};
