import type { SuperAdminCommercialConversionMetrics, SuperAdminGiftMetrics, SuperAdminMetricsCoverageReport, SuperAdminMetricsQuery, SuperAdminMetricsSnapshot, SuperAdminPaymentReadinessMetrics, SuperAdminPlanIntervalSplit, SuperAdminRestrictionMetrics, SuperAdminRevenueMetrics, SuperAdminSubscriptionMetrics, SuperAdminTrialMetrics, SuperAdminUserMetrics } from '@elceo/types';

const fixture={totalUsers:120,activeUsers:107,suspendedUsers:8,bannedUsers:5,subscribedUsers:52,activePaidUsers:45,expiredPaidUsers:7,resubscribedUsers:9,subscriptionRequiredUsers:68,kickOffTrialUsers:33,activeKickOffTrialUsers:18,expiredKickOffTrialUsers:15,giftedFocusPlanUsers:12,activeGifts:7,expiredGifts:3,retractedGifts:2,socialIdentifierCompleteUsers:95,missingSocialIdentifierUsers:25,paymentReadyUsers:90,paymentBlockedUsers:30,monthlyCount:29,quarterlyCount:14,yearlyCount:9,totalRevenue:3150,mrr:3150};
const q=(input?:Partial<SuperAdminMetricsQuery>):SuperAdminMetricsQuery=>({period:input?.period??'all_time',asOf:input?.asOf??new Date().toISOString()});
export const getSuperAdminUserMetrics=():SuperAdminUserMetrics=>({totalUsers:fixture.totalUsers,activeUsers:fixture.activeUsers,suspendedUsers:fixture.suspendedUsers,bannedUsers:fixture.bannedUsers});
export const getSuperAdminSubscriptionMetrics=():SuperAdminSubscriptionMetrics=>({subscribedUsers:fixture.subscribedUsers,activePaidUsers:fixture.activePaidUsers,expiredPaidUsers:fixture.expiredPaidUsers,resubscribedUsers:fixture.resubscribedUsers,subscriptionRequiredUsers:fixture.subscriptionRequiredUsers});
export const getSuperAdminTrialMetrics=():SuperAdminTrialMetrics=>({kickOffTrialUsers:fixture.kickOffTrialUsers,activeKickOffTrialUsers:fixture.activeKickOffTrialUsers,expiredKickOffTrialUsers:fixture.expiredKickOffTrialUsers});
export const getSuperAdminGiftMetrics=():SuperAdminGiftMetrics=>({giftedFocusPlanUsers:fixture.giftedFocusPlanUsers,activeGifts:fixture.activeGifts,expiredGifts:fixture.expiredGifts,retractedGifts:fixture.retractedGifts});
export const getSuperAdminRestrictionMetrics=():SuperAdminRestrictionMetrics=>({suspendedUsers:fixture.suspendedUsers,bannedUsers:fixture.bannedUsers});
export const getSuperAdminPaymentReadinessMetrics=():SuperAdminPaymentReadinessMetrics=>({socialIdentifierCompleteUsers:fixture.socialIdentifierCompleteUsers,missingSocialIdentifierUsers:fixture.missingSocialIdentifierUsers,paymentReadyUsers:fixture.paymentReadyUsers,paymentBlockedUsers:fixture.paymentBlockedUsers});
export const getSuperAdminPlanIntervalSplit=():SuperAdminPlanIntervalSplit=>({monthlyCount:fixture.monthlyCount,quarterlyCount:fixture.quarterlyCount,yearlyCount:fixture.yearlyCount});
export const getSuperAdminRevenueMetrics=():SuperAdminRevenueMetrics=>({currency:'USD',dataStatus:'fixture_only',totalRevenue:fixture.totalRevenue,monthlyRecurringRevenue:fixture.mrr,revenueByInterval:{monthly:2030,quarterly:700,yearly:420},revenueByPlan:{kick_off:0,focus_plan:fixture.totalRevenue}});
export const getSuperAdminCommercialConversionMetrics=():SuperAdminCommercialConversionMetrics=>({totalUsers:fixture.totalUsers,subscribedUsers:fixture.subscribedUsers,activePaidUsers:fixture.activePaidUsers,kickOffTrialUsers:fixture.kickOffTrialUsers,conversionRate:Number((fixture.subscribedUsers/fixture.totalUsers).toFixed(4))});
export const getSuperAdminMetricsSnapshot=(input?:Partial<SuperAdminMetricsQuery>):SuperAdminMetricsSnapshot=>({generatedAt:q(input).asOf,period:q(input).period,dataStatus:'fixture_only',users:getSuperAdminUserMetrics(),subscriptions:getSuperAdminSubscriptionMetrics(),trials:getSuperAdminTrialMetrics(),revenue:getSuperAdminRevenueMetrics(),gifts:getSuperAdminGiftMetrics(),restrictions:getSuperAdminRestrictionMetrics(),paymentReadiness:getSuperAdminPaymentReadinessMetrics(),planIntervalSplit:getSuperAdminPlanIntervalSplit(),conversion:getSuperAdminCommercialConversionMetrics()});
export const getSuperAdminMetricsCoverageReport=():SuperAdminMetricsCoverageReport=>({generatedAt:new Date().toISOString(),deterministicOrdering:true,providerCallsPerformed:false,includesIpBanMetrics:false,liveRevenueBacked:false});
