import { validateMarketContradictionCoverageReport, validateMarketContradictionInput, validateMarketContradictionMatrixResult, validateMarketContradictionRuleSetSnapshot } from '@elceo/schemas';
import type { EvidenceWeightHorizon, MarketPriceReactionResult, MarketContradictionAsset, MarketContradictionCoverageReport, MarketContradictionEvidenceItemsOptions, MarketContradictionEvidencePoint, MarketContradictionFamily, MarketContradictionInput, MarketContradictionMatrixResult, MarketContradictionReasonCode, MarketContradictionReasoningEvidenceItem, MarketContradictionRule, MarketContradictionRuleSetSnapshot, MarketContradictionSeverity, MarketContradictionSignal, MarketContradictionStatus, MarketContradictionWarning, MarketContradictionWeightedSnapshotOptions, MarketEvidenceClass, WeightedEvidenceDirection, WeightedEvidenceItem, WeightedEvidenceSnapshot } from '@elceo/types';
import { MARKET_ASSET_CAUSALITY_ASSETS, MARKET_CONTRADICTION_FAMILIES } from '@elceo/types';
import { resolveAssetContextualDirectionForEvidenceItem } from '../asset-direction-resolution/index';
import { resolveFxRelativeStrengthFromEvidenceItems, resolveFxRelativeStrengthFromWeightedSnapshot } from '../fx-relative-strength/index';
import { normalizeMacroSurpriseFromEvidenceItem } from '../macro-surprise-normalization/index';

type Direction = 'bullish' | 'bearish' | 'neutral' | 'mixed' | 'unknown';
type Driver = MarketContradictionEvidencePoint['driverKind'];
type RuleBuilder = (input: MarketContradictionInput) => MarketContradictionSignal[];
type BuiltRule = MarketContradictionRule & { build: RuleBuilder };
type MetadataRecord = Record<string, string | number | boolean | null>;
const pending = { confidenceCalibrationR6: true, priceReactionR7: true, providerReliabilityExpansion: true } as const;
const fxAssets = new Set<MarketContradictionAsset>(['eur_usd','gbp_usd','usd_jpy','aud_usd','usd_chf','nzd_usd','usd_cad']);
const riskAssets = new Set<MarketContradictionAsset>(['nasdaq_100','sp500','btc_usd']);
const equityAssets = new Set<MarketContradictionAsset>(['nasdaq_100','sp500']);
const severityRank: Record<MarketContradictionSeverity, number> = { none: 0, low: 1, moderate: 2, high: 3, critical: 4 };


function priceReactionWarnings(reaction: MarketPriceReactionResult | undefined): MarketContradictionWarning[] {
  if (!reaction) return ['pending_price_confirmation'];
  if (reaction.status === 'confirmed') return ['price_reaction_confirmed'];
  if (reaction.status === 'rejected') return ['price_reaction_rejected'];
  if (reaction.status === 'reversed') return ['price_reaction_reversed'];
  if (reaction.status === 'absorbed') return ['price_reaction_absorbed','pending_price_confirmation'];
  if (reaction.status === 'delayed') return ['price_reaction_delayed','pending_price_confirmation'];
  if (reaction.status === 'ambiguous') return ['price_reaction_ambiguous','pending_price_confirmation'];
  return ['missing_price_reaction','pending_price_confirmation'];
}
function priceReactionReasons(reaction: MarketPriceReactionResult | undefined): MarketContradictionReasonCode[] {
  if (!reaction) return ['price_confirmation_pending'];
  if (reaction.status === 'confirmed') return ['price_reaction_confirmed'];
  if (reaction.status === 'rejected') return ['price_reaction_rejected'];
  if (reaction.status === 'reversed') return ['price_reaction_reversed'];
  if (reaction.status === 'absorbed') return ['price_reaction_absorbed'];
  if (reaction.status === 'delayed') return ['price_reaction_delayed'];
  return ['price_reaction_ambiguous'];
}
function hasUsablePriceReaction(input: MarketContradictionInput): boolean { return input.priceReactionAvailable || input.priceReaction !== undefined; }

function parseMetadata(json: string): MetadataRecord {
  try {
    const value: unknown = JSON.parse(json || '{}');
    if (typeof value !== 'object' || value === null || Array.isArray(value)) return {};
    const out: MetadataRecord = {};
    for (const [key, raw] of Object.entries(value)) if (typeof raw === 'string' || typeof raw === 'number' || typeof raw === 'boolean' || raw === null) out[key] = raw;
    return out;
  } catch { return {}; }
}
function text(item: Pick<WeightedEvidenceItem, 'evidenceClass' | 'reasons' | 'providerId' | 'payloadId'>): string { return `${item.evidenceClass}|${item.providerId}|${item.payloadId}|${item.reasons.join('|')}`.toLowerCase(); }
function metaText(metadata: MetadataRecord): string { return Object.entries(metadata).map(([k, v]) => `${k}:${String(v)}`).join('|').toLowerCase(); }
function includesAny(haystack: string, needles: readonly string[]): boolean { return needles.some((needle) => haystack.includes(needle)); }
function asAsset(asset: string): MarketContradictionAsset { if ((MARKET_ASSET_CAUSALITY_ASSETS as readonly string[]).includes(asset)) return asset as MarketContradictionAsset; throw new Error(`market_contradiction_unsupported_asset:${asset}`); }
function driverFromEvidence(evidenceClass: MarketEvidenceClass, narrative: string): Driver {
  if (evidenceClass === 'central_bank_policy') return 'central_bank_policy';
  if (evidenceClass === 'inflation') return 'inflation_surprise';
  if (evidenceClass === 'real_yields') return 'real_yields';
  if (evidenceClass === 'dollar_liquidity') return 'dollar_liquidity';
  if (evidenceClass === 'volatility_surface') return 'volatility_surface';
  if (evidenceClass === 'credit_stress') return 'credit_stress';
  if (evidenceClass === 'equity_index_breadth') return 'equity_breadth';
  if (evidenceClass === 'crypto_market_structure') return includesAny(narrative, ['funding','leverage','derivative']) ? 'crypto_derivatives' : 'crypto_onchain';
  if (evidenceClass === 'liquidity_conditions' || evidenceClass === 'financial_conditions') return 'liquidity_conditions';
  if (evidenceClass === 'energy_commodities') return 'oil_energy';
  if (evidenceClass === 'geopolitical_risk') return 'geopolitical_risk';
  if (evidenceClass === 'macro_calendar' || evidenceClass === 'economic_indicator' || evidenceClass === 'macro_surprise_history') return 'macro_surprise';
  if (evidenceClass === 'risk_sentiment') return 'risk_sentiment';
  if (evidenceClass === 'market_news') return includesAny(narrative, ['duplicate','scraped','same headline']) ? 'source_independence' : 'unknown';
  return 'unknown';
}
function directionForDriver(item: WeightedEvidenceItem, driver: Driver): Direction {
  const narrative = text(item);
  if (driver === 'volatility_surface') return includesAny(narrative, ['falling','benign','cooling','declining']) || item.direction === 'bearish' ? 'bearish' : 'bullish';
  if (driver === 'credit_stress') return includesAny(narrative, ['falling','improving','narrowing']) || item.direction === 'bearish' ? 'bearish' : 'bullish';
  if (driver === 'equity_breadth') return includesAny(narrative, ['deteriorat','weak','negative','narrow']) || item.direction === 'bearish' ? 'bearish' : 'bullish';
  if (driver === 'central_bank_policy') return includesAny(narrative, ['dovish','easing']) ? 'bearish' : includesAny(narrative, ['hawkish','tightening']) ? 'bullish' : item.direction;
  if (driver === 'real_yields' || driver === 'dollar_liquidity') return item.direction === 'bearish' ? 'bearish' : 'bullish';
  if (driver === 'crypto_derivatives') return includesAny(narrative, ['overheated','high funding','leverage','stress']) ? 'bearish' : item.direction;
  return item.direction;
}
function evidencePointFromWeighted(item: WeightedEvidenceItem, asset: MarketContradictionAsset, generatedAt: string): MarketContradictionEvidencePoint {
  const narrative = text(item);
  const driver = driverFromEvidence(item.evidenceClass, narrative);
  const warnings: MarketContradictionWarning[] = [];
  const reasonCodes: MarketContradictionReasonCode[] = ['contradiction_matrix_rule_applied'];
  if (includesAny(narrative, ['stale','expired'])) warnings.push('stale_evidence_conflict');
  if (includesAny(narrative, ['duplicate','scraped','same headline'])) warnings.push('duplicate_source_risk','source_independence_unverified');
  if (includesAny(narrative, ['price_confirmation','price reaction missing','missing_price_reaction'])) warnings.push('missing_price_reaction','pending_price_confirmation');
  return { evidencePointId: `cmp|${asset}|${item.payloadId}`, asset, horizon: item.horizon, observedAt: item.observedAt || generatedAt, evidenceClass: item.evidenceClass, driverKind: driver, side: item.direction === 'unknown' ? 'context' : 'supporting', direction: directionForDriver(item, driver), strength: Math.min(100, Math.abs(item.contributionScore) + item.qualityAdjustedWeight), quality: item.finalQualityScore, providerId: item.providerId || null, sourceId: item.providerId || null, rationale: `Weighted ${item.evidenceClass} evidence mapped into expanded contradiction context.`, reasonCodes, warnings };
}
function evidencePointFromInputItem(asset: MarketContradictionAsset, item: MarketContradictionReasoningEvidenceItem, horizon: EvidenceWeightHorizon): MarketContradictionEvidencePoint {
  const metadata = parseMetadata(item.metadataJson);
  const narrative = `${item.evidenceClass}|${item.providerId}|${item.payloadId}|${item.reasons.join('|')}|${metaText(metadata)}`.toLowerCase();
  const driver = driverFromEvidence(item.evidenceClass, narrative);
  const supportedTradingAsset = ['xau_usd','eur_usd','gbp_usd','usd_jpy','aud_usd','usd_chf','nzd_usd','usd_cad','btc_usd','nasdaq_100','sp500','de30'].includes(asset);
  const resolved = supportedTradingAsset ? resolveAssetContextualDirectionForEvidenceItem({ asset: asset as Parameters<typeof resolveAssetContextualDirectionForEvidenceItem>[0]['asset'], evidenceClass: item.evidenceClass, metadataJson: item.metadataJson, observedAt: item.observedAt }) : { resolvedDirection: 'unknown' as const, warnings: ['unsupported_diagnostic_asset'] as string[] };
  const warnings: MarketContradictionWarning[] = [...resolved.warnings.includes('pending_fx_relative_strength') ? ['fx_relative_strength_context_required' as const] : []];
  const reasonCodes: MarketContradictionReasonCode[] = ['contradiction_matrix_rule_applied'];
  if (includesAny(narrative, ['stale','expired'])) warnings.push('stale_evidence_conflict');
  if (includesAny(narrative, ['duplicate','scraped','same headline'])) warnings.push('duplicate_source_risk','source_independence_unverified');
  if (includesAny(narrative, ['price reaction missing','missing_price_reaction'])) warnings.push('missing_price_reaction','pending_price_confirmation');
  if (['macro_calendar','economic_indicator','macro_surprise_history','inflation','labor_market','growth_activity'].includes(item.evidenceClass)) {
    const macro = normalizeMacroSurpriseFromEvidenceItem(item);
    if (macro.reasonCodes.includes('inflation_policy_pressure') || macro.reasonCodes.includes('growth_policy_pressure') || macro.reasonCodes.includes('labor_policy_pressure')) reasonCodes.push('price_confirmation_pending');
    if (macro.warnings.includes('historical_distribution_missing')) warnings.push('macro_surprise_context_required');
  }
  return { evidencePointId: `cmp|${asset}|${item.payloadId}`, asset, horizon, observedAt: item.observedAt, evidenceClass: item.evidenceClass, driverKind: driver, side: resolved.resolvedDirection === 'unknown' ? 'context' : 'supporting', direction: directionForDriver({ payloadId: item.payloadId, asset: asset as WeightedEvidenceItem['asset'], horizon, evidenceTypeId: item.evidenceTypeId, evidenceClass: item.evidenceClass, providerId: item.providerId, observedAt: item.observedAt, finalQualityScore: item.qualityScore.finalQualityScore, baseWeight: item.qualityScore.finalQualityScore, qualityAdjustedWeight: item.qualityScore.finalQualityScore, role: 'context', direction: resolved.resolvedDirection as WeightedEvidenceDirection, contributionScore: resolved.resolvedDirection === 'bullish' ? item.qualityScore.finalQualityScore : resolved.resolvedDirection === 'bearish' ? -item.qualityScore.finalQualityScore : 0, reasons: item.reasons }, driver), strength: item.qualityScore.finalQualityScore, quality: item.qualityScore.finalQualityScore, providerId: item.providerId || null, sourceId: item.providerId || null, rationale: `Raw ${item.evidenceClass} evidence mapped into expanded contradiction context.`, reasonCodes, warnings };
}
const sourceConflictTerms = ['duplicate','scraped','same headline','source conflict','source disagreement'] as const;
function isSourceConflictEvidence(point: MarketContradictionEvidencePoint): boolean {
  return point.warnings.includes('duplicate_source_risk') || point.reasonCodes.includes('source_disagreement_detected') || (point.driverKind === 'source_independence' && includesAny(point.rationale.toLowerCase(), sourceConflictTerms));
}
function sourceDisagreementEvidence(input: MarketContradictionInput): MarketContradictionEvidencePoint[] {
  const duplicateRisk = input.evidencePoints.filter((p) => p.warnings.includes('duplicate_source_risk'));
  const explicitConflict = input.evidencePoints.filter((p) => !p.warnings.includes('duplicate_source_risk') && isSourceConflictEvidence(p));
  if (duplicateRisk.length > 1) return [...duplicateRisk, ...explicitConflict].slice(0, 3);
  if (explicitConflict.length > 0) return explicitConflict.slice(0, 3);
  return [];
}
function points(input: MarketContradictionInput, drivers: readonly Driver[], direction?: Direction): MarketContradictionEvidencePoint[] { return input.evidencePoints.filter((p) => drivers.includes(p.driverKind) && (!direction || p.direction === direction)); }
function has(input: MarketContradictionInput, drivers: readonly Driver[], direction?: Direction): boolean { return points(input, drivers, direction).length > 0; }
function mk(input: MarketContradictionInput, rule: MarketContradictionRule, evidence: MarketContradictionEvidencePoint[], status?: MarketContradictionStatus, warnings?: MarketContradictionWarning[], reasonCodes?: MarketContradictionReasonCode[], rationale?: string): MarketContradictionSignal {
  const mergedWarnings = Array.from(new Set<MarketContradictionWarning>([...rule.warnings, ...evidence.flatMap((p) => p.warnings), ...(warnings ?? []), ...(!input.providerReliabilitySupplied ? ['pending_provider_reliability' as const, 'missing_provider_reliability' as const] : []), ...(!input.sourceIndependenceVerified ? ['source_independence_unverified' as const] : [])]));
  const mergedReasons = Array.from(new Set<MarketContradictionReasonCode>([...rule.reasonCodes, ...evidence.flatMap((p) => p.reasonCodes), ...(reasonCodes ?? []), 'contradiction_matrix_rule_applied']));
  return { signalId: `matrix|${input.asset}|${input.horizon}|${rule.ruleId}|${input.generatedAt}`, ruleId: rule.ruleId, family: rule.family, asset: input.asset, horizon: input.horizon, generatedAt: input.generatedAt, status: status ?? rule.status, severity: rule.severity, confidenceTier: rule.severity === 'critical' || rule.severity === 'high' ? 'high' : rule.severity === 'moderate' ? 'medium' : 'low', evidencePointIds: evidence.map((p) => p.evidencePointId), warnings: mergedWarnings, reasonCodes: mergedReasons, rationale: rationale ?? rule.rationale };
}
function rule(rule: MarketContradictionRule, build: RuleBuilder): BuiltRule { return { ...rule, build }; }
function r(index: number): BuiltRule { const found = RULES[index]; if (!found) throw new Error(`missing_market_contradiction_rule:${index}`); return found; }
const baseWarnings: MarketContradictionWarning[] = ['pending_confidence_calibration','pending_price_confirmation','pending_provider_reliability'];
const RULES: BuiltRule[] = [
  rule({ ruleId:'policy_vs_risk.hawkish_risk_strength', family:'policy_vs_risk', assets:['nasdaq_100','sp500','btc_usd'], requiredDrivers:['central_bank_policy','inflation_surprise','risk_sentiment'], severity:'moderate', status:'tension', reasonCodes:['policy_risk_tension'], warnings:['pending_price_confirmation'], rationale:'Hawkish policy or inflation pressure can conflict with risk-asset strength until price reaction confirms the interpretation.' }, (i) => riskAssets.has(i.asset) && (has(i, ['central_bank_policy'],'bullish') || has(i, ['inflation_surprise'],'bullish')) && has(i, ['risk_sentiment'],'bullish') && !hasUsablePriceReaction(i) ? [mk(i, r(0), [...points(i,['central_bank_policy','inflation_surprise'],'bullish'), ...points(i,['risk_sentiment'],'bullish')], 'tension', ['missing_price_reaction','pending_price_confirmation'], ['price_confirmation_pending'])] : []),
  rule({ ruleId:'rates_vs_gold.real_yield_usd_strength', family:'rates_vs_gold', assets:['xau_usd'], requiredDrivers:['real_yields','dollar_liquidity'], severity:'high', status:'contradiction', reasonCodes:['rates_gold_tension'], warnings:['missing_cross_asset_context'], rationale:'Gold strength can be internally contradicted when real-yield or dollar pressure is also strengthening.' }, (i) => i.asset==='xau_usd' && has(i,['risk_sentiment','safe_haven_demand','geopolitical_risk'],'bullish') && (has(i,['real_yields'],'bullish') || has(i,['dollar_liquidity'],'bullish')) ? [mk(i,r(1),[...points(i,['risk_sentiment','safe_haven_demand','geopolitical_risk'],'bullish'),...points(i,['real_yields','dollar_liquidity'],'bullish')])] : []),
  rule({ ruleId:'fx_base_quote_conflict.strong_two_sides', family:'fx_base_quote_conflict', assets:['eur_usd','gbp_usd','usd_jpy','aud_usd','usd_chf','nzd_usd','usd_cad'], requiredDrivers:['yield_differentials'], severity:'moderate', status:'tension', reasonCodes:['fx_base_quote_conflict'], warnings:['fx_relative_strength_context_required'], rationale:'FX pair evidence is mixed when both base and quote sides show strong pressure.' }, (i) => fxAssets.has(i.asset) && has(i,['yield_differentials','central_bank_policy','macro_surprise'],'bullish') && has(i,['dollar_liquidity','safe_haven_demand'],'bullish') ? [mk(i,r(2),[...points(i,['yield_differentials','central_bank_policy','macro_surprise'],'bullish'),...points(i,['dollar_liquidity','safe_haven_demand'],'bullish')])] : fxAssets.has(i.asset) && i.evidencePoints.length === 1 ? [mk(i,r(2),i.evidencePoints,'insufficient_data',['partial_evidence_only'],[],'One-sided FX evidence is partial context, not a full contradiction.')] : []),
  rule({ ruleId:'risk_vs_volatility.risk_on_vol_shock', family:'risk_vs_volatility', assets:['nasdaq_100','sp500','btc_usd','vix'], requiredDrivers:['risk_sentiment','volatility_surface'], severity:'moderate', status:'tension', reasonCodes:['risk_volatility_tension'], warnings:['pending_price_confirmation'], rationale:'Risk-on pressure conflicts with rising volatility shock evidence and requires confirmation.' }, (i) => has(i,['risk_sentiment'],'bullish') && has(i,['volatility_surface'],'bullish') ? [mk(i,r(3),[...points(i,['risk_sentiment'],'bullish'),...points(i,['volatility_surface'],'bullish')])] : has(i,['risk_sentiment'],'bearish') && has(i,['volatility_surface'],'bearish') ? [mk(i,r(3),[...points(i,['risk_sentiment'],'bearish'),...points(i,['volatility_surface'],'bearish')],'pending_confirmation',['pending_price_confirmation'],['price_confirmation_pending'])] : []),
  rule({ ruleId:'risk_vs_credit.risk_on_credit_stress', family:'risk_vs_credit', assets:['nasdaq_100','sp500','btc_usd'], requiredDrivers:['risk_sentiment','credit_stress'], severity:'moderate', status:'tension', reasonCodes:['credit_risk_tension'], warnings:['pending_price_confirmation'], rationale:'Risk strength is less internally aligned when credit stress is rising.' }, (i) => has(i,['risk_sentiment'],'bullish') && has(i,['credit_stress'],'bullish') ? [mk(i,r(4),[...points(i,['risk_sentiment'],'bullish'),...points(i,['credit_stress'],'bullish')])] : has(i,['risk_sentiment'],'bearish') && has(i,['credit_stress'],'bearish') ? [mk(i,r(4),[...points(i,['risk_sentiment'],'bearish'),...points(i,['credit_stress'],'bearish')])] : []),
  rule({ ruleId:'equities_vs_breadth.index_breadth_divergence', family:'equities_vs_breadth', assets:['nasdaq_100','sp500'], requiredDrivers:['risk_sentiment','equity_breadth'], severity:'moderate', status:'tension', reasonCodes:['breadth_index_divergence'], warnings:['pending_price_confirmation'], rationale:'Index strength with deteriorating breadth is a market-internal tension.' }, (i) => equityAssets.has(i.asset) && has(i,['risk_sentiment'],'bullish') && has(i,['equity_breadth'],'bearish') ? [mk(i,r(5),[...points(i,['risk_sentiment'],'bullish'),...points(i,['equity_breadth'],'bearish')])] : equityAssets.has(i.asset) && has(i,['risk_sentiment'],'bearish') && has(i,['equity_breadth'],'bullish') ? [mk(i,r(5),[...points(i,['risk_sentiment'],'bearish'),...points(i,['equity_breadth'],'bullish')])] : []),
  rule({ ruleId:'crypto_vs_derivatives.btc_leverage_liquidity', family:'crypto_vs_derivatives', assets:['btc_usd'], requiredDrivers:['crypto_derivatives','liquidity_conditions'], severity:'moderate', status:'tension', reasonCodes:['crypto_derivatives_tension'], warnings:['pending_price_confirmation'], rationale:'BTC strength can be tense when derivatives leverage or liquidity deterioration is elevated.' }, (i) => i.asset==='btc_usd' && has(i,['risk_sentiment','crypto_onchain','crypto_etf_flows'],'bullish') && (has(i,['crypto_derivatives'],'bearish') || has(i,['liquidity_conditions','dollar_liquidity'],'bearish')) ? [mk(i,r(6),[...points(i,['risk_sentiment','crypto_onchain','crypto_etf_flows'],'bullish'),...points(i,['crypto_derivatives'],'bearish'),...points(i,['liquidity_conditions','dollar_liquidity'],'bearish')])] : i.asset==='btc_usd' && has(i,['risk_sentiment'],'bearish') && has(i,['crypto_onchain','crypto_etf_flows','liquidity_conditions'],'bullish') ? [mk(i,r(6),[...points(i,['risk_sentiment'],'bearish'),...points(i,['crypto_onchain','crypto_etf_flows','liquidity_conditions'],'bullish')])] : []),
  rule({ ruleId:'commodity_cross_asset.oil_cad_de30', family:'commodity_cross_asset', assets:['usd_cad','de30'], requiredDrivers:['oil_energy','industrial_cycle'], severity:'moderate', status:'tension', reasonCodes:['commodity_margin_tension'], warnings:['missing_cross_asset_context'], rationale:'Oil strength is asset-specific: it can support CAD terms of trade while pressuring energy-sensitive industrial margins.' }, (i) => (i.asset==='usd_cad' || i.asset==='de30') && has(i,['oil_energy'],'bullish') ? [mk(i,r(7),points(i,['oil_energy'],'bullish'),'tension', i.asset==='usd_cad' ? ['fx_relative_strength_context_required'] : ['missing_cross_asset_context'])] : []),
  rule({ ruleId:'safe_haven_conflict.usd_jpy_chf_gold', family:'safe_haven_conflict', assets:['usd_jpy','usd_chf','xau_usd','dxy'], requiredDrivers:['safe_haven_demand','dollar_liquidity','geopolitical_risk'], severity:'moderate', status:'tension', reasonCodes:['haven_cross_conflict'], warnings:['missing_cross_asset_context'], rationale:'Risk-off may support USD, JPY, CHF, and gold differently, creating safe-haven side conflicts.' }, (i) => (['usd_jpy','usd_chf','xau_usd','dxy'] as MarketContradictionAsset[]).includes(i.asset) && (has(i,['safe_haven_demand'],'bullish') || has(i,['geopolitical_risk'],'bullish')) && (has(i,['dollar_liquidity'],'bullish') || i.asset==='usd_jpy' || i.asset==='usd_chf') ? [mk(i,r(8),[...points(i,['safe_haven_demand','geopolitical_risk'],'bullish'),...points(i,['dollar_liquidity'],'bullish')])] : []),
  rule({ ruleId:'macro_vs_price_reaction.missing_confirmation', family:'macro_vs_price_reaction', assets:['xau_usd','eur_usd','gbp_usd','usd_jpy','aud_usd','usd_chf','nzd_usd','usd_cad','btc_usd','nasdaq_100','sp500','de30','dxy'], requiredDrivers:['macro_surprise','event_reaction'], severity:'low', status:'pending_confirmation', reasonCodes:['price_confirmation_pending'], warnings:['missing_price_reaction','pending_price_confirmation'], rationale:'Strong macro surprise pressure remains pending confirmation when price reaction evidence is absent.' }, (i) => has(i,['macro_surprise','inflation_surprise','growth_surprise','labor_market_surprise']) ? (i.priceReaction?.status === 'confirmed' ? [] : i.priceReaction?.status === 'rejected' || i.priceReaction?.status === 'reversed' ? [mk(i,r(9),points(i,['macro_surprise','inflation_surprise','growth_surprise','labor_market_surprise']),'contradiction',['price_reaction_rejected'],priceReactionReasons(i.priceReaction),'Macro surprise pressure conflicts with deterministic post-event price reaction context.')] : i.priceReaction?.status === 'absorbed' ? [mk(i,r(9),points(i,['macro_surprise','inflation_surprise','growth_surprise','labor_market_surprise']),'tension',['price_reaction_absorbed','pending_price_confirmation'],priceReactionReasons(i.priceReaction),'Macro surprise pressure appears absorbed by event-window price action, so confirmation remains cautious.')] : i.priceReaction?.status === 'delayed' || i.priceReaction?.status === 'ambiguous' ? [mk(i,r(9),points(i,['macro_surprise','inflation_surprise','growth_surprise','labor_market_surprise']),'pending_confirmation',priceReactionWarnings(i.priceReaction),priceReactionReasons(i.priceReaction),'Macro surprise pressure has delayed or ambiguous price reaction context.')] : !hasUsablePriceReaction(i) ? [mk(i,r(9),points(i,['macro_surprise','inflation_surprise','growth_surprise','labor_market_surprise']),'pending_confirmation',['missing_price_reaction','pending_price_confirmation'],['price_confirmation_pending'])] : []) : []),
  rule({ ruleId:'provider_staleness_conflict.fresh_over_stale', family:'provider_staleness_conflict', assets:['xau_usd','eur_usd','gbp_usd','usd_jpy','aud_usd','usd_chf','nzd_usd','usd_cad','btc_usd','nasdaq_100','sp500','de30','dxy','vix'], requiredDrivers:['provider_freshness'], severity:'moderate', status:'tension', reasonCodes:['stale_fresh_conflict'], warnings:['stale_evidence_conflict'], rationale:'Fresh evidence should be separated from stale evidence when they point in opposite directions.' }, (i) => { const stale = i.evidencePoints.filter((p)=>p.warnings.includes('stale_evidence_conflict')); const fresh = i.evidencePoints.filter((p)=>!p.warnings.includes('stale_evidence_conflict')); return stale.some((s)=>fresh.some((f)=>s.direction !== 'unknown' && f.direction !== 'unknown' && s.direction !== f.direction)) ? [mk(i,r(10),[...stale,...fresh].slice(0,4))] : []; }),
  rule({ ruleId:'source_disagreement.duplicate_burst', family:'source_disagreement', assets:['xau_usd','eur_usd','gbp_usd','usd_jpy','aud_usd','usd_chf','nzd_usd','usd_cad','btc_usd','nasdaq_100','sp500','de30','dxy','vix'], requiredDrivers:['source_independence'], severity:'low', status:'tension', reasonCodes:['source_disagreement_detected'], warnings:['duplicate_source_risk','source_independence_unverified'], rationale:'Duplicate, scraped, same-headline, or explicit source-conflict evidence is not independent contradiction confirmation.' }, (i) => { const evidence = sourceDisagreementEvidence(i); return evidence.length > 0 ? [mk(i,r(11), evidence, 'tension', !i.sourceIndependenceVerified ? ['source_independence_unverified'] : [])] : []; })
];
function highest(signals: MarketContradictionSignal[]): MarketContradictionSeverity { return signals.map((s)=>s.severity).sort((a,b)=>severityRank[b]-severityRank[a])[0] ?? 'none'; }
function resultStatus(signals: MarketContradictionSignal[]): MarketContradictionStatus { if (signals.some((s)=>s.status==='contradiction')) return 'contradiction'; if (signals.some((s)=>s.status==='tension')) return 'tension'; if (signals.some((s)=>s.status==='pending_confirmation')) return 'pending_confirmation'; return signals.length ? 'aligned' : 'insufficient_data'; }
export function evaluateMarketContradictionMatrix(input: MarketContradictionInput): MarketContradictionMatrixResult {
  const validation = validateMarketContradictionInput(input); if (validation.ok === false) throw new Error(`invalid_market_contradiction_input:${validation.errors.join('|')}`);
  const signals = RULES.flatMap((r)=>r.build(input)).filter((s)=>s.evidencePointIds.length > 0 || s.family === 'source_disagreement');
  const rawWarnings = Array.from(new Set<MarketContradictionWarning>([...baseWarnings, ...input.warnings, ...input.evidencePoints.flatMap((p)=>p.warnings), ...priceReactionWarnings(input.priceReaction), ...signals.flatMap((s)=>s.warnings), ...(!input.providerReliabilitySupplied ? ['missing_provider_reliability' as const] : []), ...(!input.sourceIndependenceVerified ? ['source_independence_unverified' as const] : [])]));
  const warnings = input.priceReaction?.status === 'confirmed' ? rawWarnings.filter((w)=>w !== 'pending_price_confirmation' && w !== 'missing_price_reaction') : rawWarnings;
  const reasonCodes = Array.from(new Set<MarketContradictionReasonCode>([...input.evidencePoints.flatMap((p)=>p.reasonCodes), ...priceReactionReasons(input.priceReaction), ...signals.flatMap((s)=>s.reasonCodes)]));
  const result: MarketContradictionMatrixResult = { resultId:`matrix|${input.asset}|${input.horizon}|${input.generatedAt}`, asset:input.asset, horizon:input.horizon, generatedAt:input.generatedAt, status:resultStatus(signals), highestSeverity:highest(signals), signals, evidencePoints:input.evidencePoints, warnings, reasonCodes, rationale: signals.length ? 'Expanded contradiction matrix found market tension or pending confirmation; this is uncertainty context, not reversal logic.' : 'Expanded contradiction matrix found no deterministic cross-driver contradiction from supplied evidence.', complete:false, pending };
  const v = validateMarketContradictionMatrixResult(result); if (v.ok === false) throw new Error(`invalid_market_contradiction_matrix_result:${v.errors.join('|')}`);
  return result;
}
export function buildContradictionEvidencePointsFromWeightedSnapshot(weightedSnapshot: WeightedEvidenceSnapshot): MarketContradictionEvidencePoint[] { const asset=asAsset(weightedSnapshot.asset); return weightedSnapshot.items.filter((i)=>i.role!=='excluded').map((i)=>evidencePointFromWeighted(i, asset, weightedSnapshot.generatedAt)); }
export function evaluateContradictionsFromWeightedSnapshot(weightedSnapshot: WeightedEvidenceSnapshot, options?: MarketContradictionWeightedSnapshotOptions): MarketContradictionMatrixResult {
  const asset=asAsset(weightedSnapshot.asset); if (fxAssets.has(asset)) { try { resolveFxRelativeStrengthFromWeightedSnapshot(weightedSnapshot); } catch { /* diagnostics remain warnings-only here */ } }
  return evaluateMarketContradictionMatrix({ asset, horizon: weightedSnapshot.horizon, generatedAt: weightedSnapshot.generatedAt, evidencePoints: buildContradictionEvidencePointsFromWeightedSnapshot(weightedSnapshot), priceReactionAvailable: options?.priceReactionAvailable ?? (options?.priceReaction !== undefined), ...(options?.priceReaction ? { priceReaction: options.priceReaction } : {}), providerReliabilitySupplied: options?.providerReliabilitySupplied ?? false, sourceIndependenceVerified: options?.sourceIndependenceVerified ?? false, warnings: [...baseWarnings, ...weightedSnapshot.warnings as MarketContradictionWarning[]] });
}
export function buildContradictionEvidencePointsFromEvidenceItems(asset: MarketContradictionAsset, evidenceItems: MarketContradictionReasoningEvidenceItem[], horizon: EvidenceWeightHorizon = 'intraday'): MarketContradictionEvidencePoint[] { return evidenceItems.map((i)=>evidencePointFromInputItem(asset, i, horizon)); }
export function evaluateContradictionsFromEvidenceItems(asset: MarketContradictionAsset, evidenceItems: MarketContradictionReasoningEvidenceItem[], options?: MarketContradictionEvidenceItemsOptions): MarketContradictionMatrixResult {
  if (fxAssets.has(asset)) { try { resolveFxRelativeStrengthFromEvidenceItems(asset as Parameters<typeof resolveFxRelativeStrengthFromEvidenceItems>[0], evidenceItems, options?.generatedAt ? { asOfIso: options.generatedAt } : undefined); } catch { /* diagnostics remain warnings-only here */ } }
  const generatedAt = options?.generatedAt ?? new Date().toISOString();
  const horizon = options?.horizon ?? 'intraday';
  return evaluateMarketContradictionMatrix({ asset, horizon, generatedAt, evidencePoints: buildContradictionEvidencePointsFromEvidenceItems(asset, evidenceItems, horizon), priceReactionAvailable: options?.priceReactionAvailable ?? (options?.priceReaction !== undefined), ...(options?.priceReaction ? { priceReaction: options.priceReaction } : {}), providerReliabilitySupplied: options?.providerReliabilitySupplied ?? false, sourceIndependenceVerified: options?.sourceIndependenceVerified ?? false, warnings: baseWarnings });
}
export function getMarketContradictionRuleSetSnapshot(asOfIso = new Date().toISOString()): MarketContradictionRuleSetSnapshot { const snapshot: MarketContradictionRuleSetSnapshot = { generatedAt: asOfIso, rules: RULES.map(({ build: _build, ...r }) => r), warnings: baseWarnings, complete:false, pending }; const v=validateMarketContradictionRuleSetSnapshot(snapshot); if(v.ok === false) throw new Error(`invalid_market_contradiction_rule_set:${v.errors.join('|')}`); return snapshot; }
export function getMarketContradictionCoverageReport(asOfIso = new Date().toISOString()): MarketContradictionCoverageReport { const covered = Array.from(new Set(RULES.map((r)=>r.family))).sort() as MarketContradictionFamily[]; const missing = MARKET_CONTRADICTION_FAMILIES.filter((f)=>!covered.includes(f)); const report: MarketContradictionCoverageReport = { generatedAt: asOfIso, familyCount: covered.length, ruleCount: RULES.length, coveredFamilies: covered, missingFamilies: missing, warnings: baseWarnings, complete:false, pending, notes:['C6-R5 expanded contradiction matrix foundation is deterministic and read-only.','Contradiction means tension or uncertainty, not automatic reversal.','C6-R7 deterministic price reaction context is available when supplied; provider reliability expansion remains pending.'] }; const v=validateMarketContradictionCoverageReport(report); if(v.ok === false) throw new Error(`invalid_market_contradiction_coverage:${v.errors.join('|')}`); return report; }
export function assertMarketContradictionRuleSetValid(): MarketContradictionRuleSetSnapshot { return getMarketContradictionRuleSetSnapshot('2026-06-04T00:00:00.000Z'); }
export function listMarketContradictionWarnings(asset?: MarketContradictionAsset): MarketContradictionWarning[] { return asset && fxAssets.has(asset) ? Array.from(new Set([...baseWarnings, 'fx_relative_strength_context_required'])) : [...baseWarnings]; }
export function listMarketContradictionRules(asset?: MarketContradictionAsset): MarketContradictionRule[] { return getMarketContradictionRuleSetSnapshot('2026-06-04T00:00:00.000Z').rules.filter((r)=>!asset || r.assets.includes(asset)); }
