import type { ProviderActivationChecklistItem, ProviderActivationCoverageReport, ProviderActivationEnvironmentRequirement, ProviderActivationReadinessMode, ProviderActivationProviderReadiness, ProviderActivationReadinessReport } from '@elceo/types';

const providerIds = ['alphavantage','etf_fund_issuers','firecrawl','finnhub','fred','gdelt','internal_commercial_entitlement_guard','internal_frontend_contracts','internal_provider_registry','internal_scheduled_ingestion','korapay','marketaux','newsapi','sec_edgar','stripe_mock','whatsapp_provider','email_provider'] as const;
const mkChecklist = (providerId: string, family: ProviderActivationProviderReadiness['family']): ProviderActivationChecklistItem[] => ['activation owner approval required','auth method to verify','env vars required','error mapping to verify','fallback behavior defined','legal/terms/usage review required','logging and redaction configured','production support confirmed','quota behavior confirmed','rate limits confirmed','response schema verified','retry/backoff policy verified','rollback plan required','sandbox/staging support confirmed','smoke test required','timeout policy verified'].sort().map((d,i)=>({id:`${providerId}-${i+1}`,providerId,family,stage:'dry_run_ready',mode:'dry_run',status:'pending',description:d,required:true,ownerRole:'platform_ops',evidenceNote:'placeholder-only evidence; live activation blocked'}));
const mkEnv=(providerId:string, vars:string[]):ProviderActivationEnvironmentRequirement[]=>vars.sort().map((envVar)=>({providerId,envVar,placeholderExample:`YOUR_${envVar}_HERE`,requiredForModes:['staging_live','production_live'],notes:['approval required','placeholder only','production defaults blocked'].sort()}));
const providers: ProviderActivationProviderReadiness[] = providerIds.map((providerId)=>{const family: ProviderActivationProviderReadiness['family'] = providerId.includes('kora')||providerId.includes('stripe') ? 'payment' : providerId.includes('email')||providerId.includes('whatsapp') ? 'notification' : providerId.startsWith('internal_') ? 'internal_runtime' : providerId.includes('news')||providerId.includes('firecrawl')||providerId.includes('gdelt') ? 'news' : providerId.includes('fred') ? 'macro' : providerId.includes('sec') ? 'filings' : 'market_data'; const env = providerId==='korapay' ? ['KORAPAY_PUBLIC_KEY','KORAPAY_SECRET_KEY','KORAPAY_WEBHOOK_SECRET'] : providerId==='email_provider' ? ['EMAIL_PROVIDER_API_KEY','NOTIFICATION_SENDS_ENABLED'] : providerId==='whatsapp_provider' ? ['WHATSAPP_ACCESS_TOKEN','NOTIFICATION_SENDS_ENABLED'] : [`${providerId.toUpperCase()}_API_KEY`]; return {providerId,family,stage:'dry_run_ready',mode:'dry_run',riskLevel:providerId==='korapay'?'critical':'high',liveBlockedByDefault:true,checklist:[...mkChecklist(providerId,family),...(providerId==='korapay'?[{id:'korapay-webhook-signature',providerId,family,stage:'dry_run_ready',mode:'dry_run',status:'pending',description:'official webhook signature docs must be verified',required:true,ownerRole:'billing_ops',evidenceNote:'no live webhook accepted until verified'}]:[]),...(providerId.includes('email')||providerId.includes('whatsapp')?[{id:`${providerId}-no-live-send`,providerId,family,stage:'dry_run_ready',mode:'dry_run',status:'blocked',description:'no live sends until activated',required:true,ownerRole:'notification_ops',evidenceNote:'NOTIFICATION_SENDS_ENABLED remains false'}]:[])],environmentRequirements:mkEnv(providerId,env),smokePlan:{providerId,status:'planned',scenarios:['ensure timeout and retry policy','ensure redaction in logs','validate fixture/sandbox schema contract'].sort(),safetyRules:['no live provider calls in this batch','only staging/sandbox with approval','trade recommendation output prohibited'].sort()},rollbackPlan:{providerId,status:'ready',steps:['alert operator/admin','block webhook entitlement grant','disable activation flag','disable notification sends','preserve audit logs','revert to fixture/dry-run mode','stop scheduler'].sort(),escalation:['application oncall','billing oncall','security oncall'].sort()},approvalGate:{providerId,status:'not_requested',requiredApprovers:['platform_owner','security_owner','product_owner'].sort(),controls:['manual enablement required','security gate pass required','staging smoke plan approval required'].sort()}} as ProviderActivationProviderReadiness;}).sort((a,b)=>a.providerId.localeCompare(b.providerId));

export const listProviderActivationChecklistItems=(providerId?:string)=>providers.filter((p)=>!providerId||p.providerId===providerId).flatMap((p)=>p.checklist).sort((a,b)=>a.id.localeCompare(b.id));
export const getProviderActivationChecklistForProvider=(providerId:string)=>providers.find((p)=>p.providerId===providerId)?.checklist??[];
export const listProviderActivationEnvironmentRequirements=(providerId?:string)=>providers.filter((p)=>!providerId||p.providerId===providerId).flatMap((p)=>p.environmentRequirements).sort((a,b)=>a.envVar.localeCompare(b.envVar));
export const getProviderActivationSmokeTestPlan=(providerId:string)=>providers.find((p)=>p.providerId===providerId)?.smokePlan??null;
export const getProviderActivationRollbackPlan=(providerId:string)=>providers.find((p)=>p.providerId===providerId)?.rollbackPlan??null;
export const assertProviderLiveActivationBlocked=()=>{ if (process.env.ELCEO_LIVE_PROVIDER_ACTIVATION==='true') throw new Error('provider_live_activation_blocked_by_policy'); return true; };
export const evaluateProviderActivationGate=(input:{mode:ProviderActivationReadinessMode; approvals:string[]})=>({allowed:false,reasons:['live activation defaults blocked','manual approval + staged activation required',...(input.mode==='production_live'?['production activation requires explicit override and security approval']:[])].sort()});
export const getProviderActivationReadinessReport=():ProviderActivationReadinessReport=>({generatedAt:new Date().toISOString(),mode:'dry_run',liveActivationAllowed:false,providers,warnings:['all live integrations intentionally disabled','placeholders only; no secrets committed','smoke tests are plans only'].sort()});
export const getProviderActivationCoverageReport=():ProviderActivationCoverageReport=>({generatedAt:new Date().toISOString(),totalProviders:providers.length,providersByFamily:{market_data:providers.filter((x)=>x.family==='market_data').length,news:providers.filter((x)=>x.family==='news').length,macro:providers.filter((x)=>x.family==='macro').length,filings:providers.filter((x)=>x.family==='filings').length,payment:providers.filter((x)=>x.family==='payment').length,notification:providers.filter((x)=>x.family==='notification').length,internal_runtime:providers.filter((x)=>x.family==='internal_runtime').length},blockedByDefaultCount:providers.filter((x)=>x.liveBlockedByDefault).length,smokePlanCoverage:providers.filter((x)=>x.smokePlan.status!=='not_planned').length,rollbackPlanCoverage:providers.filter((x)=>x.rollbackPlan.status!=='not_required').length,approvalGateCoverage:providers.filter((x)=>x.approvalGate.status==='not_requested').length});
