import type { BillingOrchestrationDecisionCode, BillingOrchestrationRun, BillingOrchestrationRunStatus, BillingOrchestrationStepResult, BillingRetryPlan } from '@elceo/types';
import type { BillingOrchestrationRunRepository } from '../persistence';
import { buildBillingRetryPlan } from './retry-planner';
import { isDuplicateRetryPlan } from './duplicate-guard';
import { serializeBillingOrchestrationRun } from './serialization';
import type { BillingAdminQueryService } from '../billing-admin/query-service';
import type { CanonicalBillingLifecycleBoundaryService } from '../runtime/canonical-billing-lifecycle-boundary';
import type { CanonicalBillingPolicyBoundaryService } from '../runtime/canonical-billing-policy-boundary';

const step=(k:BillingOrchestrationStepResult['stepKind'],status:BillingOrchestrationRunStatus,code:BillingOrchestrationDecisionCode,summary:string,startedAt:string):BillingOrchestrationStepResult=>({stepId:`step_${k}_${Date.now()}`,stepKind:k,status,decisionCode:code,summary,startedAt,endedAt:new Date().toISOString(),metadataJson:'{}'});
export class BillingOrchestrationExecutionService { constructor(private repo:BillingOrchestrationRunRepository, private admin:BillingAdminQueryService, private lifecycle:CanonicalBillingLifecycleBoundaryService, private policy:CanonicalBillingPolicyBoundaryService){}
 async runBillingRetryOrchestration(params:{subjectKind:'user';subjectId:string;explicitPlan?:BillingRetryPlan|null;}):Promise<BillingOrchestrationRun>{const startedAt=new Date().toISOString(); const candidate=(await this.admin.listBillingRetryCandidates()).find((c)=>c.subjectId===params.subjectId)??null; const latestRun=await this.lifecycle.getLatestBillingReconciliationRun(params.subjectKind,params.subjectId); const latestPolicy=await this.policy.getLatestBillingPolicyTransition(params.subjectKind,params.subjectId); const plan=params.explicitPlan??(candidate?buildBillingRetryPlan(candidate,latestRun,latestPolicy,startedAt):null); if(!plan){throw new Error('no retry candidate');}
 const steps:BillingOrchestrationStepResult[]=[step('candidate_selection','success','retry_candidate_accepted','candidate selected',startedAt)];
 if(await isDuplicateRetryPlan(this.repo,plan,startedAt)){steps.push(step('completion','skipped','retry_candidate_rejected_duplicate_recent_run','duplicate suppressed',startedAt)); return this.persist(plan,steps,'skipped',false,false,false,null,null,startedAt);}
 if(!plan.retryable){steps.push(step('completion','skipped','retry_candidate_rejected_no_context','not retryable',startedAt)); return this.persist(plan,steps,'skipped',false,false,false,null,null,startedAt);}
 let latestReconciliationRunId:string|null=plan.sourceReconciliationRunId; let latestPolicyTransitionId:string|null=plan.sourcePolicyTransitionId; let changedLifecycle=false; let changedPolicy=false; let changedEntitlement=false;
 if(plan.sourceEventId){try{const rec=await this.lifecycle.reconcileProviderEvent(plan.providerKind,plan.sourceEventId,plan.subjectId); latestReconciliationRunId=rec.run.runId; changedLifecycle=rec.run.customerChanged||rec.run.subscriptionChanged; changedEntitlement=rec.run.entitlementChanged; steps.push(step('reconciliation_retry','success','reconciliation_retry_succeeded','reconciliation succeeded',startedAt));}catch{steps.push(step('reconciliation_retry','failed','reconciliation_retry_failed','reconciliation failed',startedAt));}}
 if(plan.requiresPolicyReEvaluation){try{const p=await this.policy.evaluateBillingPolicyForSubject(plan.subjectKind,plan.subjectId,latestReconciliationRunId??undefined); latestPolicyTransitionId=p.transition.transitionId; changedPolicy=true; steps.push(step('policy_re_evaluation','success','policy_re_evaluation_succeeded','policy re-evaluated',startedAt));}catch{steps.push(step('policy_re_evaluation','failed','policy_re_evaluation_failed','policy evaluation failed',startedAt));}}
 const anyFail=steps.some((s)=>s.status==='failed'); const anySucc=steps.some((s)=>s.status==='success'&&s.stepKind!=='candidate_selection'); const status:BillingOrchestrationRunStatus=anyFail&&anySucc?'partial_success':anyFail?'failed':'success'; const changed=changedLifecycle||changedPolicy||changedEntitlement; steps.push(step('completion',status,changed?'subject_completed_changed':'subject_completed_no_change',changed?'subject changed':'subject unchanged',startedAt));
 return this.persist(plan,steps,status,changedLifecycle,changedPolicy,changedEntitlement,latestReconciliationRunId,latestPolicyTransitionId,startedAt);
 }
 private async persist(plan:BillingRetryPlan,steps:BillingOrchestrationStepResult[],status:BillingOrchestrationRunStatus,changedLifecycle:boolean,changedPolicy:boolean,changedEntitlement:boolean,latestReconciliationRunId:string|null,latestPolicyTransitionId:string|null,startedAt:string){const run:BillingOrchestrationRun={runId:`bor_${plan.subjectId}_${Date.now()}`,subjectKind:plan.subjectKind,subjectId:plan.subjectId,providerKind:plan.providerKind,retryPlan:plan,status,changedLifecycle,changedPolicy,changedEntitlement,latestReconciliationRunId,latestPolicyTransitionId,startedAt,endedAt:new Date().toISOString(),steps,createdAt:startedAt}; await this.repo.saveRun({runId:run.runId,subjectKind:run.subjectKind,subjectId:run.subjectId,providerKind:run.providerKind,retryPlanJson:JSON.stringify(run.retryPlan),status:run.status,changedLifecycle:run.changedLifecycle,changedPolicy:run.changedPolicy,changedEntitlement:run.changedEntitlement,sourceReconciliationRunId:run.latestReconciliationRunId,sourcePolicyTransitionId:run.latestPolicyTransitionId,startedAt:run.startedAt,endedAt:run.endedAt,runJson:serializeBillingOrchestrationRun(run),createdAt:run.createdAt}); return run;}
}
