import {StripeSandboxPaymentProviderAdapter,applyCanonicalSubscriptionLifecycleEvent,assertProductionPaymentActivation,internalPaymentRuntime,reconcileStripePaymentOperation,validateStripeCommercialIdentity} from '@elceo/application-state';
import {captureError} from '../../../../lib/monitoring';

const lifecycleKind=(type:string)=>type==='customer.subscription.created'?'subscription_created':type==='customer.subscription.updated'?'subscription_updated':type==='customer.subscription.deleted'?'subscription_deleted':type==='invoice.payment_succeeded'||type==='invoice.paid'?'renewal_succeeded':type==='invoice.payment_failed'?'renewal_failed':null;
export async function POST(request:Request){
 try{
  const mode=process.env.PAYMENT_PROVIDER_MODE;if(mode==='production_provider')assertProductionPaymentActivation(process.env,'stripe');else if(mode!=='sandbox_provider')return Response.json({error:'stripe_webhook_activation_required'},{status:503});
  const raw=await request.text(),adapter=new StripeSandboxPaymentProviderAdapter(),event=adapter.parseWebhookEvent(raw,request.headers.get('stripe-signature'));
  let op=event.metadataOperationId?await internalPaymentRuntime.repository.getOperation(event.metadataOperationId):null;if(!op&&event.providerSessionReference)op=await internalPaymentRuntime.repository.findBySessionReference(event.providerSessionReference);if(!op&&event.providerPaymentReference)op=await internalPaymentRuntime.repository.findByProviderReference(event.providerPaymentReference);if(!op&&event.providerSubscriptionReference)op=await internalPaymentRuntime.repository.findBySubscriptionReference(event.providerSubscriptionReference);if(!op||!event.providerEventId)return Response.json({ok:true,matched:false},{status:202});
  const reference=op.providerCheckoutSessionReference??op.providerPaymentReference??op.providerSubscriptionReference;if(!reference)return Response.json({ok:true,reconciliationRequired:true},{status:202});
  const negative=event.refundOrReversalOrChargeback;if(negative!=='none'){const truth=await adapter.retrievePaymentOrSession(reference);if(validateStripeCommercialIdentity(op,truth))return Response.json({ok:true,reconciliationRequired:true},{status:202});const kind=negative==='refund'?'refund':negative==='partial_refund'?'partial_refund':negative==='reversal'?'reversal':'chargeback';const result=await internalPaymentRuntime.webhook({eventId:event.providerEventId,kind,operationId:op.internalPaymentOperationId,providerPaymentReference:truth.providerPaymentReference,providerCheckoutSessionReference:truth.providerSessionReference});return Response.json({ok:true,duplicate:result.duplicate,negativeEffect:kind});}
  const lifecycle=lifecycleKind(event.providerEventType);if(lifecycle){const truth=await adapter.retrievePaymentOrSession(reference);if(validateStripeCommercialIdentity(op,truth))return Response.json({ok:true,reconciliationRequired:true},{status:202});const result=await applyCanonicalSubscriptionLifecycleEvent({providerEventId:event.providerEventId,kind:lifecycle,operationId:op.internalPaymentOperationId,providerPaymentReference:truth.providerPaymentReference,providerSessionReference:truth.providerSessionReference,providerCustomerReference:truth.providerCustomerReference,providerSubscriptionReference:truth.providerSubscriptionReference,subjectUserId:truth.metadataSubjectUserId,targetPlan:truth.metadataTargetPlan,billingInterval:truth.metadataBillingInterval,subscriptionState:truth.subscriptionState,currentPeriodStart:truth.currentPeriodStart,currentPeriodEnd:truth.currentPeriodEnd,cancelAtPeriodEnd:truth.cancelAtPeriodEnd,occurredAt:event.createdAt??new Date().toISOString()});return Response.json({ok:true,...result},{status:result.status==='reconciliation_required'?202:200});}
  const result=await reconcileStripePaymentOperation(internalPaymentRuntime.repository,adapter,op.internalPaymentOperationId,event.providerEventId);return Response.json({ok:true,status:result.status,reconciliationRequired:result.status!=='matched'},{status:result.status==='matched'?200:202});
 }catch(error){captureError('api.billing.webhook',error,{});return Response.json({error:'stripe_webhook_unavailable'},{status:503});}
}
