import type { CanonicalAssetSymbol } from '@elceo/types';
import type { EventRealityEvaluation, SourceProvenance } from '../expectation-reality/contracts';

export type NarrativeDecayPolicyVersion = 'narrative-decay-v1';
export type NarrativeState = 'active' | 'decaying' | 'expired';
export type NarrativeEvidenceSufficiency = 'sufficient' | 'insufficient_data' | 'provenance_limited';
export type NarrativeDirection = 'bullish' | 'bearish' | 'neutral' | 'unresolved';
export type NarrativeComponentName = 'primary_reaction_persistence'|'follow_through_continuity'|'related_market_persistence'|'revision_impact'|'cognition_persistence'|'analog_decay_context'|'provenance_quality';

export type NarrativePriceCandle = Readonly<{ openedAt:string; closedAt:string; open:number; high:number; low:number; close:number; complete:boolean }>;
export type NarrativePriceObservation = Readonly<{ sourceId:string; provider:string; payloadRef?:string|null; observationVersion:string; asset:CanonicalAssetSymbol; candles:readonly NarrativePriceCandle[]; reliability:SourceProvenance['reliability']; effectiveReliability?:SourceProvenance['effectiveReliability']; trustBasis?:string|null; verificationRef?:string|null; verifiedAt?:string|null }>;
export type NarrativeContinuationObservationRecord = Readonly<{ observationId:string; policyVersion:NarrativeDecayPolicyVersion; expectationId:string; eventReleaseId:string; releaseVersion:string; sourceEventEvaluationId:string; asset:CanonicalAssetSymbol; observedAt:string; availableAt:string; evidenceCutoffAt:string; windowStartAt:string; windowEndAt:string; primaryPriceObservation:NarrativePriceObservation; relatedPriceObservations:readonly NarrativePriceObservation[]; cognitionSnapshotId:string|null; warnings:readonly string[]; limitations:readonly string[]; canonicalPayloadHash:string; createdAt:string }>;
export type NarrativeContinuationObservationDraft = Omit<NarrativeContinuationObservationRecord,'observationId'|'canonicalPayloadHash'|'createdAt'>;

export type NarrativeFamilyIdentity = Readonly<{ narrativeFamilyId:string; expectationId:string; eventReleaseId:string; scheduledReleaseTime:string; asset:CanonicalAssetSymbol; eventKind:string; indicatorKind:string; indicatorCategory:string }>;
export type NarrativeVersionIdentity = Readonly<{ narrativeVersionId:string; narrativeFamilyId:string; releaseVersion:string; sourceEventEvaluationId:string; releaseObservedAt:string; resolvedDirection:NarrativeDirection; revisionAdjustedInterpretation:string; assessmentEvidenceHash:string }>;
export type NarrativeComponent = Readonly<{ component:NarrativeComponentName; weight:number; availability:'available'|'unavailable'|'not_expected'|'provenance_limited'; score:number|null; weightedScore:number; coverage:number; rationale:string; warnings:readonly string[]; limitations:readonly string[] }>;
export type NarrativeCheckpoint = Readonly<{ observationId:string; observedAt:string; epochAnchor:number|null; rawPersistenceScore:number; expectedWeight:number; availableWeight:number; evidenceCoverageRatio:number; evidenceQualifiedPersistenceScore:number; primaryRetentionRatio:number|null; terminalSignedMovePct:number|null; peakSignedCloseMovePct:number|null; volatilityAdjustedRetention:number|null; materialOppositeMove:boolean; relatedConfirmedConflict:boolean; continuity:'continued_acceptance'|'delayed_acceptance'|'absorption'|'fading'|'acceptance_loss'|'reversal'|'renewed_acceptance'|'two_sided_expansion'|'insufficient'; components:readonly NarrativeComponent[] }>;
export type HalfLifeAssessment = Readonly<{ halfLifeStatus:'observed_interval'|'not_reached'|'insufficient_data'; halfLifeLowerBoundMinutes:number|null; halfLifeUpperBoundMinutes:number|null; halfLifeCrossingObservationId:string|null }>;
export type SourceUpdateLedger = Readonly<{ latestSourceUpdateAt:string; materialSourceUpdateAt:string|null; sourceIds:readonly string[]; distinctSourceCount:number; duplicateSourceCount:number; contentChanged:boolean; releaseVersionChanged:boolean; warnings:readonly string[] }>;
export type NarrativeCognitionAudit = Readonly<{ epochSnapshotId:string|null; currentSnapshotId:string|null; startConfidence:number|null; currentConfidence:number|null; confidenceDelta:number|null; startContradiction:number|null; currentContradiction:number|null; contradictionDelta:number|null; biasChanged:boolean|null }>;
export type NarrativeDecayEvaluation = Readonly<{ narrativeDecayEvaluationId:string; policyVersion:NarrativeDecayPolicyVersion; family:NarrativeFamilyIdentity; version:NarrativeVersionIdentity; sourceEventEvaluationId:string; sourceExpectationId:string; sourceAnalogRetrievalId:string|null; analogMemoryIds:readonly string[]; observationIds:readonly string[]; eventVersionIds:readonly string[]; asset:CanonicalAssetSymbol; eventKind:string; indicatorCategory:string; revisionFamily:string; evidenceCutoffAt:string; narrativeAsOf:string; narrativeState:NarrativeState|null; evidenceSufficiency:NarrativeEvidenceSufficiency; resolvedDirection:NarrativeDirection; epochStartedAt:string; epochReset:boolean; epochResetReason:'material_reinforcing_revision'|'material_reversal'|null; priorNarrativeVersionId:string|null; supersededNarrativeVersionId:string|null; supersededByNarrativeVersionId:string|null; checkpoints:readonly NarrativeCheckpoint[]; cognition:NarrativeCognitionAudit; peakQualifiedPersistenceScore:number; peakObservedAt:string|null; currentQualifiedPersistenceScore:number; currentPersistenceRatioToPeak:number|null; halfLife:HalfLifeAssessment; sourceUpdates:SourceUpdateLedger; recoveryObserved:boolean; terminalExpiryReason:string|null; warnings:readonly string[]; limitations:readonly string[]; deterministicRationale:string; canonicalPayloadHash:string; createdAt:string }>;
export type NarrativeDecayServiceInput = Readonly<{ eventEvaluationId:string; evidenceCutoffAt:string; analogRetrievalId?:string; sourceUpdates?:readonly SourceProvenance[] }>;
export type NarrativeDecayEvaluationContext = Readonly<{ event:EventRealityEvaluation; eventVersions:readonly EventRealityEvaluation[]; observations:readonly NarrativeContinuationObservationRecord[]; priorEvaluation?:NarrativeDecayEvaluation|null; startCognition:{snapshotId:string;confidence:number;contradiction:number;bias:string;asset:CanonicalAssetSymbol;evaluatedAt:string;createdAt:string}|null; cognitionById:ReadonlyMap<string,{snapshotId:string;evaluatedAt:string;createdAt:string;confidence:number;contradiction:number;bias:string;asset:CanonicalAssetSymbol}>; analogContext?:Readonly<{ retrievalId:string; retrievalSufficiency:'sufficient'|'sparse'|'insufficient_feature_overlap'|'provenance_limited'|'no_comparable_history'; memoryIds:readonly string[]; sufficiency:NarrativeEvidenceSufficiency; comparableCount:number; persistentCount:number; fadedCount:number; reversedCount:number; censoredCount:number; score:number|null; limitations:readonly string[] }>; evidenceCutoffAt:string; sourceUpdates:readonly SourceProvenance[] }>;

export type NarrativeDecayDistributionReport = Readonly<{ generatedAt:string; groupBy:'asset'|'event_kind'|'indicator_category'|'revision_family'|'policy_version'; groups:readonly {key:string;sampleSize:number;activeCount:number;decayingCount:number;expiredCount:number;insufficientCount:number;provenanceLimitedCount:number;observedHalfLifeCount:number;rightCensoredCount:number;halfLifeIntervals:readonly {lower:number;upper:number;count:number}[];ageMinutes:readonly number[];componentAvailability:Record<string,number>;revisionResetCount:number;revisionReversalCount:number;relatedFadeCount:number;recoveryCount:number;provenanceLimitations:number}[]; warnings:readonly string[]; limitations:readonly string[] }>;
