import { canonicalHash, canonicalJson, deepCloneFreeze } from '../expectation-reality/identity';
import type { EventExpectationRecord, EventRealityEvaluation } from '../expectation-reality/contracts';
import type { NarrativeContinuationObservationDraft, NarrativeContinuationObservationRecord, NarrativeDecayEvaluation, NarrativeDirection, NarrativeFamilyIdentity, NarrativePriceObservation, NarrativeVersionIdentity } from './contracts';
const time=(v:string)=>{const n=Date.parse(v);if(!Number.isFinite(n))throw new Error('narrative_invalid_timestamp');return n;};
export function normalizePriceObservation(input:NarrativePriceObservation):NarrativePriceObservation{const byTime=new Map<string,NarrativePriceObservation['candles'][number]>();for(const candle of input.candles){time(candle.openedAt);time(candle.closedAt);if(time(candle.openedAt)>=time(candle.closedAt))throw new Error('narrative_observation_invalid_candle');const key=`${candle.openedAt}|${candle.closedAt}`;const prior=byTime.get(key);if(prior&&canonicalJson(prior)!==canonicalJson(candle))throw new Error('narrative_observation_conflicting_candle');byTime.set(key,candle);}return deepCloneFreeze({...input,candles:[...byTime.values()].sort((a,b)=>time(a.openedAt)-time(b.openedAt)||time(a.closedAt)-time(b.closedAt))});}
export function createObservationRecord(draft:NarrativeContinuationObservationDraft,createdAt=draft.evidenceCutoffAt):NarrativeContinuationObservationRecord{const primary=normalizePriceObservation(draft.primaryPriceObservation);const related=[...draft.relatedPriceObservations].map(normalizePriceObservation).sort((a,b)=>a.asset.localeCompare(b.asset)||a.sourceId.localeCompare(b.sourceId));const body={...draft,primaryPriceObservation:primary,relatedPriceObservations:related,warnings:[...new Set(draft.warnings)].sort(),limitations:[...new Set(draft.limitations)].sort()};const canonicalPayloadHash=canonicalHash(body);return deepCloneFreeze({...body,observationId:`ndo_${canonicalPayloadHash.slice(0,32)}`,canonicalPayloadHash,createdAt});}
export function resolveNarrativeDirection(event:EventRealityEvaluation):NarrativeDirection{const actual=event.reality.actualAssetDirections.find(x=>x.asset===event.asset)?.resolvedDirection ?? event.reality.releaseAlignment.actualDirection;if(actual==='bullish'||actual==='up')return'bullish';if(actual==='bearish'||actual==='down')return'bearish';if(actual==='neutral'||event.reality.releaseAlignment.status==='inline'||event.reality.revisionAdjustedMeasures.revisionAdjustedDirection==='inline')return'neutral';return'unresolved';}
export function narrativeFamily(expectation:EventExpectationRecord):NarrativeFamilyIdentity{const body={expectationId:expectation.expectationId,eventReleaseId:expectation.eventReleaseId,scheduledReleaseTime:expectation.scheduledReleaseTime,asset:expectation.asset,eventKind:expectation.eventKind,indicatorKind:String(expectation.indicatorKind),indicatorCategory:String(expectation.indicatorCategory)};return {...body,narrativeFamilyId:`ndf_${canonicalHash(body).slice(0,32)}`};}
export function narrativeVersion(event:EventRealityEvaluation,family:NarrativeFamilyIdentity):NarrativeVersionIdentity{const body={narrativeFamilyId:family.narrativeFamilyId,releaseVersion:event.releaseVersion,sourceEventEvaluationId:event.eventEvaluationId,releaseObservedAt:event.reality.observedAt,resolvedDirection:resolveNarrativeDirection(event),revisionAdjustedInterpretation:`${event.reality.revisionAdjustedMeasures.revisionEffect}:${event.reality.revisionAdjustedMeasures.revisionAdjustedDirection}`,assessmentEvidenceHash:event.assessmentEvidenceHash};return {...body,narrativeVersionId:`ndv_${canonicalHash(body).slice(0,32)}`};}
export function finalizeEvaluation(body:Omit<NarrativeDecayEvaluation,'narrativeDecayEvaluationId'|'canonicalPayloadHash'>):NarrativeDecayEvaluation{const hash=canonicalHash(body);return deepCloneFreeze({...body,narrativeDecayEvaluationId:`nde_${hash.slice(0,32)}`,canonicalPayloadHash:hash});}
