import { runSourceReliabilityTests } from './source-reliability.test.js';
import { runEventRecencyTests } from './event-recency.test.js';
import { runEventRelevanceTests } from './event-relevance.test.js';
import { runEventDedupeTests, runEventMergeTests } from './event-dedupe.test.js';
import { runCompositeEventIngestionTests } from './composite-event-ingestion.test.js';
import { runProviderSuiteBuilderTests } from './provider-suite-builder.test.js';
import { runCanonicalIngestionFacadeTests } from './canonical-ingestion-facade.test.js';
import { runLegacyBridgeTests } from './legacy-bridge.test.js';
import { runActiveBoundaryTests } from './active-boundary.test.js';
import { runRuntimeConfigTests } from './runtime-config.test.js';
import { runRunReportHelperTests } from './run-report-helpers.test.js';
import { runCanonicalWorkerBoundaryTests } from './canonical-worker-boundary.test.js';
import { runWorkerRuntimeAdoptionTests } from './worker-runtime-adoption.test.js';
import { runPersistenceRepositoryTests } from './persistence-repository.test.js';
import { runReplayQueryTests } from './replay-query.test.js';
import { runRuntimePersistenceIntegrationTests } from './runtime-persistence-integration.test.js';
import { runSchedulerFrequencyTests } from './scheduler-frequency.test.js';
import { runSchedulerRequestKeyTests } from './scheduler-request-key.test.js';
import { runSchedulerLeaseRepositoryTests } from './scheduler-lease-repository.test.js';
import { runSchedulerDuePlannerTests } from './scheduler-due-planner.test.js';
import { runSchedulerTickServiceTests } from './scheduler-tick-service.test.js';
import { runTriggerContextPersistenceTests } from './trigger-context-persistence.test.js';
import { runOutboxStagingTests } from './outbox-staging.test.js';
import { runOutboxRepositoryTests } from './outbox-repository.test.js';
import { runOutboxPublisherTests } from './outbox-publisher.test.js';
import { runReplayPublishTests } from './replay-publish.test.js';
import { runRuntimeOutboxIntegrationTests } from './runtime-outbox-integration.test.js';
import { runPublishTransportTests } from './publish-transport.test.js';

async function run(): Promise<void> {
  runSourceReliabilityTests();
  runEventRecencyTests();
  runEventRelevanceTests();
  runEventDedupeTests();
  runEventMergeTests();
  await runCompositeEventIngestionTests();
  runProviderSuiteBuilderTests();
  await runCanonicalIngestionFacadeTests();
  await runLegacyBridgeTests();
  runActiveBoundaryTests();
  runRuntimeConfigTests();
  runRunReportHelperTests();
  await runCanonicalWorkerBoundaryTests();
  runWorkerRuntimeAdoptionTests();
  await runPersistenceRepositoryTests();
  await runReplayQueryTests();
  await runRuntimePersistenceIntegrationTests();
  runSchedulerFrequencyTests();
  runSchedulerRequestKeyTests();
  await runSchedulerLeaseRepositoryTests();
  await runSchedulerDuePlannerTests();
  await runSchedulerTickServiceTests();
  await runTriggerContextPersistenceTests();
  await runOutboxStagingTests();
  await runOutboxRepositoryTests();
  await runOutboxPublisherTests();
  await runReplayPublishTests();
  await runRuntimeOutboxIntegrationTests();
  await runPublishTransportTests();
  console.log('ingestion tests passed');
}

run();
