import type { MarketAssetCausalityAsset, MarketAssetCausalityCoverageReport, MarketAssetCausalityDescriptor, MarketAssetCausalityDriver, MarketAssetCausalityGap, MarketAssetCausalityMatrixSnapshot, MarketAssetContradictionTrigger, MarketAssetDirectionResolutionRequirement, MarketAssetDriverDirectionSensitivity, MarketAssetDriverKind, MarketAssetFamily, MarketAssetProviderDependency, MarketAssetProviderDependencyTier, MarketAssetRegimeModifier } from '@elceo/types';
import { MARKET_ASSET_CAUSALITY_ASSETS } from '@elceo/types';
import { validateMarketAssetCausalityMatrixSnapshot } from '@elceo/schemas';

const PHASE_GAPS: MarketAssetCausalityGap[] = [
  { gapId: 'c6-r2-direction-resolution', asset: 'all', phase: 'R2', status: 'pending_r2_r9', description: 'Asset-contextual direction resolution remains pending.' },
  { gapId: 'c6-r3-fx-relative-strength', asset: 'all', phase: 'R3', status: 'pending_r2_r9', description: 'FX base and quote relative strength engine remains pending.' },
  { gapId: 'c6-r4-macro-surprise-normalization', asset: 'all', phase: 'R4', status: 'pending_r2_r9', description: 'Macro surprise normalization by release type remains pending.' },
  { gapId: 'c6-r5-contradiction-matrix', asset: 'all', phase: 'R5', status: 'pending_r2_r9', description: 'Expanded contradiction detection matrix remains pending.' },
  { gapId: 'c6-r6-confidence-calibration', asset: 'all', phase: 'R6', status: 'pending_r2_r9', description: 'Confidence calibration upgrade remains pending.' },
  { gapId: 'c6-r7-price-reaction', asset: 'all', phase: 'R7', status: 'pending_r2_r9', description: 'Price reaction and event impulse engine remains pending.' },
  { gapId: 'c6-r8-provider-gap-weighting', asset: 'all', phase: 'R8', status: 'pending_r2_r9', description: 'Provider reliability and activation-gap weighting remains pending.' },
  { gapId: 'c6-r9-golden-scenarios', asset: 'all', phase: 'R9', status: 'pending_r2_r9', description: 'Golden scenario expansion remains pending.' }
];

type DriverSeed = readonly [MarketAssetDriverKind, string, string, MarketAssetDriverDirectionSensitivity[]];
const driver = (asset: MarketAssetCausalityAsset, importance: 'primary'|'secondary'|'contextual', seed: DriverSeed): MarketAssetCausalityDriver => ({ driverId: `${asset}:${seed[0]}:${importance}`, kind: seed[0], importance, evidenceClasses: seed[1].split(','), directionSensitivity: seed[3], interpretation: seed[2], rationale: `${asset} uses ${seed[0]} as ${importance} evidence because this driver changes the asset pressure only after asset-specific context is applied.` });
const mod = (asset: MarketAssetCausalityAsset, kind: MarketAssetRegimeModifier['kind'], text: string): MarketAssetRegimeModifier => ({ modifierId: `${asset}:${kind}`, kind, interpretation: text, rationale: `${kind} can alter driver priority for ${asset} and must be visible before later scoring engines change confidence.` });
const trig = (asset: MarketAssetCausalityAsset, kind: MarketAssetContradictionTrigger['kind'], text: string): MarketAssetContradictionTrigger => ({ triggerId: `${asset}:${kind}`, kind, detectionIntent: text, rationale: `${asset} needs this contradiction contract so later engines can flag evidence tension instead of forcing a single simple pressure.` });
const dep = (asset: MarketAssetCausalityAsset, id: string, tier: MarketAssetProviderDependencyTier, sourceIds: MarketAssetProviderDependency['sourceIds'], classes: string[], status: MarketAssetProviderDependency['currentStatus']): MarketAssetProviderDependency => ({ dependencyId: `${asset}:${id}`, tier, sourceIds, evidenceClasses: classes, currentStatus: status, rationale: `${id} sources are ${tier} for ${asset}; current ELCEO coverage is ${status} and must not be over-weighted while live activation is blocked.` });
const req = (asset: MarketAssetCausalityAsset, base: boolean, quote: boolean, relative: boolean, surprise: boolean, price: boolean, id = 'direction-contract'): MarketAssetDirectionResolutionRequirement => ({ requirementId: `${asset}:${id}`, asset, requiresBasePressure: base, requiresQuotePressure: quote, requiresRelativeStrength: relative, requiresSurpriseNormalization: surprise, requiresPriceConfirmation: price, rationale: `${asset} direction must be resolved from explicit pressure requirements and later price confirmation, not a generic sentiment label.` });

function descriptor(asset: MarketAssetCausalityAsset, displayName: string, family: MarketAssetFamily, primary: DriverSeed[], secondary: DriverSeed[], contextual: DriverSeed[], providerDependencies: MarketAssetProviderDependency[], directionResolutionRequirements: MarketAssetDirectionResolutionRequirement[], currentCodeCoverage: string[], knownGaps: MarketAssetCausalityGap[], implementationPhaseDependencies: string[], regimeKinds: MarketAssetRegimeModifier[], triggerKinds: MarketAssetContradictionTrigger[], freshnessSensitivity: MarketAssetCausalityDescriptor['freshnessSensitivity'], priceConfirmationNeeds: MarketAssetCausalityDescriptor['priceConfirmationNeeds'], macroEventSensitivity: MarketAssetCausalityDescriptor['macroEventSensitivity']): MarketAssetCausalityDescriptor {
  return { asset, displayName, family, primaryDrivers: primary.map((x) => driver(asset, 'primary', x)), secondaryDrivers: secondary.map((x) => driver(asset, 'secondary', x)), contextualDrivers: contextual.map((x) => driver(asset, 'contextual', x)), regimeModifiers: regimeKinds, contradictionTriggers: triggerKinds, freshnessSensitivity, priceConfirmationNeeds, macroEventSensitivity, providerDependencies, directionResolutionRequirements, currentCodeCoverage, knownGaps, implementationPhaseDependencies, rationale: `${displayName} is mapped as a C6-R1 causality contract only; downstream C6 engines remain pending and no final market-intelligence realism is claimed.` };
}
const standardCoverage = ['C6-R0 docs identify truth-source gaps.', 'Provider registry and fixture libraries expose partial source coverage.', 'Weighting, taxonomy, contradiction, and confidence modules exist but are not asset-complete causality engines.'];
const stdTriggers = (a: MarketAssetCausalityAsset): MarketAssetContradictionTrigger[] => [trig(a, 'driver_price_divergence', 'Expected driver pressure conflicts with observed market structure.'), trig(a, 'provider_activation_gap', 'Fixture or dry-run evidence attempts to dominate live-blocked provider gaps.')];

const DESCRIPTORS: MarketAssetCausalityDescriptor[] = [
  descriptor('xau_usd','XAU/USD','precious_metals',
    [['real_yields','rates,real_yields','Lower real yield pressure is supportive for non-yielding gold; higher real yields can pressure gold.',['inverse','requires_direction_resolver','requires_price_confirmation']], ['dollar_liquidity','liquidity,dollar','USD liquidity and dollar funding context determine whether gold trades as money or commodity.',['inverse','regime_dependent','requires_direction_resolver']], ['safe_haven_demand','risk,geopolitical','Haven demand matters when stress is credible and confirmed by cross-market risk evidence.',['direct_positive','regime_dependent']], ['etf_flows','flows,metals','ETF and metals flows provide allocation confirmation with lag awareness.',['direct_positive','requires_price_confirmation']]],
    [['central_bank_demand','official_flows,metals','Official-sector demand can alter gold floor dynamics but is often lagged.',['direct_positive','regime_dependent']], ['positioning_cot','positioning,cot','COT positioning can reveal crowded metal exposure and should be lag discounted.',['regime_dependent','requires_price_confirmation']]],
    [['geopolitical_risk','news,risk','Geopolitical shock evidence is contextual unless confirmed by haven and price reaction.',['regime_dependent','requires_price_confirmation']]],
    [dep('xau_usd','price-rates', 'must_have', ['tiingo_market_data','us_treasury_official','fred_macro'], ['market_price','real_yields'], 'partially_covered'), dep('xau_usd','flows-positioning', 'important', ['cftc_cot','etf_flows_shell'], ['positioning','etf_flows'], 'pending_provider_activation')], [req('xau_usd', false, true, false, true, true)], standardCoverage, PHASE_GAPS, ['R2','R4','R5','R6','R7','R8','R9'], [mod('xau_usd','risk_off','Risk-off can raise haven priority over normal rate sensitivity.'), mod('xau_usd','inflation_shock','Inflation shocks require separating nominal yields from real yields.')], stdTriggers('xau_usd').concat(trig('xau_usd','flow_price_divergence','ETF or metal flow evidence conflicts with gold price reaction.')), 'high','event_window_required','high'),
  descriptor('btc_usd','BTC/USD','crypto',
    [['liquidity_conditions','liquidity,financial_conditions','Broad liquidity conditions are primary for crypto beta and leverage cycles.',['direct_positive','regime_dependent','requires_price_confirmation']], ['crypto_derivatives','derivatives,leverage','Funding, liquidations, and open interest shape event impulse and crowdedness.',['regime_dependent','requires_price_confirmation']], ['crypto_onchain','onchain,network','On-chain activity contextualizes participation and transfer stress.',['regime_dependent']], ['risk_sentiment','risk,equity','Crypto often trades with risk appetite but can decouple during crypto-native stress.',['direct_positive','regime_dependent']]],
    [['crypto_etf_flows','etf_flows,flows','ETF flow evidence can confirm institutional demand with freshness limits.',['direct_positive','requires_price_confirmation']], ['regulatory_risk','news,policy','Regulatory shocks can dominate liquidity signals during event windows.',['direct_negative','regime_dependent','requires_price_confirmation']]],
    [['dollar_liquidity','dollar,liquidity','Dollar funding stress can override crypto-native positives.',['inverse','regime_dependent']]],
    [dep('btc_usd','crypto-native', 'must_have', ['crypto_exchange_public','crypto_onchain_public','crypto_derivatives_shell'], ['crypto_onchain','crypto_derivatives'], 'partially_covered'), dep('btc_usd','etf-regulatory', 'important', ['etf_flows_shell','sec_edgar','marketaux_news'], ['crypto_etf_flows','regulatory_risk'], 'pending_provider_activation')], [req('btc_usd', false, true, false, false, true)], standardCoverage, PHASE_GAPS, ['R2','R5','R6','R7','R8','R9'], [mod('btc_usd','crypto_leverage_cycle','Crypto leverage cycles can invert otherwise simple risk interpretation.'), mod('btc_usd','liquidity_stress','Liquidity stress can dominate on-chain participation.')], stdTriggers('btc_usd').concat(trig('btc_usd','liquidity_risk_divergence','Crypto-native leverage improves while broader liquidity deteriorates.')), 'very_high','event_window_required','medium'),
];

const fx = (asset: MarketAssetCausalityAsset, name: string, family: MarketAssetFamily, baseBank: string, quoteBank: string, extraPrimary: DriverSeed, extraSecondary: DriverSeed[], providers: MarketAssetProviderDependency[]): MarketAssetCausalityDescriptor => descriptor(asset, name, family,
  [['central_bank_policy','policy,central_bank',`${baseBank} and ${quoteBank} policy paths must be compared as two sides of the pair.`,['relative','pair_base_positive','pair_quote_positive','requires_direction_resolver']], ['yield_differentials','rates,yields','Rate differentials require base-versus-quote pressure rather than single-currency scoring.',['relative','pair_base_positive','pair_quote_positive','requires_direction_resolver']], ['growth_surprise','macro,growth','Growth surprises must be normalized by region and release importance.',['relative','requires_surprise_normalization']], extraPrimary],
  [['risk_sentiment','risk,liquidity','Risk regime changes whether carry, haven, or commodity beta dominates.',['regime_dependent','requires_direction_resolver']], ...extraSecondary],
  [['market_price_structure','price,technicals','Pair reaction confirms whether macro pressure is being absorbed.',['requires_price_confirmation']]],
  providers, [req(asset, true, true, true, true, true)], standardCoverage, PHASE_GAPS, ['R2','R3','R4','R5','R6','R7','R8','R9'], [mod(asset,'policy_surprise','Policy surprise can re-rank rate and growth evidence.'), mod(asset,'risk_off','Risk-off can favor haven currencies over carry logic.')], stdTriggers(asset).concat(trig(asset,'base_quote_pressure_conflict','Base and quote pressure point in competing directions.')), 'high','high','very_high');

DESCRIPTORS.push(
  fx('eur_usd','EUR/USD','fx_major','ECB/eurozone','Fed/U.S.',['financial_conditions','liquidity,financial_conditions','European and U.S. financial conditions shape relative euro-dollar pressure.',['relative','regime_dependent']], [['fiscal_risk','fiscal,eurozone','Eurozone fiscal spread concerns can alter EUR pressure.',['regime_dependent']]], [dep('eur_usd','euro-us-policy', 'must_have', ['ecb_official','federal_reserve_official','eurostat_official','bls_official'], ['policy','macro'], 'partially_covered')]),
  fx('gbp_usd','GBP/USD','fx_major','BoE/U.K.','Fed/U.S.',['financial_conditions','liquidity,financial_conditions','U.K. and U.S. financial conditions define relative sterling-dollar stress.',['relative','regime_dependent']], [['fiscal_risk','fiscal,uk','U.K. fiscal credibility can alter sterling pressure.',['regime_dependent']]], [dep('gbp_usd','uk-us-policy', 'must_have', ['boe_official','ons_official','federal_reserve_official','bls_official'], ['policy','macro'], 'partially_covered')]),
  fx('usd_jpy','USD/JPY','fx_safe_haven','Fed/U.S.','BoJ/Japan',['intervention_risk','policy,intervention','Japan MoF intervention risk can dominate normal rate-differential interpretation.',['regime_dependent','requires_price_confirmation']], [['safe_haven_demand','risk,haven','JPY haven pressure can conflict with U.S. rate support.',['pair_quote_positive','regime_dependent']]], [dep('usd_jpy','us-japan-policy', 'must_have', ['federal_reserve_official','boj_official','japan_mof_official','us_treasury_official'], ['policy','intervention','rates'], 'partially_covered')]),
  fx('usd_chf','USD/CHF','fx_safe_haven','Fed/U.S.','SNB/Swiss',['safe_haven_demand','risk,haven','CHF safe-haven pressure can conflict with USD risk-off demand.',['pair_quote_positive','regime_dependent']], [['intervention_risk','policy,intervention','Swiss policy and intervention watch can alter CHF pressure.',['regime_dependent']]], [dep('usd_chf','us-swiss-policy', 'must_have', ['federal_reserve_official','fred_macro','marketaux_news'], ['policy','safe_haven'], 'pending_provider_activation')]),
  fx('aud_usd','AUD/USD','fx_commodity','RBA/Australia','Fed/U.S.',['china_demand','growth,china,commodities','China and global demand are primary for AUD commodity beta.',['direct_positive','relative','regime_dependent']], [['commodity_terms_of_trade','commodities,terms_of_trade','Commodity terms of trade modify AUD pressure.',['direct_positive','regime_dependent']]], [dep('aud_usd','aud-global-demand', 'must_have', ['world_bank_official','oecd_official','federal_reserve_official'], ['growth','commodities'], 'pending_provider_activation')]),
  fx('nzd_usd','NZD/USD','fx_commodity','RBNZ/New Zealand','Fed/U.S.',['china_demand','growth,china,commodities','China and global demand are primary for NZD high-beta commodity exposure.',['direct_positive','relative','regime_dependent']], [['commodity_terms_of_trade','commodities,terms_of_trade','Terms of trade and global demand modify NZD pressure.',['direct_positive','regime_dependent']]], [dep('nzd_usd','nzd-global-demand', 'must_have', ['world_bank_official','oecd_official','federal_reserve_official'], ['growth','commodities'], 'pending_provider_activation')]),
  fx('usd_cad','USD/CAD','fx_commodity','Fed/U.S.','BoC/Canada',['oil_energy','energy,oil','Oil and energy terms affect CAD pressure and therefore USD/CAD quote-side interpretation.',['pair_quote_positive','regime_dependent']], [['commodity_terms_of_trade','commodities,terms_of_trade','Canadian terms of trade modify CAD pressure.',['regime_dependent']]], [dep('usd_cad','canada-us-energy-policy', 'must_have', ['federal_reserve_official','fred_macro','oecd_official'], ['policy','oil_energy'], 'pending_provider_activation')])
);

const equity = (asset: MarketAssetCausalityAsset, name: string, family: MarketAssetFamily, euro = false): MarketAssetCausalityDescriptor => descriptor(asset, name, family,
  [['real_yields','rates,real_yields','Real yields and discount-rate pressure affect index valuation sensitivity.',['inverse','requires_direction_resolver','requires_price_confirmation']], ['earnings_macro','earnings,macro','Earnings and macro growth determine whether rates pressure is absorbed.',['direct_positive','requires_surprise_normalization']], ['equity_breadth','breadth,equity','Breadth confirms whether index moves are narrow or broad.',['direct_positive','requires_price_confirmation']], ['volatility_surface','volatility,risk','Volatility term structure frames stress and hedging demand.',['inverse','regime_dependent']]],
  [['liquidity_conditions','liquidity,financial_conditions','Liquidity and financial conditions set beta appetite.',['direct_positive','regime_dependent']], ['credit_stress','credit,risk','Credit stress can undermine equity index resilience.',['inverse','regime_dependent']]],
  euro ? [['central_bank_policy','policy,ecb','ECB policy and euro funding conditions are key context for DE30.',['relative','regime_dependent']], ['industrial_cycle','industry,germany','German industrial cycle and export demand drive domestic cyclicality.',['direct_positive','requires_surprise_normalization']], ['energy_commodities','energy,commodities','Energy shocks can pressure German margins and activity.',['inverse','regime_dependent']]] : [['financial_conditions','financial_conditions,liquidity','Financial conditions contextualize equity risk appetite.',['direct_positive','regime_dependent']]],
  euro ? [dep(asset,'euro-equity-stack', 'must_have', ['index_futures_shell','ecb_official','destatis_official','ifo_shell','zew_shell','credit_stress_source'], ['price','ecb','german_industrial','energy','credit'], 'pending_provider_activation')] : [dep(asset,'us-equity-stack', 'must_have', ['index_futures_shell','federal_reserve_official','earnings_filings_shell','public_equity_breadth_sources','volatility_metric_source','liquidity_condition_source'], ['rates','earnings','breadth','volatility','liquidity'], 'pending_provider_activation')],
  [req(asset, false, false, false, true, true)], standardCoverage, PHASE_GAPS, ['R2','R4','R5','R6','R7','R8','R9'], [mod(asset,'volatility_shock','Volatility shocks can overwhelm normal earnings interpretation.'), mod(asset,'liquidity_stress','Liquidity stress can reduce confidence in positive breadth.')], stdTriggers(asset).concat(trig(asset,'breadth_index_divergence','Index level moves conflict with breadth evidence.'), trig(asset,'volatility_equity_divergence','Equity reaction conflicts with volatility surface evidence.')), 'very_high','event_window_required','high');

DESCRIPTORS.push(equity('nasdaq_100','Nasdaq 100','equity_index_us'), equity('sp500','S&P 500','equity_index_us'), equity('de30','DE30','equity_index_europe', true));
DESCRIPTORS.push(
  descriptor('dxy','DXY','dollar_index',
    [['central_bank_policy','fed,policy','Fed policy path is primary but must be compared with non-U.S. policy paths.',['direct_positive','relative','requires_direction_resolver']], ['growth_surprise','us_macro,growth','U.S. macro surprises require normalization against forecasts and revisions.',['requires_surprise_normalization','direct_positive']], ['yield_differentials','rates,yields','U.S. yield advantage versus basket currencies is core DXY causality.',['relative','requires_direction_resolver']], ['dollar_liquidity','liquidity,dollar','USD liquidity and funding stress can support broad dollar pressure.',['direct_positive','regime_dependent']]],
    [['risk_sentiment','risk,global','Global risk regime can lift the broad dollar even when U.S. data is weak.',['regime_dependent']], ['positioning_cot','positioning,cot','Crowded USD positioning can alter follow-through.',['regime_dependent','requires_price_confirmation']]],
    [['market_price_structure','price,basket','Basket reaction across major FX legs is required context.',['requires_price_confirmation']]],
    [dep('dxy','dollar-basket', 'must_have', ['federal_reserve_official','us_treasury_official','bls_official','ecb_official','boj_official','boe_official','liquidity_condition_source','index_futures_shell'], ['fed_policy','us_macro','yield_differentials','liquidity','risk'], 'pending_provider_activation')], [req('dxy', false, false, true, true, true)], standardCoverage, PHASE_GAPS, ['R2','R3','R4','R5','R6','R7','R8','R9'], [mod('dxy','risk_off','Risk-off can support USD even with adverse domestic macro.'), mod('dxy','policy_surprise','Fed repricing can dominate short event windows.')], stdTriggers('dxy').concat(trig('dxy','macro_price_divergence','U.S. macro surprise conflicts with dollar basket reaction.')), 'high','high','very_high'),
  descriptor('vix','VIX','volatility_index',
    [['volatility_surface','volatility,term_structure','Volatility regime and term structure are primary VIX drivers.',['direct_positive','requires_price_confirmation']], ['risk_sentiment','risk,equity','Risk-off and event uncertainty shape volatility demand.',['direct_positive','regime_dependent']], ['credit_stress','credit,risk','Credit stress can sustain elevated volatility.',['direct_positive','regime_dependent']], ['equity_breadth','breadth,equity','Equity stress breadth confirms whether VIX pressure is broad.',['inverse','requires_price_confirmation']]],
    [['liquidity_conditions','liquidity,financial_conditions','Liquidity stress can amplify volatility repricing.',['inverse','regime_dependent']], ['event_reaction','event,price','Event-window reaction determines whether vol pressure persists.',['requires_price_confirmation']]],
    [['market_price_structure','price,equity','Equity index drawdown and recovery behavior provide confirmation.',['requires_price_confirmation']]],
    [dep('vix','vol-risk-stack', 'must_have', ['volatility_metric_source','credit_stress_source','liquidity_condition_source','public_equity_breadth_sources','index_futures_shell'], ['volatility','equity_stress','credit','risk_off'], 'pending_provider_activation')], [req('vix', false, false, false, false, true)], standardCoverage, PHASE_GAPS, ['R2','R5','R6','R7','R8','R9'], [mod('vix','event_window','Scheduled event windows can sustain implied volatility.'), mod('vix','credit_stress','Credit stress can keep volatility elevated after equity bounce.')], stdTriggers('vix').concat(trig('vix','volatility_equity_divergence','Equities improve while volatility surface remains stressed.'), trig('vix','credit_risk_divergence','Credit stress conflicts with calm equity price action.')), 'very_high','event_window_required','very_high')
);

function sortedDescriptors(): MarketAssetCausalityDescriptor[] { return [...DESCRIPTORS].sort((a, b) => MARKET_ASSET_CAUSALITY_ASSETS.indexOf(a.asset) - MARKET_ASSET_CAUSALITY_ASSETS.indexOf(b.asset)); }
export function listMarketAssetCausalityDescriptors(): MarketAssetCausalityDescriptor[] { return sortedDescriptors(); }
export function getMarketAssetCausalityDescriptor(asset: MarketAssetCausalityAsset): MarketAssetCausalityDescriptor { const found = DESCRIPTORS.find((x) => x.asset === asset); if (!found) throw new Error(`unknown_asset_causality:${asset}`); return found; }
export function listMarketAssetCausalityGaps(): MarketAssetCausalityGap[] { return PHASE_GAPS; }
export function getMarketAssetCausalityCoverageReport(generatedAt = new Date().toISOString()): MarketAssetCausalityCoverageReport { const descriptors = sortedDescriptors(); const counts = new Map<MarketAssetCausalityAsset, number>(); for (const d of descriptors) counts.set(d.asset, (counts.get(d.asset) ?? 0) + 1); const representedAssets = MARKET_ASSET_CAUSALITY_ASSETS.filter((a) => (counts.get(a) ?? 0) > 0); return { generatedAt, launchAssetCount: MARKET_ASSET_CAUSALITY_ASSETS.length, representedAssets, missingAssets: MARKET_ASSET_CAUSALITY_ASSETS.filter((a) => !counts.has(a)), duplicateAssets: MARKET_ASSET_CAUSALITY_ASSETS.filter((a) => (counts.get(a) ?? 0) > 1), gapCount: PHASE_GAPS.length, gaps: PHASE_GAPS, complete: false, notes: ['C6-R1 typed causality foundation exists.', 'R2-R9 engines remain pending.', 'No live provider, UI, commercial, payment, or notification activation changed.'] }; }
export function buildMarketAssetCausalityMatrixSnapshot(asOfIso = new Date().toISOString()): MarketAssetCausalityMatrixSnapshot { return { generatedAt: asOfIso, descriptors: sortedDescriptors(), coverageReport: getMarketAssetCausalityCoverageReport(asOfIso) }; }
export function assertMarketAssetCausalityMatrixComplete(): MarketAssetCausalityMatrixSnapshot { const snapshot = buildMarketAssetCausalityMatrixSnapshot('2026-06-03T00:00:00.000Z'); const validation = validateMarketAssetCausalityMatrixSnapshot(snapshot); if ('errors' in validation) throw new Error(`market_asset_causality_matrix_invalid:${validation.errors.join(';')}`); return snapshot; }
export function listDirectionResolutionRequirements(asset?: MarketAssetCausalityAsset): MarketAssetDirectionResolutionRequirement[] { return (asset ? [getMarketAssetCausalityDescriptor(asset)] : sortedDescriptors()).flatMap((d) => d.directionResolutionRequirements); }
export function listProviderDependenciesForAsset(asset: MarketAssetCausalityAsset): MarketAssetProviderDependency[] { return getMarketAssetCausalityDescriptor(asset).providerDependencies; }
export function listContradictionTriggersForAsset(asset: MarketAssetCausalityAsset): MarketAssetContradictionTrigger[] { return getMarketAssetCausalityDescriptor(asset).contradictionTriggers; }
export function listRegimeModifiersForAsset(asset: MarketAssetCausalityAsset): MarketAssetRegimeModifier[] { return getMarketAssetCausalityDescriptor(asset).regimeModifiers; }
