import type { MarketEvidenceProviderAdapter } from './normalization-contracts';
import type { NormalizedMarketEvidencePayload, ProviderSourceRequest, ProviderSourceResponse } from '@elceo/types';
import type { NormalizedMarketEvidencePayloadRepository, ProviderSourceRequestRepository, ProviderSourceResponseRepository } from '../persistence/market-evidence-ingestion-repository';
export type IngestionPersistenceReport={requestId:string;providerId:string;capability:string;responseStatus:ProviderSourceResponse['status'];payloadCount:number;persistedPayloadIds:string[];errors:string[]};
export class IngestionPersistenceService{constructor(private readonly req:ProviderSourceRequestRepository,private readonly res:ProviderSourceResponseRepository,private readonly pay:NormalizedMarketEvidencePayloadRepository){}
async persistProviderSourceRequest(request:ProviderSourceRequest){await this.req.saveRequest({...request,createdAt:new Date().toISOString()});}
async persistProviderSourceResponse(response:ProviderSourceResponse){await this.res.saveResponse({...response,createdAt:new Date().toISOString()});}
async persistNormalizedMarketEvidencePayload(payload:NormalizedMarketEvidencePayload){await this.pay.savePayload({...payload,createdAt:new Date().toISOString()});}
async persistIngestionResult(request:ProviderSourceRequest,response:ProviderSourceResponse,payloads:NormalizedMarketEvidencePayload[]):Promise<IngestionPersistenceReport>{const errors:string[]=[];const ids:string[]=[]; try{await this.persistProviderSourceRequest(request);}catch(e){errors.push(String(e));} try{await this.persistProviderSourceResponse(response);}catch(e){errors.push(String(e));} for(const p of payloads){try{await this.persistNormalizedMarketEvidencePayload(p); ids.push(p.payloadId);}catch(e){errors.push(String(e));}} return {requestId:request.requestId,providerId:request.providerId,capability:request.capability,responseStatus:response.status,payloadCount:payloads.length,persistedPayloadIds:ids,errors};}
async persistAdapterFetchAndNormalize(adapter:MarketEvidenceProviderAdapter,request:ProviderSourceRequest){const response=await adapter.fetch(request); const payloads=await adapter.normalize(response); return this.persistIngestionResult(request,response,payloads);}}
