import type { ProviderCapabilityKind, ProviderSourceRequest, ProviderSourceResponse } from '@elceo/types';
import { getProviderDescriptor } from './provider-capability-registry';
import type { MarketEvidenceProviderAdapter } from './normalization-contracts';

export type ProviderSourceId = string;
export type ProviderCapabilityId = ProviderCapabilityKind;
export type ProviderAdapterId = `${string}_adapter`;
export type ProviderActivationMode = 'disabled'|'fixture_only'|'dry_run'|'replay'|'staging_live_allowed'|'production_live_allowed';
export type ProviderCallMode = 'blocked_live'|'fixture_response'|'dry_run_no_external_call'|'replay_captured_payload'|'live_staging_call'|'live_production_call';
export type ProviderFallbackMode = 'none'|'explicit_fixture_fallback'|'explicit_replay_fallback'|'stale_if_error';
export type CircuitState = 'closed'|'open'|'half_open';

export type ProviderApiGatePolicy = {
  activationMode?: ProviderActivationMode; explicitProductionLiveAllow?: boolean; explicitStagingLiveAllow?: boolean;
  fallbackMode?: ProviderFallbackMode; maxWindowDays?: number; quotaLimit?: number; quotaUsed?: number; rateLimitRemaining?: number; costBudgetRemaining?: number;
  cacheHitPayload?: ProviderRuntimeResponse; stalePayload?: ProviderRuntimeResponse; circuitState?: CircuitState; allowUnknownFields?: boolean;
};
export type ProviderRuntimeRequest = { requestId:string; sourceId:ProviderSourceId; capabilityId:ProviderCapabilityId; asset?:string|null; region?:string|null; startAt?:string|null; endAt?:string|null; paginationCursor?:string|null; idempotencyKey?:string|null; provenance?:{ actor:string; purpose:string }; activationMode?:ProviderActivationMode; metadata?:Record<string,unknown>; policy?:ProviderApiGatePolicy; replayPayload?:ProviderRuntimeResponse; };
export type ProviderCapabilityTranslation = { sourceId:ProviderSourceId; capabilityId:ProviderCapabilityId; adapterId:ProviderAdapterId; descriptorOnly:boolean; secretRequired:boolean; };
export type ProviderRuntimeResolverDecision = { allowed:boolean; reason:string; sourceId:ProviderSourceId; capabilityId:ProviderCapabilityId; adapterId:ProviderAdapterId|null; activationMode:ProviderActivationMode; providerCallMode:ProviderCallMode; fallbackMode:ProviderFallbackMode; quotaStatus:'ok'|'exceeded'; rateLimitStatus:'ok'|'exceeded'; costStatus:'ok'|'exceeded'; cacheStatus:'hit'|'miss'; circuitStatus:CircuitState; observabilityLabels:Record<string,string>; validationSchema:'provider_runtime_response_v1'; provenanceRequired:true; secretRequired:boolean; };
export type ProviderRuntimeResponse = { requestId:string; responseId:string; sourceId:ProviderSourceId; capabilityId:ProviderCapabilityId; adapterId:ProviderAdapterId; receivedAt:string; payload:unknown; payloadSchemaStatus:'valid'|'provider_error'|'rate_limited'; payloadSizeBytes:number; recordCount:number; duplicateProviderIds?:string[]; revision?:string|null; provenance:{ requestId:string; sourceId:ProviderSourceId }; error?:{ category:string; message:string }|null; rateLimit?:{ remaining:number; resetAt:string|null }|null; };
export type ProviderApiGateSnapshot = { sourceId:ProviderSourceId; capabilityId:ProviderCapabilityId; adapterId:ProviderAdapterId|null; activationMode:ProviderActivationMode; providerCallMode:ProviderCallMode; decisionReason:string; quotaStatus:string; rateLimitStatus:string; costStatus:string; cacheStatus:string; fallbackStatus:ProviderFallbackMode; circuitStatus:CircuitState; requestId:string; responseOrProvenanceId:string|null; redactedErrorCategory:string|null; };

const ACTIVATION = new Set<ProviderActivationMode>(['disabled','fixture_only','dry_run','replay','staging_live_allowed','production_live_allowed']);
const SECRET_KEYS = /api[-_]?key|authorization|bearer|client[-_]?secret|webhook[-_]?secret|provider[-_]?credential|database[-_]?url|databaseUrl|internal[-_]?token|secret/i;
const SECRET_VAL = /(sk_live_|sk_test_|Bearer\s+|api[_-]?key=|postgres:\/\/|-----BEGIN|tok_[a-z0-9])/i;
const DESCRIPTOR_ONLY = new Set(['tradingview_chart_metadata']);
const FIXTURE_ONLY = new Set(['cftc_cot','public_statistics_agencies','calculated_internal_macro_calendar']);

export function redactProviderSecrets<T>(value:T):T { return JSON.parse(JSON.stringify(value, (k, v) => SECRET_KEYS.test(k) ? '[REDACTED]' : (typeof v === 'string' && SECRET_VAL.test(v) ? '[REDACTED]' : v))) as T; }
export function translateProviderCapability(sourceId:string, capabilityId:string): ProviderCapabilityTranslation {
  const d=getProviderDescriptor(sourceId); if(!d) throw new Error('unknown_provider_source_id');
  if(!d.supportedCapabilities.includes(capabilityId as ProviderCapabilityKind)) throw new Error('source_capability_mismatch');
  return { sourceId, capabilityId: capabilityId as ProviderCapabilityKind, adapterId: `${sourceId}_${capabilityId}_adapter` as ProviderAdapterId, descriptorOnly: DESCRIPTOR_ONLY.has(sourceId), secretRequired: d.accessRequirement.includes('api_key') || d.accessRequirement.includes('paid') };
}
function reject(req:ProviderRuntimeRequest, reason:string, mode:ProviderActivationMode, t?:Partial<ProviderCapabilityTranslation>):ProviderRuntimeResolverDecision { return { allowed:false, reason, sourceId:req.sourceId, capabilityId:req.capabilityId, adapterId:t?.adapterId??null, activationMode:mode, providerCallMode:'blocked_live', fallbackMode:req.policy?.fallbackMode??'none', quotaStatus:'ok', rateLimitStatus:'ok', costStatus:'ok', cacheStatus:'miss', circuitStatus:req.policy?.circuitState??'closed', observabilityLabels:{ reason }, validationSchema:'provider_runtime_response_v1', provenanceRequired:true, secretRequired:t?.secretRequired??false }; }
export function resolveProviderRuntimeRequest(req:ProviderRuntimeRequest):ProviderRuntimeResolverDecision {
  const mode=req.activationMode ?? req.policy?.activationMode ?? 'dry_run';
  if(!ACTIVATION.has(mode)) return reject(req,'unknown_activation_mode', 'disabled');
  let t:ProviderCapabilityTranslation; try{ t=translateProviderCapability(req.sourceId, req.capabilityId); }catch(e){ return reject(req, e instanceof Error?e.message:'translation_failed', mode); }
  if(!req.provenance?.actor || !req.provenance.purpose) return reject(req,'missing_provenance',mode,t);
  if(SECRET_KEYS.test(JSON.stringify(req.metadata??{})) || SECRET_VAL.test(JSON.stringify(req.metadata??{}))) return reject(req,'secret_like_request_metadata',mode,t);
  if(['market_price_history','end_of_day_prices','intraday_quotes','cot_report'].includes(req.capabilityId) && !req.asset) return reject(req,'missing_asset',mode,t);
  if(req.asset==='unsupported_asset') return reject(req,'unsupported_asset',mode,t);
  if(req.startAt&&req.endAt){ const days=(Date.parse(req.endAt)-Date.parse(req.startAt))/86400000; if(!Number.isFinite(days)||days<0) return reject(req,'invalid_time_range',mode,t); if(days>(req.policy?.maxWindowDays??370)) return reject(req,'oversized_window',mode,t); }
  if(req.paginationCursor && !/^[A-Za-z0-9._:-]{1,128}$/.test(req.paginationCursor)) return reject(req,'invalid_pagination_cursor',mode,t);
  if((mode==='replay'||req.replayPayload) && !req.idempotencyKey) return reject(req,'missing_idempotency_key',mode,t);
  if((req.policy?.quotaUsed??0) >= (req.policy?.quotaLimit??Number.POSITIVE_INFINITY)) return {...reject(req,'quota_exceeded',mode,t), quotaStatus:'exceeded'};
  if((req.policy?.rateLimitRemaining??1) <= 0) return {...reject(req,'rate_limit_exceeded',mode,t), rateLimitStatus:'exceeded'};
  if((req.policy?.costBudgetRemaining??1) <= 0) return {...reject(req,'cost_budget_exceeded',mode,t), costStatus:'exceeded'};
  if(req.policy?.circuitState==='open') return reject(req,'circuit_open',mode,t);
  if(t.descriptorOnly && (mode==='staging_live_allowed'||mode==='production_live_allowed')) return reject(req,'descriptor_only_provider_cannot_execute',mode,t);
  if(FIXTURE_ONLY.has(req.sourceId) && (mode==='staging_live_allowed'||mode==='production_live_allowed')) return reject(req,'fixture_only_provider_cannot_execute_live',mode,t);
  if(mode==='production_live_allowed' && !req.policy?.explicitProductionLiveAllow) return reject(req,'production_live_requires_explicit_allow',mode,t);
  if(mode==='staging_live_allowed' && !req.policy?.explicitStagingLiveAllow) return reject(req,'staging_live_requires_explicit_allow',mode,t);
  const providerCallMode:ProviderCallMode = mode==='fixture_only'?'fixture_response':mode==='dry_run'?'dry_run_no_external_call':mode==='replay'?'replay_captured_payload':mode==='staging_live_allowed'?'live_staging_call':mode==='production_live_allowed'?'live_production_call':'blocked_live';
  return { allowed: mode!=='disabled', reason: mode==='disabled'?'disabled':'allowed', sourceId:req.sourceId, capabilityId:req.capabilityId, adapterId:t.adapterId, activationMode:mode, providerCallMode, fallbackMode:req.policy?.fallbackMode??'none', quotaStatus:'ok', rateLimitStatus:'ok', costStatus:'ok', cacheStatus:req.policy?.cacheHitPayload?'hit':'miss', circuitStatus:req.policy?.circuitState??'closed', observabilityLabels:{sourceId:req.sourceId,capabilityId:req.capabilityId,providerCallMode}, validationSchema:'provider_runtime_response_v1', provenanceRequired:true, secretRequired:t.secretRequired };
}
export function assertProviderApiGateRequestAllowed(req:ProviderRuntimeRequest):ProviderRuntimeResolverDecision { const d=resolveProviderRuntimeRequest(req); if(!d.allowed) throw new Error(d.reason); return d; }
export function validateProviderRuntimeResponse(r:ProviderRuntimeResponse, decision:ProviderRuntimeResolverDecision):ProviderRuntimeResponse { if(r.sourceId!==decision.sourceId||r.capabilityId!==decision.capabilityId||r.adapterId!==decision.adapterId) throw new Error('response_provenance_mismatch'); if(!r.requestId||!r.responseId||!r.receivedAt) throw new Error('response_identity_missing'); if(r.payloadSizeBytes>1024*1024) throw new Error('oversized_response'); if(r.payloadSchemaStatus==='valid' && r.error) throw new Error('valid_response_with_error'); return redactProviderSecrets(r); }
export async function executeProviderApiGateRequest(req:ProviderRuntimeRequest, adapter?:MarketEvidenceProviderAdapter):Promise<{decision:ProviderRuntimeResolverDecision; response:ProviderRuntimeResponse|null; snapshot:ProviderApiGateSnapshot}> { const decision=resolveProviderRuntimeRequest(req); let response:ProviderRuntimeResponse|null=null; if(!decision.allowed){ response=null; } else if(req.policy?.cacheHitPayload){ response=req.policy.cacheHitPayload; } else if(decision.providerCallMode==='replay_captured_payload'){ response=req.replayPayload??null; } else if(decision.providerCallMode==='dry_run_no_external_call'){ response={requestId:req.requestId,responseId:`dry-${req.requestId}`,sourceId:req.sourceId,capabilityId:req.capabilityId,adapterId:decision.adapterId!,receivedAt:new Date().toISOString(),payload:{dryRun:true},payloadSchemaStatus:'valid',payloadSizeBytes:15,recordCount:0,provenance:{requestId:req.requestId,sourceId:req.sourceId},error:null,rateLimit:null}; } else if(decision.providerCallMode==='fixture_response' && adapter){ const sourceReq:ProviderSourceRequest={requestId:req.requestId,providerId:req.sourceId,capability:req.capabilityId,asset:req.asset??null,region:req.region??null,evidenceTypeId:req.capabilityId,requestedAt:new Date().toISOString(),paramsJson:'{}'}; const res:ProviderSourceResponse=await adapter.fetch(sourceReq); response={requestId:req.requestId,responseId:`fixture-${req.requestId}`,sourceId:req.sourceId,capabilityId:req.capabilityId,adapterId:decision.adapterId!,receivedAt:res.fetchedAt,payload:res.rawPayloadJson?JSON.parse(res.rawPayloadJson):null,payloadSchemaStatus:res.status==='success'?'valid':'provider_error',payloadSizeBytes:(res.rawPayloadJson??'').length,recordCount:0,provenance:{requestId:req.requestId,sourceId:req.sourceId},error:res.errorCode?{category:res.errorCode,message:redactProviderSecrets(res.errorMessage??'')}:null,rateLimit:null}; } if(response) response=validateProviderRuntimeResponse(response,decision); return {decision,response,snapshot:buildProviderApiGateSnapshot(decision,req.requestId,response)}; }
export function buildProviderApiGateSnapshot(d:ProviderRuntimeResolverDecision, requestId:string, response:ProviderRuntimeResponse|null, error?:unknown):ProviderApiGateSnapshot { return redactProviderSecrets({ sourceId:d.sourceId, capabilityId:d.capabilityId, adapterId:d.adapterId, activationMode:d.activationMode, providerCallMode:d.providerCallMode, decisionReason:d.reason, quotaStatus:d.quotaStatus, rateLimitStatus:d.rateLimitStatus, costStatus:d.costStatus, cacheStatus:d.cacheStatus, fallbackStatus:d.fallbackMode, circuitStatus:d.circuitStatus, requestId, responseOrProvenanceId:response?.responseId??response?.provenance.requestId??null, redactedErrorCategory:error instanceof Error?error.message:null }); }
