import type { MarketReasoningModuleId, MarketReasoningModuleReadiness, MarketReasoningReadinessReport } from '@elceo/types';
import { MARKET_REASONING_MODULE_IDS } from '@elceo/types';
import { validateMarketReasoningReadinessReport } from '@elceo/schemas';
const note=(module:string)=>`${module} deterministic foundation exists; live provider activation, empirical validation, and production calibration are tracked separately.`;
const BASE: Record<MarketReasoningModuleId, Omit<MarketReasoningModuleReadiness,'moduleId'>> = {
  asset_causality:{contractShapeStatus:'valid',deterministicFoundationStatus:'implemented',liveProviderIntegrationStatus:'not_applicable',empiricalValidationStatus:'pending',productionCalibrationStatus:'not_applicable',notes:['Asset-causality descriptor contract validates one descriptor per reasoning asset.','DXY and VIX are reasoning diagnostics, not launch-tradable instruments.']},
  asset_direction:{contractShapeStatus:'valid',deterministicFoundationStatus:'implemented',liveProviderIntegrationStatus:'blocked',empiricalValidationStatus:'pending',productionCalibrationStatus:'pending',notes:[note('Asset-direction')]},
  fx_relative_strength:{contractShapeStatus:'valid',deterministicFoundationStatus:'implemented',liveProviderIntegrationStatus:'blocked',empiricalValidationStatus:'pending',productionCalibrationStatus:'pending',notes:[note('FX relative-strength')]},
  macro_surprise:{contractShapeStatus:'valid',deterministicFoundationStatus:'implemented',liveProviderIntegrationStatus:'blocked',empiricalValidationStatus:'pending',productionCalibrationStatus:'pending',notes:[note('Macro-surprise')]},
  contradiction_matrix:{contractShapeStatus:'valid',deterministicFoundationStatus:'implemented',liveProviderIntegrationStatus:'blocked',empiricalValidationStatus:'pending',productionCalibrationStatus:'pending',notes:[note('Contradiction-matrix')]},
  confidence_calibration:{contractShapeStatus:'valid',deterministicFoundationStatus:'implemented',liveProviderIntegrationStatus:'blocked',empiricalValidationStatus:'pending',productionCalibrationStatus:'pending',notes:['Confidence calibration deterministic arithmetic exists; empirical calibration remains pending.']},
  price_reaction:{contractShapeStatus:'valid',deterministicFoundationStatus:'implemented',liveProviderIntegrationStatus:'blocked',empiricalValidationStatus:'pending',productionCalibrationStatus:'pending',notes:[note('Price-reaction')]},
  provider_reliability:{contractShapeStatus:'valid',deterministicFoundationStatus:'implemented',liveProviderIntegrationStatus:'blocked',empiricalValidationStatus:'pending',productionCalibrationStatus:'pending',notes:['Provider reliability scoring foundation exists; live provider activation remains blocked.']},
  golden_scenarios:{contractShapeStatus:'valid',deterministicFoundationStatus:'implemented',liveProviderIntegrationStatus:'blocked',empiricalValidationStatus:'pending',productionCalibrationStatus:'pending',notes:['Fixture-driven golden-scenario acceptance foundation exists; not live provider activation or empirical backtesting.']}
};
export function getMarketReasoningModuleReadiness(moduleId:MarketReasoningModuleId):MarketReasoningModuleReadiness{return {moduleId,...BASE[moduleId],notes:[...BASE[moduleId].notes]};}
export function getMarketReasoningReadinessReport(asOfIso=new Date().toISOString()):MarketReasoningReadinessReport{return {generatedAt:asOfIso,modules:MARKET_REASONING_MODULE_IDS.map(getMarketReasoningModuleReadiness),moduleCount:MARKET_REASONING_MODULE_IDS.length,notes:['RC-A readiness separates contract shape, deterministic foundation, live integration, empirical validation, and production calibration.']};}
export function assertMarketReasoningReadinessValid():MarketReasoningReadinessReport{const r=getMarketReasoningReadinessReport('2026-06-03T00:00:00.000Z'); const v=validateMarketReasoningReadinessReport(r); if(v.ok===false) throw new Error(`market_reasoning_readiness_invalid:${v.errors.join('|')}`); return r;}
