import type { MarketEvidenceClass, SeoContentArchitectureSnapshot, SeoContentCluster, SeoInternalLinkRule, SeoPageDefinition, SeoPageKind, TradingAssetCoverage } from '@elceo/types';
import { SEO_KEYWORDS } from './keyword-taxonomy';
const mk=(id:string,slug:string,kind:SeoPageKind,assets:TradingAssetCoverage[]=[],ev:string[]=[]):SeoPageDefinition=>({pageId:id,slug,pageKind:kind,titleTemplate:id,metaDescriptionTemplate:id,h1Template:id,canonicalPath:`/${slug}`,freshnessClass:'frequently_updated',targetKeywords:[],relatedEvidenceTypes:ev,relatedAssets:assets,internalLinkTargets:[],structuredDataKind:'article',isLaunchScope:true});
const PAGES: SeoPageDefinition[] = [
mk('asset-xau-usd','assets/xau-usd','asset_page',['xau_usd']),mk('asset-eur-usd','assets/eur-usd','asset_page',['eur_usd']),mk('asset-gbp-usd','assets/gbp-usd','asset_page',['gbp_usd']),mk('asset-usd-jpy','assets/usd-jpy','asset_page',['usd_jpy']),mk('asset-usd-chf','assets/usd-chf','asset_page',['usd_chf']),mk('asset-aud-usd','assets/aud-usd','asset_page',['aud_usd']),mk('asset-nzd-usd','assets/nzd-usd','asset_page',['nzd_usd']),mk('asset-usd-cad','assets/usd-cad','asset_page',['usd_cad']),mk('asset-btc-usd','assets/btc-usd','asset_page',['btc_usd']),mk('asset-nasdaq-100','assets/nasdaq-100','asset_page',['nasdaq_100']),mk('asset-sp500','assets/sp500','asset_page',['sp500']),mk('asset-de30','assets/de30','asset_page',['de30']),
mk('macro-nfp','macro/nfp','macro_event_page',['xau_usd'],['macro_calendar']),mk('macro-cpi','macro/cpi','macro_event_page',['xau_usd'],['inflation']),mk('macro-fomc','macro/fomc','macro_event_page',['xau_usd'],['central_bank_policy']),mk('inst-ecb','institutions/ecb','institution_page',['eur_usd']),mk('inst-boe','institutions/boe','institution_page',['gbp_usd']),mk('inst-boj','institutions/boj','institution_page',['usd_jpy']),
mk('ev-cot','evidence/cot-report','evidence_class_page',['eur_usd'],['cot_positioning']),mk('ev-real-yields','evidence/real-yields','evidence_class_page',['xau_usd'],['real_yields']),mk('ev-treasury-auctions','evidence/treasury-auctions','evidence_class_page',['usd_jpy'],['bond_auctions']),mk('ev-cb-balance-sheet','evidence/central-bank-balance-sheets','evidence_class_page',['nasdaq_100'],['central_bank_balance_sheet']),mk('ev-credit-stress','evidence/credit-stress','evidence_class_page',['nasdaq_100'],['credit_stress']),mk('ev-volatility','evidence/volatility','evidence_class_page',['sp500'],['volatility_surface']),mk('ev-macro-surprise','evidence/macro-surprise-index','evidence_class_page',['eur_usd'],['macro_surprise_history']),
mk('edu-journal','education/trading-journal','trading_education_page'),mk('edu-risk-management','education/risk-management','trading_education_page'),mk('explainer-confidence','explainers/confidence-score','market_explainer_page'),mk('explainer-cognition','explainers/market-cognition','market_explainer_page')
];
const LINKS: SeoInternalLinkRule[]=[{ruleId:'asset-macro',sourcePageKind:'asset_page',targetPageKind:'macro_event_page',anchorTemplate:'How {event} affects this asset',rationale:'Catalyst linkage'},{ruleId:'macro-institution',sourcePageKind:'macro_event_page',targetPageKind:'institution_page',anchorTemplate:'Institution policy context',rationale:'Authority linkage'}];
export function getSeoContentArchitectureSnapshot(asOfIso: string): SeoContentArchitectureSnapshot { return { generatedAt: asOfIso, keywords: SEO_KEYWORDS, pages: PAGES, internalLinkRules: LINKS }; }
export function listSeoPagesByKind(pageKind: SeoPageKind){ return PAGES.filter((x)=>x.pageKind===pageKind); }
export function listKeywordsByCluster(cluster: SeoContentCluster){ return SEO_KEYWORDS.filter((x)=>x.cluster===cluster); }
export function listSeoPagesForAsset(asset: TradingAssetCoverage){ return PAGES.filter((x)=>x.relatedAssets.includes(asset)); }
export function listSeoPagesForEvidenceClass(evidenceClass: MarketEvidenceClass){ return PAGES.filter((x)=>x.relatedEvidenceTypes.includes(evidenceClass)|| (evidenceClass==='macro_calendar'&&x.pageKind==='macro_event_page')); }
export { PAGES as SEO_PAGES };
