import type { EmailNotificationProviderReadiness, UserNotificationCoverageReport, UserNotificationDeliveryDraft, UserNotificationDeliveryLog, UserNotificationEventTrigger, UserNotificationOutboxItem, UserNotificationPreferenceSnapshot, UserNotificationPreferenceUpdateRequest, UserNotificationProviderDescriptor, UserNotificationRateLimitDecision, WhatsAppNotificationProviderReadiness } from '@elceo/types';

const TOPICS=['macro_summary','evidence_score_change','market_reasoning_update','risk_contradiction_alert','scheduled_digest'] as const;
const CHANNELS=['email','whatsapp'] as const;

export const getUserNotificationDefaultPreferences=(userId:string):UserNotificationPreferenceSnapshot=>({userId,globalEnabled:false,unsubscribed:false,channels:[{channel:'email',enabled:false,status:'inactive',contactVerified:false},{channel:'whatsapp',enabled:false,status:'inactive',contactVerified:false}],topics:TOPICS.map((t)=>({topic:t,enabled:t!=='scheduled_digest',evidenceScoreThreshold:t==='evidence_score_change'?5:null})),assetPreferences:[],digestFrequency:'weekly',quietHours:{mode:'suppress',timezone:'UTC',startLocalTime:'22:00',endLocalTime:'07:00'},updatedAt:new Date().toISOString()});
export const buildUserNotificationPreferenceSnapshot=(input:Partial<UserNotificationPreferenceSnapshot>&{userId:string})=>({...getUserNotificationDefaultPreferences(input.userId),...input});
export const updateUserNotificationPreferences=(s:UserNotificationPreferenceSnapshot,u:UserNotificationPreferenceUpdateRequest)=>({...s,...u,channels:u.channels??s.channels,topics:u.topics??s.topics,assetPreferences:u.assetPreferences??s.assetPreferences,updatedAt:new Date().toISOString()});
export const evaluateNotificationQuietHours=(input:{snapshot:UserNotificationPreferenceSnapshot;nowLocalTime:string})=>{const q=input.snapshot.quietHours; if(q.mode==='disabled') return {suppressed:false,defer:false}; const inWindow=q.startLocalTime<=q.endLocalTime?input.nowLocalTime>=q.startLocalTime&&input.nowLocalTime<q.endLocalTime:input.nowLocalTime>=q.startLocalTime||input.nowLocalTime<q.endLocalTime; return {suppressed:inWindow&&q.mode==='suppress',defer:inWindow&&q.mode==='defer'};};
export const evaluateNotificationRateLimit=(input:{alreadySentTopicHour:number;alreadySentChannelDay:number;isDuplicateEvent:boolean;maxTopicPerHour?:number;maxChannelPerDay?:number;}):UserNotificationRateLimitDecision=>{if(input.isDuplicateEvent) return {allowed:false,reason:'duplicate_event',suppressUntil:null}; if(input.alreadySentTopicHour>=(input.maxTopicPerHour??3)) return {allowed:false,reason:'rate_limited',suppressUntil:null}; if(input.alreadySentChannelDay>=(input.maxChannelPerDay??20)) return {allowed:false,reason:'rate_limited',suppressUntil:null}; return {allowed:true,reason:null,suppressUntil:null};};
export const evaluateUserNotificationEventTrigger=(input:{snapshot:UserNotificationPreferenceSnapshot;event:UserNotificationEventTrigger;nowLocalTime:string})=>{const {snapshot,event}=input; if(!snapshot.globalEnabled||snapshot.unsubscribed) return {allowed:false,reason:'unsubscribed' as const}; const c=snapshot.channels.find((x)=>x.channel===event.channel); const t=snapshot.topics.find((x)=>x.topic===event.topic); if(!c?.enabled) return {allowed:false,reason:'channel_disabled' as const}; if(!t?.enabled) return {allowed:false,reason:'topic_disabled' as const}; if(event.assetId && snapshot.assetPreferences.some((x)=>x.assetId===event.assetId&&x.topic===event.topic&&!x.enabled)) return {allowed:false,reason:'asset_disabled' as const}; if(event.topic==='evidence_score_change' && typeof event.scoreBefore==='number' && typeof event.scoreAfter==='number' && Math.abs(event.scoreAfter-event.scoreBefore)<(t.evidenceScoreThreshold??5)) return {allowed:false,reason:'below_threshold' as const}; const q=evaluateNotificationQuietHours({snapshot,nowLocalTime:input.nowLocalTime}); if(q.suppressed) return {allowed:false,reason:'quiet_hours' as const}; return {allowed:true,reason:null,defer:q.defer};};
export const buildNotificationDeliveryDraft=(event:UserNotificationEventTrigger, status:UserNotificationDeliveryDraft['deliveryStatus']='draft'):UserNotificationDeliveryDraft=>({userId:event.userId,eventId:event.eventId,eventKind:event.eventKind,topic:event.topic,channel:event.channel,assetId:event.assetId??null,title:`${event.topic.replaceAll('_',' ')} update`,safeSummary:'Market reasoning notification prepared. No trade recommendation included.',priority:event.topic==='risk_contradiction_alert'?'critical':'normal',createdAt:event.createdAt,providerActivationStatus:'shell_only',deliveryStatus:status,redacted:true});
export const buildNotificationOutboxItem=(deliveryDraft:UserNotificationDeliveryDraft):UserNotificationOutboxItem=>({outboxId:`outbox_${deliveryDraft.userId}_${deliveryDraft.eventId}_${deliveryDraft.channel}`,deliveryDraft,status:deliveryDraft.deliveryStatus,retryCount:0,maxRetries:3,nextAttemptAt:null,lastFailureReason:null});
export const buildNotificationDeliveryLog=(outbox:UserNotificationOutboxItem,status:UserNotificationDeliveryLog['status']):UserNotificationDeliveryLog=>({deliveryId:`delivery_${outbox.outboxId}`,outboxId:outbox.outboxId,userId:outbox.deliveryDraft.userId,channel:outbox.deliveryDraft.channel,status,provider:outbox.deliveryDraft.channel==='email'?'email_shell':'whatsapp_shell',attemptedAt:new Date().toISOString(),safeSummary:outbox.deliveryDraft.safeSummary,failureReason:status==='failed'?'unknown':null});
export const getEmailNotificationProviderReadiness=():EmailNotificationProviderReadiness=>({channel:'email',provider:'email_shell',activationStatus:'shell_only',liveSendsEnabled:false,requirements:['provider selection pending','sender domain verification required','unsubscribe handling required','bounce/failure handling required','env keys required later']});
export const getWhatsAppNotificationProviderReadiness=():WhatsAppNotificationProviderReadiness=>({channel:'whatsapp',provider:'whatsapp_shell',activationStatus:'shell_only',liveSendsEnabled:false,requirements:['provider selection pending','whatsapp opt-in required','template approval required','phone normalization/verification required','delivery webhook required later']});
export const getNotificationProviderDescriptors=():UserNotificationProviderDescriptor[]=>[getEmailNotificationProviderReadiness(),getWhatsAppNotificationProviderReadiness()];
export const getUserNotificationCoverageReport=(snapshot:UserNotificationPreferenceSnapshot):UserNotificationCoverageReport=>({userId:snapshot.userId,globalEnabled:snapshot.globalEnabled,enabledChannels:CHANNELS.filter((c)=>snapshot.channels.some((x)=>x.channel===c&&x.enabled)),enabledTopics:TOPICS.filter((t)=>snapshot.topics.some((x)=>x.topic===t&&x.enabled)),hasQuietHours:snapshot.quietHours.mode!=='disabled',digestEnabled:snapshot.topics.some((x)=>x.topic==='scheduled_digest'&&x.enabled)});
