import type { TradableLaunchAsset, SeoProgrammaticAssetIndexFeed, SeoProgrammaticDiagnosticAssetPage, SeoProgrammaticCanonicalFeed, SeoProgrammaticContentRegistry, SeoProgrammaticCoverageReport, SeoProgrammaticEvidenceClassPage, SeoProgrammaticFeaturePage, SeoProgrammaticGlossaryPage, SeoProgrammaticMacroEventPage, SeoProgrammaticRobotsPolicy, SeoProgrammaticSafetyReport, SeoProgrammaticSitemapFeed, SeoProgrammaticStructuredDataPayload, SeoProgrammaticSupportedAssetPage } from '@elceo/types';
const NOW='2026-05-16T00:00:00.000Z';
const assets:[TradableLaunchAsset,string,string,string,'tier_1a_core'|'tier_1b_major_fx'][]=[['xau_usd','XAU/USD','Gold','commodities','tier_1a_core'],['eur_usd','EUR/USD','Euro vs US Dollar','fx','tier_1a_core'],['gbp_usd','GBP/USD','British Pound vs US Dollar','fx','tier_1a_core'],['usd_jpy','USD/JPY','US Dollar vs Japanese Yen','fx','tier_1a_core'],['btc_usd','BTC/USD','Bitcoin vs US Dollar','crypto','tier_1a_core'],['nasdaq_100','Nasdaq 100','Nasdaq 100 Index','equity_index','tier_1a_core'],['sp500','S&P 500','S&P 500 Index','equity_index','tier_1a_core'],['de30','DE30','Germany 30 Index','equity_index','tier_1a_core'],['aud_usd','AUD/USD','Australian Dollar vs US Dollar','fx','tier_1b_major_fx'],['usd_chf','USD/CHF','US Dollar vs Swiss Franc','fx','tier_1b_major_fx'],['nzd_usd','NZD/USD','New Zealand Dollar vs US Dollar','fx','tier_1b_major_fx'],['usd_cad','USD/CAD','US Dollar vs Canadian Dollar','fx','tier_1b_major_fx']];
const diagnosticAssets: SeoProgrammaticDiagnosticAssetPage[]=[{assetId:'dxy',supportRole:'reasoning_diagnostic',tradable:false,displaySymbol:'DXY',assetName:'US Dollar Index',slug:'diagnostics/dxy',canonicalPath:'/diagnostics/dxy',title:'DXY Market Diagnostic | ELCEO',metaDescription:'Educational diagnostic context for DXY.',publicSummary:'DXY is a reasoning diagnostic, not a launch-tradable instrument.',indexingPolicy:'index_follow',structuredDataKind:'webpage',updatedAt:NOW,visibility:'public'},{assetId:'vix',supportRole:'reasoning_diagnostic',tradable:false,displaySymbol:'VIX',assetName:'Volatility Index',slug:'diagnostics/vix',canonicalPath:'/diagnostics/vix',title:'VIX Market Diagnostic | ELCEO',metaDescription:'Educational diagnostic context for VIX.',publicSummary:'VIX is a reasoning diagnostic, not a launch-tradable instrument.',indexingPolicy:'index_follow',structuredDataKind:'webpage',updatedAt:NOW,visibility:'public'}];
export function getSeoSupportedAssetPage(asset: TradableLaunchAsset): SeoProgrammaticSupportedAssetPage { const a=assets.find((x)=>x[0]===asset)!; const slug=`assets/${a[1].toLowerCase().replace('/','-')}`; return {assetId:a[0],displaySymbol:a[1],assetName:a[2],tier:a[4],marketFamily:a[3],slug,canonicalPath:`/${slug}`,title:`${a[2]} Market Explainer | ELCEO`,metaDescription:`Educational explainer for ${a[1]} covering macro, liquidity, and risk context.`,publicSummary:`ELCEO helps traders reason through market evidence around ${a[1]}.`,educationalSections:[{heading:'Macro context',body:`This page explains macro, liquidity, and risk factors commonly watched for ${a[1]}.`}],relatedGlossarySlugs:['market-reasoning','liquidity-pressure'],supportedStatus:'supported',premiumContentBoundaryNote:'Premium users can access structured evidence views inside the product.',indexingPolicy:'index_follow',structuredDataKind:'webpage',updatedAt:NOW,visibility:'public'}; }
export function listSeoSupportedAssetPages(){ return assets.map((x)=>getSeoSupportedAssetPage(x[0])); }
export function getSeoDiagnosticAssetPages(): SeoProgrammaticDiagnosticAssetPage[] { return [...diagnosticAssets]; }
export function getSeoSupportedAssetIndexFeed():SeoProgrammaticAssetIndexFeed{return {generatedAt:NOW,visibility:'public',assets:listSeoSupportedAssetPages()};}
export function getSeoMacroEventPages():SeoProgrammaticMacroEventPage[]{ return ['cpi','ppi','nfp','fomc','ecb-decision','boe-decision','boj-decision','rba-decision','rbnz-decision','boc-decision','snb-decision','gdp','pmi','retail-sales','unemployment-rate','10y-yield'].map((slug)=>({slug,title:`${slug.toUpperCase()} Market Event Explainer | ELCEO`,metaDescription:`Educational explainer for ${slug}.`,publicDefinition:`${slug} is a macro event monitored by traders for cross-asset context.`,whyTradersWatchIt:'It can shift rate expectations, liquidity conditions, and volatility regimes.',assetsCommonlyAffected:['eur_usd','usd_jpy','sp500'],evidenceClasses:['macro_context','liquidity_pressure'],safeEducationalNote:'Educational only; this is not financial advice or a trade recommendation.',indexingPolicy:'index_follow',canonicalPath:`/macro-events/${slug}`,visibility:'public'})); }
export function getSeoEvidenceClassPages():SeoProgrammaticEvidenceClassPage[]{ return [{slug:'evidence-score',title:'Evidence Score',metaDescription:'What evidence score means.',publicDefinition:'A normalized measure of evidence quality and relevance.',whyItMatters:'Helps compare signal quality without giving trade calls.',safeExample:'Example: conflicting macro releases can lower confidence.',relatedAssets:['xau_usd','eur_usd'],relatedGlossarySlugs:['confidence-decomposition'],indexingPolicy:'index_follow',canonicalPath:'/glossary/evidence-score',visibility:'public'}]; }
export function getSeoMarketReasoningGlossaryPages():SeoProgrammaticGlossaryPage[]{ return [{slug:'market-reasoning',title:'Market Reasoning',metaDescription:'How ELCEO frames market reasoning.',publicDefinition:'A structured educational framework for connecting macro, liquidity, and risk evidence.',whyItMatters:'Helps users interpret evidence interactions without issuing recommendations.',safeExample:'Example: macro surprise plus tight liquidity can increase regime uncertainty.',relatedAssets:['xau_usd','eur_usd'],relatedGlossarySlugs:['evidence-score'],indexingPolicy:'index_follow',canonicalPath:'/glossary/market-reasoning',visibility:'public',category:'market_reasoning'}]; }
export function getSeoFeaturePages():SeoProgrammaticFeaturePage[]{ return [{slug:'market-cognition-os',title:'Market Cognition OS',metaDescription:'ELCEO product feature overview.',publicSummary:'ELCEO organizes macro, liquidity, and risk evidence for trader education.',capabilityHighlights:['Evidence classification','Contradiction detection','Scenario replay mode'],premiumBoundaryNote:'Premium intelligence remains in authenticated product surfaces.',indexingPolicy:'index_follow',canonicalPath:'/features/market-cognition-os',visibility:'public'}]; }
export function getSeoSitemapFeed():SeoProgrammaticSitemapFeed{ const entries=[...listSeoSupportedAssetPages().map((x)=>({path:x.canonicalPath,changeFrequency:'weekly' as const,priority:0.7,lastModified:NOW,indexingPolicy:x.indexingPolicy,contentKind:'asset_page' as const})),...getSeoMacroEventPages().map((x)=>({path:x.canonicalPath,changeFrequency:'weekly' as const,priority:0.6,lastModified:NOW,indexingPolicy:x.indexingPolicy,contentKind:'macro_event' as const}))].sort((a,b)=>a.path.localeCompare(b.path)); return {generatedAt:NOW,entries,visibility:'public'}; }
export function getSeoRobotsPolicy():SeoProgrammaticRobotsPolicy{return {allowedPublicPaths:['/assets','/glossary','/macro-events','/features'],disallowedPaths:['/admin','/api','/dashboard','/account','/billing','/internal','/operator'],noindexPatterns:['/admin/*','/api/*','/dashboard/*','/account/*','/billing/*','/operator/*'],protectedPaths:['/dashboard','/workspace','/subscription'],adminPaths:['/admin','/operator'],apiPaths:['/api'],visibility:'public'};}
export function getSeoCanonicalFeed():SeoProgrammaticCanonicalFeed{ const entries=getSeoSitemapFeed().entries.map((x)=>({path:x.path,canonicalPath:x.path,canonicalStatus:'canonical' as const,contentKind:x.contentKind})); return {generatedAt:NOW,entries,visibility:'public'};}
export function getSeoStructuredDataPayloads():SeoProgrammaticStructuredDataPayload[]{ return [{id:'website',kind:'website',path:'/',jsonLd:{'@context':'https://schema.org','@type':'WebSite',name:'ELCEO'},visibility:'public'}]; }
export function getSeoProgrammaticContentRegistry():SeoProgrammaticContentRegistry{ return {generatedAt:NOW,status:'active',entries:getSeoSitemapFeed().entries.map((x)=>({surface:'sitemap',contentKind:x.contentKind,path:x.path,visibility:'public',indexingPolicy:x.indexingPolicy})),safetyStatus:'pass'}; }
export function getSeoProgrammaticSafetyReport():SeoProgrammaticSafetyReport{ return {generatedAt:NOW,status:'pass',checks:[{name:'no_recommendation_language',status:'pass',details:'No buy/sell/hold or profit-promise language detected.'},{name:'no_premium_or_admin_data',status:'pass',details:'Public feeds exclude premium cognition, admin/internal, and secret-like fields.'}],blockedTerms:['buy','sell','hold','guaranteed profit','financial advice']}; }
export function getSeoProgrammaticCoverageReport():SeoProgrammaticCoverageReport{return {generatedAt:NOW,tier1aCovered:true,tier1bCovered:true,supportedTradableAssetCount:assets.length,reasoningDiagnosticAssetCount:diagnosticAssets.length,representedReasoningAssetCount:assets.length+diagnosticAssets.length,macroPageCount:getSeoMacroEventPages().length,glossaryPageCount:getSeoMarketReasoningGlossaryPages().length+getSeoEvidenceClassPages().length,featurePageCount:getSeoFeaturePages().length,sitemapEntryCount:getSeoSitemapFeed().entries.length};}