import { createHash } from 'node:crypto';
import type { KoraPayCheckoutReadinessRequest, KoraPayCheckoutReadinessResult, KoraPayCheckoutSessionDraft, KoraPayEntitlementGrantDecision, KoraPayNormalizedPaymentEvent, KoraPayPaymentCoverageReport, KoraPayProviderDescriptor, KoraPayProviderReadinessReport, KoraPayRawWebhookEventFixture, KoraPayWebhookProcessingResult, KoraPayWebhookVerificationConfig, KoraPayWebhookVerificationInput, KoraPayWebhookVerificationResult } from '@elceo/types';

const configuredPrices: Record<'monthly'|'quarterly'|'yearly', number | null> = { monthly: 70, quarterly: null, yearly: null };
export const getKoraPayProviderDescriptor = (): KoraPayProviderDescriptor => ({ provider: 'korapay', activationStatus: 'not_activated', capabilities: ['checkout_draft','entitlement_decision','event_normalization','idempotency_key_derivation','webhook_fixture_verification'], liveActivationRequired: true, notes: ['live_activation_required','official_korapay_webhook_docs_verification_required'] });
export const getKoraPayEnvironmentTemplate = () => ({ provider: 'korapay' as const, mode: 'sandbox_template' as const, publicKeyTemplate: 'korapay_public_key_template_live_activation_required', secretKeyTemplate: 'korapay_secret_key_template_live_activation_required', webhookSecretTemplate: 'korapay_webhook_secret_template_live_activation_required', checkoutBaseUrlTemplate: 'https://korapay.example.template/live_activation_required', liveActivationRequired: true as const });
export const getKoraPayProviderReadinessReport = (): KoraPayProviderReadinessReport => ({ provider: 'korapay', activationStatus: 'not_activated', supportsLiveCheckout: false, supportsLiveWebhookGrant: false, requiresOfficialDocsVerification: true, pricingAuthority:'commercial_price_versions' });
export const buildKoraPayCheckoutReadinessRequest = (input: KoraPayCheckoutReadinessRequest) => input;
export const checkKoraPayCheckoutReadiness = (input: KoraPayCheckoutReadinessRequest): KoraPayCheckoutReadinessResult => {
  const reasons: string[] = [];
  if (!input.userId) reasons.push('missing_user_id');
  if (input.planCode !== 'focus_plan') reasons.push('unsupported_plan');
  if (!['monthly','quarterly','yearly'].includes(input.billingInterval)) reasons.push('unsupported_interval');
  if (!input.socialIdentifierReady || input.socialIdentifiers.length===0) reasons.push('missing_social_identifier');
  if (input.billingInterval !== 'monthly' && configuredPrices[input.billingInterval] == null) reasons.push('pending_price_config');
  return reasons.length ? { status:'blocked', reasons, checkoutSessionDraft:null } : { status:'ready_for_draft', reasons: [], checkoutSessionDraft: buildKoraPayCheckoutSessionDraft(input) };
};
export const buildKoraPayCheckoutSessionDraft = (input: KoraPayCheckoutReadinessRequest): KoraPayCheckoutSessionDraft => ({ provider:'korapay', userId:input.userId, planCode:'focus_plan', billingInterval:input.billingInterval, amount: configuredPrices[input.billingInterval], currency: configuredPrices[input.billingInterval] ? 'USD' : null, referenceDraft:`korapay_draft_${input.userId}_${input.billingInterval}`, metadata:{ socialIdentifierKinds: input.socialIdentifiers.map(s=>s.kind).sort(), providerActivationRequired:true }, activationStatus:'blocked_until_keys_configured', liveCreated:false });
export const getKoraPayWebhookVerificationConfig = (): KoraPayWebhookVerificationConfig => ({ mode:'live', signatureStrategy:'live_docs_verification_required', liveActivationRequired:true });
export const verifyKoraPayWebhookSignature = (input: KoraPayWebhookVerificationInput): KoraPayWebhookVerificationResult => {
  if (input.fixtureMode) return { status:'skipped_fixture_only', failureReason:'fixture_verification_only', eventId:null, receivedAt:input.receivedAt, signatureStrategy:'fixture_only' };
  return { status:'live_config_missing', failureReason:'missing_signature_strategy', eventId:null, receivedAt:input.receivedAt, signatureStrategy:'live_docs_verification_required' };
};
export const buildKoraPayWebhookIdempotencyKey = (event: {eventId:string;transactionReference:string|null;providerReference:string|null}) => createHash('sha256').update(`${event.eventId}|${event.transactionReference ?? ''}|${event.providerReference ?? ''}`).digest('hex');
export const normalizeProviderReference = (event: {providerReference:string|null;transactionReference:string|null}) => event.providerReference ?? event.transactionReference ?? null;
export const detectKoraPayWebhookDuplicate = (event: {idempotencyKey:string}, seenKeys: Set<string>) => seenKeys.has(event.idempotencyKey);
export const normalizeKoraPayWebhookEvent = (input: {fixture: KoraPayRawWebhookEventFixture; verificationStatus: KoraPayWebhookVerificationResult['status']; duplicateDetected?: boolean}): KoraPayNormalizedPaymentEvent => {
  const normalizedStatus = input.fixture.eventKind.includes('success') ? 'succeeded' : input.fixture.eventKind.includes('failed') ? 'failed' : input.fixture.eventKind === 'refund_or_reversal' ? 'reversed' : 'unknown';
  const providerReference = normalizeProviderReference({ providerReference: input.fixture.providerReference, transactionReference: input.fixture.transactionReference });
  const idempotencyKey = buildKoraPayWebhookIdempotencyKey({ eventId: input.fixture.eventId, transactionReference: input.fixture.transactionReference, providerReference });
  return { provider:'korapay', eventId:input.fixture.eventId, eventKind:input.fixture.eventKind, normalizedStatus, userId:input.fixture.userId, planCode:input.fixture.planCode, billingInterval:input.fixture.billingInterval, amount:input.fixture.amount, currency:input.fixture.currency, transactionReference:input.fixture.transactionReference, providerReference, occurredAt:input.fixture.occurredAt, verificationStatus:input.verificationStatus, idempotencyKey, rawFixtureId:input.fixture.fixtureId, safeSummary:`korapay fixture ${input.fixture.eventKind}`, duplicateDetected: Boolean(input.duplicateDetected) };
};
export const decideKoraPayEntitlementGrant = (input: {event: KoraPayNormalizedPaymentEvent}): KoraPayEntitlementGrantDecision => { const e=input.event; if(e.verificationStatus!=='verified') return {status:'block', reason:'webhook_not_verified', targetPlanCode:null, userId:e.userId}; if(e.duplicateDetected) return {status:'ignore', reason:'duplicate_event', targetPlanCode:null, userId:e.userId}; if(!e.userId) return {status:'block', reason:'missing_user_id', targetPlanCode:null, userId:null}; if(e.planCode!=='focus_plan') return {status:'ignore', reason:'unsupported_plan', targetPlanCode:null, userId:e.userId}; if(!['monthly','quarterly','yearly'].includes(String(e.billingInterval))) return {status:'block', reason:'invalid_interval', targetPlanCode:null, userId:e.userId}; if(e.eventKind==='payment_success'||e.eventKind==='subscription_payment_success') return {status:'grant_focus_plan', reason:'verified_successful_payment', targetPlanCode:'focus_plan', userId:e.userId}; if(e.eventKind==='refund_or_reversal') return {status:'require_manual_review', reason:'refund_or_reversal', targetPlanCode:null, userId:e.userId}; return {status:'block', reason:'non_successful_event', targetPlanCode:null, userId:e.userId}; };
export const processKoraPayWebhookFixture = (input: {fixture: KoraPayRawWebhookEventFixture; seenKeys?: Set<string>; verificationStatus?: KoraPayWebhookVerificationResult['status']}): KoraPayWebhookProcessingResult => { const verification: KoraPayWebhookVerificationResult = { status: input.verificationStatus ?? 'verified', failureReason: null, eventId: input.fixture.eventId, receivedAt: new Date().toISOString(), signatureStrategy: 'fixture_only' }; const normalized = normalizeKoraPayWebhookEvent({ fixture: input.fixture, verificationStatus: verification.status }); const duplicate = detectKoraPayWebhookDuplicate({ idempotencyKey: normalized.idempotencyKey }, input.seenKeys ?? new Set<string>()); const normalizedWithDup = { ...normalized, duplicateDetected: duplicate }; const decision = decideKoraPayEntitlementGrant({ event: normalizedWithDup }); return { verification, normalizedEvent: normalizedWithDup, decision, duplicateDetected: duplicate }; };
export const getKoraPayPaymentCoverageReport = (): KoraPayPaymentCoverageReport => ({ provider:'korapay', supportedPlans:['focus_plan'], supportedIntervals:['monthly','quarterly','yearly'], supportedEventKinds:['payment_success','payment_failed','refund_or_reversal','subscription_payment_failed','subscription_payment_success','unknown_event'], deterministicOrdering:true, providerCallsPerformed:false });
