import type { ObservabilityAuditActionKind, ObservabilityAuditCoverageReport, ObservabilityAuditDiagnosticErrorCategory, ObservabilityAuditDiagnosticErrorEnvelope, ObservabilityAuditEventEnvelope, ObservabilityAuditEventSeverity, ObservabilityAuditLiveActivationStatus, ObservabilityAuditReadinessReport, ObservabilityAuditRedactionResult, ObservabilityAuditStructuredLogEvent, ObservabilityAuditSubsystem, ObservabilityAuditTraceContext } from '@elceo/types';
import { ObservabilityAuditSubsystemValues } from '@elceo/types';

const now=()=>new Date().toISOString();
export const createObservabilityAuditTraceContext=(input:Partial<ObservabilityAuditTraceContext>={}):ObservabilityAuditTraceContext=>({traceKind:input.traceKind??'request',traceId:input.traceId??'trace-fixed',subsystem:input.subsystem??'security_runtime',environment:input.environment??'test',createdAt:input.createdAt??now(),...input});
export const buildObservabilityAuditStructuredLogEvent=(input:{message:string;subsystem:ObservabilityAuditSubsystem;actionKind:ObservabilityAuditActionKind;traceContext:ObservabilityAuditTraceContext;severity?:ObservabilityAuditEventSeverity;}):ObservabilityAuditStructuredLogEvent=>({eventKind:'structured_log',severity:input.severity??'info',source:'internal_contract',message:input.message,subsystem:input.subsystem,actionKind:input.actionKind,traceContext:input.traceContext,redactionStatus:'not_required',occurredAt:now()});
export const buildObservabilityAuditEventEnvelope=(input:{eventId:string;logEvent:ObservabilityAuditStructuredLogEvent;liveActivationStatus?:ObservabilityAuditLiveActivationStatus;}):ObservabilityAuditEventEnvelope=>({eventId:input.eventId,deliveryStatus:'not_dispatched',dataSensitivity:'internal',liveActivationStatus:input.liveActivationStatus??'blocked',logEvent:input.logEvent});
export const buildObservabilityAuditLogEvent=(input:{eventId:string;message:string;subsystem:ObservabilityAuditSubsystem;actionKind:ObservabilityAuditActionKind;traceContext:ObservabilityAuditTraceContext;})=>{const log=buildObservabilityAuditStructuredLogEvent(input);return {...log,envelope:buildObservabilityAuditEventEnvelope({eventId:input.eventId,logEvent:log})};};
const mk=(subsystem:ObservabilityAuditSubsystem,message:string,traceContext:ObservabilityAuditTraceContext)=>buildObservabilityAuditStructuredLogEvent({message,subsystem,actionKind:'evaluate',traceContext});
export const buildObservabilityAuditSecurityDiagnosticEvent=(i:{message:string;traceContext:ObservabilityAuditTraceContext;})=>({...mk('security_runtime',i.message,i.traceContext),securityEventKind:'security_decision_completed',outcome:'allowed'} as const);
export const buildObservabilityAuditProviderDiagnosticEvent=(i:{message:string;traceContext:ObservabilityAuditTraceContext;})=>mk('provider_registry',i.message,i.traceContext);
export const buildObservabilityAuditIngestionDiagnosticEvent=(i:{message:string;traceContext:ObservabilityAuditTraceContext;})=>mk('scheduled_ingestion',i.message,i.traceContext);
export const buildObservabilityAuditCognitionDiagnosticEvent=(i:{message:string;traceContext:ObservabilityAuditTraceContext;})=>mk('golden_scenario',i.message,i.traceContext);
export const buildObservabilityAuditCalibrationDiagnosticEvent=(i:{message:string;traceContext:ObservabilityAuditTraceContext;})=>mk('cognition_calibration',i.message,i.traceContext);
export const buildObservabilityAuditFrontendContractDiagnosticEvent=(i:{message:string;traceContext:ObservabilityAuditTraceContext;})=>mk('frontend_contracts',i.message,i.traceContext);
export const buildObservabilityAuditCommercialDiagnosticEvent=(i:{message:string;traceContext:ObservabilityAuditTraceContext;})=>mk('commercial_entitlements',i.message,i.traceContext);
export const buildObservabilityAuditNotificationDiagnosticEvent=(i:{message:string;traceContext:ObservabilityAuditTraceContext;})=>mk('user_notifications',i.message,i.traceContext);
export const buildObservabilityAuditSeoDiagnosticEvent=(i:{message:string;traceContext:ObservabilityAuditTraceContext;})=>mk('seo_programmatic_feeds',i.message,i.traceContext);
export const buildObservabilityAuditProviderActivationDiagnosticEvent=(i:{message:string;traceContext:ObservabilityAuditTraceContext;})=>mk('provider_activation_readiness',i.message,i.traceContext);

const KEYS=['authorization','bearer token','cookie','set-cookie','api_key','access_token','refresh_token','client_secret','webhook_secret','password','private_key','session_secret','csrf_secret','auth_secret','korapay_secret_key','stripe_secret_key','email_provider_api_key','whatsapp_access_token','twilio_auth_token','database_url','redis_url'];
export const redactObservabilityAuditPayload=(payload:unknown):ObservabilityAuditRedactionResult=>{const redactedKeys:string[]=[]; const walk=(v:any):any=>{if(Array.isArray(v)) return v.map(walk); if(v&&typeof v==='object'){const out:Record<string,unknown>={}; Object.keys(v).sort().forEach((k)=>{if(KEYS.includes(k.toLowerCase())){redactedKeys.push(k); out[k]='[REDACTED]';} else out[k]=walk(v[k]);}); return out;} if(typeof v==='string'&&/(bearer\s+|-----BEGIN|postgres:\/\/|redis:\/\/)/i.test(v)){return '[REDACTED_VALUE]';} return v;}; const redactedPayload=walk(payload); return {redactedPayload,redactionStatus:redactedKeys.length?'applied':'not_required',redactedKeys,secretLikeValueDetected:JSON.stringify(payload).toLowerCase().includes('secret'),rawPayloadRemoved:redactedKeys.length>0,operatorNote:redactedKeys.length?'sensitive keys redacted':'no sensitive keys found'};};
export const assertNoSecretsInObservabilityAuditPayload=(payload:unknown)=>{const walk=(v:unknown):boolean=>{if(v===null||v===undefined) return true; if(typeof v==='string') return !/(bearer\s+|sk_live|sk_test|-----BEGIN|postgres:\/\/|redis:\/\/|token|secret|api[_-]?key)/i.test(v); if(Array.isArray(v)) return v.every(walk); if(typeof v==='object') return Object.values(v as Record<string,unknown>).every(walk); return true;}; if(!walk(payload)) throw new Error('secret-like field detected'); return true;};
export const buildObservabilityAuditDiagnosticErrorEnvelope=(input:{errorId:string;category:ObservabilityAuditDiagnosticErrorCategory;message:string;traceContext:ObservabilityAuditTraceContext;safeSummary:string;operatorAction:string;retryable:boolean;}):ObservabilityAuditDiagnosticErrorEnvelope=>({errorId:input.errorId,category:input.category,severity:'error',message:input.message,safeSummary:input.safeSummary,traceContext:input.traceContext,redactionStatus:'not_required',occurredAt:now(),operatorAction:input.operatorAction,retryable:input.retryable});
export const getObservabilityAuditReadinessReport=():ObservabilityAuditReadinessReport=>({externalVendorIntegrated:false,structuredLoggingContractsReady:true,redactionHelpersReady:true,auditEventBuildersReady:true,securityDiagnosticEventsReady:true,errorEnvelopeReady:true,persistenceRequiredLater:false,routeIntegrationPending:true,productionExportPending:true,liveActivationStatus:'blocked'});
export const getObservabilityAuditCoverageReport=():ObservabilityAuditCoverageReport=>({generatedAt:now(),deterministicOrdering:true,subsystems:[...ObservabilityAuditSubsystemValues].sort().map((subsystem)=>({subsystem,diagnosticCoverage:'ready'}))});
