import type { ProviderSourceRequest, ProviderSourceResponse } from '@elceo/types';
import type { MarketEvidenceProviderAdapter } from '../normalization-contracts';
import { getProviderDescriptor } from '../provider-capability-registry';
import { STRESS_CONDITIONS_FIXTURE } from './fixtures';
import { buildCreditStressPayload, buildDollarLiquidityPayload, buildFinancialConditionsPayload, buildLiquidityConditionsPayload } from './stress-conditions-normalizer';
const SUPPORTED=new Set(['credit_stress_indicator','financial_conditions_index','liquidity_conditions_indicator','dollar_liquidity_indicator']);
const base=(r:ProviderSourceRequest):ProviderSourceResponse=>({requestId:r.requestId,providerId:r.providerId,capability:r.capability,status:'failed',fetchedAt:r.requestedAt,sourceUrl:null,rawPayloadJson:null,errorCode:'not_fetched',errorMessage:'not fetched'});
export class StressConditionsFixtureAdapter implements MarketEvidenceProviderAdapter { descriptor=getProviderDescriptor('fred')??getProviderDescriptor('calculated_internal_conditions')??(()=>{throw new Error('missing_stress_conditions_descriptor')})();
async fetch(request:ProviderSourceRequest):Promise<ProviderSourceResponse>{ if(!SUPPORTED.has(request.capability)) return {...base(request),status:'unsupported',errorCode:'unsupported_capability',errorMessage:`Unsupported capability: ${request.capability}`}; const fixture={...STRESS_CONDITIONS_FIXTURE,request:{providerId:request.providerId,region:request.region??'united_states',capability:request.capability as never,requestedAt:request.requestedAt}}; return {...base(request),status:'success',sourceUrl:`fixture://stress-conditions/${request.capability}`,rawPayloadJson:JSON.stringify(fixture),errorCode:null,errorMessage:null}; }
async normalize(response:ProviderSourceResponse){ if(!response.rawPayloadJson) throw new Error('stress_conditions_missing_payload'); let parsed:typeof STRESS_CONDITIONS_FIXTURE; try{parsed=JSON.parse(response.rawPayloadJson) as typeof STRESS_CONDITIONS_FIXTURE;}catch{throw new Error('stress_conditions_malformed_payload');} if(!parsed.request) throw new Error('stress_conditions_malformed_payload'); if(response.capability==='credit_stress_indicator') return parsed.creditStressRows.map((x)=>buildCreditStressPayload(parsed.request,x)); if(response.capability==='financial_conditions_index') return parsed.financialConditionsRows.map((x)=>buildFinancialConditionsPayload(parsed.request,x)); if(response.capability==='liquidity_conditions_indicator') return parsed.liquidityConditionRows.map((x)=>buildLiquidityConditionsPayload(parsed.request,x)); if(response.capability==='dollar_liquidity_indicator') return parsed.dollarLiquidityRows.map((x)=>buildDollarLiquidityPayload(parsed.request,x)); return []; }
}
