import type { MarketAffectedCurrency, MarketEconomicContextResolverInput, MarketEconomicContextResolution, MarketEconomicContextWarning, MarketEconomicDriverContext, MarketEconomicDriverContextInput, MarketEconomicDriverDirection, MarketEconomicDriverKind, MarketIssuerCurrency, MarketIssuerInstitution, MarketIssuerRegion } from '@elceo/types';
import { MARKET_AFFECTED_CURRENCIES, MARKET_ECONOMIC_DRIVER_DIRECTIONS, MARKET_ECONOMIC_DRIVER_KINDS, MARKET_ISSUER_CURRENCIES, MARKET_ISSUER_INSTITUTIONS, MARKET_ISSUER_REGIONS } from '@elceo/types';
import { validateMarketEconomicContextResolution, validateMarketEconomicDriverContext } from '@elceo/schemas';
const MAP: Record<Exclude<MarketIssuerInstitution,'other'|'unknown'>,{region:MarketIssuerRegion;currency:MarketIssuerCurrency}> = { fed:{region:'US',currency:'USD'}, ecb:{region:'eurozone',currency:'EUR'}, boe:{region:'UK',currency:'GBP'}, boj:{region:'Japan',currency:'JPY'}, snb:{region:'Switzerland',currency:'CHF'}, rba:{region:'Australia',currency:'AUD'}, rbnz:{region:'New_Zealand',currency:'NZD'}, boc:{region:'Canada',currency:'CAD'}, pboc:{region:'China',currency:'CNY'} };
const REGION_CCY: Record<string, MarketIssuerCurrency> = { US:'USD', eurozone:'EUR', UK:'GBP', Japan:'JPY', Switzerland:'CHF', Australia:'AUD', New_Zealand:'NZD', Canada:'CAD', China:'CNY', global:'global', other:'other', unknown:'unknown' };
const CCY_REGION: Record<string, MarketIssuerRegion> = { USD:'US', EUR:'eurozone', GBP:'UK', JPY:'Japan', CHF:'Switzerland', AUD:'Australia', NZD:'New_Zealand', CAD:'Canada', CNY:'China', global:'global', other:'other', unknown:'unknown' };
function norm(v: unknown): string { return typeof v === 'string' ? v.trim().replace(/[\s-]+/g,'_') : ''; }
function low(v: unknown): string { return norm(v).toLowerCase(); }
function one<T extends string>(v: unknown, allowed: readonly T[]): T | null { const n=norm(v); return (allowed as readonly string[]).includes(n) ? n as T : null; }
function inst(v: unknown): MarketIssuerInstitution | null { const n=low(v); const aliases: Record<string, MarketIssuerInstitution> = { federal_reserve:'fed', fomc:'fed', european_central_bank:'ecb', bank_of_england:'boe', bank_of_japan:'boj', swiss_national_bank:'snb', reserve_bank_of_australia:'rba', reserve_bank_of_new_zealand:'rbnz', bank_of_canada:'boc', peoples_bank_of_china:'pboc', people_s_bank_of_china:'pboc' }; return one(n, MARKET_ISSUER_INSTITUTIONS) ?? aliases[n] ?? null; }
function region(v: unknown): MarketIssuerRegion | null { const n=norm(v); const aliases: Record<string, MarketIssuerRegion> = { united_states:'US', usa:'US', us:'US', euro_area:'eurozone', eurozone:'eurozone', united_kingdom:'UK', uk:'UK', new_zealand:'New_Zealand' }; return one(n, MARKET_ISSUER_REGIONS) ?? aliases[n] ?? null; }
function ccy(v: unknown): MarketIssuerCurrency | null { const n=norm(v).toUpperCase(); return (MARKET_ISSUER_CURRENCIES as readonly string[]).includes(n) ? n as MarketIssuerCurrency : null; }
function aff(v: unknown): MarketAffectedCurrency[] { const vals = Array.isArray(v) ? v : v === undefined || v === null ? [] : [v]; return vals.map((x)=>norm(x).toUpperCase()).filter((x): x is MarketAffectedCurrency => (MARKET_AFFECTED_CURRENCIES as readonly string[]).includes(x)); }
function uniq<T extends string>(a:T[]):T[]{return [...new Set(a)]}
function unresolved(warnings: MarketEconomicContextWarning[], conflictFields: string[], ignoredIdentityFields: string[], eventRegion: MarketIssuerRegion, affectedCurrencies: MarketAffectedCurrency[]): MarketEconomicContextResolution { return { issuerInstitution:'unknown', issuerRegion:'unknown', issuerCurrency:'unknown', eventRegion, affectedCurrencies, resolutionSource:'unresolved', resolutionConfidence:'unresolved', warnings:uniq(warnings), conflictFields:uniq(conflictFields), ignoredIdentityFields:uniq(ignoredIdentityFields)}; }
export function resolveMarketEconomicContext(input: MarketEconomicContextResolverInput = {}): MarketEconomicContextResolution {
  const m = input.metadata ?? {}; const warnings: MarketEconomicContextWarning[] = []; const ignored: string[] = [];
  for (const k of ['providerId','provider','source','sourceId','sourceFamily'] as const) if (input[k] || m[k]) { warnings.push('provider_identity_ignored'); ignored.push(k); }
  for (const k of ['targetAsset','pairAsset','scenarioId','title','note'] as const) if (input[k] || m[k]) { warnings.push(k === 'targetAsset' || k === 'pairAsset' ? 'target_asset_identity_ignored' : 'unstructured_metadata_fallback'); ignored.push(k); }
  const explicitCurrency = ccy(input.issuerCurrency ?? m.issuerCurrency ?? input.policyIssuerCurrency ?? m.policyIssuerCurrency ?? m.releaseCurrency);
  const explicitInst = inst(input.issuerInstitution ?? m.issuerInstitution ?? m.centralBank ?? input.centralBank);
  const explicitRegion = region(input.issuerRegion ?? m.issuerRegion ?? input.policyIssuerRegion ?? m.policyIssuerRegion ?? m.releaseRegion);
  const eventRegion = region(input.eventRegion ?? m.eventRegion ?? m.releaseRegion) ?? explicitRegion ?? 'unknown';
  const affectedCurrencies = aff(input.affectedCurrencies ?? m.affectedCurrencies ?? input.affectedCurrency ?? m.affectedCurrency);
  const conflict: string[] = [];
  if (explicitCurrency && explicitInst && explicitInst !== 'other' && explicitInst !== 'unknown' && MAP[explicitInst]?.currency !== explicitCurrency) conflict.push('issuerCurrency','issuerInstitution');
  if (explicitRegion && explicitCurrency && REGION_CCY[explicitRegion] !== explicitCurrency) conflict.push('issuerRegion','issuerCurrency');
  if (explicitRegion && explicitInst && explicitInst !== 'other' && explicitInst !== 'unknown' && MAP[explicitInst]?.region !== explicitRegion) conflict.push('issuerInstitution','issuerRegion');
  if (conflict.length) return unresolved([...warnings,'issuer_context_conflict', ...(conflict.includes('issuerRegion') && conflict.includes('issuerCurrency') ? ['issuer_region_currency_conflict' as const] : [])], conflict, ignored, eventRegion, affectedCurrencies);
  let r: MarketEconomicContextResolution;
  if (explicitCurrency) r = { issuerInstitution: explicitInst ?? 'unknown', issuerRegion: CCY_REGION[explicitCurrency] ?? 'unknown', issuerCurrency: explicitCurrency, eventRegion, affectedCurrencies, resolutionSource:'explicit_issuer_currency', resolutionConfidence:'high', warnings:uniq(warnings), conflictFields:[], ignoredIdentityFields:uniq(ignored) };
  else if (explicitInst && explicitInst !== 'unknown') { const mapped = explicitInst === 'other' ? {region:'other' as const,currency:'other' as const} : MAP[explicitInst]; r = { issuerInstitution:explicitInst, issuerRegion:mapped.region, issuerCurrency:mapped.currency, eventRegion, affectedCurrencies, resolutionSource:'explicit_issuer_institution', resolutionConfidence:'high', warnings:uniq(warnings), conflictFields:[], ignoredIdentityFields:uniq(ignored)}; }
  else if (explicitRegion) r = { issuerInstitution:'unknown', issuerRegion:explicitRegion, issuerCurrency:REGION_CCY[explicitRegion] ?? 'unknown', eventRegion, affectedCurrencies, resolutionSource:'explicit_issuer_region', resolutionConfidence:'medium', warnings:uniq(warnings), conflictFields:[], ignoredIdentityFields:uniq(ignored)};
  else { const legacyInst = inst(m.issuer); const legacy = legacyInst ?? ccy(m.currency) ?? region(m.region); if (legacy) { const isInst = (MARKET_ISSUER_INSTITUTIONS as readonly string[]).includes(String(legacy)) && legacy !== 'unknown' && legacy !== 'other'; const mapped = isInst ? MAP[legacy as Exclude<MarketIssuerInstitution,'other'|'unknown'>] : null; const isCurrency = (MARKET_ISSUER_CURRENCIES as readonly string[]).includes(String(legacy)); r = { issuerInstitution:isInst ? legacy as MarketIssuerInstitution : 'unknown', issuerRegion:mapped?.region ?? (isCurrency ? (CCY_REGION[String(legacy)] ?? 'unknown') : legacy as MarketIssuerRegion), issuerCurrency:mapped?.currency ?? (isCurrency ? legacy as MarketIssuerCurrency : (REGION_CCY[String(legacy)] ?? 'unknown')), eventRegion, affectedCurrencies, resolutionSource:'validated_legacy_alias', resolutionConfidence:'medium', warnings:uniq(warnings), conflictFields:[], ignoredIdentityFields:uniq(ignored)}; } else r = unresolved([...warnings,'issuer_context_missing', ...(affectedCurrencies.length ? ['affected_currency_not_issuer' as const] : [])], [], ignored, eventRegion, affectedCurrencies); }
  const badAlias = [input.issuerCurrency,m.issuerCurrency,input.issuerRegion,m.issuerRegion,input.issuerInstitution,m.issuerInstitution].some((v)=> typeof v === 'string' && !ccy(v) && !region(v) && !inst(v));
  if (badAlias) r.warnings = uniq([...r.warnings,'unsupported_region_or_currency_alias']);
  const validation = validateMarketEconomicContextResolution(r); if ('errors' in validation) throw new Error(`economic_context_invalid:${validation.errors.join('|')}`); return r;
}
export function resolveMarketEconomicDriverContext(input: MarketEconomicDriverContextInput = {}): MarketEconomicDriverContext { const m=input.metadata ?? {}; const kind = one(low(input.driverKind ?? m.driverKind), MARKET_ECONOMIC_DRIVER_KINDS) ?? 'unknown'; const rawDir = low(input.driverDirection ?? m.driverDirection ?? input.direction ?? m.direction); const dir = one(rawDir, MARKET_ECONOMIC_DRIVER_DIRECTIONS) ?? (rawDir === 'bullish' ? 'positive' : rawDir === 'bearish' ? 'negative' : 'unknown'); const out = { driverKind: kind as MarketEconomicDriverKind, driverDirection: dir as MarketEconomicDriverDirection, warnings: kind !== 'unknown' && dir === 'unknown' ? ['driver_direction_missing' as const] : [] }; const v=validateMarketEconomicDriverContext(out); if ('errors' in v) throw new Error(`economic_driver_context_invalid:${v.errors.join('|')}`); return out; }
export function assertMarketEconomicContextResolutionValid(input: MarketEconomicContextResolution): true { const v=validateMarketEconomicContextResolution(input); if ('errors' in v) throw new Error(`economic_context_invalid:${v.errors.join('|')}`); return true; }
