import type { ProviderSourceRequest, ProviderSourceResponse } from '@elceo/types';
import type { MarketEvidenceProviderAdapter } from '../normalization-contracts';
import { getProviderDescriptor } from '../provider-capability-registry';
import { REGULATORY_LIQUIDITY_FIXTURE } from './fixtures';
import { buildInstitutionalLiquidityPayload, buildRegulatoryFilingPayload, buildStressTestPayload } from './regulatory-liquidity-normalizer';
const SUPPORTED=new Set(['stress_test_result','institutional_liquidity_report','bank_health_metric','regulatory_filing_reference']);
const base=(r:ProviderSourceRequest):ProviderSourceResponse=>({requestId:r.requestId,providerId:r.providerId,capability:r.capability,status:'failed',fetchedAt:r.requestedAt,sourceUrl:null,rawPayloadJson:null,errorCode:'not_fetched',errorMessage:'not fetched'});
export class RegulatoryLiquidityFixtureAdapter implements MarketEvidenceProviderAdapter{ descriptor=getProviderDescriptor('public_regulatory_filings')??(()=>{throw new Error('missing_regulatory_liquidity_descriptor')})();
async fetch(request:ProviderSourceRequest): Promise<ProviderSourceResponse> { if(!SUPPORTED.has(request.capability)) return {...base(request),status:'unsupported',errorCode:'unsupported_capability',errorMessage:`Unsupported capability: ${request.capability}`}; const fixture={...REGULATORY_LIQUIDITY_FIXTURE,request:{providerId:request.providerId,region:request.region,institution:request.asset,capability:request.capability as never,requestedAt:request.requestedAt}}; return {...base(request),status:'success',sourceUrl:`fixture://regulatory-liquidity/${request.capability}`,rawPayloadJson:JSON.stringify(fixture),errorCode:null,errorMessage:null}; }
async normalize(response:ProviderSourceResponse){ if(!response.rawPayloadJson) throw new Error('regulatory_liquidity_missing_payload'); const parsed=JSON.parse(response.rawPayloadJson) as typeof REGULATORY_LIQUIDITY_FIXTURE; if(response.capability==='stress_test_result') return parsed.stressTestRows.map((x)=>buildStressTestPayload(parsed.request,x)); if(response.capability==='institutional_liquidity_report') return parsed.institutionalLiquidityRows.map((x)=>buildInstitutionalLiquidityPayload(parsed.request,x)); if(response.capability==='bank_health_metric'||response.capability==='regulatory_filing_reference') return parsed.filingRows.map((x)=>buildRegulatoryFilingPayload(parsed.request,x)); return []; }
}
