import type { ProviderAdmissionDecision,ProviderAdmissionRequest,ProviderControlSnapshot,ProviderControlStore,ProviderExecutionClaim,ProviderReservation,ProviderReservationStatus } from './contracts';
import { providerControlCoordinationTag,providerControlScopeTag } from './keys';
import { validateProviderControlPolicy } from './policy';
type State={tokens:number;lastRefill:number;quotaWindow:number;quotaUsed:number;costWindow:number;reserved:number;committed:number;leases:Map<string,number>};
type Stored={reservation:ProviderReservation;expiresAt:number};
export class MemoryProviderControlStore implements ProviderControlStore {
  readonly kind='memory' as const; private states=new Map<string,State>(); private admissions=new Map<string,Stored>(); private chain=Promise.resolve();
  constructor(private readonly clock:()=>number=()=>Date.now(),private readonly tombstoneTtlMs=60_000){}
  isReady(){return true;} async close(){}
  private serialize<T>(fn:()=>T|Promise<T>):Promise<T>{const next=this.chain.then(fn,fn);this.chain=next.then(()=>undefined,()=>undefined);return next;}
  private cleanup(now:number){for(const [key,value] of this.admissions)if(value.expiresAt<=now)this.admissions.delete(key);}
  admissionCount(){this.cleanup(this.clock());return this.admissions.size;}
  async admit(request:ProviderAdmissionRequest):Promise<ProviderAdmissionDecision>{return this.serialize(()=>{
    const now=this.clock();this.cleanup(now);validateProviderControlPolicy(request.policy,now);const p=request.policy,key=providerControlScopeTag(p),admissionKey=`${providerControlCoordinationTag(p)}:${request.admissionId}`;
    const prior=this.admissions.get(admissionKey);if(prior){const r=prior.reservation;if(r.fingerprint!==request.fingerprint||r.policyHash!==p.canonicalPolicyHash||r.requestId!==request.requestId)return {allowed:false,reason:'provider_control_idempotency_conflict',retryAfterMs:0};if(r.status==='EXECUTING')return {allowed:false,reason:'provider_control_admission_in_progress',retryAfterMs:0};if(r.status!=='RESERVED')return {allowed:false,reason:'provider_control_admission_already_settled',retryAfterMs:0};return {allowed:true,reason:'provider_control_admitted',reused:true,reservation:r};}
    let s=this.states.get(key);if(!s){s={tokens:p.rate.capacity,lastRefill:now,quotaWindow:0,quotaUsed:0,costWindow:0,reserved:0,committed:0,leases:new Map()};this.states.set(key,s);}
    const steps=Math.floor((now-s.lastRefill)/p.rate.refillIntervalMs);if(steps>0){s.tokens=Math.min(p.rate.capacity,s.tokens+steps*p.rate.refillAmount);s.lastRefill+=steps*p.rate.refillIntervalMs;}
    const qw=p.quota?Math.floor(now/p.quota.windowMs)*p.quota.windowMs:0,cw=Math.floor(now/p.cost.windowMs)*p.cost.windowMs;if(s.quotaWindow!==qw){s.quotaWindow=qw;s.quotaUsed=0;}if(s.costWindow!==cw){s.costWindow=cw;s.reserved=0;s.committed=0;}for(const [owner,expiry] of s.leases)if(expiry<=now)s.leases.delete(owner);
    const snapshot=():ProviderControlSnapshot=>({scope:{sourceId:p.sourceId,capabilityId:p.capabilityId,credentialPoolId:p.credentialPoolId,policyVersion:p.policyVersion},rate:{capacity:p.rate.capacity,remaining:s!.tokens,retryAfterMs:s!.tokens>=p.rate.requestTokens?0:Math.ceil((p.rate.requestTokens-s!.tokens)/p.rate.refillAmount)*p.rate.refillIntervalMs},quota:p.quota?{limit:p.quota.limit,used:s!.quotaUsed,remaining:p.quota.limit-s!.quotaUsed,windowStart:qw,windowEnd:qw+p.quota.windowMs,resetAt:qw+p.quota.windowMs}:null,cost:{limit:p.cost.budgetUnits,reserved:s!.reserved,committed:s!.committed,remaining:p.cost.budgetUnits-s!.reserved-s!.committed,windowStart:cw,windowEnd:cw+p.cost.windowMs},concurrency:{limit:p.concurrency.maxConcurrent,active:s!.leases.size,leaseExpiresAt:now+p.concurrency.leaseDurationMs}});
    if(s.tokens<p.rate.requestTokens)return {allowed:false,reason:'provider_rate_exhausted',retryAfterMs:snapshot().rate.retryAfterMs,snapshot:snapshot()};if(p.quota&&s.quotaUsed>=p.quota.limit)return {allowed:false,reason:'provider_quota_exhausted',retryAfterMs:qw+p.quota.windowMs-now,snapshot:snapshot()};if(s.reserved+s.committed+p.cost.requestCostUnits>p.cost.budgetUnits)return {allowed:false,reason:'provider_cost_exhausted',retryAfterMs:cw+p.cost.windowMs-now,snapshot:snapshot()};if(s.leases.size>=p.concurrency.maxConcurrent)return {allowed:false,reason:'provider_concurrency_exhausted',retryAfterMs:Math.max(0,Math.min(...s.leases.values())-now),snapshot:snapshot()};
    s.tokens-=p.rate.requestTokens;s.quotaUsed+=p.quota?1:0;s.reserved+=p.cost.requestCostUnits;s.leases.set(request.ownerToken,now+p.concurrency.leaseDurationMs);
    const reservation:ProviderReservation={admissionId:request.admissionId,reservationId:request.reservationId,requestId:request.requestId,fingerprint:request.fingerprint,policyHash:p.canonicalPolicyHash,ownerToken:request.ownerToken,status:'RESERVED',costUnits:p.cost.requestCostUnits,rateTokens:p.rate.requestTokens,quotaUnits:p.quota?1:0,quotaWindowStart:qw,costWindowStart:cw,leaseDurationMs:p.concurrency.leaseDurationMs,snapshot:snapshot()};this.admissions.set(admissionKey,{reservation,expiresAt:now+Math.max(p.cost.windowMs,p.quota?.windowMs??0,p.concurrency.leaseDurationMs)*2});return {allowed:true,reason:'provider_control_admitted',reused:false,reservation};
  });}
  async claimExecution(reservation:ProviderReservation,executionToken:string):Promise<ProviderExecutionClaim>{return this.serialize(()=>{const now=this.clock(),key=providerControlScopeTag(reservation.snapshot.scope),stored=this.admissions.get(`${providerControlCoordinationTag(reservation.snapshot.scope)}:${reservation.admissionId}`),state=this.states.get(key);if(!stored||stored.reservation.reservationId!==reservation.reservationId)return {claimed:false,reason:'provider_control_admission_already_settled'};if(stored.reservation.status==='EXECUTING')return {claimed:false,reason:'provider_control_admission_in_progress'};if(stored.reservation.status!=='RESERVED')return {claimed:false,reason:'provider_control_admission_already_settled'};if(!state||!state.leases.has(stored.reservation.ownerToken)||(state.leases.get(stored.reservation.ownerToken)??0)<=now){if(state){if(state.tokens!==undefined)state.tokens=Math.min(stored.reservation.snapshot.rate.capacity,state.tokens+stored.reservation.rateTokens);if(state.quotaWindow===stored.reservation.quotaWindowStart)state.quotaUsed=Math.max(0,state.quotaUsed-stored.reservation.quotaUnits);if(state.costWindow===stored.reservation.costWindowStart)state.reserved=Math.max(0,state.reserved-stored.reservation.costUnits);state.leases.delete(stored.reservation.ownerToken);}stored.reservation={...stored.reservation,status:'RELEASED'};stored.expiresAt=now+this.tombstoneTtlMs;return {claimed:false,reason:'provider_control_lease_expired'};}const executionLeaseExpiresAt=now+stored.reservation.leaseDurationMs;state.leases.set(stored.reservation.ownerToken,executionLeaseExpiresAt);stored.reservation={...stored.reservation,status:'EXECUTING',executionToken,claimedAt:now,executionLeaseExpiresAt,snapshot:{...stored.reservation.snapshot,concurrency:{...stored.reservation.snapshot.concurrency,leaseExpiresAt:executionLeaseExpiresAt}}};return {claimed:true,reservation:stored.reservation};});}
  async settle(reservation:ProviderReservation,status:Exclude<ProviderReservationStatus,'RESERVED'|'EXECUTING'>):Promise<boolean>{return this.serialize(()=>{const now=this.clock(),key=providerControlScopeTag(reservation.snapshot.scope),stored=this.admissions.get(`${providerControlCoordinationTag(reservation.snapshot.scope)}:${reservation.admissionId}`);if(!stored||stored.reservation.reservationId!==reservation.reservationId||stored.reservation.ownerToken!==reservation.ownerToken||stored.reservation.status!=='EXECUTING'||stored.reservation.executionToken!==reservation.executionToken)return false;const s=this.states.get(key);if(!s)return false;s.leases.delete(reservation.ownerToken);if(status==='RELEASED'){s.tokens=Math.min(reservation.snapshot.rate.capacity,s.tokens+reservation.rateTokens);if(s.quotaWindow===reservation.quotaWindowStart)s.quotaUsed=Math.max(0,s.quotaUsed-reservation.quotaUnits);if(s.costWindow===reservation.costWindowStart)s.reserved=Math.max(0,s.reserved-reservation.costUnits);}else if(s.costWindow===reservation.costWindowStart){s.reserved=Math.max(0,s.reserved-reservation.costUnits);s.committed+=reservation.costUnits;}stored.reservation.status=status;stored.expiresAt=now+this.tombstoneTtlMs;return true;});}
}
