import { createClient, type RedisClientType } from 'redis';
import type { ProviderAdmissionDecision,ProviderAdmissionRequest,ProviderControlStore,ProviderReservation,ProviderReservationStatus } from './contracts';
import { providerControlKeys } from './keys';
import { validateProviderControlPolicy } from './policy';

const ADMIT=`
local t=redis.call('TIME'); local now=tonumber(t[1])*1000+math.floor(tonumber(t[2])/1000)
local cap=tonumber(ARGV[1]); local refill=tonumber(ARGV[2]); local interval=tonumber(ARGV[3]); local tokenCost=tonumber(ARGV[4]); local quotaLimit=tonumber(ARGV[5]); local quotaWindow=tonumber(ARGV[6]); local budget=tonumber(ARGV[7]); local costWindow=tonumber(ARGV[8]); local requestCost=tonumber(ARGV[9]); local maxConcurrent=tonumber(ARGV[10]); local leaseMs=tonumber(ARGV[11]); local owner=ARGV[12]; local reservation=ARGV[13]
local tokens=tonumber(redis.call('HGET',KEYS[1],'tokens') or cap); local last=tonumber(redis.call('HGET',KEYS[1],'last') or now); local steps=math.floor((now-last)/interval); if steps>0 then tokens=math.min(cap,tokens+steps*refill); last=last+steps*interval end
local qw=quotaWindow>0 and math.floor(now/quotaWindow)*quotaWindow or 0; local storedQw=tonumber(redis.call('HGET',KEYS[2],'window') or qw); local used=tonumber(redis.call('HGET',KEYS[2],'used') or 0); if storedQw~=qw then used=0 end
local cw=math.floor(now/costWindow)*costWindow; local storedCw=tonumber(redis.call('HGET',KEYS[3],'window') or cw); local reserved=tonumber(redis.call('HGET',KEYS[3],'reserved') or 0); local committed=tonumber(redis.call('HGET',KEYS[3],'committed') or 0); if storedCw~=cw then reserved=0;committed=0 end
redis.call('ZREMRANGEBYSCORE',KEYS[4],'-inf',now); local active=redis.call('ZCARD',KEYS[4]); local reason=''; local retry=0
if tokens<tokenCost then reason='provider_rate_exhausted';retry=math.ceil((tokenCost-tokens)/refill)*interval elseif quotaLimit>0 and used>=quotaLimit then reason='provider_quota_exhausted';retry=qw+quotaWindow-now elseif reserved+committed+requestCost>budget then reason='provider_cost_exhausted';retry=cw+costWindow-now elseif active>=maxConcurrent then reason='provider_concurrency_exhausted';local first=redis.call('ZRANGE',KEYS[4],0,0,'WITHSCORES');if #first>1 then retry=math.max(0,tonumber(first[2])-now) end end
if reason~='' then return cjson.encode({allowed=false,reason=reason,retryAfterMs=retry,rateRemaining=tokens,quotaUsed=used,reserved=reserved,committed=committed,active=active,now=now,qw=qw,cw=cw}) end
tokens=tokens-tokenCost;used=used+(quotaLimit>0 and 1 or 0);reserved=reserved+requestCost;redis.call('HSET',KEYS[1],'tokens',tokens,'last',last);redis.call('PEXPIRE',KEYS[1],math.max(interval*math.ceil(cap/refill)*2,interval));if quotaLimit>0 then redis.call('HSET',KEYS[2],'window',qw,'used',used);redis.call('PEXPIREAT',KEYS[2],qw+quotaWindow+60000) end;redis.call('HSET',KEYS[3],'window',cw,'reserved',reserved,'committed',committed);redis.call('PEXPIREAT',KEYS[3],cw+costWindow+60000);redis.call('ZADD',KEYS[4],now+leaseMs,owner);redis.call('PEXPIRE',KEYS[4],leaseMs*2);redis.call('HSET',KEYS[5],reservation,cjson.encode({owner=owner,cost=requestCost,status='RESERVED'}));redis.call('PEXPIRE',KEYS[5],math.max(costWindow,leaseMs)*2)
return cjson.encode({allowed=true,now=now,rateRemaining=tokens,quotaUsed=used,reserved=reserved,committed=committed,active=active+1,qw=qw,cw=cw})`;
const SETTLE=`local raw=redis.call('HGET',KEYS[2],ARGV[1]);if not raw then return 0 end;local r=cjson.decode(raw);if r.owner~=ARGV[2] or r.status~='RESERVED' then return 0 end;redis.call('ZREM',KEYS[1],ARGV[2]);local reserved=tonumber(redis.call('HGET',KEYS[3],'reserved') or 0);local committed=tonumber(redis.call('HGET',KEYS[3],'committed') or 0);redis.call('HSET',KEYS[3],'reserved',math.max(0,reserved-r.cost));if ARGV[3]~='RELEASED' then redis.call('HSET',KEYS[3],'committed',committed+r.cost) end;r.status=ARGV[3];redis.call('HSET',KEYS[2],ARGV[1],cjson.encode(r));return 1`;
type Raw={allowed:boolean;reason?:ProviderAdmissionDecision extends {allowed:false;reason:infer R}?R:string;retryAfterMs?:number;rateRemaining:number;quotaUsed:number;reserved:number;committed:number;active:number;now:number;qw:number;cw:number};
export function createProviderControlRedisClient():RedisClientType { const url=process.env.REDIS_URL;if(!url)throw new Error('provider_control_unavailable');return createClient({url,socket:{connectTimeout:3000,reconnectStrategy:(retries)=>retries<3?Math.min(100*2**retries,1000):false}}) as RedisClientType; }
export class RedisProviderControlStore implements ProviderControlStore { readonly kind='redis' as const; private ready=false; private connecting:Promise<unknown>|undefined; constructor(private client:RedisClientType,private namespace='elceo:provider-control:v1',private timeoutMs=3000){} isReady(){return this.ready&&this.client.isReady;} private async bounded<T>(p:Promise<T>):Promise<T>{let timer:NodeJS.Timeout;try{return await Promise.race([p,new Promise<T>((_,reject)=>{timer=setTimeout(()=>reject(new Error('provider_control_command_timeout')),this.timeoutMs)})]);}finally{clearTimeout(timer!);}} private async ensure(){if(this.connecting)await this.connecting;if(!this.client.isOpen){this.connecting=this.bounded(this.client.connect()).finally(()=>{this.connecting=undefined;});await this.connecting;}this.ready=this.client.isReady;if(!this.ready)throw new Error('provider_control_unavailable');}
  async admit(request:ProviderAdmissionRequest):Promise<ProviderAdmissionDecision>{try{validateProviderControlPolicy(request.policy);await this.ensure();const p=request.policy,k=providerControlKeys(p,this.namespace);const raw=JSON.parse(String(await this.bounded(this.client.eval(ADMIT,{keys:[k.rate,k.quota,k.cost,k.leases,k.reservations],arguments:[p.rate.capacity,p.rate.refillAmount,p.rate.refillIntervalMs,p.rate.requestTokens,p.quota?.limit??0,p.quota?.windowMs??0,p.cost.budgetUnits,p.cost.windowMs,p.cost.requestCostUnits,p.concurrency.maxConcurrent,p.concurrency.leaseDurationMs,request.ownerToken,request.requestId].map(String)})))) as Raw;const snapshot={scope:{sourceId:p.sourceId,capabilityId:p.capabilityId,credentialPoolId:p.credentialPoolId,policyVersion:p.policyVersion},rate:{capacity:p.rate.capacity,remaining:raw.rateRemaining,retryAfterMs:raw.retryAfterMs??0},quota:p.quota?{limit:p.quota.limit,used:raw.quotaUsed,remaining:p.quota.limit-raw.quotaUsed,windowStart:raw.qw,windowEnd:raw.qw+p.quota.windowMs,resetAt:raw.qw+p.quota.windowMs}:null,cost:{limit:p.cost.budgetUnits,reserved:raw.reserved,committed:raw.committed,remaining:p.cost.budgetUnits-raw.reserved-raw.committed,windowStart:raw.cw,windowEnd:raw.cw+p.cost.windowMs},concurrency:{limit:p.concurrency.maxConcurrent,active:raw.active,leaseExpiresAt:raw.now+p.concurrency.leaseDurationMs}};if(!raw.allowed)return {allowed:false,reason:raw.reason as never,retryAfterMs:raw.retryAfterMs??0,snapshot};return {allowed:true,reason:'provider_control_admitted',reservation:{reservationId:request.requestId,ownerToken:request.ownerToken,status:'RESERVED',costUnits:p.cost.requestCostUnits,snapshot}};}catch{return {allowed:false,reason:'provider_control_unavailable',retryAfterMs:0};}}
  async settle(r:ProviderReservation,status:Exclude<ProviderReservationStatus,'RESERVED'>):Promise<boolean>{try{await this.ensure();const k=providerControlKeys(r.snapshot.scope,this.namespace);return Number(await this.bounded(this.client.eval(SETTLE,{keys:[k.leases,k.reservations,k.cost],arguments:[r.reservationId,r.ownerToken,status]})))===1;}catch{return false;}}
  async close(){this.ready=false;if(this.client.isOpen)await this.client.quit();}
}
