import { randomUUID } from 'node:crypto';
import type { SuperAdminCommercialAuditEvent, SuperAdminCommercialControlCoverageReport, SuperAdminCommercialControlSnapshot, SuperAdminFocusPlanGiftRecord, SuperAdminFocusPlanGiftRequest, SuperAdminFocusPlanGiftResult, SuperAdminRetractGiftRequest, SuperAdminRetractGiftResult, SuperAdminStepUpChallengeRequest, SuperAdminStepUpCoverageReport, SuperAdminStepUpProviderReadinessReport, SuperAdminStepUpReadinessState, SuperAdminStepUpVerification, SuperAdminStepUpVerificationRequest, SuperAdminStepUpVerificationResult, SuperAdminUserRestrictionResult } from '@elceo/types';
import { validateSuperAdminFocusPlanGiftRequest, validateSuperAdminRetractGiftRequest, validateSuperAdminStepUpChallengeRequest, validateSuperAdminStepUpVerification, validateSuperAdminStepUpVerificationRequest, validateSuperAdminUserRestrictionRequest } from '@elceo/schemas';
import { MemorySuperAdminStepUpRepository, SQLSuperAdminStepUpRepository, isStepUpPersistenceError, StepUpPersistenceError, type ProviderDisposition, type StepUpPersistenceStatus, type StepUpPolicy, type SuperAdminStepUpRepository } from '../persistence/super-admin-step-up-repository';

import { createCommercialPriceVersion } from '../commercial-pricing';
import { getDefaultSuperAdminCommercialRepository, resetSuperAdminCommercialRepositoryForTests, evaluateCommercialEntitlementFromControls } from '../persistence/super-admin-commercial-repository';
import { isCommercialPersistenceError } from '../persistence/commercial-persistence-error';
const runtimeEnv = () => (globalThis as { process?: { env?: Record<string, string | undefined> } }).process?.env ?? {};
const useSql = () => runtimeEnv().APP_STATE_REPOSITORY === 'sql' && Boolean(runtimeEnv().DATABASE_URL);
export const stepUpPolicy: StepUpPolicy = { freshnessSeconds: 10 * 60, challengeExpirySeconds: 5 * 60, maxAttemptsPerChallenge: 5, maxChallengesPerWindow: 10, windowSeconds: 10 * 60, lockoutSeconds: 15 * 60 };
export const SUPER_ADMIN_COMMERCIAL_ACTION_ROUTES = { focus_plan_gift: '/api/admin/commercial/users/[userId]/gift-focus-plan', focus_plan_gift_retract: '/api/admin/commercial/users/[userId]/retract-focus-gift', user_restriction: '/api/admin/commercial/users/[userId]/restrict', focus_plan_price_update:'/api/admin/commercial/prices' } as const;
export type SuperAdminCommercialActionKind = keyof typeof SUPER_ADMIN_COMMERCIAL_ACTION_ROUTES;
export const getSuperAdminCommercialRouteScope = (actionKind: SuperAdminCommercialActionKind) => SUPER_ADMIN_COMMERCIAL_ACTION_ROUTES[actionKind];
export const isSuperAdminCommercialActionKind = (value: unknown): value is SuperAdminCommercialActionKind => typeof value === 'string' && Object.prototype.hasOwnProperty.call(SUPER_ADMIN_COMMERCIAL_ACTION_ROUTES, value);
export const validateSuperAdminStepUpVerificationInput = (input: unknown) => validateSuperAdminStepUpVerification(input);
export const assertSuperAdminStepUpVerified = (input: SuperAdminStepUpVerification) => { if (input.status !== 'verified') throw new Error('super_admin_step_up_required'); return input; };
export const evaluateSuperAdminGrantedEntitlement = (input: { subscriptionActive: boolean; gift: SuperAdminFocusPlanGiftRecord | null; nowIso: string; restricted: boolean }): 'focus_plan_active' | 'subscription_required' | 'restricted' => { if (input.restricted) return 'restricted'; if (input.subscriptionActive) return 'focus_plan_active'; if (!input.gift || input.gift.status !== 'active') return 'subscription_required'; return new Date(input.nowIso).getTime() < new Date(input.gift.endsAt).getTime() ? 'focus_plan_active' : 'subscription_required'; };
export const buildSuperAdminCommercialAuditEvent = (input: SuperAdminCommercialAuditEvent) => input;
export const getSuperAdminStepUpReadinessReport = (): SuperAdminStepUpProviderReadinessReport[] => [
  { providerKind: 'totp', readiness: 'provider_pending', activated: false, notes: 'Provider integration not configured.' }, { providerKind: 'webauthn_passkey', readiness: 'provider_pending', activated: false, notes: 'Provider integration not configured.' }, { providerKind: 'authenticator_app', readiness: 'provider_pending', activated: false, notes: 'Provider integration not configured.' }, { providerKind: 'verified_email_fallback', readiness: 'readiness_only', activated: false, notes: 'Fallback policy only; no notification dispatch activation.' }, { providerKind: 'fixture_test_only', readiness: 'fixture_test_only', activated: runtimeEnv().NODE_ENV !== 'production', notes: 'Test-mode only fixture verification.' }
];
const isFixturePermitted = () => runtimeEnv().NODE_ENV !== 'production' && (runtimeEnv().NODE_ENV === 'test' || runtimeEnv().ELCEO_ENABLE_FIXTURE_STEP_UP === '1');
const nowIso = () => new Date().toISOString();

let defaultRepo: SuperAdminStepUpRepository | null = null;
const persistenceUnavailable = () => new StepUpPersistenceError();
export function buildDefaultSuperAdminStepUpRepository(): SuperAdminStepUpRepository {
  const env = runtimeEnv();
  if (env.NODE_ENV === 'production' && (env.APP_STATE_REPOSITORY !== 'sql' || !env.DATABASE_URL)) throw persistenceUnavailable();
  if (env.APP_STATE_REPOSITORY === 'sql') { if (!env.DATABASE_URL) throw persistenceUnavailable(); return new SQLSuperAdminStepUpRepository(); }
  if (env.NODE_ENV === 'production') throw persistenceUnavailable();
  return new MemorySuperAdminStepUpRepository();
}
const getDefaultRepo = () => (defaultRepo ??= buildDefaultSuperAdminStepUpRepository());
export const resetSuperAdminStepUpServiceForTests = () => { defaultRepo = null; };

export class SuperAdminStepUpService {
  constructor(private readonly repository: SuperAdminStepUpRepository, private readonly ids: { challengeId: () => string } = { challengeId: () => `stepup_${randomUUID()}` }) {}
  async createChallenge(input: SuperAdminStepUpChallengeRequest) { const r = validateSuperAdminStepUpChallengeRequest(input); if (!r.ok) throw new Error('invalid_step_up_challenge_request'); const out = await this.repository.createChallengeAtomically({ ...r.value, challengeId: this.ids.challengeId(), nowIso: r.value.requestedAt, policy: stepUpPolicy, fixturePermitted: isFixturePermitted() }); if (out.status === 'denied') { if (out.reason === 'fixture_forbidden') throw new Error('fixture_provider_forbidden'); throw new Error(out.reason); } return { ...out.challenge, persistenceStatus: out.persistenceStatus }; }
  async verify(input: SuperAdminStepUpVerificationRequest): Promise<SuperAdminStepUpVerificationResult> { const r = validateSuperAdminStepUpVerificationRequest(input); if (!r.ok) return { status: 'failed', verified: false, failureReason: 'invalid_proof', challengeId: String((input as { challengeId?: unknown }).challengeId ?? ''), providerKind: 'fixture_test_only', verifiedAt: null, freshUntil: null, persistenceStatus: this.status() }; const disposition: ProviderDisposition = r.value.providerKind !== 'fixture_test_only' ? 'provider_pending' : (!isFixturePermitted() ? 'fixture_forbidden' : (r.value.proof === 'fixture-pass' ? 'accepted' : 'rejected')); return this.repository.applyVerificationAttemptAtomically({ challengeId: r.value.challengeId, actorUserId: r.value.actorUserId, providerKind: r.value.providerKind, nowIso: r.value.requestedAt, disposition, policy: stepUpPolicy }) as Promise<SuperAdminStepUpVerificationResult>; }
  async consume(input: { challengeId: string; actorUserId: string; expectedActionKind: SuperAdminCommercialActionKind; expectedRouteScope: string; expectedTargetUserId: string | null; nowIso: string }) { const out = await this.repository.consumeVerifiedChallengeAtomically({ ...input, fixturePermitted: isFixturePermitted() }); if (out.status !== 'consumed') { if (out.reason === 'actor_locked') throw new Error('step_up_actor_locked'); if (out.reason === 'challenge_expired') throw new Error('challenge_expired'); throw new Error('step_up_verification_failed'); } return { status: 'verified' as const, challengeId: input.challengeId, providerKind: out.providerKind! }; }
  async readiness() { return this.repository.getPersistenceReadiness(); }
  status(): StepUpPersistenceStatus { try { const env = runtimeEnv(); if (env.NODE_ENV === 'production' && (env.APP_STATE_REPOSITORY !== 'sql' || !env.DATABASE_URL)) return 'unavailable'; return env.APP_STATE_REPOSITORY === 'sql' ? (env.DATABASE_URL ? 'durable' : 'unavailable') : 'memory_fallback'; } catch { return 'unavailable'; } }
}

const getDefaultService = () => new SuperAdminStepUpService(getDefaultRepo());
export const createSuperAdminStepUpChallenge = (input: SuperAdminStepUpChallengeRequest) => getDefaultService().createChallenge(input);
export const verifySuperAdminStepUpChallenge = (input: SuperAdminStepUpVerificationRequest) => getDefaultService().verify(input);
export const detectSuperAdminStepUpReplay = () => false;
export const assertSuperAdminStepUpFresh = async (input: { challengeId: string; nowIso: string }) => { const c = await getDefaultRepo().getChallengeById(input.challengeId); if (!c || c.status !== 'verified' || !c.freshUntil || new Date(input.nowIso).getTime() >= new Date(c.freshUntil).getTime()) throw new Error('super_admin_step_up_stale'); };
export const consumeVerifiedSuperAdminStepUpChallenge = (input: { challengeId: string; actorUserId: string; expectedActionKind: SuperAdminCommercialActionKind; expectedRouteScope: string; expectedTargetUserId: string; nowIso: string }) => getDefaultService().consume(input);
export const buildSuperAdminStepUpAuditEvent = (input: { actorUserId: string; action: string; targetUserId: string | null; challengeId: string; providerKind: string; verificationStatus: string; failureReason: string | null; routeScope: string }) => ({ ...input, timestamp: nowIso(), redactionStatus: 'safe' as const });
export const buildSuperAdminStepUpCoverageReport = (persistenceStatus: StepUpPersistenceStatus): SuperAdminStepUpCoverageReport => ({ generatedAt: nowIso(), persistenceStatus, freshnessWindow: { maxAgeSeconds: stepUpPolicy.freshnessSeconds }, replayProtection: { enforceSingleUse: true }, rateLimitPolicy: { maxChallengesPerWindow: stepUpPolicy.maxChallengesPerWindow, windowSeconds: stepUpPolicy.windowSeconds }, lockoutPolicy: { maxAttemptsPerChallenge: stepUpPolicy.maxAttemptsPerChallenge, lockoutSeconds: stepUpPolicy.lockoutSeconds }, recoveryPolicy: { mode: 'manual_super_admin_reset_only', notes: 'Manual reset only while provider is pending.' }, providerReadiness: getSuperAdminStepUpReadinessReport() });
export const getSuperAdminStepUpCoverageReport = async (): Promise<SuperAdminStepUpCoverageReport> => { const readiness = await getSuperAdminStepUpPersistenceReadiness(); return buildSuperAdminStepUpCoverageReport(readiness.persistenceStatus); };
export const getSuperAdminStepUpPersistenceReadiness = async () => { try { return await getDefaultService().readiness(); } catch { return { selectedRepositoryMode: runtimeEnv().APP_STATE_REPOSITORY === 'sql' ? 'sql' as const : 'unavailable' as const, databaseConfigured: Boolean(runtimeEnv().DATABASE_URL), requiredRelationsAvailable: false, persistenceStatus: 'unavailable' as const }; } };

function commercialPersistenceStatus(): 'durable' | 'memory_fallback' | 'unavailable' { const env = runtimeEnv(); if (env.NODE_ENV === 'production' && (env.APP_STATE_REPOSITORY !== 'sql' || !env.DATABASE_URL)) return 'unavailable'; return useSql() ? 'durable' : 'memory_fallback'; }
function blockedCommercial(reason: 'step_up_required' | 'step_up_persistence_unavailable' | 'commercial_persistence_unavailable', fallback: 'subscription_required' | 'restricted'): any { return { status: 'blocked' as const, failureReason: reason, giftRecord: null, restrictionRecord: null, resultingEntitlementState: fallback, persistenceStatus: reason === 'commercial_persistence_unavailable' ? 'unavailable' as const : commercialPersistenceStatus() }; }
async function consumeForCommercial(input: { challengeId: string; actorSuperAdminId: string; targetUserId: string; actionKind: SuperAdminCommercialActionKind; requestedAt: string }) { return consumeVerifiedSuperAdminStepUpChallenge({ challengeId: input.challengeId, actorUserId: input.actorSuperAdminId, expectedActionKind: input.actionKind, expectedRouteScope: getSuperAdminCommercialRouteScope(input.actionKind), expectedTargetUserId: input.targetUserId, nowIso: input.requestedAt }); }

export async function giftFocusPlanToUser(input: SuperAdminFocusPlanGiftRequest): Promise<SuperAdminFocusPlanGiftResult & { persistenceStatus: 'durable' | 'memory_fallback' | 'unavailable' }> { const r = validateSuperAdminFocusPlanGiftRequest(input); if (!r.ok) return blockedCommercial('step_up_required', 'subscription_required'); try { await consumeForCommercial({ challengeId: r.value.stepUpChallengeId, actorSuperAdminId: r.value.actorSuperAdminId, targetUserId: r.value.targetUserId, actionKind: 'focus_plan_gift', requestedAt: r.value.requestedAt }); return await getDefaultSuperAdminCommercialRepository().createFocusPlanGiftAtomically(r.value) as never; } catch (e) { return blockedCommercial(isStepUpPersistenceError(e) ? 'step_up_persistence_unavailable' : (isCommercialPersistenceError(e) ? 'commercial_persistence_unavailable' : 'step_up_required'), 'subscription_required'); } }
export async function retractFocusPlanGift(input: SuperAdminRetractGiftRequest): Promise<SuperAdminRetractGiftResult & { persistenceStatus: 'durable' | 'memory_fallback' | 'unavailable' }> { const r = validateSuperAdminRetractGiftRequest(input); if (!r.ok) return blockedCommercial('step_up_required', 'subscription_required'); try { await consumeForCommercial({ challengeId: r.value.stepUpChallengeId, actorSuperAdminId: r.value.actorSuperAdminId, targetUserId: r.value.targetUserId, actionKind: 'focus_plan_gift_retract', requestedAt: r.value.requestedAt }); return await getDefaultSuperAdminCommercialRepository().retractFocusPlanGiftAtomically(r.value) as never; } catch (e) { return blockedCommercial(isStepUpPersistenceError(e) ? 'step_up_persistence_unavailable' : (isCommercialPersistenceError(e) ? 'commercial_persistence_unavailable' : 'step_up_required'), 'subscription_required'); } }
export async function restrictUserAccount(input: Parameters<typeof validateSuperAdminUserRestrictionRequest>[0]): Promise<SuperAdminUserRestrictionResult & { persistenceStatus: 'durable' | 'memory_fallback' | 'unavailable' }> { const r = validateSuperAdminUserRestrictionRequest(input); if (!r.ok) return blockedCommercial('step_up_required', 'restricted') as never; try { await consumeForCommercial({ challengeId: r.value.stepUpChallengeId, actorSuperAdminId: r.value.actorSuperAdminId, targetUserId: r.value.targetUserId, actionKind: 'user_restriction', requestedAt: r.value.requestedAt }); return await getDefaultSuperAdminCommercialRepository().createUserRestrictionAtomically(r.value) as never; } catch (e) { return blockedCommercial(isStepUpPersistenceError(e) ? 'step_up_persistence_unavailable' : (isCommercialPersistenceError(e) ? 'commercial_persistence_unavailable' : 'step_up_required'), 'restricted') as never; } }
export const getStepUpReadinessState = (): SuperAdminStepUpReadinessState => 'provider_pending';
export async function getSuperAdminCommercialControlSnapshot(targetUserId: string): Promise<SuperAdminCommercialControlSnapshot> { return getDefaultSuperAdminCommercialRepository().getControlSnapshot(targetUserId); }
export async function evaluateSuperAdminGrantedEntitlementForUser(input: { targetUserId: string; subscriptionActive: boolean; nowIso: string }) { const snapshot = await getDefaultSuperAdminCommercialRepository().getControlSnapshot(input.targetUserId, input.nowIso); return evaluateCommercialEntitlementFromControls(snapshot.activeGift, snapshot.activeRestrictionCount > 0, input.subscriptionActive, input.nowIso); }
export const resetSuperAdminCommercialControlsForTests = () => { resetSuperAdminStepUpServiceForTests(); resetSuperAdminCommercialRepositoryForTests(); };
export const getSuperAdminCommercialControlCoverageReport = (): SuperAdminCommercialControlCoverageReport => ({ generatedAt: new Date().toISOString(), supportsGiftDurations: ['two_weeks', 'one_month'], mandatoryStepUpRequired: true, ipBanSupported: false, paymentProviderCallsPerformed: false });

export async function updateFocusPlanPrice(input:{actorSuperAdminId:string;stepUpChallengeId:string;billingInterval:'monthly'|'quarterly'|'yearly';currency:string;amountMinor:string;effectiveFrom:string;reasonCode:string;operatorNote:string;idempotencyKey:string}){await consumeVerifiedSuperAdminStepUpChallenge({challengeId:input.stepUpChallengeId,actorUserId:input.actorSuperAdminId,expectedActionKind:'focus_plan_price_update',expectedRouteScope:getSuperAdminCommercialRouteScope('focus_plan_price_update'),expectedTargetUserId:input.actorSuperAdminId,nowIso:new Date().toISOString()});return createCommercialPriceVersion({...input,planCode:'focus_plan'});}
