import { randomUUID } from 'node:crypto';
import type { SuperAdminCommercialAuditEvent, SuperAdminCommercialControlCoverageReport, SuperAdminCommercialControlSnapshot, SuperAdminFocusPlanGiftRecord, SuperAdminFocusPlanGiftRequest, SuperAdminFocusPlanGiftResult, SuperAdminRetractGiftRequest, SuperAdminRetractGiftResult, SuperAdminStepUpChallengeRecord, SuperAdminStepUpChallengeRequest, SuperAdminStepUpCoverageReport, SuperAdminStepUpProviderReadinessReport, SuperAdminStepUpReadinessState, SuperAdminStepUpVerification, SuperAdminStepUpVerificationRequest, SuperAdminStepUpVerificationResult, SuperAdminUserRestrictionRecord, SuperAdminUserRestrictionResult } from '@elceo/types';
import { validateSuperAdminFocusPlanGiftRequest, validateSuperAdminRetractGiftRequest, validateSuperAdminStepUpChallengeRequest, validateSuperAdminStepUpVerification, validateSuperAdminStepUpVerificationRequest, validateSuperAdminUserRestrictionRequest } from '@elceo/schemas';
import { queryDb } from '../db/client';

const gifts = new Map<string, SuperAdminFocusPlanGiftRecord>();
const restrictions = new Map<string, SuperAdminUserRestrictionRecord>();
const challenges = new Map<string, SuperAdminStepUpChallengeRecord>();
const consumedProofs = new Set<string>();
const actorRate = new Map<string, string[]>();
const actorLockouts = new Map<string, string>();
const verifiedFreshness = new Map<string, string>();
const days = (d: number) => d * 24 * 60 * 60 * 1000;
const runtimeEnv = () => (globalThis as { process?: { env?: Record<string, string | undefined> } }).process?.env ?? {};
const useSql = () => runtimeEnv().APP_STATE_REPOSITORY === 'sql' && Boolean(runtimeEnv().DATABASE_URL);
const stepUpPolicy = { freshnessSeconds: 10 * 60, challengeExpirySeconds: 5 * 60, maxAttemptsPerChallenge: 5, maxChallengesPerWindow: 10, windowSeconds: 10 * 60, lockoutSeconds: 15 * 60 };

export const validateSuperAdminStepUpVerificationInput = (input: unknown) => validateSuperAdminStepUpVerification(input);
export const assertSuperAdminStepUpVerified = (input: SuperAdminStepUpVerification) => { if (input.status !== 'verified') throw new Error('super_admin_step_up_required'); return input; };
const buildGiftEnd = (start: string, d: 'two_weeks' | 'one_month') => new Date(new Date(start).getTime() + (d === 'two_weeks' ? days(14) : days(30))).toISOString();
export const evaluateSuperAdminGrantedEntitlement = (input: { subscriptionActive: boolean; gift: SuperAdminFocusPlanGiftRecord | null; nowIso: string; restricted: boolean }): 'focus_plan_active' | 'subscription_required' | 'restricted' => { if (input.restricted) return 'restricted'; if (input.subscriptionActive) return 'focus_plan_active'; if (!input.gift || input.gift.status !== 'active') return 'subscription_required'; return new Date(input.nowIso).getTime() < new Date(input.gift.endsAt).getTime() ? 'focus_plan_active' : 'subscription_required'; };
export const buildSuperAdminCommercialAuditEvent = (input: SuperAdminCommercialAuditEvent) => input;
export const getSuperAdminStepUpReadinessReport=():SuperAdminStepUpProviderReadinessReport[]=>[
  {providerKind:'totp',readiness:'provider_pending',activated:false,notes:'Provider integration not configured.'},
  {providerKind:'webauthn_passkey',readiness:'provider_pending',activated:false,notes:'Provider integration not configured.'},
  {providerKind:'authenticator_app',readiness:'provider_pending',activated:false,notes:'Provider integration not configured.'},
  {providerKind:'verified_email_fallback',readiness:'readiness_only',activated:false,notes:'Fallback policy only; no notification dispatch activation.'},
  {providerKind:'fixture_test_only',readiness:'fixture_test_only',activated:true,notes:'Test-mode only fixture verification.'}
];
const isTestMode=()=>runtimeEnv().NODE_ENV==='test' || runtimeEnv().ELCEO_ENABLE_FIXTURE_STEP_UP==='1';
const nowIso=()=>new Date().toISOString();
const locked=(actorUserId:string,at:string)=>{const until=actorLockouts.get(actorUserId); return until?new Date(until).getTime()>new Date(at).getTime():false;};
export function createSuperAdminStepUpChallenge(input: SuperAdminStepUpChallengeRequest){const r=validateSuperAdminStepUpChallengeRequest(input); if(!r.ok) throw new Error('invalid_step_up_challenge_request'); if(locked(input.actorUserId,input.requestedAt)) throw new Error('step_up_actor_locked'); const bucket=(actorRate.get(input.actorUserId)??[]).filter((x)=>new Date(x).getTime()>new Date(input.requestedAt).getTime()-stepUpPolicy.windowSeconds*1000); if(bucket.length>=stepUpPolicy.maxChallengesPerWindow) throw new Error('step_up_rate_limited'); bucket.push(input.requestedAt); actorRate.set(input.actorUserId,bucket); const challenge:SuperAdminStepUpChallengeRecord={challengeId:`stepup_${randomUUID()}`,actorUserId:input.actorUserId,actionKind:input.actionKind,routeScope:input.routeScope,targetUserId:input.targetUserId,providerKind:input.providerKind,status:'pending',createdAt:input.requestedAt,expiresAt:new Date(new Date(input.requestedAt).getTime()+stepUpPolicy.challengeExpirySeconds*1000).toISOString(),attemptCount:0,lastAttemptAt:null}; challenges.set(challenge.challengeId,challenge); return challenge;}
export const detectSuperAdminStepUpReplay=(input:{challengeId:string;proof:string})=>consumedProofs.has(`${input.challengeId}:${input.proof}`);
export function verifySuperAdminStepUpChallenge(input:SuperAdminStepUpVerificationRequest):SuperAdminStepUpVerificationResult{ const r=validateSuperAdminStepUpVerificationRequest(input); if(!r.ok) return {status:'failed',verified:false,failureReason:'invalid_proof',challengeId:String((input as {challengeId?:unknown}).challengeId??''),providerKind:'fixture_test_only',verifiedAt:null,freshUntil:null,persistenceStatus:'memory_fallback'}; const c=challenges.get(r.value.challengeId); if(!c) return {status:'failed',verified:false,failureReason:'challenge_not_found',challengeId:r.value.challengeId,providerKind:r.value.providerKind,verifiedAt:null,freshUntil:null,persistenceStatus:'memory_fallback'}; if(locked(r.value.actorUserId,r.value.requestedAt)) return {status:'locked',verified:false,failureReason:'actor_locked',challengeId:r.value.challengeId,providerKind:r.value.providerKind,verifiedAt:null,freshUntil:null,persistenceStatus:'memory_fallback'}; if(c.actorUserId!==r.value.actorUserId) return {status:'failed',verified:false,failureReason:'invalid_proof',challengeId:r.value.challengeId,providerKind:r.value.providerKind,verifiedAt:null,freshUntil:null,persistenceStatus:'memory_fallback'}; if(new Date(c.expiresAt).getTime()<new Date(r.value.requestedAt).getTime()) return {status:'expired',verified:false,failureReason:'challenge_expired',challengeId:r.value.challengeId,providerKind:r.value.providerKind,verifiedAt:null,freshUntil:null,persistenceStatus:'memory_fallback'}; if(c.status!=='pending') return {status:'replayed',verified:false,failureReason:'challenge_replayed',challengeId:r.value.challengeId,providerKind:r.value.providerKind,verifiedAt:null,freshUntil:null,persistenceStatus:'memory_fallback'}; if(detectSuperAdminStepUpReplay({challengeId:r.value.challengeId,proof:r.value.proof})) return {status:'replayed',verified:false,failureReason:'challenge_replayed',challengeId:r.value.challengeId,providerKind:r.value.providerKind,verifiedAt:null,freshUntil:null,persistenceStatus:'memory_fallback'};
 c.attemptCount+=1; c.lastAttemptAt=r.value.requestedAt;
 const providerPending=r.value.providerKind!=='fixture_test_only';
 const verified = !providerPending && isTestMode() && r.value.proof==='fixture-pass';
 if(!verified){ if(c.attemptCount>=stepUpPolicy.maxAttemptsPerChallenge){ c.status='locked'; actorLockouts.set(c.actorUserId,new Date(new Date(r.value.requestedAt).getTime()+stepUpPolicy.lockoutSeconds*1000).toISOString()); return {status:providerPending?'provider_pending':'locked',verified:false,failureReason:providerPending?'provider_pending':'max_attempts_exceeded',challengeId:c.challengeId,providerKind:r.value.providerKind,verifiedAt:null,freshUntil:null,persistenceStatus:'memory_fallback'}; } return {status:providerPending?'provider_pending':'failed',verified:false,failureReason:providerPending?'provider_pending':'invalid_proof',challengeId:c.challengeId,providerKind:r.value.providerKind,verifiedAt:null,freshUntil:null,persistenceStatus:'memory_fallback'}; }
 c.status='verified'; consumedProofs.add(`${c.challengeId}:${r.value.proof}`); const verifiedAt=r.value.requestedAt; const freshUntil=new Date(new Date(verifiedAt).getTime()+stepUpPolicy.freshnessSeconds*1000).toISOString(); verifiedFreshness.set(c.challengeId,freshUntil); return {status:'verified',verified:true,failureReason:null,challengeId:c.challengeId,providerKind:r.value.providerKind,verifiedAt,freshUntil,persistenceStatus:'memory_fallback'}; }
export const assertSuperAdminStepUpFresh=(input:{challengeId:string;nowIso:string})=>{const until=verifiedFreshness.get(input.challengeId); if(!until||new Date(until).getTime()<new Date(input.nowIso).getTime()) throw new Error('super_admin_step_up_stale');};
export const buildSuperAdminStepUpAuditEvent=(input:{actorUserId:string;action:string;targetUserId:string|null;challengeId:string;providerKind:string;verificationStatus:string;failureReason:string|null;routeScope:string})=>({ ...input,timestamp:nowIso(),redactionStatus:'safe' as const});
export const getSuperAdminStepUpCoverageReport=():SuperAdminStepUpCoverageReport=>({generatedAt:nowIso(),persistenceStatus:'memory_fallback',freshnessWindow:{maxAgeSeconds:stepUpPolicy.freshnessSeconds},replayProtection:{enforceSingleUse:true},rateLimitPolicy:{maxChallengesPerWindow:stepUpPolicy.maxChallengesPerWindow,windowSeconds:stepUpPolicy.windowSeconds},lockoutPolicy:{maxAttemptsPerChallenge:stepUpPolicy.maxAttemptsPerChallenge,lockoutSeconds:stepUpPolicy.lockoutSeconds},recoveryPolicy:{mode:'manual_super_admin_reset_only',notes:'Manual reset only while provider is pending.'},providerReadiness:getSuperAdminStepUpReadinessReport()});

export async function giftFocusPlanToUser(input: SuperAdminFocusPlanGiftRequest): Promise<SuperAdminFocusPlanGiftResult & { persistenceStatus: 'durable' | 'memory_fallback' }> {
  const r = validateSuperAdminFocusPlanGiftRequest(input); if (!r.ok) return { status: 'blocked', failureReason: 'unsupported_action', giftRecord: null, resultingEntitlementState: 'subscription_required', persistenceStatus: useSql() ? 'durable' : 'memory_fallback' };
  try { assertSuperAdminStepUpVerified(r.value.stepUpVerification); if (r.value.stepUpVerification.challengeId) assertSuperAdminStepUpFresh({ challengeId: r.value.stepUpVerification.challengeId, nowIso: input.requestedAt }); } catch { return { status: 'blocked', failureReason: 'step_up_required', giftRecord: null, resultingEntitlementState: 'subscription_required', persistenceStatus: useSql() ? 'durable' : 'memory_fallback' }; }
  const now = input.requestedAt;
  const giftRecord: SuperAdminFocusPlanGiftRecord = { giftRecordId: `gift_${randomUUID()}`, actorSuperAdminId: input.actorSuperAdminId, targetUserId: input.targetUserId, planCode: 'focus_plan', duration: input.duration, status: 'active', startsAt: now, endsAt: buildGiftEnd(now, input.duration), reasonCode: input.reasonCode, operatorNote: input.operatorNote, stepUpStatus: input.stepUpVerification.status, idempotencyKey: input.idempotencyKey, createdAt: now, updatedAt: now };
  if (useSql()) {
    await queryDb('INSERT INTO super_admin_focus_plan_gifts(gift_id,target_user_id,actor_user_id,status,duration,starts_at,ends_at,operator_note,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)', [giftRecord.giftRecordId, giftRecord.targetUserId, giftRecord.actorSuperAdminId, giftRecord.status, giftRecord.duration, giftRecord.startsAt, giftRecord.endsAt, giftRecord.operatorNote, giftRecord.createdAt, giftRecord.updatedAt]);
    return { status: 'success', failureReason: null, giftRecord, resultingEntitlementState: 'focus_plan_active', persistenceStatus: 'durable' };
  }
  gifts.set(giftRecord.giftRecordId, giftRecord);
  return { status: 'success', failureReason: null, giftRecord, resultingEntitlementState: 'focus_plan_active', persistenceStatus: 'memory_fallback' };
}
export async function retractFocusPlanGift(input: SuperAdminRetractGiftRequest): Promise<SuperAdminRetractGiftResult & { persistenceStatus: 'durable' | 'memory_fallback' }> { const r = validateSuperAdminRetractGiftRequest(input); if (!r.ok) return { status: 'blocked', failureReason: 'unsupported_action', giftRecord: null, resultingEntitlementState: 'subscription_required', persistenceStatus: useSql() ? 'durable' : 'memory_fallback' }; try { assertSuperAdminStepUpVerified(r.value.stepUpVerification); } catch { return { status: 'blocked', failureReason: 'step_up_required', giftRecord: null, resultingEntitlementState: 'subscription_required', persistenceStatus: useSql() ? 'durable' : 'memory_fallback' }; } const existing = gifts.get(input.giftRecordId); if (!existing || existing.status !== 'active') return { status: 'blocked', failureReason: !existing ? 'gift_not_found' : 'gift_not_active', giftRecord: null, resultingEntitlementState: 'subscription_required', persistenceStatus: useSql() ? 'durable' : 'memory_fallback' }; const next = { ...existing, status: 'retracted' as const, updatedAt: input.requestedAt }; gifts.set(existing.giftRecordId, next); if (useSql()) await queryDb('UPDATE super_admin_focus_plan_gifts SET status=$1,retracted_at=$2,retracted_by=$3,updated_at=$4 WHERE gift_id=$5', ['retracted', input.requestedAt, input.actorSuperAdminId, input.requestedAt, input.giftRecordId]); return { status: 'success', failureReason: null, giftRecord: next, resultingEntitlementState: 'subscription_required', persistenceStatus: useSql() ? 'durable' : 'memory_fallback' }; }
export async function restrictUserAccount(input: Parameters<typeof validateSuperAdminUserRestrictionRequest>[0]): Promise<SuperAdminUserRestrictionResult & { persistenceStatus: 'durable' | 'memory_fallback' }> { const r = validateSuperAdminUserRestrictionRequest(input); if (!r.ok) return { status: 'blocked', failureReason: 'unsupported_action', restrictionRecord: null, resultingEntitlementState: 'restricted', persistenceStatus: useSql() ? 'durable' : 'memory_fallback' }; try { assertSuperAdminStepUpVerified(r.value.stepUpVerification); } catch { return { status: 'blocked', failureReason: 'step_up_required', restrictionRecord: null, resultingEntitlementState: 'restricted', persistenceStatus: useSql() ? 'durable' : 'memory_fallback' }; } const rec: SuperAdminUserRestrictionRecord = { restrictionRecordId: `restriction_${randomUUID()}`, actorSuperAdminId: r.value.actorSuperAdminId, targetUserId: r.value.targetUserId, restrictionKind: r.value.restrictionKind, status: 'active', reasonCode: r.value.reasonCode, operatorNote: r.value.operatorNote, stepUpStatus: r.value.stepUpVerification.status, idempotencyKey: r.value.idempotencyKey, createdAt: r.value.requestedAt, updatedAt: r.value.requestedAt }; restrictions.set(rec.restrictionRecordId, rec); if (useSql()) await queryDb('INSERT INTO super_admin_user_restrictions(restriction_id,target_user_id,actor_user_id,restriction_kind,status,reason,operator_note,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)', [rec.restrictionRecordId, rec.targetUserId, rec.actorSuperAdminId, rec.restrictionKind, rec.status, rec.reasonCode, rec.operatorNote, rec.createdAt, rec.updatedAt]); return { status: 'success', failureReason: null, restrictionRecord: rec, resultingEntitlementState: 'restricted', persistenceStatus: useSql() ? 'durable' : 'memory_fallback' }; }

export const getStepUpReadinessState = (): SuperAdminStepUpReadinessState => 'provider_pending';
export async function getSuperAdminCommercialControlSnapshot(targetUserId: string): Promise<SuperAdminCommercialControlSnapshot> { const activeGift = [...gifts.values()].find((x) => x.targetUserId === targetUserId && x.status === 'active') ?? null; const activeRestriction = [...restrictions.values()].find((x) => x.targetUserId === targetUserId && x.status === 'active') ?? null; return { generatedAt: new Date().toISOString(), targetUserId, activeGiftCount: activeGift ? 1 : 0, activeRestrictionCount: activeRestriction ? 1 : 0, activeGift, activeRestriction, persistenceStatus: useSql() ? 'durable' : 'memory_fallback', stepUpReadinessState: getStepUpReadinessState() }; }
export const getSuperAdminCommercialControlCoverageReport = (): SuperAdminCommercialControlCoverageReport => ({ generatedAt: new Date().toISOString(), supportsGiftDurations: ['two_weeks', 'one_month'], mandatoryStepUpRequired: true, ipBanSupported: false, paymentProviderCallsPerformed: false });
