import type { CanonicalAssetSymbol } from '@elceo/types';
import type { EventAssessmentStage } from '../expectation-reality/contracts';

export type FragilityPolicyVersion='fragility-score-v1';
export type FragilityComponentName='counterfactual_dependency_fragility'|'contradiction_invalidation_pressure'|'path_instability'|'context_coherence_fragility'|'narrative_decay_vulnerability'|'crowding_amplification'|'volatility_sensitivity'|'historical_analog_dispersion';
export type FragilityAvailability='available'|'unavailable'|'structurally_unavailable'|'provenance_limited';
export type FragilitySourceOwner='ifp_1'|'ifp_2'|'ifp_3'|'ifp_4'|'ifp_5'|'ifp_6'|'derived';
export type FragilityComponent=Readonly<{component:FragilityComponentName;availability:FragilityAvailability;score:number|null;weight:number;effectiveWeight:number;sourceOwner:FragilitySourceOwner;assessmentStage:EventAssessmentStage;sourceEvaluationIds:readonly string[];sourceReferences:readonly string[];reasonCodes:readonly string[];warnings:readonly string[];limitations:readonly string[];rationale:string;audit?:Readonly<Record<string,unknown>>}>;
export type RemovalScenario=Readonly<{removedFamily:FragilityComponentName;baselinePositiveSupport:number;removedContribution:number;supportLossPct:number;remainingPositiveSupport:number;rank:number}>;
export type CounterfactualDependencyAudit=Readonly<{dominantSupportFamily:FragilityComponentName|null;dominantSupportShare:number;supportFamilyCount:number;supportConcentrationIndex:number;baselinePositiveSupport:number;removalScenarios:readonly RemovalScenario[]}>;
export type FragilityProvenanceAudit=Readonly<{state:'qualified'|'partially_limited'|'limited';upstreamPolicyVersions:Readonly<Record<string,string>>;sourceEvaluationIds:readonly string[];excludedComponentIds:readonly FragilityComponentName[];reliabilityLimitations:readonly string[];warnings:readonly string[]}>;
export type FragilityScoreEvaluation=Readonly<{fragilityScoreEvaluationId:string;policyVersion:FragilityPolicyVersion;sourceEventEvaluationId:string;sourceExpectationId:string;sourceAnalogRetrievalId:string|null;sourceProtocolDecisionId:string;sourceCleanlinessEvaluationId:string;sourceNarrativeDecayEvaluationId:string;sourcePositioningStressEvaluationId:string;asset:CanonicalAssetSymbol;eventKind:string;assessmentStage:EventAssessmentStage;evidenceCutoffAt:string;evidenceSufficiency:'sufficient'|'insufficient_data'|'provenance_limited';expectedWeight:number;availableWeight:number;evidenceCoverageRatio:number;rawFragilityScore:number|null;fragilityScore:number|null;fragilityState:'low'|'elevated'|'high'|'severe'|'insufficient_data';components:readonly FragilityComponent[];counterfactualDependency:CounterfactualDependencyAudit;provenanceAudit:FragilityProvenanceAudit;dominantFragilityDrivers:readonly FragilityComponentName[];upstreamThesisInvalidated:boolean;sourceEvidenceReferences:readonly string[];warnings:readonly string[];limitations:readonly string[];deterministicRationale:string;canonicalPayloadHash:string;createdAt:string}>;
export type FragilityScoreServiceInput=Readonly<{eventEvaluationId:string;protocolDecisionId:string;cleanlinessEvaluationId:string;narrativeDecayEvaluationId:string;positioningStressEvaluationId:string;analogRetrievalId?:string;evidenceCutoffAt:string}>;
