async function main(): Promise<void> {
  (globalThis as { process?: { env?: Record<string, string | undefined> } }).process ??= { env: {} };
  (globalThis as { process?: { env?: Record<string, string | undefined> } }).process!.env ??= {};
  (globalThis as { process?: { env?: Record<string, string | undefined> } }).process!.env!.APP_STATE_REPOSITORY = 'memory';

  const { runApplicationStateTests } = await import('./application-state.test.js');
  const { runUserStateAccessTests } = await import('./user-state-access.test.js');
  const { runRouteEntitlementMapCoreTests } = await import('./route-entitlement-map-core.test.js');
  const { runJournalPersistenceTests } = await import('./journal-persistence.test.js');
  const { runEntitlementEnforcementTests } = await import('./entitlement-enforcement.test.js');
  const { runSubscriptionMappingTests } = await import('./subscription-mapping.test.js');
  const { runJournalDomainCoreTests } = await import('./journal-domain-core.test.js');
  const { runJournalInfluenceEngineTests } = await import('./journal-influence-engine.test.js');
  const { runPortfolioDomainCoreTests } = await import('./portfolio-domain-core.test.js');
  const { runWorkspaceSnapshotEngineTests } = await import('./workspace-snapshot-engine.test.js');
  const { runSnapshotRefreshRuntimeTests } = await import('./snapshot-refresh-runtime.test.js');
  const { runOpsRuntimeTests } = await import('./ops-runtime.test.js');
  const { runAdminControlPlaneTests } = await import('./admin-control-plane.test.js');
  const { runEntitlementsRuntimeCoreTests } = await import('./entitlements-runtime-core.test.js');
  const { runBillingRuntimeCoreTests } = await import('./billing-runtime-core.test.js');
  const { runBillingLifecycleCoreTests } = await import('./billing-lifecycle-core.test.js');
  const { runBillingPolicyCoreTests } = await import('./billing-policy-core.test.js');
  const { runBillingAdminCoreTests } = await import('./billing-admin-core.test.js');
  const { runBillingOrchestrationCoreTests } = await import('./billing-orchestration-core.test.js');
  const { runSecurityRuntimeCoreTests } = await import('./security-runtime-core.test.js');
  const { runCommercialEntitlementsCoreTests } = await import('./commercial-entitlements-core.test.js');
  const { runDbTransactionHelperTests } = await import('./db-transaction-helper.test.js');
  const { runDbClientLifecycleTests } = await import('./db-client-lifecycle.test.js');
  const { runUserSocialIdentifiersRepositoryTests } = await import('./user-social-identifiers-repository.test.js');
  const { runSuperAdminCommercialRepositoryTests } = await import('./super-admin-commercial-repository.test.js');
  const { runSuperAdminCommercialControlsCoreTests } = await import('./super-admin-commercial-controls-core.test.js');
  const { runSuperAdminStepUpSqlRepositoryTests } = await import('./super-admin-step-up-sql-repository.test.js');
  const { runSuperAdminStepUpPersistenceTests } = await import('./super-admin-step-up-persistence.test.js');
  const { runSuperAdminMetricsCoreTests } = await import('./super-admin-metrics-core.test.js');
  const { runProviderActivationReadinessCoreTests } = await import('./provider-activation-readiness-core.test.js');
  const { runSeoProgrammaticFeedsTests } = await import('./seo-programmatic-feeds.test.js');
  const { runObservabilityAuditCoreTests } = await import('./observability-audit-core.test.js');

  await runApplicationStateTests();
  await runUserStateAccessTests();
  await runRouteEntitlementMapCoreTests();
  await runJournalPersistenceTests();
  await runEntitlementEnforcementTests();
  await runSubscriptionMappingTests();
  await runJournalDomainCoreTests();
  await runJournalInfluenceEngineTests();
  await runPortfolioDomainCoreTests();
  await runWorkspaceSnapshotEngineTests();
  await runSnapshotRefreshRuntimeTests();
  await runOpsRuntimeTests();
  await runAdminControlPlaneTests();
  await runEntitlementsRuntimeCoreTests();
  await runBillingRuntimeCoreTests();
  await runBillingLifecycleCoreTests();
  await runBillingPolicyCoreTests();
  await runBillingAdminCoreTests();
  await runBillingOrchestrationCoreTests();
  await runSecurityRuntimeCoreTests();
  await runCommercialEntitlementsCoreTests();
  await runDbTransactionHelperTests();
  await runDbClientLifecycleTests();
  await runUserSocialIdentifiersRepositoryTests();
  await runSuperAdminCommercialRepositoryTests();
  await runSuperAdminCommercialControlsCoreTests();
  await runSuperAdminStepUpSqlRepositoryTests();
  await runSuperAdminStepUpPersistenceTests();
  runSuperAdminMetricsCoreTests();
  runProviderActivationReadinessCoreTests();
  runSeoProgrammaticFeedsTests();
  runObservabilityAuditCoreTests();
  console.log('application-state tests passed');
}

void main();
