import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import {shouldResumeProviderCheckout} from '../billing/checkout-resume';
import {assertImmediateCommercialPriceEffectiveFrom} from '../commercial-pricing/index';
import {InternalPaymentRuntime,MemoryInternalPaymentRepository,createMemoryPaymentStore} from '../billing/internal-payment';
import {buildStripeTestSignature,normalizeStripeProviderPayload,verifyStripeWebhookSignature} from '../payment-providers/sandbox-adapter';
import {reconcileStripePaymentOperation,validateStripeProviderTruth} from '../payment-providers/stripe-reconciliation';
import {koraEventIdentity,validateKoraTruth,verifyKoraWebhook} from '../payment-providers/korapay-adapter';
export async function runSecCPaymentCoreTests(){
 const body='{"id":"evt"}',secret='whsec_fixture_not_live',now=2_000_000_000;
 assert.equal(verifyStripeWebhookSignature(body,buildStripeTestSignature(body,secret,String(now)),secret,now),true);
 assert.throws(()=>verifyStripeWebhookSignature(body,buildStripeTestSignature(body,'wrong',String(now)),secret,now),/invalid_provider/);
 assert.throws(()=>verifyStripeWebhookSignature(body,buildStripeTestSignature(body,secret,String(now-301)),secret,now),/timestamp_out_of_tolerance/);
 assert.throws(()=>verifyStripeWebhookSignature(body,buildStripeTestSignature(body,secret,String(now+301)),secret,now),/timestamp_out_of_tolerance/);
 const rotated=`t=${now},v1=${'0'.repeat(64)},v1=${buildStripeTestSignature(body,secret,String(now)).split('v1=')[1]}`;assert.equal(verifyStripeWebhookSignature(body,rotated,secret,now),true);
 const data={reference:'r'},sig=createHmac('sha256','k').update(JSON.stringify(data)).digest('hex');assert.equal(verifyKoraWebhook(data,sig,'k'),true);assert.throws(()=>verifyKoraWebhook(data,'0'.repeat(64),'k'),/invalid_korapay_signature/);assert.equal(koraEventIdentity('charge.success',data),koraEventIdentity('charge.success',data));
 const kora={reference:'r',status:'success',amountExpected:'100',amountPaid:'100',currency:'KES',paymentMethod:'card',metadata:{operationId:'o',plan:'focus_plan',billingInterval:'monthly'}};assert.equal(validateKoraTruth({reference:'r',amountMinor:'100',currency:'KES',plan:'focus_plan',interval:'monthly',operationId:'o'},kora),true);for(const bad of [{...kora,amountPaid:'99'},{...kora,amountPaid:'101'},{...kora,currency:'GHS'},{...kora,reference:'x'},{...kora,status:'pending'}])assert.throws(()=>validateKoraTruth({reference:'r',amountMinor:'100',currency:'KES',plan:'focus_plan',interval:'monthly',operationId:'o'},bad),/provider_commercial_mismatch/);
 const store=createMemoryPaymentStore(),repo=new MemoryInternalPaymentRepository(store),runtime=new InternalPaymentRuntime('local_fake_provider',repo);const input={subjectUserId:'u',targetPlan:'focus_plan',billingInterval:'monthly' as const,amount:100,currency:'KES',businessIdempotencyKey:'gesture-123'};
 assert.throws(()=>assertImmediateCommercialPriceEffectiveFrom(new Date(2_000_000_010_000).toISOString(),2_000_000_000_000),/future_commercial_price_not_supported/);assert.doesNotThrow(()=>assertImmediateCommercialPriceEffectiveFrom(new Date(2_000_000_000_000).toISOString(),2_000_000_000_000));
 const intention=await repo.createOrReuseOperation({...input,provider:'local_fake_provider'});assert.equal(shouldResumeProviderCheckout(intention.operation),true);const retry=await runtime.checkout(input);assert.equal(retry.operation.internalPaymentOperationId,intention.operation.internalPaymentOperationId);assert.equal(retry.operation.providerIdempotencyKey,intention.operation.providerIdempotencyKey);assert.equal((await runtime.counts()).operations,1);
 await assert.rejects(repo.createOrReuseOperation({...input,amount:101,provider:'local_fake_provider'}),/payment_idempotency_input_mismatch/);
 const lostStore=createMemoryPaymentStore(),lostRepo=new MemoryInternalPaymentRepository(lostStore),lostRuntime=new InternalPaymentRuntime('local_fake_provider',lostRepo);const lost=await lostRuntime.checkout({...input,businessIdempotencyKey:'gesture-lost',outcome:'accepted_response_lost'});const identity=lost.operation.providerIdempotencyKey;const resumed=await lostRuntime.checkout({...input,businessIdempotencyKey:'gesture-lost',outcome:'accepted'});assert.equal(resumed.operation.providerIdempotencyKey,identity);assert.equal((await lostRuntime.counts()).providerCharges,1);assert.equal((await lostRuntime.counts()).operations,1);
 const truth=normalizeStripeProviderPayload({id:'cs_1',object:'checkout.session',payment_status:'paid',amount_total:100,currency:'kes',payment_intent:'pi_1',metadata:{operationId:resumed.operation.internalPaymentOperationId,providerIdempotencyKey:identity,subjectUserId:'u',targetPlan:'focus_plan',billingInterval:'monthly'}},null);const attached=await lostRepo.recordProviderAccepted(resumed.operation.internalPaymentOperationId,'pi_1','cs_1');assert.equal(shouldResumeProviderCheckout(attached),false);assert.equal(validateStripeProviderTruth(attached,truth),null);assert.equal(await reconcileStripePaymentOperation(lostRepo,{retrievePaymentOrSession:async()=>truth},attached.internalPaymentOperationId).then(x=>x.status),'matched');assert.equal(lostRuntime.providerChargeAttempts,2);
 for(const changed of [{...truth,amount:99},{...truth,currency:'GHS'},{...truth,providerProductReference:'wrong'}])assert.equal(validateStripeProviderTruth({...attached,quotedProviderProductReference:changed.providerProductReference==='wrong'?'expected':null},changed),'provider_commercial_mismatch');
}
