import assert from 'node:assert/strict';
import { MemorySuperAdminStepUpRepository } from '../persistence/super-admin-step-up-repository';
import { SuperAdminStepUpService, getSuperAdminCommercialRouteScope, getSuperAdminStepUpPersistenceReadiness, resetSuperAdminStepUpServiceForTests, stepUpPolicy } from '../super-admin-commercial-controls/index';
const at=(m:number)=>`2026-05-15T00:${String(m).padStart(2,'0')}:00.000Z`;
export async function runSuperAdminStepUpPersistenceTests(): Promise<void> {
  const oldNodeEnv=process.env.NODE_ENV; const oldFixture=process.env.ELCEO_ENABLE_FIXTURE_STEP_UP; process.env.NODE_ENV='test'; process.env.ELCEO_ENABLE_FIXTURE_STEP_UP='1';
  const repo=new MemorySuperAdminStepUpRepository(); const a=new SuperAdminStepUpService(repo,{challengeId:()=>`stepup_a`});
  const ch=await a.createChallenge({actorUserId:'admin-a',actionKind:'focus_plan_gift',routeScope:getSuperAdminCommercialRouteScope('focus_plan_gift'),targetUserId:'user-a',providerKind:'fixture_test_only',requestedAt:at(0)});
  const b=new SuperAdminStepUpService(repo); assert.equal((await b.verify({challengeId:ch.challengeId,providerKind:'fixture_test_only',actorUserId:'admin-a',proof:'fixture-pass',requestedAt:at(1)})).status,'verified');
  const [c1,c2]=await Promise.allSettled([b.consume({challengeId:ch.challengeId,actorUserId:'admin-a',expectedActionKind:'focus_plan_gift',expectedRouteScope:getSuperAdminCommercialRouteScope('focus_plan_gift'),expectedTargetUserId:'user-a',nowIso:at(2)}),a.consume({challengeId:ch.challengeId,actorUserId:'admin-a',expectedActionKind:'focus_plan_gift',expectedRouteScope:getSuperAdminCommercialRouteScope('focus_plan_gift'),expectedTargetUserId:'user-a',nowIso:at(2)})]);
  assert.equal([c1,c2].filter(x=>x.status==='fulfilled').length,1); assert.equal((await repo.listAuditEventsForChallenge(ch.challengeId)).filter(e=>e.eventKind==='challenge_consumed').length,1);
  const rateRepo=new MemorySuperAdminStepUpRepository(); for(let i=0;i<stepUpPolicy.maxChallengesPerWindow;i++) await new SuperAdminStepUpService(rateRepo,{challengeId:()=>`stepup_r${i}`}).createChallenge({actorUserId:'admin-r',actionKind:'focus_plan_gift',routeScope:getSuperAdminCommercialRouteScope('focus_plan_gift'),targetUserId:'user-r',providerKind:'fixture_test_only',requestedAt:at(3)});
  await assert.rejects(()=>new SuperAdminStepUpService(rateRepo,{challengeId:()=>`stepup_rx`}).createChallenge({actorUserId:'admin-r',actionKind:'focus_plan_gift',routeScope:getSuperAdminCommercialRouteScope('focus_plan_gift'),targetUserId:'user-r',providerKind:'fixture_test_only',requestedAt:at(4)}),/step_up_rate_limited/);
  const failRepo=new MemorySuperAdminStepUpRepository(); const failSvc=new SuperAdminStepUpService(failRepo,{challengeId:()=>`stepup_fail`}); const failCh=await failSvc.createChallenge({actorUserId:'admin-f',actionKind:'focus_plan_gift',routeScope:getSuperAdminCommercialRouteScope('focus_plan_gift'),targetUserId:'user-f',providerKind:'fixture_test_only',requestedAt:at(5)}); for(let i=0;i<5;i++) await failSvc.verify({challengeId:failCh.challengeId,providerKind:'fixture_test_only',actorUserId:'admin-f',proof:'bad',requestedAt:at(6)}); await assert.rejects(()=>new SuperAdminStepUpService(failRepo).createChallenge({actorUserId:'admin-f',actionKind:'focus_plan_gift',routeScope:getSuperAdminCommercialRouteScope('focus_plan_gift'),targetUserId:'user-f',providerKind:'fixture_test_only',requestedAt:at(7)}),/step_up_actor_locked/);
  const staleRepo=new MemorySuperAdminStepUpRepository(); const staleSvc=new SuperAdminStepUpService(staleRepo,{challengeId:()=>`stepup_stale`}); const stale=await staleSvc.createChallenge({actorUserId:'admin-s',actionKind:'focus_plan_gift',routeScope:getSuperAdminCommercialRouteScope('focus_plan_gift'),targetUserId:'user-s',providerKind:'fixture_test_only',requestedAt:at(8)}); const ok=await staleSvc.verify({challengeId:stale.challengeId,providerKind:'fixture_test_only',actorUserId:'admin-s',proof:'fixture-pass',requestedAt:at(9)}); await assert.rejects(()=>staleSvc.consume({challengeId:stale.challengeId,actorUserId:'admin-s',expectedActionKind:'focus_plan_gift',expectedRouteScope:getSuperAdminCommercialRouteScope('focus_plan_gift'),expectedTargetUserId:'user-s',nowIso:ok.freshUntil!}),/challenge_expired/);

  const createRollbackRepo=new MemorySuperAdminStepUpRepository(); createRollbackRepo.failAudit=true; await assert.rejects(()=>new SuperAdminStepUpService(createRollbackRepo,{challengeId:()=>`stepup_create_rollback`}).createChallenge({actorUserId:'admin-cr',actionKind:'focus_plan_gift',routeScope:getSuperAdminCommercialRouteScope('focus_plan_gift'),targetUserId:'user-cr',providerKind:'fixture_test_only',requestedAt:at(10)})); assert.equal(await createRollbackRepo.getChallengeById('stepup_create_rollback'), null);
  const verifyRollbackRepo=new MemorySuperAdminStepUpRepository(); const verifyRollbackSvc=new SuperAdminStepUpService(verifyRollbackRepo,{challengeId:()=>`stepup_verify_rollback`}); const verifyRollbackChallenge=await verifyRollbackSvc.createChallenge({actorUserId:'admin-vr',actionKind:'focus_plan_gift',routeScope:getSuperAdminCommercialRouteScope('focus_plan_gift'),targetUserId:'user-vr',providerKind:'fixture_test_only',requestedAt:at(11)}); verifyRollbackRepo.failAudit=true; await assert.rejects(()=>verifyRollbackSvc.verify({challengeId:verifyRollbackChallenge.challengeId,providerKind:'fixture_test_only',actorUserId:'admin-vr',proof:'fixture-pass',requestedAt:at(12)})); const verifyRollbackStored=await verifyRollbackRepo.getChallengeById(verifyRollbackChallenge.challengeId); assert.equal(verifyRollbackStored?.status,'pending'); assert.equal(verifyRollbackStored?.attemptCount,0); assert.equal(verifyRollbackStored?.freshUntil,null);
  const consumeRollbackRepo=new MemorySuperAdminStepUpRepository(); const consumeRollbackSvc=new SuperAdminStepUpService(consumeRollbackRepo,{challengeId:()=>`stepup_consume_rollback`}); const consumeRollbackChallenge=await consumeRollbackSvc.createChallenge({actorUserId:'admin-cor',actionKind:'focus_plan_gift',routeScope:getSuperAdminCommercialRouteScope('focus_plan_gift'),targetUserId:'user-cor',providerKind:'fixture_test_only',requestedAt:at(13)}); const consumeRollbackVerified=await consumeRollbackSvc.verify({challengeId:consumeRollbackChallenge.challengeId,providerKind:'fixture_test_only',actorUserId:'admin-cor',proof:'fixture-pass',requestedAt:at(14)}); consumeRollbackRepo.failAudit=true; await assert.rejects(()=>consumeRollbackSvc.consume({challengeId:consumeRollbackChallenge.challengeId,actorUserId:'admin-cor',expectedActionKind:'focus_plan_gift',expectedRouteScope:getSuperAdminCommercialRouteScope('focus_plan_gift'),expectedTargetUserId:'user-cor',nowIso:at(15)})); const consumeRollbackStored=await consumeRollbackRepo.getChallengeById(consumeRollbackChallenge.challengeId); assert.equal(consumeRollbackStored?.status,'verified'); assert.equal(consumeRollbackStored?.consumedAt,null); assert.equal(consumeRollbackStored?.freshUntil,consumeRollbackVerified.freshUntil);
  const oldRepo=process.env.APP_STATE_REPOSITORY; const oldDb=process.env.DATABASE_URL; process.env.NODE_ENV='production'; delete process.env.APP_STATE_REPOSITORY; delete process.env.DATABASE_URL; resetSuperAdminStepUpServiceForTests(); assert.equal((await getSuperAdminStepUpPersistenceReadiness()).persistenceStatus,'unavailable'); process.env.APP_STATE_REPOSITORY=oldRepo; if(oldRepo===undefined) delete process.env.APP_STATE_REPOSITORY; if(oldDb===undefined) delete process.env.DATABASE_URL; else process.env.DATABASE_URL=oldDb; process.env.NODE_ENV='test'; resetSuperAdminStepUpServiceForTests();

  const businessRepo=new MemorySuperAdminStepUpRepository(); const businessSvc=new SuperAdminStepUpService(businessRepo,{challengeId:()=>`stepup_business_failure`}); const businessChallenge=await businessSvc.createChallenge({actorUserId:'admin-business',actionKind:'focus_plan_gift_retract',routeScope:getSuperAdminCommercialRouteScope('focus_plan_gift_retract'),targetUserId:'user-business',providerKind:'fixture_test_only',requestedAt:at(16)}); await businessSvc.verify({challengeId:businessChallenge.challengeId,providerKind:'fixture_test_only',actorUserId:'admin-business',proof:'fixture-pass',requestedAt:at(17)}); await businessSvc.consume({challengeId:businessChallenge.challengeId,actorUserId:'admin-business',expectedActionKind:'focus_plan_gift_retract',expectedRouteScope:getSuperAdminCommercialRouteScope('focus_plan_gift_retract'),expectedTargetUserId:'user-business',nowIso:at(18)}); const simulatedBusinessFailure={status:'blocked',failureReason:'gift_not_found'}; assert.equal(simulatedBusinessFailure.status,'blocked'); assert.equal((await businessRepo.getChallengeById(businessChallenge.challengeId))?.status,'consumed'); await assert.rejects(()=>businessSvc.consume({challengeId:businessChallenge.challengeId,actorUserId:'admin-business',expectedActionKind:'focus_plan_gift_retract',expectedRouteScope:getSuperAdminCommercialRouteScope('focus_plan_gift_retract'),expectedTargetUserId:'user-business',nowIso:at(19)}));
  if(!process.env.ELCEO_TEST_DATABASE_URL) console.log('ELCEO_TEST_DATABASE_URL not configured; optional PostgreSQL step-up integration skipped.');
  process.env.NODE_ENV=oldNodeEnv; if(oldFixture===undefined) delete process.env.ELCEO_ENABLE_FIXTURE_STEP_UP; else process.env.ELCEO_ENABLE_FIXTURE_STEP_UP=oldFixture;
}
