import assert from 'node:assert/strict';
import { MemorySuperAdminStepUpRepository } from '../persistence/super-admin-step-up-repository';
import { SuperAdminStepUpService, getSuperAdminCommercialRouteScope, stepUpPolicy } from '../super-admin-commercial-controls/index';
const at=(m:number)=>`2026-05-15T00:${String(m).padStart(2,'0')}:00.000Z`;
export async function runSuperAdminStepUpPersistenceTests(): Promise<void> {
  const oldNodeEnv=process.env.NODE_ENV; const oldFixture=process.env.ELCEO_ENABLE_FIXTURE_STEP_UP; process.env.NODE_ENV='test'; process.env.ELCEO_ENABLE_FIXTURE_STEP_UP='1';
  const repo=new MemorySuperAdminStepUpRepository(); const a=new SuperAdminStepUpService(repo,{challengeId:()=>`stepup_a`});
  const ch=await a.createChallenge({actorUserId:'admin-a',actionKind:'focus_plan_gift',routeScope:getSuperAdminCommercialRouteScope('focus_plan_gift'),targetUserId:'user-a',providerKind:'fixture_test_only',requestedAt:at(0)});
  const b=new SuperAdminStepUpService(repo); assert.equal((await b.verify({challengeId:ch.challengeId,providerKind:'fixture_test_only',actorUserId:'admin-a',proof:'fixture-pass',requestedAt:at(1)})).status,'verified');
  const [c1,c2]=await Promise.allSettled([b.consume({challengeId:ch.challengeId,actorUserId:'admin-a',expectedActionKind:'focus_plan_gift',expectedRouteScope:getSuperAdminCommercialRouteScope('focus_plan_gift'),expectedTargetUserId:'user-a',nowIso:at(2)}),a.consume({challengeId:ch.challengeId,actorUserId:'admin-a',expectedActionKind:'focus_plan_gift',expectedRouteScope:getSuperAdminCommercialRouteScope('focus_plan_gift'),expectedTargetUserId:'user-a',nowIso:at(2)})]);
  assert.equal([c1,c2].filter(x=>x.status==='fulfilled').length,1); assert.equal((await repo.listAuditEventsForChallenge(ch.challengeId)).filter(e=>e.eventKind==='challenge_consumed').length,1);
  const rateRepo=new MemorySuperAdminStepUpRepository(); for(let i=0;i<stepUpPolicy.maxChallengesPerWindow;i++) await new SuperAdminStepUpService(rateRepo,{challengeId:()=>`stepup_r${i}`}).createChallenge({actorUserId:'admin-r',actionKind:'focus_plan_gift',routeScope:getSuperAdminCommercialRouteScope('focus_plan_gift'),targetUserId:'user-r',providerKind:'fixture_test_only',requestedAt:at(3)});
  await assert.rejects(()=>new SuperAdminStepUpService(rateRepo,{challengeId:()=>`stepup_rx`}).createChallenge({actorUserId:'admin-r',actionKind:'focus_plan_gift',routeScope:getSuperAdminCommercialRouteScope('focus_plan_gift'),targetUserId:'user-r',providerKind:'fixture_test_only',requestedAt:at(4)}),/step_up_rate_limited/);
  const failRepo=new MemorySuperAdminStepUpRepository(); const failSvc=new SuperAdminStepUpService(failRepo,{challengeId:()=>`stepup_fail`}); const failCh=await failSvc.createChallenge({actorUserId:'admin-f',actionKind:'focus_plan_gift',routeScope:getSuperAdminCommercialRouteScope('focus_plan_gift'),targetUserId:'user-f',providerKind:'fixture_test_only',requestedAt:at(5)}); for(let i=0;i<5;i++) await failSvc.verify({challengeId:failCh.challengeId,providerKind:'fixture_test_only',actorUserId:'admin-f',proof:'bad',requestedAt:at(6)}); await assert.rejects(()=>new SuperAdminStepUpService(failRepo).createChallenge({actorUserId:'admin-f',actionKind:'focus_plan_gift',routeScope:getSuperAdminCommercialRouteScope('focus_plan_gift'),targetUserId:'user-f',providerKind:'fixture_test_only',requestedAt:at(7)}),/step_up_actor_locked/);
  const staleRepo=new MemorySuperAdminStepUpRepository(); const staleSvc=new SuperAdminStepUpService(staleRepo,{challengeId:()=>`stepup_stale`}); const stale=await staleSvc.createChallenge({actorUserId:'admin-s',actionKind:'focus_plan_gift',routeScope:getSuperAdminCommercialRouteScope('focus_plan_gift'),targetUserId:'user-s',providerKind:'fixture_test_only',requestedAt:at(8)}); const ok=await staleSvc.verify({challengeId:stale.challengeId,providerKind:'fixture_test_only',actorUserId:'admin-s',proof:'fixture-pass',requestedAt:at(9)}); await assert.rejects(()=>staleSvc.consume({challengeId:stale.challengeId,actorUserId:'admin-s',expectedActionKind:'focus_plan_gift',expectedRouteScope:getSuperAdminCommercialRouteScope('focus_plan_gift'),expectedTargetUserId:'user-s',nowIso:ok.freshUntil!}),/challenge_expired/);
  const auditRepo=new MemorySuperAdminStepUpRepository(); auditRepo.failAudit=true; await assert.rejects(()=>new SuperAdminStepUpService(auditRepo,{challengeId:()=>`stepup_audit`}).createChallenge({actorUserId:'admin-audit',actionKind:'focus_plan_gift',routeScope:getSuperAdminCommercialRouteScope('focus_plan_gift'),targetUserId:'user-audit',providerKind:'fixture_test_only',requestedAt:at(10)}));
  if(!process.env.ELCEO_TEST_DATABASE_URL) console.log('ELCEO_TEST_DATABASE_URL not configured; optional PostgreSQL step-up integration skipped.');
  process.env.NODE_ENV=oldNodeEnv; if(oldFixture===undefined) delete process.env.ELCEO_ENABLE_FIXTURE_STEP_UP; else process.env.ELCEO_ENABLE_FIXTURE_STEP_UP=oldFixture;
}
