import assert from 'node:assert/strict';
import { __setDbPoolFactoryForTests } from '../db/client';
import { SQLSuperAdminStepUpRepository, StepUpPersistenceError, type StepUpPolicy } from '../persistence/super-admin-step-up-repository';
const at=(m:number)=>`2026-05-15T00:${String(m).padStart(2,'0')}:00.000Z`;
const policy:StepUpPolicy={freshnessSeconds:600,challengeExpirySeconds:300,maxAttemptsPerChallenge:5,maxChallengesPerWindow:10,windowSeconds:600,lockoutSeconds:900};
const row=(over:Record<string,unknown>={})=>({challenge_id:'stepup_sql',actor_user_id:'admin-sql',action_kind:'focus_plan_gift',route_scope:'/api/admin/commercial/users/[userId]/gift-focus-plan',target_user_id:'user-sql',provider_kind:'fixture_test_only',verified_provider_kind:null,status:'pending',created_at:at(0),expires_at:at(5),verified_at:null,fresh_until:null,failed_attempts:0,last_attempt_at:null,consumed_at:null,lockout_until:null,updated_at:at(0),version:0,...over});
function installHarness(handler:(sql:string,params?:unknown[])=>Record<string,unknown>[]) { const ops:string[]=[]; const client={async query(sql:string,params?:unknown[]){ops.push(sql); return {rows:handler(sql,params)};}, release(){ops.push('release');}}; __setDbPoolFactoryForTests(()=>({async query(sql:string,params?:unknown[]){ops.push(`pool:${sql}`); return {rows:handler(sql,params)};}, async connect(){ops.push('connect'); return client;}})); return ops; }
export async function runSuperAdminStepUpSqlRepositoryTests(): Promise<void> {
  const repo=new SQLSuperAdminStepUpRepository();
  let ops=installHarness((sql)=>sql.includes('count(*)')?[{count:'0'}]:sql.includes('SELECT * FROM super_admin_step_up_actor_state')?[{lockout_until:null}]:[]);
  await repo.createChallengeAtomically({challengeId:'stepup_sql',actorUserId:'admin-sql',actionKind:'focus_plan_gift',routeScope:'/api/admin/commercial/users/[userId]/gift-focus-plan',targetUserId:'user-sql',providerKind:'fixture_test_only',requestedAt:at(0),nowIso:at(0),policy,fixturePermitted:true});
  assert.equal(ops.some(x=>x.includes('INSERT INTO super_admin_step_up_actor_state')),true); assert.equal(ops.some(x=>x.includes('FOR UPDATE')),true); assert.equal(ops.some(x=>x.includes('count(*)')),true); assert.equal(ops.some(x=>x.includes('INSERT INTO super_admin_step_up_challenges')),true); assert.equal(ops.some(x=>x.includes('INSERT INTO super_admin_step_up_audit_events')),true); assert.equal(ops.includes('COMMIT'),true);
  ops=installHarness((sql)=>sql.includes('SELECT * FROM super_admin_step_up_actor_state')?[{lockout_until:null}]:sql.includes('SELECT * FROM super_admin_step_up_challenges')?[row()]:[]);
  await repo.applyVerificationAttemptAtomically({challengeId:'stepup_sql',actorUserId:'admin-sql',providerKind:'fixture_test_only',nowIso:at(1),disposition:'accepted',policy});
  assert.equal(ops.findIndex(x=>x.includes('INSERT INTO super_admin_step_up_actor_state')) < ops.findIndex(x=>x.includes('SELECT * FROM super_admin_step_up_actor_state')), true); assert.equal(ops.some(x=>x.includes('SELECT * FROM super_admin_step_up_challenges')&&x.includes('FOR UPDATE')),true); assert.equal(ops.some(x=>x.includes("status='verified'")),true); assert.equal(ops.includes('COMMIT'),true);
  ops=installHarness((sql)=>sql.includes('SELECT * FROM super_admin_step_up_actor_state')?[{lockout_until:null}]:sql.includes('SELECT * FROM super_admin_step_up_challenges')?[]:[]);
  const unknown=await repo.applyVerificationAttemptAtomically({challengeId:'missing',actorUserId:'admin-sql',providerKind:'fixture_test_only',nowIso:at(1),disposition:'accepted',policy}); assert.equal(unknown.failureReason,'challenge_not_found'); assert.equal(ops.some(x=>x.includes('verification_unknown_challenge')||x.includes('INSERT INTO super_admin_step_up_audit_events')),true);
  ops=installHarness((sql)=>sql.includes('SELECT * FROM super_admin_step_up_actor_state')?[{lockout_until:null}]:sql.includes('SELECT * FROM super_admin_step_up_challenges')?[row({actor_user_id:'owner-sql'})]:[]);
  await repo.applyVerificationAttemptAtomically({challengeId:'stepup_sql',actorUserId:'requester-sql',providerKind:'fixture_test_only',nowIso:at(1),disposition:'accepted',policy}); assert.equal(ops.some(x=>x.includes('INSERT INTO super_admin_step_up_audit_events')),true);
  ops=installHarness((sql)=>sql.includes('SELECT * FROM super_admin_step_up_actor_state')?[{lockout_until:null}]:sql.includes('SELECT * FROM super_admin_step_up_challenges')?[row({provider_kind:'totp'})]:[]);
  await repo.applyVerificationAttemptAtomically({challengeId:'stepup_sql',actorUserId:'admin-sql',providerKind:'fixture_test_only',nowIso:at(1),disposition:'accepted',policy}); assert.equal(ops.some(x=>x.includes('failed_attempts=$2')),false);
  ops=installHarness((sql)=>sql.includes('SELECT * FROM super_admin_step_up_actor_state')?[{lockout_until:null}]:sql.includes('SELECT * FROM super_admin_step_up_challenges')?[row()]:[]);
  await repo.applyVerificationAttemptAtomically({challengeId:'stepup_sql',actorUserId:'admin-sql',providerKind:'fixture_test_only',nowIso:at(1),disposition:'fixture_forbidden',policy}); assert.equal(ops.some(x=>x.includes('failed_attempts=$2')),false);
  ops=installHarness((sql)=>sql.includes('SELECT * FROM super_admin_step_up_actor_state')?[{lockout_until:null}]:sql.includes('SELECT * FROM super_admin_step_up_challenges')?[row({provider_kind:'totp'})]:[]);
  await repo.applyVerificationAttemptAtomically({challengeId:'stepup_sql',actorUserId:'admin-sql',providerKind:'totp',nowIso:at(1),disposition:'provider_pending',policy}); assert.equal(ops.some(x=>x.includes('failed_attempts=$2')),false);
  ops=installHarness((sql)=>sql.includes('SELECT * FROM super_admin_step_up_actor_state')?[{lockout_until:null}]:sql.includes('SELECT * FROM super_admin_step_up_challenges')?[row({failed_attempts:4})]:[]);
  await repo.applyVerificationAttemptAtomically({challengeId:'stepup_sql',actorUserId:'admin-sql',providerKind:'fixture_test_only',nowIso:at(1),disposition:'rejected',policy}); assert.equal(ops.some(x=>x.includes("status='locked'")),true); assert.equal(ops.some(x=>x.includes('UPDATE super_admin_step_up_actor_state SET lockout_until')),true);
  ops=installHarness((sql)=>sql.includes('SELECT * FROM super_admin_step_up_actor_state')?[{lockout_until:null}]:sql.includes('SELECT * FROM super_admin_step_up_challenges')?[row({status:'verified',verified_provider_kind:'fixture_test_only',verified_at:at(1),fresh_until:at(11)})]:[]);
  await repo.consumeVerifiedChallengeAtomically({challengeId:'stepup_sql',actorUserId:'admin-sql',expectedActionKind:'focus_plan_gift',expectedRouteScope:'/api/admin/commercial/users/[userId]/gift-focus-plan',expectedTargetUserId:'user-sql',nowIso:at(2),fixturePermitted:true}); assert.equal(ops.some(x=>x.includes('SELECT * FROM super_admin_step_up_challenges WHERE challenge_id=$1')&&!x.includes('FOR UPDATE')),false); assert.equal(ops.some(x=>x.includes("status='consumed'")),true);
  ops=installHarness((sql)=>sql.includes('SELECT * FROM super_admin_step_up_actor_state')?[{lockout_until:null}]:sql.includes('SELECT * FROM super_admin_step_up_challenges')?[]:[]);
  await repo.consumeVerifiedChallengeAtomically({challengeId:'missing',actorUserId:'admin-sql',expectedActionKind:'focus_plan_gift',expectedRouteScope:'/api/admin/commercial/users/[userId]/gift-focus-plan',expectedTargetUserId:'user-sql',nowIso:at(2),fixturePermitted:true}); assert.equal(ops.some(x=>x.includes('INSERT INTO super_admin_step_up_audit_events')),true);
  ops=installHarness((sql)=>{ if(sql==='COMMIT') throw new Error('db table connection leaked'); if(sql.includes('SELECT * FROM super_admin_step_up_actor_state')) return [{lockout_until:null}]; return []; }); await assert.rejects(()=>repo.createChallengeAtomically({challengeId:'x',actorUserId:'a',actionKind:'focus_plan_gift',routeScope:'/r',targetUserId:'u',providerKind:'fixture_test_only',requestedAt:at(0),nowIso:at(0),policy,fixturePermitted:true}), StepUpPersistenceError);
  __setDbPoolFactoryForTests(null);
}
