import assert from 'node:assert/strict';
import { __setDbPoolFactoryForTests } from '../db/client';
import { SQLSuperAdminStepUpRepository, StepUpPersistenceError, type StepUpPolicy } from '../persistence/super-admin-step-up-repository';

type Op={index:number; via:'pool'|'client'|'lifecycle'; sql:string; params:unknown[]|undefined; command:string|undefined};
const at=(m:number)=>`2026-05-15T00:${String(m).padStart(2,'0')}:00.000Z`;
const policy:StepUpPolicy={freshnessSeconds:600,challengeExpirySeconds:300,maxAttemptsPerChallenge:5,maxChallengesPerWindow:10,windowSeconds:600,lockoutSeconds:900};
const route='/api/admin/commercial/users/[userId]/gift-focus-plan';
const row=(over:Record<string,unknown>={})=>({challenge_id:'stepup_sql',actor_user_id:'admin-sql',action_kind:'focus_plan_gift',route_scope:route,target_user_id:'user-sql',provider_kind:'fixture_test_only',verified_provider_kind:null,status:'pending',created_at:at(0),expires_at:at(5),verified_at:null,fresh_until:null,failed_attempts:0,last_attempt_at:null,consumed_at:null,lockout_until:null,updated_at:at(0),version:0,...over});
function installHarness(handler:(sql:string,params?:unknown[],op?:Op)=>Record<string,unknown>[]) { const ops:Op[]=[]; let index=0; const push=(op:Omit<Op,'index'>)=>{const next={index:index++,...op}; ops.push(next); return next;}; const client={async query(sql:string,params?:unknown[]){const op=push({via:'client',sql,params,command:['BEGIN','COMMIT','ROLLBACK'].includes(sql)?sql:undefined}); return {rows:handler(sql,params,op)};}, release(){push({via:'lifecycle',sql:'release',params:undefined,command:'release'});}}; __setDbPoolFactoryForTests(()=>({async query(sql:string,params?:unknown[]){const op=push({via:'pool',sql,params,command:undefined}); return {rows:handler(sql,params,op)};}, async connect(){push({via:'lifecycle',sql:'connect',params:undefined,command:'connect'}); return client;}})); return ops; }
const q=(ops:Op[])=>ops.filter(o=>o.via==='client').map(o=>o.command??o.sql);
const auditOps=(ops:Op[])=>ops.filter(o=>o.sql.includes('INSERT INTO super_admin_step_up_audit_events'));
const assertNoPoolQuery=(ops:Op[])=>assert.equal(ops.some(o=>o.via==='pool'),false);
async function expectPersistenceError(fn:()=>Promise<unknown>,ops:Op[]){await assert.rejects(fn,StepUpPersistenceError); assert.equal(ops.some(o=>o.command==='ROLLBACK'),true); assert.equal(ops.some(o=>o.command==='COMMIT'),false);}
async function create(repo:SQLSuperAdminStepUpRepository,over:Partial<Parameters<SQLSuperAdminStepUpRepository['createChallengeAtomically']>[0]>={}){return repo.createChallengeAtomically({challengeId:'stepup_sql',actorUserId:'admin-sql',actionKind:'focus_plan_gift',routeScope:route,targetUserId:'user-sql',providerKind:'fixture_test_only',requestedAt:at(0),nowIso:at(0),policy,fixturePermitted:true,...over});}
async function verify(repo:SQLSuperAdminStepUpRepository,over:Partial<Parameters<SQLSuperAdminStepUpRepository['applyVerificationAttemptAtomically']>[0]>={}){return repo.applyVerificationAttemptAtomically({challengeId:'stepup_sql',actorUserId:'admin-sql',providerKind:'fixture_test_only',nowIso:at(1),disposition:'accepted',policy,...over});}
async function consume(repo:SQLSuperAdminStepUpRepository,over:Partial<Parameters<SQLSuperAdminStepUpRepository['consumeVerifiedChallengeAtomically']>[0]>={}){return repo.consumeVerifiedChallengeAtomically({challengeId:'stepup_sql',actorUserId:'admin-sql',expectedActionKind:'focus_plan_gift',expectedRouteScope:route,expectedTargetUserId:'user-sql',nowIso:at(2),fixturePermitted:true,...over});}
export async function runSuperAdminStepUpSqlRepositoryTests(): Promise<void> {
  const repo=new SQLSuperAdminStepUpRepository();
  let ops=installHarness((sql)=>sql.includes('count(*)')?[{count:'0'}]:sql.includes('SELECT * FROM super_admin_step_up_actor_state')?[{lockout_until:null}]:[]);
  await create(repo);
  assert.deepEqual(q(ops).map(s=>s.includes('INSERT INTO super_admin_step_up_actor_state')?'insert actor':s.includes('FOR UPDATE')?'lock actor':s.includes('count(*)')?'count':s.includes('INSERT INTO super_admin_step_up_challenges')?'insert challenge':s.includes('challenge_created')||s.includes('INSERT INTO super_admin_step_up_audit_events')?'audit':s).filter(s=>['BEGIN','insert actor','lock actor','count','insert challenge','audit','COMMIT'].includes(String(s))),['BEGIN','insert actor','lock actor','count','insert challenge','audit','COMMIT']); assert.equal(ops[ops.length-1]?.command,'release'); assertNoPoolQuery(ops);
  ops=installHarness((sql)=>sql.includes('SELECT * FROM super_admin_step_up_actor_state')?[{lockout_until:at(9)}]:[]); await create(repo); assert.equal(auditOps(ops)[0]!.params?.[12],'step_up_actor_locked');
  ops=installHarness((sql)=>sql.includes('count(*)')?[{count:'10'}]:sql.includes('SELECT * FROM super_admin_step_up_actor_state')?[{lockout_until:null}]:[]); await create(repo); assert.equal(auditOps(ops)[0]!.params?.[12],'step_up_rate_limited');
  ops=installHarness((sql)=>sql.includes('SELECT * FROM super_admin_step_up_actor_state')?[{lockout_until:null}]:sql.includes('SELECT * FROM super_admin_step_up_challenges')?[row()]:[]);
  await verify(repo); assert.equal(ops.findIndex(o=>o.sql.includes('SELECT * FROM super_admin_step_up_actor_state'))<ops.findIndex(o=>o.sql.includes('SELECT * FROM super_admin_step_up_challenges')),true); assert.equal(ops.some(o=>o.sql.includes('SELECT * FROM super_admin_step_up_challenges')&&o.sql.includes('FOR UPDATE')),true); assert.deepEqual(ops.find(o=>o.sql.includes("status='verified'"))?.params,['stepup_sql',at(1),at(11)]); assertNoPoolQuery(ops);
  ops=installHarness((sql)=>sql.includes('SELECT * FROM super_admin_step_up_actor_state')?[{lockout_until:null}]:sql.includes('SELECT * FROM super_admin_step_up_challenges')?[]:[]); await verify(repo,{challengeId:'missing'}); assert.equal(auditOps(ops)[0]!.params?.[2],null); assert.equal(auditOps(ops)[0]!.params?.[6],null); assert.equal(auditOps(ops)[0]!.params?.[10],'verification_unknown_challenge');
  ops=installHarness((sql)=>sql.includes('SELECT * FROM super_admin_step_up_actor_state')?[{lockout_until:null}]:sql.includes('SELECT * FROM super_admin_step_up_challenges')?[row({actor_user_id:'owner-sql'})]:[]); await verify(repo,{actorUserId:'requester-sql'}); assert.equal(auditOps(ops)[0]!.params?.[1],'requester-sql'); assert.equal(auditOps(ops)[0]!.params?.[2],'owner-sql');
  ops=installHarness((sql)=>sql.includes('SELECT * FROM super_admin_step_up_actor_state')?[{lockout_until:null}]:sql.includes('SELECT * FROM super_admin_step_up_challenges')?[row({provider_kind:'totp'})]:[]); await verify(repo,{providerKind:'fixture_test_only'}); assert.equal(auditOps(ops)[0]!.params?.[10],'verification_provider_mismatch');
  ops=installHarness((sql)=>sql.includes('SELECT * FROM super_admin_step_up_actor_state')?[{lockout_until:null}]:sql.includes('SELECT * FROM super_admin_step_up_challenges')?[row({provider_kind:'totp',failed_attempts:3})]:[]); await verify(repo,{providerKind:'totp',disposition:'provider_pending'}); assert.equal(ops.some(o=>o.sql.includes('failed_attempts')),false); assert.equal(auditOps(ops)[0]!.params?.[13],3);
  ops=installHarness((sql)=>sql.includes('SELECT * FROM super_admin_step_up_actor_state')?[{lockout_until:null}]:sql.includes('SELECT * FROM super_admin_step_up_challenges')?[row({failed_attempts:3})]:[]); await verify(repo,{disposition:'fixture_forbidden'}); assert.equal(ops.some(o=>o.sql.includes('failed_attempts')),false); assert.equal(auditOps(ops)[0]!.params?.[13],3);
  ops=installHarness((sql)=>sql.includes('SELECT * FROM super_admin_step_up_actor_state')?[{lockout_until:null}]:sql.includes('SELECT * FROM super_admin_step_up_challenges')?[row({failed_attempts:0})]:[]); await verify(repo,{disposition:'rejected'}); assert.equal(auditOps(ops)[0]!.params?.[10],'verification_failed'); assert.equal(auditOps(ops)[0]!.params?.[13],1);
  ops=installHarness((sql)=>sql.includes('SELECT * FROM super_admin_step_up_actor_state')?[{lockout_until:null}]:sql.includes('SELECT * FROM super_admin_step_up_challenges')?[row({failed_attempts:4})]:[]); await verify(repo,{disposition:'rejected'}); assert.equal(ops.some(o=>o.sql.includes("status='locked'")),true); assert.equal(ops.some(o=>o.sql.includes('UPDATE super_admin_step_up_actor_state SET lockout_until')),true); assert.equal(auditOps(ops)[0]!.params?.[10],'actor_locked'); assert.equal(auditOps(ops)[0]!.params?.[13],5);
  const verified=row({status:'verified',verified_provider_kind:'fixture_test_only',verified_at:at(1),fresh_until:at(11)});
  ops=installHarness((sql)=>sql.includes('SELECT * FROM super_admin_step_up_actor_state')?[{lockout_until:null}]:sql.includes('SELECT * FROM super_admin_step_up_challenges')?[verified]:[]); await consume(repo); assert.equal(ops.some(o=>o.sql.includes('SELECT * FROM super_admin_step_up_challenges WHERE challenge_id=$1')&&!o.sql.includes('FOR UPDATE')),false); assert.equal(ops.findIndex(o=>o.sql.includes('SELECT * FROM super_admin_step_up_actor_state'))<ops.findIndex(o=>o.sql.includes('SELECT * FROM super_admin_step_up_challenges')),true); assert.equal(ops.some(o=>o.sql.includes("status='consumed'")),true);
  for (const [field,over] of [['action',{expectedActionKind:'user_restriction'}],['route',{expectedRouteScope:'/wrong'}],['target',{expectedTargetUserId:'other'}]] as const){ops=installHarness((sql)=>sql.includes('SELECT * FROM super_admin_step_up_actor_state')?[{lockout_until:null}]:sql.includes('SELECT * FROM super_admin_step_up_challenges')?[verified]:[]); await consume(repo,over); assert.equal(ops.some(o=>o.sql.includes("status='consumed'")),false,field);}
  ops=installHarness((sql)=>sql.includes('SELECT * FROM super_admin_step_up_actor_state')?[{lockout_until:null}]:sql.includes('SELECT * FROM super_admin_step_up_challenges')?[row({...verified,fresh_until:at(2)})]:[]); const stale=await consume(repo,{nowIso:at(2)}); assert.equal(stale.status,'expired'); assert.equal(ops.some(o=>o.sql.includes("status='expired'")),true); assert.equal(ops.some(o=>o.sql.includes("status='consumed'")),false);
  ops=installHarness((sql)=>sql.includes('SELECT * FROM super_admin_step_up_actor_state')?[{lockout_until:null}]:sql.includes('SELECT * FROM super_admin_step_up_challenges')?[row({...verified,status:'consumed',consumed_at:at(2)})]:[]); const replay=await consume(repo); assert.equal(replay.status,'denied'); assert.equal(ops.some(o=>o.sql.includes("status='consumed'")),false);
  ops=installHarness((sql)=>sql.includes('SELECT * FROM super_admin_step_up_actor_state')?[{lockout_until:null}]:sql.includes('SELECT * FROM super_admin_step_up_challenges')?[]:[]); await consume(repo,{challengeId:'missing'}); assert.equal(auditOps(ops)[0]!.params?.[10],'consumption_unknown_challenge');
  ops=installHarness((sql)=>{if(sql.includes('INSERT INTO super_admin_step_up_audit_events')) throw new Error('audit down'); if(sql.includes('count(*)')) return [{count:'0'}]; if(sql.includes('SELECT * FROM super_admin_step_up_actor_state')) return [{lockout_until:null}]; return [];}); await expectPersistenceError(()=>create(repo,{challengeId:'audit_create'}),ops);
  ops=installHarness((sql)=>{if(sql.includes('INSERT INTO super_admin_step_up_audit_events')) throw new Error('audit down'); if(sql.includes('SELECT * FROM super_admin_step_up_actor_state')) return [{lockout_until:null}]; if(sql.includes('SELECT * FROM super_admin_step_up_challenges')) return [row()]; return [];}); await expectPersistenceError(()=>verify(repo),ops);
  ops=installHarness((sql)=>{if(sql.includes('INSERT INTO super_admin_step_up_audit_events')) throw new Error('audit down'); if(sql.includes('SELECT * FROM super_admin_step_up_actor_state')) return [{lockout_until:null}]; if(sql.includes('SELECT * FROM super_admin_step_up_challenges')) return [verified]; return [];}); await expectPersistenceError(()=>consume(repo),ops);
  ops=installHarness(()=>{throw new Error('missing relation secret detail');}); const readiness=await repo.getPersistenceReadiness(); assert.equal(readiness.requiredRelationsAvailable,false); assert.equal(readiness.persistenceStatus,'unavailable'); assert.equal(ops.some(o=>o.via==='pool'),true);
  __setDbPoolFactoryForTests(null);
}
