import assert from 'node:assert/strict';
import { buildSuperAdminCommercialAuditEvent, buildSuperAdminStepUpAuditEvent, createSuperAdminStepUpChallenge, evaluateSuperAdminGrantedEntitlement, giftFocusPlanToUser, getSuperAdminCommercialControlCoverageReport, getSuperAdminCommercialRouteScope, getSuperAdminStepUpCoverageReport, getSuperAdminStepUpReadinessReport, retractFocusPlanGift, restrictUserAccount, verifySuperAdminStepUpChallenge } from '../super-admin-commercial-controls/index';
const at = (minute: number) => `2026-05-15T00:${String(minute).padStart(2, '0')}:00.000Z`;
export async function runSuperAdminCommercialControlsCoreTests(): Promise<void> {
  const oldNodeEnv = process.env.NODE_ENV; const oldFixture = process.env.ELCEO_ENABLE_FIXTURE_STEP_UP; process.env.NODE_ENV = 'test'; process.env.ELCEO_ENABLE_FIXTURE_STEP_UP = '1';
  const ch = await createSuperAdminStepUpChallenge({ actorUserId: 'admin-1', actionKind: 'focus_plan_gift', routeScope: getSuperAdminCommercialRouteScope('focus_plan_gift'), targetUserId: 'user-1', providerKind: 'fixture_test_only', requestedAt: at(0) });
  assert.equal(ch.challengeId.startsWith('stepup_'), true);
  const verified = await verifySuperAdminStepUpChallenge({ challengeId: ch.challengeId, providerKind: 'fixture_test_only', actorUserId: 'admin-1', proof: 'fixture-pass', requestedAt: at(1) });
  assert.equal(verified.status, 'verified');
  const forged = await giftFocusPlanToUser({ actorSuperAdminId: 'admin-forged', targetUserId: 'user-forged', duration: 'two_weeks', reasonCode: 'commercial_support', operatorNote: 'forged', stepUpVerification: { status: 'verified', challengeId: null, verifiedAt: null }, idempotencyKey: null, requestedAt: at(2) } as never);
  assert.equal(forged.status, 'blocked');
  const gift = await giftFocusPlanToUser({ actorSuperAdminId: 'admin-1', targetUserId: 'user-1', duration: 'two_weeks', reasonCode: 'commercial_support', operatorNote: 'grant', stepUpChallengeId: ch.challengeId, idempotencyKey: 'id-1', requestedAt: at(2) });
  assert.equal(gift.status, 'success');
  const replayGift = await giftFocusPlanToUser({ actorSuperAdminId: 'admin-1', targetUserId: 'user-1', duration: 'two_weeks', reasonCode: 'commercial_support', operatorNote: 'reuse', stepUpChallengeId: ch.challengeId, idempotencyKey: null, requestedAt: at(3) });
  assert.equal(replayGift.status, 'blocked');

  for (const stepUpChallengeId of [undefined, '', 12]) assert.equal((await giftFocusPlanToUser({ actorSuperAdminId: 'admin-missing', targetUserId: 'user-missing', duration: 'two_weeks', reasonCode: 'commercial_support', operatorNote: 'missing', stepUpChallengeId, idempotencyKey: null, requestedAt: at(3) } as never)).status, 'blocked');
  const retractChallenge = await createSuperAdminStepUpChallenge({ actorUserId: 'admin-1', actionKind: 'focus_plan_gift_retract', routeScope: getSuperAdminCommercialRouteScope('focus_plan_gift_retract'), targetUserId: 'user-1', providerKind: 'fixture_test_only', requestedAt: at(11) }); await verifySuperAdminStepUpChallenge({ challengeId: retractChallenge.challengeId, providerKind: 'fixture_test_only', actorUserId: 'admin-1', proof: 'fixture-pass', requestedAt: at(12) }); assert.equal((await retractFocusPlanGift({ actorSuperAdminId: 'admin-1', targetUserId: 'user-1', giftRecordId: gift.giftRecord!.giftRecordId, reasonCode: 'operator_correction', operatorNote: 'reverse', stepUpChallengeId: retractChallenge.challengeId, idempotencyKey: 'id-retract', requestedAt: at(13) })).status, 'success');
  const restrictChallenge = await createSuperAdminStepUpChallenge({ actorUserId: 'admin-rs', actionKind: 'user_restriction', routeScope: getSuperAdminCommercialRouteScope('user_restriction'), targetUserId: 'user-rs', providerKind: 'fixture_test_only', requestedAt: at(14) }); await verifySuperAdminStepUpChallenge({ challengeId: restrictChallenge.challengeId, providerKind: 'fixture_test_only', actorUserId: 'admin-rs', proof: 'fixture-pass', requestedAt: at(15) }); assert.equal((await restrictUserAccount({ actorSuperAdminId: 'admin-rs', targetUserId: 'user-rs', restrictionKind: 'banned', reasonCode: 'policy_violation', operatorNote: 'ban', stepUpChallengeId: restrictChallenge.challengeId, idempotencyKey: 'id-restrict', requestedAt: at(16) })).status, 'success');
  assert.equal((await restrictUserAccount({ actorSuperAdminId: 'admin-1', targetUserId: 'user-1', restrictionKind: 'banned', reasonCode: 'policy_violation', operatorNote: 'cross-route', stepUpChallengeId: ch.challengeId, idempotencyKey: null, requestedAt: at(17) })).status, 'blocked');
  const giftOnly = await createSuperAdminStepUpChallenge({ actorUserId: 'admin-x', actionKind: 'focus_plan_gift', routeScope: getSuperAdminCommercialRouteScope('focus_plan_gift'), targetUserId: 'user-x', providerKind: 'fixture_test_only', requestedAt: at(18) }); await verifySuperAdminStepUpChallenge({ challengeId: giftOnly.challengeId, providerKind: 'fixture_test_only', actorUserId: 'admin-x', proof: 'fixture-pass', requestedAt: at(19) }); assert.equal((await retractFocusPlanGift({ actorSuperAdminId: 'admin-x', targetUserId: 'user-x', giftRecordId: 'gift-missing', reasonCode: 'operator_correction', operatorNote: 'cross-action', stepUpChallengeId: giftOnly.challengeId, idempotencyKey: null, requestedAt: at(20) })).status, 'blocked');
  const targetChallenge = await createSuperAdminStepUpChallenge({ actorUserId: 'admin-target', actionKind: 'focus_plan_gift', routeScope: getSuperAdminCommercialRouteScope('focus_plan_gift'), targetUserId: 'user-target-1', providerKind: 'fixture_test_only', requestedAt: at(21) }); await verifySuperAdminStepUpChallenge({ challengeId: targetChallenge.challengeId, providerKind: 'fixture_test_only', actorUserId: 'admin-target', proof: 'fixture-pass', requestedAt: at(22) }); assert.equal((await giftFocusPlanToUser({ actorSuperAdminId: 'admin-target', targetUserId: 'user-target-2', duration: 'two_weeks', reasonCode: 'commercial_support', operatorNote: 'wrong-target', stepUpChallengeId: targetChallenge.challengeId, idempotencyKey: null, requestedAt: at(23) })).status, 'blocked'); assert.equal((await giftFocusPlanToUser({ actorSuperAdminId: 'admin-other', targetUserId: 'user-target-1', duration: 'two_weeks', reasonCode: 'commercial_support', operatorNote: 'wrong-actor', stepUpChallengeId: targetChallenge.challengeId, idempotencyKey: null, requestedAt: at(24) })).status, 'blocked');
  const staleChallenge = await createSuperAdminStepUpChallenge({ actorUserId: 'admin-stale', actionKind: 'focus_plan_gift', routeScope: getSuperAdminCommercialRouteScope('focus_plan_gift'), targetUserId: 'user-stale', providerKind: 'fixture_test_only', requestedAt: at(25) }); await verifySuperAdminStepUpChallenge({ challengeId: staleChallenge.challengeId, providerKind: 'fixture_test_only', actorUserId: 'admin-stale', proof: 'fixture-pass', requestedAt: at(26) }); assert.equal((await giftFocusPlanToUser({ actorSuperAdminId: 'admin-stale', targetUserId: 'user-stale', duration: 'two_weeks', reasonCode: 'commercial_support', operatorNote: 'stale', stepUpChallengeId: staleChallenge.challengeId, idempotencyKey: null, requestedAt: '2026-05-15T01:00:00.000Z' })).status, 'blocked');
  const providerMismatch = await createSuperAdminStepUpChallenge({ actorUserId: 'admin-provider', actionKind: 'focus_plan_gift', routeScope: getSuperAdminCommercialRouteScope('focus_plan_gift'), targetUserId: 'user-provider', providerKind: 'totp', requestedAt: at(27) }); assert.equal((await verifySuperAdminStepUpChallenge({ challengeId: providerMismatch.challengeId, providerKind: 'fixture_test_only', actorUserId: 'admin-provider', proof: 'fixture-pass', requestedAt: at(28) })).verified, false);
  const concurrentChallenge = await createSuperAdminStepUpChallenge({ actorUserId: 'admin-con', actionKind: 'focus_plan_gift', routeScope: getSuperAdminCommercialRouteScope('focus_plan_gift'), targetUserId: 'user-con', providerKind: 'fixture_test_only', requestedAt: at(29) }); await verifySuperAdminStepUpChallenge({ challengeId: concurrentChallenge.challengeId, providerKind: 'fixture_test_only', actorUserId: 'admin-con', proof: 'fixture-pass', requestedAt: at(30) }); const [conA, conB] = await Promise.all([giftFocusPlanToUser({ actorSuperAdminId: 'admin-con', targetUserId: 'user-con', duration: 'two_weeks', reasonCode: 'commercial_support', operatorNote: 'a', stepUpChallengeId: concurrentChallenge.challengeId, idempotencyKey: null, requestedAt: at(31) }), giftFocusPlanToUser({ actorSuperAdminId: 'admin-con', targetUserId: 'user-con', duration: 'two_weeks', reasonCode: 'commercial_support', operatorNote: 'b', stepUpChallengeId: concurrentChallenge.challengeId, idempotencyKey: null, requestedAt: at(31) })]); assert.equal([conA.status, conB.status].filter((x)=>x==='success').length, 1);

  const wrong = await createSuperAdminStepUpChallenge({ actorUserId: 'admin-route', actionKind: 'focus_plan_gift', routeScope: '/wrong', targetUserId: 'user-route', providerKind: 'fixture_test_only', requestedAt: at(4) });
  assert.equal((await verifySuperAdminStepUpChallenge({ challengeId: wrong.challengeId, providerKind: 'fixture_test_only', actorUserId: 'admin-route', proof: 'fixture-pass', requestedAt: at(5) })).status, 'verified');
  assert.equal((await giftFocusPlanToUser({ actorSuperAdminId: 'admin-route', targetUserId: 'user-route', duration: 'two_weeks', reasonCode: 'commercial_support', operatorNote: 'wrong route', stepUpChallengeId: wrong.challengeId, idempotencyKey: null, requestedAt: at(6) })).status, 'blocked');
  const pendingProviderChallenge = await createSuperAdminStepUpChallenge({ actorUserId: 'admin-2', actionKind: 'user_restriction', routeScope: getSuperAdminCommercialRouteScope('user_restriction'), targetUserId: 'user-9', providerKind: 'totp', requestedAt: at(7) });
  assert.equal((await verifySuperAdminStepUpChallenge({ challengeId: pendingProviderChallenge.challengeId, providerKind: 'totp', actorUserId: 'admin-2', proof: '111111', requestedAt: at(8) })).status, 'provider_pending');
  assert.equal((await restrictUserAccount({ actorSuperAdminId: 'admin-2', targetUserId: 'user-9', restrictionKind: 'banned', reasonCode: 'policy_violation', operatorNote: 'pending', stepUpChallengeId: pendingProviderChallenge.challengeId, idempotencyKey: null, requestedAt: at(9) })).status, 'blocked');
  process.env.NODE_ENV = 'production'; process.env.ELCEO_ENABLE_FIXTURE_STEP_UP = '1';
  await assert.rejects(() => createSuperAdminStepUpChallenge({ actorUserId: 'admin-prod', actionKind: 'focus_plan_gift', routeScope: getSuperAdminCommercialRouteScope('focus_plan_gift'), targetUserId: 'user-prod', providerKind: 'fixture_test_only', requestedAt: at(10) }));
  process.env.NODE_ENV = 'test'; process.env.ELCEO_ENABLE_FIXTURE_STEP_UP = '1';
  assert.equal(evaluateSuperAdminGrantedEntitlement({ subscriptionActive: true, gift: null, nowIso: '2026-07-20T00:00:00.000Z', restricted: false }), 'focus_plan_active');
  assert.equal(buildSuperAdminCommercialAuditEvent({ actorSuperAdminId: 'admin-1', targetUserId: 'user-3', actionKind: 'user_restriction', reasonCode: 'policy_violation', operatorNote: 'abuse', stepUpStatus: 'verified', createdAt: at(0), resultingEntitlementState: 'restricted', idempotencyKey: 'id-4' }).actionKind, 'user_restriction');
  assert.equal(buildSuperAdminStepUpAuditEvent({ actorUserId: 'admin-1', action: 'focus_plan_gift', targetUserId: 'user-1', challengeId: ch.challengeId, providerKind: 'fixture_test_only', verificationStatus: 'verified', failureReason: null, routeScope: getSuperAdminCommercialRouteScope('focus_plan_gift') }).redactionStatus, 'safe');
  assert.equal(getSuperAdminCommercialControlCoverageReport().ipBanSupported, false);
  assert.equal(getSuperAdminStepUpReadinessReport().find((x) => x.providerKind === 'totp')?.readiness, 'provider_pending');
  assert.equal(getSuperAdminStepUpCoverageReport().persistenceStatus, 'memory_fallback');
  process.env.NODE_ENV = oldNodeEnv; if (oldFixture === undefined) delete process.env.ELCEO_ENABLE_FIXTURE_STEP_UP; else process.env.ELCEO_ENABLE_FIXTURE_STEP_UP = oldFixture;
}
