import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { __setDbPoolFactoryForTests, closeDbPool } from '../db/client';
import { CommercialPersistenceError } from '../persistence/commercial-persistence-error';
import { MemorySuperAdminCommercialRepository, SQLSuperAdminCommercialRepository } from '../persistence/super-admin-commercial-repository';
import { MemorySecurityIdempotencyRepository, MemorySecurityIdempotencyResponseRepository } from '../persistence/security-runtime-repository';
import { SecurityIdempotencyService } from '../security/idempotency-service';
import { MemorySuperAdminStepUpRepository } from '../persistence/super-admin-step-up-repository';
import { SuperAdminStepUpService, getSuperAdminCommercialRouteScope } from '../super-admin-commercial-controls/index';

type Call = { sql: string; params?: unknown[]; clientId: string; order: number };
type Row = Record<string, any>;
const baseGift = { actorSuperAdminId: 'admin', targetUserId: 'target', duration: 'two_weeks' as const, reasonCode: 'commercial_support' as const, operatorNote: 'note', stepUpChallengeId: 'challenge-a', idempotencyKey: 'idem-1', requestedAt: '2026-01-01T00:00:00.000Z' };
const baseRetract = (giftRecordId: string) => ({ actorSuperAdminId: 'admin', targetUserId: 'target', giftRecordId, reasonCode: 'operator_correction' as const, operatorNote: 'retract', stepUpChallengeId: 'challenge-r', idempotencyKey: 'idem-r', requestedAt: '2026-01-02T00:00:00.000Z' });
const baseRestriction = { actorSuperAdminId: 'admin', targetUserId: 'target-r', restrictionKind: 'banned' as const, reasonCode: 'policy_violation' as const, operatorNote: 'restrict', stepUpChallengeId: 'challenge-x', idempotencyKey: 'idem-x', requestedAt: '2026-01-01T00:00:00.000Z' };

export async function runSuperAdminCommercialRepositoryTests() {
  await runMemoryEvidenceTests();
  await runSqlGiftStateMachineTests();
  await runSqlRetractionStateMachineTests();
  await runSqlRestrictionStateMachineTests();
  await runSqlDeterministicConcurrencyTests();
  await runCommercialCommitFinalizationRecoveryTest();
}

async function runMemoryEvidenceTests() {
  const mem = new MemorySuperAdminCommercialRepository();
  const gift = await mem.createFocusPlanGiftAtomically(baseGift); assert.equal(gift.status, 'success', 'memory gift create succeeds');
  assert.equal((await mem.createFocusPlanGiftAtomically(baseGift)).giftRecord?.giftRecordId, gift.giftRecord?.giftRecordId, 'same-key gift replays exact resource');
  assert.equal((await mem.createFocusPlanGiftAtomically({ ...baseGift, duration: 'one_month' })).failureReason, 'idempotency_conflict', 'same key different gift request conflicts');
  assert.equal((await mem.createFocusPlanGiftAtomically({ ...baseGift, idempotencyKey: null, stepUpChallengeId: 'challenge-b' })).failureReason, 'gift_already_active', 'null-key normal path denies duplicate active gift'); assert.ok(mem.getOperationRowsForTests().some((row) => row.idempotencyKey === null && row.target === 'target' && row.stepUpChallengeId === 'challenge-b' && row.status === 'business_denied'), 'null-key request preserves a complete memory operation row');
  const snap = await mem.getControlSnapshot('target', '2026-01-01T00:00:01.000Z'); assert.equal(snap.activeGiftCount, 1, 'snapshot sees active memory gift');
  const retract = await mem.retractFocusPlanGiftAtomically(baseRetract(gift.giftRecord!.giftRecordId)); assert.equal(retract.status, 'success', 'memory retraction succeeds');
  assert.equal((await mem.getControlSnapshot('target', '2026-01-02T00:00:01.000Z')).activeGiftCount, 0, 'retracted gift removed from entitlement snapshot');
  const restrict = await mem.createUserRestrictionAtomically(baseRestriction); assert.equal(restrict.status, 'success', 'memory restriction succeeds');
  const conflict = await mem.createUserRestrictionAtomically({ ...baseRestriction, restrictionKind: 'suspended' }); assert.equal(conflict.failureReason, 'idempotency_conflict'); assert.ok('restrictionRecord' in conflict); assert.equal('giftRecord' in conflict, false, 'restriction idempotency conflict has restriction-shaped result');
  assert.ok(mem.getAuditEventsForTests().some((event) => event.eventKind === 'idempotency_conflict'), 'memory audit records idempotency conflict event'); assert.ok(mem.getTargetStateForTests('target'), 'memory target state updated');

  const rollbackGift = new MemorySuperAdminCommercialRepository(); const beforeGift = await memoryEvidence(rollbackGift, 'target'); rollbackGift.injectFailureAfterResourceMutationForTests(); await assert.rejects(() => rollbackGift.createFocusPlanGiftAtomically({ ...baseGift, idempotencyKey: null }), CommercialPersistenceError); assert.deepEqual(await memoryEvidence(rollbackGift, 'target'), beforeGift, 'gift rollback restores gifts, restrictions, operation rows, events, and target state');
  const rollbackRetract = new MemorySuperAdminCommercialRepository(); const g2 = await rollbackRetract.createFocusPlanGiftAtomically({ ...baseGift, idempotencyKey: null }); const beforeRetract = await memoryEvidence(rollbackRetract, 'target'); rollbackRetract.injectFailureAfterResourceMutationForTests(); await assert.rejects(() => rollbackRetract.retractFocusPlanGiftAtomically({ ...baseRetract(g2.giftRecord!.giftRecordId), idempotencyKey: null }), CommercialPersistenceError); assert.deepEqual(await memoryEvidence(rollbackRetract, 'target'), beforeRetract, 'retraction rollback leaves rows, events, and target version unchanged');
  const rollbackRestriction = new MemorySuperAdminCommercialRepository(); const beforeRestriction = await memoryEvidence(rollbackRestriction, 'target-r'); rollbackRestriction.injectFailureAfterResourceMutationForTests(); await assert.rejects(() => rollbackRestriction.createUserRestrictionAtomically({ ...baseRestriction, idempotencyKey: null }), CommercialPersistenceError); assert.deepEqual(await memoryEvidence(rollbackRestriction, 'target-r'), beforeRestriction, 'restriction rollback restores all five memory stores');
}

async function memoryEvidence(repo: MemorySuperAdminCommercialRepository, target: string) { return { snapshot: await repo.getControlSnapshot(target, '2026-01-02T00:00:01.000Z'), operations: repo.getOperationRowsForTests(), events: repo.getAuditEventsForTests(), targetState: repo.getTargetStateForTests(target) }; }

async function runSqlGiftStateMachineTests() {
  const db = new CommercialSqlHarness(); await withHarness(db, async () => {
    const repo = new SQLSuperAdminCommercialRepository();
    const gift = await repo.createFocusPlanGiftAtomically(baseGift); assert.equal(gift.status, 'success');
    const op = [...db.state.operations.values()][0]!; assert.equal(op.actor_user_id, 'admin'); assert.equal(op.target_user_id, 'target'); assert.equal(op.step_up_challenge_id, 'challenge-a'); assert.equal(op.reason_code, 'commercial_support'); assert.equal(op.operator_note, 'note'); assert.equal(op.gift_id, gift.giftRecord!.giftRecordId);
    const ev = db.state.events[0]!; assert.equal(ev.step_up_challenge_id, 'challenge-a'); assert.equal(ev.resulting_resource_id, gift.giftRecord!.giftRecordId); assert.equal(ev.redaction_status, 'safe');
    assertLockOrder(db, 'INSERT INTO super_admin_commercial_operations', 'SELECT target_user_id FROM super_admin_commercial_target_state', 'INSERT INTO super_admin_focus_plan_gifts');
    const replay = await repo.createFocusPlanGiftAtomically(baseGift); assert.equal(replay.giftRecord?.giftRecordId, gift.giftRecord!.giftRecordId, 'same-key same-request exact replay');
    const changed = await repo.createFocusPlanGiftAtomically({ ...baseGift, duration: 'one_month' }); assert.equal(changed.failureReason, 'idempotency_conflict', 'same-key changed gift conflicts');
    const active = await repo.createFocusPlanGiftAtomically({ ...baseGift, idempotencyKey: 'idem-2', stepUpChallengeId: 'challenge-b' }); assert.equal(active.failureReason, 'gift_already_active', 'active gift denies duplicate');
    const nullKey = await repo.createFocusPlanGiftAtomically({ ...baseGift, idempotencyKey: null, stepUpChallengeId: 'challenge-null' }); assert.equal(nullKey.failureReason, 'gift_already_active'); assert.ok([...db.state.operations.values()].some((r) => r.idempotency_key === null && r.step_up_challenge_id === 'challenge-null'), 'null-idempotency operation row persisted');
    db.state.gifts[0]!.ends_at = '2026-01-03T00:00:00.000Z'; const afterExpiry = await repo.createFocusPlanGiftAtomically({ ...baseGift, requestedAt: '2026-01-03T00:00:00.000Z', idempotencyKey: 'idem-after-expiry', stepUpChallengeId: 'challenge-c' }); assert.equal(afterExpiry.status, 'success', 'now equals endsAt expires previous gift and allows new gift');
  });
  const opFail = new CommercialSqlHarness(); opFail.failOnOperationComplete = true; await withHarness(opFail, async () => { await assert.rejects(() => new SQLSuperAdminCommercialRepository().createFocusPlanGiftAtomically(baseGift), CommercialPersistenceError); assert.equal(opFail.state.gifts.length, 0); assert.equal(opFail.state.operations.size, 0); assert.equal(opFail.state.events.length, 0); assert.equal(opFail.targetVersion('target'), 0); });
  const eventFail = new CommercialSqlHarness(); eventFail.failOnEventInsert = true; await withHarness(eventFail, async () => { await assert.rejects(() => new SQLSuperAdminCommercialRepository().createFocusPlanGiftAtomically(baseGift), CommercialPersistenceError); assert.equal(eventFail.state.gifts.length, 0); assert.equal(eventFail.state.operations.size, 0); assert.equal(eventFail.state.events.length, 0); assert.equal(eventFail.targetVersion('target'), 0); });
}

async function runSqlRetractionStateMachineTests() {
  const db = new CommercialSqlHarness(); await withHarness(db, async () => {
    const first = new SQLSuperAdminCommercialRepository(); const gift = await first.createFocusPlanGiftAtomically(baseGift); const giftId = gift.giftRecord!.giftRecordId;
    const repo = new SQLSuperAdminCommercialRepository(); const missing = await repo.retractFocusPlanGiftAtomically({ ...baseRetract('missing'), idempotencyKey: 'idem-r-missing' }); assert.equal(missing.failureReason, 'gift_not_found');
    db.state.gifts[0]!.status = 'expired'; const inactive = await repo.retractFocusPlanGiftAtomically({ ...baseRetract(giftId), idempotencyKey: 'idem-r-inactive' }); assert.equal(inactive.failureReason, 'gift_not_active');
    db.state.gifts[0]!.status = 'active'; db.state.gifts[0]!.ends_at = '2026-01-02T00:00:00.000Z'; const equalExpired = await repo.retractFocusPlanGiftAtomically({ ...baseRetract(giftId), idempotencyKey: 'idem-r-expired' }); assert.equal(equalExpired.failureReason, 'gift_not_active');
    db.state.gifts[0]!.ends_at = '2026-01-03T00:00:00.000Z'; const retractionStart = db.calls.length; const ok = await repo.retractFocusPlanGiftAtomically(baseRetract(giftId)); assert.equal(ok.status, 'success'); const row = db.state.gifts[0]!; assert.equal(row.retracted_by, 'admin'); assert.equal(row.retraction_reason_code, 'operator_correction'); assert.equal(row.retraction_operator_note, 'retract'); assert.equal(row.retraction_step_up_challenge_id, 'challenge-r'); assert.equal(row.retraction_idempotency_key, 'idem-r'); assert.equal(row.retracted_at, '2026-01-02T00:00:00.000Z'); assert.equal(row.version, 1);
    assertLockOrderFrom(db, retractionStart, 'SELECT target_user_id FROM super_admin_commercial_target_state', 'SELECT * FROM super_admin_focus_plan_gifts WHERE gift_id=$1 AND target_user_id=$2 FOR UPDATE', 'UPDATE super_admin_focus_plan_gifts SET status=');
    const replay = await repo.retractFocusPlanGiftAtomically(baseRetract(giftId)); assert.equal(replay.giftRecord?.giftRecordId, giftId, 'same-key retraction replay'); const conflict = await repo.retractFocusPlanGiftAtomically({ ...baseRetract(giftId), operatorNote: 'different' }); assert.equal(conflict.failureReason, 'idempotency_conflict'); assert.ok('giftRecord' in conflict);
  });
  const fail = new CommercialSqlHarness(); await withHarness(fail, async () => { const repo = new SQLSuperAdminCommercialRepository(); const gift = await repo.createFocusPlanGiftAtomically(baseGift); fail.failOnEventInsert = true; await assert.rejects(() => repo.retractFocusPlanGiftAtomically(baseRetract(gift.giftRecord!.giftRecordId)), CommercialPersistenceError); assert.equal(fail.state.gifts[0]!.status, 'active'); assert.equal(fail.state.events.length, 1); });
}

async function runSqlRestrictionStateMachineTests() {
  const db = new CommercialSqlHarness(); await withHarness(db, async () => {
    const repo = new SQLSuperAdminCommercialRepository(); const r = await repo.createUserRestrictionAtomically(baseRestriction); assert.equal(r.status, 'success'); assert.equal(db.state.restrictions.length, 1); assertLockOrder(db, 'INSERT INTO super_admin_commercial_operations', 'SELECT target_user_id FROM super_admin_commercial_target_state', 'INSERT INTO super_admin_user_restrictions');
    const replay = await repo.createUserRestrictionAtomically(baseRestriction); assert.equal(replay.restrictionRecord?.restrictionRecordId, r.restrictionRecord!.restrictionRecordId); const changed = await repo.createUserRestrictionAtomically({ ...baseRestriction, restrictionKind: 'suspended' }); assert.equal(changed.failureReason, 'idempotency_conflict'); assert.equal(changed.restrictionRecord, null); assert.equal('giftRecord' in changed, false); assert.equal(changed.resultingEntitlementState, 'restricted');
    const dup = await repo.createUserRestrictionAtomically({ ...baseRestriction, idempotencyKey: 'idem-y', stepUpChallengeId: 'challenge-y' }); assert.equal(dup.failureReason, 'restriction_already_active');
  });
  const fail = new CommercialSqlHarness(); fail.failOnOperationComplete = true; await withHarness(fail, async () => { await assert.rejects(() => new SQLSuperAdminCommercialRepository().createUserRestrictionAtomically(baseRestriction), CommercialPersistenceError); assert.equal(fail.state.restrictions.length, 0); assert.equal(fail.state.operations.size, 0); assert.equal(fail.state.events.length, 0); assert.equal(fail.targetVersion('target-r'), 0); });
}

async function runSqlDeterministicConcurrencyTests() {
  await withHarness(new CommercialSqlHarness(), async () => { const repo = new SQLSuperAdminCommercialRepository(); const [a, b] = await Promise.all([repo.createFocusPlanGiftAtomically({ ...baseGift, idempotencyKey: 'cg-a' }), repo.createFocusPlanGiftAtomically({ ...baseGift, idempotencyKey: 'cg-b', stepUpChallengeId: 'challenge-b' })]); assert.equal([a.status, b.status].filter((s) => s === 'success').length, 1); assert.equal([a.failureReason, b.failureReason].filter((s) => s === 'gift_already_active').length, 1); });
  await withHarness(new CommercialSqlHarness(), async () => { const repo = new SQLSuperAdminCommercialRepository(); const g = await repo.createFocusPlanGiftAtomically(baseGift); const [a, b] = await Promise.all([repo.retractFocusPlanGiftAtomically({ ...baseRetract(g.giftRecord!.giftRecordId), idempotencyKey: 'cr-a' }), repo.retractFocusPlanGiftAtomically({ ...baseRetract(g.giftRecord!.giftRecordId), idempotencyKey: 'cr-b', stepUpChallengeId: 'challenge-r2' })]); assert.equal([a.status, b.status].filter((s) => s === 'success').length, 1); assert.equal([a.failureReason, b.failureReason].filter((s) => s === 'gift_not_active').length, 1); });
  await withHarness(new CommercialSqlHarness(), async () => { const repo = new SQLSuperAdminCommercialRepository(); const [a, b] = await Promise.all([repo.createUserRestrictionAtomically({ ...baseRestriction, idempotencyKey: 'sr-a' }), repo.createUserRestrictionAtomically({ ...baseRestriction, idempotencyKey: 'sr-b', stepUpChallengeId: 'challenge-s2' })]); assert.equal([a.status, b.status].filter((s) => s === 'success').length, 1); assert.equal([a.failureReason, b.failureReason].filter((s) => s === 'restriction_already_active').length, 1); });
}


async function runCommercialCommitFinalizationRecoveryTest() {
  const oldFixture = process.env.ELCEO_ENABLE_FIXTURE_STEP_UP; process.env.ELCEO_ENABLE_FIXTURE_STEP_UP = '1';
  const idRepo = new MemorySecurityIdempotencyRepository(); const responseRepo = new MemorySecurityIdempotencyResponseRepository(); const idSvc = new SecurityIdempotencyService(idRepo, responseRepo);
  const stepRepo = new MemorySuperAdminStepUpRepository(); const stepSvc = new SuperAdminStepUpService(stepRepo, { challengeId: () => `stepup-${stepIds.shift()}` }); const stepIds = ['one', 'two', 'three'];
  const commercial = new MemorySuperAdminCommercialRepository(); const requestHash = sha('actor=admin;action=gift;target=recovery;duration=two_weeks;reason=commercial_support;note=recovery');
  const begin = await idSvc.beginIdempotentAction({ actionKind: 'admin_write', actorKind: 'admin', actorId: 'admin', idempotencyKey: 'outer-recovery', requestHash, nowIso: '2026-01-01T00:00:00.000Z' }); assert.equal(begin.status, 'allowed');
  const ch1 = await stepSvc.createChallenge({ actorUserId: 'admin', actionKind: 'focus_plan_gift', routeScope: getSuperAdminCommercialRouteScope('focus_plan_gift'), targetUserId: 'recovery', providerKind: 'fixture_test_only', requestedAt: '2026-01-01T00:00:01.000Z' }); await stepSvc.verify({ challengeId: ch1.challengeId, providerKind: 'fixture_test_only', actorUserId: 'admin', proof: 'fixture-pass', requestedAt: '2026-01-01T00:00:02.000Z' });
  await stepSvc.consume({ challengeId: ch1.challengeId, actorUserId: 'admin', expectedActionKind: 'focus_plan_gift', expectedRouteScope: getSuperAdminCommercialRouteScope('focus_plan_gift'), expectedTargetUserId: 'recovery', nowIso: '2026-01-01T00:00:03.000Z' });
  const first = await commercial.createFocusPlanGiftAtomically({ ...baseGift, targetUserId: 'recovery', stepUpChallengeId: ch1.challengeId, idempotencyKey: 'inner-recovery', requestedAt: '2026-01-01T00:00:03.000Z' }); assert.equal(first.status, 'success'); assert.equal((await stepRepo.getChallengeById(ch1.challengeId))?.status, 'consumed'); assert.equal(commercial.getOperationRowsForTests().filter((row) => row.status === 'completed').length, 1);
  await idSvc.failIdempotentAction({ idempotencyKey: 'outer-recovery', nowIso: '2026-01-01T00:00:04.000Z', metadata: { reason: 'response_finalization_failed' } });
  const ch2 = await stepSvc.createChallenge({ actorUserId: 'admin', actionKind: 'focus_plan_gift', routeScope: getSuperAdminCommercialRouteScope('focus_plan_gift'), targetUserId: 'recovery', providerKind: 'fixture_test_only', requestedAt: '2026-01-01T00:00:05.000Z' }); await stepSvc.verify({ challengeId: ch2.challengeId, providerKind: 'fixture_test_only', actorUserId: 'admin', proof: 'fixture-pass', requestedAt: '2026-01-01T00:00:06.000Z' });
  const [retryA, retryB] = await Promise.all([idSvc.beginIdempotentAction({ actionKind: 'admin_write', actorKind: 'admin', actorId: 'admin', idempotencyKey: 'outer-recovery', requestHash, nowIso: '2026-01-01T00:00:07.000Z' }), idSvc.beginIdempotentAction({ actionKind: 'admin_write', actorKind: 'admin', actorId: 'admin', idempotencyKey: 'outer-recovery', requestHash, nowIso: '2026-01-01T00:00:07.001Z' })]);
  assert.equal([retryA, retryB].filter((r) => r.status === 'allowed').length, 1, 'one outer retry restarts'); assert.equal([retryA, retryB].filter((r) => r.blockReason === 'idempotency_conflict').length, 1, 'one concurrent outer retry conflicts');
  await stepSvc.consume({ challengeId: ch2.challengeId, actorUserId: 'admin', expectedActionKind: 'focus_plan_gift', expectedRouteScope: getSuperAdminCommercialRouteScope('focus_plan_gift'), expectedTargetUserId: 'recovery', nowIso: '2026-01-01T00:00:08.000Z' });
  const replay = await commercial.createFocusPlanGiftAtomically({ ...baseGift, targetUserId: 'recovery', stepUpChallengeId: ch2.challengeId, idempotencyKey: 'inner-recovery', requestedAt: '2026-01-01T00:00:08.000Z' }); assert.equal(replay.giftRecord?.giftRecordId, first.giftRecord!.giftRecordId); assert.equal((await commercial.getControlSnapshot('recovery', '2026-01-01T00:00:09.000Z')).activeGiftCount, 1); assert.equal(commercial.getOperationRowsForTests().filter((row) => row.status === 'completed').length, 1); assert.equal((await stepRepo.getChallengeById(ch2.challengeId))?.status, 'consumed');
  await idSvc.completeIdempotentActionWithResponse({ idempotencyKey: 'outer-recovery', actionKind: 'admin_write', actorKind: 'admin', actorId: 'admin', requestHash, httpStatus: 200, responseJson: JSON.stringify(replay), responseHash: sha(JSON.stringify(replay)), completedAt: '2026-01-01T00:00:09.000Z' }); assert.equal((await idSvc.getReplayForIdempotencyKey({ idempotencyKey: 'outer-recovery', requestHash, asOfIso: '2026-01-01T00:00:10.000Z' })).replayable, true); if (oldFixture === undefined) delete process.env.ELCEO_ENABLE_FIXTURE_STEP_UP; else process.env.ELCEO_ENABLE_FIXTURE_STEP_UP = oldFixture;
}
function sha(value: string) { return createHash('sha256').update(value).digest('hex'); }

async function withHarness(db: CommercialSqlHarness, fn: () => Promise<void>) { __setDbPoolFactoryForTests(() => db.pool() as any); try { await fn(); } finally { await closeDbPool(); __setDbPoolFactoryForTests(null); } }
function assertLockOrder(db: CommercialSqlHarness, ...prefixes: string[]) { assertLockOrderFrom(db, 0, ...prefixes); }
function assertLockOrderFrom(db: CommercialSqlHarness, start: number, ...prefixes: string[]) { const calls = db.calls.slice(start); const order = prefixes.map((p) => calls.findIndex((c) => c.sql.startsWith(p))); for (const index of order) assert.notEqual(index, -1, `missing SQL prefix ${prefixes[order.indexOf(index)]!}`); for (let i = 1; i < order.length; i++) assert.ok(order[i - 1]! < order[i]!, `${prefixes[i - 1]!} must precede ${prefixes[i]!}`); }

class CommercialSqlHarness {
  calls: Call[] = []; releases = 0; failOnOperationComplete = false; failOnEventInsert = false; private nextClient = 0; state = this.empty(); private snapshots: ReturnType<CommercialSqlHarness['empty']>[] = []; private locks = new Map<string, string>(); private waiters = new Map<string, Array<() => void>>();
  empty() { return { gifts: [] as Row[], restrictions: [] as Row[], operations: new Map<string, Row>(), events: [] as Row[], targets: new Map<string, Row>() }; }
  cloneState() { return { gifts: structuredClone(this.state.gifts), restrictions: structuredClone(this.state.restrictions), operations: new Map([...this.state.operations].map(([k, v]) => [k, structuredClone(v)])), events: structuredClone(this.state.events), targets: new Map([...this.state.targets].map(([k, v]) => [k, structuredClone(v)])) }; }
  targetVersion(target: string) { return this.state.targets.get(target)?.version ?? 0; }
  pool() { return { query: async (sql: string, params?: unknown[]) => this.query('pool', sql, params), connect: async () => { const id = `client-${++this.nextClient}`; return { query: async (sql: string, params?: unknown[]) => this.query(id, sql, params), release: () => { this.releases++; this.calls.push({ sql: 'RELEASE', clientId: id, order: this.calls.length }); } }; }, end: async () => undefined }; }
  async query(clientId: string, sql: string, params: unknown[] = []) { this.calls.push({ sql, params, clientId, order: this.calls.length }); if (sql === 'BEGIN') { this.snapshots.push(this.cloneState()); return { rows: [] }; } if (sql === 'COMMIT') { this.snapshots.pop(); this.releaseLocks(clientId); return { rows: [] }; } if (sql === 'ROLLBACK') { const snap = this.snapshots.pop(); if (snap) this.state = snap; this.releaseLocks(clientId); return { rows: [] }; }
    if (sql.startsWith('INSERT INTO super_admin_commercial_operations') && params.length === 11) { const [operation_id, action_kind, actor_user_id, target_user_id, step_up_challenge_id, idempotency_key, request_hash, reason_code, operator_note, requested_resource_id, created_at] = params; if (!idempotency_key || ![...this.state.operations.values()].some((r) => r.actor_user_id === actor_user_id && r.action_kind === action_kind && r.idempotency_key === idempotency_key)) this.state.operations.set(String(operation_id), { operation_id, action_kind, actor_user_id, target_user_id, step_up_challenge_id, idempotency_key, request_hash, reason_code, operator_note, requested_resource_id, operation_status: 'pending', resulting_entitlement_state: 'subscription_required', response_json: {}, created_at, version: 0 }); return { rows: [] }; }
    if (sql.startsWith('SELECT * FROM super_admin_commercial_operations')) return { rows: [[...this.state.operations.values()].find((r) => r.actor_user_id === params[0] && r.action_kind === params[1] && r.idempotency_key === params[2])].filter(Boolean) as Row[] };
    if (sql.startsWith('INSERT INTO super_admin_commercial_target_state')) { const [target_user_id, updated_at] = params; if (!this.state.targets.has(String(target_user_id))) this.state.targets.set(String(target_user_id), { target_user_id, updated_at, version: 0 }); return { rows: [] }; }
    if (sql.startsWith('SELECT target_user_id FROM super_admin_commercial_target_state')) { await this.acquireLock(String(params[0]), clientId); return { rows: [this.state.targets.get(String(params[0]))].filter(Boolean) as Row[] }; }
    if (sql.startsWith('UPDATE super_admin_focus_plan_gifts SET status=\'expired\'')) { for (const gift of this.state.gifts) if (gift.target_user_id === params[0] && gift.status === 'active' && Date.parse(gift.ends_at) <= Date.parse(String(params[1]))) { gift.status = 'expired'; gift.updated_at = params[1]; gift.version++; } return { rows: [] }; }
    if (sql.startsWith('SELECT * FROM super_admin_focus_plan_gifts WHERE target_user_id')) return { rows: this.state.gifts.filter((g) => g.target_user_id === params[0] && g.status === 'active' && Date.parse(g.ends_at) > Date.parse(String(params[1]))).sort((a, b) => String(b.created_at).localeCompare(String(a.created_at)) || String(b.gift_id).localeCompare(String(a.gift_id))).slice(0, 1) };
    if (sql.startsWith('INSERT INTO super_admin_focus_plan_gifts')) { const [gift_id, target_user_id, actor_user_id, duration, starts_at, ends_at, operator_note, reason_code, step_up_challenge_id, idempotency_key] = params; this.state.gifts.push({ gift_id, target_user_id, actor_user_id, status: 'active', duration, starts_at, ends_at, operator_note, created_at: starts_at, updated_at: starts_at, plan_code: 'focus_plan', reason_code, step_up_challenge_id, idempotency_key, version: 0 }); return { rows: [] }; }
    if (sql.startsWith('SELECT * FROM super_admin_focus_plan_gifts WHERE gift_id=$1 AND target_user_id=$2')) return { rows: [this.state.gifts.find((g) => g.gift_id === params[0] && g.target_user_id === params[1])].filter(Boolean) as Row[] };
    if (sql.startsWith('UPDATE super_admin_focus_plan_gifts SET status=\'retracted\'')) { const gift = this.state.gifts.find((g) => g.gift_id === params[6]); if (gift) Object.assign(gift, { status: 'retracted', retracted_at: params[0], retracted_by: params[1], retraction_reason_code: params[2], retraction_operator_note: params[3], retraction_step_up_challenge_id: params[4], retraction_idempotency_key: params[5], updated_at: params[0], version: gift.version + 1 }); return { rows: [] }; }
    if (sql.startsWith('SELECT * FROM super_admin_user_restrictions')) return { rows: this.state.restrictions.filter((r) => r.target_user_id === params[0] && r.status === 'active').slice(0, 1) };
    if (sql.startsWith('INSERT INTO super_admin_user_restrictions')) { const [restriction_id, target_user_id, actor_user_id, restriction_kind, reason, operator_note, created_at, step_up_challenge_id, idempotency_key] = params; this.state.restrictions.push({ restriction_id, target_user_id, actor_user_id, restriction_kind, status: 'active', reason, operator_note, created_at, updated_at: created_at, step_up_challenge_id, idempotency_key, version: 0 }); return { rows: [] }; }
    if (sql.startsWith('INSERT INTO super_admin_commercial_operations') && params.length === 17) { if (this.failOnOperationComplete) throw new Error('operation completion failed'); const [operation_id, action_kind, actor_user_id, target_user_id, step_up_challenge_id, idempotency_key, request_hash, reason_code, operator_note, requested_resource_id, operation_status, failure_reason, gift_id, restriction_id, resulting_entitlement_state, response_json, now] = params; this.state.operations.set(String(operation_id), { operation_id, action_kind, actor_user_id, target_user_id, step_up_challenge_id, idempotency_key, request_hash, reason_code, operator_note, requested_resource_id, operation_status, failure_reason, gift_id, restriction_id, resulting_entitlement_state, response_json: JSON.parse(String(response_json)), created_at: now, completed_at: now, version: (this.state.operations.get(String(operation_id))?.version ?? -1) + 1 }); return { rows: [] }; }
    if (sql.startsWith('INSERT INTO super_admin_commercial_operation_events')) { if (this.failOnEventInsert) throw new Error('event insertion failed'); const [event_id, operation_id, actor_user_id, target_user_id, action_kind, idempotency_key, request_hash, step_up_challenge_id, event_kind, outcome, failure_reason, reason_code, operator_note, requested_resource_id, resulting_resource_id, occurred_at] = params; this.state.events.push({ event_id, operation_id, actor_user_id, target_user_id, action_kind, idempotency_key, request_hash, step_up_challenge_id, event_kind, outcome, failure_reason, reason_code, operator_note, requested_resource_id, resulting_resource_id, occurred_at, redaction_status: 'safe' }); return { rows: [] }; }
    if (sql.startsWith('UPDATE super_admin_commercial_target_state SET')) { const row = this.state.targets.get(String(params[0])); if (row) { row.updated_at = params[1]; row.version++; } return { rows: [] }; }
    if (sql.includes('super_admin_commercial_operation_events') || sql.includes('LIMIT 0')) return { rows: [] };
    if (sql.startsWith('WITH active_gifts')) return { rows: [{ gift_count: 0, restriction_count: 0, gift: null, restriction: null }] };
    throw new Error(`unhandled SQL: ${sql}`);
  }
  private async acquireLock(target: string, clientId: string) {
    while (this.locks.has(target) && this.locks.get(target) !== clientId) await new Promise<void>((resolve) => { const list = this.waiters.get(target) ?? []; list.push(resolve); this.waiters.set(target, list); });
    this.locks.set(target, clientId);
  }
  private releaseLocks(clientId: string) {
    for (const [target, holder] of [...this.locks]) {
      if (holder === clientId) { this.locks.delete(target); for (const resolve of this.waiters.get(target) ?? []) resolve(); this.waiters.delete(target); }
    }
  }
}
